### PR TITLE
[WIP] provider/azurerm: create app_gateway resource

### PR DESCRIPTION
**Pull request by pmcatominey**
Todo:
- [ ]  Fix Create failing with status 200 error
- [ ]  Add import test
- [ ]  Documentation

### CODE REVIEW

**Comment by bpoland** [comment]
Would be great to see this resource added -- does anyone know when this will get merged?

**Comment by retheshnair** [comment]
@stack72 Any help on this will be appreciated

**Comment by choppedpork** [comment]
This is amazing @pmcatominey - thanks a lot! I've built terraform from your branch and haven't ran into any problems (using the unit test as documentation... :) - would be great to see this merged.

**Comment by benkoller** [comment]
Great work, a merge of this would be terrific!

**Comment by gyoza** [comment]
Anybody know any if or if not this will get merged into terraform?

**Comment by brandontosch** [comment]
I'm trying to jump on this to revive it, just been trying to find the time. Things have changed a bit since November of last year (when this was opened) so there was a little refactoring to do. Have it mostly working now so hopefully not much longer.

**Comment by blucas-accela** [comment]
+1

**Comment by dominik-lekse** [comment]
@brandontosch Is it possible to publish your draft as WIP pull request?

**Comment by brandontosch** [comment]
@dominik-lekse Sorry for the delay, been swamped. Opened up WIP PR #14426

**Comment by pmcatominey** [comment]
Superseded by #14426.

**Pull request closed without merging**
