### PR TITLE
Changes to address #12552

### PR DESCRIPTION
**Pull request by jzampieron**
The documentation for the Azure API clearly says that the use should provide a base64 encoded string. This is reflected in the provider documentation for a virtual machine.

Change from a computed value to a straight encoded string.
Reference Issue #12552

### CODE REVIEW

**Comment by jzampieron** [comment]
I'm not sure this is the best fix for the password part of the issue. It looks like `SchemaStateFunc` is unsupported, so I used a `SchemaDiffSuppressFunc` instead. Looking for feedback.

**Comment by sethvargo** [comment]
Hey @jzampieron 

Thank you for the Pull Request. I'm the original author of #12552, and I wanted to follow up directly. 

> The documentation for the Azure API clearly says that the use should provide a base64 encoded string.

This is correct, and 12552 makes that possible. Prior to 12552, users had to manually base64 encode custom_data using Terraform's `base64` function. That means you had to write this:

```hcl
resource "azure_virtual_machine" "test" {
  custom_data = "${base64(file("whatever"))}"
}
```

The double-nesting and double-quoting got weird, and that API does not match how other cloud providers (i.e. AWS and Google) behave. We let the user supply plain-text and Terraform does the encoding for you.

```hcl
resource "azure_virtual_machine" "test" {
  custom_data = "${file("whatever")}"
}
```

In all providers, including Azure, this change is pre-detected and idempotent. If you supply base64-encoded data, we do not re-encode it. If you supply plain-text, we automatically base64 encode it. The API only ever receives base64-encoded data.

This is separate from what is stored in the state file. In the statefile, we store the base64 encoded data in the statefile to diff against. This helps reduce the verbosity of the `terraform plan` and `terraform apply` output, and also helps in the diffing output during changes.

I'd like to hear a bit more about the problem you are experiencing and the misbehavior your might be seeing.

**Comment by jzampieron** [comment]
The fundamental problem is simple to reproduce:
1. Deploy an azure system with a couple of VMs and a network and public IPs w/ `terraform apply`
2. Run `terraform plan` immediately after. Notice that terraform will try to redeploy the VMs even though the configuration hasn't changed at all.

I isolated this down to the `password` field and the `custom_data` field, as discussed above. 

At the very least, the documentation for the `custom_data` field on the website needs to reflect that the string is encoded for you (as you described). As it stands now, a dev would assume they need to call that `base64encode` function to comply with the requirements. 

Thanks.

If you have a better fix, I'll dump the PR. No big deal.

**Comment by sethvargo** [comment]
Hi @jzampieron 

We'll update the docs on release. The behavior shouldn't change though; if you b64 the data yourself, it won't be b64 encoded again.

I'm not able to reproduce this using my configuration (https://github.com/sethvargo/terraform-azure-webinar-demo). I see a few uses of `uuid` in your configuration without the lifecycle hook to ignore changes. Could that be affecting this?

**Comment by apparentlymart** [comment]
Hello @jzampieron, and thanks for working on this!

As part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it.

If this change is still needed and you or someone else has the time and motivation to apply the same changes to [the `azurerm` provider repository](https://github.com/terraform-providers/terraform-provider-azurerm) and open a new PR there, the maintainers of that provider should be able to review it.

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Pull request closed without merging**
