### PR TITLE
backend/s3: Adds nested attribute for `assume_role`

### LINKED ISSUE #30495: backend/s3: Move assume role parameters to block
The assume role parameters are currently at the root level.

1. Add block `assume_role` with
  * `duration` of type duration
  * `external_id`
  * `policy`
  * `policy_arns`
  * `role_arn` (required)
  * `session_name`
  * `tags`
  * `transitive_tag_keys`
2. Deprecate
  * `role_arn`
  * `session_name`
  * `external_id`
  * `assume_role_duration_seconds`
  * `assume_role_policy`
  * `assume_role_policy_arns`
  * `assume_role_tags`
  * `assume_role_transitive_tag_keys`

### PR DESCRIPTION
**Pull request by gdavison**
Adds a nested attribute `assume_role` for all arguments related to assuming an IAM role. Deprecates arguments related to assuming role at top level.

Related #30443
Closes #30495

## Target Release

1.6.0

###  ENHANCEMENTS

- backend/s3: Moves arguments related to assuming IAM role to nested attribute `assume_role`
- backend/s3: Deprecates the arguments `role_arn`, `session_name`, `external_id`, `assume_role_duration_seconds`, `assume_role_policy`, `assume_role_policy_arns`, `assume_role_tags`, and `assume_role_transitive_tag_keys`

### CODE REVIEW

**Review by jar-b — APPROVED** [review]
LGTM 👍 

```console
$ TF_ACC=1 go test -count=1 ./internal/backend/remote-state/s3/...
ok      github.com/hashicorp/terraform/internal/backend/remote-state/s3 171.348s
```

**Comment by Nuru** [comment]
This is a breaking change. IMHO this does not provide enough benefits to be worth a breaking change. Why is this important?

**Comment by gdavison** [comment]
Hi @Nuru. The top-level parameters are being deprecated, not removed, so they will still work. That isn't my understanding of a breaking change. Could you explain your perspective more, please?

The benefit in this case is to have configuration parity with the [AWS Provider](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)

**Comment by Nuru** [comment]
@gdavison "deprecated" is the step before "removed". Usually "deprecated" means "will be removed in the next major release". Additionally, people complain about deprecation warnings and want the underlying cause fixed. It ends up being a lot of work, especially on something as widely used as the S3 backend.

If you were adding a new capability or removing something that does not work anymore, that would be a good reason for such a change. Changing things to look more like the AWS provider, especially when you are not providing full feature parity, does not seem worth the disruption to me.

**Comment by gdavison** [comment]
@Nuru we are planning for feature parity for authentication and configuration. The issue #33687 details the changes that we will be making.

**Pull request merged**
