### PR TITLE
terraform test: parse global variables without looking for config reference

### LINKED ISSUE #35005: terraform test command does not honor TF_VAR_* environment variables when "module" is specified after 1.8.0
### Terraform Version

```shell
Terraform v1.8.0
on linux_amd64
```

### Terraform Configuration Files

a dummy module, with a test, and a module used by the test:

main.tf:
```hcl
resource null_resource foo {}
```

foo/main.tf:
```hcl
variable "foo" {}
output "foo" {
    value = var.foo
}
```

foo.tftest.hcl:
```hcl
run "foo" {
    module {
        source = "./foo"
    }
}
```

### Debug Output

cannot post publicly.

### Expected Behavior

```bash
$ TF_VAR_foo=something terraform test
foo.tftest.hcl... in progress
  run "foo"... pass
foo.tftest.hcl... tearing down
foo.tftest.hcl... pass

Success! 1 passed, 0 failed.
```

### Actual Behavior

```bash
$ TF_VAR_foo=something terraform test
foo.tftest.hcl... in progress
  run "foo"... fail
╷
│ Error: Required variable not set
│ 
│   on foo/main.tf line 1:
│    1: variable "foo" {}
│ 
│ The variable "foo" is required, but is not set.
╵
foo.tftest.hcl... tearing down
foo.tftest.hcl... fail
Failure! 0 passed, 1 failed.
```

### Steps to Reproduce

```bash
TF_VAR_foo=something terraform test
```

### Additional Context

this does not happen on 1.7.x terraform versions. This also only seems to happen for tests with a custom module, ie:
```hcl
run {
  module {
    source = "./a-custom-module"
  }
}
```

### References

_No response_

### PR DESCRIPTION
**Pull request by liamcervante**
This PR updates the global variable parsing during Terraform Test to attempt to parse the variable as both HCL and as a literal string. 

Previously, we looked into the main configuration to see if we could find a `variable` block providing a type for the specified variable that could allow us to make a decision about which parsing mode to use. This meant that variables that were not defined in the main configuration would always default to HCL parsing mode, which broke the behaviour for parsing strings from environment variables or the CLI.

Now, we always try to parse the input as HCL first, ensuring we capture any non-string types. For variables that are defined purely as strings the HCL mode will fail, and we'll fall back to just interpreting the input as a literal string. 

Fixes #35005 

## Target Release

1.8.1

### BUG FIXES

 

-  `terraform test`: Fix bug preventing global variables propagating into testing modules.

### CODE REVIEW

**Review by DanielMSchmidt — APPROVED** [review]
Makes sense to me 👍

**Review by apparentlymart — COMMENTED** [review]
This seems ambiguous for values that would be valid in both modes. For example, `true` for a `type = string` variable is supposed to produce `"true"` (the string) rather than `true` (the boolean value). Resolving that ambiguity was, of course, the purpose of the existing rule.

Is there some way we can allow an author to declare the type of a variable in this context so that there's at least the option of unambiguous behavior here? That would be consistent with the normal handling of input variables if we assume that a variable that lacks such a declaration is `type = any`, which is effectively what we do already for variables that don't have a `type` explicitly set in the configuration.

**Comment by liamcervante** [comment]
> Is there some way we can allow an author to declare the type of a variable in this context so that there's at least the option of unambiguous behavior here?

Unfortunately not in a way that wouldn't be a breaking change. We could introduce a `variable` block within the test files, and say that anything referenced within the tests needs to be defined within a variable block. This would break workflows for anyone already providing global variables. This has evolved from a time when you could only reference variables directly within run blocks (when you always have a type definition from the underlying configuration). We always used to defer parsing the variables until the run blocks as a way of getting as much information as possible.

Maybe we could introduce the `variable` blocks optionally? Users can then provide context if they want to disambiguate.


The other option would be to lean into the old approach a bit more. This is more complicated, but essentially we defer all processing of variables, even the file level values, until the run block. The problem then is you have the behaviour of the variables potentially changing based on the run block they are used in. If two run blocks have underlying variables with the same name but different types the variable behaviour will change between run blocks. But, maybe that's preferable to the ambiguity in the short term and I can talk to Omar/Garvita in the long term about optional variable blocks for 1.9 or later.

**Comment by apparentlymart** [comment]
I think optional variable declarations is one way to interpret the idea I was describing at the end of my comment. To make that more concrete:

We could allow `variable` blocks in the tftest files with the same structure they would have in a normal Terraform module. When present, they get treated in the same way as the ones in a normal module.

As a special case for the test language in particular, we could treat any undeclared variable as if it implies a declaration like the following: 

```hcl
variable "example" {}
```

This declaration doesn't specify a type constraint, and so the type constraint in turn defaults to `any`.

That means then that an environment variable defining this variable would always be interpreted as HCL expression syntax, because that's how we treat `any`.

Someone who wants the raw interpretation as a string would then opt in to that by writing an explicit declaration using `type = string`, which would then be treated the same way as such a declaration in a module.

Does that seem plausible, or did I misunderstand the existing behavior that this needs to preserve compatibility with?

**Comment by liamcervante** [comment]
> Does that seem plausible

Yeah, that sounds good to me! I'll chat to Omar and Garvita about this as I don't think we can introduce it in a patch release. We'd need to wait for the next minor release. 

We'd still need some short term fix for this at moment, as there was a definite unintended breaking change here. Potentially the alternate idea I had is better in the short term as it doesn't introduce any kind of ambiguity.

**Comment by apparentlymart** [comment]
I think I'm not fully understanding what the old behavior was that we are trying to restore. :thinking: 

I see in the removed code in this diff that previously `getGlobalVariable` was unconditionally using the HCL parsing mode. If we did what I described in my previous comment then that would still be the default if no `variable` block was present. So if interpreting these variable values as HCL is the break that we're trying to repair here then what I previously proposed would presumably not repair it, because anyone wanting the raw string parsing approach would still need to modify their test scenarios to include the explicit variable declaration.

If the previous behavior that you were intending to restore was that it was previously somehow defaulting to the raw string parsing mode, then I think my previous idea would need to be modified so that the implied declaration for an undeclared variable would instead be:

```
variable "example" {
  type = string
}
```

...which would mean that anyone wanting to set a non-string variable would need to add an input variable declaration to specify the type they want, but would otherwise have the same characteristics as what I previously described.

Whichever way we approach it, I would imagine that the small change for a patch release would be to only support the implied-declaration behavior -- whichever orientation of that restores backward-compatibility -- and then add the option to use an explicit declaration in v1.9, which would be backward-compatible as long as the treatment of the absence of such a declaration remains unchanged.

If I am totally missing the point of what earlier behavior you are trying to restore here, please let me know! The associated issue does say that it behaved differently in v1.7, but I don't personally remember exactly how v1.7 treated this situation, and so I was making some assumptions.

**Pull request closed without merging**
