### PR TITLE
provider/aws: Add support for bucket name validation

### PR DESCRIPTION
**Pull request by kjmkznr**
Support bucket name validation.

https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

### CODE REVIEW

**Comment by catsby** [comment]
Hey @kjmkznr thanks for the PR! Does this make any accommodations for the more relaxed restrictions on Buckets in us-east-1, mentioned not that doc page? I like this validation, but we need to be flexible for people still on us-east-1 and allowed to have more relaxed names

**Comment by kjmkznr** [comment]
Yes, mentioned that doc page. And I know lax only in us-east-1 region.
I wanted this validation,  I tried to put out the pull request.
And I agree to what you say.

**Comment by kjmkznr** [comment]
link #6173

**Comment by catsby** [comment]
Hey @kjmkznr – I didn't mean to suggest you close your pull request, I apologize for giving that impression! 

I do like this change, we just need to think on how we'd approach this, gracefully if we can. As the doc says, this will be enforced in us-east-1 eventually. For us, it's a matter of what to do with users who are currently using the relaxed names.

**Comment by kjmkznr** [comment]
@catsby 
Sorry!
I see.

It is one of the idea, What about to add a ‘ignore_validation‘ parameter?

**Pull request closed without merging**
