### PR TITLE
Improve shell scripts

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Multiple shell scripts improvements here to make them more robbust.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
The CI failure came from `master` branch: https://travis-ci.org/hashicorp/terraform/builds/442481009, which is not related to the changes here.

**Comment by PeterDaveHello** [comment]
@mildwonkey would you like to help review this PR? Thank you!

**Comment by mildwonkey** [comment]
Hi, thanks and sorry for the long silence! We have been making many changes to our build process since this was opened and generally prefer to maintain these files ourselves - if you run across an issue with any of our build scripts, please open a new github issue. Cheers!

**Comment by PeterDaveHello** [comment]
Hi @mildwonkey, these contributions are going to make Terraform's shell script more robust and modern, if there is anything not clear enough in the commit message, I can explain it to you people who maintain it, would you mind to help me reopen it and have some discussion about the changes?

No offense, but directly close it for such a good project seem to be a not so good choice to me 😅

**Comment by PeterDaveHello** [comment]
Hi @mitchellh, I took a look and found that you seem to be the original author/commiter of shell scripts in the project, not sure if you could help take a look of the changes and see if we can get them merged or revised? Thanks 😄

**Comment by mildwonkey** [comment]
@PeterDaveHello I apologize, I should have been more clear: These scripts (or at least most of them) aren't used anymore. Our build process has been moved to an internal repository. 

I will confirm which of the scripts are no longer necessary, in case some are still used, and remove them.

**Comment by PeterDaveHello** [comment]
Thanks @mildwonkey for the clarification, I got it!

**Pull request closed without merging**
