### PR TITLE
Persist state more frequently

### LINKED ISSUE #14487: S3 remote backend tfstate is not available immediately
### Terraform Version
Terraform v0.9.1

### Affected Resource(s)
Please list the resources as a list, for example:
s3 remote state

It is a remote backend issue affecting tfstate

### Terraform Configuration Files
Terraform has multiple modules with lots of tf files along with remote backend configured as S3

### Expected Behavior
Remote backend behavior for tfstate stored on S3 should be such that as my resources get created one by one, the tfstate on S3 should immediately get updated with the details of these resources in real time

For local tfstate files, tftsate gets updated immediately when a resource becomes "creation completed" and I can see it in tfstate immediately. But that is not the case with Remote S3 backends

### Actual Behavior
What actually happened?
I saw the the remote tfstate file in S3 UI , only after terraform apply completed and all resources were already created by then. I did not see the tfstate file getting updated as resources were getting created on by one. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
`terraform apply`

### PR DESCRIPTION
**Pull request by jbardin**
State implementations may not commit state to storage until PersistState is called. With the new separate backends running the show, PersistState wasn't called during the apply execution, and if the process was terminated early there would be no state saved.

This PR provides 2 new pieces to help mitigate the issue. The StateHook, which writes the state after changes during the apply walk, will periodically call PersistState. This is set to a minimum 10 second interval from the previous PersistState call. 

The second improvement is when the backend received notice that the operation is being cancelled, it immediately calls PersistState to attempt to flush and cached state to permanent storage. 

Since we now have possible concurrent access to the StateWriters, the outer structs all need to be concurrent-safe. Mutexes are added to the methods that mutate the structs to serialize access, along with tests for the race detector. 

Fixes #14487

### CODE REVIEW

**Comment by jbardin** [comment]
@apparentlymart,

That's a good point, but I would lean heavily on the side of TFE not depending on the behavior of the state in the UI.

**Comment by manuwelakanade** [comment]
@jbardin, @apparentlymart : Since this was supposed to fix: https://github.com/hashicorp/terraform/issues/14487, and now it has been reverted in 0.9.8, when is the actual fix for this expected.

 It creates a bit of a problem for us to use terraform 0.9+ versions since S3 backend has nothing populated in some error scenarios. But we do have to move to v0.9+ for some other unrelated fixes/features.

**Comment by apparentlymart** [comment]
Due to the this revert being unplanned we've unfortunately had to prioritize other ongoing work ahead of it for the moment, but we do plan to come back to this soon once we've got some of the big logistical work for 0.10 out of the way.

However, if there are situations where Terraform is failing without doing a final write of the state, that is a bug in itself and worth addressing separately, so a new top-level issue would be welcome for that if you have some more details to share about what kinds of errors are experiencing that. Periodic state writes _during_ apply would just be a band-aid for that.

Also worth noting that this PR wasn't reverted in its entirety, but rather just the one commit about periodically persisting state. The part of this change where state is persisted immediately on `SIGINT` is still in 0.9.8, which doesn't help with the "not saving state on error" problem, but it does address a related concern that others might find useful.

**Comment by manuwelakanade** [comment]
Thanks for the reply @apparentlymart

**Comment by manuwelakanade** [comment]
Hi @apparentlymart , @jbardin : Any update on when this will be taken up since there have been a couple of 0.9.X and one 0.10 beta release since then. Thanks

**Comment by jbardin** [comment]
@manuwelakanade,

While we do hope to improve the functionality of the state is persisted in the backend, we would like to stress that this is working as intended right now. Because Terraform operates concurrently, and state checkpoints aren't atomic, there no guarantee that any state seen while running reflects the actual state of the infrastructure, which makes incremental state updates less useful in most cases.

As apparentlymart mentioned, if you have a case where an updated state isn't persisted at all from a run, please file a new issue as that could be very serious. In the meantime, there are other related issues pertaining to state serialization that need to be sorted out before we can attempt to re-instate incremental updates in remote backends.

**Comment by glasser** [comment]
Is this specifically a problem with Atlas? Maybe this could be reverted but only enabled for backends that claim to support it? (This is probably what we'll do in our fork.)

**Comment by jbardin** [comment]
@glasser, no this has turned out to be a problem with state handling in general, it was just that Atlas was the first to encounter an issue because of its strict handling of state checksums and serial numbers.

Terraform 0.10-beta2 contains some major refactoring of how state serialization is handled, and we can see how that works in practice before moving forward.

**Pull request merged**
