### PR TITLE
provider/openstack: Add support provider network

### PR DESCRIPTION
**Pull request by takaishi**
Hello, I want create provider network with segment_id.

refs: http://developer.openstack.org/api-ref/networking/v2/?expanded=create-network-with-multiple-segment-mappings-detail

### CODE REVIEW

**Comment by jtopjian** [comment]
@takaishi Thanks for this! I will review this ASAP.

**Comment by jtopjian** [comment]
@takaishi I'm so sorry for the delay on this.

I noticed that you manually patched the `vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/requests.go` file. This file is part of the https://github.com/gophercloud/gophercloud repository, so the addition of Segments will first need to be submitted as a PR to Gophercloud.

Once that patch has been merged, you can use `govendor` to pull in the upstream patch.

Unfortunately patching the vendor files like this isn't recommended because then we would diverge from the upstream Gophercloud, essentially creating our own version.

Again, I do apologize for not getting to this sooner. Please let me know if you have any questions.

**Comment by takaishi** [comment]
@jtopjian 
Thank you for your comemnt!

> I noticed that you manually patched the vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/requests.go file. This file is part of the https://github.com/gophercloud/gophercloud repository, so the addition of Segments will first need to be submitted as a PR to Gophercloud.

OK, I will to submmit PR to gopercloud.

**Comment by stack72** [comment]
ping on this PR :)

**Comment by takaishi** [comment]
@stack72 
I created new issue and PR for gorphercloud.
So, when merged it, I will update this PR.

**Comment by takaishi** [comment]
@stack72 
I created new issue and PR on gophercloud.
So, when it merged I will fix this PR.

**Comment by jtopjian** [comment]
@takaishi Is this ready for a review or are you still working on it?

**Comment by takaishi** [comment]
@jtopjian Yes, ready for review.

**Comment by jtopjian** [comment]
@takaishi Thanks for putting this together.

There were some areas that needed to be cleaned up. It was easier to do a code diff than try to explain them with inline comments. You can see it [here](https://github.com/jtopjian/terraform/commit/c04e2fac95947db9b73a7f9c1c802eb1f12382e8). Let me know if you have any questions about any of the changes.

In addition, the commit history needs cleaned up. There shouldn't be revert and "merge" commits. Do you mind making a clean commit history and then doing a force push?

**Comment by takaishi** [comment]
@jtopjian Thank you for review.
I'll clean up code and commit history.

**Comment by takaishi** [comment]
>　@jtopjian Thank you for review.
I'll clean up code and commit history.

I finished fix and rebase.

**Comment by jtopjian** [comment]
@takaishi This looks good to me - thank you :)

```
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/05/29 21:23:59 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/openstack -v -run=TestAccNetworkingV2Network -timeout 120m
=== RUN   TestAccNetworkingV2Network_importBasic
--- PASS: TestAccNetworkingV2Network_importBasic (25.55s)
=== RUN   TestAccNetworkingV2Network_basic
--- PASS: TestAccNetworkingV2Network_basic (32.71s)
=== RUN   TestAccNetworkingV2Network_netstack
--- PASS: TestAccNetworkingV2Network_netstack (70.00s)
=== RUN   TestAccNetworkingV2Network_fullstack
--- PASS: TestAccNetworkingV2Network_fullstack (116.16s)
=== RUN   TestAccNetworkingV2Network_timeout
--- PASS: TestAccNetworkingV2Network_timeout (24.05s)
=== RUN   TestAccNetworkingV2Network_with_multiple_segment_mappings
--- PASS: TestAccNetworkingV2Network_with_multiple_segment_mappings (24.68s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/openstack      293.188s
```

**Pull request merged**
