### PR TITLE
Document `inline` & `on_failure` behaviour

### PR DESCRIPTION
**Pull request by OJFord**
cf. #27554

### CODE REVIEW

**Review by alisdair — APPROVED** [review]
Thanks for writing this up! If you're able to sign the CLA, I'd be happy to merge this.

**Comment by OJFord** [comment]
I did when I opened, just clicked 'recheck it', hopefully that works. (Opened and closed immediately on mobile.)

**Comment by alisdair** [comment]
@OJFord Unfortunately that didn't seem to work. Can you try signing again?

**Comment by OJFord** [comment]
@alisdair Done, sorry about that. Cookies. Without cookies enable clicking 'sign with GitHub' just redirects to a copy of it and sort of seems like it succeeded.

**Pull request merged**
