### PR TITLE
Remove redundant const from command package

### PR DESCRIPTION
**Pull request by rue-dng**
Replace usages of DefaultDataDir with the equivalent DefaultDataDirectory
Remove now unused DefaultDataDir const

### CODE REVIEW

**Comment by jen20** [comment]
LGTM @rue-dng! Thanks for opening a pull request! When you think it's ready to be merged, please take off the [WIP] label and one of us will take a look!

**Comment by stack72** [comment]
Hi @rue-dng 

After a short discussion internally, we are going to close this one in favour of merging #7666

This is nothing more than the fact that the other PR touches much less files. Thanks so much for the time you have taken here

Paul

**Comment by rue-dng** [comment]
@stack72 Ah, no worries. Only reason I chose the other one was consistency with other var names. I'll be looking for additional ways to contribute soon, thanks.

**Comment by stack72** [comment]
Looking forward to the contributions!

**Pull request closed without merging**
