### PR TITLE
[WIP] New resource: aws_opsworks_chef_server

### LINKED ISSUE #10478: [Feature Request] OpsWorks for Chef Automate Support
Just announced at re:Invent 2016
https://www.chef.io/opsworks/

OpsWorks now supports Chef Automate (a managed chef server... woo!)

This is a feature request to add support for the new opsworks service to Terraform :)

### PR DESCRIPTION
**Pull request by bradfeehan**
Allows Terraform to manage resources relating to OpsWorks for Chef Automate.

See https://www.chef.io/opsworks/ and https://aws.amazon.com/opsworks/chefautomate/.

This is my first contribution to Terraform, and I'd appreciate some feedback :smile: 

1. would further tests would be a good idea?
2. is my documentation too verbose?
3. anything I'm missing?

Fixes #10478.

### CODE REVIEW

**Comment by dude051** [comment]
@bradfeehan have you had any further progress on this?

Functionally things look good.  I would really like to see momentum on this to get implemented into the provider. Currently we are looking for a solution in terraform to build out an OpsWorks Chef Server and this would do the trick.

**Comment by dude051** [comment]
Also one last thing. Since the split this should be moved to https://github.com/terraform-providers/terraform-provider-aws. If you have no time for this, I would be willing to move your code over and get anything missing and or working there if you don't mind.

**Comment by apparentlymart** [comment]
Hello @bradfeehan, and thanks for working on this!

As part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it.

If you or someone else has the time and motivation to apply same changes to [the `aws` provider repository](https://github.com/terraform-providers/terraform-provider-aws) and open a new PR there, the maintainers of that provider should be able to review and merge it.

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Comment by cornfeedhobo** [comment]
@bradfeehan Any interested in continuing with this?

**Comment by bradfeehan** [comment]
Hey team, sorry but I've moved on from Terraform development so I won't have any bandwidth to return to this.

**Comment by cornfeedhobo** [comment]
@bradfeehan out of curiosity, are you using a different tool instead now, or just not doing TF development as much?

**Pull request closed without merging**
