### PR TITLE
tools: remove terraform-bundle.

### PR DESCRIPTION
**Pull request by mildwonkey**
terraform-bundle is no longer supported in the main branch of terraform, in favor of using the [newer provider installation options](https://www.terraform.io/docs/cli/config/config-file.html#provider-installation) introduced in terraform v0.13. Anyone who still needs access to this can build terraform-bundle from terraform tagged v0.15 and older.

### CODE REVIEW

**Review by apparentlymart — APPROVED** [review]
LGTM! Thanks.

**Comment by lorengordon** [comment]
This makes me sad.

**Comment by lorengordon** [comment]
@mildwonkey Do you happen to have any examples of *how* to use the builtin options to replace what terraform-bundle does? I can't see how they're equivalent, without a bunch of custom scripting. How do I use the builtin options to create an archive of core+providers that I can just unzip into `TF_PLUGIN_CACHE_DIR`?

**Comment by mildwonkey** [comment]
@lorengordon I'd start by looking at the [`terraform providers mirror`](https://www.terraform.io/docs/cli/commands/providers/mirror.html) command, which will download providers for a given configuration. You can archive that directory structure for use on other workstations, or use one of the other installation methods to point those workstations to a [`filesystem_` or `network_mirror`](https://www.terraform.io/docs/cli/config/config-file.html#explicit-installation-method-configuration) where the provider binaries are hosted.

**Comment by lorengordon** [comment]
Ahh, ok, I'll play around with `providers mirror` to see if I can replicate the same structure. That command wasn't mentioned in the linked doc, so I just couldn't see how to get from A to Z...

**Pull request merged**
