### PR TITLE
Upgrade DNSimple provider to API v2

### PR DESCRIPTION
**Pull request by weppos**
A couple of days ago [DNSimple announced the next major release](https://blog.dnsimple.com/2016/12/api-v2-stable/) of the API. Among the various improvements, API v2 supports the following new features:

1. OAuth
1. Multi-accounts

In the last months, few users contacted us in particular about the second point, as they created a separate account (e.g. for the company) and they wanted to be able to use it via Terraform.

This PR upgrades the current DNSimple provider to API v2, and replaces @pearkes's Go client with the [official DNSimple Go client](https://github.com/dnsimple/dnsimple-go).

I tried to follow the instructions in the CONTRIBUTING.md file, but I'd be happy if someone can review the changes and provide a feedback. Some notes:

- I removed @pearkes's client from the vendor folder, and added the DNSimple one in a separate commit, as requested in the CONTRIBUTING file.
- I upgraded the provider to v2
- I needed to access some config inside the resources, hence I added a Client wrapper (similar approaches were adopted e.g. in the GitHub provider and others) in https://github.com/hashicorp/terraform/commit/ba723c5d07f6ba9a49315e6d0415fc4c0949ce2a. Please let me know if there is a preferred way.

Open questions:

- API v1 and API v2 are not compatible. The API token is different, as well the auth mechanism. I've tried to add a warning if the user had the previous token configured. Is there a better way?
- Some names in the resource no longer really reflect the API structure. For e.g, we replaced "domain" with "zone", that it will be more relevant also when we will expose reverse zones. Any objection to change them as part of this major change?
- There are certain resource fields that Terraform defines as String, although they are actually integers (e.g. TTL, Priority). I've seen a very limited usage of non-String types, even in other providers. Is there a recommended approach? Should I leave them String?

The documentation is not updated yet, I'll work on it, including feedback from this PR (if any). I will probably highlight API v2 support. Does it make sense to provide an API v1 to v2 Terraform upgrade section?

### CODE REVIEW

**Comment by stack72** [comment]
Hey @weppos 

Thanks for this work - this is a great addition to the provider - I would love to talk about this work more (upgrade path etc) - please can you drop me an email? stack72 at hashicorp.com

Thanks

P.

**Comment by weppos** [comment]
@stack72 👍  done, email sent!

**Comment by weppos** [comment]
Hi @stack72, do you have any update about this PR and/or the email?

**Comment by weppos** [comment]
Sorry to bother again, but I was wondering it there's any way I can help to move forward with the review of this PR.

As we have a fixed deadline for API v1 removal, it would be amazing if I can get this completed in advance so that users will be able to take their time to migrate. :)

**Comment by weppos** [comment]
❤️

**Comment by stack72** [comment]
Hey @weppos 

I *promise* i will get back to you on this tomorrow - are you EU based? If so, could we have a discussion on this? I can se up a quick hangout for tomorrow to discuss

Paul

**Comment by weppos** [comment]
Yes, I am in GMT+1. I'd be happy to jump in an hangout. Feel free to reply to the email I sent with the details :)

**Comment by stack72** [comment]
Perfect! Doing so now :)

**Comment by weppos** [comment]
I generally don't rebase against master, but in this case the merge caused 4k files to be changed, and the diff was `+925,296 −86,913`.

I decided to rebase instead.

**Comment by weppos** [comment]
@stack72 the PR is now ready for review (and merge).

I updated the docs and the integration, but I haven't added the schema deprecations. I am still reading other providers to get more details, and determine an action plan.

To avoid adding too many changes here, I would probably open a fresh PR with deprecations, if any is required.

If any of you is using this provider, I'd love to get feedbacks. I haven't been able to try it directly (except for running the test suites). I'll try to create a Terraform local setup to play with it.

**Comment by stack72** [comment]
Hi @weppos 

Serious love for this :) LGTM and the tests pass!

```
% make testacc TEST=./builtin/providers/dnsimple                                                                                            ✭
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/03/02 05:10:36 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/dnsimple -v  -timeout 120m
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccDNSimpleRecord_Basic
--- PASS: TestAccDNSimpleRecord_Basic (1.52s)
=== RUN   TestAccDNSimpleRecord_Updated
--- PASS: TestAccDNSimpleRecord_Updated (1.85s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/dnsimple	3.382s
``` 

Merged and will be part of 0.9 - it won't be back ported to 0.8.8 though if that's ok

Paul

**Comment by weppos** [comment]
Thanks @stack72. Yes, I'm absolutely fine with the changes NOT being back ported to 0.8.8.

**Comment by joshuacronemeyer** [comment]
I thought I'd give this great new code a try. Ran into a problem/inconsistency between the behavior you describe and what i'm actually seeing.

```
terraform --version                                                                         [ruby-2.2.1]
Terraform v0.9.0-dev (d24c761bbb96a9921575582a2055cccbfb0b302d+CHANGES)
```
```
provider "dnsimple" {
  token = "${var.dnsimple_token}"
  account = "${var.dnsimple_account}"
}
```
I added the token and got rid of the email settings as per the instructions in this PR, but when i run terraform plan i am immediately prompted for the dnsimple email

```
provider.dnsimple.email
  The DNSimple account email address.

  Enter a value:
```

My workaround is to configure email as empty string as follows

```
provider "dnsimple" {
  token = "${var.dnsimple_token}"
  account = "${var.dnsimple_account}"
  email = ""
}
```

If you actually set an email address then you get the following error

```
* module.events-staging.provider.dnsimple: DNSimple API v2 requires an account identifier and the new OAuth token. Please upgrade your configuration.
```

Maybe a problem with this PR. It wasn't immediately obvious to my what is causing it to prompt for the email. Hope this helps somebody.

**Comment by stack72** [comment]
Hi @joshuacronemeyer

I am fixing this right now so that it will be part of the main release :) Thanks for testing this out for us

Paul

**Comment by weppos** [comment]
Thanks for reporting it @joshuacronemeyer

**Comment by joshuacronemeyer** [comment]
Glad to hear it was useful. Thanks again.

**Pull request merged**
