### PR TITLE
command/jsonplan: "deposed" should be a string, not a bool.

### PR DESCRIPTION
**Pull request by mildwonkey**
🙄 No excuses, just user error on my part.

@vancluever you'll want to make note of this, I used the wrong type entirely for the "deposed" key in "resource_changes".

### CODE REVIEW

**Comment by vancluever** [comment]
@mildwonkey noted. Should we change this to `deposed_key` then so that it's reflective of the true nature of the value that it contains?

```
	// DeposedKey is the identifier for a deposed object associated with the
	// given instance, or states.NotDeposed if this change applies to the
	// current object.
	//
	// A Replace change for a resource with create_before_destroy set will
	// create a new DeposedKey temporarily during replacement. In that case,
	// DeposedKey in the plan is always states.NotDeposed, representing that
	// the current object is being replaced with the deposed.
```

**Comment by vancluever** [comment]
Also, what does `DeposedKey` specifically look like? Is it a resource address, or something else?

**Comment by apparentlymart** [comment]
From the perspective of an outside caller, it's an opaque, meaningless string that is used only to correlate deposed objects between plan and state, and from one state snapshot to the next.

Physically, it's _currently_ implemented as a 32-bit integer serialized as hexadecimal, but no client should be relying on that.

**Comment by vancluever** [comment]
Hmm. Maybe we should omit it from the JSON then period if it has no value?

**Comment by apparentlymart** [comment]
Its value is what I mentioned: correlating deposed objects between plan and state. In other words, the only valid operation on a deposed key is to do a string comparison with another deposed key. It's not valid to parse it or make any assumptions about it beyond that.

**Comment by vancluever** [comment]
Should we expose this in the state representation then? It doesn't exist there.

**Comment by apparentlymart** [comment]
Since that isn't required for our initial goals here, let's defer that for later work.

**Pull request merged**
