### PR TITLE
provider/azurerm: Implement azurerm_storage_share

### PR DESCRIPTION
**Pull request by enieuw**
PR for https://github.com/hashicorp/terraform/issues/6849

Upstream PR for the Azure SDK for go has been filed but needs to be merged before this can go through. I'll update this PR when the upstream changes have been merged.

### CODE REVIEW

**Comment by stack72** [comment]
Hi @enieuw 

So this looks like it will hit in Azure SDK 5.0.0 - that's currently in the planning. When this hits, I will merge this PR

P.

**Comment by stack72** [comment]
Hi @enieuw 

We have finally been able to upgrade our version of the SDK to 5.0.0-beta. Please can you rebase this PR from master and we can get it tested and merged :)

Thanks

Paul

**Comment by enieuw** [comment]
Hi @stack72 

I've just rebased this PR on master, please have a look and let me know if you have any feedback.

Eric

**Comment by stack72** [comment]
Hi @enieuw 

This LGTM! Thanks for the work here - sorry it took so much longer to get merged :)

```
% make testacc TEST=./builtin/providers/azurerm TESTARGS='-run=TestAccAzureRMStorageShare_'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/10/25 14:10:53 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/azurerm -v -run=TestAccAzureRMStorageShare_ -timeout 120m
=== RUN   TestAccAzureRMStorageShare_basic
--- PASS: TestAccAzureRMStorageShare_basic (124.57s)
=== RUN   TestAccAzureRMStorageShare_disappears
--- PASS: TestAccAzureRMStorageShare_disappears (129.45s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/azurerm	254.026s
```

P.

**Pull request merged**
