### PR TITLE
provider/fastly Adds healthcheck service

### LINKED ISSUE #6944: Missing healthcheck support in fastly provider
### Terraform Version

`Terraform v0.6.16`
### Affected Resource(s)
- fastly_service_v1
### Terraform Configuration Files

``` hcl

resource "fastly_service_v1" "test" {
  name = "test"

  domain {
    name = "example.org"
  }

  backend {
    name = "test"
    address = "backend.example.org"
  }

  healtcheck {
        name = "main"
        method = "GET"
        path = "/.heartbeat"
  }
}
```
### Debug Output

N/A
### Expected Behavior

A service with a healthcheck should have been created.
### Actual Behavior

```
> ./terraform plan test
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * fastly_service_v1.test: : invalid or unknown key: healtcheck
```
### Steps to Reproduce
1. `terraform plan`

### PR DESCRIPTION
**Pull request by travertischio**
Allows the user to set up healthchecks for fastly

[Fastly API](https://docs.fastly.com/api/config#healthcheck)

- [x] Tests included
- [x] Website documentation included

Closes #6944

### CODE REVIEW

**Comment by stack72** [comment]
Hi @travertischio 

Thanks for the work here - unfortunately, the test is broken

```
=== RUN   TestAccFastlyServiceV1_healthcheck_basic
--- FAIL: TestAccFastlyServiceV1_healthcheck_basic (0.00s)
	testing.go:265: Step 0 error: Error loading configuration: Error parsing /var/folders/gd/yv86v7pd1cd5dpzjrw8702k00000gn/T/tf-test204341608/main.tf: At 16:7: illegal char
```

Can you have a look and see?

Thanks

Paul

**Comment by travertischio** [comment]
Hey @stack72 I believe I fixed the issue there.

**Comment by travertischio** [comment]
I also rebased to get rid of a merge conflict, let me know if you all would rather merging master than rebasing.

**Comment by stack72** [comment]
Thanks for fixing this up @travertischio 

This now LGTM and all tests pass :)

```
% make testacc TEST=./builtin/providers/fastly                                                                                               ✭
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/02/07 11:29:19 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/fastly -v  -timeout 120m
=== RUN   TestAccFastlyIPRanges
--- PASS: TestAccFastlyIPRanges (2.00s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccFastlyServiceV1CacheSetting_basic
--- PASS: TestAccFastlyServiceV1CacheSetting_basic (50.87s)
=== RUN   TestAccFastlyServiceV1_conditional_basic
--- PASS: TestAccFastlyServiceV1_conditional_basic (24.79s)
=== RUN   TestFastlyServiceV1_FlattenGzips
--- PASS: TestFastlyServiceV1_FlattenGzips (0.00s)
=== RUN   TestAccFastlyServiceV1_gzips_basic
--- PASS: TestAccFastlyServiceV1_gzips_basic (51.25s)
=== RUN   TestFastlyServiceV1_BuildHeaders
--- PASS: TestFastlyServiceV1_BuildHeaders (0.00s)
=== RUN   TestAccFastlyServiceV1_headers_basic
--- PASS: TestAccFastlyServiceV1_headers_basic (49.31s)
=== RUN   TestAccFastlyServiceV1_healthcheck_basic
--- PASS: TestAccFastlyServiceV1_healthcheck_basic (48.16s)
=== RUN   TestAccFastlyServiceV1_papertrail_basic
--- PASS: TestAccFastlyServiceV1_papertrail_basic (47.34s)
=== RUN   TestAccFastlyServiceV1RequestSetting_basic
--- PASS: TestAccFastlyServiceV1RequestSetting_basic (22.39s)
=== RUN   TestAccFastlyServiceV1_s3logging_basic
--- PASS: TestAccFastlyServiceV1_s3logging_basic (47.43s)
=== RUN   TestAccFastlyServiceV1_s3logging_s3_env
--- PASS: TestAccFastlyServiceV1_s3logging_s3_env (22.89s)
=== RUN   TestAccFastlyServiceV1_s3logging_formatVersion
--- PASS: TestAccFastlyServiceV1_s3logging_formatVersion (21.96s)
=== RUN   TestResourceFastlyFlattenDomains
--- PASS: TestResourceFastlyFlattenDomains (0.00s)
=== RUN   TestResourceFastlyFlattenBackend
--- PASS: TestResourceFastlyFlattenBackend (0.00s)
=== RUN   TestAccFastlyServiceV1_updateDomain
--- PASS: TestAccFastlyServiceV1_updateDomain (46.97s)
=== RUN   TestAccFastlyServiceV1_updateBackend
--- PASS: TestAccFastlyServiceV1_updateBackend (48.98s)
=== RUN   TestAccFastlyServiceV1_basic
--- PASS: TestAccFastlyServiceV1_basic (21.03s)
=== RUN   TestAccFastlyServiceV1_disappears
--- PASS: TestAccFastlyServiceV1_disappears (12.23s)
=== RUN   TestAccFastlyServiceV1_VCL_basic
--- PASS: TestAccFastlyServiceV1_VCL_basic (50.62s)
=== RUN   TestValidateS3FormatVersion
--- PASS: TestValidateS3FormatVersion (0.00s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/fastly	568.249s
```

P.

**Pull request merged**
