### PR TITLE
Add split function

### PR DESCRIPTION
**Pull request by brycekahle**
Adds the split function.

This allows a workaround for #845 by using `join` within the module, and `split` when using the output variable.

### CODE REVIEW

**Comment by knuckolls** [comment]
I'm glad to see that you're working on this. I reviewed the code. Do you have an example of how this would be used within the terraform configuration? Would you split a string back out and then use element() on it? If so, would I also need to capture the count of what was previously joined and ensure that whatever is interpolating information out of it had an identical count so i could use count.index? Those are the first questions that come to mind.

**Comment by brycekahle** [comment]
Sure.

Within a module 'amod'
```
resource "aws_instance" "mod_inst" {
  ...
  count = 3
}

output "server_ids" {
  value = "${join(",", aws_instance.mod_inst.*.id)}"
}
```

Within a normal config
```
module "amod" {
  source = "./amod"
}

resource "aws_elb" "mod_elb" {
  ...
  instances = "${split(",", module.amod.server_ids)}"
}
```

**Comment by knuckolls** [comment]
That's handy. So due to this it looks like split will effectively return a list of strings.

https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_elb.go#L50

@mitchellh basically in this instance we're marshaling a list structure into a string for transport into another module to then be marshaled back into a list. That solves a problem that people face today and I say we merge it as it stands. Beyond that, do you intend for module outputs to be typed at some point so we don't have to do this interpolation level marshaling between modules?

**Comment by mitchellh** [comment]
LGTM! This is great. Can you add docs? Once docs are there, we can merge.

**Comment by mitchellh** [comment]
(Or, if you don't add docs, one of us will add them one day and merge, but it'll take longer)

**Comment by brycekahle** [comment]
@mitchellh Added docs.

**Comment by mitchellh** [comment]
LGTM. Thanks!

**Comment by c4milo** [comment]
This doesn't seem to expand :( 
```
subnet_id = "${element(split(",", module.network.subnets), count.index)}"
```

**Comment by radeksimko** [comment]
@c4milo Could you please create this as a [new issue](https://github.com/hashicorp/terraform/issues/new) and ideally add a bit more code related to `module.network.subnets`, so we can replicate and eventually fix that?

**Comment by c4milo** [comment]
@radeksimko https://github.com/hashicorp/terraform/issues/1997.

**Comment by jsonmaur** [comment]
Needs to be noted that for some resources, the resulting `"${split(...)}"` needs to be wrapped in brackets (`["${split(...)}"]`) or you'll get the error `should be a list`.

**Pull request merged**
