### PR TITLE
Adding CRUD support for Customer Gateway for AWS VPC.

### PR DESCRIPTION
**Pull request by yahyapo**
This solves part of #551. AWS makes bgp_asn compulsory in its API. This is used for a dynamic gateway. However, if you want to create a static gateway, you need to pass a dummy bgp_asn. Hence, I have made bgp_asn field optional and given it a default value of 65000.

### CODE REVIEW

**Comment by yahyapo** [comment]
Check https://github.com/hashicorp/terraform/pull/787 for the initial PR and comments.

**Comment by yahyapo** [comment]
@mitchellh, I did not exactly understand why partial state mode is required in Create, as you had mentioned in your comment?

**Comment by mitchellh** [comment]
I'm getting a merge conflict, but this looks good otherwise. Can you fix that (rebase and push up) and I'll take another look?

**Comment by EvanKrall** [comment]
Bump. I want this.

**Comment by catsby** [comment]
@yahyapo We've also nearly completed migrating all our AWS resources to https://github.com/hashicorp/aws-sdk-go . If possible, you could upgrade this resource to the new library, but I doubt it will be a blocker for merging.

**Comment by yahyapo** [comment]
I am raising a new PR with the correct changes. Something has gone really wonky with this one.
Please check #1218

**Pull request closed without merging**
