### PR TITLE
provider/gitlab: add `gitlab_deploy_key`

### PR DESCRIPTION
**Pull request by richardc**
As suggested in #14471 this adds a `gitlab_deploy_key` resource to manage deploy keys.

### CODE REVIEW

**Comment by richardc** [comment]
Todo:

- [ ] Tests
- [ ] Documentation
- [ ] Monitor gitlab merge request https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/11607

To expand on that pending merge request, the /v3 api cannot currently manage the `can_push` attribute, so it is stuck at the default value (false).  That means given this snippet:

```
resource "gitlab_deploy_key" "example" {
  project = "${gitlab_project.test1.id}"
  title = "test"
  key = "${chomp(file("/Users/richardc/.ssh/id_rsa.pub"))}"
  can_push = true
}
``` 

Terraform will repeatedly delete and recreate the deploy key.  The merge request will fix that, but will take integration and releasing.

**Comment by richardc** [comment]
I've split out a commit to remove the testing of the `can_push` attribute, so we can move this on.  It should be safe (if misleading) to ship as-is, as the `can_push` attribute won't be correctly managed until the gitlab api is fixed.  I look to the terraform maintainers for guidance here.

**Comment by stack72** [comment]
Hi @richardc 

I agree with your move to remove that param for now - we should just document this as a NOTE on the resource - to say that it can't currently be managed (not the reason) and then tell the user what gitlab defaults to

Sound ok?

Paul

**Comment by richardc** [comment]
@stack72 So just patch website/source/docs/providers/gitlab/r/deploy_key.html.markdown to indicate the attribute isn't fully functional?  I don't see a mechanism to do this in the code from a skim of schema.Schema.

**Comment by stack72** [comment]
@richardc yeah there is no formal way to do this. The Markdown looks as follows

```
~> **NOTE::** My Note here
```

**Comment by richardc** [comment]
@stack72 How's the wording on that?

**Comment by stack72** [comment]
Hi @richardc 

This works - if it's not clear to users, we can change it up :)

Thanks for this! Tests are green as expected:

```
% make testacc TEST=./builtin/providers/gitlab                                                                                             ✭
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/05/24 11:39:31 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/gitlab -v  -timeout 120m
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccGitlabDeployKey_basic
--- PASS: TestAccGitlabDeployKey_basic (39.50s)
=== RUN   TestAccGitlabProjectHook_basic
--- PASS: TestAccGitlabProjectHook_basic (31.64s)
=== RUN   TestAccGitlabProject_basic
--- PASS: TestAccGitlabProject_basic (30.03s)
=== RUN   TestGitlab_validation
--- PASS: TestGitlab_validation (0.00s)
=== RUN   TestGitlab_visbilityHelpers
--- PASS: TestGitlab_visbilityHelpers (0.00s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/gitlab	101.189s
```

Paul

**Pull request merged**
