### PR TITLE
Added new evaluation_delay parameter

### PR DESCRIPTION
**Pull request by opteemister**
Added new evaluation_delay parameter to datadog_monitor

### CODE REVIEW

**Comment by stack72** [comment]
Hi @opteemister 

this is looking good  - please can you add the new parameter to the documentation?

Thanks

Paul

**Comment by opteemister** [comment]
Added

**Comment by opteemister** [comment]
Btw, could you please look at this provider for sendgrid?

https://github.com/opteemister/terraform-provider-sendgrid

It could be useful for managing sendgrid templates (we wrote it for our own usage, but maybe it could be extended and added to the build-in providers).

**Comment by stack72** [comment]
With regards to the sendgrid provider - can you drop me an email about it? stack72 @ hashicorp . com and we can chat about it a bit offline

**Pull request merged**
