### PR TITLE
Update docs to show correct launching of atlas artifact in AWS.

### PR DESCRIPTION
**Pull request by carinadigital**
See issue #2203 .

### CODE REVIEW

**Comment by pearkes** [comment]
@carinadigital We're trying to centralize around `amazon.ami` across all the documentation for the artifact type for AMIs. Do you mind switching that?

Additionally, it might be helpful to write a short comment above the reference to the AMI explaining the need to encode the region into the reference. See also #2731

**Comment by carinadigital** [comment]
@pearkes Updated as requested.

**Comment by josephholsten** [comment]
Rebased in #3367 

@pearkes ready for your :eyes:

**Comment by carinadigital** [comment]
This is superseded in #3367.  Closing.

**Pull request closed without merging**
