### PR TITLE
Adds note that VCS is required and adds line for setting up a git rep…

### PR DESCRIPTION
**Pull request by timmytofu**
…o so the remainder works

### CODE REVIEW

**Comment by phinze** [comment]
Hi @timmytofu - thanks for contributing!

I'm pretty sure VCS is not a requirement for using remote state storage, though. What behavior did you see that gave you that impression?

**Comment by timmytofu** [comment]
```
tim 2016Jan20 00:26:14> mkdir blah ; cd blah
tim 2016Jan20 00:26:14> cp ../tf/example.tf ../tf/terraform.tfvars ../tf/variables.tf .
tim 2016Jan20 00:26:44> terraform remote config -backend-config="name=timmy_tofu/no-git"
Initialized blank state with remote state enabled!
Remote state configured and pulled.
tim 2016Jan20 00:26:56> terraform push -name="timmy_tofu/no-git"
An error has occurred while archiving the module for uploading:
error detecting VCS: no VCS found for path: /home/tim/blah
[1] tim 2016Jan20 00:27:08> git init
Initialized empty Git repository in /home/tim/blah/.git/
tim 2016Jan20 00:27:17> terraform push -name="timmy_tofu/no-git"
An error has occurred while archiving the module for uploading:
error getting git commit: exit status 128
stdout:
stderr: fatal: bad default revision 'HEAD'

[1] tim 2016Jan20 00:27:21> git add . ; git ci -m "Initial commit"
[master (root-commit) 26d88a4] Initial commit
…
tim 2016Jan20 00:27:43> terraform push -name="timmy_tofu/no-git"
Uploading Terraform configuration...
Configuration "timmy_tofu/no-git" uploaded! (v1)
tim 2016Jan20 00:27:51>
```

**Comment by radeksimko** [comment]
It looks like the VCS is required for the Atlas subcommand `push` as [`vcs` flag is enabled by default](https://github.com/hashicorp/terraform/blob/master/command/push.go#L36).

As @phinze mentioned VCS is not required for the remote state generally (i.e. for any `terraform remote *` commands). `push` is an Atlas-specific command for pushing source code to Atlas to be `plan`-ed & `applied` from Atlas.

However I believe the docs or behaviour can still be changed, specifically this part:
https://www.terraform.io/docs/commands/push.html

> If Terraform doesn't detect a VCS, it will upload all files.

That's not true as you demonstrated with the example above.

I'm not sure whether it was intention to upload all files w/out VCS, when `terraform push vcs=true` (which is default behaviour) or whether we want to be erroring out (in which case we should update the docs).

**Comment by phinze** [comment]
Yeah I think we treat this as a bug - `terraform push` should work inside and outside of VCS.

**Comment by jen20** [comment]
Hi all, I've opened a new issue to track this: #5478 - in order that it gets tracked as a bug rather than a pull request. Consequently we'll close this issue and move the discussion to #5478.

**Pull request closed without merging**
