### PR TITLE
provider/aws: Cleanup ASG acceptance tests

### PR DESCRIPTION
**Pull request by tpounds**
Splitting out AWS auto scaling group acceptance test cleanup per pull request #5044.

### CODE REVIEW

**Comment by phinze** [comment]
Hiya @tpounds - I'm guessing that dropping these instance counts to zero makes sense because the instance-waiting behavior is covered in other tests?

Think you could include a little bit of context/explanation in the commit message so we can record why the numbers are changing?

**Comment by tpounds** [comment]
@phinze This change was made to an auto scaling group acceptance test that doesn't care about instances. It's hard to tell from the collapsed diff but if you expand it you will see it's a template for the TestAccAWSAutoScalingGroup_VpcUpdates test. It's assertions don't care about the instance state. FWIW, I was planning to audit a few other auto scaling group acceptance tests to see if it makes sense to do this elsewhere. Thoughts?

**Comment by phinze** [comment]
Sounds good to me! If you can reflect that reasoning in the commit message I'm good to merge.

I'm all for making tests faster/simpler. :+1: :grinning:

**Comment by tpounds** [comment]
@phinze I've refactored my original commit and fixed up another test as well. I think my commit messages explain the changes in a more detail now. LMK if you think this can be improved further.

**Comment by phinze** [comment]
Nice - this looks great @tpounds - thank you!

**Pull request merged**
