### PR TITLE
add 'power_state'  attribute to reflect desired power state

### LINKED ISSUE #13803: Crash when acting upon powered off VM
### Terraform Version
Terraform version: 0.9.3  1601af7a076fd03fe940455db7fd01dfa747c795

### Affected Resource(s)
vsphere_virtual_machine

### Terraform Configuration Files
```hcl
provider "vsphere" {
  user                 = "${var.vsphere_user}"
  password             = "${var.vsphere_password}"
  vsphere_server       = "${var.vsphere_server}"
  allow_unverified_ssl = "${var.vsphere_allow_unverified_ssl}"
}

resource "vsphere_virtual_machine" "dest_image" {
  name         = "${var.vsphere_dest_image_name}"
  folder       = "${var.vsphere_root_folder}/${var.vsphere_dest_image_folder}"
  vcpu         = "${var.vsphere_dest_image_vcpu}"
  memory       = "${var.vsphere_dest_image_memory}"
  domain       = "${var.vsphere_dest_image_domain}"
  datacenter   = "${var.vsphere_datacenter}"
  cluster      = "${var.vsphere_cluster}"
  dns_suffixes = ["${var.vsphere_dest_image_domain}"]
  dns_servers  = ["${var.vsphere_dns_servers}"]

  network_interface {
    label = "${var.vsphere_network}"
  }

  disk {
    datastore = "${var.vsphere_datastore}"
    template  = "${var.vsphere_root_folder}/${var.vsphere_source_image_folder}/${var.vsphere_source_image_name}"
  }
  
  connection {
    type = "ssh"
    user = "${var.vsphere_image_username}"
    password = "${var.vsphere_image_password}"
  }
}

```

### Debug Output
I believe it's in the panic output below, here is the regular output:

$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

vsphere_virtual_machine.dest_image: Refreshing state... (ID: bp-vm-01)
Error refreshing state: 1 error(s) occurred:

* vsphere_virtual_machine.dest_image: vsphere_virtual_machine.dest_image: unexpected EOF
panic: runtime error: invalid memory address or nil pointer dereference
2017/04/20 10:32:49 [DEBUG] plugin: terraform: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x3cdc5c9]
2017/04/20 10:32:49 [DEBUG] plugin: terraform: 
2017/04/20 10:32:49 [DEBUG] plugin: terraform: goroutine 47 [running]:
2017/04/20 10:32:49 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/vsphere.resourceVSphereVirtualMachineRead(0xc42023a380, 0x4daa380, 0xc4204ef650, 0x1, 0x77c2d80)
2017/04/20 10:32:49 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/vsphere/resource_vsphere_virtual_machine.go:1030 +0x18a9
2017/04/20 10:32:49 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc420421d40, 0xc4201a0410, 0x4daa380, 0xc4204ef650, 0xc42043fd10, 0xc42042d301, 0x0)
2017/04/20 10:32:49 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:314 +0x21d
2017/04/20 10:32:49 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc42026b1f0, 0xc4201a03c0, 0xc4201a0410, 0x7f42dc212000, 0x0, 0x0)
2017/04/20 10:32:49 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:267 +0x91
2017/04/20 10:32:49 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc4200af140, 0xc4203f2060, 0xc4203f2c90, 0x0, 0x0)
2017/04/20 10:32:49 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provider.go:510 +0x4e
2017/04/20 10:32:49 [DEBUG] plugin: terraform: reflect.Value.call(0xc42035d920, 0xc42000c5a0, 0x13, 0x4e8780f, 0x4, 0xc4206c6f20, 0x3, 0x3, 0x0, 0x0, ...)
2017/04/20 10:32:49 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:434 +0x91f
2017/04/20 10:32:49 [DEBUG] plugin: terraform: reflect.Value.Call(0xc42035d920, 0xc42000c5a0, 0x13, 0xc420643f20, 0x3, 0x3, 0x0, 0x0, 0x0)
2017/04/20 10:32:49 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:302 +0xa4
2017/04/20 10:32:49 [DEBUG] plugin: terraform: net/rpc.(*service).call(0xc4204dcf40, 0xc4204dcf00, 0xc4201450f8, 0xc420521300, 0xc420434860, 0x4078040, 0xc4203f2060, 0x16, 0x4078080, 0xc4203f2c90, ...)
2017/04/20 10:32:49 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:387 +0x144
2017/04/20 10:32:49 [DEBUG] plugin: terraform: created by net/rpc.(*Server).ServeCodec
2017/04/20 10:32:49 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:481 +0x404
2017/04/20 10:32:49 [ERROR] root: eval: *terraform.EvalRefresh, err: vsphere_virtual_machine.dest_image: unexpected EOF
2017/04/20 10:32:49 [ERROR] root: eval: *terraform.EvalSequence, err: vsphere_virtual_machine.dest_image: unexpected EOF
2017/04/20 10:32:49 [TRACE] [walkRefresh] Exiting eval tree: vsphere_virtual_machine.dest_image
2017/04/20 10:32:49 [DEBUG] dag/walk: upstream errored, not walking "output.dest_image_ip"
2017/04/20 10:32:49 [DEBUG] dag/walk: upstream errored, not walking "root"
2017/04/20 10:32:49 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/04/20 10:32:49 [WARN] plugin: error closing client during Kill: connection is shut down
2017/04/20 10:32:49 [DEBUG] plugin: terraform: plugin process exited

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

### Panic Output
https://gist.github.com/bpoland/5c9055b1c64e82654e5d928609d2cda3

### Expected Behavior
Shouldn't crash.  Should refresh successfully since the VM still exists it's just powered off.

### Actual Behavior
Terraform crashed

### Steps to Reproduce
1. `terraform refresh`

### Important Factoids
Only seems to happen if the VM has been sitting there for a while.  A newly created and shut down VM does not have this issue

### References
Seems potentially related to this: https://github.com/hashicorp/terraform/issues/4302

### PR DESCRIPTION
**Pull request by matt-deboer**
Adds a new `power_state` (string) attribute to `vsphere_virtual_machine`, with behavior as follows:
- when `ignored' (default): if the target vm is in a `powered off` state, instead of crashing terrraform during read operations (the current behavior), an error will be thrown indicating that the vm must be powered on in order to properly read it's state via terraform.
- when `poweredOn`: if the target vm is not in a `powered on` state, the vm will show as requiring a change to `poweredOn`; additionally, network interfaces will be reconstructed from the current (last known) state where they cannot be read from the govmomi api while the vm is not 'powered on'.

This fixes #13803 and #14910; see those issues for more details.

**Notes**:
- If the machine is not in a `poweredOn` state AND `power_state` value is `poweredOn` AND there are changes to the networking configuration, those changes will not be listed in the things needing change, although the overall resource will show as needing change.

### CODE REVIEW

**Comment by Freyert** [comment]
@matt-deboer the built in providers have been moved out of master. You will need to remake these changes over on https://github.com/terraform-providers/terraform-provider-vsphere

**Comment by matt-deboer** [comment]
Done; thanks.

**Comment by apparentlymart** [comment]
I'm going to close this since it was migrated over to terraform-providers/terraform-provider-vsphere#103. Thanks for doing, that, @matt-deboer!

**Comment by Xat59** [comment]
Hi team,

thank a lot for this commit. When will this commit added to a terraform release ?

**Comment by Freyert** [comment]
@Xat59 it looks like terraform-providers/terraform-provider-vsphere#103 and terraform-providers/terraform-provider-vsphere#129 (which supersedes terraform-providers/terraform-provider-vsphere#103) may take care of some of the issues?

Whatever the case they closed terraform-providers/terraform-provider-vsphere#103, but terraform-providers/terraform-provider-vsphere#129 has landed in master.

If you want you can probably pull it down and compile it yourself to play around with if you want.

**Pull request closed without merging**
