### PR TITLE
Add support for instance tenancy in `aws_opsworks_instance`

### LINKED ISSUE #10679: Feature request - Opsworks Instance Tenancy
AWS Opsworks instances [support tenancy](http://docs.aws.amazon.com/opsworks/latest/APIReference/API_CreateInstance.html). Curious about adding this configuration option as a param to the `aws_opsworks_instance` resource.

### PR DESCRIPTION
**Pull request by myoung34**
Resolves #10679

### CODE REVIEW

**Comment by stack72** [comment]
Hi @myoung34 

Thanks for the work here - I just looked at the code and ran the acceptance tests. I get the following error:

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSOpsworksInstance'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/12/28 16:42:28 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSOpsworksInstance -timeout 120m
=== RUN   TestAccAWSOpsworksInstance
--- FAIL: TestAccAWSOpsworksInstance (39.80s)
	testing.go:265: Step 0 error: After applying this step, the plan was not empty:

		DIFF:

		UPDATE: aws_opsworks_instance.tf-acc
		  tenancy: "default" => ""

		STATE:
```

I suspect that AWS sets tenancy to be `default` - is this correct? If this is the case, then we need to make the schema include `Computed: true` as well so that we know we can get a value from AWS even though we have not set anything

Thoughts?

Paul

**Comment by myoung34** [comment]
@stack72 i'll take a look. Didn't realize there were acc tests, I went based on the automated PR tests. Let me see if i can get that to pass. And yea, the default value is `default`

**Comment by myoung34** [comment]
@stack72 that acc test passes now, you were write on `Computed: true`

**Comment by stack72** [comment]
Hi @myoung34 

This LGTM now - thanks for making that change :)

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSOpsworksInstance'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/12/28 22:43:08 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSOpsworksInstance -timeout 120m
=== RUN   TestAccAWSOpsworksInstance
--- PASS: TestAccAWSOpsworksInstance (230.51s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	230.531s
```

**Pull request merged**
