### PR TITLE
Refactor handling of credential ENVs for GCS backend

### PR DESCRIPTION
**Pull request by SarahFrench**
This PR refactors existing code to use the `(schema.Backend).DefaultFunc` field instead of accessing and using ENVs with the `os` package and `if...else` in the configure function.

Not essential, but I think it's useful to use the same approach for all fields. Plus it helps people see all the relevant ENVs in the backend schema.

No linked issue.

## Target Release

1.4.0

### ~~NEW FEATURES | UPGRADE NOTES | ENHANCEMENTS | BUG FIXES | EXPERIMENTS~~

 

No CHANGELOG entry as it's not a user-facing change

### CODE REVIEW

**Comment by SarahFrench** [comment]
I'm revisiting this PR as I'd like to get it reviewed and merged.


# How to test this refactor

In terms of testing, I think there are two scenarios to cover:
- someone setting up a backend for the first time, using code from this PR
- someone upgrading to a new TF version, including code from this PR, and interacting with an existing remote state

For the first one, I think the fact the automated unit tests are working is a good enough test! Credentials are supplied via ENV in those tests.

For the second, testing an existing remote state, I've done this experiment below. I  don't think an automated test is needed as it'd be testing the SDK and not the gcs backend.

1. Build terraform from source @v1.3 tag and @615f289 commit from this PR
2. Use terraform@1.3.0 to provision a service account, using a gcs bucket to store state. Credentials are supplied as a `GOOGLE_CREDENTIALS` ENV:

```
envchain google ~/go/bin/terraform@1.3.0 apply --auto-approve
```

```
terraform {
  backend "gcs" {
    bucket = "<bucket name>"
    prefix = "test"
  }
}

resource "google_service_account" "service_account" {
  project = var.gcp_project_id
  account_id   = "sarah-test-sa"
  display_name = "Made by Sarah testing a gcs backend update"
}

output "service_account_email" {
  value = google_service_account.service_account.email
}
```

3. Run `terraform plan` using terraform built from this PR immediately afterwards, to see if users are warned about changes - there are none
4. Update the service account description and apply the changes. There were no obvious change in user experience or any warnings in the terminal:

```
envchain google ~/go/bin/terraform@615f289 apply
```

```
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

**Comment by appilon** [comment]
I would like to defer to Megan for this PR, but I can step in the situation where there's an urgency.

**Comment by SarahFrench** [comment]
It turns out this PR isn't going to be just a simple refactor after all, so I've removed you from the reviewers for now but can re-add you later!

**Comment by SarahFrench** [comment]
Closing this PR as it got stale.

The choice to access ENVs with code in the configure functions, instead of using the `DefaultFunc` feature in the SDK, was intentional and mirrors approaches in the Google provider. If refactoring did take place it would need to be larger more deliberate project.

**Pull request closed without merging**
