### PR TITLE
provider/aws: New SSM Parameter resource

### PR DESCRIPTION
**Pull request by pmorton**
Hi - I have taken the work from #14043 / #11433 . I have done the following:

1. Addressed the code review comments
2. Added the ability to specify the KMS key to be used for `SecureString`
3. ForceNew when the `type` is changed (AWS Imposed Limitation)
4. Added a data source for ssm parameters

@tomelliff - Did most of the work, but since this is such a great community I thought I would pitch in an bring it over the finish line. Plus I could really use this provider ;)

@radeksimko Since you did the review on the other PR, ping. If you have free time.

### CODE REVIEW

**Comment by ozbillwang** [comment]
@pmorton 

I like this PR and hope it can be merged ASAP.  Do you mean #14043 can be deprecated? 

 Resource `SSM Parameter` (#14043) itself currently is in reviewing and not merged to master branch, your changes are based on it.  

Can I recommend, you fork @tomelliff 's repo, and raise PR to @tomelliff first, then add all features together with #14043?

**Comment by ozbillwang** [comment]
@pmorton 

Do you mean #14043 can be closed directly?

**Comment by pmorton** [comment]
@ozbillwang The PR is meant to be a replacement for #14043, so closing 14043 is likely a reasonable choice. Let me know if there is anything else I can do.

**Comment by radeksimko** [comment]
Hi @pmorton 
thank you for taking the time to address my comments regarding the resource.

> Added a data source for ssm parameters

Just a friendly advice for future contributions - we always prefer smaller PRs with ideally just single data source/resource. It's much easier to review as it's less LOC. 😅 

At the moment I can't merge this because the data source test is failing - most likely because it's expecting `test.parameter` to exist. We expect all acceptance tests to be as self sustainable as possible - that means we expect the test to also create such parameter before testing the behaviour of the data source.

See https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/data_source_aws_alb_test.go#L51 for example of how we test ALB data source.

```
=== RUN   TestAccAwsSsmParameterDataSource_basic
--- FAIL: TestAccAwsSsmParameterDataSource_basic (6.57s)
	testing.go:280: Step 0 error: Error refreshing: 1 error(s) occurred:

		* data.aws_ssm_parameter.test: 1 error(s) occurred:

		* data.aws_ssm_parameter.test: data.aws_ssm_parameter.test: [ERROR] SSM Parameter test.parameter is invalid
FAIL
```

**Comment by pmorton** [comment]
@radeksimko Thanks for the guidance. I have since reviewed the contribution guide (which was super helpful). I have fixed the integration tests. Let me know the next steps. Cheers.

**Comment by tomelliff** [comment]
@pmorton thanks for finishing this off, I've been utterly swamped since starting a new job so haven't had any time to look at this. Looking forward to being able to use this in the next release!

**Comment by ozbillwang** [comment]
So nice. It has been released in v0.9.7

**Pull request merged**
