### PR TITLE
Update `golang.org/x/oauth2` to `v0.17.0` for Google Cloud Storage SDK compatibility

### LINKED ISSUE #34234: Terraform doesn't support GCP "external_account_authorized_user"
### Terraform Version

```shell
v1.6.2aTerraform v1.6.3
on darwin_amd64
```

### Terraform Configuration Files

```terraform
provider "google" {
  region = "us-east1"
  project = "project-name"
}
terraform {
  backend "gcs" {
    bucket = "bucket-name"
    prefix = "state-name.tfstate"
  }
}
```

### Debug Output

2023-11-13T17:54:31.126Z [INFO]  Terraform version: 1.6.3
2023-11-13T17:54:31.127Z [DEBUG] using github.com/hashicorp/go-tfe v1.36.0
2023-11-13T17:54:31.127Z [DEBUG] using github.com/hashicorp/hcl/v2 v2.19.1
2023-11-13T17:54:31.127Z [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.1
2023-11-13T17:54:31.127Z [DEBUG] using github.com/zclconf/go-cty v1.14.1
2023-11-13T17:54:31.127Z [INFO]  Go runtime version: go1.21.3
2023-11-13T17:54:31.127Z [INFO]  CLI args: []string{"terraform", "init"}
2023-11-13T17:54:31.127Z [DEBUG] Attempting to open CLI config file: /Users/fabioantunes/.terraformrc
2023-11-13T17:54:31.127Z [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2023-11-13T17:54:31.128Z [INFO]  Loading CLI configuration from /Users/fabioantunes/.terraform.d/credentials.tfrc.json
2023-11-13T17:54:31.128Z [DEBUG] checking for credentials in "/Users/fabioantunes/.terraform.d/plugins"
2023-11-13T17:54:31.128Z [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2023-11-13T17:54:31.128Z [DEBUG] will search for provider plugins in /Users/fabioantunes/.terraform.d/plugins
2023-11-13T17:54:31.130Z [DEBUG] ignoring non-existing provider search directory /Users/fabioantunes/Library/Application Support/io.terraform/plugins
2023-11-13T17:54:31.130Z [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2023-11-13T17:54:31.130Z [INFO]  CLI command args: []string{"init"}

Initializing the backend...
2023-11-13T17:54:31.156Z [DEBUG] New state was assigned lineage "c7a673bd-fbc4-c147-1114-964bfdba5430"
2023-11-13T17:54:31.156Z [DEBUG] checking for provisioner in "."
2023-11-13T17:54:31.170Z [DEBUG] checking for provisioner in "/usr/local/bin"
2023-11-13T17:54:31.170Z [DEBUG] checking for provisioner in "/Users/fabioantunes/.terraform.d/plugins"
╷
│ Error: storage.NewClient() failed: dialing: unknown credential type: "external_account_authorized_user"

### Expected Behavior

Terraform init should work

### Actual Behavior

Terraform init fails even though the credentials are valid.

### Steps to Reproduce

1. `gcloud auth login`
2. `gcloud auth application-default login`
3.
``` 
cat /Users/fabioantunes/.config/gcloud/application_default_credentials.json
{
  "audience": "//iam.googleapis.com/locations/global/workforcePools/random/stuff/in/here/name-of-the-provider",
  "client_id": "randomnumber.apps.googleusercontent.com",
  "client_secret": "super-client-secret",
  "quota_project_id": "my-super-project",
  "refresh_token": "super-refresh-token",
  "token_info_url": "https://sts.googleapis.com/v1/introspect",
  "token_url": "https://sts.googleapis.com/v1/oauthtoken",
  "type": "external_account_authorized_user"
}
```
4. `terraform init`

### Additional Context

I have raised this with terragrunt as well and it seems they managed to fix this by upgrading the gcp SDK
https://github.com/gruntwork-io/terragrunt/pull/2775

### References

_No response_

### PR DESCRIPTION
**Pull request by bschaatsbergen**
Closes #34234

## Summary
The current implementation resolves version `v0.11.0` of the [golang.org/x/oauth2](https://pkg.go.dev/cloud.google.com/go/storage) package, and this update is necessary for compatibility with the Google Cloud Storage SDK, as per the token source application code in: https://github.com/hashicorp/terraform/blob/main/internal/backend/remote-state/gcs/backend.go#L148-L163

This pull request addresses an issue where we pass in (initialize) credentials of a type that isn't supported by the current ([golang.org/x/oauth2/google](https://pkg.go.dev/golang.org/x/oauth2)) package we use. The missing user type: `external_account_authorized_user` was introduced in version v0.12.0, released in September 2023. For more details, refer to the commit: https://cs.opensource.google/go/x/oauth2/+/43b6a7ba1972152df70cd1e5ac7705e981df5f66.

## Changes
- Upgraded the `golang.org/x/oauth2` package to version: `v0.17.0`

### CODE REVIEW

**Comment by bschaatsbergen** [comment]
It would be appreciated if someone could ack my investigation shared in #34234.

**Comment by crw** [comment]
Thanks for the submission, I'll bring it to triage.

**Comment by bschaatsbergen** [comment]
> Thanks for the submission, I'll bring it to triage.

Awesome, thanks @crw

**Comment by thomas-dussouillez** [comment]
Hello ! Any news/progress on this ? It's quite blocking for us :( Thank you !

**Review by alisdair — APPROVED** [review]

**Comment by alisdair** [comment]
Thanks for working on this!

**Pull request merged**
