### PR TITLE
provider/aws Return an error if PrincipalIsNotFound because of invalid parameter

### LINKED ISSUE #14179: aws_sns_topic_policy fails to return errors to user
Today I created an SNS topic policy that included an IAM role with a typo.  When specifying an IAM principal in a resource policy, AWS checks that the principal exists.  If it doesn't, the API returns a PrincipalNotFound error.  Rather than return the failure, terraform retries until timeout.

### Terraform Version
Terraform v0.9.4

### Affected Resource(s)
- aws_sns_topic_policy
- probably other resource policies, but I didn't test

### Terraform Configuration Files
```hcl
resource "aws_sns_topic" "test" {
  name = "topic"
}

resource "aws_sns_topic_policy" "test" {
  arn = "${aws_sns_topic.test.arn}"
  policy = <<EOF
{
    "Version": "2012-10-17",
    "Id": "default",
    "Statement": [
        {
            "Sid": "default",
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "arn:aws:iam::012345678901:role/wooo"
                ]
            },
            "Action": [
                "sns:Publish"
            ],
            "Resource": "${aws_sns_topic.test.arn}"
        }
    ]
}
EOF
}
```

### Expected Behavior
Terraform should've returned the AWS error that creating that policy generates:
```sh
$ aws sns set-topic-attributes --topic-arn arn:aws:sns:us-east-1:012345678901:topic --attribute-name Policy --attribute-value file://policy.json 

An error occurred (InvalidParameter) when calling the SetTopicAttributes operation: Invalid parameter: Policy Error: PrincipalNotFound
```

### Actual Behavior
```sh
$ terraform apply
...
aws_sns_topic_policy.test: Still creating... (2m40s elapsed)
aws_sns_topic_policy.test: Still creating... (2m50s elapsed)
Error applying plan:

1 error(s) occurred:

* aws_sns_topic_policy.test: 1 error(s) occurred:

* aws_sns_topic_policy.test: timeout while waiting for state to become 'success' (last state: 'retrying', timeout: 3m0s)
...
```

### Important Factoids
I guess terraform tolerates & retries to handle the case when the principal in question has just been created by terraform.  If there's a way for terraform to sort out the two cases by looking at the policy, it'd be great to get this error instead of waiting for timeout.

### PR DESCRIPTION
**Pull request by mbfrahry**
This PR fixes #14179 where a invalid principal name was passed into an `sns_topic`. 

```
make testacc TEST=./builtin/providers/aws/ TESTARGS='-run=TestAccAWSSNSTopic_withFakeIAMRole'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/05/04 15:07:54 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws/ -v -run=TestAccAWSSNSTopic_withFakeIAMRole -timeout 120m
=== RUN   TestAccAWSSNSTopic_withFakeIAMRole
--- PASS: TestAccAWSSNSTopic_withFakeIAMRole (72.10s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	72.135s
```

### CODE REVIEW

**Comment by grubernaut** [comment]
I don't believe this is actually a bug or a desired behavior. See: 
https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_sns_topic.go#L147
https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_sns_topic.go#L117

Also, if the `WaitForState()`, function will return after the timeout has already happened, thus not fixing the original issue. 

However, I'm not 100% clear on the SNS API, deferring to @catsby who wrote the original resource.

**Comment by mbfrahry** [comment]
You're right @grubernaut. I might have found the actual issue. First, we weren't passing the error returned when we had a principal not found. Second, we were exiting out of the waitForState function whenever we encountered an error.

**Comment by catsby** [comment]
@mbfrahry hey sorry for the delay here does this need to be moved to GitHub.com/terraform-providers/terraform-provider-aws?

**Comment by mbfrahry** [comment]
If it still has value, I'd love to see it in! I'll defer to you on this one.

**Comment by catsby** [comment]
@mbfrahry if #14179 is still an issue then yeah I'd say this still has value

**Comment by catsby** [comment]
@mbfrahry when you get some time please either close or migrate this, thanks!

**Comment by mbfrahry** [comment]
@catsby Migrated to https://github.com/terraform-providers/terraform-provider-aws/pull/1548

**Pull request closed without merging**
