### PR TITLE
Use standard AWS environment variables

### PR DESCRIPTION
**Pull request by sethvargo**
Fixes https://github.com/hashicorp/terraform/issues/850, but maintains backwards compatibility.

/cc @mitchellh @svanharmelen

### CODE REVIEW

**Comment by svanharmelen** [comment]
Following the preferred/standard AWS naming would (IMHO) indeed make sense. But personally I would not make the `MultiEnvDefaultFunc` part of `helper/schema`, but make it an AWS specific func only available in the AWS provider.

Allowing/supporting both variable names should be a temporary thing if you ask me. So maybe deprecate the old names for a few versions and with the 0.4.0 release (for example) only allow the new names and cleanup this temp fix/workaround?

My 2cts...

**Comment by sethvargo** [comment]
@svanharmelen that was my original intention. You can't see it from the git history, but the original prototype was to add a private func to `aws/provider.go` that delegated to the existing `EnvDefaultFunc`, but supported multiple values. But then I looked at the code more...

As a general rule, it looks like Terraform follows the `<provider>_<key_name>`  syntax for all of its environment variables (`AWS_ACCESS_KEY`, etc), and I wasn't sure about breaking that norm. Technically, either approach is fine, but I'm not sure what the UX should be... I thought it was weird that the envvars were not matching the "normal ones", but a different user could find it weird that the AWS environment variables do not map 1-1 with what is used inside a `.tf` file for example.

What do you think? I'm more than happy to move it back to a private func on the AWS provider :smile:

**Comment by svanharmelen** [comment]
Well... Personally I don't mind that much which name to use for the vars, as they both seem to have a valid thought behind them. The current one being inline with the others within TF, the latter one being inline with the AWS standards.

So I think maybe @armon or @mitchellh (who once choose the var names for this provider) are better candidates to have an opinion about what envvar names to use here.

But either way I do think that whatever the name should be, we should only one support 1 name for a given envvar and not multiple as it will only confuse things and make support cases more unclear.

So if the naming should change to the AWS standard names, then indeed I would prefer it to be a temp (for a few versions) private func inside the AWS provider...

**Comment by armon** [comment]
I agree. Let's do it a temporary backwards compatible fix, but eventually deprecate. I do think `MultiEnvDefaultFunc` maybe useful in other places for similar transitions, so the helper.Schema seems fine to me.

**Comment by sethvargo** [comment]
Created https://github.com/hashicorp/terraform/issues/866 to track the deprecation.

**Pull request merged**
