### PR TITLE
provider/aws: allow assocation of EIP to ENI

### LINKED ISSUE #1468: aws/eip: allow attachment to aws_network_interface
Hi,

In AWS, EIP's can be attached to an instance or an ENI.  Now that there's ENI support in 0.4.0, it makes sense to support attaching EIP's to them as well.

Currently, this fails on 0.4.1 with an invalid id error, I assume because the eip code assumes an ec2_instance.id

Thanks!

-n

### PR DESCRIPTION
**Pull request by jstremick**
Adds a new attribute 'network_interface' to the 'aws_eip' resource.

Resolves #1468

### CODE REVIEW

**Comment by mitchellh** [comment]
Sorry this no longer merges cleanly. Can you fix that? Thanks!

**Comment by jstremick** [comment]
All set, EIP acceptance tests still pass.

**Comment by JeanMertz** [comment]
looking forward to this :+1: (although it doesn't seem to merge cleanly anymore)

**Comment by mitchellh** [comment]
Thanks!

**Pull request merged**
