### PR TITLE
normalize all objects read from the provider

### PR DESCRIPTION
**Pull request by jbardin**
Use `objchange.NormalizeObjectFromLegacySDK` to ensure that all objects
returned from the provider match what is expected based on the
configuration according to the schemas.

This is intended to provide additional warnings about blocks that are unexpectedly altered, most commonly blocks that are marked as "computed" in `helper/schema`, which we don't intend to support in the same manner going forward.

### CODE REVIEW

**Comment by jbardin** [comment]
I'll just add those changes into this PR so they're in one place.

**Comment by jbardin** [comment]
@apparentlymart: were those all the places you were thinking of?

**Comment by mingfang** [comment]
Hi. I'm wondering if this is causing errors in my provider like these 
```attribute representing nested block must not be unknown itself; set nested attribute values to unknown instead```

Question is, why can't nested blocks be unknown, if the blocks are optional?

Let's say I have nest blocks like these
```hcl
optional_block1 {
  optional_block2 {
    //required_field = "foo", optional_block2 has a required field
  }
}
```
If I have a resource that does not set either optional_block1 or 2, then this normalization code will create this
```hcl
optional_block1 {
  optional_block2 {
  }
}
```
This is a problem since the required field is missing.

**Comment by jbardin** [comment]
Hi @mingfang 
This commit was reverted, so it's no longer a factor.
The Normalization mentioned is only executed just in time for the diff formatter so the values are correctly structured. You should not be seeing an errors from those, though there will be warnings in the logs when using the legacy sdk.

**Comment by mingfang** [comment]
@jbardin Thanks James.  

Something else must be creating those empty blocks then.  My blocks are set as Optional, Computed and AsSingle.  If I don't set AsSingle then the problem goes away.  I'll dig some more.

**Pull request merged**
