### PR TITLE
add support for `includes` function

### LINKED ISSUE #27198: Add a String `contains` or `includes` function that can replace the `can(regex(..., ...))` pattern
### Current Terraform Version

```
0.14.1
```

### Use-cases

The current solution for checking if a string var or local contains a given substring is typically done using `can(regex("substring_to_check", var.my_string))` ([and there are a number of other ways to do so as well](https://stackoverflow.com/questions/47243474/how-to-check-if-string-contains-a-substring-in-terraform-interpolation)). IMHO, this is pretty unintuitive as it requires using a couple functions and doesn't "read" well. 

The end goal of providing a specific function to handle this problem is to provide a cleaner and more concise way to accomplish the same.

### Attempted Solutions

As mentioned above, the current solution is typically done with `regex` and pals. There are many ways to accomplish this. 

### Proposal

I'm proposing that Terraform provide a native function to handle this instead of the unintuitive ways it's handled now. This can be seen in many programming languages: 

1. [Golang strings#Contains](https://golang.org/pkg/strings/#Contains)
1. [Ruby String#include?](https://ruby-doc.org/core-1.9.3/String.html#method-i-include-3F)
1. [JS string#includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes)

I believe a new function like `contains` (problematic because of the Collection `contains` function?) or `includes` would solve this problem elegantly. I think this is worth bringing up since this is such common business logic pattern. 

### References

N/A

### PR DESCRIPTION
**Pull request by njuCZ**
fix #27198

### CODE REVIEW

**Comment by jgrumboe** [comment]
@njuCZ 
Wouldn't "include**s**" be a better functionname in analogy to "contains"?
"Include" sounds more imperative than "includes" which sounds like a question, which the function actually is.

**Comment by njuCZ** [comment]
@jgrumboe I have resolved the conflict. In fact, there is already a `contains` func, it's used to check whether a list contains an element. So I used `include`

**Comment by njuCZ** [comment]
@jgrumboe I have refactor it to `includes`.

**Review by daksh-sagar — APPROVED** [review]

**Comment by orgads** [comment]
Is anything blocking this PR from being merged, except rebase?

**Comment by Cliftonz** [comment]
@njuCZ  Is anything blocking this PR?

**Comment by crw** [comment]
@Cliftonz I am checking in with the team. Will put this back on the queue for triage. If the core team gives the thumbs-up, then @njuCZ would need to rebase (and fix any potential feedback) before it could be merged. Thanks!

**Comment by Cliftonz** [comment]
@crw  Thank you! If @njuCZ  is unavailable I am happy to take this over.

**Comment by Cliftonz** [comment]
@kmoe  Is there any issue if I make a new pull request as OP is not responding?

**Comment by njuCZ** [comment]
@Cliftonz thanks if you can take over this PR. (It seems the CI needs to deploy a github app and I can't do that for current account). I will close it for now.

**Comment by Cliftonz** [comment]
@njuCZ  No problem, thank you for getting this going!

**Pull request closed without merging**
