### PR TITLE
[WIP] Partial Apply for Computed Provider Configuration

### PR DESCRIPTION
**Pull request by apparentlymart**
> **This is not yet ready to merge, but the code here so far is functional and so I'm posting it for a general design review before I proceed any further with polish, tests, docs, etc.**

This is an implementation of the "partial apply" concept proposed in #4149, along with a first use for this concept: deferring instantiation of providers with computed configurations.

As an example of what this is about, consider the following configuration:

``` hcl
data "docker_registry_image" "consul" {
  name = "consul"
}

resource "docker_image" "consul" {
  name         = "${data.docker_registry_image.consul.name}"
  pull_trigger = "${data.docker_registry_image.consul.sha256_digest}"
}

resource "docker_container" "consul" {
  name  = "consul-for-terraform-testing"
  image = "${docker_image.consul.latest}"

  env = [
    "CONSUL_BIND_INTERFACE=eth0",
    "CONSUL_CLIENT_INTERFACE=eth0",
  ]

  provisioner "local-exec" {
    # this script polls the consul kv API until it returns a 200 OK status,
    # working around the fact that Terraform can't tell when the consul
    # server has finished bootstrapping.
    command = "./wait-for-consul"
  }
}

provider "consul" {
  address = "${docker_container.consul.ip_address}:8500"
}

resource "consul_key_prefix" "test" {
  path_prefix = "test/"

  subkeys = {
    hi = "world"
  }
}
```

This configuration is an example of what I've come to refer to as a "multi-layer" Terraform configuration. In this case, the layers are Docker, which is being used to start up a Consul server, and Consul itself.

In Terraform _today_, this configuration is problematic in two situations:
- On initial run from an empty state, Terraform will attempt to instantiate the `consul` provider during the Plan phase, when the `address` argument is not yet resolvable. This causes the `consul` provider to use the literal string `${docker_container.consul.ip_address}:8500` as its Consul address, which fails.
- Once this stack has been created, If the docker container is deleted outside of Terraform, on the next Refresh pass Terraform will correctly detect that the container is gone, but it will then fail trying to refresh `consul_key_prefix.test`.

In both of these situations, Terraform _today_ requires the use of `-target=docker_container.consul` on the first run in order to help Terraform understand how to apply the configuration in multiple steps.

The _partial apply_ mechanism added here allows Terraform to automatically recognize when the configuration must be applied across multiple passes, and to guide the user through the necessary steps while automatically excluding the parts of the configuration that are not ready to be planned.

---

Since this is a UX change, let's walk through the user experience when applying the above configuration, so we can see how this plays out in practice.

The first step is the same as usual:

```
$ terraform plan -input=false -out=tfplan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

data.docker_registry_image.consul: Refreshing state...
docker_image.consul: Refreshing state... (ID: b04f6ab77bb82ae613256022c560002956eed1076c761410513b5e8421534fa5consul)

The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed. Cyan entries are data sources to be read.

Your plan was also saved to the path below. Call the "apply" subcommand
with this plan file and Terraform will exactly execute this execution
plan.

Path: tfplan

+ docker_container.consul
    bridge:           "<computed>"
    env.#:            "2"
    env.2438063316:   "CONSUL_BIND_INTERFACE=eth0"
    env.852711472:    "CONSUL_CLIENT_INTERFACE=eth0"
    gateway:          "<computed>"
    image:            "b04f6ab77bb82ae613256022c560002956eed1076c761410513b5e8421534fa5"
    ip_address:       "<computed>"
    ip_prefix_length: "<computed>"
    log_driver:       "json-file"
    must_run:         "true"
    name:             "consul-for-terraform-testing"
    restart:          "no"


Terraform is not able to apply this configuration in a single step. The plan
above will partially apply the configuration, after which you can run
"terraform plan" again to plan the next set of changes to converge on the
state given in your configuration.

The following resources are being deferred:
- all from provider consul:
    "address" not yet resolvable: ${docker_container.consul.ip_address}:8500


Plan: 1 to add, 0 to change, 0 to destroy.
```

On the first run, Terraform detects that the `consul` provider configuration cannot yet be evaluated and so defers all resources belonging to that provider. It produces a plan containing the maximal set of changes that _can_ be applied, and explains to the user why the rest cannot be applied yet.

If desired, we can use `terraform graph tfplan` to get a more detailed understanding of what's going on with this plan, with deferred nodes and edges de-emphasized:

graph

We can now apply the plan:

```
$ terraform apply tfplan
docker_container.consul: Creating...
  bridge:           "" => "<computed>"
  env.#:            "" => "2"
  env.2438063316:   "" => "CONSUL_BIND_INTERFACE=eth0"
  env.852711472:    "" => "CONSUL_CLIENT_INTERFACE=eth0"
  gateway:          "" => "<computed>"
  image:            "" => "b04f6ab77bb82ae613256022c560002956eed1076c761410513b5e8421534fa5"
  ip_address:       "" => "<computed>"
  ip_prefix_length: "" => "<computed>"
  log_driver:       "" => "json-file"
  must_run:         "" => "true"
  name:             "" => "consul-for-terraform-testing"
  restart:          "" => "no"
docker_container.consul: Provisioning with 'local-exec'...
docker_container.consul (local-exec): Executing: /bin/sh -c "./wait-for-consul"
docker_container.consul: Creation complete

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate

This plan has only partially applied the configuration.
Run 'terraform plan' again now to plan the next set of changes to converge
on the desired state.
```

Terraform has now applied the subset of the configuration that it said it would, but reminds the user at the end of the output that this wasn't the whole configuration and that we need to iterate again.

So we repeat the first step:

```
$ terraform plan -input=false -out=tfplan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

data.docker_registry_image.consul: Refreshing state...
docker_image.consul: Refreshing state... (ID: b04f6ab77bb82ae613256022c560002956eed1076c761410513b5e8421534fa5consul)
docker_container.consul: Refreshing state... (ID: a7baccf3aec1676fd549c1b36e9aac1f1e8a8a1e902bba4756d1be9863ce5207)
consul_key_prefix.test: Refreshing state... (ID: test/)

The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed. Cyan entries are data sources to be read.

Your plan was also saved to the path below. Call the "apply" subcommand
with this plan file and Terraform will exactly execute this execution
plan.

Path: tfplan

~ consul_key_prefix.test
    subkeys.%:  "0" => "1"
    subkeys.hi: "" => "world"


Plan: 0 to add, 1 to change, 0 to destroy.
```

Now Terraform can successfully plan the `consul_key_prefix.test` resource, because the `consul` provider has a completely-resolved configuration. Nothing is deferred this time, so this looks like the plan output we're used to.

We can now apply this second plan:

```
$ terraform apply tfplan
consul_key_prefix.test: Modifying...
  subkeys.%:  "0" => "1"
  subkeys.hi: "" => "world"
consul_key_prefix.test: Modifications complete

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate
```

As promised, the `consul_key_prefix` resource is created, and Terraform completes successfully. The state now matches the configuration, as we can find out by running the plan one more time:

```
$ terraform plan -input=false -out=tfplan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

data.docker_registry_image.consul: Refreshing state...
docker_image.consul: Refreshing state... (ID: b04f6ab77bb82ae613256022c560002956eed1076c761410513b5e8421534fa5consul)
docker_container.consul: Refreshing state... (ID: a7baccf3aec1676fd549c1b36e9aac1f1e8a8a1e902bba4756d1be9863ce5207)
consul_key_prefix.test: Refreshing state... (ID: test/)

No changes. Infrastructure is up-to-date. This means that Terraform
could not detect any differences between your configuration and
the real physical resources that exist. As a result, Terraform
doesn't need to do anything.
```

In most situations, this is where we'd stay... we'll leave the consul server running, and subsequent runs might update the keys under our prefix but we won't mess with that Docker container much.

However, let's consider what happens in the situation where that docker container gets deleted outside of Terraform's view for some reason:

```
$ docker stop consul-for-terraform-testing
$ docker rm consul-for-terraform-testing
```

Next time we run Terraform:

```
$ terraform plan -input=false -out=tfplan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

data.docker_registry_image.consul: Refreshing state...
docker_image.consul: Refreshing state... (ID: b04f6ab77bb82ae613256022c560002956eed1076c761410513b5e8421534fa5consul)
docker_container.consul: Refreshing state... (ID: a7baccf3aec1676fd549c1b36e9aac1f1e8a8a1e902bba4756d1be9863ce5207)

The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed. Cyan entries are data sources to be read.

Your plan was also saved to the path below. Call the "apply" subcommand
with this plan file and Terraform will exactly execute this execution
plan.

Path: tfplan

+ docker_container.consul
    bridge:           "<computed>"
    env.#:            "2"
    env.2438063316:   "CONSUL_BIND_INTERFACE=eth0"
    env.852711472:    "CONSUL_CLIENT_INTERFACE=eth0"
    gateway:          "<computed>"
    image:            "b04f6ab77bb82ae613256022c560002956eed1076c761410513b5e8421534fa5"
    ip_address:       "<computed>"
    ip_prefix_length: "<computed>"
    log_driver:       "json-file"
    must_run:         "true"
    name:             "consul-for-terraform-testing"
    restart:          "no"


Terraform is not able to apply this configuration in a single step. The plan
above will partially apply the configuration, after which you can run
"terraform plan" again to plan the next set of changes to converge on the
state given in your configuration.

The following resources are being deferred:
- all from provider consul:
    "address" not yet resolvable: ${docker_container.consul.ip_address}:8500


Plan: 1 to add, 0 to change, 0 to destroy.
```

During the Refresh walk, Terraform detected that the Docker container was deleted. Later in the walk, it detected that the `consul` provider's configuration is back to being unresolvable again, since we no longer have a docker container instance. Thus Terraform defers dealing with the resources from that provider, since it's not safe nor reasonable to make plans about those resources if we aren't able to refresh them.

This time, just to illustrate an alternative, more cavalier workflow, we'll ignore the plan file that was created and just run `terraform apply` with no arguments:

```
$ terraform apply -input=false
data.docker_registry_image.consul: Refreshing state...
docker_image.consul: Refreshing state... (ID: b04f6ab77bb82ae613256022c560002956eed1076c761410513b5e8421534fa5consul)
docker_container.consul: Refreshing state... (ID: a7baccf3aec1676fd549c1b36e9aac1f1e8a8a1e902bba4756d1be9863ce5207)
docker_container.consul: Creating...
  bridge:           "" => "<computed>"
  env.#:            "" => "2"
  env.2438063316:   "" => "CONSUL_BIND_INTERFACE=eth0"
  env.852711472:    "" => "CONSUL_CLIENT_INTERFACE=eth0"
  gateway:          "" => "<computed>"
  image:            "" => "b04f6ab77bb82ae613256022c560002956eed1076c761410513b5e8421534fa5"
  ip_address:       "" => "<computed>"
  ip_prefix_length: "" => "<computed>"
  log_driver:       "" => "json-file"
  must_run:         "" => "true"
  name:             "" => "consul-for-terraform-testing"
  restart:          "" => "no"
docker_container.consul: Provisioning with 'local-exec'...
docker_container.consul (local-exec): Executing: /bin/sh -c "./wait-for-consul"
docker_container.consul: Creation complete
data.docker_registry_image.consul: Refreshing state...
docker_image.consul: Refreshing state... (ID: b04f6ab77bb82ae613256022c560002956eed1076c761410513b5e8421534fa5consul)
docker_container.consul: Refreshing state... (ID: ba0dcebc925cb42f4faff9507b99e41f17b1faa776ba780dfa7cf660803c9d50)
consul_key_prefix.test: Refreshing state... (ID: test/)
consul_key_prefix.test: Modifying...
  subkeys.%:  "0" => "1"
  subkeys.hi: "" => "world"
consul_key_prefix.test: Modifications complete

Apply complete! Resources: 1 added, 1 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate
```

A bare `terraform apply` behaves a little differently. Since the user doesn't care to view and approve the plan before proceeding, we just automatically run multiple plan/apply passes until we reach either an error or a success with no deferrals. In this case Terraform just "does what I mean", and doesn't trouble me with thinking about the fact that it takes multiple passes to reach this state. Certainly this approach is not recommended for production, but it provides a simpler path for those still learning/experimenting.

---
# How it works

There are several parts to the problem here:
- Detecting that a provider needs to be deferred.
- Detecting and transforming deferred nodes in the graph, including propagation of deferrals to dependent nodes.
- UX/workflow changes to support this.

The detection of deferrals happens during the _refresh_ and _plan_ phases. It needs to be done in two parts because each part detects different situations:
- Refresh: Provider depends on a resource that either hasn't been created yet or that an earlier `Read` has discovered has been deleted outside of Terraform.
- Plan: Provider depends on a resource that is being replaced due to a change to an argument that has `ForceNew` set.

During each of these walks, a deferred provider is skipped but its resources are still visited. Thus we must gracefully handle this during evaluation, by doing an _early exit_ from the evaluation if we try to retrieve a deferred provider.

Once a provider is deferred by one walk, it is automatically deferred for all _subsequent_ walks. That is,  a provider deferred during refresh cannot become un-deferred during a subsequent plan if both of these walks are happening during a single run. The rationale for this design is that unless the user specifically disabled refresh with `-refresh=false` we should not attempt to plan resources whose states may be stale.

On subsequent walks, the graph is transformed such that deferred nodes are replaced with no-op placeholder nodes. These nodes do nothing during evaluation, but allow the deferred nodes to be seen in the `terraform graph` output. This transformation operates under a similar principle to how the `-target` argument is handled, but inverted since deferrals are conceptually "anti-targets", excluding particular nodes.

The deferrals that are present at the end of the Plan walk are recorded in the plan so they can propagate into a subsequent run of `terraform apply` against that plan.

The UX changes are then implemented in terms of the above:
- For `terraform plan`, an additional note is added to the end of the plan output if there are deferrals recorded in the plan.
- For `terraform apply {planfile}`, an additional note is added to the end of the output when the plan contains deferrals, to remind the user that they need to run `terraform plan` again to see the next step.
- For `terraform apply` with no arguments, this is treated as if the user were repeatedly running `terraform plan -out=tfplan` and `terraform apply tfplan` until either there are no more deferrals or until an error occurs.

### CODE REVIEW

**Comment by mkuzmin** [comment]
Is there a chance to have this feature finished and merged before 0.8?
I've tested it briefly on the original revision, and it does work.
Unfortunately, now it conflicts with recent commits related to a shadow apply. I wasn't able to rebase the branch on my own.

Of course, Vault and Nomad providers are major features for the next release, but this issue is a real show-stopper for using terraform with layered infrastructure.
My current use case is a common Terraform configuration with EC2 instances, Docker containers, InfluxDB databases, and Grafana dashboards.

Thanks!

**Comment by greenboxal** [comment]
What's the status on this? We have a fully layered infrastructure built ground up on AWS with terraform and we need to circumvent those issues you described with ugly hacks.

@apparentlymart do you need any help on this? we're interested in helping if you need

**Comment by apparentlymart** [comment]
Hi @greenboxal! Thanks for the offer.

I ended up putting this on ice for a while because the Terraform core team was redesigning a bunch of Terraform's core architecture for 0.8 and 0.9 and it seemed better to let that stabilize first. I have on my to-do list the task of getting up to speed on how things have changed and taking another swipe at this, but I expect I won't do it until at least after 0.9 is out so I have a stable state to study.

**Comment by greenboxal** [comment]
Ok, great to know. But, just in case, do this branch in the current state work? (at least partially)

If so we may try to rebase it against our current version until this is merged.

**Comment by apparentlymart** [comment]
@greenboxal I have not tested it, but I doubt it works. It was built within what is now the legacy graph builder, which is being removed in 0.9. I expect lots of it needs to be rewritten to fit into the new refresh-specific and plan-specific graph builders, which are now distinct codepaths.

**Comment by stack72** [comment]
@apparentlymart I think it's worth closing this due to 0.9 - thoughts?

**Comment by mitchellh** [comment]
I just read this PR for the first time (missed it up to this point, sorry). I really like the notion of deferrals and its pretty close to what I had in mind for how to solve this problem. 

With the new graphs I wonder if this becomes easier since the Apply graph only contains what is in the diff (making deferrals implicit but w/o UX help). I wonder if we can use that to make this work in the short term, and improve the UX and visibility that a change requires multi-phased applies later.

Actually, the new dag/walker I merged that allows dynamic graph changes could help with this too: we can remove/defer the entire subgraph past a certain point and have dag/walker remove the entire thing. Just saying ideas as I have them though so it may be a bad idea. 

I agree that these changes are super incompatible with the current core state so I'm going to close this, but the core idea here is still highly applicable.

**Pull request closed without merging**
