### PR TITLE
Modify parameter_group_name to db_cluster_parameter_group_name

### PR DESCRIPTION
**Pull request by ijin**
for #7046

### CODE REVIEW

**Comment by catsby** [comment]
Thanks @ijin – I opened https://github.com/hashicorp/terraform/pull/7083 that builds off of this. It keeps the old parameter name around but marks it as deprecated. I realize its likely the number of people using `master` or the release candidate and also using this parameter is probably pretty small, but I though it a nice thing to do. What do you think?

**Comment by ijin** [comment]
@catsby Thanks. I just thought it would be easier to change the parameter name now before the official release of v0.7.0. Although it feels weird having a deprecation message from RC, I do understand your concerns for maintaining compatibility. How far in the future would removing the old parameter make sense? I could submit a pullreq when the time comes.

**Comment by catsby** [comment]
It's absolutely easier to change it now, since v7 isn't officially out! 
I did however personally point a handful of people to _this particular_ config attribute, so I was happy to put in the little bit of extra code to make things smoother. 

I've made a self-note to remove the attribute in the future. Our versioning and release schedule is not fixed, so it's hard to say when it will happen, likely a release or three. Thanks!

**Comment by ijin** [comment]
Ok, got it! 👍

**Pull request closed without merging**
