### PR TITLE
Updating sensitive/nonsensitive docs with v0.14 specifics.

### PR DESCRIPTION
**Pull request by stevematney**
A continuation of #28492 with more correct info.

### CODE REVIEW

**Review by alisdair — CHANGES_REQUESTED** [review]
Thanks for the contribution. I don't think this is correct; the `nonsensitive` and `sensitive` functions were only introduced for 0.15, and are not available in 0.14 at all.

**Comment by alisdair** [comment]
Sorry, after clicking through to the previous PR, I can see you were given guidance in the opposite direction! I'm really pretty sure that was just a mistake:

```hcl
terraform {
  experiments = [provider_sensitive_attrs]
}

output "foo" {
  value = sensitive("foo")
}
```

```shellsession
$ terraform-0.14.11 plan

Warning: Experimental feature "provider_sensitive_attrs" is active

  on main.tf line 2, in terraform:
   2:   experiments = [provider_sensitive_attrs]

Experimental features are subject to breaking changes in future minor or patch
releases, based on feedback.

If you have feedback on the design of this feature, please open a GitHub issue
to discuss it.


Error: Call to unknown function

  on main.tf line 6, in output "foo":
   6:   value = sensitive("foo")

There is no function named "sensitive".
```

If you would like to update these two lines to instead just read "This function is only available in Terraform v0.15 and later", I'd be happy to merge.

**Comment by apparentlymart** [comment]
We have typically dropped mentions of an experiment once it's concluded, even though it technically remains available in older versions, because the goal of experiments is to gather feedback and we are typically no longer interested in feedback on the experimental feature once the experiment has concluded. (We are, of course, still interested in feedback on the _shipped_ feature, but the experimental precursor to it becomes irrelevant as soon as the experiment concludes.)

This particular case was a bit more messy because I believe we'd originally intended to include these functions earlier but then there was some delay before merging, and so by the time we merged the documentation wasn't correct anymore. I'd agree with @alisdair though that in the long run we'd be best served by just keeping this simple and saying that the function is only in v0.15 and later, because that'll keep the content of this callout box shorter and easier to scan.

**Comment by stevematney** [comment]
I've updated with (I think) the correct v0.15 info. My editor automatically runs Prettier on save of markdown files, and it looks like it moved some words around. I hope that's ok!

I also corrected a misspelling.

**Review by alisdair — APPROVED** [review]
Thank you!

**Comment by alisdair** [comment]
Cherry-picked to v0.15 as 618ddfba0

**Pull request merged**
