### PR TITLE
Added ability to show specified types of resources

### PR DESCRIPTION
**Pull request by little-arhat**
New argument `-resource-types` for `show` command allows to specify list
of resource types, i.e. "aws_instance,aws_db_instance" to limit output
for these types.

This is useful for ad-hoc queries regarding Terraform state -- getting
list of particular attributes, like ip addresses or tags, etc.

Since output of `terraform show` is not json, where tools like `jshon`
can be applied to filter, it's useful to have smth like proposed changes.

### CODE REVIEW

**Comment by jen20** [comment]
Hi @little-arhat! Thanks for submitting this. I'd agree this functionality could be hard to replicate using filters in a pipeline and could be valuable. Is there any chance you could add a context test or two to verify expected behaviour? If not I can likely look at doing so but it may take a while longer.

**Comment by little-arhat** [comment]
@jen20 cool, will look into this! Do you have any comments on functionality itself? anything else we should think of, some corner cases maybe?

**Comment by little-arhat** [comment]
@jen20 tests added

**Comment by jen20** [comment]
Thanks @little-arhat! Sorry for the delay on reviewing this.

**Comment by little-arhat** [comment]
@jen20 Happy New Year! is everything ok with this? any other suggestion/fixes you might think of?

**Comment by josephholsten** [comment]
@phinze, @mitchellh this is ready for your :eyes:, has tests, needs doc

**Comment by phinze** [comment]
The implementation here looks good! But I'm a little worried about potential "flag sprawl" by adding this feature. Picturing possible ways you might want to filter terraform show output, I can think of -resource-names, -module-names, etc., not to mention the negation side of all those options.

I'm thinking it might be a better strategy to try to address terraform show output filtering in a more holistic way. Two ideas:

(a) Add a JSON output format to terraform show, which would let users slice and dice the output with something like jq
(b) Support the full -target syntax on terraform show which would keep things consistent but allow scoping the output.

In order to do filtering equivalent to this, you'd need something more like (a).

**Comment by josephholsten** [comment]
@little-arhat @phinze Just wanted to note that the original recommendation for how to solve this: `terraform show -json | jq ...` has been taken off the table with https://github.com/hashicorp/terraform/issues/2460

Are we okay with "(b) Support the full -target syntax on terraform show which would keep things consistent but allow scoping the output."

**Comment by mildwonkey** [comment]
Hi folks! Sorry for the long, long silence here.

Now that `terraform show` has a [`-json` flag](https://www.terraform.io/docs/commands/show.html#json-output) which will let users (consistently!) "slice and dice the output" (to borrow phinze's phrase), I am going to close this PR. Thanks for all your work and the good conversation!

**Pull request closed without merging**
