### PR TITLE
[WIP] Better display for set diffs, drop unchanged elements

### PR DESCRIPTION
**Pull request by Bowbaq**
@apparentlymart @phinze initial crack at the problem for #5179

### CODE REVIEW

**Comment by tecnobrat** [comment]
@Bowbaq if I understand correctly this removes all of the beanstalk diffs where a value has not actually changed?  This is awesome if so, what needs to happen next?

**Comment by Bowbaq** [comment]
@tecnobrat correct, I've been using this on my custom branch of terraform, it works pretty well. Not sure what's next ...

**Comment by tecnobrat** [comment]
@apparentlymart whats the next step here?  Our beanstalk diffs are HUGE, and its extremely hard to see what has really changed.

**Comment by apparentlymart** [comment]
Hi @Bowbaq! Thanks for posting this and sorry I took so long to get back to you about it.

I tried to test this but couldn't figure out what sort of change I'd need to make to see the effect of this change.

Would you mind posting the configuration you were using to test this change along with what output you saw when you ran `terraform plan` with that configuration? That'll help me understand the intent of this change.

So far I tried to test with an `aws_security_group`'s `ingress` set, but I couldn't see a difference compared to how it used to behave:

```hcl
resource "aws_security_group" "foo" {
  name = "matkins-baz-test"
  description = "testing"

  ingress {
    from_port = 22
    to_port = 22
    protocol = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  ingress {
    from_port = 80
    to_port = 80
    protocol = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
}
```

I created the above and then changed the `to_port` in the first block to `23`. This is what the plan looked like:

```
~ aws_security_group.foo
    ingress.2152932494.cidr_blocks.#:     "0" => "1"
    ingress.2152932494.cidr_blocks.0:     "" => "0.0.0.0/0"
    ingress.2152932494.from_port:         "" => "22"
    ingress.2152932494.protocol:          "" => "tcp"
    ingress.2152932494.self:              "" => "false"
    ingress.2152932494.to_port:           "" => "23"
    ingress.2541437006.cidr_blocks.#:     "1" => "0"
    ingress.2541437006.cidr_blocks.0:     "0.0.0.0/0" => ""
    ingress.2541437006.from_port:         "22" => "0"
    ingress.2541437006.protocol:          "tcp" => ""
    ingress.2541437006.self:              "false" => "false"
    ingress.2541437006.to_port:           "22" => "0"
```

Am I doing something wrong here, or am I just misunderstanding your goal?

**Comment by Bowbaq** [comment]
@apparentlymart in your example, without this change, you'd also see something like:
```
ingress.1234567891.cidr_blocks.1:     "0.0.0.0/0" => "0.0.0.0/0"
ingress.1234567891.from_port:         "80" => "80"
ingress.1234567891.protocol:          "tcp" => "tcp"
ingress.1234567891.self:              "false" => "false"
ingress.1234567891.to_port:           "80" => "80"
```
In the case of elasticbeanstalk, which was my use case, this actually makes most diffs unreadable.

It was a stretch goal of mine to also be able to detect changes in sets and cleanup the leftover output from your example to something like the following:
```
~ aws_security_group.foo
    ingress.0.to_port:           "22" => "23"
```
or maybe
```
~ aws_security_group.foo
    ingress.0.cidr_blocks.0:     "0.0.0.0/0" => "0.0.0.0/0"
    ingress.0.from_port:         "22" => "22"
    ingress.0.protocol:          "tcp" => "tcp"
    ingress.0.self:              "false" => "false"
    ingress.0.to_port:           "22" => "23"
```
I just never got around to it.

**Comment by apparentlymart** [comment]
Oh okay @Bowbaq... I see what you mean now. You just wanted to omit the whole items that are unchanged, and focus only one the ones that *are* changed. Makes sense!

I'll take another look at this soon.

**Comment by tecnobrat** [comment]
This is close, but its not quite there.  It breaks the diff on things like security group strings that are comma separated:

```
~ aws_elastic_beanstalk_environment.poco
    setting.1111684148.name:      "" => "LoadBalancerType"
    setting.1111684148.namespace: "" => "aws:elasticbeanstalk:environment"
    setting.1111684148.resource:  "" => ""
    setting.1111684148.value:     "" => "application2"
    setting.1220848252.name:      "Subnets" => "Subnets"
    setting.1220848252.namespace: "aws:ec2:vpc" => "aws:ec2:vpc"
    setting.1220848252.resource:  "" => ""
    setting.1220848252.value:     "subnet-a644ebd0,subnet-a6ae3e9b,subnet-a8de1ff0" => "subnet-a644ebd0,subnet-a8de1ff0,subnet-a6ae3e9b"
    setting.3325418587.name:      "SecurityGroups" => "SecurityGroups"
    setting.3325418587.namespace: "aws:autoscaling:launchconfiguration" => "aws:autoscaling:launchconfiguration"
    setting.3325418587.resource:  "" => ""
    setting.3325418587.value:     "sg-0042d47a,sg-c82887b0" => "sg-c82887b0,sg-0042d47a"
    setting.4278593597.name:      "LoadBalancerType" => ""
    setting.4278593597.namespace: "aws:elasticbeanstalk:environment" => ""
    setting.4278593597.resource:  "" => ""
    setting.4278593597.value:     "application" => ""
    setting.965499686.name:       "ELBSubnets" => "ELBSubnets"
    setting.965499686.namespace:  "aws:ec2:vpc" => "aws:ec2:vpc"
    setting.965499686.resource:   "" => ""
    setting.965499686.value:      "subnet-17f0314f,subnet-e559c9d8,subnet-f852fd8e" => "subnet-f852fd8e,subnet-17f0314f,subnet-e559c9d8"
```

Normally the subnet changes are not seen as diff changes, but they are now shown in the output due to how this PR handles "what is equal" in its calculation.

**Comment by myoung34** [comment]
Any updates to this? The behavior is driving me mad.

**Comment by tecnobrat** [comment]
@Bowbaq any update on this PR?

**Comment by Bowbaq** [comment]
@tecnobrat I'm no longer working w/ Beanstalk + terraform so this isn't an immediate priority for me. If there's interest from the terraform team, I can try to get this over the line. Do I need to do anything besides rebasing?

**Comment by catsby** [comment]
Hey @Bowbaq I apologize for the silence here – yes could you please rebase? Let me know if that doesn't go well, and thanks for all the work so far!

**Comment by Bowbaq** [comment]
@catsby that file doesn't appear to exist anymore, looks like most of it maybe went to https://github.com/hashicorp/terraform/blob/master/command/format/plan.go, but it's unclear

**Comment by catsby** [comment]
@Bowbaq ah, sorry, indeed it was renamed/moved in #11286 

screen shot 2017-02-09 at 4 46 20 pm

**Comment by myoung34** [comment]
@catsby @Bowbaq i need this in my life =(

**Comment by josephholsten** [comment]
Rebased into https://github.com/hashicorp/terraform/pull/15265

**Comment by jbardin** [comment]
This no longer applies, as similar changes have been made.

**Pull request closed without merging**
