### PR TITLE
Add missing defaults for salt masterless

### PR DESCRIPTION
**Pull request by leslitagordita**
Defaults were added for` remote_pillar_roots`
and `remote_state_tree`.

This will fix issue [17150](https://github.com/hashicorp/terraform/issues/17150). (I *think*)

### CODE REVIEW

**Comment by jcockhren** [comment]
@leslitagordita Your solution is very similar to PR #17151. Been trying to get the fix merged for almost a year.

**Comment by leslitagordita** [comment]
@jcockhren Ah, I missed your PR. Well, here's hoping a fix gets in. I'll submit a PR to update the documentation at the very least, so others don't get confused and spend too much time hunting around. Thanks!

**Comment by SpencerSharkey** [comment]
Bumping this issue too.

We are currently relying on our own build of terraform, please merge either this PR or #17151 - it's a harmless patch.

**Comment by azban** [comment]
this can be closed now, due to the merge of https://github.com/hashicorp/terraform/pull/17151

**Comment by danieldreier** [comment]
Hi @acornies -

I'm closing this PR because we announced tool-specific (vendor or 3rd-party) provisioner deprecation in [mid-September 2020](https://discuss.hashicorp.com/t/notice-terraform-to-begin-deprecation-of-vendor-tool-specific-provisioners-starting-in-terraform-0-13-4/13997). Additionally, we added a deprecation notice for tool-specific provisioners in 0.13.4. On a practical level this means we will no longer be reviewing or merging PRs for these built-in plugins.

For the time being, the best option if you want to incorporate this change, is to extract the salt-masterless provisioner from the core codebase and distribute it as a plugin binary, similar to how the [ansible provisioner](https://github.com/radekg/terraform-provisioner-ansible) is distributed. I'm aware of the limitations of this approach, but it's the less-bad option compared to coupling provisioner development to the Terraform Core release lifecycle. We believe the benefit to users of having provisioner development decoupled from core, exceeds the convenience of having these provisioners built in to core. We want to provide a better user experience in the future, and our hope here is that the ability to improve, fix and repair provisioners without us blocking their development, much like providers, will help make a strong case for what's next.

I think it’s also important to highlight that we have no plans to remove the generic provisioners or the pluggable functionality during Terraform's 1.0 lifecycle. 

I appreciate your work here to improve Terraform, and am always happy to talk. Please feel free to reach out to me or Petros Kolyvas if you would like to talk more about this change.

**Pull request closed without merging**
