### PR TITLE
provider/aws: allow key_pair name to be generated

### PR DESCRIPTION
**Pull request by phinze**

### CODE REVIEW

**Comment by knuckolls** [comment]
Just curious, what is the use case for this?

**Comment by phinze** [comment]
As a module author, I'd like to be able to create a module that includes a key_pair. 
I don't care about the name, I only know I don't want it to collide with anything else in the account.

This allows my module to be used multiple times in the same account without having to do anything funky like adding a user-specified unique name parameter.

**Comment by phinze** [comment]
For my money, TF should do this for every AWS resource that must have a unique name.

I'd like to enhance the feature down the road so that we can let users define a custom prefix (while retaining the UUID suffix) to help folks who want to visually distinguish stuff.

**Comment by knuckolls** [comment]
Interesting. That makes sense. Thanks for the infobits. :+1:

**Comment by catsby** [comment]
LGTM :rocket:

**Comment by mitchellh** [comment]
LGTM

**Pull request merged**
