### PR TITLE
deps: Migrate to govendor

### PR DESCRIPTION
**Pull request by jen20**
This pull request migrates Terraform to use `govendor` instead of `godep`, as a number of HashiCorp tools have switched recently.

### CODE REVIEW

**Comment by jen20** [comment]
cc @phinze @sean- @catsby @jbardin

**Comment by jbardin** [comment]
I'm 👍 considering my recent godeps experience. We need to update the REAME to.

**Comment by jen20** [comment]
Now updated the README and rebased on top of the latest changes.

**Comment by phinze** [comment]
LGTM

**Pull request merged**
