### PR TITLE
Chef zero / solo / local mode provisioner

### PR DESCRIPTION
**Pull request by Mwea**
This is a PR providing support for a Chef Zero provisioner. It's mainly ( perhaps too much ) based on the chef provisioner. 

In this provisioner, there is the possibility of defining DNA attributes, but also Node attributes ( in case you would want to differ one from another). 

Because we're using chef-zero, I made sure to generate nodes files dynamically.
These will be uploaded to each instance, giving the possibility of using chef search.

There is also the possibility of building "templated" attributes.  
For instance : 
``` 
  provisioner "chef-zero" {

    automatic_attributes = "${file("test/terraform/attributes/slave_shared.json")}"
    dna_attributes = "${file("test/terraform/attributes/slave_shared.json")}"

    environment     = "preprod"
    run_list        = ["role[mesos_slave]"]
    instance_id     = "slave-${count.index+1}"

    dir_resources   = "test/terraform",
    local_nodes_dir = "nodes",
    version = "12.18.31"

    mapped_attributes = {
      node_ip = "${element(aws_instance.mesos_master.*.public_ip, count.index)}"
      node_id = "slave-${count.index+1}"
      node_index = "${count.index+1}"
    }

  }
``` 
Giving this configuration, we can now define a in `slave_shared.json` file such things : 

 ```
{
  "ipaddress": "<%= @node_ip %>",
  "os_criteo": {
    "hostname": "<%= @node_id %>"
  }
}
``` 
Every variables starting with "<%=" and ending with "%>" will be mapped if it has been defined in the mapped_attributes block. 

Feel free to comment all of this work, I'm definitely sure that there are a lot of work I missed. 
Have a good day ! :smile:

### CODE REVIEW

**Comment by steffentemplin** [comment]
Nice approach with the dynamic attributes and generation of node files, this makes it superior to #17827 👍 I had also thought about creating a separate provisioner but hesitated to duplicate all the install, config and run code for chef-client.

Let's see what the maintainers prefer. As long as we finally get local mode support, I'm happy to contribute to both approaches.

**Comment by Mwea** [comment]
@apparentlymart would you have any advice on these PR ? 
I thought it was okay to ping you, since you gave your opinion on this subject in #2652

**Comment by thommay** [comment]
As a cosmetic thing, we (Chef Software) would prefer for this to be called "chef-solo" or "chef-local-mode".

**Comment by rabidscorpio** [comment]
@Mwea it's funny that you're making changes to this now after it's sat for 2 months. I just found this PR this morning and as we're migrating to terraform, I'm really hoping something will happen with this!

**Comment by rabidscorpio** [comment]
@Mwea Any chance you can fix the failing tests so we can move this along?

**Comment by Mwea** [comment]
Is there any news coming from reviewers ? I'd be happy to improve this PR if needed.

**Comment by Mwea** [comment]
Documentation for both projects have been updated.
Feel free to open issues if you encounter bugs. 

Have a good day :+1:

**Pull request closed without merging**
