### PR TITLE
provider/azurerm: support non public clouds

### LINKED ISSUE #10666: Azure Germany: Error refreshing token: invalid character '<' looking for beginning of value.
I tried terraform with my Azure Germany free trial, but have problems to make it work/login. I tried the same steps in global Azure and location `West Europe` instead of `Germany Central` without a problem.

### Terraform Version
```
$ terraform -v
Terraform v0.7.13
```

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm
- azurerm_resource_group

### Terraform Configuration Files
```hcl
variable "location" { default = "Germany Central" }

resource "azurerm_resource_group" "test" {
  name     = "HelloGermany"
  location = "${var.location}"
}
```

### Debug Output
Gist: https://gist.github.com/StefanScherer/5da2a4b3c30f75a8cc6629c1c354cd6c

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

It should work like in public Azure:

```
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

azurerm_resource_group.test: Refreshing state... (ID: /subscriptions/guid/resourceGroups/HelloWorld)

The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed. Cyan entries are data sources to be read.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

- azurerm_resource_group.test

+ azurerm_resource_group.test
    location: "germanycentral"
    name:     "HelloGermany"
    tags.%:   "<computed>"


Plan: 1 to add, 0 to change, 1 to destroy.
```
### Actual Behavior
What actually happened?

```
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

Error refreshing state: 1 error(s) occurred:

* Cannot request provider registration for Azure Resource Manager: Error obtaining authorization token: Error refreshing token: invalid character '<' looking for beginning of value.
```

### Steps to Reproduce
1. Create a free trial for Azure Germany https://azure.microsoft.com/en-us/free/germany/
2. Create credentials in portal as described in https://www.terraform.io/docs/providers/azurerm/
3. fetch german locations with `azure location list`, found `Germany Central` and `Germany Northeast`
3. `terraform plan`

### Important Factoids
Azure Germany

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- pull request #9765

### LINKED ISSUE #10895: AzureRM fails for  USGov
The AzureRM provider fails to even run `terraform plan` when using a USGov account. Will likely fail for China and Germany too.

### Terraform Version

`Terraform v0.8.1`

### Affected Resource(s)

AzureRM

### Terraform Configuration Files

```
provider "azurerm" {
  subscription_id = "11111111-222222-33333"
  tenant_id = "11111111-222222-33334
  client_id = "11111111-222222-33335"
  client_secret = "3333333-44444-5555"
}

# Create a resource group
resource "azurerm_resource_group" "terraform_demo" {
    name     = "terraform_demo"
    location = "USGovVirginia"
#    location = "eastus"
}

```

### Debug Output

https://gist.github.com/pburkholder/bd1e716caa858119fe2e68a7f4ecda18

### Expected Behavior

`terraform plan` works

### Actual Behavior

```
Error refreshing state: 1 error(s) occurred:

2016/12/21 12:11:21 [DEBUG] plugin: waiting for all plugin processes to complete...
* Credentials for accessing the Azure Resource Manager API are likely to be incorrect, or
  the service principal does not have permission to use the Azure Service Management
  API.
```

### Steps to Reproduce

1. Have a USGov subscription, and login with it
2. Create a service principal with:

```
az ad sp create-for-rbac --name "http://terraform.demo" \
  --role "Contributor" --scopes "/subscriptions/$SUBSCRIPTION_ID" --verbose
```
3. Update the .tf file with appropriate tokens and credentials
4. Run `terraform plan`
5. Watch the error

### Important Factoids

1. Watching `tcpdump` I see traffic to the standard API, not the usgov one, management.usgovcloudapi.net.

```
12:10:34.468537 IP xcoh2j-3befvh8.home.51342 > wireless_broadband_router.home.domain: 58205+ AAAA? management.azure.com. (38)
12:10:34.468564 IP xcoh2j-3befvh8.home.58776 > wireless_broadband_router.home.domain: 27344+ A? management.azure.com. (38)
12:10:34.505287 IP 104.211.48.17.https > xcoh2j-3befvh8.home.53061: Flags [.], ack 904, win 511, options [nop,nop,TS val 110468775 ecr 573642779], length 0
12:10:34.523095 IP wireless_broadband_router.home.domain > xcoh2j-3befvh8.home.58776: 27344 4/0/0 CNAME arm-rpfd-prod.trafficmanager.net., CNAME eastus.management.azure.com., CNAME rpfd-prod-bl-01.cloudapp.net., A 40.76.78.16 (160)
12:10:34.580511 IP wireless_broadband_router.home.domain > xcoh2j-3befvh8.home.51342: 58205 3/1/0 CNAME arm-rpfd-prod.trafficmanager.net., CNAME eastus.management.azure.com., CNAME rpfd-prod-bl-01.cloudapp.net. (236)
12:10:34.580966 IP xcoh2j-3befvh8.home.53062 > 40.76.78.16.https: Flags [S], seq 2995917756, win 65535, options [mss 1460,nop,wscale 5,nop,nop,TS val 573642890 ecr 0,sackOK,eol], length 0
12:10:34.596046 IP 40.76.78.16.https > xcoh2j-3befvh8.home.53062: Flags [S.], seq 835199399, ack 2995917757, win 8192, options [mss 1440,nop,wscale 8,sackOK,TS val 16671362 ecr 573642890], length 0
12:10:34.596102 IP xcoh2j-3befvh8.home.53062 > 40.76.78.16.https: Flags [.], ack 1, win 4105, options [nop,nop,TS val 573642905 ecr 16671362], length 0
```

2. There isn't any support in the code for `ManagementURL` which was noted in https://github.com/hashicorp/terraform/pull/4226#r47362510 - with the expectation it could be useful someday (which is probably now).

3.  The errors occur regardless of the value used for `location`, I presume the client is going to https://management.azure.com and failing to find the SubscriptionID.

4. It all works fine with my PublicAzure account

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

https://github.com/hashicorp/terraform/issues/10666

### PR DESCRIPTION
**Pull request by pmcatominey**
Fixes #10666.
Should fix #10895 too but I'm unable to test in that region.

@tombuildsstuff this should let you manage resources in the China cloud now.

### CODE REVIEW

**Comment by stack72** [comment]
This is fantastic - thanks so much for taking the time to fix this @pmcatominey :)

This LGTM!

P.

**Comment by tasquith** [comment]
@stack72 - just a FYI, the provider label incorrectly set as AWS

**Comment by stack72** [comment]
thanks @tasquith ;)

**Comment by martinbjorgan** [comment]
Hi. Any date on when azure stack is supported in TF? My org is waiting for this :)

**Pull request merged**
