### PR TITLE
provider/aws: Fix Security Group Rule self reference bug

### LINKED ISSUE #1985: Error removing aws_security_group_rule that has self reference rule
Create succeeds fine but destroy can't.

```
aws_security_group_rule.allow-elastic_instance-to-elastic_instance-ingress-elastic_instance: Refreshing state... (ID: sg-835539191)
aws_security_group_rule.allow-elastic_instance-to-elastic_instance-ingress-elastic_instance: Destroying...
aws_security_group_rule.allow-elastic_instance-to-elastic_instance-ingress-elastic_instance: Error: 1 error(s) occurred:

* Error revoking security group sg-8f92b4ea rules: InvalidPermission.NotFound: The specified rule does not exist in this security group.
aws_vpc.customer: Destroying...
aws_vpc.customer: Error: 1 error(s) occurred:

* Error deleting VPC: DependencyViolation: The vpc 'vpc-8bef5fee' has dependencies and cannot be deleted.
```

### PR DESCRIPTION
**Pull request by catsby**
Fixes #1985 by building a unique set of security group name/ids.

### CODE REVIEW

**Comment by catsby** [comment]
Might also fix #2291

**Comment by catsby** [comment]
confirmations from #1985 and #2291 :+1:

**Comment by phinze** [comment]
LGTM

**Comment by jayudhandha** [comment]
can anyone tell me how this gets fixed (Or What should i do to fix this)?
I am facing the same issue. :(

**Pull request merged**
