### PR TITLE
update arch docs; remove old EvalNode references

### PR DESCRIPTION
**Pull request by mildwonkey**
I've removed references to EvalNode() / Eval() and replaced with a basic explanation of `GraphNodeExecutable.Execute` and a list of the "main" graph `Execution`s. 

I'm sure this section could be re-written better, and I'll happily take any suggestions, but the main goal of _this_ PR is accuracy.

### CODE REVIEW

**Comment by pselle** [comment]
I dare say that a larger/broader edit may be warranted, to fully communicate how the architecture now differs from the`EvalNode` era. For example:

> EnterEvalTree and ExitEvalTree are each called once for each vertex in the graph during vertex evaluation, which is described in the following section.

Appears earlier in the doc, as well. I don't think we can switch out `EvalNode` for `Execute` very directly in the conceptualization ... I have to wrap my head again around how this works now, but I'd want to be clear about when we "visit"/"execute"/"evaluate" the nodes ... in PastTimes EvalNodes were added, and then those were later evaluated ... now we have nodes added, and as we walk, if we can evaluate/exec them, we do ... there's whole layer that's gone (which was the idea of the refactor, no?) and I'd want to communicate that more accurately.

**Comment by pselle** [comment]
Hmm, actually, re-reading the full rendered: https://github.com/hashicorp/terraform/blob/0a0fafe8d3934f9b3ab4b93f8875e0fbcf58c1b2/docs/architecture.md again, I think maybe those EvalTree might be the only extra bits to pay attention to ... otherwise this _does_ read pretty clearly (which might say more about how EvalNodes were pretty confusing as extra graph nodes?)

**Comment by mildwonkey** [comment]
Thank you @pselle , I removed that bullet - I think everything else around it looks good. 

>  (which might say more about how EvalNodes were pretty confusing as extra graph nodes?)
YUP 😂

**Review by pselle — APPROVED** [review]
Thanks! This looks good to me to at least get the doc to a "represents current state of world"

**Pull request merged**
