### PR TITLE
Add support for unary operators + and - to the interpolation syntax

### PR DESCRIPTION
**Pull request by jszwedko**
This adds support to the configuration interpolation syntax for + and -
as unary operators, specifically to represent negative numbers.

This is the first time I've touched the AST code, so I'm sure that I did something wrong.

### CODE REVIEW

**Comment by phinze** [comment]
This LGTM - but I'd like to get @mitchellh's eyes on it too.

**Comment by jszwedko** [comment]
Rebased to get mergeable again. Let me know what you think @mitchellh.

**Comment by mitchellh** [comment]
This all LGTM. Great job.

**Comment by phinze** [comment]
:+1:

**Pull request merged**
