### PR TITLE
provider/google: Add support for scope aliases to google_container_cluster

### PR DESCRIPTION
**Pull request by cblecker**
This PR adds support for scope aliases to the `google_container_cluster` resource, and also cleans up the formatting on the related docs.

### CODE REVIEW

**Comment by cblecker** [comment]
Acceptance tests pass:
```
$ make testacc TEST=./builtin/providers/google TESTARGS='-run=TestAccContainerCluster...'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/11/14 15:24:27 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/google -v -run=TestAccContainerCluster... -timeout 120m
=== RUN   TestAccContainerCluster_basic
--- PASS: TestAccContainerCluster_basic (241.91s)
=== RUN   TestAccContainerCluster_withNodeConfig
--- PASS: TestAccContainerCluster_withNodeConfig (272.19s)
=== RUN   TestAccContainerCluster_withNodeConfigScopeAlias
--- PASS: TestAccContainerCluster_withNodeConfigScopeAlias (272.25s)
=== RUN   TestAccContainerCluster_network
--- PASS: TestAccContainerCluster_network (313.29s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/google	1099.661s
```

**Comment by cblecker** [comment]
@evandbrown -- FYI if you have time to review this :)

**Comment by evandbrown** [comment]
Totes. I'm on a plane now and wifi is shit but will look when I get in the
office tomorrow!

On Nov 14, 2016 4:03 PM, "Christoph Blecker" <notifications@github.com>
wrote:

@evandbrown <https://github.com/evandbrown> -- FYI if you have time to
review this :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hashicorp/terraform/pull/10117#issuecomment-260504268>,
or mute the thread

**Comment by cblecker** [comment]
ping @evandbrown :)

**Comment by evandbrown** [comment]
Thanks, @cblecker!

**Pull request merged**
