### PR TITLE
fix panic when validating composite schema type

### PR DESCRIPTION
**Pull request by ceh**
Fixes issue #691.

### CODE REVIEW

**Comment by ceh** [comment]
Not sure if the reasoning, mentioned in the commit message of 2ff4861, for renaming list to array in the docs is sound.

Lists might be what the community prefers?

**Comment by mitchellh** [comment]
Yeah I think discussing "list" vs "array" is getting a little bikeshed-y. Some programming languages use lists, some use arrays, I imagine devs/ops are generally comfortable with both. I prefer "list" personally for no better reason than when I hear "array" I put on my C hat and think of a fixed size memory buffer and its so mechanical to me that I feel that "list" is more human friendly.

Like I said, not a good reason, but also not one I think matters.

**Comment by mitchellh** [comment]
LGTM. I think I'm going to just keep things as "list" since we also use that internally everywhere. But thanks for this fix and thanks for the tests, great job. :)

**Comment by ceh** [comment]
@mitchellh Just noticed 5e8b300ca1369cb04ca4cee8d493f41bd01e395c. Do you prefer that contributors also updates the CHANGELOG with a reference to the fixed issue in the proposed PR?

**Comment by mitchellh** [comment]
@ceh I like to update the CL myself, the reason being that its a common place for merge conflict in a PR and its the dumbest merge conflict...

**Pull request merged**
