### PR TITLE
New header/footer redesign

### PR DESCRIPTION
**Pull request by captainill**

### CODE REVIEW

**Comment by catsby** [comment]
Hey @captainill – the header text is hard to read on Safari (9.0.1)

header-footer

**Comment by captainill** [comment]
thanks @catsby that didn't look good. I've updated.

**Comment by catsby** [comment]
Aye, more better now. Is this ready for us then?

**Comment by captainill** [comment]
good question. @pearkes are  deploying these ASAP? I assume so just want to loop you in in case you'd like to have a look.

**Comment by pearkes** [comment]
@captainill This LGTM and can just go out at whatever schedule works for the project, or on that release schedule.

**Comment by catsby** [comment]
moneysloth

**Pull request merged**
