### PR TITLE
Performance - Allow a single terraform import command to process multiple resources.

### PR DESCRIPTION
**Pull request by ehud-eshet**
Currently, each terraform import command reads and parses all *.tf files.
The change allows reading and parsing all *.tf files once.
And then, process all imports using the default amount of parallel threads.

Current code imported 152 resources using 152 import commands in 150 seconds.
Modified code imported same 152 resources using 1 import command in 7.5 seconds.

### CODE REVIEW

**Comment by crw** [comment]
Thanks for this submission. Although I cannot commit to having this PR reviewed at this time, we acknowledge your contribution and appreciate it! Thanks again for the submission!

**Comment by crw** [comment]
Is there an existing issue that describes the problem to be solved by this pull request? Thanks!

**Comment by ehud-eshet** [comment]
I believe that issue [22219](https://github.com/hashicorp/terraform/issues/22219) complains about same thing.

**Comment by madimadi** [comment]
Merging this PR  can be a true performance gain. How can this PR get some priority and looked up by a reviewer to progress?

**Comment by crw** [comment]
Apologies, we did a triage of this PR in June and I failed to update. 

It looks like the same functionality as is being contributed by #22227 - the recommendation at the time was to close this PR and focus on #22227. I am going to leave this one open for a little while longer to gather any feedback on the preceding information; if we mis-identified this as contributing duplicate functionality for example. Thanks for the contribution and the feedback to date!

**Comment by crw** [comment]
Going to close this PR in favor of continuing the discussion on https://github.com/hashicorp/terraform/pull/30015. Thanks for your contribution!

**Pull request closed without merging**
