### PR TITLE
v0.12 update HC Public Key

### PR DESCRIPTION
**Pull request by jbardin**

### CODE REVIEW

**Review by alisdair — APPROVED** [review]

**Comment by jbardin** [comment]
The e2e test failures are expected here, and we can re-run the suite once the registry is updated too.

**Comment by NicoleYson** [comment]
👋 Hi @jbardin! 
Just out of curiosity / exploring my options, do you intend to push a `0.12.31` with this fix? 

Asking because I just got:
```
Error verifying GPG signature for provider "vault"
Terraform was unable to verify the GPG signature of the downloaded provider
files using the keys downloaded from the Terraform Registry. This may mean that
the publisher of the provider removed the key it was signed with, or that the
distributed files were changed after this version was released.
```

**Comment by jbardin** [comment]
Hi @NicoleYson, there are patch releases in the works right now, but what you are seeing is an error with the vault provider jumping ahead of the process. The registry should be taking care of that shortly to allow your current release to continue working.

**Comment by NicoleYson** [comment]
👋 Hi! Sorry to be a bother, but I noticed that this is merged for 0.12.31, but it still seems to be an intermittent issue at ~10% success rates with plans and applies. 
Should I open up an issue or is there any further action that needs to be done or is this still expected at this point? 

```
Upgrading modules...

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Checking for available provider plugins...

Error verifying GPG signature for provider "template"
Terraform was unable to verify the GPG signature of the downloaded provider
files using the keys downloaded from the Terraform Registry. This may mean that
the publisher of the provider removed the key it was signed with, or that the
distributed files were changed after this version was released.


Error verifying GPG signature for provider "kubernetes"
Terraform was unable to verify the GPG signature of the downloaded provider
files using the keys downloaded from the Terraform Registry. This may mean that
the publisher of the provider removed the key it was signed with, or that the
distributed files were changed after this version was released.

- Downloading plugin for provider "vault" (hashicorp/vault) 2.19.1...
- Downloading plugin for provider "aws" (hashicorp/aws) 3.37.0...

Error: unable to verify signature

Error: unable to verify signature
```

**Pull request merged**
