### PR TITLE
Windows support for Habitat Provisioner

### PR DESCRIPTION
**Pull request by mudash**
This PR adds functionality to Habitat provisioner for installation and configuration of Habitat on Windows OS.

### CODE REVIEW

**Comment by mudash** [comment]
@pselle It will be good to get it reviewed/merged quickly to avoid any conflicting subsequent changes that might slow down the process. This has been a feature many have been looking for. Thanks.

cc: @davymcaleer @kmott

**Comment by davymcaleer** [comment]
@pselle any view on when this might be merged please?

**Comment by mudash** [comment]
Kindly update when can it be reviewed and merged. @pselle 
cc: @davymcaleer

**Comment by davymcaleer** [comment]
@pselle is there anything else we can do to push this along a little?

**Comment by gyamada619** [comment]
Any updates on this PR? We are looking to implement Habitat and this would be hugely beneficial.

**Comment by pkolyvas** [comment]
I apologize that we've left this for so long. We're trying hard to get to a place where that doesn't happen again.

I'll be closing this PR not because of it's quality or value but rather because we announced tool-specific (vendor or 3rd-party) provisioner deprecation in [mid-September 2020](https://discuss.hashicorp.com/t/notice-terraform-to-begin-deprecation-of-vendor-tool-specific-provisioners-starting-in-terraform-0-13-4/13997). Additionally, we added a deprecation notice for tool-specific provisioners in `0.13.4`.

On a practical level this means we will no longer be reviewing or merging PRs for these built-in plugins.

The long term strategy here is less clear than we'd like, but for the time being I'd encourage the community of Terraform provisioner users and developers (who might also be reading this) to follow in the footsteps of the [ansible provisioner](https://github.com/radekg/terraform-provisioner-ansible).

Creating provisioner plugins and installing provisioner plugins manually is more involved. Our hope here is that the ability to improve, fix and repair these tools without us blocking their development, much like providers, will help make a strong case for what's next.

There are also some technical hurdles we have to to cross. The Terraform plugin SDK does not support provisioners and so moving beyond the deprecation will require something more concrete plans. We’d like to base those plans, in part, on the feedback we receive. I think it’s also important to highlight that we have no plans to remove the generic provisioners or the pluggable functionality during Terraform's 1.0 lifecycle.

We didn't make this decision lightly, and removing or no longer supporting features is not ideal for anyone who uses and depends on them. To that end, my door is always open. I'd invite you, or anyone interested, to write me or schedule some time with me to talk about these changes moving forward.

**Pull request closed without merging**
