### PR TITLE
backend/plan: Show warnings even without changes (backport)

### PR DESCRIPTION
**Pull request by nyurik**
Backport of https://github.com/hashicorp/terraform/pull/24095
Fixes https://github.com/hashicorp/terraform/issues/22541 for v0.12

### CODE REVIEW

**Comment by nyurik** [comment]
@apparentlymart is there something I should do to get this PR merged? Or is there a different process I need to follow to get it backported into 0.12? `hashibot` has removed your name from the reviewers.

**Comment by nyurik** [comment]
cc:  @pselle for visibility

**Comment by mildwonkey** [comment]
Thank you for submitting this additional backport PR @nyurik ! Can you either fix or revert the changelog entry? I am happy to add it to the changelog manually after merging this PR.

**Comment by nyurik** [comment]
@mildwonkey thx for noticing, fixed

**Comment by mildwonkey** [comment]
great, thank you! this will be in the next 0.12 release (planned for this week)

**Pull request merged**
