### PR TITLE
Allow underscore in database_name [redshift]

### LINKED ISSUE #10009: aws_redshift_cluster does not allow underscore in database_name
I have a redshift cluster with a database that has an underscore in its name that I used awscli to create in the past. When I migrate that process to use the aws_redshift_cluster resource in terraform configuration, terraform reports the following error

aws_redshift_cluster.test_redshift_cluster: only lowercase letters and numeric characters allowed in "database_name"

According to redshift documentation on this page - http://docs.aws.amazon.com/redshift/latest/dg/r_names.html - underscores and $ are valid characters for the database name. 

This issue is a request to allow the database_name to allow the aws specified naming convention.

Terraform version: 0.7.6

### PR DESCRIPTION
**Pull request by optimisticanshul**
Fixes #10009

### CODE REVIEW

**Comment by stack72** [comment]
Hi @optimisticanshul 

Thanks for the work here - please can you add a test that covers the different use cases? You can use iam_user name validation as an example

Thanks

Paul

**Comment by optimisticanshul** [comment]
```
anssharma@Ban-1Anssharma-M:~/Code/go/src/github.com/hashicorp/terraform|patch-2
⇒  make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestValidateRedshiftClusterDbName'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/11/10 18:50:01 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestValidateRedshiftClusterDbName -timeout 120m
=== RUN   TestValidateRedshiftClusterDbName
--- PASS: TestValidateRedshiftClusterDbName (0.00s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	5.586s
```

**Comment by optimisticanshul** [comment]
@stack72 Ready for another review.

**Comment by stack72** [comment]
Hi @optimisticanshul 

1 last addition please - can you readd back in the failing test cases for too long and empty string? :)

Thanks

**Comment by optimisticanshul** [comment]
@stack72 👍

**Comment by stack72** [comment]
Thanks for all the work here @optimisticanshul :)

LGTM!

**Pull request merged**
