### PR TITLE
Fix EMR schema to match docs

### PR DESCRIPTION
**Pull request by nevins-b**
additional_master_security_groups and additional_slave_security_groups should be lists not strings

### CODE REVIEW

**Comment by catsby** [comment]
Hey @nevins-b – you're probably right in that those should likely be sets, however I don't think this pull request will work as is. For instance, we manipulate those values here:

- https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_emr_cluster.go#L217

I don't believe lines like that in the codebase will work after this change. We'll need to review all areas that those schema elements are touched and covert them to sets. Additionally, we probably need to specify a migration for anyone using those attributes. Do you have a configuration that uses those attributes? Are you running into issues?

**Comment by nevins-b** [comment]
@catsby Looks like you're right. I can go through the code and make those changes. This will probably be a breaking change for some users though.

I was working on a configuration and ran into this issue since the documentation indicates that these attributes should be lists.

**Comment by catsby** [comment]
The docs say this:

    List of additional Amazon EC2 security group IDs for the master node

As the code stands, the docs should probably say 

   String list of additional Amazon EC2 security group IDs, comma separated, for the master node

I'm curious who is using this though, and if they run into sort/ordering issues 🤔

**Comment by fabiendelpierre** [comment]
@catsby I'm using this, FYI, since you said you were curious 😄 I encountered the same issue, googled "additional_master_security_groups terraform example", found https://github.com/terraform-providers/terraform-provider-aws/issues/391, then followed the link to https://github.com/hashicorp/terraform/issues/10331, and finally ended up here.

When the Terraform docs mention a "list" I usually assume it means "array", so that's what I tried first, but this particular parameter doesn't take an array, as already discussed. I quickly figured out that it simply expects a comma-separated list of security group IDs, so my `aws_emr_cluster` resource now looks like this and works fine:

```
resource "aws_emr_cluster" "foo" {
  # stuff

  ec2_attributes {
    # more stuff
    additional_master_security_groups = "${aws_security_group.vpc-external.id},${aws_security_group.vpc-internal.id}"
    # etc
  }

  master_instance_type = "m4.xlarge"
  core_instance_type   = "m4.xlarge"
  core_instance_count  = 4

  # etc
}
```

I don't believe AWS security groups need ordering at all, you just apply them to an instance, AWS aggregates all the rules within your groups and applies all of them at once (not like network ACLs which have priority numbers).

**Comment by apparentlymart** [comment]
Hello @nevins-b, and thanks for working on this!

As part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it.

If you or someone else has the time and motivation to apply same changes (modulo the above feedback) to [the `aws` provider repository](https://github.com/terraform-providers/terraform-provider-aws) and open a new PR there, the maintainers of that provider should be able to review and merge it.

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Pull request closed without merging**
