### PR TITLE
Opsworks Application support

### PR DESCRIPTION
**Pull request by odise**
This PR implements Opsworks App resources along with some tests. I tried to include all app related features however `aws-flow-ruby` type is incomplete (`AwsFlowRubySettings`). `opsworks.UpdateApp` doesn't support application `Shortname` updates so those will be ignored.

### CODE REVIEW

**Comment by u2mejc** [comment]
@odise Would you be willing to squash your commits and rebase this?

Also here's a patch to fix the current compilation issues: (you can apply it with `git apply` or manually)

```patch
From 26146c9c9d50493680da3999c75fd3e9d87fdd4a Mon Sep 17 00:00:00 2001
From: Justin Clark <u2mejc@users.noreply.github.com>
Date: Fri, 1 Apr 2016 17:00:31 -0700
Subject: [PATCH] Refactor OpsWorks Applications PR for Terraform 0.6.x

---
 .../providers/aws/resource_aws_opsworks_application.go | 18 +++++++++---------
 1 file changed, 9 insertions(+), 9 deletions(-)

diff --git a/builtin/providers/aws/resource_aws_opsworks_application.go b/builtin/providers/aws/resource_aws_opsworks_application.go
index 3b9a2af..cf63c3b 100644
--- a/builtin/providers/aws/resource_aws_opsworks_application.go
+++ b/builtin/providers/aws/resource_aws_opsworks_application.go
@@ -268,7 +268,7 @@ func resourceAwsOpsworksApplicationRead(d *schema.ResourceData, meta interface{}
 	d.Set("stack_id", app.StackId)
 	d.Set("type", app.Type)
 	d.Set("description", app.Description)
-	d.Set("domains", unwrapAwsStringList(app.Domains))
+	d.Set("domains", flattenStringList(app.Domains))
 	d.Set("enable_ssl", app.EnableSsl)
 	resourceAwsOpsworksSetApplicationSsl(d, app.SslConfiguration)
 	resourceAwsOpsworksSetApplicationSource(d, app.AppSource)
@@ -292,7 +292,7 @@ func resourceAwsOpsworksApplicationCreate(d *schema.ResourceData, meta interface
 		StackId:          aws.String(d.Get("stack_id").(string)),
 		Type:             aws.String(d.Get("type").(string)),
 		Description:      aws.String(d.Get("description").(string)),
-		Domains:          makeAwsStringList(d.Get("domains").([]interface{})),
+		Domains:          expandStringList(d.Get("domains").([]interface{})),
 		EnableSsl:        aws.Bool(d.Get("enable_ssl").(bool)),
 		SslConfiguration: resourceAwsOpsworksApplicationSsl(d),
 		AppSource:        resourceAwsOpsworksApplicationSource(d),
@@ -302,7 +302,7 @@ func resourceAwsOpsworksApplicationCreate(d *schema.ResourceData, meta interface
 	}
 
 	var resp *opsworks.CreateAppOutput
-	err = resource.Retry(2*time.Minute, func() error {
+	err = resource.Retry(2*time.Minute, func() *resource.RetryError {
 		var cerr error
 		resp, cerr = client.CreateApp(req)
 		if cerr != nil {
@@ -310,9 +310,9 @@ func resourceAwsOpsworksApplicationCreate(d *schema.ResourceData, meta interface
 			if opserr, ok := cerr.(awserr.Error); ok {
 				// XXX: handle errors
 				log.Printf("[ERROR] OpsWorks error: %s message: %s", opserr.Code(), opserr.Message())
-				return cerr
+				return resource.RetryableError(cerr)
 			}
-			return resource.RetryError{Err: cerr}
+			return resource.NonRetryableError(cerr)
 		}
 		return nil
 	})
@@ -336,7 +336,7 @@ func resourceAwsOpsworksApplicationUpdate(d *schema.ResourceData, meta interface
 		Name:             aws.String(d.Get("name").(string)),
 		Type:             aws.String(d.Get("type").(string)),
 		Description:      aws.String(d.Get("description").(string)),
-		Domains:          makeAwsStringList(d.Get("domains").([]interface{})),
+		Domains:          expandStringList(d.Get("domains").([]interface{})),
 		EnableSsl:        aws.Bool(d.Get("enable_ssl").(bool)),
 		SslConfiguration: resourceAwsOpsworksApplicationSsl(d),
 		AppSource:        resourceAwsOpsworksApplicationSource(d),
@@ -348,7 +348,7 @@ func resourceAwsOpsworksApplicationUpdate(d *schema.ResourceData, meta interface
 	log.Printf("[DEBUG] Updating OpsWorks layer: %s", d.Id())
 
 	var resp *opsworks.UpdateAppOutput
-	err := resource.Retry(2*time.Minute, func() error {
+	err := resource.Retry(2*time.Minute, func() *resource.RetryError {
 		var cerr error
 		resp, cerr = client.UpdateApp(req)
 		if cerr != nil {
@@ -356,9 +356,9 @@ func resourceAwsOpsworksApplicationUpdate(d *schema.ResourceData, meta interface
 			if opserr, ok := cerr.(awserr.Error); ok {
 				// XXX: handle errors
 				log.Printf("[ERROR] OpsWorks error: %s message: %s", opserr.Code(), opserr.Message())
-				return cerr
+				return resource.NonRetryableError(cerr)
 			}
-			return resource.RetryError{Err: cerr}
+			return resource.RetryableError(cerr)
 		}
 		return nil
 	})
-- 
2.7.3

```

**Comment by janschumann** [comment]
@u2mejc This branch is now squashed and rebased. Tests should also pass.

There are some issues. E.g. Attributes are not passed to the client for some reason, resulting in default values for document_root etc.

Would you now get this PR merged, so we can continue working on issues and refactorings in separate PRs/Issues?

**Comment by u2mejc** [comment]
@janschumann said:
>There are some issues. E.g. Attributes are not passed to the api client for some reason, resulting in default values for document_root etc.

ah I just worked quickly to get it to compile and just a quick `terraform apply` test on friday, sorry I missed that. Do you have time to see if you can find that bug and do an amend?

**Comment by janschumann** [comment]
@u2mejc I tried to figure out what the problem is.But debugging ist not very easy in terraform. Could you assist me with debugging? I am using IntelliJ IDEA. But the go debugging feature does not work due tu multiple file builds.

**Comment by u2mejc** [comment]
@janschumann I'm not sure if I can help much, I'm not familiar with IntelliJ. I'm a vim user and I've been compiling using `make plugin-dev PLUGIN=provider-aws`. I didn't have to do much debug for the refactor.

Good news is I'm not able to reproduce the bug you mentioned. IMHO this better then just MVP and ready to ship. I just rebased and dropped the errant new line in the .travis.yml. 

@apparentlymart when you have a sec, could you please give this a peak and let me know if you'd think we need anything else before we merge?

**Comment by apparentlymart** [comment]
Sorry for the delay on this one @odise, and thanks for the contribution and your patience with getting it merged.

Some drift in the stack acceptance tests was causing the acceptance tests here to fail but I fixed that up in 2d597f09a8c4aff75c476801664bbc700cc222d5.

**Pull request merged**
