### PR TITLE
Use password data facility in AWS for provisioning (issue #3148)

### PR DESCRIPTION
**Pull request by deftflux**
This PR addresses [issue #3148](https://github.com/hashicorp/terraform/issues/3148).  It does so by implementing two features:
- aws_instance exports `password_data` with a base-64 encoded encrypted password when `get_password_data = true` is specified.
- WinRM communicator supports decrypting the password when a `password_private_key` is specified in the connection info.

It was done this way mainly so that a plain-text password does not end up in the terraform state file.  The encrypted password data does, however, end up in the state file.

I am marking this as a work in progress because of the following:
- I have not implemented any acceptance tests yet.
- I have not modified the documentation accordingly.
- I would like some feedback, mainly on the following items:
  - There doesn't appear to be a way to know automatically whether password data should be available and hence whether or not to wait for it, which is why I opted for a `get_password_data` attribute.  Is there a better way?  Should it be called something else?
  - Does it make sense to assume that the encrypted password is base-64 encoded when specified in the connection info?  Or should a byte array be used?
  - As it is, the connection `password` must be manually specified if you want to use `password_data`, but it could be automatically filled in by the aws provider.  Should this be done?  If so, under what circumstances?  (So as not to break existing functionality.)
  - I'm not sure if the password decryption feature would also be useful when using SSH.  If so, it would be pretty simple to apply it to both communicators.

### CODE REVIEW

**Comment by deftflux** [comment]
Here is an example .tf config:

```
variable "region" { }

variable "ami" {
    description = "Any default Amazon-provided Windows Server AMI will do" 
}

variable "vpc_id" { }

variable "subnet_id" { }

variable "key_name" { }
variable "private_key_path" { }

provider "aws" {
    region = "${var.region}"
}

resource "aws_security_group" "sg" {
    name = "winpasswordtest-sg"
    vpc_id = "${var.vpc_id}"
	
    # WinRM
    ingress {
        from_port = 5985
        to_port = 5985
        protocol = "tcp"
        cidr_blocks = ["0.0.0.0/0"]
    }
    
    # Remote Desktop - optional
	ingress {
        from_port = 3389
        to_port = 3389
        protocol = "tcp"
        cidr_blocks = ["0.0.0.0/0"]
    }
}

resource "aws_instance" "server" {
    ami = "${var.ami}"
    subnet_id = "${var.subnet_id}"
    key_name = "${var.key_name}"
    instance_type = "t2.medium"
    vpc_security_group_ids = ["${aws_security_group.sg.id}"]
    tags {
        Name = "winpasswordtest"
    }
    
    # User data script must configure WinRM
    user_data = "${file("user-data.txt")}"    
    
    get_password_data = true        
    
    connection {
        type = "winrm"
               
        # As it is, this must be set in order to use it.
        # It could be automatic, however, but the other two attributes would still be required.
        password = "${self.password_data}"
        
        password_private_key = "${file(var.private_key_path)}"
    }
    
    provisioner "remote-exec" {
        inline = [
            "echo Instance provisioner works!"
        ]
    }
}

# Using the password data elsewhere:
resource "null_resource" "server_provisions" {    
    connection {
        type = "winrm"
        host = "${aws_instance.server.0.private_ip}"
        user = "Administrator"
        password = "${aws_instance.server.0.password_data}"
        password_private_key = "${file(var.private_key_path)}"
    }
    
    provisioner "remote-exec" {
        inline = [
            "echo Null provisioner works!"
        ]
    }
}
```

**Comment by deftflux** [comment]
I've removed the work-in-progress status on this even though I don't have acceptance tests yet.  I can certainly write them or assist in writing them, but I don't know what AMIs will be available to the build server.  For this feature, we need a Windows AMI with the Ec2ConfigService configured to set the administrator password, which is how out-of-the-box Amazon AMIs are typically configured.  In addition, to test the communicator, WinRM needs to be configured on the instance.

The acceptance test will need to verify that:
1. On an `aws_instance`, when `get_password_data = true`, the `password_data` attribute is exported.
2. On any communicator connection, when `type = "winrm"` and `password_private_key` is set, the value of `password` is decrypted when logging in.

**Comment by ajeba99** [comment]
I added my review, why isn't this going through?

**Comment by svanharmelen** [comment]
@deftflux I wonder if it makes sense to put this logic partly in the communicator, as it seems this is very much related to how AWS works?

If so, I guess you could move the needed functions into the AWS provider and not change the communicator. If you decrypt the password and set it [here](https://github.com/deftflux/terraform/blob/72b23512518e1d4bb71f1c3640772f40051868a6/builtin/providers/aws/resource_aws_instance.go#L429-L440), it will not end up in the state, but you will be able to use the password to connect to your new node.

And this will then work for both Windows and Linux in the same way, instead of only for Windows. I do something similar [here](https://github.com/hashicorp/terraform/blob/master/builtin/providers/cloudstack/resource_cloudstack_instance.go#L273-L277) where I set the password directly in the `conn` info and so it never gets into the state but we can still use it. Only difference in this case is that I don't have to decrypt password...

Hope this helps getting to a nice and clean solution :wink:

**Comment by ajeba99** [comment]
@svanharmelen Linux instances in AWS do not require passwords but instead use SSH keys and thus a solution is already provided and working in the provider as it stands.  What @deftflux is trying to resolve is Windows doesn't use SSH Keys for logins and we need the Admin password in order to complete the Chef-Client installation via WinRM.

**Comment by deftflux** [comment]
The problem with only setting the password in the connection info and not exporting it is that it would only be accessible to the aws_instance resource itself.  You could not, for instance, use the information to connect to that instance to provision it from a different null_resource.  (That's a trick I use to be able to share provisioning scripts to be used for multiple instance resources.)

So I tried to keep the changes to the communicator as generic as possible.  It can perform password decryption given the encrypted password and an RSA private key, such as one you would use for aws.

If there is another way to export a value for use in the configuration files, but not have it saved to the state file, that would work too.

**Comment by ajeba99** [comment]
@mitchellh Can we get a merge here?

**Comment by alexmnt** [comment]
@deftflux I think this is a very nice functionality to have, but I had some difficulties in getting this to work.  terraform was not able to connect to my provisioned host, and I assume that the user_data is not configuring the winrm correctly. is it possible to provide a correct configuration of the winrm for the user_data script? Here is .tf that I used:


resource "aws_security_group" "windows" {
  name = "terraform_windows_private"
  description = "Used in the terraform"

  # WinRM access from anywhere
  ingress {
    from_port = 5985
    to_port = 5985
    protocol = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  # WinRMS access from anywhere
  ingress {
    from_port = 5986
    to_port = 5986
    protocol = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  # WinRD access from anywhere
  ingress {
    from_port = 3389
    to_port = 3389
    protocol = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  # outbound internet access
  egress {
    from_port = 0
    to_port = 0
    protocol = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
  vpc_id = "${aws_vpc.default.id}"
}

resource "aws_key_pair" "auth-windows" {
  key_name   = "${var.key_name_windows}"
  public_key = "${file(var.public_key_path_windows)}"
}

resource "aws_instance" "windows" {
  # The connection block tells our provisioner how to
  // # communicate with the resource (instance)
  // connection {
  //   type = "winrm"
  //   user = "Administrator"
  //   password = "${var.admin_password}"
  // }
  instance_type = "t2.micro"
  availability_zone = "eu-west-1a"

  # Lookup the correct AMI based on the region
  # we specified
  // ami = "${lookup(var.aws_amis, var.aws_region)}"
  ami = "${var.aws_windows_ami}"
  key_name = "${aws_key_pair.auth-windows.id}"
  associate_public_ip_address = true

  tags {
    Name = "winpasswordtest"
  }

  # Our Security group to allow WinRM access
  vpc_security_group_ids = ["${aws_security_group.windows.id}"]

  get_password_data = true
  connection {
      type        = "winrm"
      password = "${self.password_data}"
      password_private_key = "${file(var.private_key_path_windows)}"
      timeout     = "5m"
  }

  subnet_id = "${aws_subnet.eu-west-1a-public.id}"

  provisioner "remote-exec" {
    inline = [
        "echo Instance provisioner works!"
    ]
  }

  user_data = <<EOF
<script>
winrm quickconfig -q & winrm set winrm/config/winrs @{MaxMemoryPerShellMB="300"} & winrm set winrm/config @{MaxTimeoutms="1800000"} & winrm set winrm/config/service @{AllowUnencrypted="true"} & winrm set winrm/config/service/auth @{Basic="true"}
</script>
<powershell>
netsh advfirewall firewall add rule name="WinRM in" protocol=TCP dir=in profile=any localport=5985 remoteip=any localip=any action=allow
$admin = [adsi]("WinNT://./administrator, user")
$admin.psbase.invoke("SetPassword", "${var.admin_password}")
</powershell>
EOF
}

**Comment by alexmnt** [comment]
Ok, I managed to figure out how this was intended to work. There is one single issue left which is HTTPS. From the logs, terraform tries to use port 5986, but I do not know if HTTPS is used or the there is a problem in decrypting the password over HTTPS.
Here is a working sample:

```
resource "aws_security_group" "windows" {
  name = "terraform_windows_private"
  description = "Used in the terraform"

  # WinRM access from anywhere
  ingress {
    from_port = 5985
    to_port = 5985
    protocol = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  # WinRMS access from anywhere
  ingress {
    from_port = 5986
    to_port = 5986
    protocol = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  # outbound internet access
  egress {
    from_port = 0
    to_port = 0
    protocol = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
  vpc_id = "${aws_vpc.default.id}"
}

resource "aws_key_pair" "auth-windows" {
  key_name   = "${var.key_name_windows}"
  public_key = "${file(var.public_key_path_windows)}"
}

resource "aws_instance" "windows" {
  instance_type = "t2.micro"
  availability_zone = "eu-west-1a"

  ami = "${var.aws_windows_ami}"
  key_name = "${aws_key_pair.auth-windows.id}"
  associate_public_ip_address = true

  tags {
    Name = "winpasswordtest"
  }

  # Our Security group to allow WinRM access
  vpc_security_group_ids = ["${aws_security_group.windows.id}"]

  subnet_id = "${aws_subnet.eu-west-1a-public.id}"

  user_data = <<EOF
<powershell>
winrm quickconfig -q
winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="300"}'
winrm set winrm/config '@{MaxTimeoutms="1800000"}'
winrm set winrm/config/service '@{AllowUnencrypted="true"}'
winrm set winrm/config/service/auth '@{Basic="true"}'

netsh advfirewall firewall add rule name="WinRM 5985" protocol=TCP dir=in localport=5985 action=allow
netsh advfirewall firewall add rule name="WinRM 5986" protocol=TCP dir=in localport=5986 action=allow

net stop winrm
sc.exe config winrm start= auto
net start winrm
</powershell>
EOF

  get_password_data = true

  provisioner "remote-exec" {
    connection {
        type = "winrm"
        user = "Administrator"
        port = 5985
        https = false
        insecure = true
        CACert = false
        password = "${self.password_data}"
        password_private_key = "${file(var.private_key_path_windows)}"
        timeout = "10m"
    }
    inline = [
      "echo Instance provisioner works!"
    ]
  }

}
```

**Comment by deftflux** [comment]
The password decryption with the AWS key pair is done by terraform, so unless HTTPS is used, the decrypted password is transmitted plaintext over the network, which isn't the most secure thing to do.  But it should be sufficient to test the password decrypting function.

In my project, we do use HTTPS.  Here's a user data script to set up WinRM with HTTPS:

```
<powershell>

echo "Generate certificate for WinRM"
$cert = New-SelfSignedCertificate -CertStoreLocation cert:\LocalMachine\My -DnsName $env:computername
$thumb = $cert.Thumbprint

echo "Enable WinRM"
winrm quickconfig -q
winrm set winrm/config '@{MaxTimeoutms="1800000"}'
winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="300"}'
winrm set winrm/config/service/auth '@{Basic="true"}'
winrm create winrm/config/listener?Address=*+Transport=HTTPS "@{CertificateThumbprint=`"$thumb`";Port=`"5986`"}"

echo "Enable WinRM firewall rules"
Remove-NetFirewallRule -DisplayName "WinRMS" -ErrorAction SilentlyContinue
New-NetFirewallRule -DisplayName "WinRMS" -Direction Inbound -Protocol TCP -LocalPort 5986 | Out-Null

echo "Restart WinRM service"
Stop-Service winrm
Set-Service winrm -StartupType Automatic
Start-Service winrm

</powershell>
```

**Comment by riponbanik** [comment]
is this being merged?

**Comment by jakemig** [comment]
Any blocks on this getting merged in?

**Comment by LuneraSteve** [comment]
+1 for needing this.

**Comment by deftflux** [comment]
Sorry I've been less motivated to advocate this pull request since we stopped needing this particular feature in our project...

There are two things I think that are blocking it at this point: First, it has been some time since I worked on this pull request, which I believe was based on Terraform 0.6.x, and obviously there have been a few new version since then, so the code probably needs to be updated before it can be merged with the current version.

Second, I never wrote any acceptance tests.  This is because I could never get Terraform's acceptance tests for AWS to work with our AWS account.  Since then, however, our company has set up what we are calling "landing zones" for each team, which are basically separate AWS accounts that we have more control over.  I can maybe see if I can get the acceptance tests to work with those now.

I have other things taking priority for me right now, but one of them actually involves working on a different enhancement to Terraform, so I'll be setting up a dev environment again anyway.  After all that, hopefully I can revisit this pull request, but it may be some time.  If anyone else wants to jump in and see this through, I wouldn't mind! ;)  You should probably use your own GitHub account for it and submit it as a new pull request; just be sure to link to it here.

**Comment by ajeba99** [comment]
We've moved on to another solution altogether.  After waiting over a year we gave up on Terraform including this functionality.  Looks like Windows, AWS, Chef, and Terraform isn't going to ever be a thing.

**Comment by deftflux** [comment]
By "we" do you mean HashiCorp has moved on to another solution, or you / your company has moved on?

It just dawned on me what a better solution would be.  If there were interpolated string functions available to perform the decryption, then no changes to the communicator would be necessary.  It would be easier to write tests for it too that way.

I did do a little work on this recently.  The changes survived pulling the latest code without too much difficulty.  I got stuck trying to figure out a way to write tests for it, and then I got busy with other things.  :/

**Comment by ajeba99** [comment]
I mean we as a company, not Hashicorp.  I hate to be a pessimist here but after waiting over a year who can really consider this viable.  The fact is neither Hashicorp or the open source community has succeeded here.

**Comment by Ninir** [comment]
Hi @deftflux,

As per the Terraform 0.10 split, could  you migrate this PR to https://github.com/terraform-providers/terraform-provider-aws/ please?
It will be easier to manage there.
Thanks!

**Comment by deftflux** [comment]
@Ninir yes!  I am planning on it.  I am waiting on getting access to a lab account so that I will be able to run acceptance tests.  In theory, I should be getting that any day now, but I will go bug some people.

**Comment by apparentlymart** [comment]
Hello @deftflux, and thanks for working on this!

As part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it.

Since this change spans both provisioner code and provider code, it must unfortunately be split into two changes to apply to the now-separated repositories. If you or someone else has the time and motivation to apply the AWS provider portion of this to [the `aws` provider repository](https://github.com/terraform-providers/terraform-provider-aws) and open a new PR there, the maintainers of that provider should be able to review and merge it. This PR could then shrink in scope to just cover the necessary provisioner changes, although unfortunately I expect this will require some revisions due to the fact that Terraform has switched to a new WinRM client in the mean time.

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Comment by deftflux** [comment]
@apparentlymart Understood, thanks for the response.

I was wondering if I could get some feedback on my plan for this before taking the time to work on it.

I never was a fan of the changes to the communicator that were included in this, but I needed some way to make the password accessible outside the aws instance resource without leaking a plaintext password into the state file.  But I've since come up with this idea instead:

The aws instance resource will export the encrypted password data.  Then, rather than adding decryption to the communicator, I would add built-in functions available when doing interpolated strings that would be capable of taking the password data and private key and decrypting it.  There are already other conversion and encryption functions available there, so I think it would be more at home.  Then if you set the communicator password to the decrypted value, it still won't end up in the state file, since communicator properties aren't stored there.

So yeah, this would end up being two PR's; one in the aws provider to enable getting the password data (and auto-populating it to that resource's communicator), and one in terraform core to add built-in functions needed to be able to decrypt and use it elsewhere.

**Comment by apparentlymart** [comment]
Using a function to decrypt it sounds like a good alternative to me! Keeps these concerns separated better, and -- depending on what encryption algorithm it uses -- can hopefully also be used for other purposes as well.

**Comment by deftflux** [comment]
For any who are still following this, one half is done now: https://github.com/terraform-providers/terraform-provider-aws/pull/2219

Show your support over there for getting it merged.

**Comment by deftflux** [comment]
Just submitted the second half of this: https://github.com/hashicorp/terraform/pull/16647

It's all ready to go.  Just waiting for merge now.

**Pull request closed without merging**
