### PR TITLE
[WIP] Issue-5648: aws_db_instance iops param should be only being used when storage_type is io1

### PR DESCRIPTION
**Pull request by iceycake**

### CODE REVIEW

**Comment by catsby** [comment]
Hey @iceycake thanks for opening this!

I think the idea here is correct, but I'm not sure the implementation is quite what we need. For example, `storage_type` is optional both in Terraform and the API (Default: io1 if the Iops parameter is specified; otherwise standard) 

So here, if the user omits `storage_type`, I think we'll get a nil pointer dereference in the `isIopsSupportedStorageType` method. 

I think we can fix this by introducing some logic like so:

- if `storage_type` is supplied, use that for `StorageType`. If `iops` is supplied and storage type is not `io1`, log a warning and ignore the `io1` value. 

- If `storage_type` is not set, and `iops` is set, log that `storage_type` was omitted and the API will assume `io1` because we specify an `iops` value. 

I believe that should cover our bases, how does that sound? It doesn't look like we ever call `d.Set("iops")` so that should work out in our favor.

**Comment by iceycake** [comment]
Makes sense.  I will take a look and submit the changes based on your comment.

**Comment by Bowbaq** [comment]
probably related https://github.com/hashicorp/terraform/pull/5676

**Comment by catsby** [comment]
Thanks @iceycake – let me know when this is ready for another look!

**Comment by iceycake** [comment]
Try to find spare time to get this re-implement.  Marked this as WIP.

**Comment by catsby** [comment]
Hey I'm going to go ahead and close this for now. Let us know if you pick it back up again!

**Pull request closed without merging**
