### PR TITLE
Colorize changes of attributes outputs

### PR DESCRIPTION
**Pull request by sylr**
This help us to have a better vision of what is going to happen in big plans.

Signed-off-by: Sylvain Rabot <s.rabot@lectra.com>

### CODE REVIEW

**Comment by apparentlymart** [comment]
Hi @sylr! Thanks for working on this and sorry for the delayed response.

Would you mind sharing a screenshot of this in your terminal so we can see what you're going for here?

I like the idea of this in principle as a way to more easily recognize the status of each change. My concern is that we're trying to move away from presenting important information in colored text because it can cause readability problems for those with poorly-configured terminals and/or limited vision. Therefore I wonder if we could compromise by making use of the same symbols we use for the resource-level diffs to apply the coloring to something less critical than the main values, like this:

```
  ~ aws_instance.foo
    ~ tags.Name:        "foo" => "bar"
    + tags.Environment: "production"
```

If we color the per-attribute symbols in the same way as the per-resource symbols, I think that'll get a similar benefit of easier scanning for those who can see color, while leaving the main content in the terminal default color to maximize readability.

What do you think?

**Comment by sylr** [comment]
I'm all for marking attributes with different signs according to the type of change but I wouldn't discard colors, it's the most convenient for most of all.

However implementing a switch that could turn colouring off (or turn it on according to the default behaviour you want to implement) could be a good compromise. It should not be that hard to implement as https://github.com/mitchellh/colorstring already has a mechanism (Colorize.Disable) to discard all colour references (https://github.com/mitchellh/colorstring/blob/master/colorstring.go#L46).

Cheers.

**Comment by apparentlymart** [comment]
Hi @sylr,

Sorry I wasn't clear in my previous response. I was not suggesting that we avoid coloring _altogether_, but rather that we apply the coloring to the `+`, `-` and `~` symbols instead of to the values.

**Comment by sylr** [comment]
I personally prefer that the color applies to the whole line, like a diff output.

**Pull request closed without merging**
