### PR TITLE
Added role_arn example usage to terraform_remote_state data source

### PR DESCRIPTION
**Pull request by jpancoast**
I had trouble finding an example of how to use a role_arn for reading the remote state in S3 using a role that had to be assumed. I thought this would make a good example in the documentation.

Fixes #

## Target Release

1.5.x

### NEW FEATURES | UPGRADE NOTES | ENHANCEMENTS | BUG FIXES | EXPERIMENTS

 

-

### CODE REVIEW

**Comment by crw** [comment]
Thanks! Please sign the CLA and I will notify the docs team for review.

**Comment by jpancoast** [comment]
Sorry, @crw , just signed the CLA, didn't see this until now. Thank you!

**Comment by crw** [comment]
No worries, the docs team has been backed up on work in any case. Thanks!

**Review by justinretzolk — COMMENTED** [review]
Hey @jpancoast 👋 Thank you for taking the time to raise this contribution! The [document](https://developer.hashicorp.com/terraform/language/state/remote-state-data) that you're looking to edit here covers what the `terraform_remote_state` data is, how and when it's generally used, and how to directly configure the data source. Where the current examples outline general use cases, the one that you're looking to add with this pull request is more of a specific S3-related scenario.

Referring to the [`config` argument](https://developer.hashicorp.com/terraform/language/state/remote-state-data#config) description, it directs the reader to the documentation for the relevant backend for more specific details. With that in mind, this type of example would be more suited to the [S3 backend documentation](https://developer.hashicorp.com/terraform/language/settings/backends/s3), however, there's an existing example in the [Assume Role Configuration](https://developer.hashicorp.com/terraform/language/settings/backends/s3#assume-role-configuration) section. Given that, I'm not sure that this change is necessary at this time, and so will be closing this pull request.

**Pull request closed without merging**
