### PR TITLE
Use a set for service account scopes.  Fix #1759

### LINKED ISSUE #1759: Order of returned scopes in GCE different to input config
I am trying out a fix that uses a set instead of a list for the scopes.  However it is blocked because the StateFunc doesn't work for sets.

### PR DESCRIPTION
**Pull request by sparkprime**

### CODE REVIEW

**Comment by sparkprime** [comment]
@phinze This may need a state migration function I think?

**Comment by phinze** [comment]
@sparkprime Yep - should be pretty similar to the stuff I did in https://github.com/hashicorp/terraform/blob/master/builtin/providers/google/resource_compute_instance_migrate.go

Seems like this is something we could write an AccTest for to guard against regression too, no?

**Comment by sparkprime** [comment]
Is there a way to test if the plan is empty?

**Comment by phinze** [comment]
@sparkprime the AccTests do that for you now! see #1757 and #1443 :grinning:

**Comment by sparkprime** [comment]
That should cover that then! :)

I'll take a look at the migration function...

**Comment by dcarley** [comment]
There's also #1697

**Comment by sparkprime** [comment]
@dcarley heh that is literally the 3rd time this has happened :)

**Comment by sparkprime** [comment]
Ok so your PR is basically the same as this one, and we need a state migration function anyway so I'm just going to keep going and do that now.

**Comment by sparkprime** [comment]
Actually your test is more thorough, we should merge.

**Comment by dcarley** [comment]
No problem. Can you explain or point to something about what the state migration is necessary? It seemed to "just work". I've looked at some previous PRs and couldn't really figure it out.

**Comment by sparkprime** [comment]
It is necessary for people with "old" tfstate files to be able to continue to use terraform without recreating their infrastructure.  With this change, all the scopes would appear to change, and that would redeploy all instances.

**Comment by dcarley** [comment]
Gotcha. Maybe I didn't test in the right order.

It's late for me now. Do you want to cherry pick my commit with the test and carry on?

**Comment by sparkprime** [comment]
@dcarley I went ahead and grabbed it.

@phinze PTAL

**Comment by sparkprime** [comment]
Ok I'm going to use my new-found powers to merge this :)

**Pull request merged**
