### PR TITLE
module provider inheritance

### PR DESCRIPTION
**Pull request by jbardin**
The primary goal of this PR is to define the new provider inheritance model, while hoisting the provider inheritance mechanisms into the config itself. The new providers field in the module block allows users to declare a provider configuration to apply within a module. Since this new inheritance mechanism is configuration based, it is much simpler to apply all the inheritance rules within the config, rather than searching for provider configurations during graph evaluation.

The only remnant of "inheritance" in core is now through the provider input cache. Though the cached Input result no longer force unintended inheritance, the fields added by a provider's Input call are added to the config of other providers by the same name. It might be advantageous to remove the input cache just as we've done with the config cache, but that would cause every Provider missing fields to prompt, which may be inconvenient for users relying on manual Inputs. 

Due to the removal of inheritance in the terraform package, orphaned module resources can no longer be destroyed without a provider config. This is not optimal, but can be handled in a later PR to keep this more manageable.

### CODE REVIEW

**Comment by vvondra** [comment]
could this theoretically fix https://github.com/hashicorp/terraform/issues/15520?

**Comment by jbardin** [comment]
Hi @vvondra, 

Unfortunately not. This still will configure the provider for each provider instance in the configuration.

I am exploring some paths that might be able to reduce the number of virtual "provider instances" in the graph, but optimizing for lots of providers is still a ways off.

**Comment by jbardin** [comment]
Orphaned modules will have to wait, merging this into a dev branch.

**Comment by thomasbiddle** [comment]
@jbardin Can we get an example of how this would look? I was following #11578 originally.

**Comment by jbardin** [comment]
@thomasbiddle,

I'm not sure what you're looking for exactly; does the documentation help answer your question? https://www.terraform.io/docs/modules/usage.html#providers-within-modules

**Comment by jbardin** [comment]
@bukzor: Removing modules is working as intended. If the provider configuration is removed, there's no way to reliably destroy the resources in a module. If the provider configuration is passed into the module, then you can retain the configuration separate from the module source.

**Comment by bukzor** [comment]
I'm hearing that the issue doesn't exist. I've worked up a demo and explained the problems in [this github repo](https://github.com/bukzor/terraform-gke-k8s-demo). Should I file each of those gripes as an issue, or would you be willing to do triage? There's two misfeatures and one outright bug here, by my count.

https://github.com/bukzor/terraform-gke-k8s-demo

**Comment by jbardin** [comment]
Hi @bukzor,

I haven't gone through that repo in detail, but the first thing that stands out is that there are provider configurations within the module, which is what isn't going to work. We do have some known issues around providers, like #13018, and some new things implemented like #16835.

Of course feel free to file an other issues you have that aren't covered.

**Pull request merged**
