### PR TITLE
Updated note about variable files and secret variables

### PR DESCRIPTION
**Pull request by shanielh**
Added note about multiple `-var-file` statements in the `terraform` command.

### CODE REVIEW

**Comment by apparentlymart** [comment]
:+1: to the idea. Good to clarify this as it's a very useful capability for managing multiple environments from a single config.

It looks like for the rest of this file the Markdown is hard-wrapped, but your new additions are not. Could you adjust your new paragraphs to conform to the wrapping precedent of the paragraphs above?

**Comment by shanielh** [comment]
I've updated it, I think it should be good now.

**Comment by apparentlymart** [comment]
Thanks! LGTM

**Comment by josephholsten** [comment]
:+1: delightfully boring!

**Comment by apparentlymart** [comment]
Thanks! I tweaked this a little and merged it as 9a6f680eda2eef2044fee8b0cc8ffd8bdfa82231.

**Pull request closed without merging**
