### PR TITLE
provider/cloudstack: add security_group_names

### PR DESCRIPTION
**Pull request by mcanevet**

### CODE REVIEW

**Comment by svanharmelen** [comment]
@mcanevet could we maybe also add `security_group_ids` while we are at it :wink: And then also add the `ConflicsWith` params... Would make it nice and complete.

**Comment by mcanevet** [comment]
@svanharmelen fixed

**Comment by mcanevet** [comment]
@svanharmelen Travis is happy now!

**Comment by mcanevet** [comment]
@svanharmelen rebasing in progress...

**Comment by mcanevet** [comment]
@svanharmelen rebased

**Comment by svanharmelen** [comment]
And again, thanks! 😀

**Pull request merged**
