### PR TITLE
CLC update: tests and alias

### PR DESCRIPTION
**Pull request by ack**
customer requested account alias be optionally available. updated tests as per previous PR discussion

### CODE REVIEW

**Comment by phinze** [comment]
Hi @ack - thanks for this!

I see `builtin/providers/clc/resource_clc_load_balancer_test.go` is going entirely away here - is that because it's exercised elsewhere?

If that's the case, I think we should keep a file there with a comment pointing to where it is tested, just because the "every resource has a test file sibling" is such a pattern for us.

**Comment by ack** [comment]
gotcha, resurrected an empty test

**Comment by phinze** [comment]
LGTM

**Comment by phinze** [comment]
Congrats on your first merge :smile: 

There's a user facing change here - so let's have you add a line to the changelog under IMPROVEMENTS about the fact that you can now set an account alias. You can follow the patterns elsewhere in the file and commit right to master. Most of us just use the GitHub `edit` button just after merging to keep the workflow lightweight.

**Comment by fatmcgav** [comment]
Cheers for the quick turnaround @ack...

**Pull request merged**
