### PR TITLE
Adding firehose to elastic search support

### PR DESCRIPTION
**Pull request by iceycake**
Attempting to add firehose stream to elastic search support as stated in https://github.com/hashicorp/terraform/issues/6680

### CODE REVIEW

**Comment by iceycake** [comment]
Please review the elasticsearch_configuration schema before I actually code the rest.

**Comment by stack72** [comment]
Hi @iceycake 

The schema looks solid - I think the only thing that seems to be missing is `retry_options`

The rest looks ready to get started with the CRUD

P.

**Comment by iceycake** [comment]
@stack72 Interesting, the retry_options param is also missing from the redshift configuration (https://github.com/hashicorp/terraform/pull/7375).  I wonder if there is any reason behind it?

**Comment by iceycake** [comment]
@stack72  `make` works on the branch but I ran into problem on the acceptance test.  The error message is not informative: "Invalid Argument".  Can you help pointing me to the right direction to fix it?

**Comment by iceycake** [comment]
@stack72 The acceptance test took a loooooooong to run but I think I got it.

```
USHOLACH01-ML:terraform andy.chan$ make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSKinesisFirehoseDeliveryStream_ElasticsearchConfigUpdates'
==> Checking that code complies with gofmt requirements...
/Users/andy.chan/Projects/go/bin/stringer
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/08/05 11:38:23 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSKinesisFirehoseDeliveryStream_ElasticsearchConfigUpdates -timeout 120m
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_ElasticsearchConfigUpdates
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ElasticsearchConfigUpdates (1684.12s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/aws    3009.142s
```

Please review the PR.  Thanks.

**Comment by iceycake** [comment]
Tune the timeout settings and it's way better now.

```
USHOLACH01-ML:terraform andy.chan$ make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSKinesisFirehoseDeliveryStream_ElasticsearchConfigUpdates'
==> Checking that code complies with gofmt requirements...
/Users/andy.chan/Projects/go/bin/stringer
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/08/05 15:55:01 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSKinesisFirehoseDeliveryStream_ElasticsearchConfigUpdates -timeout 120m
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_ElasticsearchConfigUpdates
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ElasticsearchConfigUpdates (1712.07s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/aws    1712.092s
```

**Comment by stack72** [comment]
Hi @iceycake 

Thanks for the work here :)

This LGTM! Functionality works as expected

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSKinesisFirehoseDeliveryStream_'
==> Checking that code complies with gofmt requirements...
/Users/stacko/Code/go/bin/stringer
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/08/08 11:18:43 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSKinesisFirehoseDeliveryStream_ -timeout 120m
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_s3basic
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_s3basic (185.49s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_s3ConfigUpdates
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_s3ConfigUpdates (326.47s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_RedshiftConfigUpdates
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_RedshiftConfigUpdates (820.64s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_ElasticsearchConfigUpdates
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ElasticsearchConfigUpdates (2157.09s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	3489.719s
```

Merging now!

Paul

**Pull request merged**
