### PR TITLE
Optimize some code and fix some spelling of words

### PR DESCRIPTION
**Pull request by wgliang**

### CODE REVIEW

**Comment by tomelliff** [comment]
Out of curiosity are you using a tool that's flagging these changes? If so, what tool is that?

**Comment by apparentlymart** [comment]
Hi @wgliang! Thanks for working on this.

We're generally a little nervous about this sort of commit that makes loads of assorted changes across the whole codebase, since it's hard to review and it can making history investigation harder (with tools like `git blame`) by obscuring the origins of certain code.

I looked over the changes you made here, and indeed they all seem reasonable in isolation (as far as I was able to tell just by reading them), but we usually prefer to make "cleanup" changes of this sort as part of changes to the surrounding code, so that we're in the right "context" to properly test (interactively) the change along with its surrounding code, and so that it's fixed as part of commits we would've naturally made to that portion of the code anyway. For a project of this size, commit history is very important in debugging.

So with that said: I appreciate the time you took to do this. I don't think we can merge it as-is for the above reasons. :confounded: It looks like there's a few different sorts of change here:

* Some of what you corrected here are typos that appear in the UI, and I _would_ like to get _those_ in, if you'd be willing to separate them, because they directly affect end-users and their impact is obvious.
* Typos in comments are also annoying, but better fixed in conjunction with changes to the neighboring code.
* Some of these changes are rewrites of some code to apparently-equivalent code, presumably either to make it more concise or to make it execute faster. These feel like the riskiest changes, since although I can look at each one in isolation and see that it seems equivalent, there's a _lot_ to work through here and it'd be easy to miss something along the way. For these, it'd be better to submit them separately so that they can be reviewed and tested in isolation, but on the other hand the real-world _impact_ of many of these is perhaps not worth the overhead that implies, in which case again I think we'd prefer to wait and clean these things up next time some more significant changes are being made in the surrounding code, where that additional review/testing can be amortized with the review/testing we'd be doing anyway.

I hope that seems reasonable. I never like saying "no" to things like this, and I appreciate your work here; in the big picture, we need to be careful to manage time and risk, and the time it would take to review and test each of these items in isolation, and the history "noise" it would create, seem to outweigh the benefit in this case.

Thanks again for working on this. I'd also second @tomelliff's comment that if you used some automated tool to find these it'd be good to know its name, and then perhaps we can make use of it to ensure that we _do_ correct such things when we're working on nearby code. Many of us currently use `lint` in our editors to easily see opportunities to improve, but if you know of a more advanced tool it'd be great to know about it.

**Comment by wgliang** [comment]
Has been curious to submit the PR on github when I will submit multiple PRs, but they let me merge into one, such as moby and kubernetes; but some let me split a big commit into multiple PRs, for example terraform. Can you tell me why? Greatful!

**Comment by nbering** [comment]
@wgliang Some projects prefer that commits touch fewer files to avoid merge conflicts when there are a large number of open pull requests. It just makes it easier to manage the effect of changes.

**Comment by wgliang** [comment]
Ok I will close this PR and submit multiple separate PRs.

**Pull request closed without merging**
