### PR TITLE
terraform: fix ContextPlan test failure on Windows

### PR DESCRIPTION
**Pull request by ceh**
The attributes in the diff are %#v-formatted. This means that all `\`
characters in the Windows paths are escaped with a `\`. We need to
escape the `\` characters in cwd, module, and root before doing any
comparison work.

Fixes the following test failure on Windows:
```
--- FAIL: TestContextPlan_pathVar (0.00s)
        context_test.go:3833: bad:
                DIFF:

                CREATE: aws_instance.foo
                  cwd:    "" => "C:\\Users\\ceh\\src\\github.com\\hashicorp\\terraform\\terraform/barpath"
                  module: "" => "C:\\Users\\ceh\\src\\github.com\\hashicorp\\terraform\\terraform\\test-fixtures\\plan-path-var/foopath"
                  root:   "" => "C:\\Users\\ceh\\src\\github.com\\hashicorp\\terraform\\terraform\\test-fixtures\\plan-path-var/barpath"
                  type:   "" => "aws_instance"

                STATE:

                <no state>

                expected:

                DIFF:

                CREATE: aws_instance.foo
                  cwd:    "" => "C:\Users\ceh\src\github.com\hashicorp\terraform\terraform/barpath"
                  module: "" => "C:\Users\ceh\src\github.com\hashicorp\terraform\terraform\test-fixtures\plan-path-var/foopath"
                  root:   "" => "C:\Users\ceh\src\github.com\hashicorp\terraform\terraform\test-fixtures\plan-path-var/barpath"
                  type:   "" => "aws_instance"

                STATE:

                <no state>
FAIL
exit status 1
FAIL    github.com/hashicorp/terraform/terraform        0.050s
```

### CODE REVIEW

**Comment by ceh** [comment]
All tests pass on windows/amd64 when this is rebased onto #876:

```
C:\Users\ceh\src\github.com\hashicorp\terraform (terraform-win-test)
$ git branch -vv
  command-win-tests  97227a5 config/module: fix detection of file paths on Windows
  master             c01f1a5 [origin/master] Merge pull request #864 from paystee/doc_boolean_syntax
* terraform-win-test 25cba2f terraform: fix ContextPlan test failure on Windows

C:\Users\ceh\src\github.com\hashicorp\terraform (terraform-win-test)
$ git rebase -i command-win-tests
Successfully rebased and updated refs/heads/terraform-win-test.

C:\Users\ceh\src\github.com\hashicorp\terraform (terraform-win-test)
$ make.bat test
ok      github.com/hashicorp/terraform  0.050s
ok      github.com/hashicorp/terraform/builtin/bins/provider-atlas      0.043s
ok      github.com/hashicorp/terraform/builtin/bins/provider-aws        0.046s
ok      github.com/hashicorp/terraform/builtin/bins/provider-cloudflare 0.090s
ok      github.com/hashicorp/terraform/builtin/bins/provider-cloudstack 0.051s
ok      github.com/hashicorp/terraform/builtin/bins/provider-consul     0.049s
ok      github.com/hashicorp/terraform/builtin/bins/provider-digitalocean       0.045s
ok      github.com/hashicorp/terraform/builtin/bins/provider-dnsimple   0.045s
ok      github.com/hashicorp/terraform/builtin/bins/provider-google     0.043s
ok      github.com/hashicorp/terraform/builtin/bins/provider-heroku     0.046s
ok      github.com/hashicorp/terraform/builtin/bins/provider-mailgun    0.044s
ok      github.com/hashicorp/terraform/builtin/bins/provider-null       0.043s
ok      github.com/hashicorp/terraform/builtin/bins/provisioner-file    0.044s
ok      github.com/hashicorp/terraform/builtin/bins/provisioner-local-exec      0.046s
ok      github.com/hashicorp/terraform/builtin/bins/provisioner-remote-exec     0.044s
ok      github.com/hashicorp/terraform/builtin/providers/atlas  0.042s
ok      github.com/hashicorp/terraform/builtin/providers/aws    0.048s
ok      github.com/hashicorp/terraform/builtin/providers/cloudflare     0.043s
ok      github.com/hashicorp/terraform/builtin/providers/cloudstack     0.056s
ok      github.com/hashicorp/terraform/builtin/providers/consul 0.042s
ok      github.com/hashicorp/terraform/builtin/providers/digitalocean   0.044s
ok      github.com/hashicorp/terraform/builtin/providers/dnsimple       0.041s
ok      github.com/hashicorp/terraform/builtin/providers/google 0.045s
ok      github.com/hashicorp/terraform/builtin/providers/heroku 0.042s
ok      github.com/hashicorp/terraform/builtin/providers/mailgun        0.043s
ok      github.com/hashicorp/terraform/builtin/providers/null   0.043s
ok      github.com/hashicorp/terraform/builtin/provisioners/file        0.043s
ok      github.com/hashicorp/terraform/builtin/provisioners/local-exec  0.057s
ok      github.com/hashicorp/terraform/builtin/provisioners/remote-exec 0.041s
ok      github.com/hashicorp/terraform/command  0.286s
ok      github.com/hashicorp/terraform/config   0.043s
ok      github.com/hashicorp/terraform/config/lang      0.027s
ok      github.com/hashicorp/terraform/config/lang/ast  0.025s
ok      github.com/hashicorp/terraform/config/module    3.656s
ok      github.com/hashicorp/terraform/depgraph 0.028s
ok      github.com/hashicorp/terraform/digraph  0.030s
ok      github.com/hashicorp/terraform/flatmap  0.026s
ok      github.com/hashicorp/terraform/helper/config    0.040s
ok      github.com/hashicorp/terraform/helper/diff      0.042s
ok      github.com/hashicorp/terraform/helper/hashcode  0.025s
ok      github.com/hashicorp/terraform/helper/multierror        0.026s
ok      github.com/hashicorp/terraform/helper/resource  2.354s
ok      github.com/hashicorp/terraform/helper/schema    0.049s
ok      github.com/hashicorp/terraform/helper/ssh       0.191s
ok      github.com/hashicorp/terraform/plugin   0.287s
ok      github.com/hashicorp/terraform/remote   0.069s
ok      github.com/hashicorp/terraform/rpc      0.062s
ok      github.com/hashicorp/terraform/terraform        0.273s

C:\Users\ceh\src\github.com\hashicorp\terraform (terraform-win-test)
$ go version
go version devel +1b61a97 Sat Jan 24 09:56:25 2015 +0000 windows/amd64
```

**Comment by mitchellh** [comment]
Hm, I think the changes here are less clear. Can we just do a dumb string replace of `\\` with `\` and call it good? I think that with a comment would be easier to understand than this, and still gets the test done.

**Comment by ceh** [comment]
@mitchellh Please take another look.

**Comment by mitchellh** [comment]
LGTM

**Pull request merged**
