### PR TITLE
Add ability to set Performance Mode in aws_efs_file_system.

### PR DESCRIPTION
**Pull request by kwilczynski**
The Elastic File System (EFS) allows for setting a Performance Mode during
creation, thus enabling anyone to chose performance of the file system according
to their particular needs. This commit adds an optional "performance_mode"
attribute to the aws_efs_file_system resource so that an appropriate mode can be
set as needed.

Signed-off-by: Krzysztof Wilczynski <krzysztof.wilczynski@linux.com>

### CODE REVIEW

**Comment by kwilczynski** [comment]
Resolves #7773.

**Comment by kwilczynski** [comment]
Test is passing:

```
$ make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSEFSFileSystem_basic'

==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/07/25 03:16:19 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSEFSFileSystem_basic -timeout 120m
=== RUN   TestAccAWSEFSFileSystem_basic
--- PASS: TestAccAWSEFSFileSystem_basic (84.05s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	84.074s

$ make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSEFSFileSystem_importBasic'

==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/07/25 03:14:23 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSEFSFileSystem_importBasic -timeout 120m
=== RUN   TestAccAWSEFSFileSystem_importBasic
--- PASS: TestAccAWSEFSFileSystem_importBasic (34.85s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	34.873s
```

Plus, verified from the command line:

```json
$ aws efs describe-file-systems --region us-west-2
{
    "FileSystems": [
        {
            "SizeInBytes": {
                "Value": 6144
            },
            "CreationToken": "terraform-qyipifpi2zcrda6yphpslydvgy",
            "CreationTime": 1469401038.0,
            "PerformanceMode": "maxIO",
            "FileSystemId": "fs-c0e21369",
            "NumberOfMountTargets": 0,
            "LifeCycleState": "available",
            "OwnerId": "635543228030"
        }
    ]
}
```

**Comment by kwilczynski** [comment]
@phinze a few questions to you.

How does one handle import? Is there something more that needs to be done for the import to work? I've noticed that import test excludes one of the arguments, does this suppose to be like that?

Also, I personally think that "reference_name" as an attribute name is a little bit confusing, perhaps renaming it to something along the lines of "creation_token_prefix" or just "token_prefix" would make it less of a misnomer. We could also let the user decide and introduce "creation_token" and "creation_token_prefix", which would be mutually-exclusive and should the former be absent and/or empty, then the second would be take into account, and should it be empty, then we would auto-generate (so business as usual). What do you think?

**Comment by kwilczynski** [comment]
@stack72 and I had a quick chat. I will add better test coverage e.g. test validation functions, etc.

**Comment by kwilczynski** [comment]
@stack72 let me know about the attribute name change, if you have any ideas.

**Comment by kwilczynski** [comment]
Updated tests are passing:

```
$ make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSEFSFileSystem_basic'

==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/07/28 06:56:55 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSEFSFileSystem_basic -timeout 120m
=== RUN   TestAccAWSEFSFileSystem_basic
--- PASS: TestAccAWSEFSFileSystem_basic (81.56s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	81.589s

$ make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestResourceAWSEFS*'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/07/28 06:59:26 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestResourceAWSEFS* -timeout 120m
=== RUN   TestResourceAWSEFSReferenceName_validation
--- PASS: TestResourceAWSEFSReferenceName_validation (0.00s)
=== RUN   TestResourceAWSEFSPerformanceMode_validation
--- PASS: TestResourceAWSEFSPerformanceMode_validation (0.00s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	0.021s

$ make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSEFSFileSystem_importBasic'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/07/28 07:01:51 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSEFSFileSystem_importBasic -timeout 120m
=== RUN   TestAccAWSEFSFileSystem_importBasic
--- PASS: TestAccAWSEFSFileSystem_importBasic (35.37s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	35.397s
```

And verified from the command line:

```json
$ aws efs describe-file-systems --region us-west-2
{
    "FileSystems": [
        {
            "SizeInBytes": {
                "Value": 6144
            },
            "CreationToken": "supercalifragilisticexpialidocious",
            "CreationTime": 1469656720.0,
            "PerformanceMode": "maxIO",
            "FileSystemId": "fs-ae1bea07",
            "NumberOfMountTargets": 0,
            "LifeCycleState": "available",
            "OwnerId": "635543228030"
        }
    ]
}
```

**Comment by kwilczynski** [comment]
Over to you @phinze 🚀

**Comment by stack72** [comment]
Hi @kwilczynski 

This LGTM! 

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSEFSFileSystem_'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSEFSFileSystem_ -timeout 120m
=== RUN   TestAccAWSEFSFileSystem_importBasic
--- PASS: TestAccAWSEFSFileSystem_importBasic (33.59s)
=== RUN   TestAccAWSEFSFileSystem_basic
--- PASS: TestAccAWSEFSFileSystem_basic (74.61s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	108.226s
```

**Pull request merged**
