### PR TITLE
Update aws-sdk to 1.8.5

### PR DESCRIPTION
**Pull request by w32-blaster**
Bumping the aws-sdk vendor to 1.8.5
First time doing this, so I hope that I'm doing it in the right way. 
Did not find clear instructions on preferred method.

### CODE REVIEW

**Comment by stack72** [comment]
Hi @w32-blaster 

There are some changes we are making to the provider before the upgrade - we need to change the waiters as the package changed in 1.8.0

Paul

**Comment by w32-blaster** [comment]
Hi @stack72 

Yeah, Already realized from the tests. Should I close this PR? 
The reason I'm pushing on this to make it possible to extend the cloudfront resource to support timeouts. 

Tamas

**Comment by stack72** [comment]
@w32-blaster 

No, no. Keep it open but it will fail until I merge another PR first :)

Working on it atm

P.

**Comment by w32-blaster** [comment]
Cool. I was looking into fixing the Waiter part but I don't have enough context on that :)

**Comment by stack72** [comment]
it's all in our DMS resources - that's what I am changing atm :)

**Comment by w32-blaster** [comment]
For reference, we are waiting on PR https://github.com/hashicorp/terraform/pull/13291 to get merged.

**Comment by stack72** [comment]
Hi @w32-blaster 

Thanks for waiting on #13291 on this - I have finally got to merge this

So, last night, AWS SDK 1.8.8 was released - I am going to govendor update straight to this as we need it for another feature. I thank you for the work you put into the PR to help us upgrade

Paul

**Pull request closed without merging**
