### PR TITLE
provider/azurerm: suppport for primary network interface

### PR DESCRIPTION
**Pull request by kvisscher**
This brings support for setting the primary IP of a network interface.

### CODE REVIEW

**Comment by pmcatominey** [comment]
Hi @kvisscher 

Thanks for the PR!

Unfortunately we can't merge this right now as the feature is still in preview:
```
--- FAIL: TestAccAzureRMNetworkInterface_primaryNetworkInterface (148.04s)
    testing.go:265: Step 0 error: Error applying: 1 error(s) occurred:
        
        * azurerm_network_interface.test1: 1 error(s) occurred:
        
        * azurerm_network_interface.test1: network.InterfacesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="SubscriptionNotRegisteredForFeature" Message="Subscription xxx is not registered for feature Microsoft.Network/AllowMultipleIpConfigurationsPerNic required to carry out the requested operation." Details=[]
```
Once this feature is in general availability we will circle back to this PR, #9874 is also tracking this feature request.

**Comment by dominik-lekse** [comment]
Hi @pmcatominey, @kvisscher,

as from 22nd March, the "Multiple IP addresses per network interface" feature has been announced to be generally available in all public regions (refer to https://azure.microsoft.com/de-de/updates/ga-multiple-ips-per-nic/).

Can we consider this PR to be merged into the upcoming release?

// Dominik

**Comment by tombuildsstuff** [comment]
@dominik-lekse thanks for the update - it's great to see that this has hit GA :)

Hi @kvisscher

I've taken a look into your PR - and it looks good :) There's a couple of minor changes needed in order to be able to merge this:

  1) The Linter is complaining about the test file - can we run `make fmt` which will fix this?
  2) I've run the tests and the `TestAccAzureRMNetworkInterface_primaryNetworkInterface` test is failing - is it possible to fix this?
  3) Update the Documentation to include the `primary` field (and it's default value)

Out of interest -  when specifying only a single IP Configuration, does the Azure API set a default value for `primary`? [The Azure Docs](https://docs.microsoft.com/en-us/rest/api/network/networkinterfaces#NetworkInterfaces_CreateOrUpdate) don't state either way - but it'd be good to mention if it does :)

Thanks!

**Comment by dominik-lekse** [comment]
@tombuildsstuff Regarding the value `primary` in case of a single IP configuration, you are right that the official docs are not quite clear on this. When checking this in the [relevant implementation of Azure CLI 2.0](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-network/azure/cli/command_modules/network/custom.py#L859) the value is `false`by default and when using only a single IP configuration. Therefore, I would consider the default set in this pull request as correct. I will reserve time this week to test it.

Another point: We could add a validation that only one `primary = true` exists in all IP configurations of a NIC.

**Comment by dominik-lekse** [comment]
Are there any plans yet to migrate this to the new terraform provider repository?

@kvisscher I can offer to help you here.

**Comment by 422158** [comment]
why is this not merged yet?

**Comment by tombuildsstuff** [comment]
Hey @kvisscher 

I hope you don't mind, but I've ported this PR over to the new repository in https://github.com/terraform-providers/terraform-provider-azurerm/pull/245 as this has now hit GA. As such I'm going to close this PR for the moment - but I'd like to thank you for your contribution here!

Thanks!

**Pull request closed without merging**
