### PR TITLE
[WIP] provider/aws: AWS WAF Regional Web ACL Association support

### PR DESCRIPTION
**Pull request by yusukegoto**
This PR is from #13676.

test

```
resource "aws_wafregional_ipset" "ipset" {
  name = "tfIPSet"
  ip_set_descriptors {
    type = "IPV4"
    value = "192.0.7.0/24"
  }
}

resource "aws_wafregional_rule" "wafrule" {
  depends_on = ["aws_wafregional_ipset.ipset"]
  name = "tfWAFRule"
  metric_name = "tfWAFRule"
  predicates {
    data_id = "${aws_wafregional_ipset.ipset.id}"
    negated = false
    type = "IPMatch"
  }
}

resource "aws_wafregional_web_acl" "wafacl" {
  depends_on = ["aws_wafregional_ipset.ipset", "aws_wafregional_rule.wafrule"]
  name = "tfWebACL"
  metric_name = "tfWebACL"
  default_action {
    type = "ALLOW"
  }
  rules {
    action {
       type = "BLOCK"
    }
    priority = 1
    rule_id = "${aws_wafregional_rule.wafrule.id}"
  }
}

resource "aws_vpc" "main" {
  cidr_block = "10.1.0.0/16"
}

resource "aws_subnet" "foo" {
  vpc_id = "${aws_vpc.main.id}"
  cidr_block = "10.1.1.0/24"
}

resource "aws_subnet" "bar" {
  vpc_id = "${aws_vpc.main.id}"
  cidr_block = "10.1.2.0/24"
}

resource "aws_alb" "alb" {
    subnets = ["${aws_subnet.foo.id}", "${aws_subnet.bar.id}"]
}

resource "aws_wafregional_web_acl_association" "wafassociation" {
    depends_on = ["aws_alb.alb", "aws_wafregional_web_acl.wafacl"]
    web_acl_id = "${aws_wafregional_web_acl.wafacl.id}"
    resource_arn = "${aws_alb.alb.arn}"
}
```

exec
```
```

### CODE REVIEW

**Comment by ajvb** [comment]
Any ideas when this will get merged?

**Comment by DennyLoko** [comment]
Hello @yusukegoto. Since #13705 has already been merged, would you mind to rebase this?

**Comment by robertoandrade** [comment]
Any progress on any of these WAF Regional PRs?

**Comment by apparentlymart** [comment]
Hello @yusukegoto, and thanks for working on this!

As part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it.

If you or someone else has the time and motivation to apply the same changes to [the `aws` provider repository](https://github.com/terraform-providers/terraform-provider-aws) and open a new PR there, the maintainers of that provider should be able to review and merge it.

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Comment by moonyoungheo** [comment]
Any progress on any of these WAF Regional PRs?

**Pull request closed without merging**
