### PR TITLE
[WIP] ultradns: add dirpool, tcpool & probe resources

### PR DESCRIPTION
**Pull request by josephholsten**
Yes this is huge. It'll be broken into smaller pieces as soon as we put it through aggressive manual testing.

### CODE REVIEW

**Comment by Pryz** [comment]
@josephholsten hi there, do you manage Resource Distribution pools in this PR ? Is it the "dirpool" thing ? thanks

**Comment by josephholsten** [comment]
@Pryz this actually doesn't do rdpools, but they'd be a super quick feature. They're essentially a subset of the dirpool and tcpool implementations, with none of the fancy stuff, then with a different profile `@context` value.

I'll gladly help you get a local dev&test environment if you'd like to try your hand at it.

**Comment by Pryz** [comment]
Will be happy to help on that :)

**Comment by stack72** [comment]
Closed in favour of #9788

**Pull request closed without merging**
