### PR TITLE
provider/aws: Support ec2-classic and vpc in beanstalk recurring plans.

### LINKED ISSUE #6257: Recurring plan issue with aws_elastic_beanstalk_environment and aws:autoscaling:launchconfiguration:SecurityGroups setting
Hi there,

### Terraform Version
Using Terraform v0.6.14

### Affected Resource(s)
aws_elastic_beanstalk_environment

### Expected Behavior
When applying custom security groups to instances in a beanstalk using aws_elastic_beanstalk_environment and the "aws:autoscaling:launchconfiguration:SecurityGroups" setting, subsequent plans should show no changes required.

### Actual Behavior
Subsequent plans show a change to this setting is needed

### Steps to Reproduce
1. Include the following in your beanstalk configuration:

  setting {
    namespace = "aws:autoscaling:launchconfiguration"
    name = "SecurityGroups"
    value = "my_securitygroup_a,my_securitygroup_b"
  }

2. `terraform apply`
3. `terraform plan`

You'll see output in the plan like:

    setting.1137948120.name:      "SecurityGroups" => ""
    setting.1137948120.namespace: "aws:autoscaling:launchconfiguration" => ""
    setting.1137948120.value:     "my_securitygroup_a,my_securitygroup_b,awseb-e-mbtpf9p2hy-stack-AWSEBSecurityGroup-OMD0ATLU3CZ8" => ""
    ...
    setting.3267732739.name:      "" => "SecurityGroups"
    setting.3267732739.namespace: "" => "aws:autoscaling:launchconfiguration"
    setting.3267732739.value:     "" => "my_securitygroup_a,my_securitygroup_b"

### Important Factoids
awseb-e-mbtpf9p2hy-stack-AWSEBSecurityGroup-OMD0ATLU3CZ8 will be a security group that AWS EB adds to the instance to allow ingress rules from the loadbalancer & apply rules specified by  
aws:autoscaling:launchconfiguration:SSHSourceRestriction

### References
This seems a similar issue to the aws:elb:loadbalancer:ManagedSecurityGroup setting issue that was fixed with https://github.com/hashicorp/terraform/pull/4691

I believe terraform needs to ignore the security group added by AWS when doing a compare.

### PR DESCRIPTION
**Pull request by dharrisio**
Fix Elastic Beanstalk recurring plans when additional security groups
are supplied. In the previous version, only non-default vpc security
groups would be handled by dropGeneratedSecurityGroup.

Fixes #6257 

If there's a way to write tests for this I'd like to add those as well. Currently not sure how to verify that subsequent plans return an empty diff.

### CODE REVIEW

**Comment by stack72** [comment]
Hey @dharrisio 

Is there a way we can test this works as expected? 

P.

**Comment by dharrisio** [comment]
@stack72 I think I was a bit confused when I wrote that original comment, since the tests will fail if there is a non-empty diff after apply. Ran into a few other issues adding the vpc test for this yesterday, but I'm planning on finishing this up today, so we can get this merged soon!

**Comment by stack72** [comment]
👍 thanks so much :)

**Comment by dharrisio** [comment]
@stack72 Added the VPC test for this.

Tests:
```
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSBeanstalk -timeout 120m
=== RUN   TestAccAWSBeanstalkApp_basic
--- PASS: TestAccAWSBeanstalkApp_basic (17.69s)
=== RUN   TestAccAWSBeanstalkConfigurationTemplate_basic
--- PASS: TestAccAWSBeanstalkConfigurationTemplate_basic (23.33s)
=== RUN   TestAccAWSBeanstalkConfigurationTemplate_VPC
--- PASS: TestAccAWSBeanstalkConfigurationTemplate_VPC (27.46s)
=== RUN   TestAccAWSBeanstalkConfigurationTemplate_Setting
--- PASS: TestAccAWSBeanstalkConfigurationTemplate_Setting (21.27s)
=== RUN   TestAccAWSBeanstalkEnv_basic
--- PASS: TestAccAWSBeanstalkEnv_basic (353.91s)
=== RUN   TestAccAWSBeanstalkEnv_tier
--- PASS: TestAccAWSBeanstalkEnv_tier (611.89s)
=== RUN   TestAccAWSBeanstalkEnv_outputs
--- PASS: TestAccAWSBeanstalkEnv_outputs (384.20s)
=== RUN   TestAccAWSBeanstalkEnv_cname_prefix
--- PASS: TestAccAWSBeanstalkEnv_cname_prefix (384.07s)
=== RUN   TestAccAWSBeanstalkEnv_config
--- PASS: TestAccAWSBeanstalkEnv_config (514.57s)
=== RUN   TestAccAWSBeanstalkEnv_resource
--- PASS: TestAccAWSBeanstalkEnv_resource (395.33s)
=== RUN   TestAccAWSBeanstalkEnv_vpc
--- PASS: TestAccAWSBeanstalkEnv_vpc (534.25s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/aws    3267.994s
```

**Comment by stack72** [comment]
Hi @dharrisio 

Just ran the tests on this and it LGTM! Thanks (again!) for all the work on BeanStalk :)

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSBeanstalkEnv_'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSBeanstalkEnv_ -timeout 120m
=== RUN   TestAccAWSBeanstalkEnv_basic
--- PASS: TestAccAWSBeanstalkEnv_basic (482.97s)
=== RUN   TestAccAWSBeanstalkEnv_tier
--- PASS: TestAccAWSBeanstalkEnv_tier (594.87s)
=== RUN   TestAccAWSBeanstalkEnv_outputs
--- PASS: TestAccAWSBeanstalkEnv_outputs (383.94s)
=== RUN   TestAccAWSBeanstalkEnv_cname_prefix
--- PASS: TestAccAWSBeanstalkEnv_cname_prefix (373.88s)
=== RUN   TestAccAWSBeanstalkEnv_config
--- PASS: TestAccAWSBeanstalkEnv_config (576.01s)
=== RUN   TestAccAWSBeanstalkEnv_resource
--- PASS: TestAccAWSBeanstalkEnv_resource (427.95s)
=== RUN   TestAccAWSBeanstalkEnv_vpc
--- PASS: TestAccAWSBeanstalkEnv_vpc (687.32s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	3526.950s
```

Paul

**Pull request merged**
