### PR TITLE
helper/schema: add test for statefunc with nested sets

### PR DESCRIPTION
**Pull request by phinze**
refs #1759

### CODE REVIEW

**Comment by mitchellh** [comment]
Does this fail currently?

**Comment by phinze** [comment]
@mitchellh no see comment on linked issue - it passes and i was double checking. we can keep it or throw it away, it's mostly for illustrative purposes

**Comment by mitchellh** [comment]
Comment wasnt there when I first commented :O :) But okay, LGTM

**Comment by phinze** [comment]
Oh HA. He's TOO FAST. :runner: :dash:

**Pull request merged**
