### PR TITLE
Adding a simple way to support authenticate registry.

### PR DESCRIPTION
**Pull request by IsmailMehdi**
This change will allow terraform to support the docker mechanism for authenticated private registry. It is simple in the sense that it does not require any changes to the manifest. The credentials are provided via the normal docker config.json authentication scheme.

### CODE REVIEW

**Comment by kyhavlov** [comment]
👍 this is a very convenient way to pass registry credentials to terraform

**Comment by stack72** [comment]
Hi @IsmailMehdi 

Thanks for the PR here. Please can you add an acceptance test on how we can test this works as expected?

Thanks

Paul

**Comment by IsmailMehdi** [comment]
@stack72 Would love to add a test, unfortunately I am not sure how to establish a private registry with authentication enabled as part of the test. Any thoughts on that ?

**Comment by IsmailMehdi** [comment]
@stack72 Any thoughts on this ?

**Pull request closed without merging**
