### PR TITLE
Update GCS backend docs for TF >=0.12

### PR DESCRIPTION
**Pull request by lnesteroff**
Updated GCS remote backend to include the >=0.12 remote backend data source formatting (incl .output before output name). The current documentation is not valid if it is run with TF >= 0.12

Fixes #

## Target Release

1.4.0

### ENHANCEMENTS

 

-  backend/gcs:  Update documentation for usage of `gcs` with `terraform_remote_state`

### CODE REVIEW

**Comment by crw** [comment]
Thanks for this submission!

**Review by SarahFrench — COMMENTED** [review]
Hi @lnesteroff 👋  thanks for this update 

This section of the docs is pretty old (6 years!) so there's a bunch of things that can be improved here. I went to go read up about the [template](https://registry.terraform.io/providers/hashicorp/template/latest/docs) provider used for this example config and I found that it has been deprecated and isn't recommended for use in newer versions of Terraform. Because of this, I'm thinking we should change the example to use a different resource so we don't encourage people to use it.

**Would you be happy to update your PR with a new example resource that uses data from `data.terraform_remote_state.foo`?** A simple example I thought of was the [local_file](https://registry.terraform.io/providers/hashicorp/local/latest/docs/resources/file) resource (see example below) but you could pick a different resource if you'd like

```
resource "local_file" "foo" {
  content  = data.terraform_remote_state.foo.outputs.greeting
  filename = "${path.module}/outputs.txt"
}
```

The above is more of a nit than a required change- please feel free to not do if you don't have time. **The only thing I think requires changes is updating `output` to `outputs`.**

Cheers! - Sarah

**Comment by lnesteroff** [comment]
Good catch, updated both your suggestions

**Review by SarahFrench — APPROVED** [review]
Thanks! I'll get this merged now

**Pull request merged**
