### PR TITLE
provider/aws: Fix flattened cloudfront lambda function associations t…

### LINKED ISSUE #11925: Error setting up a CloudFront distribution with a Lambda@Edge function
### Terraform Version
Terraform v0.8.6

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_cloudfront_distribution

### Terraform Configuration Files
```hcl
...
  cache_behavior {
    allowed_methods = ["HEAD", "GET", "OPTIONS"]
    cached_methods = ["HEAD", "GET", "OPTIONS"]
    compress = true
    forwarded_values {
      cookies {
        forward = "none"
      }
      query_string = false
    }
    min_ttl = 0
    max_ttl = 86400
    default_ttl = 86400
    path_pattern = "/lender-profile/*"
    target_origin_id = "${var.mortgage_origin_id}"
    viewer_protocol_policy = "redirect-to-https"
    lambda_function_association {
      event_type = "origin-request"
      lambda_arn = "arn:aws:lambda:us-west-2:${data.aws_caller_identity.current.account_id}:function:zgm-frontend-rewrite-lambda"
    }
  }
...
```

### Debug Output
From running `TF_LOG=DEBUG terraform refresh`
https://gist.github.com/jakepusateri/b8d11df3b3133b5b4dc46576d0f2d490

### Expected Behavior
`terraform apply` completes successfully.

### Actual Behavior
Lambda function is correctly associated in AWS, but terraform fails to save this result with the following error:
```
Error applying plan:

1 error(s) occurred:

* aws_cloudfront_distribution.distribution: Invalid address to set: []string{"cache_behavior", "3044970313", "lambda_function_association"}
```
All future `terraform refresh` attempts are similarly errored.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` a distribution with a lambda function association

### PR DESCRIPTION
**Pull request by jakepusateri**
…o be a set, not a slice

Fixes #11925

### CODE REVIEW

**Comment by pxlpnk** [comment]
Is there a plan to get this merged?

**Comment by majormoses** [comment]
@stack72 any chance of getting this looked at?

**Comment by stack72** [comment]
LGTM! Thanks for the work here - sorry it took so long to merge!

Paul

**Comment by sandyfox** [comment]
https://www.terraform.io/docs/providers/aws/r/lambda_event_source_mapping.html
This document says "The event source ARN - can either be a Kinesis or DynamoDB stream". I don't see an option to attach cloudfront as a source trigger to lambda (edge). Using Terraform v0.9.3.

**Comment by elblivion** [comment]
@sandyfox IIUC you have to set it in Cloudfront, not as a regular event source mapping: https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html#lambda_function_association

**Comment by sandyfox** [comment]
Great thank you, but It would be nice to control it from lambda too. When there is an option in the console I believe it should be in CLI too.

**Pull request merged**
