### PR TITLE
implement "openstack_networking_port_v2" resource

### PR DESCRIPTION
**Pull request by JeanMertz**
A couple of notes:

* I didn't write any tests, because I apparently can't even *break* any tests. Whenever I change random test values in `_test.go` files, and run `go test ./...`, all tests still pass. As soon as I manage to get a test-workflow going, I will try my hand at the tests.

* I tested this on my own OpenStack environment, and things work as expected.

* It seems the resource `mac_address` value is "updated" on every run, if left unspecified. This is something I also mentioned in #1784 but I am unsure if it is a fault of my usage of Terraform, or the implementation.

### CODE REVIEW

**Comment by mitchellh** [comment]
@JeanMertz Are you running `make testacc`? `go test` will not run acceptance tests.

**Comment by mitchellh** [comment]
This LGTM. Let me know when you can get the tests passing.

**Comment by dupuy** [comment]
@catsby this issue could use a **provider/openstack** label...

**Comment by JeanMertz** [comment]
@mitchellh thanks for the heads up. I was under the impression that the `_test.go` files where unit-tests. I guess I didn't look at them thoroughly.

I'll work on the tests this weekend so this can be pulled.

**Comment by jtopjian** [comment]
@JeanMertz If you're interested, [here's](https://gist.github.com/jtopjian/4ffc82bfcbbcc78d07e4) a Terraform configuration and build script to build out a devstack environment and run the suite of acceptance tests. You can tweak it as needed.

**Comment by josephholsten** [comment]
@JeanMertz did you ever get tests working? anything you need to finish this out?

**Comment by jtopjian** [comment]
Closing in favor of #3731. @JeanMertz's original commit is still included :smile:

**Comment by JeanMertz** [comment]
Sorry for letting this linger guys. Awesome to see it getting picked up to the finish line :+1:

**Pull request closed without merging**
