### PR TITLE
update docs for aws instance source_dest_check

### PR DESCRIPTION
**Pull request by dwradcliffe**
Default should be false, not true.

### CODE REVIEW

**Comment by phinze** [comment]
Thanks for this! This situation is actually a little tricky...

The default in AWS is true:

https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_NAT_Instance.html#EIP_Disable_SrcDestCheck

But reviewing the code, it does seem like we don't respect this default, and that the Terraform default ends up being effectively false.

If that's the case, this is a Terraform bug I think. Pinging @catsby to check me.

**Comment by dwradcliffe** [comment]
Ah, I think you're right.

**Comment by catsby** [comment]
@phinze is correct in that we're effectively making it default `false` :cry: 

Is this pull request because you believe it should be defaulting to `false`, or because you observed it defaulting to `false`? I suspect the latter. I think the _correct_ way would be to make it behave like it is documented, and fix the bug where we're mistakenly sending `false`. Agree?

**Comment by phinze** [comment]
@catsby definitely agree. TF behavior should not modify the AWS default. so i think we close this and fix the bug.

**Comment by dwradcliffe** [comment]
I observed that the docs did not match the behavior. This PR should be replaced by one that fixes the real problem.

**Comment by catsby** [comment]
will do, thanks @dwradcliffe !

**Pull request closed without merging**
