### PR TITLE
Support TF_LOG=json

### PR DESCRIPTION
**Pull request by paddycarver**
Add support for TF_LOG=json, which logs at the TRACE level but outputs
the contents in their JSON encoding.

This makes logs parsable after the fact.

### CODE REVIEW

**Comment by apparentlymart** [comment]
Hi @paddycarver! Thanks for working on this.

I understand from context elsewhere (such as in hashicorp/terraform-plugin-sdk#695) that one key motivation for this is that the provider bug report template would ask users to share their logs in this format and then the provider developers reading those logs would, I suppose, use something like `jq` to narrow down the data in there to show only what they are interested in.

That use-case makes sense to me, but I have some concerns about how broad a solution this is an thus what other implications it might have. In particular, this suddenly makes everything that any component of Terraform prints as log output a de-facto machine-readable public interface. However, all of the logs Terraform Core currently emits are implementation details subject to arbitrary changes in future releases, and so anyone depending on them would risk being broken on upgrades.

With that said, I think it'd be important for us to be clear in documentation somewhere what subset of the JSON output this produces is something external software can rely on, with everything else being subject to change at any time, even in patch releases. You'll have a better sense than I do what characteristics of the output will be important to remain unchanged, but as an example of what I mean here are some examples of behaviors I could imagine us documenting as contract:
* The log output will consist of a series of JSON objects, each serialized with no inner newlines, with a newline separating each one.
* Each JSON object will contain the following properties:
  * `@level`: a keyword from a fixed set defining the log level
  * `@timestamp`: RFC 3339 timestamp when the log event was emitted, always in UTC timezone ("Z" suffix)
  * `@message`: An opaque, human-oriented string describing what happened. The contents are arbitrary and not machine-readable.
* JSON objects _may_ contain other properties, but none of them are a public interface and are subject to change at any time even in patch releases of Terraform CLI and of individual providers.

The above doesn't mean to (and cannot) forbid using other characteristics of the output on an ad-hoc basis, such as doing filtering of _one particular log file_ using custom `jq` queries as part of debugging an issue, but I'd like to draw a line between that and the idea of implementing long-lived integrations in external software for purposes like policy enforcement, custom progress UI, etc. Those deeper integrations can use the small subset we've defined as contractual, but if they depend on anything else then they should expect to vary their implementation for each patch release of CLI/providers.

Does the above align with your goals here? If so, would you mind adding a documentation page somewhere to capture some information of a form similar to what I showed above, and link to that from the documentation of the `TF_LOG` environment variable? It'd also be nice to link from that page to the other machine-readable integration points we have, such as [JSON Output Formats](https://www.terraform.io/docs/internals/json-format.html), which are likely to be a better solution for anyone wanting to build a long-lived integration. We don't really have a great category to put this sort of thing in, but at least this feels a lot more at home in [the "Internals" section](https://www.terraform.io/docs/internals/) than many of the other things we've dumped in there in the past, and so that'd be my starting suggestion for where to put it.

**Comment by apparentlymart** [comment]
Poking a little more, I just noticed we have this page [Debugging Terraform](https://www.terraform.io/docs/internals/debugging.html) which seems like it could be a potential home for some information on the JSON log format, as an alternative to creating an entirely new page for it.

**Comment by paddycarver** [comment]
So a few things.

First, apologies, it didn't occur to me exactly how useless that PR description was for conveying intent until just now. Sorry about that. :( This is why I shouldn't try and do too many things at once. :D 

Second, I want to try and convey some of that intent now. You are correct that this is related to hashicorp/terraform-plugin-sdk#695, though it's not a prerequisite of that work. My thought process is that we can ship that work without this being merged, but having this merged or approved first conveys benefits. The first one being that we're sure what we're shipping is in alignment with Core and that its design doesn't need to be modified/assumptions don't need to be rethought in the face of previously unconsidered requirements. That's why I wanted to open a PR prior to the feedback period on that ending. The second one being that for provider developers to be able to specify `TF_LOG=JSON` in their issue templates, for example, their users need to be on a version of Terraform that supports that. So the earlier this gets in, the more quickly it will become useful, because more users can be counted on to be using a version of Terraform that supports it.

Third, I want to address the very valid issue of compatibility guarantees, real or imagined. I think this is a really good point, and one I hadn't properly grappled with. I think my _assumption_ was that we wouldn't make any support guarantees around this at all except that JSON was a valid log level that would output structured logs at a TRACE level. This would make it hard for provider developers to use `jq` or custom tooling to parse logs, but that wasn't really the intended user experience. The SDK team intended to ship a CLI binary that would include parsing and filtering these log files, and I was imagining that as our "supported" interface, with the SDK and Core teams working together to ensure that continues to work. Even then, though, we'd probably want something--say, an initial line logged that indicated the version of Terraform or a log output version--to make those efforts work in a reasonable manner, though I'm struggling to see how that would work with core _and_ providers logging and potentially using two different log "formats". Perhaps just guaranteeing a subset of the JSON exists, as you did, and we just don't get to break those guarantees ever is the way to go. I think my knee-jerk reaction though is that we document it as making no compatibility guarantees and discourage the development of tooling around it, prove it out for a bit with our one consumer, and make sure we're happy with the results before making promises about it that we encourage the wider community to rely on. That may just be my conservative approach to interfaces, though.

I'm open to everything you suggested happening and doing it exactly as you said, honestly, I just wanted to flesh out some context on this and offer an alternative approach in case you found it more attractive. If we want to do anything about versioning or initial log line printing, I imagine that will take _some_ more invasive work, but it shouldn't take _too much_ more work, I'd imagine?

**Comment by apparentlymart** [comment]
I'd be comfortable with whatever level of guarantees or non-guarantees you feel ready to be constrained by (for future updates) here, as long as it doesn't include any guarantees about log objects that Terraform Core might happen to generate.

Some documentation saying that it's not for external use at all and linking to the tool you mentioned as the only supported way to consume it would also be a fine way to go as far as I'm concerned; I mainly just want to _not_ leave it completely implied and thus risk creating the _assumption_ of a supported interface where we aren't intending to maintain one.

**Comment by paddycarver** [comment]
@apparentlymart does that commit resolve your concerns?

**Review by apparentlymart — APPROVED** [review]
This looks good to me! I'm going to merge it now and also mark it for backport into the 0.15 branch so it can be included in the forthcoming beta2 release.

**Pull request merged**
