### PR TITLE
provider/openstack: 409 Response on Member Create

### LINKED ISSUE #10852: Terraform fails when Neutron is in a PENDING_UPDATE state
Environment:
```
Terraform v0.8.0
go version go1.6.2 darwin/amd64
```

```openstack_lb_member_v2```

main.tf
```
provider "openstack" {
  auth_url    = "${var.region != "dev" ? var.auth_url["prod_url"] : var.auth_url["dev_url"]}"
  domain_name = "${var.region != "dev" ? var.domain_name["prod_domain"] : var.domain_name["dev_domain"]}"
  tenant_name = "bnet-classic"
  insecure    = "true"
}

data "template_file" "userdata" {
  template = "$${file("${path.module}/userdata.tpl")}"

  vars {
    role = "${var.role}"
  }
}

resource "openstack_compute_instance_v2" "instance" {
  region          = "${var.region}"
  count           = "${var.instance_count["${var.role}"]}"
  name            = "${format("%s-cg-ncs-%s%02d", "${var.region_prefix}", "${var.role}", count.index + 1)}"
  image_id        = "${var.region != "dev" ? var.image_id["prod_image"] : var.image_id["dev_image"]}"
  flavor_name     = "${var.region != "dev" ? var.flavor_name["prod_flavor"] : var.flavor_name["dev_flavor"]}"
  security_groups = ["default"]

  network = {
    name = "${var.role != "gateway" ? var.network_name["internal"] : var.network_name["floating"]}"
  }

  security_groups = ["default"]
  user_data       = "${data.template_file.userdata.rendered}"
}

output "contents" {
  value = "${data.template_file.userdata.rendered}"
}

resource "openstack_lb_member_v2" "member" {
  depends_on     = ["openstack_compute_instance_v2.instance"]
  count          = "${var.load_balancer_count["${var.role}"]}"
  subnet_id      = "${var.vip_subnet_id}"
  pool_id        = "${var.pool_id}"
  protocol_port  = "${var.protocol_port["${var.role}"]}"
  admin_state_up = "true"
  region         = "${var.region}"
  address        = "${element(openstack_compute_instance_v2.instance.*.access_ip_v4, count.index)}"
}
```

variables.tf
```
variable "auth_url" {
  type = "map"

  default = {
    dev_url   = "https://dev.keystone.xxx.net:5000/v3"
    prod_url = "https://keystone.xxx.net:5000/v3"
  }
}

variable "domain_name" {
  type = "map"

  default = {
    dev_domain  = "development"
    prod_domain = "production"
  }
}

variable "tenant_name" {
  default = "classic"
}

variable "role" {
  default       =  "datastore"
  description = "Instance role"
}

variable "region" {
  default = "dev"
  description = "Tenant region"
}

variable "region_prefix" {
  default = "dev81b"
  description = "Site name"
}

variable "image" {
  default = "centos7.2-latest"
}

variable "flavor_name" {
  type = "map"

  default = {
    dev_flavor  = "t2.medium"
    prod_flavor = "m4.large"
  }
}

variable "instance_count" {
  default = "1"
  description = "Number of instances"
}

variable "network_name" {
  default = "classic-internal-net"
}
```

Error:
```
* openstack_lb_member_v2.member.2: Error creating OpenStack LBaaSV2 member: Expected HTTP response code [201 202] when accessing [POST http://dev.neutron.cloud.xxx:9696/v2.0/lbaas/pools/d90a6b80-92ea-4478-9576-16dcc70b8511/members], but got 409 instead
{"NeutronError": {"message": "Invalid state PENDING_UPDATE of loadbalancer resource 50748818-e2f6-4306-b20a-0cdcecf79565", "type": "StateInvalid", "detail": ""}}
```

Neutron will lock a resource into one of many PENDING_* states to avoid concurrent changes, which typically is not a problem, but there are edge cases where a load balancer will briefly be in a "PENDING_UPDATE" state, which causes the deployment to fail. Since the resource is technically available Terraform should attempt to recreate the resource rather than failing. This makes large scale deployments extremely difficult as there is no way to throttle how many resources are created at a given time, nor does Terraform provide the ability to add an arbitrary wait during resource creation.

### PR DESCRIPTION
**Pull request by jtopjian**
This commit accounts for a 409 response when a LBaaS v2 member is
being created. Rather than error out, this should be considered a
pending state.

Fixes #10852

### CODE REVIEW

**Comment by jtopjian** [comment]
@mrantipyrine I _think_ this should fix the problem. It's really hard for me to recreate the situation where this would happen, so I'm flying a little blind. Are you able to build from source with this patch and confirm? Let me know if you'd need some help.

**Comment by mrantipyrine** [comment]
```Terraform v0.8.2-dev (93f600dbf765bc979813460260abf99bcb8f58a3+CHANGES)```

So far so good but I made one change```return member, "PENDING_CREATE", nil``` to ```return member, "PENDING_UPDATE", nil```. 

Prior to this change I was still seeing this still frequently:
```
* openstack_lb_member_v2.member.2: Error creating OpenStack LBaaSV2 member: Expected HTTP response code [201 202] when accessing [POST http://dev.neutron.cloud.net:9696/v2.0/lbaas/pools/d90a6b80-92ea-4478-9576-16dcc70b8511/members], but got 409 instead
{"NeutronError": {"message": "Invalid state PENDING_UPDATE of loadbalancer resource 50748818-e2f6-4306-b20a-0cdcecf79565", "type": "StateInvalid", "detail": ""}}
```

I'll do more testing in the morning.

**Comment by jtopjian** [comment]
Ah, if you want to change `PENDING_CREATE` to `PENDING_UPDATE`, you'll need to add it to the `StateChangeConf` as you did [here](https://github.com/hashicorp/terraform/issues/10852#issuecomment-268326541).

I recommend just leaving the `PENDING_CREATE` status untouched. It's a bit confusing, but this resource is completely ignoring the status that the member is returning. There's a semi-good reason for that, related to how 409s are handled in general at the moment, and it'll eventually be fixed down the road.

**Comment by mrantipyrine** [comment]
The problem still seems to be happening when the number of lb_members in a particular pool is > 4; anything <= 4 is working works without issue. 

```* openstack_lb_member_v2.member.1: Error creating OpenStack LBaaSV2 member: Expected HTTP response code [201 202] when accessing [POST http://dev.neutron.cloud.net:9696/v2.0/lbaas/pools/d90a6b80-92ea-4478-9576-16dcc70b8511/members], but got 409 instead
{"NeutronError": {"message": "Invalid state PENDING_UPDATE of loadbalancer resource 50748818-e2f6-4306-b20a-0cdcecf79565", "type": "StateInvalid", "detail": ""}}```

And no need to thank me for testing :)

**Comment by jtopjian** [comment]
hm... I wonder if that error is being triggered somewhere else. Can you post the debug output to a gist?

**Comment by mrantipyrine** [comment]
https://gist.github.com/mrantipyrine/a0a9c37be63b37dcf0cd05b5516f91c7

**Comment by mrantipyrine** [comment]
Thanks for looking into this so quickly :)

**Comment by jtopjian** [comment]
No problem at all. 

The gist helped a lot -- the error is being triggered [here](https://github.com/hashicorp/terraform/blob/master/builtin/providers/openstack/resource_openstack_lb_member_v2.go#L120) and not in the `StateChangeConf` section, which makes sense.

I just pushed a new commit that I think catches the 409 in the right spot. This is the first time I've used the `resource.Retry` feature, so let's see how it works. :)

**Comment by mrantipyrine** [comment]
So far it looks to be working! I'm going to run 20-30 more build/destroys to see if the error pops up again.

**Comment by mrantipyrine** [comment]
I left a loop running overnight and came in to see the problem still occurring but it appears with less frequency

``` openstack_lb_member_v2.member.3: Error creating OpenStack LBaaSV2 member: Expected HTTP response code [201 202] when accessing [POST http://dev.neutron.cloud.net:9696/v2.0/lbaas/pools/d90a6b80-92ea-4478-9576-16dcc70b8511/members], but got 409 instead
{"NeutronError": {"message": "Invalid state PENDING_UPDATE of loadbalancer resource 50748818-e2f6-4306-b20a-0cdcecf79565", "type": "StateInvalid", "detail": ""}}
* openstack_lb_member_v2.member.0: Error creating OpenStack LBaaSV2 member: Expected HTTP response code [201 202] when accessing [POST http://dev.neutron.cloud.net:9696/v2.0/lbaas/pools/c16af7f9-e9dc-4428-8dd1-8d766f399b6b/members], but got 409 instead```

Additionally I am also seeing timeouts errors that I was not seeing before but this most certainly on my end 
```
* openstack_lb_member_v2.member.2: Error creating OpenStack LBaaSV2 member: Expected HTTP response code [201 202] when accessing [POST http://dev.neutron.cloud.net:9696/v2.0/lbaas/pools/d90a6b80-92ea-4478-9576-16dcc70b8511/members], but got 504 instead
<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
```

**Comment by jtopjian** [comment]
I wonder if the error is happening after 2 minutes of trying. If you'd like to do some more testing, maybe increase the time to 10 minutes and let it run for a while. Unfortunately it's not possible to dynamically specify a timeout -- it has to be hard-coded.

**Comment by mrantipyrine** [comment]
I've been running with a 5 minute timeout on a constant loop for the last 5 hours and have not seen the error since. It think it's safe to say this fixed the issue. 

The one thing I forgot to mention is that older version of Neutron will return a 500 when in a ```PENDING_UPDATE``` state so this fix will not work. This is the patch that fixed said problem
https://review.openstack.org/gitweb?p=openstack/neutron-lbaas.git;a=commitdiff;h=3cf4a7cffd5f76b9f8a3eed649d04075714dcd9c

**Comment by jtopjian** [comment]
That's great news! I just pushed a final commit that should be good to go. If you'd like to give it one last shot, I'd really appreciate it.

**Comment by mrantipyrine** [comment]
I have the new changes built and will start testing in the next hour or so.  :)

**Comment by mrantipyrine** [comment]
I've done 40+ builds/destroys and not a single one failed because of the PENDING state. I think we're good.

**Comment by jtopjian** [comment]
That's awesome news! Thank you very much for your help with this.

**Pull request merged**
