### PR TITLE
Not Error out on AWS Lambda VPC config if both subnet_ids and security_group_ids are empty.

### PR DESCRIPTION
**Pull request by srikalyan**
AWS Lambda VPC config is an optional configuration and which needs both subnet_ids and
security_group_ids to tie the lambda function to a VPC. We should make it optional if
both subnet_ids and security_group_ids are not set which would add better flexiblity in
creation of more useful modules as there are no way add "if else" logic in modules. Without this we are creating duplicate modules one with VPC and one without VPC resulting in various anomalies.

### CODE REVIEW

**Comment by srikalyan** [comment]
Any update on how long would it take to fix this?

**Comment by srikalyan** [comment]
Guys are you planning to merge this PR?

**Comment by srikalyan** [comment]
Guys are you planning to merge this anytime soon?

**Comment by srikalyan** [comment]
Guys are you planning to merge this anytime soon?

**Comment by radeksimko** [comment]
Hi @srikalyan 
removing an empty `vpc_config` block, i.e. changing

```hcl
resource "aws_lambda_function" "test_lambda" {
...
    vpc_config {
        subnet_ids = []
        security_group_ids = []
    }
}
```
to
```hcl
resource "aws_lambda_function" "test_lambda" {
...
}
```
would still produce a non-empty plan, specifically recreation of the Lambda function. It should probably be noop (which I think can be achieved via `StateFunc`) but it's an edge case that is rare enough that I'm happy to ignore it.

All Lambda acceptance test are passing:

```sh
$ make testacc TEST=./builtin/providers/aws TESTARGS='-run=AWSLambdaFunction'
```
```
TF_ACC=1 go test ./builtin/providers/aws -v -run=AWSLambdaFunction -timeout 120m
=== RUN   TestAccAWSLambdaFunction_importLocalFile
--- PASS: TestAccAWSLambdaFunction_importLocalFile (35.15s)
=== RUN   TestAccAWSLambdaFunction_importLocalFile_VPC
--- PASS: TestAccAWSLambdaFunction_importLocalFile_VPC (39.41s)
=== RUN   TestAccAWSLambdaFunction_importS3
--- PASS: TestAccAWSLambdaFunction_importS3 (43.83s)
=== RUN   TestAccAWSLambdaFunction_basic
--- PASS: TestAccAWSLambdaFunction_basic (35.11s)
=== RUN   TestAccAWSLambdaFunction_VPC
--- PASS: TestAccAWSLambdaFunction_VPC (38.85s)
=== RUN   TestAccAWSLambdaFunction_s3
--- PASS: TestAccAWSLambdaFunction_s3 (45.09s)
=== RUN   TestAccAWSLambdaFunction_localUpdate
--- PASS: TestAccAWSLambdaFunction_localUpdate (36.78s)
=== RUN   TestAccAWSLambdaFunction_localUpdate_nameOnly
--- PASS: TestAccAWSLambdaFunction_localUpdate_nameOnly (32.30s)
=== RUN   TestAccAWSLambdaFunction_s3Update
--- PASS: TestAccAWSLambdaFunction_s3Update (91.86s)
PASS
ok     	github.com/hashicorp/terraform/builtin/providers/aws   	398.410s
```

Sorry for the long delay in reviewing this.

**Pull request merged**
