### PR TITLE
aws: Adding in additional retry logic due to latency with delete of db_option_group

### LINKED ISSUE #7311: Intermittent aws_db_instance & aws_db_option_group lifecycle issues
We are seeing fairly regular issues deleting `aws_db_option_group` when removing the `aws_db_instance` first in the same destroy path. 

Looking at the debug logs, the issue is that while the DB instance is non-existent per the `Request rds/DescribeDBInstances` returning 404 however upon initial `rds/DeleteOptionGroup` request there is a 400 error thrown for `InvalidOptionGroupStateFault` due to `The option group 'dev-data-primary-justin-option-group' cannot be deleted because it is in use.`

### Terraform Version
0.6.16+

### Affected Resource(s)
- aws_db_option_group

### Debug Output
```
* aws_db_option_group.xmldb: Error Deleting DB Option Group: InvalidOptionGroupStateFault: The option group 'dev-data-primary-option-group' cannot be deleted because it is in use.
 	status code: 400, request id: d732f0b9-37a5-11e6-a48d-af638ac63cab
```

### Expected Behavior
DB Option group deletes properly seeing that AWS DB Instance had been deleted

### Actual Behavior
AWS exception stating that DB Option Group is still in use and fails deletion (intermittently but primarily with Oracle RDS instances)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform destroy`

### Important Factoids
I have been unable to replicate this yet with smaller MySQL instances however can consistently reproduce with the Oracle 11-ee instance we have based off a larger snapshot.

### PR DESCRIPTION
**Pull request by jrnt30**
Fixes #7311

### CODE REVIEW

**Comment by jen20** [comment]
Hi @jrnt30! Thanks for opening a pull request - it looks good to me. However, are we sure that a 1 minute retry window is sufficient here?

**Comment by jen20** [comment]
In light of the issue and the passing acceptance test I'll merge this now and we can increase the time out in future if necessary.

**Comment by jrnt30** [comment]
That is a fair point. It seems in general the timeouts are somewhat conservative on a few other resources as well but it would probably be more robust to simply increase it.  

I'll monitor it over the next few days

**Comment by catsby** [comment]
Hey Friends –

This looks good to me. I ran the tests as well:

```
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSDBOptionGroup -timeout 120m
=== RUN   TestAccAWSDBOptionGroup_basic
--- PASS: TestAccAWSDBOptionGroup_basic (19.33s)
=== RUN   TestAccAWSDBOptionGroup_basicDestroyWithInstance
--- PASS: TestAccAWSDBOptionGroup_basicDestroyWithInstance (551.74s)
=== RUN   TestAccAWSDBOptionGroup_OptionSettings
--- PASS: TestAccAWSDBOptionGroup_OptionSettings (38.34s)
=== RUN   TestAccAWSDBOptionGroup_sqlServerOptionsUpdate
--- PASS: TestAccAWSDBOptionGroup_sqlServerOptionsUpdate (38.27s)
=== RUN   TestAccAWSDBOptionGroup_multipleOptions
--- PASS: TestAccAWSDBOptionGroup_multipleOptions (19.61s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	667.299s
Test:
```

Fwiw I've not seen this error, and we do have an existing DB Instance test that uses a db option group and I've not seen it, so I'm fine with just a 1 minute retry.

Thanks!

**Pull request merged**
