### PR TITLE
Librato Alerts fixes

### PR DESCRIPTION
**Pull request by elblivion**
This PR:

- Fixes an error whereby updating an Alert times out due to the change not being properly taken into account, which we've run into several times already.
- Applies a series of improvements to the and very likely bug fixes inspired by https://github.com/hashicorp/terraform/pull/14562

### CODE REVIEW

**Comment by elblivion** [comment]
```
$ make testacc TEST=./builtin/providers/librato TESTARGS='-run=TestAccLibratoAlert'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/06/06 15:31:10 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/librato -v -run=TestAccLibratoAlert -timeout 120m
=== RUN   TestAccLibratoAlert_Minimal
--- PASS: TestAccLibratoAlert_Minimal (3.46s)
=== RUN   TestAccLibratoAlert_Basic
--- PASS: TestAccLibratoAlert_Basic (2.67s)
=== RUN   TestAccLibratoAlert_Full
--- PASS: TestAccLibratoAlert_Full (4.71s)
=== RUN   TestAccLibratoAlert_Updated
--- PASS: TestAccLibratoAlert_Updated (13.28s)
=== RUN   TestAccLibratoAlert_Rename
--- PASS: TestAccLibratoAlert_Rename (13.92s)
=== RUN   TestAccLibratoAlert_FullUpdate
--- PASS: TestAccLibratoAlert_FullUpdate (4.54s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/librato	42.590s
```

**Comment by elblivion** [comment]
I'm also preparing a PR to add support for alerting on tagged metrics, should I roll both into one?

**Comment by stack72** [comment]
@elblivion thanks for the PR - can you open a separate PR - that way we can merge them separately

Thanks

P.

**Comment by stack72** [comment]
LGTM! thanks for this

```
% make testacc TEST=./builtin/providers/librato
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/06/06 19:26:30 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/librato -v  -timeout 120m
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccLibratoAlert_Minimal
--- PASS: TestAccLibratoAlert_Minimal (1.72s)
=== RUN   TestAccLibratoAlert_Basic
--- PASS: TestAccLibratoAlert_Basic (1.24s)
=== RUN   TestAccLibratoAlert_Full
--- PASS: TestAccLibratoAlert_Full (2.73s)
=== RUN   TestAccLibratoAlert_Updated
--- PASS: TestAccLibratoAlert_Updated (10.61s)
=== RUN   TestAccLibratoAlert_Rename
--- PASS: TestAccLibratoAlert_Rename (10.63s)
=== RUN   TestAccLibratoAlert_FullUpdate
--- PASS: TestAccLibratoAlert_FullUpdate (2.75s)
=== RUN   TestAccLibratoMetrics
--- PASS: TestAccLibratoMetrics (46.78s)
=== RUN   TestAccLibratoService_Basic
--- PASS: TestAccLibratoService_Basic (1.74s)
=== RUN   TestAccLibratoService_Updated
--- PASS: TestAccLibratoService_Updated (11.28s)
=== RUN   TestAccLibratoSpaceChart_Basic
--- PASS: TestAccLibratoSpaceChart_Basic (1.90s)
=== RUN   TestAccLibratoSpaceChart_Full
--- PASS: TestAccLibratoSpaceChart_Full (1.95s)
=== RUN   TestAccLibratoSpaceChart_Updated
--- PASS: TestAccLibratoSpaceChart_Updated (11.66s)
=== RUN   TestAccLibratoSpace_Basic
--- PASS: TestAccLibratoSpace_Basic (1.08s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/librato	106.093s
```

**Pull request merged**
