### PR TITLE
helper/schema: Add TypeFloat

### LINKED ISSUE #594: There is no TypeFloat
I need this to implement failoverRatio https://cloud.google.com/compute/docs/reference/latest/targetPools

There are bound to be other cases as well

### PR DESCRIPTION
**Pull request by mitchellh**
Fixes #594 

Self explanatory...

### CODE REVIEW

**Comment by mitchellh** [comment]
Note how much easier this was with the refactor #764

**Comment by phinze** [comment]
I am probably missing something silly here, but don't we also need handle the new `TypeFloat` down in the `switch schema.Type` in `func (m schemaMap) diff` as well?

For example, if I add this test case to `TestSchemaMap_Diff`

```go
		// #46 - Float
		{
			Schema: map[string]*Schema{
				"some_threshold": &Schema{
					Type: TypeFloat,
				},
			},

			State: &terraform.InstanceState{
				Attributes: map[string]string{
					"some_threshold": "567.8",
				},
			},

			Config: map[string]interface{}{
				"some_threshold": 12.34,
			},

			Diff: &terraform.InstanceDiff{
				Attributes: map[string]*terraform.ResourceAttrDiff{
					"port": &terraform.ResourceAttrDiff{
						Old: "567.8",
						New: "12.34",
					},
				},
			},

			Err: false,
		},
```

...it fails with:

```
schema_test.go:1842: #46 err: some_threshold: unknown type 3
```

**Comment by mitchellh** [comment]
@phinze Ah! You're right, I forgot that diffs (and validation) aren't unified into the new FieldReader stuff yet. :cry: Do you want to PR that test for me and I'll fix it?

**Comment by phinze** [comment]
:+1: :point_up_2: :gift:

**Pull request merged**
