### PR TITLE
[WIP] Create InputGraphBuilder

### PR DESCRIPTION
**Pull request by jbardin**
Don't handle module variables at all during the Input operation. Because Input happens before Refresh, module variable interpolation can fail when referencing values that aren't yet in the state, but are expected after Refresh. 

This creates a new `InputGraphBuilder`, which strips out all the unneeded pieces transformations inherited form the `PlanGraphBuilder`, most importantly the `ModuleVariableTransformer`.  This also removes the state entirely from the Input phase. Because Input happens before Refresh, but possibly depended on the state that will be refreshed, it is simpler to reason about if we don't allow the Input phase to depend on the state at all.

### CODE REVIEW

**Comment by jbardin** [comment]
@apparentlymart: rewrote this to use a new graph builder, rather than layers more conditionals on the already overloaded Plan graph.

**Comment by catsby** [comment]
Hey @jbardin is this still `WIP`?

**Comment by jbardin** [comment]
@catsby, yes, this is still a WIP, thanks!

**Comment by jbardin** [comment]
OK, dropping this in favor of my previous method of parameterizing the graph builder to use an interpolation eval node that doesn't cause fatal errors.  Because we need to call Input in the providers, and the providers may be parameterized in modules via variables, we simply have to process module variables in the Graph.

**Pull request closed without merging**
