### PR TITLE
providers/google: support optionial uuid naming for Instance Template

### PR DESCRIPTION
**Pull request by evandbrown**
Auto-generating an Instance Template name (or just its suffix) allows the
create_before_destroy lifecycle option to function correctly on the
Instance Template resource. This in turn allows Instance Group Managers
to be updated without being destroyed.

Addresses #6234

### CODE REVIEW

**Comment by phinze** [comment]
Nice! Can you attach test output from all the acctests for this resource? `-run ^TestAccInstanceGroupManager`

Code and docs look solid. 👍

**Comment by billf** [comment]
This is a good middle ground for allowing modifications of templates without destroying IGMs.
You can achieve something similar with the `uuid()` interpolation function and ignoring the name attribute, but then you have to format the `uuid()` output each time and it gets ugly quick.

**Comment by evandbrown** [comment]
@phinze yep!

```
$ make testacc TEST=./builtin/providers/google GOOGLE_PROJECT=evandbrown17 GOOGLE_REGION=us-central1 TESTARGS='-run=TestAccInstanceGroupManager'
==> Checking that code complies with gofmt requirements...
/home/evanbrown/dev/golang/bin/stringer
go generate $(go list ./... | grep -v /vendor/)
2016/05/10 15:54:48 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/google -v -run=TestAccInstanceGroupManager -timeout 120m
=== RUN   TestAccInstanceGroupManager_basic
--- PASS: TestAccInstanceGroupManager_basic (233.67s)
=== RUN   TestAccInstanceGroupManager_update
--- PASS: TestAccInstanceGroupManager_update (198.31s)
=== RUN   TestAccInstanceGroupManager_updateLifecycle
--- PASS: TestAccInstanceGroupManager_updateLifecycle (143.55s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/google 575.639s
```

**Comment by phinze** [comment]
LGTM

**Pull request merged**
