### PR TITLE
GCE - google cloud storage backend for remote state

### PR DESCRIPTION
**Pull request by sl1pm4t**
Adds Google Cloud Storage support for remote state. 
Operation very similar to S3.

### CODE REVIEW

**Comment by thomasbibb** [comment]
This feature would be very helpful!  Do you have an update on when it may be merged?

**Comment by stack72** [comment]
@sl1pm4t please can you rebase your PR - we will have a look at it then :)

**Comment by stack72** [comment]
Just a FYI, I am going to manually merge this as long as it is ok with one of the other core team members

**Comment by sl1pm4t** [comment]
Sorry @stack72  - I started rebasing this, but it wasn't straight forward for some reason ( I forget why exactly ), I got about 80% through a rework and then my real job got in the way (lots of travel).

**Comment by sl1pm4t** [comment]
@stack72  - in case you need it the incomplete rebase / rework is available [here](https://github.com/sl1pm4t/terraform/commit/64269990ec407a6a1a18c59d24f97263bb8ce58c)

Docs were copied from AWS S3 remote state docs, and still need to be updated for GCS.

**Comment by stack72** [comment]
Hi @sl1pm4t 

thanks for shouting back, I have managed to rebase (locally) and wrote up the changes to the docs as follows:

```
---
layout: "remotestate"
page_title: "Remote State Backend: gcs"
sidebar_current: "docs-state-remote-gcs"
description: |-
  Terraform can store the state remotely, making it easier to version and work with in a team.
---

# gcs

Stores the state at a given patch in a given bucket on [Google Storage bucket](https://cloud.google.com/storage/docs/overview).

-> **Note:** Passing credentials directly via config options will
make them included in cleartext inside the persisted state.
Use of environment variables or config file is recommended.

## Example Usage

```
terraform remote config \
	-backend=gcs \
	-backend-config="bucket=terraform-state-prod" \
	-backend-config="path=testState" \
	-backend-config="project=myproject"
```

## Example Referencing

```
resource "terraform_remote_state" "foo" {
	backend = "gcs"
	config {
		bucket = "terraform-state-prod"
		path = "testState"
		project = "myproject"
	}
}
```

## Configuration variables

The following configuration options / environment variables are supported:

 * `bucket` - (Required) The name of the Google Cloud Storage bucket.
 * `path` - (Required) The path within the bucket to store the statefile
 * `project` - (Required) A valid API project identifier.

```

Please let me know any chances that are needed :)

**Comment by stack72** [comment]
Hi @sl1pm4t 

When i try and build this, I get the following errors:

```
make
==> Checking that code complies with gofmt requirements...
/Users/stacko/Code/go/bin/stringer
go generate $(go list ./... | grep -v /vendor/)
TF_ACC= go test $(go list ./... | grep -v /vendor/)  -timeout=30s -parallel=4
# google.golang.org/grpc/transport
../../../google.golang.org/grpc/transport/handler_server.go:203: undefined: http2.TrailerPrefix
../../../google.golang.org/grpc/transport/http2_client.go:678: undefined: http2.MetaHeadersFrame
../../../google.golang.org/grpc/transport/http2_client.go:774: undefined: http2.MetaHeadersFrame
../../../google.golang.org/grpc/transport/http2_server.go:140: undefined: http2.MetaHeadersFrame
../../../google.golang.org/grpc/transport/http2_server.go:253: undefined: http2.MetaHeadersFrame
../../../google.golang.org/grpc/transport/http_util.go:279: f.fr.ReadMetaHeaders undefined (type *http2.Framer has no field or method ReadMetaHeaders)
```

Any thoughts?

**Comment by sl1pm4t** [comment]
@stack72 - I'm not sure sorry. I'm able to build without error?!
Could you give me more detail about what branches your building etc?

**Comment by thomasbibb** [comment]
Hi,  Any progress on this?

**Comment by daodennis** [comment]
Is the only thing left to do here is rebase, build, and do some smoke testing of this feature @stack72 ?

**Comment by sl1pm4t** [comment]
I've submitted a new PR #6814 with the GCS remote state rebased on master.

**Pull request closed without merging**
