### PR TITLE
provider/cloudstack: Added loadbalancer support to the provider

### PR DESCRIPTION
**Pull request by jeroendekorte**
Added load balancer feature to the Cloudstack provider to be able to add a loadbalancer resource to your configuration and load balance your instances from a public IP.

### CODE REVIEW

**Comment by svanharmelen** [comment]
LGTM! Thanks for the work!

**Comment by glenjamin** [comment]
Is it too late to point out that although the underlying API for this is similar to `cloudstack_port_forward`, the terraform APIs differ?

`cloudstack_port_forward` creates a resource for a public IP, and allows it to be flagged as `managed`, and then groups forwards within the resource.

`cloudstack_loadbalancer_rule` creates a resource per port mapping, and has no equivalent of `managed`.

**Comment by svanharmelen** [comment]
@glenjamin nope, it's never too late to improve or fix something :wink:

As for this specific one, the `managed` flag is not related to the ability to group forwards or rules. The `managed` flag is a special flag that tells the resource that **only** the forwards or rules created by this resource should exists and all other forwards or rules should be removed. This is especially helpful with firewall rules as it enables you to have a single source of truth.

Currently the flag is not implemented for load balancer rules, but of course it can be added if someone has a need for it. The same goes for the ability to add multiple load balancer rules with a single load balancer resource. The author of the currently available resource didn't have that need, so didn't think about making it that way. But of course we can add/change it if needed.

**Comment by glenjamin** [comment]
How easy would it be to maintain backwards-compatibility if multiple rules were added? Is it worth changing this before a release so a future breaking-change isn't required, even if at present only one sub-resource at a time is supported?

**Comment by svanharmelen** [comment]
Must say I also thought about that just after pressing the `Comment` button... As long as this is not in a release, it's indeed a lot easier to refactor this.

@phinze any insights about when a new release is due? Would be nice to have a (rough) indication so we can think about this one before a new release is cut.

**Comment by phinze** [comment]
@svanharmelen If I had to guess at a rough timespan for the next release, I'd say > 1 week, < 6 weeks. Does that help?

**Comment by svanharmelen** [comment]
Kind of... :wink: thx!

**Pull request merged**
