### PR TITLE
Update alicloud provider, including resource and examples of alicloud provider

### PR DESCRIPTION
**Pull request by wangyuelucky**
Hi Terraform teams:
    This PR is based on #10761, almost 10 days without progress.
    We expect our provider to be merged as soon as possible.
    Any suggestions are appreciated.

Sincerely,
YueWang

### CODE REVIEW

**Comment by stack72** [comment]
Hi @wangyuelucky 

Does this superceed the need for #10761? Or is this a follow up to it?

Paul

**Comment by wangyuelucky** [comment]
Hi @stack72 ,
Thanks for your so quick response.
This PR is the latest version, so #10761 could be closed.

Do you have the schedule of merge this PR?

Thanks
YueWang

**Comment by stack72** [comment]
Hi @wangyuelucky 

Sorry for the delay here - each time a new PR is opened, it takes a lot more time to review - I cannot track what changes are being made so I need to start the review process again

I will try and start this PR again today

Paul

**Comment by wangyuelucky** [comment]
ok, follow your plan.
Any demand please mention to me. We will do our best to complete this.



Regards,
YueWang

**Comment by stack72** [comment]
Hi @wangyuelucky 

Thanks so much for all the work here - this PR is looking much more rock solid to adhering to how we write our providers :) The test results look as follows:

```
=== RUN   TestAccAlicloudSecurityGroupRule_Egress
--- PASS: TestAccAlicloudSecurityGroupRule_Egress (61.80s)
=== RUN   TestAccAlicloudSecurityGroupRule_Vpc_Ingress
--- PASS: TestAccAlicloudSecurityGroupRule_Vpc_Ingress (75.85s)
=== RUN   TestAccAlicloudSecurityGroup_basic
--- PASS: TestAccAlicloudSecurityGroup_basic (44.43s)
=== RUN   TestAccAlicloudSecurityGroup_withVpc
--- PASS: TestAccAlicloudSecurityGroup_withVpc (62.83s)
=== RUN   TestAccAlicloudSlbAttachment_basic
--- PASS: TestAccAlicloudSlbAttachment_basic (128.33s)
=== RUN   TestAccAlicloudSlb_basic
--- PASS: TestAccAlicloudSlb_basic (45.87s)
=== RUN   TestAccAlicloudSlb_traffic
--- PASS: TestAccAlicloudSlb_traffic (44.21s)
=== RUN   TestAccAlicloudSlb_listener
--- PASS: TestAccAlicloudSlb_listener (58.44s)
=== RUN   TestAccAlicloudSlb_vpc
--- PASS: TestAccAlicloudSlb_vpc (86.29s)
=== RUN   TestAccAlicloudVpc_basic
--- PASS: TestAccAlicloudVpc_basic (54.91s)
=== RUN   TestAccAlicloudVpc_update
--- PASS: TestAccAlicloudVpc_update (77.16s)
=== RUN   TestAccAlicloudRouteEntry_Basic
--- PASS: TestAccAlicloudRouteEntry_Basic (181.73s)
=== RUN   TestAccAlicloudVswitch_basic
--- PASS: TestAccAlicloudVswitch_basic (163.31s)
=== RUN   TestValidateInstancePort
--- PASS: TestValidateInstancePort (0.00s)
=== RUN   TestValidateInstanceProtocol
--- PASS: TestValidateInstanceProtocol (0.00s)
=== RUN   TestValidateInstanceDiskCategory
--- PASS: TestValidateInstanceDiskCategory (0.00s)
=== RUN   TestValidateInstanceName
--- PASS: TestValidateInstanceName (0.00s)
=== RUN   TestValidateInstanceDescription
--- PASS: TestValidateInstanceDescription (0.00s)
=== RUN   TestValidateSecurityGroupName
--- PASS: TestValidateSecurityGroupName (0.00s)
=== RUN   TestValidateSecurityGroupDescription
--- PASS: TestValidateSecurityGroupDescription (0.00s)
=== RUN   TestValidateSecurityRuleType
--- PASS: TestValidateSecurityRuleType (0.00s)
=== RUN   TestValidateSecurityRuleIpProtocol
--- PASS: TestValidateSecurityRuleIpProtocol (0.00s)
=== RUN   TestValidateSecurityRuleNicType
--- PASS: TestValidateSecurityRuleNicType (0.00s)
=== RUN   TestValidateSecurityRulePolicy
--- PASS: TestValidateSecurityRulePolicy (0.00s)
=== RUN   TestValidateSecurityRulePriority
--- PASS: TestValidateSecurityRulePriority (0.00s)
=== RUN   TestValidateCIDRNetworkAddress
--- PASS: TestValidateCIDRNetworkAddress (0.00s)
=== RUN   TestValidateRouteEntryNextHopType
--- PASS: TestValidateRouteEntryNextHopType (0.00s)
=== RUN   TestValidateSwitchCIDRNetworkAddress
--- PASS: TestValidateSwitchCIDRNetworkAddress (0.00s)
=== RUN   TestValidateIoOptimized
--- PASS: TestValidateIoOptimized (0.00s)
=== RUN   TestValidateInstanceNetworkType
--- PASS: TestValidateInstanceNetworkType (0.00s)
=== RUN   TestValidateInstanceChargeType
--- PASS: TestValidateInstanceChargeType (0.00s)
=== RUN   TestValidateInternetChargeType
--- PASS: TestValidateInternetChargeType (0.00s)
=== RUN   TestValidateInternetMaxBandWidthOut
--- PASS: TestValidateInternetMaxBandWidthOut (0.00s)
=== RUN   TestValidateSlbName
--- PASS: TestValidateSlbName (0.00s)
=== RUN   TestValidateSlbInternetChargeType
--- PASS: TestValidateSlbInternetChargeType (0.00s)
=== RUN   TestValidateSlbBandwidth
--- PASS: TestValidateSlbBandwidth (0.00s)
=== RUN   TestValidateSlbListenerBandwidth
--- PASS: TestValidateSlbListenerBandwidth (0.00s)
```

There are a lot of tests so I am just including this - thanks for this :)

Paul

**Comment by wangyuelucky** [comment]
@stack72  Thank you for your compliments, our pleasure be part of terraform.
Follow-up we will improve our provider, and provide more resources.

Thanks for your support!

YueWang

**Pull request merged**
