### PR TITLE
Add resources to CFN stack data source

### LINKED ISSUE #8949: Request: provider/aws: cloudformation_stack data source expose "resources"
Providing access to the "Resources" section of a CloudFormation stack would be helpful if what you need isn't provided as an output on the stack (particularly if you aren't able to modify the stack to add it).
### Use Case

We currently have several [convox](https://convox.com) environments running - each of which is a CloudFormation stack. We're managing non-convox resources with Terraform, including a new Bastion instances inside of an auto-scaling group. We need to specify the public subnets of the convox stack for our bastion module, and currently have to hardcode them after grabbing the IDs from the Cloudformation console page. Providing access to the subnet resources of the stack would allow us to do this programatically.

I'm sure there are plenty of other use cases, however that's the current problem I'd like to resolve.
### Affected Resource(s)
- aws_cloudformation_stack
### References
- #8640 
### Documentation
- [API](http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_ListStackResources.html)
- [Go SDK](http://docs.aws.amazon.com/sdk-for-go/api/service/cloudformation/#example_CloudFormation_ListStackResources)

### PR DESCRIPTION
**Pull request by mwarkentin**
Fixes #8949 - not tested yet.

### CODE REVIEW

**Comment by radeksimko** [comment]
Hi @mwarkentin 
it looks like the resources are wrapped in `cloudformation.StackResourceSummary` (available via `ListStackResources`) which is a type with >2 useful properties.

I'm assuming that a map can be useful here because you'd want to be able to address the resource via a key instead of iterating over those?

```go
type StackResourceSummary struct {
	_ struct{} `type:"structure"`

	// Time the status was updated.
	LastUpdatedTimestamp *time.Time `type:"timestamp" timestampFormat:"iso8601" required:"true"`

	// The logical name of the resource specified in the template.
	LogicalResourceId *string `type:"string" required:"true"`

	// The name or unique identifier that corresponds to a physical instance ID
	// of the resource.
	PhysicalResourceId *string `type:"string"`

	// Current status of the resource.
	ResourceStatus *string `type:"string" required:"true" enum:"ResourceStatus"`

	// Success/failure message associated with the resource.
	ResourceStatusReason *string `type:"string"`

	// Type of resource. (For more information, go to  AWS Resource Types Reference
	// (http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html)
	// in the AWS CloudFormation User Guide.)
	ResourceType *string `min:"1" type:"string" required:"true"`
}
```
out of those I think these three may be of interest:

 - `LogicalResourceId`
 - `PhysicalResourceId`
 - `ResourceType`

but if we want a map it means we'll need to pick 2. Would it make sense to build a map where key is `LogicalResourceId` and value is `PhysicalResourceId`?

-----

Overall I'm thinking that it may potentially lead to some anti-patterns as people could start building infrastructure on top of resources which aren't explicitly exposed via `Outputs`, but if they have some ancient CF stacks which they don't want to touch I reckon this may come handy ?

Knowing some specific use cases of this would be helpful @mwarkentin ^

**Comment by mwarkentin** [comment]
Thanks for the review @radeksimko - I'll provide our current use case here, and then think about your other comments some more and get back to you.

We're using [Convox](https://convox.com) to manage our applications. We have some AWS resources which are not managed by Convox - we're using Terraform to manage these (bastion instance, ASG scaling schedules, DNS entries, RDS instances, etc.).

Convox uses Cloudformation stacks for basically everything - racks (aka. clusters / environments), applications, services. These stacks (and configured outputs) are out of our control. Having access to the resources section would enable us to programatically access things like security group IDs, IAM instance roles, etc. without having to request upstream changes from Convox.

Does that help?

**Comment by mwarkentin** [comment]
@radeksimko `LogicalResourceId` and `PhysicalResourceId` would definitely be the most useful for us, so if we need to pick two, those would be my pick.

I don't currently have a use case for needing to access the status or type values - if something came up in the future would it be an issue refactoring it to expose those via a Map value?

**Comment by apparentlymart** [comment]
Hello @mwarkentin, and thanks for working on this!

As part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it.

If you or someone else has the time and motivation to apply same changes to [the `aws` provider repository](https://github.com/terraform-providers/terraform-provider-aws) and open a new PR there, the maintainers of that provider should be able to review and merge it.

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Pull request closed without merging**
