### PR TITLE
Convert int to int64 when building the cluster.NodeConfig struct

### PR DESCRIPTION
**Pull request by djworth**
related to issue https://github.com/hashicorp/terraform/issues/2901

### CODE REVIEW

**Comment by apparentlymart** [comment]
:+1: looks plausible to me. There's a similar thing going on in the AWS EBS code where the disk sizes are set.

I eagerly await the day when someone wants to create a 4.3 exabyte disk and Terraform fails to represent it correctly due to its use of a paltry 32-bit integer. :D

**Comment by radeksimko** [comment]
@djworth Thanks for noticing and sending the PR! Would you mind attaching a test or modify an existing test, so it's covering this bug?

@apparentlymart I didn't know about EBS, but I know there's the same bug in `google_compute_instance_template`, which the linked issue is actually mentioning.

**Comment by djworth** [comment]
@radeksimko Sure thing!

**Comment by sparkprime** [comment]
I fixed the other one, I'll leave this one to you lot :)

**Comment by radeksimko** [comment]
@apparentlymart Can you explain further what the problem is with EBS volumes? I just checked that resource and all `int64` attributes seem to be ok - in fact since that EBS support has been implemented, it was correct:
https://github.com/hashicorp/terraform/blob/dcebff7108ed423de777792ff5ae0b165deb2afa/builtin/providers/aws/resource_aws_ebs_volume.go#L73-L81

**Comment by apparentlymart** [comment]
@radeksimko sorry I wasn't meaning to say that there is an issue there *now*, but more that the issue had existed historically and we did the same workaround. So my comment was more "this seems like a reasonable solution because it's how we already solved EBS volumes", not "this also needs to be done for EBS volumes". I apologize for not being clearer.

**Comment by radeksimko** [comment]
Merging, I will add the test in a separate commit.
Thanks again @djworth

**Comment by radeksimko** [comment]
Done in 53499a9391804727ecdcc3551515ec4e9a101fff

**Pull request merged**
