### PR TITLE
ECS service ignore taks definition

### PR DESCRIPTION
**Pull request by zimbatm**
On AWS ECS services, allow to ignore task definition changes. This is to
provide an interface where terraform manages everything except the task
definitions and deploys to the services. You would have to provision the
initial services with a blank task definition.

```tf
# A noop-like task definition to bootstrap the cluster
resource "aws_ecs_task_definition" "null" {
  family = "null"

  container_definitions = <<EOF
[
  {
    "name": "null",
    "image": "busybox",
    "memory": 4,
    "essential": true,
    "command": ["sleep", "100000"]
  }
]
EOF
}

resource "aws_ecs_service" "example" {
  name                       = "example"
  cluster                     = "${aws_ecs_cluster.default.id}"
  task_definition        = "${aws_ecs_task_definition.null.arn}"
  # Allow to update task definitions independently
  update_task_definition = false
  desired_count          = 1
}
```

### CODE REVIEW

**Comment by zimbatm** [comment]
Looking for 20% percent review

**Comment by catsby** [comment]
Hello @zimbatm – I'm curious , would using `ignore_changes` work here, instead? 

- https://www.terraform.io/docs/configuration/resources.html#ignore-changes

Ex: 

```
resource "aws_ecs_task_definition" "null" {
  family = "null"

  container_definitions = <<EOF
[
  {
    "name": "null",
    "image": "busybox",
    "memory": 4,
    "essential": true,
    "command": ["sleep", "100000"]
  }
]
EOF

  lifecycle {
    ignore_changes = ["container_definitions"]
  }
}
```

**Comment by zimbatm** [comment]
OMG! I think you're right

**Comment by zimbatm** [comment]
Yep. Neverming then, sorry for the noise.

**Comment by catsby** [comment]
@zimbatm not at all! Thanks for opening the PR, even if not accepted we appreciate the thought, time, and energy 😄

**Pull request closed without merging**
