### PR TITLE
provider/kubernetes: Pods Resource CRUD operations implemented

### PR DESCRIPTION
**Pull request by lwander**
The issue I was having in the old PR is actually a Terraform core issue, see #3575 

Currently the Update operation mirrors the Create operation, this is done to have Terraform updates mirror those of `kubectl`. 

I will add more acceptance tests soon, but I'm not sure how in depth the documentation should be.

@radeksimko @sparkprime

### CODE REVIEW

**Comment by radeksimko** [comment]
Sorry for the silence from my side here, it was partially intentional - I was thinking if there is any good solution in the middle of _JSON strings_ as parameters (i.e. very generic solution) and full expansion (i.e. very specific solution). That said nothing was born in my head in the meantime.

> I'm not sure how in depth the documentation should be.

^ **That** (the documentation) and this
screen shot 2015-12-15 at 17 55 50
makes me think that the extra effort & pain we'd have to experience by comparing (un)marshalled JSON strings would not be _such pain_ compared to this.

@lwander What do you think about these two different approaches now, when you have slightly more in-depth experience with k8s API?

**Comment by lwander** [comment]
It makes me question if Kubernetes should really be managed by a tool like Terraform, since this approach just replaces on DSL with another... then again having some level of integration allows Kubernetes to fit into the bigger Hashicorp toolset, which is great. 

My response halfway through this PR was to automate most of this work using code generation, which would allow the implementer of a Terraform provider to define how a Terraform schema maps to a data type like `k8s.PodSpec` and then have Terraform do transformation for you. This is overkill for smaller resources, but becomes necessary when dealing the resource representations as large as the one defined in this PR. I wrote up a small proposal for @phinze, have you had the chance to look over that yet?

**Comment by xied75** [comment]
@lwander @radeksimko while I was trying to get k8s into production, the way to manage many lines of "kubectl" is getting annoying.

Pods need to use env variables to find other services, it can only see the vars that already created before it. Thus making sure the ordering is correct now falls into terraform's territory.

I would rather see a light-weight hybrid k8s provider that can allow me to specify the dependencies in TF file and integrate the actually creation/query of k8s resources to kubectl for the time-being?

My two pence.

**Comment by radeksimko** [comment]
As discussed privately with @lwander I'm closing this stale PR for now along with https://github.com/hashicorp/terraform/pull/3453 .

The Kubernetes provider implementation is open for anyone else to revisit, but I'd highly recommend doing so after the [mentioned things](https://github.com/hashicorp/terraform/pull/3453#issuecomment-224261369) are at least partially solved.

Implementing even a very basic (and actually useful) K8S provider _manually_ doesn't seem to be a good approach which is a **lesson learnt** from these closed PRs - so in that sense the effort & time here was not wasted.

**Pull request closed without merging**
