### PR TITLE
helper/schema: If a list field contains maps with computed entries, then mark the list as computed

### PR DESCRIPTION
**Pull request by philsttr**
Prior to this change, I noticed that:
1. if a list field contains computed string elements, then the list is marked as computed.   
2. if a map field contains computed elements, then the map is marked as computed.
3. if a list field contains maps, which contain computed elements, then the list is NOT marked as computed (this seemed incorrect)

This change corrects 3, such that the list will be marked as computed.

In particular, this fixes a problem for fields of type `schema.TypeSet`, whose elements are of type `schema.TypeMap`, whose elements are computed.  Note that `readSet` actually reads the field as a list first.

For example, consider the following schema...

```go
	"maps": &schema.Schema{
		Type:        schema.TypeSet,
		Set:         mapHash,
		MinItems:    0,

		Elem: &schema.Schema{
			Type:        schema.TypeMap,
			MinItems:    1,
			MaxItems:    1,
			Elem: &schema.Schema{
				Type:        schema.TypeString,
			},
		},
		Optional: true,
	},
```

Note that the `mapHash` function determines the unique ID of an item (a map) so that a proper set can be built.

Without this change, during `terraform plan`, the `mapHash` function will be passed `nil` for computed maps (since field_reader.ReadField returns null for maps with computed entries).
A proper hash for `nil` cannot be accurately determined.  You could theoretically always return the same value, but that breaks downstream logic that assumes each element will have a unique hash.

With this change, since the list is marked as computed, `mapHash` is not invoked for each element during `terraform plan`

This is causing Pryz/terraform-provider-ldap#6.  To reproduce the issue, take a look at that issue.

I tried to get creative and fix `terraform-provider-ldap` by handling `nil` by always returning the same value, or by returning unique values for each invocation, but could never get both plan and apply to work.

So, I started looking into terraform itself, and was able to solve the issue with this change.

### CODE REVIEW

**Comment by apparentlymart** [comment]
Hi @philsttr! Thanks for working on this.

The behavior of nested structures in field readers can be tricky due to all of the different interactions, including all the different `FieldReader` implementations, so thanks for digging in here and getting to the bottom of this!

The code here is actually planned to be significantly rewritten in a forthcoming release to introduce the new value/type system that's coming from the configuration language improvements we're currently working on, but since that's a few months away at least I'm open to merging this in the interim to address the problem described in Pryz/terraform-provider-ldap#6.

If you're able, it'd be great to have a unit test for this situation so we can make sure we don't break it again, particularly in the aforementioned forthcoming rework of this subsystem. I think adding a new case to `testFieldReader` should cause this to be tested against all of the different field reader implementations, since that function is used as a helper to test each of them:

https://github.com/hashicorp/terraform/blob/8c15d75d0054fba55433c76a9149c3c64d964322/helper/schema/field_reader_test.go#L188-L451

If you don't think you'll be able to work on a test here please let me know and we can have someone on the Terraform team work on a test when time allows.

Thanks again for working on this!

**Comment by philsttr** [comment]
Hi @apparentlymart ,

I had worked on developing a unit test by adding a new use case to https://github.com/hashicorp/terraform/blob/f78fe3c01e494e4eaff25627f8748902751b0d6b/helper/schema/field_reader_config_test.go#L216

I gave up after a few hours of frustration since I couldn't get it to hit the paths that I wanted.

I decided to submit this PR to make sure I was on the right implementation path before investing more time in a unit test.

I'll give it another shot, and look into adding the test in field_reader_test.go

**Comment by philsttr** [comment]
I've added some unit tests.

As a baseline, I added a unit test for all of the field readers for handling a list of maps (non-computed).

I also added a unit test for the config field reader for handling a list of _computed_ maps, which is the subject of this PR.

**Comment by philsttr** [comment]
Hi @apparentlymart, can you take another look at this?  (I've added the requested unit tests)

**Comment by philsttr** [comment]
Any chance on getting this merged soon?

**Comment by philsttr** [comment]
@apparentlymart Can this be incorporated?  At least for the unit tests that need to work with the rewrite you mentioned?

**Comment by apparentlymart** [comment]
Hi @philsttr! Sorry for the delay here.

Thanks for adding these additional tests!

We're currently doing focused work on the aforementioned configuration language improvements and so unfortunately need to hold on reviewing this for the moment due to the context-switching overhead. The fieldreader logic is notoriously _tricky_ so we need to make sure have time to do detailed review and testing. However, it _is_ on our list to look at and someone on the team will take a look at it as soon as we can.

**Comment by teamterraform** [comment]
Hello, and sorry for the long silence!
The Terraform SDK has been extracted to its own repository (https://github.com/hashicorp/terraform-plugin-sdk). In support of this we are freezing the related codepaths in Terraform and closing PRs. Thank you!

**Pull request closed without merging**
