### PR TITLE
provider/vcd: Support to add ovf parameter in vapp

### PR DESCRIPTION
**Pull request by cgroschupp**

### CODE REVIEW

**Comment by pasikarkkainen** [comment]
@ cgroschupp : Hmm.. are you planning to refresh this PR? It seems to have conflicts..

**Comment by cgroschupp** [comment]
@pasikarkkainen i fixed the conflicts.
@stack72 can you please merge the pr?

**Comment by pasikarkkainen** [comment]
Is there something else that should be done before this PR can be merged? It seems to apply cleanly now. @stack72 ?

Thanks!

**Comment by pasikarkkainen** [comment]
re-ping.. ?

**Comment by pasikarkkainen** [comment]
@stack72 , @grubernaut , @jen20 : Is there something missing from this PR ? I'd love to see this PR merged.. please let us know if something is missing!

**Comment by pasikarkkainen** [comment]
Would it be possible for @ewypych or @Boran to run the vCloud Director tests against this PR? I noticed you guys have been testing other vCD related PRs recently.. I'd like to see this PR merged aswell..

Thanks!

**Comment by ewypych** [comment]
@pasikarkkainen I can take a look at this at the weekend, but I cannot promise anything.

**Comment by Boran** [comment]
Sure, I can compile and run a test scenario against a live vCloud.
When/how is ovf parameter used in vcloud? Does this only work when one use an ovf appliance of image? I presume it has no effect when booting a VM installed by an ISO?

In the example provided, the hostname is specified. This is set for me when vmware tools are installed after the base image boots.

Found this doc on ovf attributes: https://pubs.vmware.com/vca/index.jsp?topic=%2Fcom.vmware.vcloud.api.tenant.doc_90%2FGUID-8FFA6226-DCA0-4CB1-BA4E-DD7C9713CB7C.html

Could someone explain some test cases in more detail?

**Comment by cgroschupp** [comment]
@Boram You can test it with any VM. With installed vmware tools, you can query the parameters with this command within the VM.
`vmware-rpctool 'info-get guestinfo.ovfEnv'`

The supplied ovf parameter does not change the VM, you have to create tools to react to the parameters or to use images like coreos that support ovf parameters.

**Comment by pasikarkkainen** [comment]
Yep. OVF Properties are used to pass configuration settings/values to the VM, which are then available via vmware-tools in the guest OS, to do whatever it wants with them.

vcloud director GUI also supports OVF properties so it can ask the user to provide values for configuration settings (OVF properties) when manually provisioning a new vApp/VM which has OVF properties.

**Comment by pasikarkkainen** [comment]
Here's an example with the already mentioned coreos .ovf/.ova image:
https://stable.release.core-os.net/amd64-usr/current/coreos_production_vmware_ova.ova

Upload that OVA image to vCloud Director catalog, and then manually provision vApp using the image from the vCD Web GUI. You'll be asked to provide values for the following settings (OVF properties):
http://pasik.reaktio.net/vcloud-ovf-properties-example-coreos1.png

The point with this PR is to allow specifying those OVF properties values from Terraform.

**Comment by pasikarkkainen** [comment]
You can check the actual OVF properties (key names) by extracting the image (.OVA is actually a normal tar archive), and then checking the .OVF file inside:

      <Property ovf:userConfigurable="true" ovf:type="string"
                ovf:key="guestinfo.hostname" ovf:value="">
        <Label>Hostname</Label>
        <Description>Hostname</Description>
      </Property>

      <Property ovf:userConfigurable="true" ovf:type="string"
                ovf:key="guestinfo.coreos.config.data" ovf:value="">
        <Label>CoreOS config data</Label>
        <Description>Inline cloud-config data</Description>
      </Property>

      <Property ovf:userConfigurable="true" ovf:type="string"
                ovf:key="guestinfo.coreos.config.url" ovf:value="">
        <Label>CoreOS config url</Label>
        <Description>URL to cloud-config data</Description>
      </Property>

etc.

**Comment by pasikarkkainen** [comment]
So you should be able to specify:

ovf {
    guestinfo.hostname = "core1"
    guestinfo.coreos.config.data = "whatever"
    guestinfo.coreos.config.url = "http://server.domain.tld/config"
}

and so on.

**Comment by cgroschupp** [comment]
Transfer PR to terraform-providers/terraform-provider-vcd#1

**Comment by cgroschupp** [comment]
Transfer PR to terraform-providers/terraform-provider-vcd#1

**Pull request closed without merging**
