### PR TITLE
provider/aws/spot_fleet_request: fixed reading network associate_public_ip_address configuration [closes #12974]]

### LINKED ISSUE #12974: aws_spot_fleet_request recreates every time
### Terraform Version
0.9.1

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_spot_fleet_request

### Terraform Configuration Files
```hcl
resource "aws_spot_fleet_request" "nodes-elasticsearch-spot-production-k8s" {
  iam_fleet_role      = "arn:aws:iam::example:role/aws-ec2-spot-fleet-role"
  spot_price          = "0.293"
  allocation_strategy = "lowestPrice"
  target_capacity     = 12
  valid_until         = "2019-11-04T12:00:00Z"

  launch_specification {
    instance_type               = "m3.xlarge"
    ami                         = "ami-fa5c7489"
    key_name                    = "${aws_key_pair.kubernetes-production-k8s-example-com.id}"
    availability_zone           = "${aws_subnet.eu-west-1a-production-k8s-example-com.availability_zone}"
    subnet_id                   = "${aws_subnet.eu-west-1a-production-k8s-example-com.id}"
    user_data                   = "${file("${path.module}/data/user_data.node.elasticsearch.sh")}"
    iam_instance_profile        = "${aws_iam_instance_profile.nodes-production-k8s-example-com.id}"
    vpc_security_group_ids      = ["${aws_security_group.nodes-production-k8s-example-com.id}"]
    associate_public_ip_address = true

    root_block_device {
      volume_size           = "20"
      volume_type           = "gp2"
      delete_on_termination = true
    }

    ebs_block_device {
      device_name           = "/dev/xvdg"
      volume_type           = "gp2"
      volume_size           = "100"
      delete_on_termination = true
    }
  }
}
```

### Debug Output
Sorry, it's pretty hard to strip private data from such output.

### Panic Output
No panic.

### Expected Behavior
No spot fleet request recreation.

### Actual Behavior
Recreates every time.

### Steps to Reproduce
1. `terraform apply`
2. `terraform apply` -> recreates

### Important Factoids
This probably what happened:

1. We created spot fleet request.
2. We updated spot fleet request, this change was not reflected by terraform, it didn't do anything, so we manually cancelled the old one.
3. Repeated terraform apply recrated the spot fleet request.
4. Repeated terraform apply wants create a new spot fleet request everytime.

We use remote s3 state. It seems that this remove state correnctly tracks the id (sfr-*).

Also, see output from terraform plan (and apply)

```bash
    allocation_strategy:                                                               "lowestPrice" => "lowestPrice"
    client_token:                                                                      "terraform-00baa70e260848a6cd1baa8a09" => "<computed>"
    excess_capacity_termination_policy:                                                "Default" => "Default"
    iam_fleet_role:                                                                    "arn:aws:iam::example:role/aws-ec2-spot-fleet-role" => "arn:aws:iam::example:role/aws-ec2-spot-fleet-role"
    launch_specification.#:                                                            "1" => "1"
    launch_specification.1125083684.ami:                                               "ami-fa5c7489" => "" (forces new resource)
    launch_specification.1125083684.associate_public_ip_address:                       "false" => "false"
    launch_specification.1125083684.ebs_optimized:                                     "false" => "false"
    launch_specification.1125083684.iam_instance_profile:                              "nodes.production.k8s.example.com" => "" (forces new resource)
    launch_specification.1125083684.instance_type:                                     "m3.xlarge" => "" (forces new resource)
    launch_specification.1125083684.monitoring:                                        "false" => "false"
    launch_specification.1125083684.spot_price:                                        "" => ""
    launch_specification.1125083684.user_data:                                         "376162e0e0cb7583c27a7c77bbe89004db5dab87" => "" (forces new resource)
    launch_specification.1125083684.weighted_capacity:                                 "" => ""
    launch_specification.3218522932.ami:                                               "" => "ami-fa5c7489" (forces new resource)
    launch_specification.3218522932.associate_public_ip_address:                       "" => "true"
    launch_specification.3218522932.availability_zone:                                 "" => "eu-west-1a" (forces new resource)
    launch_specification.3218522932.ebs_block_device.#:                                "" => "1"
    launch_specification.3218522932.ebs_block_device.3994770134.delete_on_termination: "" => "true" (forces new resource)
    launch_specification.3218522932.ebs_block_device.3994770134.device_name:           "" => "/dev/xvdg" (forces new resource)
    launch_specification.3218522932.ebs_block_device.3994770134.encrypted:             "" => "<computed>" (forces new resource)
    launch_specification.3218522932.ebs_block_device.3994770134.iops:                  "" => "<computed>" (forces new resource)
    launch_specification.3218522932.ebs_block_device.3994770134.snapshot_id:           "" => "<computed>" (forces new resource)
    launch_specification.3218522932.ebs_block_device.3994770134.volume_size:           "" => "100" (forces new resource)
    launch_specification.3218522932.ebs_block_device.3994770134.volume_type:           "" => "gp2" (forces new resource)
    launch_specification.3218522932.ebs_optimized:                                     "" => "false"
    launch_specification.3218522932.ephemeral_block_device.#:                          "" => "<computed>" (forces new resource)
    launch_specification.3218522932.iam_instance_profile:                              "" => "nodes.production.k8s.example.com" (forces new resource)
    launch_specification.3218522932.instance_type:                                     "" => "m3.xlarge" (forces new resource)
    launch_specification.3218522932.key_name:                                          "" => "kubernetes.production.k8s.example.com" (forces new resource)
    launch_specification.3218522932.monitoring:                                        "" => "false"
    launch_specification.3218522932.placement_group:                                   "" => "<computed>" (forces new resource)
    launch_specification.3218522932.root_block_device.#:                               "" => "1"
    launch_specification.3218522932.root_block_device.0.delete_on_termination:         "" => "true" (forces new resource)
    launch_specification.3218522932.root_block_device.0.iops:                          "" => "<computed>" (forces new resource)
    launch_specification.3218522932.root_block_device.0.volume_size:                   "" => "20" (forces new resource)
    launch_specification.3218522932.root_block_device.0.volume_type:                   "" => "gp2" (forces new resource)
    launch_specification.3218522932.spot_price:                                        "" => ""
    launch_specification.3218522932.subnet_id:                                         "" => "subnet-c7b9a7b1" (forces new resource)
    launch_specification.3218522932.user_data:                                         "" => "376162e0e0cb7583c27a7c77bbe89004db5dab87" (forces new resource)
    launch_specification.3218522932.vpc_security_group_ids.#:                          "" => "1"
    launch_specification.3218522932.vpc_security_group_ids.2814185034:                 "" => "sg-64ee291d"
    launch_specification.3218522932.weighted_capacity:                                 "" => ""
    replace_unhealthy_instances:                                                       "false" => "false"
    spot_price:                                                                        "0.293" => "0.293"
    spot_request_state:                                                                "active" => "<computed>"
    target_capacity:                                                                   "12" => "12"
    valid_until:                                                                       "2019-11-04T12:00:00Z" => "2019-11-04T12:00:00Z"
```

There is visible some mismatch in "number" launch_specification key. The remote state contains only 1125... number.

### PR DESCRIPTION
**Pull request by hrach**

### CODE REVIEW

**Comment by hrach** [comment]
This fixes #12974. Tested manually for my testcase. I tried to write a test, but I'm failing to do it. It's quite magic for me and I'm not sure what the test is actually testing. Could someone point me into right direction?

**Comment by dashkb** [comment]
@hrach I'd be happy to pull and try this out but it seems to me the only changes you made are commented out (and you changed the tests).  Are you sure you fixed the problem?

**Comment by hrach** [comment]
@dashkb sorry, the second commit for only for confirming that tests test the bug, it revealed that tests doesn't fail :D I will remove the second commit for now.

**Comment by victorcoder** [comment]
This also bite us, thank you for the patch

**Comment by lesykm** [comment]
Will this patch be merged to upstream?

**Pull request merged**
