### PR TITLE
match terraform-releases expectations

### PR DESCRIPTION
**Pull request by jbardin**

### CODE REVIEW

**Review by pselle — APPROVED** [review]
👍 I still think it's weird that go is 1.16 and not 1.16.0, but here we are (and can change if this ends up being weird)

**Comment by apparentlymart** [comment]
I already said this in a private discussion but just want to repeat it here to keep the discussion all together!

When I changed `.go-version` in my earlier PR to use `1.16`, `goenv` produced an error message saying that it wasn't a valid Go version and suggested that I add `.0` to make it valid, and so I did because `.go-version` is primarily a configuration for `goenv` and only secondarily a hook for a safety check in our release process.

Unfortunately this sort of divergence can happen because `goenv` has its own internal table of version numbers to Go release package URLs, as opposed to mechanically constructing URLs based on convention. I'm cool with temporarily changing this to get the release process unblocked, but I think afterwards we'll need to eitehr make the release process more compatible with `goenv`, or adopt some other convention for this safety check which doesn't overlap with `goenv`'s file. :confounded:

**Comment by pselle** [comment]
Thank you for adding this for completeness! We should definitely follow up.

**Comment by jbardin** [comment]
Already have the revert staged for post-release

**Pull request merged**
