### PR TITLE
website: Dead link in index.html.markdown

### PR DESCRIPTION
**Pull request by PhilippeGalvan**
It looks like this is a dead link and I have not found a valid replacement for it :/ !

### CODE REVIEW

**Comment by remilapeyre** [comment]
Hi @PhilippeGalvan, it looks like it was removed in d2e999ba1f2a4a12f29e65f4ede95882f55e15f0:

> Finally I removed the examples directory, which had outdated examples and links. There are better, actively maintained examples available.

I think this line in was just forgotten, can you remove it? The four examples are in the sidebar so the use should find them thought there documention.

**Comment by PhilippeGalvan** [comment]
I proposed another way to get up to date examples through a generic approach.

**Comment by mildwonkey** [comment]
Whoops, I removed those directories - I had no idea they were references on the website.

There are more broken links than that; if you click on any of the sub-pages they also have broken links (for e..g https://www.terraform.io/intro/examples/aws.html).  

I suspect the whole section should be removed or updated to point directly to our learn website, so I am going to reach out to both my team and our education team to see how they'd like to fix it (solutions may include restoring the content I deleted, too, of course).

**Comment by mildwonkey** [comment]
I've opened a PR to remove the entire section; if we choose not to remove it entirely it will likely end up being re-written. 

We definitely don't want to point users to randomly search github for providers, since there's no guarantee that they will find examples, or even an official provider vs an outdated fork or community provider that isn't maintained or up to our standards. I'm going to close this PR and we will fix the page internally, but thank you very much @PhilippeGalvan for bringing the issue to our attention.

**Pull request closed without merging**
