### PR TITLE
Datadog provider

### PR DESCRIPTION
**Pull request by ojongerius**
@phinze this PR is rough. I've pulled @vinceprignano's changes in, and copied my provider work over.
We've been using this provider at Atlassian for a little while and does what we need. To be useful to the general public it probably needs a little TLC.

Things worth noting/discussing:

* Read resources are not in there yet, I've started in a branch https://github.com/ojongerius/terraform-provider-datadog/tree/38_read_resources but this needs work.
* I've copied the pattern @vinceprignano used of 'faking' warning and critical levels. It keeps configurations small, but is a little inconvenient in the provider.
* Graphs are not an autonomous resource in Datadog, I'm simulating this by sneaking an ID in the title. Not something I'm happy with. What are your thoughts? Keen to discuss.
* There is a lot of duplication in the resources that are easy to abstract out. Happy to do that but wanted to get the PR our rather sooner than later.

Happy to refactor as we go :smile:

### CODE REVIEW

**Comment by ojongerius** [comment]
Have done some cleanup:

* Remove monitor resource, its replaced by metric_alert, outlier_alert and service_check
* Refactor to be closer to the API; each resource creates exactly one resource (unless count is used) instead of 2, this removes much unneeded complexity. A warning threshold is now supported by the API, which I'm working on.
* Remove fuzzy resources like graph, and resources that used them -dashboard and screenboards. I'd welcome these resources, but the current state of Terraform and the Datadog API does not allow these to be implemented in a clean way.

**Comment by ojongerius** [comment]
* Implemented support for multiple thresholds per monitor.
* Removed notify attributes, setting it in the message is more flexible.

**Comment by ojongerius** [comment]
* Revert back to one monitor resource that support all types
* Add more options
* Add read resource
* Add tests for updates
* Break Travis build fails -It looks like this is caused by vendoring, not sure how to fix that one. I'll wait for the documentation referred to in https://github.com/hashicorp/terraform/pull/4909 has surfaced.

Happy to add documentation if there is willingness to merge this in to master.

**Comment by ojongerius** [comment]
Fixed build and added some doco.

**Comment by jen20** [comment]
Hi @ojongerius! This looks good and I think we'll be happy to merge it - could you squash the commits and force push back to the pull request branch though? I'll look at getting a test account set up so that we can run the acceptance tests nightly in Travis.

**Comment by jen20** [comment]
I've gone ahead and rebased this as #5251. It should appear in Terraform 0.6.12. We also have a test account set up for acceptance testing, so the tests should be run nightly in due course.

**Pull request closed without merging**
