### PR TITLE
Remove the client secrets file for Google provider

### PR DESCRIPTION
**Pull request by stuntgoat**
Terraform seems to work without the client secrets json file. I haven't run all the acceptance tests but I'm able to interact with the API.

### CODE REVIEW

**Comment by stuntgoat** [comment]
I'm confused as to why tests are failing; they're passing locally.

**Comment by sparkprime** [comment]
Looks like the test run got killed, maybe due to some transient problem with the travis hosting (out of RAM or whatever).

**Comment by grosskur** [comment]
I'd love to see this get merged. Could someone re-run the Travis build?

**Comment by phinze** [comment]
Retriggered! :guitar:

**Comment by phinze** [comment]
Looks like the build was unsalvageable in its current state. I'm rebasing and testing this branch now - will push as a separate PR and link here.  :camel:

**Comment by phinze** [comment]
Closing this in favor of #884, (which squashes but retains commit authorship) - thanks for the contribution @stuntgoat! :candy:

**Pull request closed without merging**
