### PR TITLE
Bumped github.com/ukcloud/govcloudair vendor version

### PR DESCRIPTION
**Pull request by dn1s**
Since #13585 didn't include the latest changes here yet another pull request. :)

@bobbydeveaux can you test against this changes as well? Thank you in advance.

### CODE REVIEW

**Comment by bobbydeveaux** [comment]
the test output was using the latest master branch from ukcloud/govcloudair, and pulled in the latest versions from my local vendor file, so those functions were in when I ran the tests :)

**Comment by stack72** [comment]
Hi @dn1s / @bobbydeveaux 

Any chance you could post the output of the acceptance test run for this?

Thanks

Paul

**Comment by bobbydeveaux** [comment]
make testacc TEST=./builtin/providers/vcd 
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/05/18 10:47:32 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/vcd -v  -timeout 120m
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccVcdDNAT_Basic
--- PASS: TestAccVcdDNAT_Basic (51.76s)
=== RUN   TestAccVcdFirewallRules_basic
--- PASS: TestAccVcdFirewallRules_basic (56.21s)
=== RUN   TestAccVcdNetwork_Basic
--- PASS: TestAccVcdNetwork_Basic (64.27s)
=== RUN   TestAccVcdSNAT_Basic
--- PASS: TestAccVcdSNAT_Basic (58.67s)
=== RUN   TestAccVcdVApp_PowerOff
--- PASS: TestAccVcdVApp_PowerOff (224.59s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/vcd	455.574s

**Comment by stack72** [comment]
in that case, LGTM :)

**Comment by stack72** [comment]
@bobbydeveaux any chance you could drop me a mail (stack72 @ hashicorp dot com) - would love to discuss this provider a little more :)

**Pull request merged**
