### PR TITLE
provider/aws: adding support for SQS queues

### PR DESCRIPTION
**Pull request by mzupan**
Disclaimer, I'm pretty new to Go but this seems to be working in my tests for adding/editing/delete a queue. It also passed `make test` but I might be doing things wrong

This adds basic SQS functionality to create/edit/delete a SQS queue. Right now it doesn't support anything like dead letter or permissions.

Let me know if anything really bad or something I missed sticks out

### CODE REVIEW

**Comment by catsby** [comment]
Hey @mzupan , did you yank the branch/repo you made this PR from?

**Comment by pmoust** [comment]
@catsby 
```
git fetch upstream pull/1888/head:f-add-sqs-support
```

**Comment by radeksimko** [comment]
@pmoust Nice one! :+1: I knew there must be a way to get it if there's visible diff in the web interface.

I just pulled it down and pushed to upstream: https://github.com/hashicorp/terraform/tree/f-add-sqs-support to make it easier for anyone else to look at.

**Comment by mzupan** [comment]
ya sorry.. I think I deleted the fork and forgot I made the PR.. If you need me to re-up it and create a new PR let me know

**Comment by radeksimko** [comment]
@mzupan I feel there's a decent amount of work behind this PR, so would you mind creating a new PR? :-)

Also looking at #1939 I personally prefer more specific resource names, in this case `aws_sqs_queue` over generic ones like `aws_sqs`.

**Comment by mzupan** [comment]
ok i'll create a new PR.. I like some of the work @johnewart  did in his PR so I'll combine the two... expect a new PR tonight.. then you can choose which one to merge.. I'd just be happy to get this and then the SNS one in so I can work on a subscribe option and get messages flowing from autoscale groups

thanks!

**Comment by johnewart** [comment]
@mzupan Awesome, I just finished tests and docs for the SNS bits, once this is merged then I'll update docs / code to support pulling in an ARN on the SQS queues for the subscriptions

**Comment by mzupan** [comment]
so since @johnewart has tests.. why don't we close this and focus on merging his

**Comment by radeksimko** [comment]
leaving @catsby to decide here... :)
but I agree, if @johnewart has done tests. I just can't see any update in https://github.com/hashicorp/terraform/pull/1939 - I can only see the 1st commit.

**Comment by catsby** [comment]
@johnewart do you have have tests to push to #1939?

**Comment by johnewart** [comment]
@catsby I added tests and docs to it, borrowing a bit from here and extending / cleaning things up

**Comment by catsby** [comment]
Hey @mzupan – thanks for the work here, but I'm closing in favor of #1939.

**Pull request closed without merging**
