### PR TITLE
added flatten interpolation function

### PR DESCRIPTION
**Pull request by mootpt**
added ability to flatten things like list of lists

### CODE REVIEW

**Comment by mootpt** [comment]
this should help in a few cases. let me know if there are any questions

**Comment by lblackstone** [comment]
Any update on this PR?

**Comment by mootpt** [comment]
@lblackstone Also curious. @radeksimko ?

**Comment by apparentlymart** [comment]
Hi again @mootpt!

Hopefully we're done with 0.10.0 bugfix releases for the time being, so we're resuming normal feature merging. Sorry for the delay here, and thanks again for working on this!

**Comment by mootpt** [comment]
Thanks @apparentlymart!

**Pull request merged**
