### PR TITLE
[WIP] new resource aws_codebuild_project

### PR DESCRIPTION
**Pull request by liamjbennett**
New resource for the new AWS CodeBuild service

- [x] Schema
- [x] Functionality
  - [x] Create
  - [x] Read
  - [x] Update
  - [x] Delete
- [x] Tests
  - [x] Schema Validation
  - [x] Acceptance Tests
  - [x] Running Them
- [x] Documentation

### CODE REVIEW

**Comment by liamjbennett** [comment]
@stack72 stuggling with the last import test ..

```
=== RUN   TestAccAWSCodeBuildProject_importBasic
--- FAIL: TestAccAWSCodeBuildProject_importBasic (39.29s)
        testing.go:265: Step 1 error: 1 error(s) occurred:

                * aws_codebuild_project.foo: [ERROR] Error retreiving Projects: "InvalidInputException: Project name cannot be empty\n\tstatus code: 400, request id: 76362976-d8da-11e6-b1a9-5f8644bfcde2"
FAIL
```

**Comment by liamjbennett** [comment]
```
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSCodeBuildProject_importBasic -timeout 120m
=== RUN   TestAccAWSCodeBuildProject_importBasic
--- FAIL: TestAccAWSCodeBuildProject_importBasic (36.95s)
        testing.go:265: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

                (map[string]string) {
                }


                (map[string]string) (len=7) {
                 (string) (len=13) "environment.#": (string) (len=1) "1",
                 (string) (len=34) "environment.713653963.compute_type": (string) (len=20) "BUILD_GENERAL1_SMALL",
                 (string) (len=44) "environment.713653963.environment_variable.#": (string) (len=1) "1",
                 (string) (len=58) "environment.713653963.environment_variable.3512425362.name": (string) (len=8) "SOME_KEY",
                 (string) (len=59) "environment.713653963.environment_variable.3512425362.value": (string) (len=10) "SOME_VALUE",
                 (string) (len=27) "environment.713653963.image": (string) (len=1) "2",
                 (string) (len=26) "environment.713653963.type": (string) (len=15) "LINUX_CONTAINER"
                }

FAIL
```

**Comment by bacoboy** [comment]
It seems that also having a data source for codebuild projects would be helpful in addition to a resource to create/destroy them.  One use case I can think of is an existing codebuild repo that I might want to trigger with and `aws_codecommit_trigger`, but need the ARN for a codebuild project (maybe looked up by name via a data source).  Thoughts?

**Comment by liamjbennett** [comment]
```
vagrant@terraform:/opt/gopath/src/github.com/hashicorp/terraform$ make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSCodeBuildProject_*'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/01/31 16:20:01 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSCodeBuildProject_* -timeout 120m
=== RUN   TestAccAWSCodeBuildProject_basic
--- PASS: TestAccAWSCodeBuildProject_basic (37.77s)
=== RUN   TestAccAWSCodeBuildProject_artifactsTypeValidation
--- PASS: TestAccAWSCodeBuildProject_artifactsTypeValidation (0.00s)
=== RUN   TestAccAWSCodeBuildProject_artifactsNamespaceTypeValidation
--- PASS: TestAccAWSCodeBuildProject_artifactsNamespaceTypeValidation (0.00s)
=== RUN   TestAccAWSCodeBuildProject_nameValidation
--- PASS: TestAccAWSCodeBuildProject_nameValidation (0.00s)
=== RUN   TestAccAWSCodeBuildProject_descriptionValidation
--- PASS: TestAccAWSCodeBuildProject_descriptionValidation (0.00s)
=== RUN   TestAccAWSCodeBuildProject_environmentComputeTypeValidation
--- PASS: TestAccAWSCodeBuildProject_environmentComputeTypeValidation (0.00s)
=== RUN   TestAccAWSCodeBuildProject_environmentTypeValidation
--- PASS: TestAccAWSCodeBuildProject_environmentTypeValidation (0.00s)
=== RUN   TestAccAWSCodeBuildProject_sourceTypeValidation
--- PASS: TestAccAWSCodeBuildProject_sourceTypeValidation (0.00s)
=== RUN   TestAccAWSCodeBuildProject_sourceAuthTypeValidation
--- PASS: TestAccAWSCodeBuildProject_sourceAuthTypeValidation (0.00s)
=== RUN   TestAccAWSCodeBuildProject_timeoutValidation
--- PASS: TestAccAWSCodeBuildProject_timeoutValidation (0.00s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/aws    37.792s
```

**Comment by liamjbennett** [comment]
Closing in favour of #11560

**Pull request closed without merging**
