### PR TITLE
providers/openstack: add port_id to router interface

### PR DESCRIPTION
**Pull request by Fodoj**
It is possible to create router interface either with subnet id or with port id. Thats also how it implemented in gophercloud: https://github.com/rackspace/gophercloud/blob/master/openstack/networking/v2/extensions/layer3/routers/requests.go#L173

This PR addresses this issue by making subnet id not required and adding a way to specify port id.

### CODE REVIEW

**Comment by jtopjian** [comment]
Another nice one :smile: 

I should be able to look this over in the next day or so.

**Comment by Fodoj** [comment]
@jtopjian there was a minor bug with deletion, but now it's fixed

**Comment by Fodoj** [comment]
@jtopjian did you have time to check it out? Would be great to stop compiling personal fork and using it :)

**Comment by jtopjian** [comment]
@Fodoj I apologize - I've been tied up with a few other things, including the security group bug. I'll try to review this as soon as I can.

**Comment by jtopjian** [comment]
@Fodoj This looks good! I squashed your commits and added some tests in #3903. I'm going to close this PR in favor of that one.

**Pull request closed without merging**
