### PR TITLE
[WIP] provider/vsphere: reliable network interface indices

### PR DESCRIPTION
**Pull request by thetuxkeeper**
Before implementing the update of the network interfaces, we need a reliable way to match the config and the devices in VMware. 
This is a WIP since I have problems getting the data into the TF schema object structure. 
I want a map[string]map[string] structure. The outer map with the device id/device key as index and the inner map like the current structure with ip addresses, gateway,... 
Is there a way to override the hash function of the TypeSet ? With TypeMap  I get an error at runtime (will add the message later),  but the core message was that it was an invalid input for the schema object. 
cc @chrislovecnm

### CODE REVIEW

**Comment by tommynsong** [comment]
@thetuxkeeper i have merge your PR into my develop branch at https://github.com/tommynsong/terraform/tree/develop, but there seems to be issue with planning multiple network_interface.

Here is the resource declaration:
`resource "vsphere_virtual_machine" "web" {
  name          = "web-web"
  domain        = "domain.local"
  vcpu          = 2
  memory        = 4096
  datacenter    = "DC"
  cluster       = "test-cluster"
  host_system   = "esx1.domain.local"
  folder        = "SandboxS"
  dns_servers   = ["192.168.32.140", "192.168.33.140"]

  network_interface {
    label               = "mgmt"
    ipv4_address        = "192.168.33.21"
    ipv4_gateway        = "192.168.32.1"
    ipv4_prefix_length  = "22"
  }

  network_interface {
    label               = "nids"
    ipv4_address        = "169.254.64.2"
    ipv4_prefix_length  = "24"
  }

  disk {
    datastore = "Datastore1"
    template  = "Templates/CENTOS-7.1"
    type      = "thin"
    bootable  = true
  }
}`

And here is the output of the terraform plan:
`+ vsphere_virtual_machine.web
    cluster:                                "test-cluster"
    datacenter:                             "DC"
    disk.#:                                 "1"
    disk.3328003716.bootable:               "true"
    disk.3328003716.controller_type:        "scsi"
    disk.3328003716.datastore:              "Datastore1"
    disk.3328003716.iops:                   ""
    disk.3328003716.keep_on_remove:         ""
    disk.3328003716.key:                    "<computed>"
    disk.3328003716.name:                   ""
    disk.3328003716.size:                   ""
    disk.3328003716.template:               "Templates/CENTOS-7.1"
    disk.3328003716.type:                   "thin"
    disk.3328003716.uuid:                   "<computed>"
    disk.3328003716.vmdk:                   ""
    dns_servers.#:                          "2"
    dns_servers.0:                          "192.168.32.140"
    dns_servers.1:                          "192.168.33.140"
    domain:                                 "domain.local"
    enable_disk_uuid:                       "false"
    folder:                                 "SandboxS"
    host_system:                            "esx1.domain.local"
    linked_clone:                           "false"
    memory:                                 "4096"
    memory_reservation:                     "0"
    name:                                   "web-web"
    network_interface.#:                    "1"
    network_interface.0.adapter_type:       ""
    network_interface.0.device_key:         "<computed>"
    network_interface.0.ip_address:         "<computed>"
    network_interface.0.ipv4_address:       "169.254.64.2"
    network_interface.0.ipv4_gateway:       "<computed>"
    network_interface.0.ipv4_prefix_length: "24"
    network_interface.0.ipv6_address:       "<computed>"
    network_interface.0.ipv6_gateway:       "<computed>"
    network_interface.0.ipv6_prefix_length: "<computed>"
    network_interface.0.label:              "nids"
    network_interface.0.mac_address:        "<computed>"
    network_interface.0.subnet_mask:        "<computed>"
    skip_customization:                     "false"
    time_zone:                              "Etc/UTC"
    vcpu:                                   "2"


Plan: 1 to add, 0 to change, 0 to destroy.`

**Comment by thetuxkeeper** [comment]
Thank you for testing it! :)
 I'm having some trouble with the schema object and how to use it that it works like I want. Perhaps that's the source of the problem (overwriting indices, ...). It needs some more work :)
I don't have too much time for it, so I will take a look at it next week again.

**Comment by tommynsong** [comment]
@thetuxkeeper just want to point out that this issue seem to (in my current testing) affect CentOS 7 with open-vm-tools 9.10.2.48224 (build-2822639) .
I have tested with Ubuntu 16.04 with open-vm-tools 10.0.7.52125 (build-3227872) and the order of the vNICs remain intact.

**Comment by chrislovecnm** [comment]
@tommynsong does that version require the deploypkg?

**Comment by tommynsong** [comment]
@chrislovecnm according to https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2075048, it does not require the deploypkg

**Comment by pryorda** [comment]
Is this still a WIP or is it ready to be merged?

**Comment by thetuxkeeper** [comment]
@pryorda : Sorry, it's not ready. I haven't found the time to continue. 
I stopped at the point where I couldn't figure out how to put in predefined/self-generated indexes into the terraform schema. A "Set" seems to support custom indexing-functions, but I couldn't get it work in time.

**Comment by pryorda** [comment]
I found that vmware just reverses the order with getting guest.net info. I have a pull request to to just reverse it on the virtual machine read in the provider.

**Comment by tommynsong** [comment]
@pryorda if the issue is at govmomi, would it makes more sense to create a PR to VMware instead?
I'm just afraid that once VMware fix their guest.net info, we would come back here and undo the changes.

**Comment by pryorda** [comment]
From what i could tell, it is vmwares api. You are correct if vmware decides this is a bug we would have to come back.

Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Tommy Song <notifications@github.com> Date: 7/23/16  6:18 PM  (GMT-07:00) To: hashicorp/terraform <terraform@noreply.github.com> Cc: Daniel Pryor <daniel@pryorda.net>, Mention <mention@noreply.github.com> Subject: Re: [hashicorp/terraform] [WIP] provider/vsphere: reliable network interface indices (#7154) 
@pryorda if the issue is at govmomi, would it makes more sense to create a PR to VMware instead?

I'm just afraid that once VMware fix their guest.net info, we would come back here and undo the changes.

**Comment by sherzberg** [comment]
Any progress on this? We are running into this issue as well.

**Comment by mkrakowitzer** [comment]
Same issue here.

**Comment by sbourlon** [comment]
I have the same issue as well with Terraform v0.7.7.

**Comment by MichielVanderlee** [comment]
Any progress? This issue exists in v0.7.0-v0.8.4

**Comment by thetuxkeeper** [comment]
Sorry, I don't think there will be any progress from my side. Don't have time to work on it and we barely use terraform at the moment (no changes to the part terraform is responsible of).
Also there's a fix available by @pryorda: #7760
If someone wants to continue what I started, you can contact me. 
I'm closing this PR.

**Pull request closed without merging**
