### PR TITLE
adding exclude flag to plan and apply 

### PR DESCRIPTION
**Pull request by nevins-b**
This will exclude the specified resource and it's dependents from the graph.

Addresses #2253

### CODE REVIEW

**Comment by phinze** [comment]
Wow this is great work, @nevins-b - thank you!

I think we can actually fold this into targeting, which will make the UX a bit more cohesive and the implementation simpler as well.

My proposal is that we introduce a `!` prefix to negate the target:

```
terraform plan -target '!aws_db_instance.important'`
```

Then the implementation is basically just tacking your central loop onto the end of the TargetsTransformer.

What do you think?

**Comment by nevins-b** [comment]
@phinze Thanks!

That seems reasonable. The parseTargetAddresses function will need to be modified but it shouldn't be too bad.

**Comment by josephholsten** [comment]
@nevins-b this sounds awesome! what's the next step here? is it just rebasing onto master?

I also notice a lot of unrelated code in the diff. I think the only part that should be here is https://github.com/aocsolutions/terraform/commit/c7551d0bd9568aca48ec6eb10f1095029992f34b

**Comment by josephholsten** [comment]
Rebased at #3366

@nevins-b can you check that out and verify all's well?

**Comment by little-arhat** [comment]
Any updates on this?

**Comment by phinze** [comment]
Definitely want to land this! Closing this PR to roll into #3366 and will follow up there.

**Pull request closed without merging**
