### PR TITLE
provider/vsphere: Add custom_commands, expose admin_autologon and admin_autologon_count

### PR DESCRIPTION
**Pull request by mikesplain**
Adds the ability for users to add custom commands passed to window's sysprep step. To expand on https://github.com/hashicorp/terraform/pull/6087, I also added the ability to set the hard coded `AutoLogon` and `AutoLogonCount`.  

Tested on a vSphere 6.0 cluster.

### CODE REVIEW

**Comment by Freyert** [comment]
@mikesplain  the built in providers have been moved out of master. You will need to remake these changes over on https://github.com/terraform-providers/terraform-provider-vsphere

**Comment by apparentlymart** [comment]
Hello @mikesplain, and thanks for working on this!

As part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it.

[The vSphere provider](https://github.com/terraform-providers/terraform-provider-vsphere) -- and, in particular, the virtual machine resource -- are currently in the process of being revamped somewhat, with the goal of supporting more of the available features. Unfortunately this means that to re-target this change to the new repository may require some restructuring :confounded:.

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Comment by mikesplain** [comment]
@apparentlymart that's a real bummer. I know not everything can me merged in open source but I didn't even get a comment in the year+ it's been open... 

Thanks for your comment though.

**Comment by apparentlymart** [comment]
Hi @mikesplain,

I'm sorry for the long silence this PR got. Unfortunately at the time you opened it there wasn't any dedicated maintainer for the provider and it was easy for PRs to get lost in the one big combined queue we had for Terraform Core and all of the providers. :confounded: This was, in fact, one of the major motivations for splitting out the providers into their own repositories.

The vSphere provider _does_ nowadays have a focused maintainer and is under active development. I can understand the frustration of getting no response here for all this time and then my closing it. The Terraform project has had some growing pains as the number of providers has grown, and indeed we're still working through that to an extent, but at least nowadays many of the providers _do_ have dedicated or part-time maintainers to try to avoid dropping the ball like we did here.

I can't personally speak to the vSphere provider's development priorities since my focus is here on Terraform Core, but I _do_ know that more complete coverage of the capabilities of the virtual machine resource is a goal and so hopefully this capability would be added as part of that, if it wasn't already.

**Comment by mikesplain** [comment]
Totally understood. Thanks so much @apparentlymart.

**Pull request closed without merging**
