### PR TITLE
Add OAuth2 token support for GCS backend

### PR DESCRIPTION
**Pull request by luis-silva**
This PR aims to provide the functionality requested in issue #21680. The code was mostly inspired by what is already done in the [GCP provider](https://www.terraform.io/docs/providers/google/provider_reference.html#access_token)

I ran the following acceptance tests to validate correct operation:

- Confirm that no default credentials are set and therefore the requests should fail:

```sh
$ TF_ACC=1   GOOGLE_PROJECT=YYYY   go test -timeout=2m -parallel=4 ./backend/remote-state/gcs                                                             
--- FAIL: TestRemoteClientWithEncryption (0.00s)    backend_test.go:80: --- FAIL: TestBackend (0.00s)
    backend_test.go:134: TestBackendConfig on *gcs.Backend with configs.synthBody{Filename:"<TestWrapConfig>", Values:map[string]cty.Value{"bucket":cty.StringVal("tf-15a94aedb5a96e40-testbackend"), "encryption_key":cty.StringVal(""), "prefix":cty.StringVal("")}}
    backend_test.go:134: storage.NewClient() failed: dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
.....
```

- Specifying the path to a credentials file works as expected:

```sh
TF_ACC=1   GOOGLE_CREDENTIALS=~/Downloads/creds.json   GOOGLE_PROJECT=YYYY   go test -timeout=2m -parallel=4 ./backend/remote-state/gcs
ok      github.com/hashicorp/terraform/backend/remote-state/gcs 36.156s
```

- Using the new access token parameter also works as expected:

```sh
TF_ACC=1   GOOGLE_OAUTH_ACCESS_TOKEN=XXXX   GOOGLE_PROJECT=YYYY   go test -timeout=2m -parallel=4 ./backend/remote-state/gcs
ok      github.com/hashicorp/terraform/backend/remote-state/gcs 36.882s
```

### CODE REVIEW

**Comment by luis-silva** [comment]
@paddycarver @emilymye @mildwonkey Anything I can do to speed up the review of this PR?

**Comment by luis-silva** [comment]
@jbardin A quick and easy PR that would really unblock us with GCP remote states?

**Comment by carlpett** [comment]
Thanks for this @luis-silva, it will help my team as well! According to the codeowners file, the @terraform-google group is the reviewer.
So, @terraform-google, could you please have a look?

**Comment by carlpett** [comment]
Hm, apparently the group isn't set up :confused:

**Comment by luis-silva** [comment]
@mildwonkey I've asked @kostas-theo to sign the CLA so we've both done it now.

**Comment by williams-brian** [comment]
@mildwonkey Is this still waiting on review from someone? I would really like to see this merged. Having long-lived credentials stored on developer machines is a security risk that this feature would allow many people to avoid.

**Pull request merged**
