### PR TITLE
Support environment variables in *.tf config

### LINKED ISSUE #62: Environment variables in .tf files
Hey! This is a very cool project.

I browsed all over the documentation and couldn't find a way to interpolate environment variables in a configuration file. Is this possible?

### PR DESCRIPTION
**Pull request by ggiamarchi**
Fix #62

### CODE REVIEW

**Comment by mitchellh** [comment]
Thanks, I actually have a branch that looks a lot like this, but I think I want to take the Packer approach and only allow environmental variables as defaults to variables. The reasoning is that I want people to be able to look in just one place to find all the parameterization to a thing. 

That adds a considerable difficulty to the implementation though since variable defaults don't support interpolations in any way right now. I'm battling between doing something like this vs. the Packer way, and still leaning towards the Packer way as just being more correct long term. I'd rather do it right than do it fast. :(

Sorry, going to close this. This will surely form the basis of the final solution, but this isn't 100% there yet.

I'm trying to get it done before 0.5 but don't thnk I will. 0.6 for sure, then.

**Comment by ggiamarchi** [comment]
Sounds good, that's a good reason. Thanks.

**Comment by JeanMertz** [comment]
@mitchellh looking forward to the *Pakcer way* of environment variables support. Especially for `Provider` configurations, where most credentials go, this can be really beneficial.

As it stands now, we have to pass in the credentials from the CLI, where I'd rather get them from environment variables.

**Comment by mitchellh** [comment]
@JeanMertz See the CHANGELOG for 0.5 (to be relased soon), I added a halfway okay feature to do this :)

**Comment by JeanMertz** [comment]
@mitchellh awesome!

also (just a quick note, unworthy of a new issue(?)): it looks like the OpenStack docs on terraform.io are outdated. For example, I couldn't find any mention of `openstack_networking_router_v2`.

**Comment by mitchellh** [comment]
Probably just need to be redeployed with the next release :)

**Pull request closed without merging**
