### PR TITLE
provider/aws: Fix reading auto scaling group availability zones

### PR DESCRIPTION
**Pull request by tpounds**
A similar issue to pull request #4597 that fixes reading an auto scaling group's associated availability zones when only VPC zone identifiers (e.g. subnets) are specified. The availability zone attribute is now computed since AWS will supply the availability zones corresponding to the VPC zone identifiers.

### CODE REVIEW

**Comment by stack72** [comment]
Hi @tpounds,

Thanks for the PR. The only issue with it is the removal of the instances being created as part of the test. That should, ideally, be discussed in another issue :)

Paul

**Comment by tpounds** [comment]
@stack72 Thanks for merging with the test instance removal! I noticed this is true of many of the other auto scaling group acceptance tests as well. I'll look into cleaning this up further in another pull request.

**Comment by tpounds** [comment]
Oops! I actually missed that this pull request hasn't been merged yet. I'll split out the acceptance test change in a separate pull request.

**Comment by stack72** [comment]
Thanks @tpounds - i'll merge when travis goes green :) thanks again!

**Pull request merged**
