### PR TITLE
Closes #1906. Only submit modification requests if there is a change

### LINKED ISSUE #1906: Modifying tags on aws_db_instance attempts to send an empty modification request
When modifying tags on an RDS instance the update function attempts to send an empty modification request for the RDS instance.
Instead, within the update function, the modification request should only be send if one of the previous `hasChange` checks is true.

### PR DESCRIPTION
**Pull request by johnrengelman**

### CODE REVIEW

**Comment by radeksimko** [comment]
I would expect this behaviour to be rather built into Terraform core, because it's not just RDS that may be affected by this.

**Comment by johnrengelman** [comment]
Not sure how you image this to be supported in core. This is an artifact of how the RDS update function was first implemented. When support for tags was added, changes to tags can trigger terraform to see a modified resource which calls the update function. That function currently doesn't distinguish between changes to the RDS resource and the Tags (which is controlled via another API in AWS).

**Comment by radeksimko** [comment]
Maybe I'm just too naive here, but my point is that Terraform has a full local state + remote state (after refreshing) => it should be able to decide whether to even call `schema.Resource{ Update: ...` or not, no matter what's the content of the update function.

**Comment by johnrengelman** [comment]
Right, it does, but there **was** a change to the resource, so the update function needed to be called (in this case, I added a tag). The update function for RDS was then called and it automatically tries to submit an RDS Modification Request with no content in it, before getting to the part of the code where the tags are handled.

**Comment by radeksimko** [comment]
Ah, right, I see, that's a valid issue then, I'm just thinking if there's any more elegant solution than just creating a bool variable & setting it in to `true` in 13 blocks.

It's going to be easy to miss when adding a new parameter (i.e. new block).

**Comment by johnrengelman** [comment]
Yeah, unfortunately, the only other way is to inspect the fields on the request object which is just as error prone.

**Comment by mitchellh** [comment]
Yeah unfortunately this seems like something that should exist in core but since Terraform operates on resource-level changes and not field-level changes, I don't think it could be in the current form of Terraform. This looks good to me.

**Pull request merged**
