### PR TITLE
[WIP] Add Akamai provider

### LINKED ISSUE #5639: Support for configuring Akamai
We are using Akamai as a CDN provider and it would be awesome if we could use Terraform to configure our Akamai sites.

### PR DESCRIPTION
**Pull request by joshuaspence**
This is just a WIP but I figured that I would submit a pull request anyway in case anyone had some feedback. This PR will ultimately resolve #5639 when completed, but is far from being ready for review. I'm not a Golang programmer so please excuse any Golang faux pas.
- [ ] Acceptance tests
- [ ] Documentation
- [ ] Well-formed code

### CODE REVIEW

**Comment by cblecker** [comment]
This is a great start -- I know I'll be following this 😃

**Comment by bflad** [comment]
Hey @joshuaspence do you need any help moving this forward? New to writing Terraform myself, but absolutely hate dealing with Akamai's web interface(s). I'm specifically looking for working against the Property Manager API: https://developer.akamai.com/api/luna/papi/overview.html.

**Comment by stack72** [comment]
Hi

We see your WIP hasn't had any activity for over 28 days, so we're going to close it. We're still interested in taking a look so if it is ready for review/merge, please reopen it. 

Thank you!

Paul

**Comment by shantanugadgil** [comment]
I wonder if Akamai DNS support would (eventually 😀 ) come under this?
https://developer.akamai.com/api/luna/config-dns/overview.html

Regards,
Shantanu

**Pull request closed without merging**
