### PR TITLE
Makefile/docs: Lock in 1.6 req, doc vendored deps

### PR DESCRIPTION
**Pull request by phinze**
* Drop Go 1.5 compatibility env vars
 * Drop `make updatedeps` from `Makefile` and docs
 * Update README w/ vendored dep instructions

### CODE REVIEW

**Comment by jen20** [comment]
LGTM.

**Comment by alext** [comment]
Now that this is merged, there's nothing that installs the `gox` tool, and no mention of it in the docs. This makes it tricky for someone new to the project to build it...

**Comment by phinze** [comment]
@alext whoops good catch! :+1: 

Will get this fixed up.

**Comment by phinze** [comment]
(Done in 0cf6ba6f6417cdd5421c7b735950c05bcb4a59d5)

**Comment by alext** [comment]
Great.  Thanks for sorting that so quickly.

**Pull request merged**
