### PR TITLE
Implement restart policy support in Docker provider.

### LINKED ISSUE #2417: Docker Provider Does Not Support  --restart Switch
I'm using v0.5.3 to control some Docker containers and I've run into an issue: the Docker provider does not provide an equivalent to `--restart=yes` of the `docker run` command.  The upshot is that when the Docker host is restarted, your containers are inactive.  This is unacceptable for the majority of containers I run -- databases and message brokers.  I need those containers alive and kicking if the box gets rebooted.

### PR DESCRIPTION
**Pull request by tomwilkie**
Fixes #2417

### CODE REVIEW

**Comment by jen20** [comment]
This LGTM, however it also conflicts with #3761. IMO we should merge #3761, and then resolve the merge conflict with the functionality here with regards to failure counts.

**Comment by tomwilkie** [comment]
I'll rebase/merge tomorrow if that okay?  Got to prepare slides today.

**Comment by jen20** [comment]
Hi @tomwilkie - I'm actually doing it as we speak - you'll still get credit for the commit however!

**Comment by jen20** [comment]
Hi @tomwilkie, in merging this I realised it had already been applied as part of #3761 in a slightly different form - the `restart` and `max_retry_count` are separate arguments. I think this is ok, and perhaps a slight improvement over special string formatting, so for now I'm going to close this PR. If you think there are reasons to prefer this approach over the one in #3761, please reopen and let us know! Many thanks for your contribution - sorry it has taken us so long to get to.

**Comment by tomwilkie** [comment]
No worries, sounds good.

**Pull request closed without merging**
