### PR TITLE
provider/azurerm: Add support for exporting the `azurerm_storage_account` access keys

### LINKED ISSUE #6739: Azure RM: azurerm_storage_account should export storage keys
The azurerm_storage_account should export storage keys for use in later Terraform operations.  This would be particularly helpful when creating a storage account, then using it in an Azure RM template deployment where the storage key is an input param (ex: HD Insights cluster).

### PR DESCRIPTION
**Pull request by stack72**
Fixes #6739 

Please note that we do NOT have the ability to manage the access keys -
we are just getting the keys that the account creates for us. To manage
the keys, you would need to use the azure portal still

### CODE REVIEW

**Comment by jen20** [comment]
LGTM.

**Comment by Preskton** [comment]
Such response time! <3

**Comment by dinnak** [comment]
thoughts on when this might be available via a build?

**Comment by stack72** [comment]
Hi @dinnak

This will be part of the terraform 0.7 release

Paul

**Comment by ryhoward** [comment]
Awesome! Any idea on when 0.7 will be pushed out exactly? A couple weeks?

**Comment by stack72** [comment]
Hi @ryhoward 

I'm.not 100% sure here. I am not a member of the core team so one of @phinze or @jen20 would have to reply

Paul

**Comment by ryhoward** [comment]
thanks @stack72

**Comment by dinnak** [comment]
thanks @stack72

**Pull request merged**
