### PR TITLE
Revert "helper/schema: Make nested Set(s) in List(s) work"

### PR DESCRIPTION
**Pull request by catsby**
Reverts hashicorp/terraform#7393

### CODE REVIEW

**Comment by catsby** [comment]
re: failing tests mentioned in #7393:

```
TF_ACC=1 go test ./builtin/providers/fastly -v -run=TestAccFastlyServiceV1_gzips_basic -timeout 120m
=== RUN   TestAccFastlyServiceV1_gzips_basic
--- PASS: TestAccFastlyServiceV1_gzips_basic (35.94s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/fastly	35.953s
Test:
```

```
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSSecurityGroup_Change -timeout 120m
=== RUN   TestAccAWSSecurityGroup_Change
--- PASS: TestAccAWSSecurityGroup_Change (30.74s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	30.763s
Test:
```

**Comment by radeksimko** [comment]
Merge at will, I will see if I can turn the mentioned failures into more abstract (resource-agnostic) test cases.

**Comment by phinze** [comment]
LGTM - @catsby lets kick off AWS and Fastly suites manually after this lands.

**Comment by catsby** [comment]
New AWS run: https://travis-ci.org/hashicorp/terraform/builds/141378794
New Fastly run: https://travis-ci.org/hashicorp/terraform/builds/141378900

**Pull request merged**
