### PR TITLE
website/docs: Add cidrsubnets to IP Network Functions index

### PR DESCRIPTION
**Pull request by sirlatrom**

### CODE REVIEW

**Comment by sirlatrom** [comment]
This simple docs improvement will help users discover the existence of the `cidrsubnets` function which is very useful once you get to know it.

**Comment by sirlatrom** [comment]
Is there anybody out there?

**Comment by sirlatrom** [comment]
@mildwonkey would you be the right person to ping on this one?

**Comment by mildwonkey** [comment]
Sure, thanks @sirlatrom ! Sorry it took so long to get to this, thank you for the submission.

**Pull request merged**
