### PR TITLE
provider/openstack: Add Terraform version to UserAgent string

### PR DESCRIPTION
**Pull request by fatmcgav**
Just because it's useful... :)

### CODE REVIEW

**Comment by fatmcgav** [comment]
@jtopjian Thought this would be useful to add :)

**Comment by jtopjian** [comment]
@fatmcgav Yep, definitely useful. Looking at the other implementations of this, they all have HashiCorp in the agent, too, so how about:

```
HashiCorp-Terraform/" + terraform.VersionString()
```

**Comment by fatmcgav** [comment]
@jtopjian Yep, can make that tweak... I did look at other providers and didn't see a real standard...

**Comment by thomaschaaf** [comment]
Wouldn't it make sense to create one helper function to render the user agent for every provider? I don't think it makes sense to manually try to keep the user agent implementation the same?

**Comment by jtopjian** [comment]
> Yep, can make that tweak... I did look at other providers and didn't see a real standard...

Yeah, it looks like a mix of agent types. I saw that most of them had "HashiCorp" in the name, which is why I suggested it.

> Wouldn't it make sense to create one helper function to render the user agent for every provider? I don't think it makes sense to manually try to keep the user agent implementation the same?

I agree. Or at least standardize on a name.

@stack72 thoughts?

**Comment by fatmcgav** [comment]
There is a 'VersionHeader' const defined here: https://github.com/hashicorp/terraform/blob/master/terraform/version.go#L24

But it still needs to be used to construct a header... 
Agree that a helper function would be a useful addition..

**Comment by stack72** [comment]
@fatmcgav / @jtopjian IMO, I don't think it's so important - the AWS one is more as a partner thing so they can understand when the tool is used

But it would be nice to follow a similar convention

**Comment by fatmcgav** [comment]
@stack72 / @jtopjian Thoughts on https://github.com/fatmcgav/terraform/commit/76fbe83d87f9049d2005bc83f12d2caea59cc182

**Comment by stack72** [comment]
That looks good to me :)

**Comment by fatmcgav** [comment]
Cool, ok.. I'll see if I can stick a quick test case on it... 

Would it be better as a separate PR, or happy for it to be included in this one?

**Comment by stack72** [comment]
You can include it here :)

**Comment by fatmcgav** [comment]
Cool, ok... PR updated :)

**Comment by jtopjian** [comment]
Nice - thanks @fatmcgav! You're on a roll :)

**Pull request merged**
