### PR TITLE
provider/logentries: Implementing logentries provider

### PR DESCRIPTION
**Pull request by dabdine-r7**
Logentries provides log management, alerting and analytics for hosts, applications and more. Accounts are free to create and are free for the terraform acceptance tests.

We use logentries internally to redirect our application logs into a centralized dashboard. This provider allows management of the tokens and log IDs (which are secrets) and allows terraform users to plug log tokens and ids into their applications and infrastructure through mechanisms such as cloud-config, etc.

### CODE REVIEW

**Comment by dabdine-r7** [comment]
need to vendor a lib, but so far govendor just hangs on my system. so, figuring out why.

**Comment by dabdine-r7** [comment]
ok, vendoring done and the build passes. still need docs!

**Comment by dabdine-r7** [comment]
documentation done. A couple things to take care of:
1. Need to add the filename attribute to the logentries_log resource since it is required by the agent log source.
2. Need to add more logentries_log acceptance tests, perhaps one per log source.
3. Need to add ACCOUNT_DEFAULT as an accepted value for the retention_period of a logentries_log

**Comment by dabdine-r7** [comment]
OK, all above issues were addressed, removing WIP tags. This is ready to go / formal review.

**Comment by dabdine-r7** [comment]
can this make it into 0.7? ;)

**Comment by stack72** [comment]
Hi @dabdine-r7 

Thanks so much for the patience here. I have had a review of this and it looks good. Nothing out of the ordinary. Test results:

```
% make testacc TEST=./builtin/providers/logentries TESTARGS='-run=TestAccLogentriesLog_'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
TF_ACC=1 go test ./builtin/providers/logentries -v -run=TestAccLogentriesLog_ -timeout 120m
=== RUN   TestAccLogentriesLog_Token
--- PASS: TestAccLogentriesLog_Token (1.98s)
=== RUN   TestAccLogentriesLog_SourceApi
--- PASS: TestAccLogentriesLog_SourceApi (1.83s)
=== RUN   TestAccLogentriesLog_SourceAgent
--- PASS: TestAccLogentriesLog_SourceAgent (1.86s)
=== RUN   TestAccLogentriesLog_RetentionPeriod1M
--- PASS: TestAccLogentriesLog_RetentionPeriod1M (2.36s)
=== RUN   TestAccLogentriesLog_RetentionPeriodAccountDefault
--- PASS: TestAccLogentriesLog_RetentionPeriodAccountDefault (1.81s)
=== RUN   TestAccLogentriesLog_RetentionPeriodAccountUnlimited
--- PASS: TestAccLogentriesLog_RetentionPeriodAccountUnlimited (1.78s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/logentries	11.640s
```

```
% make testacc TEST=./builtin/providers/logentries TESTARGS='-run=TestAccLogentriesLogSet_'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
TF_ACC=1 go test ./builtin/providers/logentries -v -run=TestAccLogentriesLogSet_ -timeout 120m
=== RUN   TestAccLogentriesLogSet_Basic
--- PASS: TestAccLogentriesLogSet_Basic (1.26s)
=== RUN   TestAccLogentriesLogSet_NoLocation
--- PASS: TestAccLogentriesLogSet_NoLocation (1.54s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/logentries	2.813s
```

**Comment by dabdine-r7** [comment]
thank you @stack72!

**Pull request merged**
