### PR TITLE
provider/aws: allow ap-northeast-2 in region validation

### LINKED ISSUE #4635: new AWS region ap-northeast-2 (Seoul) not supported
AWS just launched a new region and I like to block access to all unused regions.  I get this error when I try to use `ap-northeast-2`:

Error refreshing state: 1 error(s) occurred:

* 1 error(s) occurred:

* Not a valid region: ap-northeast-2

### PR DESCRIPTION
**Pull request by phinze**
Fixes #4635

### CODE REVIEW

**Comment by catsby** [comment]
Need `[12]string` I think, otherwise :+1:

**Comment by phinze** [comment]
I'll see your `[12]string{...}` and raise you `[]string{...}` :grin:

**Comment by catsby** [comment]
:heart: to you @phinze but maybe #4637 is the one we should take :smile:

**Comment by phinze** [comment]
Yep his is better :+1:

**Pull request closed without merging**
