### PR TITLE
GitHub Organization Provider

### PR DESCRIPTION
**Pull request by johnrengelman**
This adds a new provider for managing Github organizations. It provides resources for managing membership in the organization, organization teams, team membership, and team repositories.

The acceptance tests require the `GITHUB_TOKEN` and `GITHUB_ORGANIZATION` envvars to be configured before executing.

This provider covers https://github.com/hashicorp/terraform/issues/1731

### CODE REVIEW

**Comment by johnrengelman** [comment]
Not sure what we need to do to add the new dependency. Guidance?

**Comment by jen20** [comment]
@johnrengelman you should be able to do: `godep save $(go list ./... | grep -v vendor)` in order to update the dependencies. I believe newer versions of godep negate the need for that though.

Also could you consider squashing this into one commit and force pushing back to the PR branch?

**Comment by johnrengelman** [comment]
@jen20 - will do. Getting on a plane atm, will update it tonight and figure out the deps.

**Comment by johnrengelman** [comment]
@jen20 rebased & squashed.
I ran the `godep` command and it vendored the `github` library, but it also deleted some `aws-sdk-go` library...not sure why.

**Comment by johnrengelman** [comment]
This breaks the build...why is there not a `Makefile` target for doing this?

**Comment by johnrengelman** [comment]
I just did some manual tweaking of the import stuff to get it correct. @phinze discovered an outstanding issue in `godeps` that is causing the issue:
https://github.com/tools/godep/issues/416
https://github.com/tools/godep/pull/415

CI built successfully now.

**Comment by johnrengelman** [comment]
Rebased and resolved the merge conflicts with the vendor changes.

**Comment by johnrengelman** [comment]
Rebased this commit again and split out the vendor dependency to its own commit to facilitate review.

**Comment by phinze** [comment]
Got the tests passing on our side:

```
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccGithubMembership_basic
--- PASS: TestAccGithubMembership_basic (2.79s)
=== RUN   TestAccGithubTeamMembership_basic
--- PASS: TestAccGithubTeamMembership_basic (5.21s)
=== RUN   TestAccGithubTeamRepository_basic
--- PASS: TestAccGithubTeamRepository_basic (3.89s)
=== RUN   TestAccCheckGetPermissions
--- PASS: TestAccCheckGetPermissions (0.00s)
=== RUN   TestAccGithubTeam_basic
--- PASS: TestAccGithubTeam_basic (2.88s)
=== RUN   TestAccGithubUtilRole_validation
--- PASS: TestAccGithubUtilRole_validation (0.00s)
=== RUN   TestAccGithubUtilTwoPartID
--- PASS: TestAccGithubUtilTwoPartID (0.00s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/github 14.788s
```

Great work on this @JacobASeverson and @johnrengelman! Thank you!

**Comment by johnrengelman** [comment]
@phinze you might want to look at the acceptance tests... @JacobASeverson just told me that that the account it uses for joining and stuff is hard coded...so maybe that should be a configurable option for spec.

**Comment by JacobASeverson** [comment]
Yup realized that when I got an email flood from Github while you were doing testing. I can work on that later today.

**Comment by phinze** [comment]
This is just `TerraformDummyUser` yeah? I noticed that but figured it was clearly an account created for these tests and it worked so it seemed okay. Definitely would be a bit nicer to have that parameterized though!

**Comment by JacobASeverson** [comment]
Yeah just a dummy account so won't hurt anything.

**Pull request merged**
