### PR TITLE
Disable visual error hierarchy in -no-color mode

### PR DESCRIPTION
**Pull request by kmoe**
Commit e865faf adds visual indentation for diagnostic messages using various vertical line characters. This PR disables this behaviour when running in automation, adding `format.DiagnosticPlain` to preserve the legacy behaviour.

While the contents of stderr are not intended to be part of the Terraform API, this is currently how terraform-exec detects certain error types in order to present them as well-known Go errors to the user. Such detection is complicated when vertical lines are added to the CLI output at unpredictable points.

I expect this change will also be helpful for screen reader users.

### CODE REVIEW

**Comment by apparentlymart** [comment]
Hi @kmoe! Thanks for diving into this and proposing a compromise.

I understand and agree with the motivation of producing less "complicated" output when the output target isn't a terminal, but I think the `m.RunningInAutomation` flag isn't the best way to activate this because the sort of automation that flag is imagining is running Terraform in something like Terraform Cloud or a CI system, where the output _is_ still presented to a user for reading but where it'd be confusing for Terraform to recommend the user to run other `terraform ...` commands (because it's the automations job to run Terraform CLI, in that case).

However, some preceding work (which is what enabled us to start using Unicode characters in the output here) might give a good alternative: Terraform now tracks whether each of the standard handles seems to be connected to a terminal or whether it's connected to some other sort of file descriptor, like a pipe. We could therefore consider turning off this newer rendering when stderr is connected to a non-terminal, as I assume it would be for `terraform-exec` if it's attempting to parse that output.

A downside of that approach is that some automation systems also end up capturing Terraform's output through a pipe rather than a pseudo-terminal, and so sighted users of such systems would end up with the not-so-readable output intended for pipes, rather than the terminal-oriented presentation. However, I think that'd be a reasonable compromise given that I expect we'll have machine-readable diagnostics output in the medium-term and so `terraform-exec` could then pivot to using that and we could restore the (subjectively) nicer output even when stderr is a pipe.

We don't currently have a `Meta` method for this, but [`Meta.StdinPiped`](https://github.com/hashicorp/terraform/blob/35e66e8933b3ef675a11a940953d2070679db848/command/meta.go#L327) shows the principle with `Stdin` instead of `Stderr`. I think a copy of that function with `=~ s/Stdin/Stderr/g` would get the effect I was describing above, which we could then substitute for `m.RunningInAutomation` in the `showDiagnostics` function.

**Comment by apparentlymart** [comment]
I suppose a further option would be to trigger it off the same flag which disables the virtual terminal format sequences, which I assume `terraform-exec` would already be doing in order to avoid the output being interspersed with bold, red, and reset escape sequences?

The nice thing about _that_ approach is that it would allow automation that supports VT formatting sequences but not a full pseudo-terminal to continue to see the newer output. It's a _little_ disingenuous to redefine `-no-color` as "disable things that only make sense in a visual terminal", but for this particular situation it seems like the closest fit of the three existing mechanisms we have for making this decision.

I believe `m.Color` reflects the presence of the `-no-color` option (inverted, naturally) so that could hopefully be a drop-in replacement for `m.RunningInAutomation` here.

**Comment by kmoe** [comment]
@apparentlymart, thanks for explaining the reasoning behind the `m.RunningInAutomation` flag - I agree it's best not to overload it in this case. The slightly disingenuous `m.Color` option seems best for now. All terraform-exec commands are run with `-no-color`.

Testing becomes a little more awkward when special visual hierarchy characters are coupled to colour mode. I've suggested a `stripAnsi()` utility for use in e2e tests, so we have at least one test covering the visual hierarchy characters. There are several other options here so please let me know what you think.

**Comment by apparentlymart** [comment]
Thanks for the updates, @kmoe! Although this did make the e2etests (and some other tests) a little more awkward, it seems like this is the best compromise for now, until we can reach a point where there's machine-readable diagnostics output for all of the commands that `terraform-exec` is interested in parsing errors for.

I'm going to merge this now so we can have some time for it to soak in the main branch and in our alpha releases before we start making "real" 0.15.0 releases containing this new UI, in case there are some other quirks of lightly overloading `-no-color` that we've not considered yet.

Thanks again for working on this!

**Pull request merged**
