### PR TITLE
Typo regarding ordered/unordered in for.html.md

### PR DESCRIPTION
**Pull request by navaati**
This one confused me for a hot minute, so I’m fixing it for the next person :).

### CODE REVIEW

**Comment by laurapacilio** [comment]
Thank you! This issue has since been addressed on main :)

**Comment by navaati** [comment]
Hi. That would be good, but are you sure ? I still see the issue on main here: https://github.com/navaati/terraform/blob/main/website/docs/language/expressions/for.html.md#element-ordering.

**Comment by laurapacilio** [comment]
Hi - thank you for checking! So, if I go here: https://github.com/hashicorp/terraform/blob/main/website/docs/language/expressions/for.html.md

That's the file on the main branch in the terraform repo, where the website docs are built from. It's fixed! :-) It's also fixed on the live version of this page on the website, which you can see here: https://www.terraform.io/docs/language/expressions/for.html

I think the link you sent is from a forked version of the repository, and that's why you're not seeing it.

**Comment by navaati** [comment]
Wow, yes I was looking at the fork, sorry for the noise and thank you for the fix !

**Pull request closed without merging**
