### PR TITLE
Website typographic updates

### PR DESCRIPTION
**Pull request by jasoncostello**
👋 

This PR updates the website's typography as part of a larger initiative to create typographic consistency across OSS project sites.  

- Type heirarchy (Adds Klavika font for headings)
- Updates Logo (Klavika version)
- Removes Lato font and references

cc/ @captainill 

screencapture-localhost-4567-1487031521598

screen shot 2017-02-13 at 4 45 26 pm

### CODE REVIEW

**Comment by mitchellh** [comment]
Looks great! Merging and will send it out.

**Comment by mattclegg** [comment]
This looks great on the marketing/splash pages (in the screenshots) but changing all h2 to be uppercase in the docs reduces the readability. They are already bold enough without being uppercase. Can it be changed back?

**Comment by jasoncostello** [comment]
@mattclegg Thanks for the feedback. Are you specifically referring to instances of H2's in the article? For instance, "Example"? 

screen shot 2017-02-14 at 11 13 39 am

**Comment by mattclegg** [comment]
Yeah, I actually was referring to the `ATTRIBUTES REFERENCE` & `IMPORT` title in the docs.

screen shot 2017-02-15 at 5 04 53 pm

**Comment by jasoncostello** [comment]
@mattclegg Yes, I agree. I'm working on a fix now.

**Pull request merged**
