### PR TITLE
azurerm_virtual_machine - dont send ssh_keys if length is 0

### PR DESCRIPTION
**Pull request by rrudduck**
After vm create the property linuxConfiguration.ssh.publicKeys cannot be changed. If a vm is created outside terraform (or the definition changes) and the ssh key is not provided with terraform you will get the error:

Changing property 'linuxConfiguration.ssh.publicKeys' is not allowed.

This change simply doesn't set the ssh configuration if there are no keys provided to terraform. This will not prevent diffs (changing the specified key) from failing, but it will prevent the error when omitted completely.

### CODE REVIEW

**Comment by stack72** [comment]
Hi @rrudduck 

Thanks for the PR here - did you successfully manage to get the acceptance test working? I keep getting the following error (3 times)

```
% make testacc TEST=./builtin/providers/azurerm TESTARGS='-run=TestAccAzureRMVirtualMachine_changeSSHKey'        2 ↵ ✭
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/02/09 11:56:21 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/azurerm -v -run=TestAccAzureRMVirtualMachine_changeSSHKey -timeout 120m
=== RUN   TestAccAzureRMVirtualMachine_changeSSHKey
--- FAIL: TestAccAzureRMVirtualMachine_changeSSHKey (142.36s)
	testing.go:265: Step 0 error: Error applying: 1 error(s) occurred:

		* azurerm_storage_account.test: 1 error(s) occurred:

		* azurerm_storage_account.test: Error creating Azure Storage Account 'accsa6sy8w6cift': storage.AccountsClient#Create: Failure sending request: StatusCode=0 -- Original Error: Put https://management.azure.com/subscriptions/c0a607b2-6372-4ef3-abdb-dbe52a7b56ba/resourceGroups/acctestrg6sy8w6cift/providers/Microsoft.Storage/storageAccounts/accsa6sy8w6cift?api-version=2016-01-01: net/http: request canceled
FAIL
exit status 1
FAIL	github.com/hashicorp/terraform/builtin/providers/azurerm	142.378s
make: *** [testacc] Error 1
```

**Comment by rrudduck** [comment]
I had the same issue myself a few runs but it eventually resolved itself. Let me run it again locally to confirm.

**Comment by rrudduck** [comment]
I ran it a couple more times and eventually it ran. I had issues with other tests running as well, so I'm wondering if there is an issue with the sdk version.

Here is a working run.

`
root@364bdd1f6ae3:/go/src/github.com/hashicorp/terraform# make testacc TEST=./builtin/providers/azurerm TESTARGS='-run=TestAccAzureRMVirtualMachine_changeSSHKey'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/02/09 22:17:21 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/azurerm -v -run=TestAccAzureRMVirtualMachine_changeSSHKey -timeout 120m
=== RUN   TestAccAzureRMVirtualMachine_changeSSHKey
--- PASS: TestAccAzureRMVirtualMachine_changeSSHKey (505.06s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/azurerm        505.067s
root@364bdd1f6ae3:/go/src/github.com/hashicorp/terraform#
`

**Comment by stack72** [comment]
Excellent! Thanks for this :) 

There was a new SDK released yesterday so we will upgrade and look at the potential error under the hood then

Thanks for the excellent work here

Paul

**Pull request merged**
