### PR TITLE
Use hashicorp/go-plugin for plugin system

### PR DESCRIPTION
**Pull request by mitchellh**
This replaces this plugin system with the extracted github.com/hashicorp/go-plugin

This doesn't introduce any new features such as binary flattening but opens us up to that a lot more easily and removes a lot of code from TF in favor of the upstream lib.

This will introduce a **protocol change** that will cause all existing plugins to have to be recompiled to work properly. There is no actual API changes so they just have to recompile, but it is technically backwards incompatible so it is worth mentioning and perhaps moving this PR to the 0.7 branch. It is up to you.

### CODE REVIEW

**Comment by jen20** [comment]
I think we should likely target this at 0.7 since it will break third party providers. It's likely worth us finding out the exact manner in which it breaks them so we can document it - I'll take a look at that this afternoon.

**Comment by mitchellh** [comment]
Agreed. I can tell you how it breaks them, this error will show up: https://github.com/hashicorp/go-plugin/blob/38d403273d408ac4162f4bd8210baa6f655c6145/client.go#L369

**Comment by josephholsten** [comment]
So much beautiful deletion!

**Comment by jen20** [comment]
Merged in #5808 to the `dev-0.7` branch.

**Pull request closed without merging**
