### PR TITLE
Allow new aws api-gateway integration types

### PR DESCRIPTION
**Pull request by froderick**
The added types are 'AWS_PROXY' for integrating with lambdas and
'HTTP_PROXY' for integrating via http.

See http://docs.aws.amazon.com/apigateway/api-reference/resource/integration/

### CODE REVIEW

**Comment by kwilczynski** [comment]
@froderick hi there! Thank you for contributing!

This looks great! Could you potentially abstract the `ValidateFunc` out into a helper method so that a unit test can be added? Also, acceptance test would need to be updated to cover new integration types too.

**Comment by froderick** [comment]
I've extracted the validator. I'm also working on acceptance tests. I'm not really that clear on the value of additional acceptance tests in this case. The `type` here is simply that AWS honors. There's no real difference in terms of the test behavior. Seems like unit tests would be sufficient here. I'm new to contributing to this project. Am I missing something here?

**Comment by kwilczynski** [comment]
@froderick thank you!

No problem with not adding new acceptance test. I had a look and it would not add any value, indeed, to what is there.

**Comment by froderick** [comment]
Ok, great. Does anything else remain, or is this ready to merge?

**Comment by stack72** [comment]
Hi @froderick 

Thanks so much for the work here - the only thing that I believe remains is the update of the documentation to include the new types

Thoughts?

Paul

**Comment by froderick** [comment]
I've added the new values to the docs.

**Comment by BerndWessels** [comment]
@froderick @stack72 Hi guys

Please consider to also support the new ANY method type.

**Comment by kwilczynski** [comment]
@BerndWessels hi there! I am happy to report that this has been done recently, as per the https://github.com/hashicorp/terraform/pull/9205.

**Comment by highbass** [comment]
Hello,

There is one problem that I have noticed, when you create a method using "Lambda Function" and you check off "Use Lambda Proxy integration" through the web UI... AWS automatically pre-populates the method response with "HTTP Status: Proxy". 

Using the above, updated changes, when I push it through terraform it seems like it overrides the default and leaves it completely blank. 

I sifted through amazon API for method response (https://docs.aws.amazon.com/apigateway/api-reference/resource/method-response/) and didn't find any good answer about how that setting is configured.

Not sure what else I could be Missing! Response greatly appreciated.

Z

P.S. Code to replicate

resource "aws_api_gateway_rest_api" "audit-log-api" {
  name = "${var.environment}-${var.appname}-app-apigateway-datacollector"
  description = "api gateway: ${var.appname} for ${var.environment}"
  depends_on = ["aws_lambda_function.collector-lambda-function"]
}

#RESOURCE
resource "aws_api_gateway_resource" "audit-log-resource" {
  rest_api_id = "${aws_api_gateway_rest_api.audit-log-api.id}"
  parent_id = "${aws_api_gateway_rest_api.audit-log-api.root_resource_id}"
  path_part = "${var.api_path}"
  depends_on = ["aws_api_gateway_rest_api.audit-log-api"]
}

#METHOD : ANY`
resource "aws_api_gateway_method" "audit-log-method" {
  rest_api_id = "${aws_api_gateway_rest_api.audit-log-api.id}"
  resource_id = "${aws_api_gateway_resource.audit-log-resource.id}"
  http_method = "ANY"
  authorization = "NONE"
  depends_on = ["aws_api_gateway_resource.audit-log-resource"]
}

resource "aws_api_gateway_integration" "audit-log-integration" {
  rest_api_id = "${aws_api_gateway_rest_api.audit-log-api.id}"
  resource_id = "${aws_api_gateway_resource.audit-log-resource.id}"
  http_method = "${aws_api_gateway_method.audit-log-method.http_method}"
  type = "AWS_PROXY"
  uri = "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${aws_lambda_function.collector-lambda-function.arn}/invocations"
  integration_http_method = "POST"
  depends_on = ["aws_api_gateway_method.audit-log-method"]
}


Image of what it looks like

screen shot 2016-11-04 at 2 32 36 pm


Image of what it looks like with AWS GUI

screen shot 2016-11-04 at 2 23 28 pm

**Pull request merged**
