### PR TITLE
WIP: providers/google: restore_policy supports update

### LINKED ISSUE #11736: Non-authoritative policies don't survive updates
Initially reported by @allandrick in #11556:

> Some additional data points that may be useful here - I too was doing this the old way like @craigfurman and when I updated to 0.8.5 and updated the syntax for google_project_iam_policy, I too lost access to the project I was working on, despite specifying "authortative = false" in my configuration. Thankfully I am using the org.node and was able to re-add my Terraform service account to the specific project and start clean using the 0.8.5 syntax - however, things are still not quite right.
>
> I use a Terraform module in all projects to add the default policy bindings I want - this works. I then use local policy bindings and another google_project_iam_policy resource, also with authorative = false, in the same project to add custom roles to the project that aren't needed globally in the module.
>
> This causes terraform to flip-flop between re-writing the policy bindings, especially where I am trying to add a specific IAM role to existing groups or service accounts that were defined with the base policy bindings for the project.

and

>Example:
>
>in module "iam-account", we create:
>
>```
>resource "google_project_iam_policy" "google-project" {
>    project = "${var.gcp_project}"
>    policy_data = "${data.google_iam_policy.policy-bindings.policy_data}"
>    authoritative = false
>}
>
>data "google_iam_policy" "policy-bindings" {
>    # App Engine
>    binding {
>        role = "roles/appengine.appAdmin"
>        members = [
>            "group:${var.admins_group}",
>        ]
>    }
>    binding {
>        role = "roles/appengine.deployer"
>        members = [
>            "group:${var.users_group}",
>        ]
>    }
>```
>
>and in a local terraform file, we later create:
>
>```
>resource "google_service_account" "gcr-readonly" {
>    account_id = "gcr-readonly"
>    display_name = "Google Container Registry read-only service account"
>}
>
>data "google_iam_policy" "local-policy-bindings" {
>  binding {
>    role = "roles/container.viewer"
>    members = [
>      "serviceAccount:${google_service_account.gcr-readonly.email}",
>    ]
>  }
>}
>
>resource "google_project_iam_policy" "google-project" {
>    project = "${var.gcp-project}"
>    policy_data = "${data.google_iam_policy.local-policy-bindings.policy_data}"
>    authoritative = false
>}
>```
>
>this should only add this new policy binding to the Project IAM - and terraform plan says that's all it wants to do:
>
>```
>~ google_project_iam_policy.google-project
>    policy_data: "{}" => "{\"bindings\":[{\"members\":[\"serviceAccount:gcr-readonly@xxxx-xxxx-xxxx.iam.gserviceaccount.com\"],\"role\":\"roles/container.viewer\"}]}"
>```
>
>So we apply it:
>
>```
>google_project_iam_policy.google-project: Modifying...
>  policy_data: "{}" => "{\"bindings\":[{\"members\":[\"serviceAccount:gcr-readonly@xxxx-xxxx-xxxx.iam.gserviceaccount.com\"],\"role\":\"roles/container.viewer\"}]}"
>google_project_iam_policy.google-project: Modifications complete
>```
>
>But then immediately a new terraform plan says it wants to change things again, because reality doesn't match what is in the module's state, even though it shouldn't be removing things that are already in IAM...
>
>```
>~ module.iam-account.google_project_iam_policy.google-project
>    policy_data: "{\"bindings\":[{\"members\":[\"group:admins@group.company.com\"],\"role\":\"roles/appengine.appAdmin\"},{\"members\":[\"group:users@group.company.com\"],\"role\":\"roles/appengine.deployer\"},{\"members\":[\"serviceAccount:gcr-readonly@xxxx-xxxx-xxxx.gserviceaccount.com\"],\"role\":\"roles/container.viewer\"}]}" => "{\"bindings\":[{\"members\":[\"group:admins@group.company.com\"],\"role\":\"roles/appengine.appAdmin\"},{\"members\":[\"group:users@group.company.com\"],\"role\":\"roles/appengine.deployer\"}]}"
>```

### PR DESCRIPTION
**Pull request by evandbrown**
The initial version of google_project_iam_policy would capture an IAM
policy that could be restored (for non-authoritative resources), but it
would only do this on create. If the policy drifted outside of Terraform
after create, the originaly restore_policy would be applied on an
update, removing the out-of-band changes.

This change makes non-authoritative google_project_iam_policy resources
truly non-destructive. The restore_policy is recalculated on update and
delete, ensuring that only the policy_data is removed from a project's
IAM policy.

Fixes #11736

### CODE REVIEW

**Comment by paddyforan** [comment]
Is this still a WIP @evandbrown, or is it ready for review?

**Comment by evandbrown** [comment]
@paddyforan sorry, should have clarified what I meant by WIP. It is ready for review, but I have a few acceptance tests I'd like to add before merging.

**Comment by paddyforan** [comment]
Fair enough! I will never turn down moar acceptance tests.

**Comment by paddyforan** [comment]
So, thoughts on this.

I think this will remove any ability Terraform has to detect drift, because it considers any changes outside of it to be totally OK and not something to be corrected. Also, I think that's a much bigger hammer than we need for the actual bug at hand, which is that module state and root state aren't aware of each other's changes to the same resource, which is (as I understand it) something Terraform should be able to handle.

I have some reservations about this approach, just because it's such a departure from what Terraform does in other cases.

**Comment by danawillow** [comment]
Looks like the associated issue was closed. @evandbrown, can this PR be closed?

**Comment by pdecat** [comment]
> I think this will remove any ability Terraform has to detect drift, because it considers any changes outside of it to be totally OK and not something to be corrected.

What about ignoring drift about identities (IAM users, service accounts) that are not managed by terraform (i.e. not created by `google_service_account`)?

In my use case, this would let me manage service accounts using terraform, and the customer would still be able to manage real users and custom service accounts by hand.

This could be made an additional option, or a sub-option of `authoritative` like `lenient` or `lazy`.

**Comment by paddyforan** [comment]
> This could be made an additional option, or a sub-option of authoritative like lenient or lazy.

I'd really like to avoid getting into a situation where we're specifying different levels of control Terraform has. At the root of the issue, I guess, is that Terraform is an infrastructure-as-code tool. If the code (i.e., Terraform) isn't documenting what your infrastructure actually should be, something has gone wrong somewhere.

In practice, that gets complicated sometimes, and we err on the side of UX over theory. Which is where `authoritative` comes into play (though I still feel :/ about it). As soon as you get into "by hand", we're getting away from what Terraform is good at.

I'm going to close this out, as the issue the PR is meant to resolve has been closed. If there's a continued interest in this PR and getting the implementation merged, feel free to reopen/comment, @evandbrown, and we'll pick this up. I don't mean to slam the door on the conversation, but I also don't want to leave stale PRs just sitting around. :)

If there's continued interest in supporting IAM use cases not covered by our current implementation, we'd love to hear them. But let's break them out into issues, so poor @evandbrown doesn't get a million notifications. :)

**Comment by munnerz** [comment]
Hi there - I've just been reading through this PR and the issues related to it.

I'd like to express my support for this, or some similar implementation. I too have a customer that would like to manage their users through the admin console, but also have their application/infrastructure managed by Terraform. We need to create service accounts/roles for eg. SQL users, but right now it's an all-or-nothing as whenever they add a new user through the cloud console, the users are removed later.

We also may have multiple Terraform projects that deploy different environments but within the same project - once again, each of these stacks needs to set IAM permissions. As it stands, the two stacks 'fight' each other, thus making it effectively unusable (it is far too easy to accidentally break a different environment when updating an environment!)

**Comment by paddycarver** [comment]
Hey @munnerz! Thanks for the feedback. We're mostly tracking this in terraform-providers/terraform-provider-google#72 and its linked issues and PRs right now.

I'm sorry for the problems! Definitely see how those valid use cases could totally be left in the cold by the way things are right now. Fortunately, terraform-providers/terraform-provider-google#171 is in (I hope) its final rounds of review and should be merged soon, hopefully. That should cover the use cases you discussed. If not, I'd love to hear more about it on that PR.

In the meantime, I'm going to lock the conversation on this PR. I want to say this is _explicitly_ not in the interest of not hearing more discussion about this issue, but is simply attempting to move the conversation to the appropriate venue (namely, the terraform-providers/terraform-provider-google repository, ideally in one of the issues or PRs linked.) If you have further comments or input, I encourage you to send them there, where they'll be seen by the appropriate people (which is less likely if they get put in this thread.)

**Pull request closed without merging**
