### PR TITLE
[WIP] command: Add description auto-population for fmt

### PR DESCRIPTION
**Pull request by vancluever**
Ref: #15670. This is a complete example of the proposal, and is WIP right now but feel free to reply with feedback!

Personal checklist:

- [ ] Add full-file test and fix top-of-file comment insertion issues
- [ ] Ensure strings are properly escaped (example: double quotes)
- [ ] Wrap long descriptions with heredocs

-----

This commit adds support for the addition of description population to
fmt. This basically means that when the option is supplied, Terraform
can auto-populate the description fields in variables and outputs,
deriving data from leading comments instead.

Given this example:

```hcl
// The AWS region to deploy to.
//
// Note that one can put extra detail in another paragraph to provide
// more context in the code or other documentation tools and this text
// will not be added to the description.
variable "aws_region" {
  type    = "string"
  default = "ca-central-1"
}
```

Terraform will update the code to look like:

```hcl
// The AWS region to deploy to.
//
// Note that one can put extra detail in another paragraph to provide
// more context in the code or other documentation tools and this text
// will not be added to the description.
variable "aws_region" {
  description = "The AWS region to deploy to."
      
  type    = "string"
  default = "ca-central-1"
}
```

Note that as mentioned above, only the first paragraph of text is
copied. This is to keep the description field terse, saving any extra
context for just the code, or other documentation tools that work off of
parsing comments (like [segmentio/terraform-docs](https://github.com/segmentio/terraform-docs)).

This helps enforce some best practices in Terraform code (in this case,
ensuring that description fields are populated). Also, with the addition
of the filters feature in HCL and this update to Terraform, this also
helps pave the way for future enhancements to fmt (or maybe branching
off to something like terraform lint) that can carry out further
machine-mandated style enforcement.

### CODE REVIEW

**Comment by vancluever** [comment]
Adding a WIP to this, gave it a run on a full binary test and it looks like it's copying top-of-file comments in. Will add in some full-file tests to test against this case.

**Comment by vancluever** [comment]
Another note - need to make sure double quotes are properly escaped:

```
// The log level that should be used. Needs to be one of "TRACE", "DEBUG",
// "INFO", "WARN", and "ERR".
variable "log_level" {
  description = "The log level that should be used. Needs to be one of "TRACE", "DEBUG", "INFO", "WARN", and "ERR"."

  type    = "string"
  default = "INFO"
}
```

**Comment by vancluever** [comment]
And another improvement: break up long descriptions into heredocs (wrap on 78 chars).

**Comment by apparentlymart** [comment]
Hi @vancluever! This is an interesting idea. :thinking: 

It feels a little weird to me that this encourages repeating information. I would think that the description would be either in a comment _or_ in the description, rather than both.

I do like the idea of extracting comments from the source go-style, but I wonder if instead we should make this something separate (`terraform doc`?) that produces documentation separately, rather than simply duplicating the existing docs within the config.

**Comment by apparentlymart** [comment]
(I see I should've read #15670 first for the more detailed rationale! I actually agree with you that it's weird that we pack _certain_ comments into attributes while others live in comments. Maybe we could consider phasing out the `description` attributes on variables and outputs altogether and just rely on comments everywhere, though of course that's a rather extreme change not to be taken lightly!)

**Comment by vancluever** [comment]
Hey @apparentlymart!

Yeah, I think you have the idea - I figured that the essay I wrote in #15670 was better suited for an issue versus a PR. :wink: 

I personally would not say no to deprecating `description` as it does seem out of place for me. However, as you mentioned, it's a drastic change, and will probably affect a *lot* of people, so it would need to be done right. I almost think in that instance we could do what this is doing, but in reverse, having `fmt` move descriptions back to comments maybe for a major release cycle and then remove it as well. I'm divided on this being overkill, but I think it's important in instances like this to ensure that users are supported during changes like this, and I think this would make life easier for people that do make heavy use of `description`.

With the above said, I think there is a lot of potential in an upstream tool like `terraform doc`. In addition to what you mentioned in regards to documentation being sourced completely from comments again, I think in the absence of things like `description`, TF itself could possibly dogfood metadata sourced from `doc` in its place, possibly providing a metadata service of sorts to core and external tools as well.

It was the absence of both of these kinds of concepts that really led me to write this. I am definitely not a fan of the repeating data either. To me, this is kind of a compromise for issues that I was seeing with some of the modules I was working on where differences in style from one engineer to another (ie: me :wink: ) was causing drift in the way modules were actually written. So for me this is kind of a way to support both styles.

I think I might take this one back to brainstorming for a bit and maybe think about what an upstream `terraform doc` would look like and how it could be leveraged to supply what `description` is supplying right now. I'll WIP hashicorp/hcl#206 as well, because I don't necessarily want to move forward with that unless there is a specific use case for it when it gets merged (something should be actually consuming that feature).

**Comment by nbering** [comment]
I personally use the description field for external editing/authoring tools (simple things, nothing super fleshed-out). I'd personally be against ditching the description field, but I acknowledge that I am one voice.

**Comment by vancluever** [comment]
@nbering - sorry just saw this one now!

Just to make sure here - you are one voice, but you are still a voice :slightly_smiling_face: 

And a question - would you miss `description` if there was something that took its place, ie: if you were able to get that data from a doc tool instead? That's something that I would want to make sure of if this was actually to materialize.

**Comment by nbering** [comment]
@vancluever Ya, I'd still miss it if it was in a comment because I use the JSON configuration format (no comments). Actually, I'd miss it even more because there are no comments in JSON.

**Comment by vancluever** [comment]
Hey @nbering, got it. Yeah, as this mainly addresses HCL, and as you have mentioned, no way to document JSON readily exists, I understand completely how removing `description` would remove any recourse you have from sourcing documentation.

I just want to reassure you - no plan to remove `description` exists, and given your feedback (thank you by the way!), it's possible that in the current state of things it's highly unlikely, as I would imagine that you are by far not the only person using JSON to generate Terraform config. Further to that, any features as described in #15670 would, realistically, be at least a few minor releases out. So for now and the foreseeable future, it's business as usual.
 
There was another question that I wanted to ask that I think might be better asked in #15670 so I will put another update in there, so that we can move the conversation more to the proposal at this point instead of the PR.

Thank you very much again for your feedback!

**Comment by vancluever** [comment]
Hey all - closing this as I think I want to re-think my approach on this one. Will re-submit once I have a bit more of an idea of what this looks like or if I think it's still needed. Cheers!

**Pull request closed without merging**
