### PR TITLE
ci: fix copyright header check

### PR DESCRIPTION
**Pull request by radditude**
Our copyright header situation has gotten complicated. We're keeping the [plugin protocol files](https://github.com/hashicorp/terraform/pull/33699) licensed under MPL, and to work around this, we have separate `.copywrite.hcl` files in each subdirectory that has a license different than the main repo and will need to run the `copywrite` tool separately in each one to generate the correct headers - if only invoked from the repo root, the tool will ignore the nested `.copywrite.hcl` files.

For extra complication, the existing `go generate`-based check added in https://github.com/hashicorp/terraform/pull/33164 hasn't been running. Since the file includes a `//go:build tools` tag, it's excluded from the generate command by default unless we pass `-tags tools`.

We could fix this situation in one of two ways:

1. Stick with the existing `go generate`-based check, add new `copyright_headers.go` files in each directory with a `.copywrite.hcl` file, and update [the Makefile target](https://github.com/hashicorp/terraform/blob/8402b97baf0cb137854e9a46575c2c7ff71181cd/Makefile#L5) to run `go generate -tags tools ./...` so those generate directives are actually picked up.
2. Move the copyright header check into a separate Makefile target and use a script to run `copywrite headers` in each directory with a `.copywrite.hcl`.

I've gone with approach 2 in this PR, since it's marginally less boilerplate, but I'll gladly adjust if we'd prefer to stick with `go generate` instead!

## Target Release

N/A

### CODE REVIEW

**Comment by radditude** [comment]
An example failing build with missing copyright headers: https://github.com/hashicorp/terraform/actions/runs/5886049945/job/15963339225?pr=33702

**Comment by apparentlymart** [comment]
Thanks for working on this!

This seems like a lot of unfortunate extra fuss just for a few special files in one directory. :confounded: I wonder if it would be an acceptable compromise to keep the existing exclusion from these files in the top-level `.copywrite.hcl` and hand-write MPL license headers for these files. For the plugin protocol schema files we typically create new files of this sort just by copying the previous one to a new name and making minor modifications anyway, so the existing license comments in the previous one will come along for free as we do that.

I suppose that would make it hard to retroactively change the license on these files again later -- we'd have to do it manually -- but these files are already copied into a number of other codebases anyway, and this tool is not able to update those copies. I'd personally rather just accept the unlikely one-time cost of making some manual edits than add another non-standard oddity to our build process.

If you did this because someone in leadership told you it was necessary then of course please disregard. I'm trying to make a technically-motivated tradeoff, so I don't mean to try to override directives from legal/leadership.

**Comment by apparentlymart** [comment]
Thanks for working on this!

In the past we've preferred to use `go generate` because it's the standard way to deal with code generation in Go.

We did end up making a concession for `make protobuf` because the protobuf compiler isn't written in Go and so it doesn't fit neatly into the same strategy we've used for other tools, and because we change the protobuf schemas relatively infrequently and we tend to know we're doing it when we do it, so it's clear that we need to run that makefile target.

However, I'd prefer to keep as much as possible under `go generate` just because then it's easier to remember to just run `go generate ./...` and have all the right things happen, rather than having to remember various special cases for different situations.

The `go generate` thing was working when I originally wrote it, but I guess I broke it when I tried to consolidate the tool dependency and the generate line into the same file. If splitting it back out again to make it work with `go generate` _does_ make things gnarly then I'm not opposed to making a similar tradeoff as for protobuf, but I'd suggest to err on the side of `go generate` if the difference between the two is marginal.

**Review by apparentlymart — APPROVED** [review]
Belatedly realizing that I neglected to make my earlier comment an approval, because the stuff about go generate is just my opinion, and I trust whatever you think is best after considering it. This change seems correct so I have no objection to merging it if you conclude this is the better path.

**Comment by radditude** [comment]
That's a totally fair point! I've flipped this back to use the `go generate` approach, with the addition of telling our Makefile target not to ignore files with the `tools` build tag: https://github.com/hashicorp/terraform/blob/6531b376a880525c85ddc19195c5fc4843f1131a/Makefile#L5

Does that seem like a reasonable solution? It does mean that running regular `go generate ./...` won't work to update these headers, which could be confusing.

**Comment by apparentlymart** [comment]
I guess I'd understood what you described before as meaning that we'd put the `go:generate` lines back in a separate file (I think I'd originally used `generate.go`, but whatever) and then use the one with the "tools" constraint only to declare the dependency on the copywrite module. Then the normal `go generate ./...` (without special options) would work because the `go:generate` line would be in a file that _doesn't_ have any build constraints.

Go ignores build tags when deciding the dependencies of a module, so having the file only include the anonymous import of the package will serve to prevent `go mod tidy` from removing the dependency, without the need for any extra arguments. (The "tools" constraint in that case is there to avoid linking copywrite into our release executables, since we only need the dependency for `go run` purposes.)

**Comment by radditude** [comment]
Ah, I see! I misunderstood the intent of the build tags on my earlier read - that makes more sense. Fixed.

**Review by apparentlymart — APPROVED** [review]

**Pull request merged**
