### PR TITLE
reify the list values before validation

### PR DESCRIPTION
**Pull request by jbardin**
If the list was marked as computed, all values will be raw config
values. Fetch the individual keys from the config to get any known
values before validating.

#12892

### CODE REVIEW

**Comment by jbardin** [comment]
Hmm, that map in the test fixture schema looks little wonky (it was just there for good measure, not actually part of the bug). I'll fix that up.

**Comment by jbardin** [comment]
computed primitive values are skipped completely, so ValidateFunc should never have to deal with the raw interpolation strings or know about UnknownValue.

**Comment by mitchellh** [comment]
@jbardin An issue we ran into early then was the exists/not-exists check. For example: if an entire list is computed, will helper/schema properly see that some value may exist there in the future (and therefore pass validation)?

**Comment by jbardin** [comment]
@mitchellh, In this case the list is marked as computed (which is why we had all raw values), which would skip ValidateFunc for the list if it had one (I confirmed that). The individual elements are still validated independently. 

If you're referring to Resource.ExistsFunc, that's called from a different code path

**Comment by mitchellh** [comment]
That works great.

Yeah not ExistsFunc that is to check if a resource exists via state (so never computed values) I think.

**Pull request merged**
