### PR TITLE
[docs] Add missing word _not_

### PR DESCRIPTION
**Pull request by aviflax**
I could be wrong, but I think this word was intended to be in this sentence.

### CODE REVIEW

**Comment by grubernaut** [comment]
Hey @aviflax, this is actually correct. If a user is using remote state, this should not apply. This suggestion is only for users using local statefiles, and not using remote state backends. See: https://github.com/hashicorp/terraform/pull/12860#discussion_r106942266, for more. 

Being that this is the second time this has caused confusion, however, would gladly accept some clarification for this.

**Comment by awwright** [comment]
Why would I want to commit any state to version control? The whole point of using Terraform is so I can deploy and apply the same design to multiple places, including one-off test environments.

Source control repositories can be forked and branched, leading a team member on one branch to "see" a different tfstate than another team member. If multiple people need to collaborate on a single state, you should use a [backend](https://www.terraform.io/docs/state/remote.html).

If keeping track of state change history is desirable, then then we should program a Git server (or similar system) as a remote state backend, so that branching patterns are managed and other potential problems are mitigated. But the state should not go in the same repository as the configuration.

**Comment by mitchellh** [comment]
@awwright You're right and that's pretty much the point. If you're using local state, you're not taking advantage of any sort of remote state syncing/storage/locking and therefore it is quite dangerous in a team environment. However, that state is very important to store and therefore we do recommend you put it in version control, with previously mentioned caveats noted.

It is extremely dangerous in a team environment and you can get conflicts if multiple people perform operations at the same time. I think we can do better by making this clear in the docs. However, the word is still correct here, just unclear perhaps. :)

**Comment by apparentlymart** [comment]
Hi @aviflax! Sorry for the long silence here.

The text you edited here has been revised in the mean time. (now on the "Workspaces" page rather than the "Environments" page, since that feature was renamed)

As Mitchell noted, if you're using local state files then you need to retain them _somehow_, and version control is one way to do that. However, you're right that using version control as a substitute for remote state is not a best practice and so the text now describes this as one possible approach, but affirms that remote state is the best solution:

> For local state, Terraform stores the workspace states in a directory called `terraform.tfstate.d`. This directory should be be treated similarly to local-only `terraform.tfstate`; some teams commit these files to version control, although using a remote backend instead is recommended when there are multiple collaborators.

**Pull request closed without merging**
