### PR TITLE
random_pet resource

### PR DESCRIPTION
**Pull request by jtopjian**
Just a quick, simple random name generator. If, for some reason, this isn't worthwhile to add, I'd be happy to make it a dedicated plugin. :)

### CODE REVIEW

**Comment by stack72** [comment]
Looks like a useful addition :)

```
% make testacc TEST=./builtin/providers/random
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/03/27 12:49:40 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/random -v  -timeout 120m
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccResourceID
--- PASS: TestAccResourceID (0.04s)
=== RUN   TestAccResourcePet_basic
--- PASS: TestAccResourcePet_basic (0.02s)
=== RUN   TestAccResourcePet_length
--- PASS: TestAccResourcePet_length (0.04s)
=== RUN   TestAccResourcePet_prefix
--- PASS: TestAccResourcePet_prefix (0.03s)
=== RUN   TestAccResourcePet_separator
--- PASS: TestAccResourcePet_separator (0.02s)
=== RUN   TestAccResourceShuffle
--- PASS: TestAccResourceShuffle (0.04s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/random	0.203s
```

**Comment by SydOps** [comment]
@jtopjian 

If I add `count = 5`, what will happen? still get the random name for each instance?

**Comment by jtopjian** [comment]
@SydOps You _should_. It should act like the other random providers which support `count`.

**Comment by SydOps** [comment]
@jtopjian 

Seems not. 

```
provider "aws" {
  region = "us-west-2"
}

data "aws_ami" "ubuntu" {
  most_recent = true

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"] # Canonical
}

resource "aws_instance" "web" {
  count = 3
  ami           = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.micro"

  tags {
    Name =  "web-server-${random_pet.server.id}"
  }
}

resource "random_pet" "server" {
  keepers = {
    # Generate a new pet name each time we switch to a new AMI id
    ami_id = "${data.aws_ami.ubuntu.id}"
  }
}

output "key" {
  value ="${random_pet.server.id}"
}
```

All ec2 instances have same name. Can we have different names for each instance? Or this is not your design.

**Comment by jtopjian** [comment]
@SydOps This does indeed work with `count` like the other resources. You just need to use the `element` function when using `count` just as you would with any other reference to a multi-count resource. Check the docs on `count` and `element` :)

**Pull request merged**
