### PR TITLE
Adding option_settings to aws_db_option_group

### PR DESCRIPTION
**Pull request by bigkraig**
Allows configuring settings for options

### CODE REVIEW

**Comment by stack72** [comment]
Hi @bigkraig 

This looks good, but when I ran the tests I got the following:

```
make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSDBOptionGroup' 2>~/tf.log
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /vendor/)
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSDBOptionGroup -timeout 120m
=== RUN   TestAccAWSDBOptionGroup_basic
--- PASS: TestAccAWSDBOptionGroup_basic (22.02s)
=== RUN   TestAccAWSDBOptionGroup_OptionSettings
--- FAIL: TestAccAWSDBOptionGroup_OptionSettings (18.76s)
	testing.go:172: Step 0 error: Check failed: Check 4/4 error: aws_db_option_group.bar: Attribute 'option.2422743510.option_settings.1350509764.value' expected "UTC", got ""
=== RUN   TestAccAWSDBOptionGroup_sqlServerOptionsUpdate
--- PASS: TestAccAWSDBOptionGroup_sqlServerOptionsUpdate (36.95s)
=== RUN   TestAccAWSDBOptionGroup_multipleOptions
--- PASS: TestAccAWSDBOptionGroup_multipleOptions (21.17s)
FAIL
exit status 1
FAIL	github.com/hashicorp/terraform/builtin/providers/aws	98.919s
```

Can you have a look at this and see what you think the issue may be? I am running these tests against the newly merged master branch

P.

**Comment by bigkraig** [comment]
@stack72 yeah, it's the numbers in the resource name, they change. I was able to run through them by running the test with debug logging, see what the numbers were, adjust and run again. It's pretty lame.

If there is a better way to do it I will make the change, but I got this from the ELB tests: https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_elb_test.go#L37

**Comment by stack72** [comment]
Ah its just the hash number :( I usually have to run the test twice too and check the state for the hash values as well

**Comment by bigkraig** [comment]
@stack72 yeah its a bummer. Does that mean this is good to merge?

**Comment by stack72** [comment]
I can fix the test and merge when it's done

P

**Comment by stack72** [comment]
Hi @bigkraig 

Just a FYI, this is now working. All tests are green :) Thanks for the work here. Will merge now

P.

```
make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSDBOptionGroup' 2>~/tf.log
==> Checking that code complies with gofmt requirements...
/Users/stacko/Code/go/bin/stringer
go generate $(go list ./... | grep -v /vendor/)
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSDBOptionGroup -timeout 120m
=== RUN   TestAccAWSDBOptionGroup_basic
--- PASS: TestAccAWSDBOptionGroup_basic (41.78s)
=== RUN   TestAccAWSDBOptionGroup_OptionSettings
--- PASS: TestAccAWSDBOptionGroup_OptionSettings (51.68s)
=== RUN   TestAccAWSDBOptionGroup_sqlServerOptionsUpdate
--- PASS: TestAccAWSDBOptionGroup_sqlServerOptionsUpdate (43.77s)
=== RUN   TestAccAWSDBOptionGroup_multipleOptions
--- PASS: TestAccAWSDBOptionGroup_multipleOptions (47.45s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	184.703s
```

**Pull request merged**
