### PR TITLE
Closes #12376 - implements aws_instances data source

### LINKED ISSUE #12376: aws_instances data source
I would find it useful to have an `aws_instances` data source that would be able to execute a filter and return the instance IDs of multiple instances. Presently the `aws_instance` data source says:

```
NOTE: If more or less than a single match is returned by the search, Terraform will fail. Ensure that your search is specific enough to return a single Instance ID only.
```

My use-case is that have a Terraform repo that has some common shared infrastructure (like HTTP hosts that hand-out 301s for whatever URL they're given) and I want to attach that to multiple AWS ALBs that are in separate Terraform repos (per application). I would like to do a search on those instances based on tags and be able to use the result list in an `aws_alb_target_group_attachment`. I'd really like to be able to have an `aws_alb_target_group` data source, but this is an acceptable (and useful in more ways) alternative.

Right now, the only real way I can get those instances is to hardcode the instance IDs in individual `aws_instance` data sources. I can work out some outputs where the hosts are created, and work them into being imported into the application Terraforms but this additional layer increases complexity and can become stale or out-of-sync if not done correctly. It's better just to hardcode the IDs for now.

### PR DESCRIPTION
**Pull request by artburkart**
I wanted to work through the code once more to make sure I did it correctly. Once my tests pass, I'll close my other PR for #12376 in favor of this one. It implements an `aws_instances` resource with an attribute `instances` which is essentially a list of [`aws_instance`](https://www.terraform.io/docs/providers/aws/d/instance.html) data sources minus the search arguments, since they're located at the root of the `aws_instances` data source.

As far as I know, this code works and shouldn't introduce any bugs. Any feedback is appreciated.

EDIT:
> The changes made to builtin/providers/postgresql/resource_postgresql_database.go are a result of running `make fmt` on the repo. I can revert it back if it's an unwanted change.

Actually, the `make fmt` caused the tests to fail... unsure why

### CODE REVIEW

**Comment by artburkart** [comment]
If you want to try it out, build the code and use this example script:

```hcl
data "aws_instances" "web-group" {
  instance_ids = ["i-aaaaaaaaaaaaaaaa", "i-bbbbbbbbbbbbbbbb"]
}

data "template_file" "web-group" {
    template = "$${id1}\n$${id2}\n$${instance_ids}"

    vars {
        id1 = "${data.aws_instances.web-group.instances.0.id}"
        id2 = "${data.aws_instances.web-group.instances.1.id}"
        instance_ids = "${data.aws_instances.web-group.id}"
    }
}

resource "null_resource" "web-group" {
  triggers {
    template = "${data.template_file.web-group.rendered}"
  }

  provisioner "local-exec" {
    command = "printf \"${data.template_file.web-group.rendered}\n\" > instances.txt"
  }
}
```

**Comment by artburkart** [comment]
Hey @stack72, I moved this PR over here.

**Comment by artburkart** [comment]
Is there something I need to do to get this looked at?

**Comment by artburkart** [comment]
Hi, 

I noticed the new [`aws_ami_ids` data source](https://github.com/hashicorp/terraform/pull/13844) had a PR made about a month ago and was merged in a day. Should I have made an `aws_instance_ids` data source instead of `aws_instances`? Would that help get this PR merged sooner?

Cheers

**Comment by stack72** [comment]
Hi @artburkart 

Sorry for the silence here - as you can see, the repo is moving so fast so sometimes we lose PRs in the surge

I am reviewing this now

Paul

**Comment by cemo** [comment]
@stack72 what is the status of this PR?

**Comment by cemo** [comment]
@stack72 any change to look this PR? This is unfortunately required on our side.

**Comment by artburkart** [comment]
@cemo - It probably won't get looked at until I sync up `provider.go` with the master branch, now that it's fallen out of sync. Realistically, this PR should probably be closed now, since `aws_ami_ids` was added after I wrote this code and I think that might be the convention now.

Oh wells, if you need it, I'll maybe try making a new PR for `aws_instance_ids` and see if that one will get looked at.

**Comment by stack72** [comment]
Hi @artburkart 

this PR is still very relevant - *all* of the team are crazy busy in preparation for the 0.10 release. We are going to release details that in the next few days

You will be able to see the amount of work involved in that release

Paul

**Comment by artburkart** [comment]
Now that the terraform format has changed, should I try to move this code over to the terraform providers repo? Or should I just close, since there doesn't seem to be much interest?

**Comment by radeksimko** [comment]
Hey @artburkart 
we had an internal discussion about usefulness of this data source and the conclusion is that we're happy to accept this contribution as long as there's a clear disclaimer in the docs which discourages people from using it to query autoscaled (and generally non-static, ephemeral) instances.

e.g. something like this

```
~> **Note:** It is strongly discouraged to use this data source for querying ephemeral instances (e.g. managed via autoscaling group), as the output may change at any time and you'd need to re-run `apply` every time an instance comes up or dies.
```

The `~>` will turn the paragraph into yellow box, which makes it more visible.

While I'm not a huge fan of pet instances I understand there are valid use cases in the wild and we should support it.

So yes, I'd appreciate if you can move your PR over to https://github.com/terraform-providers/terraform-provider-aws and then close this one here.

Thanks!

**Comment by artburkart** [comment]
It's funny because I was literally working on this last night, migrating it over to the other repo, except as an 'aws_instance_ids` data source. I'm still working out the acceptance tests and the vendoring differences because I just got the `hashcode.Strings` function added to terraform core last week.

To your note about pets, I don't know if I had even considered its use for them. I thought it would be useful for people who use tools outside of terraform. This would make full migration to terraform easier because you could bite off smaller chunks of an automation project. Another example use case is I've set up autoscaling events that trigger the execution of a terraform repo whenever an instance is launched. That way I could do something like attach an eip, which, in my use case, is the switch for the instance to start taking traffic. Maybe I'm doing it wrong? In lieu of terraform, I've been using the aws cli.

**Comment by radeksimko** [comment]
> except as an aws_instance_ids data source

I think that exposing IPs of instances may be useful, so I'd personally prefer the original scope. We don't need to expose everything, but I can see both IDs and IPs being useful.

> Another example use case is I've set up autoscaling events that trigger the execution of a terraform repo whenever an instance is launched. That way I could do something like attach an eip, which, in my use case, is the switch for the instance to start taking traffic. Maybe I'm doing it wrong?

Admittedly that doesn't sound right 😅  Mainly because if you have any kind of system which just runs `apply` blindly you miss the `plan` part which may be critical - e.g. someone _intentionally_ scaled something manually or changed something while dealing with an outage and Terraform is going to put it back without you ever noticing and it may do so at the most inconvenient time, e.g. when you're sleeping and can't intervene.

If you're aware of these risks and you're willing to accept them - or somehow prevent bad things from happening, then that's aok.

We cannot assume everyone knows all the consequences though, hence we should add the note as mentioned.

**Comment by apparentlymart** [comment]
Hello @artburkart, and thanks for working on this!

As part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it.

If you or someone else has the time and motivation to apply the same changes (modulo the discussion above) to [the `aws` provider repository](https://github.com/terraform-providers/terraform-provider-aws) and open a new PR there, the maintainers of that provider should be able to review and merge it.

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Comment by artburkart** [comment]
No worries! I never really needed it, doesn't seem _that_ important :+1:, and maybe it's not even desired.

**Pull request closed without merging**
