### PR TITLE
GitHub state backend

### PR DESCRIPTION
**Pull request by hartzell**
[Edited 20180513 to describe current state of affairs]

Stores remote state in a file in a github repository.

- The owner and repository names are required.
- A token that provides access to the repo is required.  If one is not
  supplied in the config then the GITHUB_TOKEN environment variable is checked.
- The path to the state file is configurable, default is `terraform.tfstate`.
- Locking is supported, the path to the lock file is configurable, default is `terraform.tfstate.lock`.
- The branch can be specified (it must already exist).
- The base URL of the API can be specified (GitHub Enterprise support).

This commit also adds another round of put and get to the testClient function in remote_test.go.  The GitHub API behaves differently when creating a file and updating an existing one and I needed to test both cases.

### Questions:

- Is the change to state/remote/remote_test.go (see above) ok?
- Is there any way to test w/out hitting a real github?
  - What is a good way to handle GitHub config info in the tests?

**Much knowledge, and a bit of code was borrowed from the GitHub provider.  Thanks to its authors!**

### CODE REVIEW

**Comment by hartzell** [comment]
> The documentation is still old-school, what's the plan for updating the website vis a vis the new world of backends?

I've found #11976, I'll review it and update my docs bit.

**Comment by hartzell** [comment]
@paddycarver -- I'm using this in a new gig.  I've brought this up to date and would appreciate some feedback (on the implementation and if/how it might get merged).  **THANKS!**

**Comment by hartzell** [comment]
@radeksimko -- noticed your activity on the GitHub provider.  Wondering if you have any feedback for/about a GitHub backend in general or this implementation.  **Thanks!**

**Comment by teamterraform** [comment]
We are sorry to have let this PR sit for so long. Since this PR targets a part of the code base that is no longer used to manage remote state, we will close this PR. If this is a feature you are still interested in, please open a Github issue using the Feature Request template so we can discuss the design.

Thank you!

**Pull request closed without merging**
