### PR TITLE
Automated cleanup of dead code and extra type declarations

### PR DESCRIPTION
**Pull request by jbardin**
Remove dead, unexported identifiers, and run `gofmt -s`.
This doesn't yet attempt to check for unused exported identifiers.

### CODE REVIEW

**Comment by jbardin** [comment]
This was a mostly automated cleanup of unused code. I've run into enough code recently where I've had to dig into the history to know if it's used, or should be used, that I thought it's time to start cleaning things out. There's a few values that are left, like the *Invalid iota placeholder, but this is pretty thorough otherwise.

Time permitting, I'll follow up with an exported identifier cleanup, but that takes a little effort to make sure we're not removing stuff we may want to keep.

**Comment by apparentlymart** [comment]
I feel a little nervous about doing something like this _en masse_ across the entire codebase... usually I prefer to be more conservative and clean things up when I'm "in the neighborhood" so that I'm already (presumably) testing the functionality in question, and so that there aren't weird cross-cutting commits in the history that can make `git blame` harder to use, and cause spurious merge conflicts for open PRs.

I feel a bit ambivalent here, then... all of these cleanups look good but I worry about the cost of resolving conflicts in numerous open PRs. What do you think about instead just making a point of running whatever automated tool you used to find the unused symbols here in a targeted way each time we're working on a big refactor or other large change to a component? That way we'd likely be paying the merge conflict cost anyway (due to the intentional refactoring).

I don't feel super-strongly about this... you mentioned that this unused code had been creating a lot of development overhead for you, which may outweigh the (hard to measure) PR-merge-conflict cost.

**Comment by jbardin** [comment]
That understandable, I decided to just run through these now, since I've been saying we'll "do it later" for a very long time. I did the removals mostly by package, so that in the face of a major conflict we could easily revert that subset.  Putting it off in hopes of a coinciding large refactor seems likely to not happen for most of these files. As for development friction, I think unused exported identifiers are actually the larger problem which needs to be tackled more carefully. 

The most likely area of conflicts would be the `gofmt -s` change, since it's reformats large test files. Though I'm note sure if there's a way to schedule a better time, since there's no convenient way to reformat large files piece by piece. We could feasibly never use `gofmt -s` and just requiring that you disable it in your editor for terraform (I end up selectively enabling and disabling it, and sometimes accidentally writing out a huge diff.)

**Comment by jbardin** [comment]
closing to handle in smaller chunks

**Pull request closed without merging**
