### PR TITLE
website: in functions sidebar, default lists to collapsed

### PR DESCRIPTION
**Pull request by nfagerlund**
Find-in-page is still supported with the 'expand/collapse all' control. And until you need cmd-F, this makes it much easier to tell where you are and what's nearby.

This uses new features that just went into terraform.io on Friday. 

Screen Shot 2019-04-05 at 6 23 49 PM

### CODE REVIEW

**Comment by apparentlymart** [comment]
This seems nice for when you are on a specific function page, to emphasize the section you're already in, and our "Related functions" links in the pages themselves also provide an alternative way to find related functions that might be in a different section, so this looks nice to me.

Will the navbar begin fully-expanded when the reader is on [the functions index page](https://www.terraform.io/docs/configuration/functions.html)? I usually immediately find-in-page when I land there, so at least for my usage pattern I'd find it convenient to have the full list available at first and then only collapse to a single section once I've chosen a single function from the list already.

**Comment by nfagerlund** [comment]
@apparentlymart As of this PR, no, it doesn't default to fully-open on the index page. I agree starting with the full list is sometimes fastest, and there's a few ways to accommodate that:

- Leave it like this -- you can get the full list by clicking the "expand all" link. An extra click for that use case, balanced against making other use cases ("I need to munge a string, and can't remember what's available") much more tractable. (I prefer this; it seems like an OK balance.)
- Do a mildly goofy hack to pop the nav open on the index page. (There's a few possible ways, all silly but basically fine.) Faster for grepping the list, but gotta click "expand all" twice if you would rather browse a single category. 
- Duplicate the full list onto the index page, so you have the default-closed sidenav AND the full list visible at the same time. Actually that's probably ideal, but it needs a little extra hackery to get the lists from a single source if we want to be totally sure they don't fall out of sync.

**Comment by apparentlymart** [comment]
Given that all of this is small fixes to tide us over until the full revamp of the site design and navigation, I'm happy to compromise on the details to make things better on average, so I'm certainly not suggesting that we block merging this to pre-expand the functions page.

I wouldn't be surprised if we get some negative feedback along these lines in sections where people already have keyboard-oriented muscle memory (particularly if there's no obvious, easy keyboard-driven trigger for "expand-all", so the reader would need to switch back to the mouse after realizing their muscle memory is broken) but I expect that'll die down after the initial adjustment and we can see about tweaking the behavior again in the later set of big changes, either by expanding by default or by doing something even better, such as an real contextual search feature.

**Comment by nfagerlund** [comment]
@apparentlymart I'll go ahead and merge for now and we'll see, but I DID just test a hack to keep it open on the index page, and it totally works. (Just put `<a href="/docs/configuration/functions.html" style="display: none" />` directly inside each `<ul>` — doesn't affect the layout, isn't clickable, DOES affect the check for whether the section should be open and returns positive if you're on the index.) So that's an option if y'all decide you want that after the filters PR goes live.

**Pull request merged**
