### PR TITLE
rancher_stack: Only read compose when catalog_id is empty

### PR DESCRIPTION
**Pull request by raphink**

### CODE REVIEW

**Comment by mcanevet** [comment]
@stack72 please merge this before the release of 0.8.6 as https://github.com/hashicorp/terraform/pull/11550 broke this

**Comment by raphink** [comment]
:warning: Please don't merge right away, I'm trying to figure out some issue with this.

**Comment by raphink** [comment]
OK so this patch works, but fa656429373d4bdfe3894d1f5fd85ff2bc225e4d broke imports apparently. /cc @johnrengelman

**Comment by johnrengelman** [comment]
LGTM

**Pull request merged**
