### PR TITLE
provider/aws: Fixes issue where an update for an `aws_elastic_beanstalk_environment ` resource would ignore the `wait_for_ready_timeout` option.

### PR DESCRIPTION
**Pull request by dharrisio**
This addresses issue brought up in #6242 where the `wait_for_ready_timeout` option is ignored, originally done in #6342

Tests
```
=== RUN   TestAccAWSBeanstalkEnv_basic
--- PASS: TestAccAWSBeanstalkEnv_basic (376.01s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/aws    376.019s
```

### CODE REVIEW

**Comment by stack72** [comment]
Another nice addition @dharrisio. Thanks for this

LGTM pending Travis build

**Comment by dharrisio** [comment]
From looking at the Travis failure, it doesn't look like this was related to the aws provider. From the logs it looks like it was 

`FAIL	github.com/hashicorp/terraform/command`

Any ideas here @stack72?

**Comment by stack72** [comment]
@dharrisio, this isn't your change. This is being worked on ATM by @phinze. We will trigger another build soon

**Comment by phinze** [comment]
@dharrisio if you rebase on master that failure should go away - sorry for the hiccup! 😁

**Comment by dharrisio** [comment]
@phinze No problem! Rebasing and pushing in a few seconds here.

**Pull request merged**
