### PR TITLE
providers/aws: support for lifecycle hooks at ASG creation

### PR DESCRIPTION
**Pull request by pcarrier**
Closes hashicorp/terraform#5619.

### CODE REVIEW

**Comment by vincer** [comment]
Thanks, just ran into this today! Hope this gets merged soon!

**Comment by glasser** [comment]
Is there anything we can do to help this get merged?

**Comment by jen20** [comment]
Hi @pcarrier and @glasser! Sorry this has taken so long to get round to reviewing. Initially this looks good to me, but we have merge conflicts (probably from ALB support though unverified), and it would be good to see an acceptance test around the new functionality. If you're able to take a look at that (particularly adding a test) we should be able to get this merged in fairly quickly now. Thanks for the contribution!

**Comment by glasser** [comment]
@jen20 Great to hear! I rebased it and added an acceptance test.  Added a small refactor of a related test to help with that.

**Comment by glasser** [comment]
@jen20 Resolved another round of merge conflicts. Hoping you can merge this soon!

**Comment by stack72** [comment]
Hi @pcarrier 

I have pulled this locally and manually merged it to resolve the merge conflict :)

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSAutoScalingGroup_'                                                                                                             2 ↵ ═ ✚
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/09/04 01:28:07 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSAutoScalingGroup_ -timeout 120m
=== RUN   TestAccAWSAutoScalingGroup_importBasic
--- PASS: TestAccAWSAutoScalingGroup_importBasic (197.26s)
=== RUN   TestAccAWSAutoScalingGroup_basic
--- PASS: TestAccAWSAutoScalingGroup_basic (229.21s)
=== RUN   TestAccAWSAutoScalingGroup_autoGeneratedName
--- PASS: TestAccAWSAutoScalingGroup_autoGeneratedName (54.24s)
=== RUN   TestAccAWSAutoScalingGroup_terminationPolicies
--- PASS: TestAccAWSAutoScalingGroup_terminationPolicies (72.85s)
=== RUN   TestAccAWSAutoScalingGroup_tags
--- PASS: TestAccAWSAutoScalingGroup_tags (259.24s)
=== RUN   TestAccAWSAutoScalingGroup_VpcUpdates
--- PASS: TestAccAWSAutoScalingGroup_VpcUpdates (108.40s)
=== RUN   TestAccAWSAutoScalingGroup_WithLoadBalancer
--- PASS: TestAccAWSAutoScalingGroup_WithLoadBalancer (468.16s)
=== RUN   TestAccAWSAutoScalingGroup_withPlacementGroup
--- PASS: TestAccAWSAutoScalingGroup_withPlacementGroup (154.89s)
=== RUN   TestAccAWSAutoScalingGroup_enablingMetrics
--- PASS: TestAccAWSAutoScalingGroup_enablingMetrics (269.78s)
=== RUN   TestAccAWSAutoScalingGroup_withMetrics
--- PASS: TestAccAWSAutoScalingGroup_withMetrics (45.08s)
=== RUN   TestAccAWSAutoScalingGroup_ALB_TargetGroups
--- PASS: TestAccAWSAutoScalingGroup_ALB_TargetGroups (157.16s)
=== RUN   TestAccAWSAutoScalingGroup_initialLifecycleHook
--- PASS: TestAccAWSAutoScalingGroup_initialLifecycleHook (254.66s)
PASS
ok     	github.com/hashicorp/terraform/builtin/providers/aws   	2270.971s
```

Thanks for all the work here

Paul

**Pull request merged**
