### PR TITLE
Added storage_profile support.

### PR DESCRIPTION
**Pull request by dn1s**
Added vm description option.
Changed api call which creates vapp + vm from instantiate_template to
compose vapp.
Removed network_href variable which is not of use anymore since the
api call changed.
Bumped govcloudair version again. I refactored my last commits.

Was tested with v0.9.5.

### CODE REVIEW

**Comment by dn1s** [comment]
Opened https://github.com/vmware/govcloudair/pull/39

**Comment by dn1s** [comment]
@bobbydeveaux can you please test the provider against your lab like you did in the last bump for govcloudair?
@tombuildsstuff It's basically working. But from another pull request I know that you guys want to see that the provider unit tests pass so we have to wait for @bobbydeveaux to test it if he's so kind.

**Comment by bobbydeveaux** [comment]
Sorry @dn1s  - didn't see this. Are you creating this as a new PR in the new provider?

**Comment by bobbydeveaux** [comment]
if it helps, you can take the patch of this and apply to a new branch on the new provider:

patch:
https://patch-diff.githubusercontent.com/raw/hashicorp/terraform/pull/13935.patch

**Comment by bobbydeveaux** [comment]
Moved to https://github.com/terraform-providers/terraform-provider-vcd/pull/23

**Pull request closed without merging**
