### PR TITLE
Add staticcheck.conf to reduce unactionable noise in IDEs

### PR DESCRIPTION
**Pull request by nfagerlund**
Turns out go-staticcheck will respect a config file and merge configs across subtrees of packages.

- [Staticcheck configuration methods](https://staticcheck.io/docs/configuration)
- [List of config options](https://staticcheck.io/docs/configuration/options/)

Since we already specify a list of staticcheck rules to ignore in the scripts/staticcheck.sh wrapper script, this hoists those preferences up to the top of the package tree, so they also affect the staticcheck integration in editors like VSCode. This avoids unnecessary yellow-squiggles for capitalized error messages, and makes integrated linting much more useful.

## The thing I'm trying to make it shut up about

image

## Target Release

1.7.x

## Draft CHANGELOG entry

N/A; this has no runtime effect on Terraform.

### CODE REVIEW

**Review by alisdair — CHANGES_REQUESTED** [review]
This is cool!

I think we can remove the `-checks` argument from the script, so that we don't have two copies of these settings which may diverge. That seems to work locally for me, at least.

If it works in CI too, perhaps we should also add a comment to that script pointing at this config file for future people.

**Comment by nfagerlund** [comment]
I was wondering if I could get away with that! :D I'll amend and we'll see what CI does with it

**Comment by nfagerlund** [comment]
Nice, looks like just setting it globally works in CI too.

**Review by alisdair — APPROVED** [review]
Nice, thanks!

**Pull request merged**
