### PR TITLE
Add "Edit this page" link everywhere except /

### PR DESCRIPTION
**Pull request by handlers**
This PR adds an 'edit this page' link everywhere on the website except the homepage.

Note that I've run `bundle update middleman-hashicorp` to bring in the changes from [this update](https://github.com/hashicorp/middleman-hashicorp/commit/fc131cfce2a1d5c8671812d9844a944ebb4bd92f) to that gem.

Also note I've added a Makefile, following the [pattern in this PR](https://github.com/mitchellh/packer/pull/2396/files).

### CODE REVIEW

**Comment by handlers** [comment]
Cleaning up some spacing issues

**Comment by stack72** [comment]
@handlers What is the usecase for this PR? Is this trying to get people to help update the documentation? An "Edit this Page" link feels very wiki-like but all it does is open the github page

**Comment by handlers** [comment]
@stack72 yeah, exactly. The idea is to help site users access the source docs/website copy, so that they can directly submit a pull request to, e.g., fix a typo (as opposed to having them spend time searching around the site for info on who to report typos to).

**Comment by apparentlymart** [comment]
Nice idea! I'm not too experienced with all the website infrastructure but to my naive eyes it looks like a reasonable change.

Nit-pick: the diff in github shows some spots where the whitespace remains a bit wonky in your changeset. In particular see how weird the Makefile diff looks and how the _footer.erb lines are differently-indented than what surrounds them. In the latter case I guess the surrounding lines are using tabs while the new lines are using spaces.

**Comment by handlers** [comment]
Thanks, @apparentlymart! Your nitpick is totally valid and should be fixed.

**Comment by josephholsten** [comment]
LGTM

**Comment by phinze** [comment]
LGTM!

**Pull request merged**
