### PR TITLE
provider/openstack: Add fixed ips to openstack ports

### PR DESCRIPTION
**Pull request by Fodoj**

### CODE REVIEW

**Comment by jtopjian** [comment]
Thank you very much for this! I don't use ports, so the initial commit was going off of assumptions and devstack. Perfect timing so it gets cleaned up for the next release. 

I'll review all commits in detail later today.

**Comment by jtopjian** [comment]
Everything else looks good!

I made the appropriate changes to the subnets locally and the tests pass, so it's good to go after that. Great addition - thank you!

**Comment by Fodoj** [comment]
@jtopjian do you mean `${openstack_networking_subnet_v2.foo.id}` change? Is that enough to fix tests?

**Comment by jtopjian** [comment]
Yeah, for the modification in `resource_openstack_networking_network_v2_tests.go` and in the documentation, that's all. 

For `resource_openstack_networking_port_v2_tests.go`, a few changes are needed:

1. Import the subnet package
2. Declare a subnet variable
3. Add a subnet block to the test
4. Change the hard-coded subnet ID to a variable reference
5. Add a `testAccCheckNetworkingV2SubnetExists` alongside the other resources in that test.

Let me know if you need a hand :smile:

**Comment by Fodoj** [comment]
@jtopjian thanks for your review! Changes to tests are pushed.

**Comment by jtopjian** [comment]
Looks good!

**Pull request merged**
