### PR TITLE
Azure remote state encrypted by Key Vault

### PR DESCRIPTION
**Pull request by allantargino**
When working with Terraform, the `.tfstate` file written in plain text is often a secure concern from many users, since secrets and keys are often outputted from many templates. The problem of storing secrets in plain text files is heavily discussed at #516, #9556

Using [Terraform's remote state backed by Azure Blob Storage](https://www.terraform.io/docs/backends/types/azurerm.html) is usually a good option to handle the local state data only in memory, letting the state to be persisted in a safe place. On the other side, even data being backed remotely, the administrator must configure explicit RBAC rules to protect this file (which it should be only the service principal and few users having the right and need to read it).

As a security addon, we can perform client-side encryption on the state content, increasing the security level. Not only it properly masquerades the content, but also increases integrity by preventing partial corruption from manual user edition. 

This PR implements the functionally of performing client-side encryption using AES-256. Encryption key is wrapped with AES 1.5 using Azure Key Vault REST APIs of [Wrap Key](https://docs.microsoft.com/en-us/rest/api/keyvault/wrapkey/wrapkey) and [Unwrap Key](https://docs.microsoft.com/en-us/rest/api/keyvault/unwrapkey/unwrapkey). 

This also includes:
- [x] unit tests
- [x] integration tests
- [x] docs

> This functionally does not change the current remote state behavior nor breaks the current API. All current mechanisms of locking and state persistence/retrieval remains the same.

To use this feature, you should provide a `key_vault_key_identifier` in `azurerm backend` definition, which is just a versioned Key Vault key URI with `Wrap Key`, `Unwrap Key` and `Get` permissions:
```hcl
terraform {
  backend "azurerm" {
    storage_account_name     = "abcd1234"
    container_name           = "tfstate"
    key                      = "prod.terraform.tfstate"
    key_vault_key_identifier = "https://keyvaultname.vault.azure.net/keys/myKey/99d67321dd9841af859129cd5551a871"
  }
}
```

This is how the blob state looks like, with `encrypted_state` representing the terraform state encrypted by AES-256:
```json
{
    "key_vault_key": {
        "vault_url": "https://keyvaultname.vault.azure.net",
        "key_name": "myKey",
        "key_version": "99d67321dd9841af859129cd5551a871"
    },
    "encryption_key": {
        "algorithm": "AES-256",
        "mode": "GCM",
        "key": "LFl5mEj628bXdCtkylw_G0LJMX....QKmZP0wIjd141TTVvYTUw",
        "nonce": "xnzyJ0bpla9aJTZ5"
    },
    "encrypted_state": "2Jmok4e5DgnXEodFXBC...LZS5K3NKgZhDRPFQ=="
}
```

It should allow us to evolve that schema and support additional features (other algorithms, additional validations, etc).

> Note that if the user/principal has the right permissions, imperative commands against the state can still be used. (such as `terraform state pull`)

### CODE REVIEW

**Comment by allantargino** [comment]
Hi @mildwonkey, @katbyte and @tombuildsstuff,
Were you able to take a look at this PR? 
Thank you!

**Comment by Krueladin** [comment]
This is a pretty cool feature! Would love to see this hit one of the next releases!

**Comment by JamesDLD** [comment]
Amazing feature!

**Comment by allantargino** [comment]
Hi @tombuildsstuff, would love some review from you. Thanks!

**Comment by allantargino** [comment]
Hi @tombuildsstuff , any thoughts/review on this old PR?

**Comment by chakri-nelluri** [comment]
@tombuildsstuff, AWS & GCP already have support securely store the state. Are we looking for anything more in the PR?

**Comment by chakri-nelluri** [comment]
@apparentlymart @jbardin This is pending for more than an year. Please help. Thanks.

**Comment by chakri-nelluri** [comment]
Hi @allantargino , PTAL when you get a chance.

**Comment by allantargino** [comment]
I will fix the conflicts @chakri-nelluri and @tombuildsstuff, thanks!

**Comment by allantargino** [comment]
Hi @tombuildsstuff and @chakri-nelluri, I fixed the conflicts and it should be ready now.

**Comment by allantargino** [comment]
Seems `ci/circleci: go-test` is failing due to `az cli` not be on the build machine.

**Comment by allantargino** [comment]
I removed `TestBackendConfig` test, which only instantiates the backend. It was failing due to the CI server not having Azure credentials.

**Comment by allantargino** [comment]
@tombuildsstuff @katbyte I fixed all conflicts and the tests are passing 👍 
I would appreciate if you could review it, thank you!

**Comment by allantargino** [comment]
Hi @tombuildsstuff @katbyte!
I fixed all conflicts and the tests are now passing. I would appreciate if you could review it, please :) 
Thank you!

**Comment by crawfs** [comment]
Any updates on this? Really looking forward to seeing this in a future terraform version.

**Comment by chakri-nelluri** [comment]
@tombuildsstuff Please take a look when you get a chance. Thanks

**Comment by allantargino** [comment]
Hey @tombuildsstuff @katbyte @mbfrahry @jackofallops @manicminer, I would appreciate a review on this PR :) It is here for a while and seems there is some people interested on this functionality. I keep rebasing the PR to keep up with `go.mod`, but I will wait for a review before doing so again.
Thank you!

**Comment by crawfs** [comment]
There is a new draft PR from a few days ago #28278 the covers the same primary feature proposed here. What will be the future for these two PRs?

**Comment by StephanHCB** [comment]
> There is a new draft PR from a few days ago #28278 that covers the same primary feature proposed here. What will be the future for these two PRs?

If I understand this PR correctly, they do two subtly different things: 

This PR uses Azure Key Vault to store the key
- only works with the Azure backend, not any of the other remote state backends
- you still have to trust Microsoft because the key is handled by their systems
- access to the key is integrated with Azure RBAC (which can be great if all your data is in Azure anyway and is thus protected in the same manner)
- this allows you to read the statefile if your identity has access rights to the key

My PR is completely stand-alone, client side encryption
- works with all remote state backends (except the extended one: tf cloud)
- you have to do key management yourself
- you trust the system your terraform command runs on (think: on-premise), but not any third party
- even if you happen to use the Azure backend, there is no way to read the statefile inside Azure, unless you somehow got the key from on-premise

See these comments on #9556 that elaborate on the difference
https://github.com/hashicorp/terraform/issues/9556#issuecomment-542694978
https://github.com/hashicorp/terraform/issues/9556#issuecomment-592663237

I'd love to hear from maintainers on how you'd prefer to proceed with this. Having the state completely unencrypted in an Azure storage account is a thousand times worse than either of the proposed solutions, and has already led to security problems like https://github.com/hashicorp/terraform/security/advisories/GHSA-4rvg-555h-r626

**Comment by allantargino** [comment]
Agreed with the differences that @StephanHCB pointed out.
On the other hand, I think the best implementation would contain both PRs ideas. I think we should create an abstraction that allows any remote backend to have client side encryption using an *encryption provider*.
The *encryption provider* could be either Azure Key Vault (from this PR) or local keys (from the other PR). This would allow us to add many more implementations, such as Hashicorp's Vault, AWS'S KMS, Google's Secret Manager, and others.

**Comment by StephanHCB** [comment]
Hi @allantargino, I'd love to collaborate on this to get this implemented as suggested.

As a starting point I took the current state of your PR and merged upstream main.

Before we start moving things around I'd like you to test that my deconflicted version still works, and potentially fix any issues I may have introduced.

It compiles and all unit tests still pass, but I don't currently have a way to test with azure key vault.

Please check out https://github.com/StephanHCB/terraform/commits/remote-state-keyvault-upd-2021-04-18 

I've sent you an invite to my repository, in case you need to push any fixes.

Once we are sure I didn't break things, I can add my code. I think I already have an idea how to pull out the encryption code from your implementation, so that it can be used for standalone encryption with just the key being stored in Azure key vault if desired.

I've also looked at the bring-your-own-key implementations in the gcs and s3 remote backends, but these use server side encryption (e.g. placing the key in a header sent to gcs), so they are not feasible to use as additional client-side encryption providers as-is. So for now, it's just going to be Azure key vault and pure client-side. It should be easy to add additional encryption providers later on, though.

**Comment by allantargino** [comment]
Hi @StephanHCB, I would love to collaborate on this too :)
On the other hand, I believe this change not only affects one provider, but also other core parts of terraform.
How about proposing and discussing the implementation details before implementing it?
It would be great to get involvement from terraform maintainers as well during the process.

**Comment by chakri-nelluri** [comment]
@tombuildsstuff @mbfrahry PTAL. Waiting on this support for a while.

**Comment by StephanHCB** [comment]
> On the other hand, I believe this change not only affects one provider, but also other core parts of terraform.
> How about proposing and discussing the implementation details before implementing it?
> It would be great to get involvement from terraform maintainers as well during the process.

Agreed. I've written a detailed proposal and posted it on https://github.com/hashicorp/terraform/issues/9556#issuecomment-826341937

I'm always a fan of presenting actual code to inform the proposal. It's ok at this point if the code is a working prototype. So I did that.

One of the things I have realized while implementing the prototype is that we can proceed in parallel. I think this is an 
attractive proposition because this PR is ready and only makes localized changes to the azure backend, so I do not see
a reason to delay getting the feature out there. (Feel free to use my recent deconflicting of your PR, @allantargino.)

The idea of state encryption providers can be implemented separately and independently.

Then once that is merged as well, it is easy to pull out the code that interacts with Azure Key Vault and performs the encryption,
turning it into another state encryption provider, while still supporting this feature.

**Comment by byteknacker** [comment]
Just checking if there is an update on this issue. What is the current status?

**Comment by gareda** [comment]
Was this feature abandoned?

**Comment by Joey40** [comment]
Any update on this?  This seems like a ready-to-go solution for a major security gap.

**Comment by allantargino** [comment]
It is a bit sad that such requested feature never got any attention from maintainers.
Plain state has been around for a long time - I am glad that Open Tofu is going to fix it: https://github.com/opentofu/opentofu/issues/874

**Pull request closed without merging**
