### PR TITLE
provider/openstack: Add allowed_address_pairs

### PR DESCRIPTION
**Pull request by FedericoCeratto**
Based on  #5076

### CODE REVIEW

**Comment by jtopjian** [comment]
@FedericoCeratto Thanks for this. Let me know when this is ready for a review. :)

**Comment by FedericoCeratto** [comment]
@jtopjian the PR is essentially ready as it is, unless acceptance tests are required (I'm having some trouble running the tests)

**Comment by jtopjian** [comment]
It looks like you added a test for the `import` functionality, and I don't think that specific test is adding anything more to what was already being tested.

Acceptance tests are not required - I can always merge this and add one post-merge.

If this is ready to go, I'd say remove the import test and then squash everything into one commit.

**Comment by FedericoCeratto** [comment]
@jtopjian the test was already in place, I populated the testAccNetworkingV2Port_basic variable.

**Comment by jtopjian** [comment]
That's already done [here](https://github.com/hashicorp/terraform/blob/master/builtin/providers/openstack/resource_openstack_networking_port_v2_test.go#L112) so it's not required.

**Comment by jtopjian** [comment]
@FedericoCeratto sorry for the delay. Thank you very much for this!

**Pull request merged**
