### PR TITLE
provider/google: Add support for attaching/detaching a disk to/from an instance

### LINKED ISSUE #6678: 'google_compute_instance' adding 'google_compute_disk' forces new resource
Hey, i've encountered unexpected behaviour while updating a google_compute_instance resource by adding a new disk {}.
### Terraform Version

Terraform v0.6.16
### Affected Resource(s)
- google_compute_instance
- google_compute_disk
### Terraform Configuration Files

Consider starting out with the following configuration:

``` hcl
variable "gce_ssh_user" {}
variable "gce_ssh_pub_key_file" {}
variable "gce_service_account" {}
variable "gce_project_id" {}
variable "gce_image" {}
variable "gce_region" {
  default = "europe-west1"
}

variable "gce_network" {}
variable "gce_subnetwork" {}

provider "google" {
  credentials = "${file(var.gce_service_account)}"
  project     = "${var.gce_project_id}"
  region      = "${var.gce_region}"
}

resource "google_compute_disk" "default" {
  name  = "test-disk"
  type  = "pd-ssd"
  zone = "${var.gce_region}-b"
  size = 10
}

resource "google_compute_instance" "remove-me" {
  name       = "disk-test"
  machine_type         = "n1-standard-1"
  can_ip_forward       = false
  zone = "${var.gce_region}-b"

  disk {
    image = "ubuntu-1604-xenial-v20160429"
  }

  network_interface {
    subnetwork = "${var.gce_subnetwork}"
    access_config {
      // Ephemeral IP
    }
  }

  service_account {
    scopes = ["compute-rw"] 
  }

  metadata {
    sshKeys = "${var.gce_ssh_user}:${file(var.gce_ssh_pub_key_file)}"
  }
}
```

When using the gce interface I would now be able to add the disk 'test-disk' to the instance 'remove-me' without recreating it (or even rebooting). I would expect terraform to behave the same when changing the resource configuration to the following:

``` hcl

variable "gce_ssh_user" {}
variable "gce_ssh_pub_key_file" {}
variable "gce_service_account" {}
variable "gce_project_id" {}
variable "gce_image" {}
variable "gce_region" {
  default = "europe-west1"
}

variable "gce_network" {}
variable "gce_subnetwork" {}

provider "google" {
  credentials = "${file(var.gce_service_account)}"
  project     = "${var.gce_project_id}"
  region      = "${var.gce_region}"
}

resource "google_compute_disk" "default" {
  name  = "test-disk"
  type  = "pd-ssd"
  zone = "${var.gce_region}-b"
  size = 10
}

resource "google_compute_instance" "remove-me" {
  name       = "disk-test"
  machine_type         = "n1-standard-1"
  can_ip_forward       = false
  zone = "${var.gce_region}-b"

  disk {
    image = "ubuntu-1604-xenial-v20160429"
  }

  #DISK ADDED HERE (using .name attribute instead of self_link yields the same result)
  disk {
    disk = "${google_compute_disk.default.self_link}"
  }

  network_interface {
    subnetwork = "${var.gce_subnetwork}"
    access_config {
      // Ephemeral IP
    }
  }

  service_account {
    scopes = ["compute-rw"] //this grands our filesystemd to modify itself
  }

  metadata {
    sshKeys = "${var.gce_ssh_user}:${file(var.gce_ssh_pub_key_file)}"
  }
}
```
### Debug Output

[https://gist.github.com/advanderveer/fc9e8ef73f1f0b0b8578fedf9140307e](https://gist.github.com/advanderveer/fc9e8ef73f1f0b0b8578fedf9140307e)
### Panic Output

No panic is produced
### Expected Behavior

I would expect the the 'google_compute_instance' not to be recreated
### Actual Behavior

It get destroyed, i.e terraform plan shows multiple "forces new resource":

```
-/+ google_compute_instance.remove-me
    can_ip_forward:                                      "false" => "false"
    disk.#:                                              "1" => "2" **(forces new resource)**
    disk.0.auto_delete:                                  "true" => "true"
    disk.0.image:                                        "ubuntu-1604-xenial-v20160429" => "ubuntu-1604-xenial-v20160429"
    disk.1.auto_delete:                                  "" => "true" **(forces new resource)**
    disk.1.disk:                                         "" => "https://www.googleapis.com/compute/v1/projects/microfactory-test/zones/europe-west1-b/disks/test-disk" (forces new resource)
    machine_type:                                        "n1-standard-1" => "n1-standard-1"
    metadata.#:                                          "1" => "1"
    metadata.sshKeys:                                    "<my public ssh key>"
    metadata_fingerprint:                                "Mq9VPCUvh-E=" => "<computed>"
    name:                                                "disk-test" => "disk-test"
    network_interface.#:                                 "1" => "1"
    network_interface.0.access_config.#:                 "1" => "1"
    network_interface.0.access_config.0.assigned_nat_ip: "146.148.15.98" => "<computed>"
    network_interface.0.address:                         "10.0.0.3" => "<computed>"
    network_interface.0.name:                            "nic0" => "<computed>"
    network_interface.0.subnetwork:                      "microfactory-subnetwork" => "microfactory-subnetwork"
    self_link:                                           "https://www.googleapis.com/compute/v1/projects/microfactory-test/zones/europe-west1-b/instances/disk-test" => "<computed>"
    service_account.#:                                   "1" => "1"
    service_account.0.email:                             "1010578936991-compute@developer.gserviceaccount.com" => "<computed>"
    service_account.0.scopes.#:                          "1" => "1"
    service_account.0.scopes.299962681:                  "https://www.googleapis.com/auth/compute" => "https://www.googleapis.com/auth/compute"
    tags_fingerprint:                                    "42WmSpB8rSM=" => "<computed>"
    zone:                                                "europe-west1-b" => "europe-west1-b"
```
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
1. `terraform apply`
### Important Factoids

Not that i'm aware of
### References

I couldn't find any maybe [https://github.com/hashicorp/terraform/pull/5241](https://github.com/hashicorp/terraform/pull/5241) is related

### PR DESCRIPTION
**Pull request by danawillow**
Fixes #6678.

This currently has a few limitations, but I think it's good enough to handle the most common uses. The limitations are:
- Trying to attach/detach an identical disk (I tried to write a test that exposes this but couldn't get one that was accepted, so maybe this is an impossible scenario)
- Trying to detach a disk and delete it at the same time (the dependencies get resolved in the wrong order and the disk can't be deleted because it's still attached)

cc @evandbrown in case you're interested since you had looked into this at one point
also @jevonearth

### CODE REVIEW

**Comment by jevonearth** [comment]
@danawillow Awesome, I will test it ASAP, but it might take me a couple days to get to. Thank you so much. :+1:

**Comment by jevonearth** [comment]
I tested this against my instances/disks, and it worked, allowing me to de/reattach disks. This makes me happy.

@danawillow if there's any particular scenario you'd like me to test, let me know. Otherwise LGTM.

**Comment by danawillow** [comment]
Great, thanks @jevonearth!

@paddyforan, this is ready for review whenever you are.

**Comment by paddyforan** [comment]
Before I get into the code of this, just a design thought: is it worth maybe making this similar to [the AWS volume attachment resource](https://www.terraform.io/docs/providers/aws/r/volume_attachment.html)?

**Comment by danawillow** [comment]
Hmm, maybe. The big difference between the two APIs is that the `attachDisk` function in GCP requires a full disk resource, whereas the `attachVolume` function in AWS just references a disk. So if we added a new resource for this, it would need the full disk characteristics, and I guess we'd have to deprecate the disk field in the `resource_compute_instance` so people don't try to use both (because if people start off using the one in the instance and then want to detach it they'd be out of luck). Something that I _could_ see us doing which would make things a bit simpler, would still be to deprecate the disk field in the instance resource but add an `instances` field in the `compute_disk` resource.

Would it be worth it to get on a hangout for 10 minutes tomorrow and talk about this?

**Comment by jevonearth** [comment]
Hi @paddycarver @danawillow , did you two figure out what to do with this? I'm stuck again today with terraform v0.9.5 wanting to nuke an instance because some disk changes. :/

**Comment by danawillow** [comment]
Hey @jevonearth, sorry for the delay and the lack of communication. We came up with a solution we like a lot better- I wrote a design doc around it and plan to implement it at some point soon, but haven't gotten around to it yet.

**Comment by jevonearth** [comment]
Great to hear @danawillow , looking forward to it. :)

**Comment by paddycarver** [comment]
I'm going to close this PR, as it's now deprecated in favour of the new design, to avoid confusion. :)

**Comment by jevonearth** [comment]
@paddycarver Is there a PR, Issue, or link to a design doc so the curious can follow along? :)

**Comment by paddycarver** [comment]
I think @danawillow is putting the finishing touches on it at the moment, but the tentative outline is that we'll move to an attached_disk resource, and eventually deprecate the disk property on instances.

I think tracking #6678 is probably the best bet for keeping track, as any new PRs or issues will almost certainly be linked back to it. I can't promise timelines or anything, but this is one of the overarching design problems that are at the forefronts of our minds right now.

**Pull request closed without merging**
