### PR TITLE
backend/manta: Update manta dependencies

### PR DESCRIPTION
**Pull request by stack72**
Internally, triton-go has changed how it handles errors. We can now get rid of
checking strings for errors, and we have introduced an errors library that
wraps some of the major errors we encounter and test for

### CODE REVIEW

**Comment by apparentlymart** [comment]
Ahh... this looks much better. :grinning: Thanks!

It looks like something went a little weird with the Travis run here (it was running for 7 hours and apparently stalled :confused:) so I've restarted it.

**Comment by apparentlymart** [comment]
Something seems to be awry with Travis-CI since the job isn't even _starting_ now. I need to quit for the day now, but I'll check in on this tomorrow and see what's going on.

**Comment by ndmckinley** [comment]
I think that's probably due to https://www.traviscistatus.com/incidents/c1s4dlyxd4lf, but I'm not 100% sure.

**Comment by stack72** [comment]
@apparentlymart looks like we are all good now - @ndmckinley may be correct that it seemed to be linked to the travis outage :)

**Comment by apparentlymart** [comment]
Hi again @stack72! Indeed I found out about that Travis issue later in the evening and suspect it was the cause of the weird behavior I saw here. Sorry about that!

**Comment by stack72** [comment]
Not your fault - thanks for the merge :)

**Pull request merged**
