### PR TITLE
Better document RDS `apply_immediately`

### PR DESCRIPTION
**Pull request by catsby**
Make it more obvious why modifying a db / rds cluster may show a plan diff after applying a change, regarding `apply_immediately` et. al.

### CODE REVIEW

**Comment by stack72** [comment]
@catsby I **think** the type of same documentation can be extended to the Elasticache Resource?

**Comment by catsby** [comment]
@stack72 good catch, adding...

**Comment by catsby** [comment]
@stack72 done, and fixed the link in rds_cluster doc

**Comment by stack72** [comment]
@catsby LGTM! Nice one :)

**Pull request merged**
