### PR TITLE
Vsphere_virtual_machine: Network interfaces

### LINKED ISSUE #3559: vSphere: do not add new network adapters by default
An the moment a new network adapter is added every time a virtual machine is created.
A quote from https://github.com/rakutentech/terraform-provider-vsphere/blob/master/README.md:

> please don't include network adapters in VM template. When deploying a new virtual machine, this provider adds new network adapters to the new virtual machine.

This requirement is fine, if a machine is created from scratch, and then loaded from PXE. But that's not the main use case.
More often machines are cloned from templates, and here such requirement makes the procedure extremely complicated. To make my templates compatible to Terraform, I have to remove network adapters explicitly. But what if later I need to update such a template? I have to add a network adapter back, load a machine, make required changes, and then delete the adapter once again. That just doesn't work.

If Terraform clones a virtual machine from a template, then `network_interface` parameter must be optional. By default it should inherit configuration from a template, and do not create additional network adapters.

### PR DESCRIPTION
**Pull request by eloycoto**
Hi, 

This PR fix #3559 and #3560, when a template is cloned we deleted all the interfaces so the createNetworkInterfaces will work correctly. 

Regards.

### CODE REVIEW

**Comment by eloycoto** [comment]
Hi, 

I've just added a few changes in this PR. Now template didn't change. 

The process of the server is the following: 

- Get the template. 
- Clone template server and keep it off. 
- Delete all old network devices and add the spec ones. 
- Apply VM customizations (hostname, domain, dns, etc.. )
- PowerOn 
- WaitForIP. 

This has a new dependency in govmomi, and this PR need to be accepted. 

https://github.com/vmware/govmomi/pull/365

Cheers

**Comment by chrislovecnm** [comment]
@eloycoto you sign the CLA for govmomi?  See their comments on your PR.

**Comment by eloycoto** [comment]
Hi, 

@chrislovecnm: Yep, is merged now. https://github.com/vmware/govmomi/pull/365

@radeksimko: This should be ok, I've just check that no godeps or glide for the dependencies. So this PR can be merged if you want ;-) 

Thanks.

**Comment by phinze** [comment]
Hi @eloycoto - thanks for this!

A few questions:

 * Are you able to run the acceptance tests in your environment?
 * Do they pass on this branch?
 * Is it possible to add or enhance a test for this new behavior?

**Comment by tkak** [comment]
@eloycoto I tried to run the acceptance tests in my environment. The test has passed in case of a template containing some network devices. Thank you!

**Comment by phinze** [comment]
@tkak that is great to hear!

Does that mean you can add a test covering the new behavior if we merge this as is?

**Comment by chrislovecnm** [comment]
@phinze can we get this merged?

**Comment by phinze** [comment]
Sounds good - it would still be nice to get a covering acceptance test for the new behavior. But we can merge as-is push that to a separate task.

**Comment by chrislovecnm** [comment]
@eloycoto any ideas on acceptance testing for this?

@phinze might be tough to write a specific test, because this behavior is based on how the virtual machine template is configured.

**Comment by eloycoto** [comment]
Hey @chrislovecnm!

Sorry, I was on vacation. I'll send a new PR this week with new test. 

Cheers

**Comment by chrislovecnm** [comment]
:+1: @eloycoto

**Pull request merged**
