### PR TITLE
Draft: Upgrade go-getter to v2

### LINKED ISSUE #31983: S3 module downloads don't work with AWS IRSA
### Terraform Version

```shell
Terraform v1.3.2
```

### Terraform Configuration Files

```terraform
module "some_s3_module" {
  source                           = "s3::https://s3.amazonaws.com/somewhere/terraform-modules/release/something-0.1.0.tgz"
  ...
  some input vars
  ...
}
```

### Debug Output

Have already applied a temp fix internally and shared the issue in the description but can obtain the debug info if necessary

### Expected Behavior

S3 modules download when Terraform is being executed from an EKS pod utilizing IRSA

### Actual Behavior

Due to the old version of hashicorp/go-getter, it's not looking in the correct place for credentials or the extra environment vars.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Additional Context

Copying from issue in go-getter, once the fix is merged there we'd need to bump the version in terraform.

[IAM roles for service accounts (IRSA)](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) is a feature of EKS to provide IAM role creds to kubernetes pods. The [aws-sdk version (v1.15.78) used in the current version of go-getter](https://github.com/hashicorp/go-getter/blob/293f9e2372e5cd5ff8cdf7b6977b861122837292/go.mod) doesn't support IRSA in its default credential chain. Versions after v1.23.13 are supported ([source](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html)). To overcome this problem, a recent version of aws-sdk should be used.

The use case: We bumped into this problem while using terraform (via atlantis) in a kubernetes pod.

### References

https://github.com/hashicorp/go-getter/issues/383

### PR DESCRIPTION
**Pull request by Jukie**
Fixes #31983

## Target Release

1.4.x

### BUG FIXES
* Fixes s3 module downloads when using AWS IRSA

### CODE REVIEW

**Comment by crw** [comment]
Thanks for this submission! Would you mind leaving a comment when it is out of "draft" status just to make sure I get a GitHub notification? I will also bring this to triage to see if we can review this PR (e.g. can we accept the newer go-getter or is there some reason it is not yet upgraded).

**Comment by Jukie** [comment]
Will do. For now if it's possible to have a new release cut for v1 go-getter (see [this merged PR](https://github.com/hashicorp/go-getter/pull/384) that would fix the issue with less code changes in Terraform and the v2 upgrade could happen under a separate effort.

**Comment by crw** [comment]
Hi @Jukie, we reviewed this in triage today. Currently Packer is the primary (and possibly only) user of go-getter@v2. What is more likely to happen in a shorter timeframe is for the Terraform core team to make a new release of go-getter@v1 and bump the dependency. We did a quick review of the changes between 1.6.2 and main, and it looks like the code changes are just the change you need and a change to the build process. So that seems like the safest course of action. I have created the internal issue necessary to get that work prioritized. 

It is possible at some point we would want to migrate to the v2 go-getter, but the cost / benefit is not particularly favorable so prioritizing it will be difficult. It might make sense if HashiCorp decides to deprecate v1 for some reason, but there is no particular motivation to make that change today. In any case, I hope this info helps set expectations!

**Comment by Jukie** [comment]
That makes sense, I'll close this then and wait for the the updated release.

**Pull request closed without merging**
