### PR TITLE
aws_lambda_event_source_mapping: Retry InvalidParameterValueException errors due to newly created resources

### PR DESCRIPTION
**Pull request by vancluever**
Reference #4103 for errors and background, this fix uses current pattern. Retry `InvalidParameterValueException` errors on creating new Lambda event source mappings.

Fixes errors like the one below, and also ones that are related to policy in the role:

```
* aws_lambda_event_source_mapping.LambdaEventSourceMapping: Error creating Lambda event source mapping: InvalidParameterValueException: Please add Lambda as a Trusted Entity for arn:aws:iam::<redacted>
	status code: 400, request id: <redacted>
```

### CODE REVIEW

**Comment by hngkr** [comment]
I can confirm that this bug also bites, and that we've worked around it using code that looks very much like this.

**Comment by vancluever** [comment]
Thanks @catsby!

**Comment by catsby** [comment]
ah, sorry @vancluever , I forgot to ping you here that I combined your PR with mine in https://github.com/hashicorp/terraform/pull/4511 , thanks so much!

**Comment by vancluever** [comment]
No problem, glad to see it in!

**Pull request merged**
