### PR TITLE
provisioner/chef: Fix provisioner failure "exited with non-zero exit status: 1"

### PR DESCRIPTION
**Pull request by mpetka**
I believe this is the reason the chef provisioner fails. I assume we want a for-each statement here so a single quote should be used.  (also a misspelled word in a comment )

### CODE REVIEW

**Comment by radeksimko** [comment]
Hi @mpetka 
did you mean to remove 24k lines of code? I'm assuming it's just an effect of some kind of branch conflict?

**Comment by radeksimko** [comment]
Also, would you mind describing the problem your PR is supposed to solve?

**Comment by mpetka** [comment]
Yes and im unsure how to remove that. There is only one change needed. %% to %

**Comment by mpetka** [comment]
Yes. The chef provisioner fails very quickly:

aws_instance.tsdr (chef): Connected!
aws_instance.tsdr: Still creating... (5m19s elapsed)
...
aws_instance.tsdr: Still creating... (6m0s elapsed)
aws_instance.tsdr: Still creating... (6m9s elapsed)
Error applying plan:

1 error(s) occurred:

* Command "powershell -NoProfile -ExecutionPolicy Bypass -File C:/Temp/ChefClient.ps1" exited with non-zero exit status:
 1

**Comment by radeksimko** [comment]
@mpetka Thanks for sharing the console output. Would you mind also sharing relevant HCL config that would help us reproduce the bug and possibly verify that it's fixing the problem?

**Comment by mpetka** [comment]
This is my provisioner statement. The runlist is empty at the moment for troubleshooting.

provisioner "chef" {
	environment = "build"
	server_url = "https://chef.gnf.org/organizations/mpetka"
	ssl_verify_mode = "verify_none"
	validation_client_name = "mpetka-validator"
	validation_key = "${file("./mpetka-validator.pem")}"
	node_name = "dr-tsdr-1"
	run_list = [""]
	log_to_file = "true"
	skip_install = "false"
	os_type = "windows"
	client_options = [
	    "exit_status = disabled",
	    "log_location = win_evt",
	    "rest_timeout = 800"
  	]
	connection {
	type = "winrm"
	user = "vagrant"
	password = "${var.admin_password}"
	timeout = "30m"
  	}
	}

Here is the default powershell alias showing that the for-loop is aliased to the single percentage

Get-Alias -Definition ForEach-Object

CommandType     Name                                                Definition
-----------     ----                                                ----------
Alias           %                                                   ForEach-Object
Alias           foreach                                             ForEach-Object

**Comment by mpetka** [comment]
The issue is discussed here [provisioner/chef: not installing chef on Windows #3769](https://github.com/hashicorp/terraform/issues/3769)

**Pull request closed without merging**
