### PR TITLE
provider/azurerm: migrate resource_group resource to Azure SDK

### PR DESCRIPTION
**Pull request by pmcatominey**
TF_ACC=1 go test ./builtin/providers/azurerm -v -run TestAccAzureRMResourceGroup -timeout 120m
=== RUN   TestAccAzureRMResourceGroup_importBasic
--- PASS: TestAccAzureRMResourceGroup_importBasic (92.95s)
=== RUN   TestAccAzureRMResourceGroup_basic
--- PASS: TestAccAzureRMResourceGroup_basic (90.26s)
=== RUN   TestAccAzureRMResourceGroup_withTags
--- PASS: TestAccAzureRMResourceGroup_withTags (123.14s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/azurerm	306.493s

### CODE REVIEW

**Comment by pmcatominey** [comment]
Given that resource groups are a pretty critical resource and underpin almost everything else in the Azure provider, I ran the tests for the public IP resource to ensure dependencies still work.

```
TF_ACC=1 go test ./builtin/providers/azurerm -v -run TestAccAzureRMPublicIp -timeout 120m
=== RUN   TestAccAzureRMPublicIpStatic_importBasic
--- PASS: TestAccAzureRMPublicIpStatic_importBasic (148.68s)
=== RUN   TestAccAzureRMPublicIpStatic_basic
--- PASS: TestAccAzureRMPublicIpStatic_basic (132.45s)
=== RUN   TestAccAzureRMPublicIpStatic_withTags
--- PASS: TestAccAzureRMPublicIpStatic_withTags (150.25s)
=== RUN   TestAccAzureRMPublicIpStatic_update
--- PASS: TestAccAzureRMPublicIpStatic_update (174.44s)
=== RUN   TestAccAzureRMPublicIpDynamic_basic
--- PASS: TestAccAzureRMPublicIpDynamic_basic (134.13s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/azurerm	740.066s
```

**Comment by jen20** [comment]
Hi @pmcatominey! What is the motivation behind migrating this?

**Comment by pmcatominey** [comment]
Hi @jen20, I just noticed that the Microsoft SDK supported resource groups.

I thought it would be preferable to use a Microsoft supported library if possible.

**Comment by jen20** [comment]
Ah - I see @pmcatominey! Sadly we've had a fairly poor experience with the Microsoft provided library (resulting in Riviera existing), so I think in general we'd prefer to stick with that where possible and indeed potentially migrate resources in the opposite direction. The APIs for resource groups are sufficiently stable that I'm not too concerned about changes there. Thanks for your work - if you're interested in contributing further to the AzureRM provider there are a number of resources such as load balancers (see open PRs) which could definitely use some attention!

**Comment by pmcatominey** [comment]
No worries, thanks for the review.

**Pull request closed without merging**
