### PR TITLE
Don't send access_token in request params

### PR DESCRIPTION
**Pull request by jbardin**
Always send the access_token in the X-Atlas-Token header.

### CODE REVIEW

**Comment by phinze** [comment]
This LGTM - there's also an Atlas client in the `terraform push` path and in the Atlas provider. Are we good in both those spots as well?

**Comment by jbardin** [comment]
I think so ... this package is the only place we ever set `access_token` (my research consisting of `git grep`), let me double check

**Comment by jbardin** [comment]
Look OK. I don't see it set anywhere else, and verified that the `tf push` request sends the header

**Comment by phinze** [comment]
Nice thanks for checking. LGTM then!

**Pull request merged**
