### PR TITLE
Feature/allow vault resource to update

### PR DESCRIPTION
**Pull request by gerr1t**
By default the vault_generic_secret resource is not configured to read back from vault. This means that changes cannot properly be compared. This is done for security reasons (see: Required Vault Capabilities on https://www.terraform.io/docs/providers/vault/r/generic_secret.html), so that a token can be limited to only writing to the vault server.

However, there are reason why you would want to be able to compare and update resources. This change allows this by setting allow_read value to true on the resource.

### CODE REVIEW

**Comment by g4rviel** [comment]
+1

**Comment by geogdog** [comment]
+1

**Comment by dsterz** [comment]
+1

**Comment by gerr1t** [comment]
@apparentlymart , any idea in which version this might be merged? This is actually a feature I am waiting for.

**Comment by gerr1t** [comment]
@apparentlymart , any update?

**Comment by rojaro** [comment]
+1

**Comment by apparentlymart** [comment]
Hi @gerr1t! Sorry for the silence here.

This looks good to me. Ideally we'd have some acceptance test coverage for having this set both on and off, but it's a bit of a tricky thing to test so I think we can pass on it for right now given the relative simplicity of this additional feature and that the rest of the behavior is already tested.

I just merged this. Thanks!

**Comment by gerr1t** [comment]
Thanks @apparentlymart !

**Pull request merged**
