### PR TITLE
Aurora rds

### PR DESCRIPTION
**Pull request by arcadiatea**
This is pull request to add aws rds db cluster parameter group function.
[GH-6568]

### CODE REVIEW

**Comment by jen20** [comment]
Hi @arcadiatea! Thanks for opening a pull request here! The actual resource added here looks great, but it seems we picked up a lot of stray line ending changes in unrelated dependencies, and a changelog entry which is traditionally made on master. Is there any chance you could adjust the commit to just contain the necessary changes to the AWS provider and force push it back to this branch so that we can merge? Thanks!

**Comment by arcadiatea** [comment]
I reverted the unrelated dependency change, most of them are result of gofmt.

**Comment by stack72** [comment]
Hi @arcadiatea 

Please can you also remove the changelog differences as well? We usually add the changelog entry after merge to make sure there are no issues

Thanks

Paul

**Comment by arcadiatea** [comment]
I cleaned up the changes. How it looks now?

**Comment by stack72** [comment]
Hi @arcadiatea 

The changes look good now. I just ran the tests to make sure all was well:

```
make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSDBClusterParameterGroup' 2>~/tf.log
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /vendor/)
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSDBClusterParameterGroup -timeout 120m
=== RUN   TestAccAWSDBClusterParameterGroup_basic
--- FAIL: TestAccAWSDBClusterParameterGroup_basic (8.58s)
	testing.go:234: Step 0 error: Error applying: 1 error(s) occurred:

		* aws_db_cluster_parameter_group.bar: Error creating DB Cluster Parameter Group: InvalidParameterValue: ParameterGroupFamily mysql5.6 does not support DB clusters
			status code: 400, request id: 12107477-1938-11e6-b038-b17e58d2ad7d
=== RUN   TestAccAWSDBClusterParameterGroup_Only
--- FAIL: TestAccAWSDBClusterParameterGroup_Only (9.18s)
	testing.go:234: Step 0 error: Error applying: 1 error(s) occurred:

		* aws_db_cluster_parameter_group.bar: Error creating DB Cluster Parameter Group: InvalidParameterValue: ParameterGroupFamily mysql5.6 does not support DB clusters
			status code: 400, request id: 17831bd9-1938-11e6-b038-b17e58d2ad7d
FAIL
exit status 1
FAIL	github.com/hashicorp/terraform/builtin/providers/aws	17.792s
```

Please can you have a look at this?

Paul

**Comment by arcadiatea** [comment]
Hi Paul
Thank you for testing. The db cluster parameter group is special for Aurora only. 
So the family group need to be "aurora5.6".

Here is the example 

resource "aws_db_cluster_parameter_group" "default" {
  name        = "test"
  family      = "aurora5.6"

  parameter {
    name         = "character_set_database"
    value        = "utf8"
    apply_method = "immediate"
  }
}

**Comment by stack72** [comment]
Hi @arcadiatea 

Thanks for clarifying here. Please can you update the PR with a test that works? Once we get this in place, we can proceed with the merge :)

P.

**Comment by arcadiatea** [comment]
Hi, @stack72  
The test code is updated. 
Thanks
Linda

**Comment by arcadiatea** [comment]
@stack72  do you have chance to take look this?

**Comment by catsby** [comment]
Hello – I believe this was already added in https://github.com/hashicorp/terraform/pull/5269, pinging @stack72 who's looked at both to confirm

**Comment by catsby** [comment]
I chatted with Paul and this does look like mistaken duplicate work, so sorry! I think https://github.com/hashicorp/terraform/pull/6865 is still good though. Sorry for the trouble

**Pull request closed without merging**
