### PR TITLE
gofmt files from recently merged PRs

### PR DESCRIPTION
**Pull request by radeksimko**
### Test plan
```
gofmt -l ./..
```

expect no output.

### CODE REVIEW

**Comment by phinze** [comment]
You beat me to it :grinning: LGTM

**Comment by stack72** [comment]
Yay! This mean's I won't get unintended changes in my files now :) git shows so many fmt changes for me (IntelliJ fixes them on as a file watcher)

**Comment by svanharmelen** [comment]
Nice :wink:

**Comment by radeksimko** [comment]
so much excitement from one-liner... :smile: 
I'll just let the tests pass and then merge.

**Comment by stack72** [comment]
it's been a slow day - no major AWS infra announcements yet ;)

**Comment by apparentlymart** [comment]
It's easy to introduce inconsistent indentation when having to maintain patches over a long period, since gofmt always wants everything lined up but other merges can introduce new, longer strings that cause the "line-up" point to change.

Should we have a test that fails if any files are not in the ``go fmt`` canonical form? That'd help to catch these things during rebasing/merging as well as just catching general carelessness and hopefully reducing the need for this sort of follow-up change.

**Comment by phinze** [comment]
@apparentlymart good idea! I'd be all for it.

**Comment by radeksimko** [comment]
@apparentlymart :+1:

**Pull request merged**
