### PR TITLE
Change variable validation error message type from string to expression

### PR DESCRIPTION
**Pull request by cgetzen**
Resolves https://github.com/hashicorp/terraform/issues/24407.

This PR changes configs.VariableValidation.ErrorMessage from a string to an expression.

One consequence of this is that some of the validations on the error message (nilstring and lookslikesentence) are moved from the configs package to the terraform package and checked during Eval.

#### Template

This file is used as a template for the table below

```terraform
variable "x" {
  type    = string
  default = "four"
  validation {
    condition     = length(var.x) > 5
    error_message = "not a sentence"
  }
}

terraform {
  experiments = [variable_validation]
}
```

#### Results

<table>
<tr>
<td> error_message </td> <td> output </td>
</tr>
<tr>
<td> [4, 3] </td>
<td>

```
Error: Unsuitable value type

  on main.tf line 6, in variable "x":
   6:     error_message = [4, 3]

Unsuitable value: string required
```

</td>
</tr>
<tr>
<td> "Your string ${var.x} isn't long enough." </td>
<td>

```
Error: Invalid value for variable

  on main.tf line 1:
   1: variable "x" {

Your string four isn't long enough.

This was checked by the validation rule at main.tf:4,3-13.
```

</td>
</tr>
<tr>
<td> "not a sentence" </td>
<td>

```
Error: Invalid value for variable

  on main.tf line 1:
   1: variable "x" {

not a sentence

This was checked by the validation rule at main.tf:4,3-13.


Error: Invalid validation error message

  on main.tf line 1:
   1: variable "x" {

Validation error message must be at least one full English sentence starting
with an uppercase letter and ending with a period or question mark.
```

</td>
</tr>
</table>

### CODE REVIEW

**Comment by cgetzen** [comment]
Looks like this may also resolve https://github.com/hashicorp/terraform/issues/24160. One think that also stuck out to me:

> Since this ability could be added later without a breaking change we may save implementing it until after the feature leaves experimental status, but we'll see how that plays out in relation to other work.

This definitely makes sense, but I think adding this feature will enable a few really cool workflows that could make this feature more popular (pushing it out of experimental?). Personally, I have some ideas around https://registry.terraform.io/modules/cgetzen/regex-errors until error checking is more powerful. What do you think @apparentlymart ?

If we wind up on "wait" I'd love to understand what is being looked at to determine if and when features graduate from experimental, and general vision of the language, so any future PRs could be more helpful  😃

**Comment by cgetzen** [comment]
Hi @jbardin, I seem to be battling merge conflicts like https://github.com/hashicorp/terraform/pull/25144. I'm wondering if you have the bandwidth to give feedback on (or merge) this PR since you've merged close-by code.

**Comment by apparentlymart** [comment]
Hi @cgetzen,

We're not intending to make any enhancements to the custom variable validation functionality before it's stabilized in the 0.13.0 release, because we want to release exactly what folks have already tested in that release (bugs notwithstanding), so we'll hold on looking at this deeply until at least after the 0.13.0 release has settled down (including any follow-up patch releases we might issue based on bug reports on the initial release), but this does seem to me like a good enhancement.

I don't want you to spend time constantly rebasing this so I'd suggest at least to hold until 0.13.0 seems stable (which might also mean after one or two patch releases if there are any critical bugs in 0.13.0) and then we can deal with any rebase conflicts all at once. (If you have your branch set to allow reviewers here to push to it then we'd be happy to deal with merge conflicts that have an "obvious" resolution on your behalf as part of review+merge.)

**Comment by cgetzen** [comment]
👋 Hoping to give this one last bump @apparentlymart @jbardin

**Comment by joe-a-t** [comment]
Is there any chance of getting this in? It looks like it would resolve a ton of validation issues that I have to help debug, particularly when the call into the variable validation is from a loop. Right now, the error message looks like
```
Error: Invalid value for variable

  on .terraform/modules/gcp/bucket-iam/main.tf line 77, in module "iam_binding":
  77:   member         = each.key

Invalid member, must match this regex '^(domain|group|serviceAccount|user):'.

This was checked by the validation rule at
.terraform/modules/gcp/bucket-iam/variables.tf:14,3-13.
```
and is really hard to trace back and figure out what string from `each.key` or `each.value` is invalid. Being able to have the error message be `"Invalid member '${var.member}', must match this regex '^(domain|group|serviceAccount|user):'.` would be a HUGE improvement

**Comment by joe-a-t** [comment]
FYI @cgetzen if you want to close this PR too https://github.com/hashicorp/terraform/pull/28044#issuecomment-1058506514

**Comment by crw** [comment]
@alisdair per https://github.com/hashicorp/terraform/pull/28044#issuecomment-1058506514 shall we close this PR as well?

**Comment by alisdair** [comment]
Thanks! See #30613 for the in-progress work which should achieve the root goal here.

**Pull request closed without merging**
