### PR TITLE
provider/aws: Updates for RDS

### LINKED ISSUE #2392: Modification of RDS subnet groups causes recreation of instance
Was just modifying the subnet groups for and RDS Instance and was surprised that TF was trying to recreate it.  I did have the prevent_destroy set, but had I not it would've been a tough night.

There's not special about the code I'm using.

    resource "aws_db_subnet_group" "db-subnet-1-group" {

        name        = "${var.env}-db-subnet-1-group"
        description = "${var.env} db subnet group"
        subnet_ids  = ["${var.db_subnet_1_id}","${var.db_subnet_2_id}"]

    }

    resource "aws_db_instance" "db-mysql-1" {

        identifier              = "${var.env}-mysql-1"
        allocated_storage       = "${var.allocated_storage}"
        engine                  = "mysql"
        engine_version          = "${var.engine_version}"
        instance_class          = "${var.instance_class}"
        name                    = "${var.env}mysql1"
        username                = "${var.env}bqmysql"
        password                = "${var.mysql_password}"
        multi_az                = "${var.multi_az}"
        apply_immediately       = true
        publicly_accessible     = false
        db_subnet_group_name    = "${aws_db_subnet_group.db-subnet-1-group.id}"
        parameter_group_name    = "default.mysql5.6"
        backup_retention_period = 3
    
        lifecycle = {
    	   prevent_destroy = true
        }
    }

### LINKED ISSUE #2719: aws_db_instance maintenance window capitalization?
Given a maintenance_window setting of `Fri:09:00-Fri:09:30`, which has never been changed, I'm seeing terraform plan/apply output like this:

```
~ aws_db_instance.pg_main: Modifying...
  maintenance_window: "fri:09:00-fri:09:30" => "Fri:09:00-Fri:09:30"
```

I'm guessing AWS is lowercasing somewhere along the line, and Terraform should either do the same or throw a validation error if the string contains any caps.

### PR DESCRIPTION
**Pull request by catsby**
Bundling some updates for RDS

- d793c6d fixes https://github.com/hashicorp/terraform/issues/3017 
- 22e73d7b fixes #2719
- fc0ccb9 fixes #2392

~~Not ready for merge yet, I think another 3 minor fixes will fit in here~~

### CODE REVIEW

**Comment by catsby** [comment]
@phinze please review when you get a chance. I had wanted another 3 some fixes in, but those ended up to be either not-doable or non-trivial.

**Comment by kyangmove** [comment]
I'm waiting this one to be released to create aurora db on AWS. Normally how long will it take to the release?

**Comment by phinze** [comment]
@catsby LGTM!

@kyangmove No specific date set for the next release quite yet.

**Comment by catsby** [comment]
@kyangmove I just merged this, though there is nothing specific to Aurora here. Pull Request https://github.com/hashicorp/terraform/pull/2935 does add the ability to use RDS Clusters (Aurora)

**Pull request merged**
