### PR TITLE
Add "gox" to the Makefile's tools section.

### PR DESCRIPTION
**Pull request by kwilczynski**
Signed-off-by: Krzysztof Wilczynski <krzysztof.wilczynski@linux.com>

### CODE REVIEW

**Comment by kwilczynski** [comment]
@stack72 over to you 🚀 . I added it as it trips me every time. I hope it's fine with you.

**Comment by catsby** [comment]
Fwiw, `gox` should be installed when `scripts/build.sh` is invoked... is that not happening for you?

**Comment by kwilczynski** [comment]
@catsby oh! I haven't used this script before. My workflow usually as:

- git clone ...
- make tools
- make test / acctest
- make dev (or for build a specific provider)

Should I move over to the `build.sh`?

**Comment by catsby** [comment]
Sorry for not being clear–

`$ make dev` invokes `$(CURDIR)/scripts/build.sh`, so you don't directly use it.

**Comment by catsby** [comment]
```
$ which gox
/Users/clint/Projects/Go/bin/gox

$ rm $(which gox)

$ which gox
gox not found

$ make dev
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/10/24 12:27:47 Generated command/internal_plugin_list.go
==> Removing old directory...
==> Installing gox...
==> Building...
Number of parallel builds: 3

-->    darwin/amd64: github.com/hashicorp/terraform

==> Results:
total 255216
-rwxr-xr-x  1 clint  staff   125M Oct 24 12:28 terraform
```

You could argue that it should be in `make tools`, though I don't think it's really necessary. I could say better if I knew the impetus of this pr, were you hitting errors?

**Comment by kwilczynski** [comment]
@catsby Blimey. I must have done something wrong, as this clearly works as it says on the tin. 

Apologies for the unnecessary commotion :(

**Comment by catsby** [comment]
Well, it's only unnecessary if there is no actual problem. If you'r e hitting something please let us know!

**Pull request closed without merging**
