### PR TITLE
provider/aws: Treat ecs_service w/ Status==INACTIVE as deleted

### PR DESCRIPTION
**Pull request by radeksimko**
fixes https://github.com/hashicorp/terraform/issues/3582

### CODE REVIEW

**Comment by stack72** [comment]
Looks good @radeksimko :)

**Comment by catsby** [comment]
Checks out, thanks Radek! :ship:

**Comment by radeksimko** [comment]
@stack72 I guess you meant a service, not a cluster? but otherwise good point, logging added in bcd63f6

**Comment by stack72** [comment]
nice - thanks @radeksimko :)

**Pull request merged**
