### PR TITLE
docs: fix typo in spelling of 'flag'

### PR DESCRIPTION
**Pull request by Skywalker427**
Change spelling from 'flat' to 'flag' to fix typo

Fixes: Typo in docs

### CODE REVIEW

**Comment by crw** [comment]
Thanks for this submission! Please accept the CLA and I will be happy to merge.

**Comment by Skywalker427** [comment]
> Thanks for this submission! Please accept the CLA and I will be happy to merge.

I get this when I try to accept the CLA via link. I don't know if it's relevant, but I'm logged in to developer.hashicorp.com with my GitHub account @crw 
Screenshot 2024-04-09 at 10 11 31

**Comment by crw** [comment]
Thanks, looking into it.

**Comment by crw** [comment]
@Skywalker427 The CLA problem should now be fixed - can you try again? Thanks!

**Comment by Skywalker427** [comment]
@crw CLA signed.

**Review by crw — APPROVED** [review]

**Pull request merged**
