### PR TITLE
AzureRM Backend snapshot support

### PR DESCRIPTION
**Pull request by pmarques**
This is a simple implementation that I'm currently using, discussion here #18284

### CODE REVIEW

**Comment by arichiardi** [comment]
This is great, I will start tracking it - very nice feature to have on Blobs especially, akin to what AWS offers.

**Comment by rkotturu** [comment]
When will this be merged ?

**Comment by rkotturu** [comment]
Is there any workaround (automation, not the manual way) until its official ?

**Comment by tombuildsstuff** [comment]
👋 hey @pmarques 

Thanks for this PR - apologies for the delayed review here!

This PR (and it's commits) been superseded into #24069 which includes these changes (and is now rebased on top of Giovanni, the new Storage SDK we're using to communicate with Azure) - as such I hope you don't mind but I'm going to close this PR in favour of #24069.

Thanks!

**Pull request closed without merging**
