### PR TITLE
provider/gce: Fix updates for http_health_check (set defaults)

### PR DESCRIPTION
**Pull request by dcarley**
#### provider/gce: Test updates to http_health_check

By first creating a very simple resource that mostly uses the default
values and then changing the two thresholds from their computed defaults.

This currently fails with the following error and will be fixed in a
subsequent commit:

    --- FAIL: TestAccComputeHttpHealthCheck_update (5.58s)
            testing.go:131: Step 1 error: Error applying: 1 error(s) occurred:

                    * 1 error(s) occurred:

                    * 1 error(s) occurred:

                    * Error patching HttpHealthCheck: googleapi: Error 400: Invalid value for field 'resource.port': '0'.  Must be greater than or equal to 1
                    More details:
                    Reason: invalid, Message: Invalid value for field 'resource.port': '0'.  Must be greater than or equal to 1
                    Reason: invalid, Message: Invalid value for field 'resource.checkIntervalSec': '0'.  Must be greater than or equal to 1
                    Reason: invalid, Message: Invalid value for field 'resource.timeoutSec': '0'.  Must be greater than or equal to 1

#### provider/gce: Set defaults for http_health_check

In order to fix the failing test in the preceding commit when optional
params are changed from their default "computed" values.

These weren't working well with `HttpHealthCheck.Patch()` because it was
attempting to set all unspecified params to Go's type defaults (eg. 0 for
int64) which the API rejected.

Changing the call to `HttpHealthCheck.Update()` seemed to fix this but it
still didn't allow you to reset a param back to it's default by no longer
specifying it.

Settings defaults like this, which match the Terraform docs, seems like the
best all round solution. Includes two additional tests for the acceptance
tests which verify the params are really getting set correctly.

### CODE REVIEW

**Comment by sparkprime** [comment]
Thanks, and this is interesting... It seems the lesson here is that the APIs don't allow an easy way to return a resource back to its default values.  Terraform needs that unless it is driving the defaults itself.  So I guess Terraform will have to drive all default values.  That applies to more GCP resources than just this one.

I am less certain about whether it is a good idea to change the defaults away from the Google defaults.  Won't this change behavior for existing users?  Do we need a state transfer function?  Personally I think it's probably better to keep the Google defaults as the Terraform defaults.  @phinze what do you think?

**Comment by sparkprime** [comment]
Ah sorry, I misread the chain of commits -- you are using the google defaults after all so ignore that last paragraph in my previous comment :)

**Comment by mitchellh** [comment]
@sparkprime don't forget to update the CHANGELOG too after merging :)

**Comment by sparkprime** [comment]
Ah yes, will do from now on :)

**Comment by dcarley** [comment]
Thanks!

**Pull request merged**
