### PR TITLE
go get cloud.google.com/go/storage@v1.28.0

### PR DESCRIPTION
**Pull request by SarahFrench**
Bumping the version of the `cloud.google.com/go/storage` dependency, used in the `gcs` backend.

This upgrade should allow users to use GCP identity federation, described in the linked issue below:

Possible fix for https://github.com/hashicorp/terraform/issues/29656

Replaces this out-dated PR: https://github.com/hashicorp/terraform/pull/30276

## Target Release

1.3.x, 1.4.x

### ENHANCEMENTS

 

-  backed/gcs: Updated storage package to v1.28.0

### CODE REVIEW

**Comment by SarahFrench** [comment]
Replacing this PR where I updated more dependencies than necessary: https://github.com/hashicorp/terraform/pull/32202

**Comment by SarahFrench** [comment]
I'm not sure what the solution is for the failing consistency test is - requested review for a bit of help!

**Comment by apparentlymart** [comment]
Hi @SarahFrench!

I'm just looking at the consistency check failure here first, since I don't think I have sufficient context to do a broader review of this (I'm not really familiar with the GCP backend).

I think we've run into something like this before when making changes to our protobuf tooling. I think what's happening here is that we have two different tools with different opinions about what this generated code ought to look like:
* The protobuf compiler is copying a comment verbatim from the source `.proto` file, leaving it formatted exactly how it was formatted in the source file.
* The `go fmt` command in recent Go versions has new opinions about how documentation comments should be formatted, and so it wants to rewrite some of those generated comments to meet the new style.

I think we'll need to eventually fix this properly by making the protobuf generation script also run the Go formatter on its results so that it's always generating code that will pass formatting.

In the meantime though, I looked back at the last PR where I encountered this (#31655) and it looks like I made it work by running `go fmt ./...` first and _then_ running `make protobuf` so that the files in my PR were the style that the protobuf compiler thinks is correct, rather than the style that the `go fmt` tool thinks is correct. I must admit I'm not sure _why_ that worked in retrospect, since I would expect the format check step to then fail instead, but since that did seem to work for me last time I'd suggest we try that first and see if it works. If not then we can consider other options.

**Comment by SarahFrench** [comment]
@apparentlymart - Thanks for posting the above context, I wasn't aware of differences in Go 1.19's fmt! After I upgraded from 1.18 to 1.19 locally I've been able to get the current consistency checks to be happy 😀

**Review by apparentlymart — APPROVED** [review]
I'm not familiar enough with the GCP backend to be able to review this beyond the shallow level of "yes, this does indeed upgrade this dependency to v1.28.0" :grinning: but I trust that you've tested it in the ways that make sense for this backend and so I've no objection to merging it.

**Comment by SarahFrench** [comment]
In terms of testing I've:
- Checked the [package's release notes](https://github.com/googleapis/google-cloud-go/releases?expanded=true&page=3&q=storage%2Fv1) for breaking changes - saw none
- Run all the automated acceptance tests - all passed
- Built this branch locally and manually tested `init`/`apply`/`import` actions

I've edited the release note to be more conservative and just describe the release bump instead of the expected result that it helps with the issue linked in the PR description.

With all this I'm as confident as I can be that the dependency bump isn't going to cause issues, and I've tried to avoid over promising the bump's effect on GCP identity federation (as I don't have the resources to test that fully).

**Pull request merged**
