### PR TITLE
[WIP] Initial Work to create AzureRM Extensions

### PR DESCRIPTION
**Pull request by stack72**
Work to allow AzureRM Extensions (for things like joining a domain)

* [ ] schema
* [ ] CRUD
* [ ] acceptance tests
* [ ] documentation

### CODE REVIEW

**Comment by clintonm9** [comment]
@stack72 This feature would be perfect for our use case. If you need anyone to test, just let me know.

**Comment by clintonm9** [comment]
@stack72 I got to spend some time playing with this feature today. Seems very useful to us AzureRM people. 

I ended up using version 1.4 of the customScriptForLinux (type_handler_version = "1.4")

I got the commandToExecute to work well. Did you get to the point where you could set an array of file_uris?

Thanks

**Comment by stack72** [comment]
oh you have tried this branch?

**Comment by clintonm9** [comment]
I did, hope that is ok.

**Comment by stack72** [comment]
that's brilliant that it sort of worked for you :)

I will get the fileUrls working - I have some issues to fix first due to their SDK api for that part :(

**Comment by stack72** [comment]
@clintonm9 

So I am not that familiar with Azure VMs. What sources would you use for a file uri here? Can I just put a simple bash script into a github gist and use that?

P.

**Comment by clintonm9** [comment]
@stack72 

You are correct. That would work.

We currently upload to a storage account in azure then link from there with our powershell scripts.

**Comment by stack72** [comment]
and for that scenario you would need private_settings declared as well right?

**Comment by clintonm9** [comment]
Currently we are not using the SA name and key (if this is what private_setting is).

We just set the files to Blob (which makes them accessible from a public url)

**Comment by clintonm9** [comment]
@stack72 Any updates on when this PR will be completed?

Thanks!

**Comment by stack72** [comment]
ok, after looking into this more, there is no way that this is easily achieved with Terraform. The Extension schema is **very specific** to each extension type. The work here is only for CustomExtensions. We can continue down that path if we want to but this will then only work for that type

There are many different types: https://acom-swtest-2.azurewebsites.net/en-gb/documentation/articles/virtual-machines-extensions-configuration-samples-linux/

@jen20 would love your thoughts here

P

**Comment by jen20** [comment]
I guess we should support some of the ones that seem useful (on a case-by-case basis) on that page and the custom one that is part of this PR. I don't know offhand what is useful though!

**Comment by gambrose** [comment]
@stack72
What is the status of vm extensions? You seemed to imply that it was too hard to do. So I'm thinking this feature my have been put on ice. But I'm hoping you have some master plan as I think this is a really important feature to support.

I have been adding extensions to my vms using azurerm_template_deployment after the vm has been created but this seems pretty hacky.

You linked to VM extensions from Linux. For what is worth these extensions are really useful for windows vms as well. I mostly use the DSC one myself to bootstrap the vm configuration.

Also if there is a plan for vm extensions would this include adding extensions to vm scale sets?

**Comment by stack72** [comment]
Hi all

I am going to close this out. I am not getting time right now to circle back to it but i know that @tombuildsstuff is looking at this :)

P.

**Pull request closed without merging**
