### PR TITLE
provider/openstack: Boot From Volume and Image Handling Fixes

### LINKED ISSUE #2189: Openstack provider : after image upgrade, refresh fails
Hi,
I deployed a stack on our Openstack env, everything went well.
Our ops team upgraded the Ubuntu image I used to boot my vms (image uuid changed).
The image ID changed so when terraform tried to refresh the local state file, I had an error because the original image was not available anymore in Glance catalog.

I'am now stuck, neither "plan", "destroy", "apply" go through. It ends with the error :
 Error refreshing state: 5 error(s) occurred:

* 1 error(s) occurred:

* Expected HTTP response code [200] when accessing [GET https://compute.fr1.cloudwatt.com/v2/1b1286db216e403694802b41c4137182/images/cc2e31fc-c24d-4905-bb45-1d57794a4f3c], but got 404 instead
{"itemNotFound": {"message": "Image not found.", "code": 404}}
[...]

### LINKED ISSUE #3206: openstack_compute_instance_v2  block_device - boot from volume
Hello, I am not understanding how this works and would like some clarifications. (I am using my private openstack cluster "Juno" and not rackspace or similar). Basically I would like to use a volume as a rootfs in an instance.

First, it seems to me that if I was to specify a block_device block in my instance resource, the image_id or image_name should not be required.

From the source_type and destination_type parameters, I am understanding that this should create a volume, but it is not the case.

```
  block_device {
    uuid = "${var.image_id}"
    source_type = "snapshot"
    volume_size = 8
    boot_index = 0
    destination_type = "volume"
  }
```

It seems that the block_device stanza never does anything.

Below is the instance information for an instance created with the "boot from image (creates new volume)" option in the horizon interface. Notice how the image parameter is "Attempt to boot from volume - no image supplied", and there is effectively one volume attached, which was used to boot the instance.
```
+--------------------------------------+----------------------------------------------------------+
| Property                             | Value                                                    |
+--------------------------------------+----------------------------------------------------------+
| OS-DCF:diskConfig                    | AUTO                                                     |
| OS-EXT-AZ:availability_zone          | nova                                                     |
| OS-EXT-SRV-ATTR:host                 | node-69.domain.tld                                       |
| OS-EXT-SRV-ATTR:hypervisor_hostname  | node-69.domain.tld                                       |
| OS-EXT-SRV-ATTR:instance_name        | instance-00000048                                        |
| OS-EXT-STS:power_state               | 1                                                        |
| OS-EXT-STS:task_state                | -                                                        |
| OS-EXT-STS:vm_state                  | active                                                   |
| OS-SRV-USG:launched_at               | 2015-09-10T15:01:10.000000                               |
| OS-SRV-USG:terminated_at             | -                                                        |
| accessIPv4                           |                                                          |
| accessIPv6                           |                                                          |
| config_drive                         |                                                          |
| created                              | 2015-09-10T14:58:14Z                                     |
| flavor                               | t2.small (b9b9cd94-4cfd-41e9-8863-b9ffeab7c9d4)          |
| hostId                               | e64e13e2745fe1bad894eda65b245378b9c6a3f1f8364b8cbe54201f |
| id                                   | 0edf517b-5ada-4242-b933-5e18fda0cfdb                     |
| image                                | Attempt to boot from volume - no image supplied          |
| key_name                             | test                                                     |
| metadata                             | {}                                                       |
| name                                 | test                                                     |
| net04 network                        | 192.168.111.17                                           |
| os-extended-volumes:volumes_attached | [{"id": "d3949ea6-33c4-42f0-b8fa-26e829949606"}]         |
| progress                             | 0                                                        |
| security_groups                      | default                                                  |
| status                               | ACTIVE                                                   |
| tenant_id                            | c7ca4adfa34342519ba20424d7b18ce3                         |
| updated                              | 2015-09-10T15:01:11Z                                     |
| user_id                              | ba276e7f36f34d2b8830f0e97fd71e93                         |
+--------------------------------------+----------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by jtopjian**
Fixes #3206
Fixes #2189

The above two issues had some overlap with regard to how images were handled. Because of the overlap, I felt it was more efficient to create a PR that fixed both.

For individual fixes of the above two issues, see #3225 and #3202, however a third PR would need to be created after both were merged to finish off the changes.

The commit message in each commit of this PR should explain the changes, though please let me know if any clarification is needed.

### CODE REVIEW

**Comment by jtopjian** [comment]
Can I do anything else to move this PR along?

**Comment by jfchevrette** [comment]
+1 I'm stuck on the same issue where I need to specify an image name or id even though I am booting from volume

**Comment by jtopjian** [comment]
I was really hoping to merge this today, but it looks like there's been a change with how Boot From Volume is handled in OpenStack Liberty.

I have a patch into Gophercloud to get it resolved: https://github.com/rackspace/gophercloud/pull/509

**Comment by jtopjian** [comment]
Gophercloud has been fixed. Doing one final review of the code and running acceptance tests, then merging.

@phinze This will require the latest commit for Gophercloud. Does that need noted anywhere for building the releases?

**Pull request merged**
