### PR TITLE
provider/azurerm: set resource_group_name on resource import

### PR DESCRIPTION
**Pull request by carinadigital**
Fix for GH-9072

I will add more resources as I test them.

### CODE REVIEW

**Comment by stack72** [comment]
Hi @carinadigital 

Thanks for the work here, this is a great addition!!! - if you are getting these added - can you also remove the `ImportStateVerifyIgnore: []string{"resource_group_name"},` from the import_arm_*_test.go files? :)

Thanks

Paul

**Comment by carinadigital** [comment]
There's another issue thrown up by the tests. The capitalisation of resource_group_name from the storage account acceptance fails due to the capitalisation.

**Comment by carinadigital** [comment]
@stack72 Would adding a DiffSuppressFunc()  https://github.com/hashicorp/terraform/blob/master/helper/schema/schema.go#L62 to resource_group_name inside most azurerm resources schema be a good solution to this?

It should just ignore the diff when the .ToLower() is equal. This will allow the name to stay capitalised for display purposes.

**Comment by carinadigital** [comment]
I've gone through the first half of the importable resource today. I'll try to complete them tomorrow.

**Comment by stack72** [comment]
@carinadigital this is awesome :)

**Comment by carinadigital** [comment]
I've found 4 resources that always store resource_group_name in lowercase. I'm not sure why this is the case.
```
azurerm_traffic_manager_endpoint
azurerm_dns_zone
azurerm_traffic_manager_profile
azurerm_traffic_manager_endpoint
```

I've not yet completed a fully run of the acceptance tests to see if there are anymore.

**Comment by carinadigital** [comment]
@stack72 This is ready for a review.
This should have an azurerm acceptance test run. FYI it took over 2hours on my machine.

**Comment by stack72** [comment]
Hi @carinadigital 

Thanks for the work here - this LGTM! All tests are passing as expected:

```
% make testacc TEST=./builtin/providers/azurerm TESTARGS='-run=_import'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/10/07 12:48:38 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/azurerm -v -run=_import -timeout 120m
=== RUN   TestAccAzureRMAvailabilitySet_importBasic
--- PASS: TestAccAzureRMAvailabilitySet_importBasic (100.66s)
=== RUN   TestAccAzureRMDnsZone_importBasic
--- PASS: TestAccAzureRMDnsZone_importBasic (92.71s)
=== RUN   TestAccAzureRMLocalNetworkGateway_importBasic
--- PASS: TestAccAzureRMLocalNetworkGateway_importBasic (124.95s)
=== RUN   TestAccAzureRMNetworkSecurityGroup_importBasic
--- PASS: TestAccAzureRMNetworkSecurityGroup_importBasic (126.42s)
=== RUN   TestAccAzureRMNetworkSecurityRule_importBasic
--- PASS: TestAccAzureRMNetworkSecurityRule_importBasic (167.86s)
=== RUN   TestAccAzureRMPublicIpStatic_importBasic
--- PASS: TestAccAzureRMPublicIpStatic_importBasic (127.65s)
=== RUN   TestAccAzureRMResourceGroup_importBasic
--- PASS: TestAccAzureRMResourceGroup_importBasic (76.44s)
=== RUN   TestAccAzureRMServiceBusSubscription_importBasic
--- PASS: TestAccAzureRMServiceBusSubscription_importBasic (365.62s)
=== RUN   TestAccAzureRMServiceBusTopic_importBasic
--- PASS: TestAccAzureRMServiceBusTopic_importBasic (366.95s)
=== RUN   TestAccAzureRMSqlFirewallRule_importBasic
--- PASS: TestAccAzureRMSqlFirewallRule_importBasic (127.38s)
=== RUN   TestAccAzureRMStorageAccount_importBasic
--- PASS: TestAccAzureRMStorageAccount_importBasic (139.00s)
=== RUN   TestAccAzureRMTrafficManagerEndpoint_importBasic
--- PASS: TestAccAzureRMTrafficManagerEndpoint_importBasic (144.72s)
=== RUN   TestAccAzureRMTrafficManagerProfile_importBasic
--- PASS: TestAccAzureRMTrafficManagerProfile_importBasic (82.50s)
=== RUN   TestAccAzureRMVirtualNetworkPeering_importBasic
--- PASS: TestAccAzureRMVirtualNetworkPeering_importBasic (213.47s)
=== RUN   TestAccAzureRMVirtualNetwork_importBasic
--- PASS: TestAccAzureRMVirtualNetwork_importBasic (122.85s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/azurerm	2379.201s
```

Paul

**Pull request merged**
