### PR TITLE
Include sensitive metadata from the schema when building the json state output

### LINKED ISSUE #33055: Suddenly sensitive resource attributes are exposed by "terraform show" in latest Terraform version 1.4.x
### Terraform Version

```shell
Terraform v1.4.5
on windows_amd64
+ provider registry.terraform.io/confluentinc/confluent v1.36.0
+ provider registry.terraform.io/hashicorp/azuread v2.37.1
+ provider registry.terraform.io/hashicorp/azurerm v3.51.0
+ provider registry.terraform.io/hashicorp/external v2.3.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/time v0.9.1
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = ">= 1.3.2"

  backend "azurerm" {}

  required_providers {
    confluent = {
      source  = "confluentinc/confluent"
      version = "~> 1.36.0"
    }
  }
}
```
Please note the `required_providers`, I experience the issue with THIS provider, but it could be a more general issue and other providers might also be affected.

### Debug Output

I am sorry, I think it is not needed at the moment. Please let me know if you think debug output is important.

### Expected Behavior
Like in previous terraform versions (tested with 1.3.9), resource attributes marked as `sensitive` by a provider shall be not exposed in the `terraform show` statement, but masked behind a `(sensitive value)` placeholder.

### Actual Behavior

There was a change in behaviour, in Terraform 1.3.9 resource attributes marked as "sensitive" by a provider were masked by the text ` (sensitive value)`. Now - in Terraform 1.4.5 - these values are exposed and can be seen in clear text. No change of provider version happened, the only thing changed was the used Terraform version. 

Please see the attached screenshot. On the left hand side the output of Terraform 1.4.5 (values exposed), on the right hand side the output of Terraform 1.3.9 (sensitive values masked). Same code, same provider versions, only the Terraform version changed.

grafik

### Steps to Reproduce

1. Use a terraform module which utilizes attributes marked as sensitive
2. Use this terraform module to create an example resource
3. Run "terraform init" and "terraform apply"
4. Observe the output of `terraform show`, sensitive values are exposed in latest terraform version.

### Additional Context

_No response_

### References

[Reported this issue also to the affected provider](https://github.com/confluentinc/terraform-provider-confluent/issues/238), in case it is not terraform specific.

### PR DESCRIPTION
**Pull request by liamcervante**
This PR makes the `jsonstate` package include the sensitive metadata from the schema when building the `sensitive_values` entry in the JSON output.

Previously, we were only including information from the config (such as the `sensitive()`) function. This new behaviour matches the behaviour of the `jsonplan` package.

I am a little concerned that the tests seem to have been deliberately checking that this didn't happen, but it doesn't make sense to me that we wouldn't want this new behaviour. Basically, the tests were setting an attribute in the schema as sensitive and then were not including that attribute in the sensitive values. I'm hoping that was an oversight instead of something deliberate. I have updated the tests to reflect the new behaviour and they now require the sensitive metadata set from the schema.

Fixes #33055 

## Target Release

1.4.6

### BUG FIXES 

 

-  Fix a bug where the schemas sensitive metadata was being missed when creating the JSON state output for a `terraform show` command.

### CODE REVIEW

**Comment by apparentlymart** [comment]
I'm not 100% sure because this was quite a while ago now, but I think the odd treatment of statically-defined sensitive might be something related to https://github.com/hashicorp/terraform-plugin-sdk/issues/201 , which ended up in a stalled state because of some disagreement about which layers ought to be dealing with and paying attention to these sensitivity declarations.

Unfortunately I don't have the full context for this anymore so I don't really have a definitive helpful answer here, but I'm mentioning it in case it triggers a stronger memory for a different reviewer who might be able to share some context about whatever decision caused us to be testing for the apparently-incorrect behavior as the expected behavior. 🤔

**Comment by jbardin** [comment]
My bet here is that as the tests were added in bulk when it was a new package, the tests were written to pass rather than for correctness. The way the values are handled internally led to attributes which are indicated as `Sensitive` by the schema only being marked during evaluation, hence they don't have marks going into and out of the state. I don't think that was done purposely, rather it was just an evolution of how they used to be handled before we had marks. I think this lead to the new renderer relying on the state representation which had incomplete information.

**Comment by jbardin** [comment]
@apparentlymart, I don't think that is going to be related. That issue was really about the lack of structural attributes, for which there is a solution now! I don't know if the legacy SDK can or even should be updated to change how the schema is generated, but it is at least possible now.

**Comment by apparentlymart** [comment]
Thanks for checking!

I don't think there are any plans to change how the legacy SDK behaves now, but indeed you're right that in principle the SDK could choose to present these computed-only objects as structured-type attributes instead of plain object type attributes, if someone did want to change it, with some risk of it subtly changing behavior.

**Review by jbardin — APPROVED** [review]
It's not needed for the issue at hand, but we should probably follow up to make sure the stored state also records sensitive schema values to prevent this from being able to diverge elsewhere.

**Pull request merged**
