### PR TITLE
client side remote state encryption

### PR DESCRIPTION
**Pull request by StephanHCB**
This is an **early draft** for a solution to #9556

It implements client side symmetric encryption of the entire state, for all remote state storage backends. 

What gets sent to the remote state storage just looks like this:

`{"crypted":"e93e3e7ad343405525...dda4fc061"}`

The idea is that even the company that operates the remote state storage cannot read it. Of course, one should still configure all other protection mechanisms on the remote storage, this is just one layer of security, but I think it's a very important one.

Features:
- encryption algorithms are pluggable, I have implemented AES256 in CFB stream mode with a fresh random initialization vector generated each time and SHA256 hashing prior to encryption to check for payload integrity
- supports key rotation by giving an optional second key to try for decryption (you must cause a change in state to re-encrypt, but this could be a statefile-only resource)
- supports transparent encryption of existing non-encrypted state (you must cause a change in state to encrypt it)
- supports decrypting existing state by setting the key to blank (you must cause a change in state to decrypt it)
- has unit tests that demonstrate how it works and cover several complete encrypt/decrypt cycles

The change to existing code is minimal, see `states/remote/states.go`, I have basically inserted the encryption/decryption at the point at which Client.Get / Client.Put are invoked. As the result of the encryption is again json, this should hopefully work with all Clients with zero changes.

Right now, set the environment variable TF_REMOTE_STATE_ENCRYPTION to "AES256:<32 byte hex key>[:<32 byte optional fallback decryption key for key rotation>" as follows:

```export TF_REMOTE_STATE_ENCRYPTION="AES256:a0a1...d0d1"```

then call terraform as usual. 

Here are my questions:
- do you think this approach is feasible? Anything I've overlooked? I'm pretty new to the terraform codebase, so any pointers are very welcome
- should I use a different mechanism to obtain the keys rather than this environment variable?
- anything else?

Known open issues:
- of course I'll update the documentation once this gets to final state
- still missing unit test cases (such as decryption)
- acceptance tests
- some manual testing

### CODE REVIEW

**Comment by StephanHCB** [comment]
Successfully tested with azurerm backend.

Known limitation: approach won't work with extended backends (tf cloud), because those need access to the state for rather obvious reasons.

**Comment by simongottschlag** [comment]
That is cool @StephanHCB!

Could there be an option to use SOPS for the encryption enabling us to leverage their work and support for different KMS providers?

**Comment by StephanHCB** [comment]
> 
> 
> That is cool @StephanHCB!
> 
> Could there be an option to use SOPS for the encryption enabling us to leverage their work and support for different KMS providers?

Just took a look at it, and it seems they only expose decryption but not encryption as a library with a stable interface, see https://pkg.go.dev/go.mozilla.org/sops/decrypt?utm_source=godoc :(

**Comment by simongottschlag** [comment]
I'm no expert at SOPS and can be mistaken, but by looking here it seems like Tree is what's used here: https://github.com/mozilla/sops/blob/master/cmd/sops/encrypt.go

https://pkg.go.dev/go.mozilla.org/sops/v3#Tree.Encrypt

**Comment by binlab** [comment]
Awesome @StephanHCB! Hope this will be implemented soon!

**Comment by binlab** [comment]
> That is cool @StephanHCB!
> 
> Could there be an option to use SOPS for the encryption enabling us to leverage their work and support for different KMS providers?

Nice idea, in this way possible to use Vault Transit backend for encryption/decryption too

**Comment by StephanHCB** [comment]
I'm closing this draft PR in favor of https://github.com/hashicorp/terraform/pull/21558, see the comments there.

I have currently got all information I need to proceed.

**Comment by WhyNotHugo** [comment]
I don’t quite see how the linked PR is related. It seems to be encryption with a remote-managed key, and only for azure.

The AWS backend already supports this kind of encryption (with a KMS key used for the state bucket). That’s not the same as client-side encryption.

**Comment by StephanHCB** [comment]
> I don’t quite see how the linked PR is related. It seems to be encryption with a remote-managed key, and only for azure.

Read the latest two comments on the linked PR. 

We are working to expand it to cover the client-side case as well, but with optional key storage in azure key vault.

This was only a draft PR anyway, which I made to get some answers which I now have to continue working on this.

**Pull request closed without merging**
