### PR TITLE
provider/docker: #5298 Add support for docker run --user option

### PR DESCRIPTION
**Pull request by lvjp**
Implement add support for the docker run option

### CODE REVIEW

**Comment by stack72** [comment]
Hi @lvjp, please can you rebase this from master. There is no need to make a change to the CHANGELOG file - this is done when the PR is merged so we can make sure that the issue gets logged with the correct release

**Comment by lvjp** [comment]
Alright, I will try to do it within a day.

**Comment by stack72** [comment]
Thanks so much! No need to rush :)

**Comment by lvjp** [comment]
Done

**Comment by jen20** [comment]
Hi @lvjp! Thanks for doing this - the code looks good to me. One more minor change - could you remove the CHANGELOG entry from the PR - we generally do this on master as it leads to merge conflicts (as in this case!)

**Comment by stack72** [comment]
Hi @lvjp 

This looks good now - thanks so much for removing the CHANGELOG entry

Paul

**Pull request merged**
