### PR TITLE
govendor fetch github.com/hashicorp/go-plugin/...

### LINKED ISSUE #15756: 0.10.0: "terraform init" works, but "terraform plan" fails with "netrpc: connect: no such file or directory"
Hello,

I have a custom provider called `myprovider` which I recently upgraded to terraform 0.10.0 using Go `dep` tool. My toml file looks like:

```toml
[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.10.0"
```

Then I built the binary and delivered it as a zip file to a VM, along with the one available in the Terraform downloads page. I tried running some HCL file and it prompted me to run `terraform init` which I did, and then when ran `terraform plan` I get the following:

```text
$ ./terraform plan
Error asking for user input: 1 error(s) occurred:

* provider.myprovider: dial unix /tmp/plugin263716127|netrpc: connect: no such file or directory
```

If I only define the provider with no resources, it works fine by saying "No changes. Infrastructure is up-to-date."

More info below:

### Terraform Version

```text
$ ./terraform version
Terraform v0.10.0
```

### Terraform Configuration Files

This works (returns there's no changes and infrastructure is up-to-date):

```hcl
provider "myprovider" {
  region = "demo"
}
```

Whereas this fails with the error mentioned above:

```hcl
provider "myprovider" {
  region = "demo"
}

resource "myprovider_instance" "default" {}
```

Do note that running `terraform apply` on 0.9.11 will fail since it doesn't have some required fields defined in the HCL code.

### Debug Output

[Link here](https://gist.github.com/a3d43a687c598510cc1196b1c39c3039)

### Expected Behavior
It should detect and run the provider and say that the validation for required attributes failed.

### Actual Behavior
It fails with the message `dial unix /tmp/plugin363438245|netrpc: connect: no such file or directory`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Compile a custom terraform provider from Go code
2. Download terraform from the releases page and place it the same folder as the compiled terraform provider
3. Zip and scp or similar both the provider and terraform to other machine (or the same machine).
4. Create a terraform file with just the provider definition and no resources, and run `terraform plan`. See it prompts for running `terraform init`.
5. Run `terraform init`, checks that it successfully executes
6. Run `terraform plan` again.
7. Notice it works okay.
8. Modify the HCL code to add an empty resource from your custom provider.
9. Run `terraform plan` again, notice it fails with the error message.

### Important Factoids
Virtual Machine, running Ubuntu:

```text
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

The interesting part is, it only fails when adding a resource, but with no resource and just the provider declaration it works perfectly.

### PR DESCRIPTION
**Pull request by apparentlymart**
This puts us on a version that has grpc protocol support. Although we're not actually using that yet, the plugin has handshake changed slightly to allow plugins to declare whether they use the old or new protocols, and so this upgrade allows us to support plugins that were built against newer versions of `go-plugin` that include this extra field in the handshake.

This fixes #15756.

### CODE REVIEW

**Comment by jbardin** [comment]
The grpc vendor versions are out of sync. I think you need to refresh the whole `google.golang.org/grpc` vendor tree.

**Comment by apparentlymart** [comment]
Heh sorry was working on that in my terminal... should've said not to review it yet. Hopefully this new commit fixes it. :grinning:

**Comment by apparentlymart** [comment]
Hmm looks like I now have a test failure that I didn't get locally. Will poke some more!

**Comment by apparentlymart** [comment]
Looks like we were lagging on the experimental `http2` library too, and `grpc` uses that at this time. So this now upgrades:
* go-plugin
* `google.golang.org/grpc`
* `golang.org/x/net/http2`

**Comment by apparentlymart** [comment]
Ooookay... @jbardin, this seems to actually be ready now!

**Pull request merged**
