### PR TITLE
Adding Govomi Debug Logging Capability and refactoring of integration tests

### PR DESCRIPTION
**Pull request by chrislovecnm**
Also refactored some of the integration tests.

### CODE REVIEW

**Comment by jen20** [comment]
Hi @chrislovecnm! Initial impressions of this look good - is it ready for integration as far as you are concerned? It would be nice to get it into our beta of Terraform 0.7. I have no way of running the acceptance tests so to some extend I'm relying on your or one of the other contributors running them. It would be great if you could post the output of `make testacc TEST=./builtin/provider/vsphere` as a comment on this? Thanks for your work here!

**Comment by chrislovecnm** [comment]
@jen20 some of @dkalleg tweaks to our tests have broken running them in my environment :(  I have reached out to him to determine what I need to do.  The basic test and debug tests are passing on my test cluster.

**Comment by chrislovecnm** [comment]
Need some TLC on the unit tests :(

**Comment by chrislovecnm** [comment]
@jen20 here is the results of local testing. https://gist.github.com/chrislovecnm/80dab5b30fad211f6c40fde0bc6b6ac2

The failures are expected:
- tf_file_test.vmdk - don't have a file for testing
- ipv6 not working on my network, so it fails
- createWithExistingVmdk - no existing vmdk

Fixed a couple more of the tests after my refactor.  Hopefully the tests are more readable and less fragile now.

**Comment by chrislovecnm** [comment]
@jen20 any comments on this?  I can squash the comments and we can get this in

**Comment by chrislovecnm** [comment]
@jen20 @stack72 might we get a merge??

**Comment by stack72** [comment]
Hi @chrislovecnm 

this will need rebased before we can merge

P.

**Comment by chrislovecnm** [comment]
@stack72 this is fun ...

**Comment by chrislovecnm** [comment]
@stack72 ~ Paul all good to go now.  We need to get this in before more.  This is a major rework of our tests, and it a pain to merge into :(  If you don't mind I will let you squash, as I want to keep the commits the same on my branch

**Comment by chrislovecnm** [comment]
@jen20 @stack72 ~ can I ask to get this in next.  This is a large refactor on our testing code, and is not a easy merge.  The quicker it is in, the less crazy rebases we will have.

**Comment by jen20** [comment]
@chrislovecnm Can you post a log of the acceptance tests run with this set of commits integrated?

**Comment by chrislovecnm** [comment]
@jen20 already did mate - https://gist.github.com/chrislovecnm/80dab5b30fad211f6c40fde0bc6b6ac2

**Comment by chrislovecnm** [comment]
@jen20 

```console
==> Checking that code complies with gofmt requirements...
/Users/clove/Workspace/bin/stringer
go generate $(go list ./... | grep -v /vendor/)
2016/06/02 11:41:06 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/vsphere -v -run TestAccVSphereVirtualMachine_mac_address -timeout 120m
=== RUN   TestAccVSphereVirtualMachine_mac_address
2016/06/02 11:41:29 [DEBUG] template=
resource "vsphere_virtual_machine" "mac_address" {
    name = "terraform-mac-address"
%s
    vcpu = 2
    memory = 1024
    network_interface {
        label = "%s"
        mac_address = "%s"
    }
    disk {
%s
        template = "%s"
    }
}
2016/06/02 11:41:29 [DEBUG] template config=
resource "vsphere_virtual_machine" "mac_address" {
    name = "terraform-mac-address"
    datacenter = "Engpipeline Datacenter"
    cluster = "Engpipeline-cluster"

    vcpu = 2
    memory = 1024
    network_interface {
        label = "VM-vlan409"
        mac_address = "f6:5c:89:2b:a0:64"
    }
    disk {
        datastore = "BEL-5798813-EMC-VMAX1789-LUN-06"

        template = "centos-clove-tpl"
    }
}
--- PASS: TestAccVSphereVirtualMachine_mac_address (153.03s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/vsphere	153.056s
```

**Comment by chrislovecnm** [comment]
@jen20 btw after the PR I am working, the one after this one, on I am going to get Jenkins running our integration testing on one of our clusters.

**Comment by chrislovecnm** [comment]
@jen20 let me now if that is what you need.  Always appreciate your and @stack72's help!!

**Comment by chrislovecnm** [comment]
This address https://github.com/hashicorp/terraform/issues/6964 as well

**Comment by stack72** [comment]
LGTM! Thanks @chrislovecnm :)

**Comment by chrislovecnm** [comment]
Appreciated @stack72 ... now I get the joy of merging my mess back on to master ... rebase hell today :(

**Pull request merged**
