### PR TITLE
Add Terraform/Remote State documentation to provider/resource section.

### PR DESCRIPTION
**Pull request by johnrengelman**
Issue #2074

### CODE REVIEW

**Comment by radeksimko** [comment]
Although I may agree with you the current place is not the best place for newcomers, I'm not overly happy with duplicating the docs since it would become difficult to maintain and keep in sync across these places.

**Comment by johnrengelman** [comment]
How about leaving the portions about the resource usage in the 'Resource section' and just providing links on each?

**Comment by josephholsten** [comment]
@radeksimko @johnrengelman did you two come to an agreement? I'm personally in favor of having the doc in one authoritative place, and a link to it in the other place.

**Comment by phinze** [comment]
I'm +1 for moving the canonical docs over to this structured resource format and linking off to them from the state docs. @johnrengelman do you have time to add the links? If not one of us can close this and resubmit for you with the additions.

**Comment by johnrengelman** [comment]
@phinze I'll get this updated this week. I started on it last week and then got lazy.

**Comment by johnrengelman** [comment]
@phinze updated and pushed. Let me know what you think.

**Comment by apparentlymart** [comment]
I like this organization of the docs much better. Thanks!

The main page of the Terraform provider talks a lot about it being a "logical provider". While it's true that it currently only has one resource and that is a logical resource, I'm not sure the concept of a "logical provider" is really meaningful. If #3164 were accepted, this provider would contain both a logical resource and a "normal" resource.

Could we instead put all of the explanation about the logical resource on the ``terraform_remote_state`` doc page, and just have the provider index page just talk about this provider being used to interact with the results from other Terraform configurations?

Of course #3164 may be considered a bad idea and so such factoring may not be needed, so I'd be fine with merging this as-is and then I'll adjust the docs as I described as part of finishing that other PR.

**Comment by radeksimko** [comment]
@johnrengelman Thank you for bringing up this PR. The current state LGTM. I will merge it separately due to some conflicts in the attached branch. Thank you for the patience.

> If #3164 were accepted, this provider would contain both a logical resource and a "normal" resource.

@apparentlymart While I'm really looking forward to see #3164 or #4169 :smiley: , I'm feeling it may take some time to fine-tune the concept and more importantly to implement it and I believe that docs should reflect the current state at least.

**Pull request closed without merging**
