### PR TITLE
fix(aws): volume attachment only forcenew on name

### PR DESCRIPTION
**Pull request by dudymas**
This is for #5240 

I'm being heavily affected by this and I found the only recourse was to sort of break convention.
## Summary

The aws_volume_attachment resource currently assumes creation and deletion whenever you alter its count. The reason for this is that the diff shows a change when it compares the calculated values for the volume or instance id ( usually something like"${element(aws_instance.foo.*.id, count.index)}" ).

Rather than waiting to see if the calculation actually changes an identifier (and usually it won't if you are just adding another instance and volume), the attachment immediately goes to delete/create .
## Example

Given a tfstate were `terraform apply` just succeeded for the following resources :

```
variable "dracula" { default = "2" }

resource "aws_volume_attachment" "foo_att" {
  count = "${var.dracula}"
  device_name = "/dev/sdh"
  volume_id = "${aws_ebs_volume.example.id}"
  instance_id = "${aws_instance.web.id}"
}

resource "aws_instance" "foo" {
  count = "${var.dracula}"
  ami = "ami-21f78e11"
  availability_zone = "us-west-2a"
  instance_type = "t1.micro"
}

resource "aws_ebs_volume" "v" {
  count = "${var.dracula}"
  availability_zone = "us-west-2a"
  size = 1
}
```

If I change dracula to be "3"

We expect for `terraform apply` to just make another instance, another volume, then attach the two.

Instead, the first two volume attachments are destroyed. Then recreated. then the expected behavior starts.
## The fix

Presently, I'm unaware of why the 'diff' functions built-in to terraform do not identify that no change has occurred.

Instead of trying to dig into the graph and unearth the failure to check for changes, I merely alter the schema. Instead of forcing new resources on changes to instance id and/or volume id, I just allow them to update the resource.

This fixes the issue, and only has the 'code smell' of being a little less than honest (because the 'Update' just does a delete/create)
## Closing thoughts

I think this is an acceptable fix because the nature of volume attachments does not follow that of a true resource. As it is... terraform has to 'invent' an id for the resource since aws doesn't really worry about one. The attachment behaves more akin to a 'pointer', essentially binding two resources to one another. As such, the Update really doesn't make much of a difference, since whether you forcenew or not... it doesn't change the fact that attachments aren't really modeled well in terraform.

This isn't a reflection of terraform... merely an observation of how aws has made volume attachments.... difficult to idempotentize [ pull request for adding that word to webster is forthcoming ]

### CODE REVIEW

**Comment by SpencerBrown** [comment]
also I believe addresses issue:  #5691 

I will try to test this today

**Comment by dudymas** [comment]
thanks @SpencerBrown ... let me know how it goes... I'll try to fix any problems you find... I haven't seen any myself... but I've hardly an exhaustive use case

**Comment by SpencerBrown** [comment]
Welp, it's a bit rocky. 
running `Terraform v0.6.15-dev (cfbe11b126e1ba307569e8912598f24e403b4b2d+CHANGES)` with your modified .go file

I have a cluster I built previously with 3 workers. It uses the same pattern you are showing above, with a count variable for both the aws_ebs_volume, the aws_ebs_volume_attachment, and the aws_instance.

when I change the count from 3 to 2,  I get this for the plan:

```

- aws_ebs_volume.docker.2

~ aws_elb.proxy
    instances.#:          "3" => "2"
    instances.2509988165: "i-b4a52b6c" => "i-b4a52b6c"
    instances.3256702759: "i-1989fec1" => ""
    instances.425464228:  "i-08a628d0" => "i-08a628d0"

- aws_instance.kube_worker.2

- aws_route.worker_priv.2

- aws_route.worker_pub.2

- aws_volume_attachment.docker.2


Plan: 0 to add, 1 to change, 5 to destroy.
```

and applying the plan kind of works. It times out waiting for the volume to detach as part of destroying the aws_volume_attachment. I rerun the plan and now it tries to delete the volume in parallel with destroying the instance, so it times out again. Then I rerun it a third time and now it destroys the volume and all is happy. 

Now, I try changing the count from 2 back to 3. 

I still get Terraform trying to modify the existing volume attachments. Here's the plan it generates:

```

Path: tf.plan

+ aws_ebs_volume.docker.2
    availability_zone: "" => "us-west-2a"
    encrypted:         "" => "<computed>"
    iops:              "" => "<computed>"
    kms_key_id:        "" => "<computed>"
    size:              "" => "10"
    snapshot_id:       "" => "<computed>"
    tags.#:            "" => "1"
    tags.Name:         "" => "tst-worker-03-docker"
    type:              "" => "gp2"

~ aws_elb.proxy
    instances.#: "" => "<computed>"

+ aws_instance.kube_worker.2
    ami:                                       "" => "ami-03de3c63"
    availability_zone:                         "" => "us-west-2a"
    ebs_block_device.#:                        "" => "<computed>"
    ephemeral_block_device.#:                  "" => "<computed>"
    iam_instance_profile:                      "" => "tst-master-profile"
    instance_state:                            "" => "<computed>"
    instance_type:                             "" => "t2.medium"
    key_name:                                  "" => "kube-key-tst"
    placement_group:                           "" => "<computed>"
    private_dns:                               "" => "<computed>"
    private_ip:                                "" => "172.20.1.32"
    public_dns:                                "" => "<computed>"
    public_ip:                                 "" => "<computed>"
    root_block_device.#:                       "" => "1"
    root_block_device.0.delete_on_termination: "" => "1"
    root_block_device.0.iops:                  "" => "<computed>"
    root_block_device.0.volume_size:           "" => "10"
    root_block_device.0.volume_type:           "" => "gp2"
    security_groups.#:                         "" => "<computed>"
    source_dest_check:                         "" => "0"
    subnet_id:                                 "" => "subnet-c8d8c4bf"
    tags.#:                                    "" => "3"
    tags.DatadogMonitoring:                    "" => "no"
    tags.KubernetesCluster:                    "" => "tst"
    tags.Name:                                 "" => "tst-kube-worker-03"
    tenancy:                                   "" => "<computed>"
    vpc_security_group_ids.#:                  "" => "1"
    vpc_security_group_ids.827882231:          "" => "sg-34e16353"

~ aws_route.worker_priv.0
    instance_id: "i-08a628d0" => "${element(aws_instance.kube_worker.*.id, count.index)}"

~ aws_route.worker_priv.1
    instance_id: "i-b4a52b6c" => "${element(aws_instance.kube_worker.*.id, count.index)}"

+ aws_route.worker_priv.2
    destination_cidr_block:     "" => "10.1.32.0/24"
    destination_prefix_list_id: "" => "<computed>"
    gateway_id:                 "" => "<computed>"
    instance_id:                "" => "${element(aws_instance.kube_worker.*.id, count.index)}"
    instance_owner_id:          "" => "<computed>"
    nat_gateway_id:             "" => "<computed>"
    network_interface_id:       "" => "<computed>"
    origin:                     "" => "<computed>"
    route_table_id:             "" => "rtb-c14094a5"
    state:                      "" => "<computed>"

~ aws_route.worker_pub.0
    instance_id: "i-08a628d0" => "${element(aws_instance.kube_worker.*.id, count.index)}"

~ aws_route.worker_pub.1
    instance_id: "i-b4a52b6c" => "${element(aws_instance.kube_worker.*.id, count.index)}"

+ aws_route.worker_pub.2
    destination_cidr_block:     "" => "10.1.32.0/24"
    destination_prefix_list_id: "" => "<computed>"
    gateway_id:                 "" => "<computed>"
    instance_id:                "" => "${element(aws_instance.kube_worker.*.id, count.index)}"
    instance_owner_id:          "" => "<computed>"
    nat_gateway_id:             "" => "<computed>"
    network_interface_id:       "" => "<computed>"
    origin:                     "" => "<computed>"
    route_table_id:             "" => "rtb-c04094a4"
    state:                      "" => "<computed>"

~ aws_volume_attachment.docker.0
    instance_id: "i-08a628d0" => "${element(aws_instance.kube_worker.*.id, count.index)}"
    volume_id:   "vol-02c4c0c2" => "${element(aws_ebs_volume.docker.*.id, count.index)}"

~ aws_volume_attachment.docker.1
    instance_id: "i-b4a52b6c" => "${element(aws_instance.kube_worker.*.id, count.index)}"
    volume_id:   "vol-d7c5c117" => "${element(aws_ebs_volume.docker.*.id, count.index)}"

+ aws_volume_attachment.docker.2
    device_name:  "" => "/dev/xvdd"
    force_detach: "" => "<computed>"
    instance_id:  "" => "${element(aws_instance.kube_worker.*.id, count.index)}"
    volume_id:    "" => "${element(aws_ebs_volume.docker.*.id, count.index)}"


Plan: 5 to add, 7 to change, 0 to destroy.
```

Interestingly, Terraform seems to have a similar bug with aws_route resources as it has with aws_volume_attachment ones.

I try applying this plan and Terraform crashes.

```

6 error(s) occurred:

* aws_route.worker_priv.1: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.6.15
    Resource ID: aws_route.worker_priv.1
    Mismatch reason: attribute mismatch: instance_id
    Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"instance_id":*terraform.ResourceAttrDiff{Old:"i-b4a52b6c", New:"${element(aws_instance.kube_worker.*.id, count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

* aws_route.worker_priv.0: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.6.15
    Resource ID: aws_route.worker_priv.0
    Mismatch reason: attribute mismatch: instance_id
    Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"instance_id":*terraform.ResourceAttrDiff{Old:"i-08a628d0", New:"${element(aws_instance.kube_worker.*.id, count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

* aws_route.worker_pub.1: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.6.15
    Resource ID: aws_route.worker_pub.1
    Mismatch reason: attribute mismatch: instance_id
    Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"instance_id":*terraform.ResourceAttrDiff{Old:"i-b4a52b6c", New:"${element(aws_instance.kube_worker.*.id, count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

* aws_route.worker_pub.0: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.6.15
    Resource ID: aws_route.worker_pub.0
    Mismatch reason: attribute mismatch: instance_id
    Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"instance_id":*terraform.ResourceAttrDiff{Old:"i-08a628d0", New:"${element(aws_instance.kube_worker.*.id, count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

* aws_volume_attachment.docker.0: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.6.15
    Resource ID: aws_volume_attachment.docker.0
    Mismatch reason: attribute mismatch: instance_id
    Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"instance_id":*terraform.ResourceAttrDiff{Old:"i-08a628d0", New:"${element(aws_instance.kube_worker.*.id, count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "volume_id":*terraform.ResourceAttrDiff{Old:"vol-02c4c0c2", New:"${element(aws_ebs_volume.docker.*.id, count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

* aws_volume_attachment.docker.1: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.6.15
    Resource ID: aws_volume_attachment.docker.1
    Mismatch reason: attribute mismatch: instance_id
    Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"instance_id":*terraform.ResourceAttrDiff{Old:"i-b4a52b6c", New:"${element(aws_instance.kube_worker.*.id, count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "volume_id":*terraform.ResourceAttrDiff{Old:"vol-d7c5c117", New:"${element(aws_ebs_volume.docker.*.id, count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.
```

HOWEVER:  a subsequent plan shows that no changes are needed! And, in fact, all the resources are correctly created on AWS.

So, it kind of works! If you just ignore the errors and keep running plan/apply until it's clean.

**Comment by dudymas** [comment]
@SpencerBrown okay... so for now, I need to go back and see what the in-betweens are. I think the issue is that I could probably get the code inside terraform itself to keep applying to within a limit, and this is a common phenomena with both terraform and aws apis.

I also think what I'm seeing here is a different in how I tested, and you nailed something I forgot: unclean force unmounts... I was usually hitting the node with ansible to detach/umount the volumes before running this. For an unresponsive vm that might not be an option, but again, the vm might be in a count of others with a count of ebs's ... brilliant.

I'll need some time to test these out and see what I can improve. Thanks for helping me on this guy

**Comment by dudymas** [comment]
Also, sorry for the slow response on this one... we both need this really bad, and now we also have a large crunch at my place, and so my focus has been on stabilizing gce. I've been told that since this fix is already working for what we have in aws, people are telling me not to focus on it... just the nature of the beast.

As such, if anyone wants to speed this up, please critique or otherwise request contributor status on my branch (I'd be happy to give it...). I quite literally I'm living the no idea what I'm doing

**Comment by SpencerBrown** [comment]
Thanks, @dudymas.

The issues when deleting a node go away completely when I manually stop the 3rd node before deleting it. I can live with this, and I think it's being addressed by another issue #5364 

However, the use case of adding a node still seems to want to change the volume attachments for ALL nodes. I just rebuilt on master with your updates and this is what I see for `terraform plan` after increasing the worker node count from 2 to 3. I thought the changes were supposed to make Terraform not mess with the volume attachments for nodes 0 and 1?

```

+ aws_ebs_volume.docker.2
    availability_zone: "" => "us-west-2a"
    encrypted:         "" => "<computed>"
    iops:              "" => "<computed>"
    kms_key_id:        "" => "<computed>"
    size:              "" => "10"
    snapshot_id:       "" => "<computed>"
    tags.#:            "" => "1"
    tags.Name:         "" => "tst-worker-03-docker"
    type:              "" => "gp2"

~ aws_elb.proxy
    instances.#: "" => "<computed>"

+ aws_instance.kube_worker.2
    ami:                                       "" => "ami-03de3c63"
    availability_zone:                         "" => "us-west-2a"
    ebs_block_device.#:                        "" => "<computed>"
    ephemeral_block_device.#:                  "" => "<computed>"
    iam_instance_profile:                      "" => "tst-master-profile"
    instance_state:                            "" => "<computed>"
    instance_type:                             "" => "t2.medium"
    key_name:                                  "" => "kube-key-tst"
    placement_group:                           "" => "<computed>"
    private_dns:                               "" => "<computed>"
    private_ip:                                "" => "172.20.1.32"
    public_dns:                                "" => "<computed>"
    public_ip:                                 "" => "<computed>"
    root_block_device.#:                       "" => "1"
    root_block_device.0.delete_on_termination: "" => "1"
    root_block_device.0.iops:                  "" => "<computed>"
    root_block_device.0.volume_size:           "" => "10"
    root_block_device.0.volume_type:           "" => "gp2"
    security_groups.#:                         "" => "<computed>"
    source_dest_check:                         "" => "0"
    subnet_id:                                 "" => "subnet-c8d8c4bf"
    tags.#:                                    "" => "3"
    tags.DatadogMonitoring:                    "" => "no"
    tags.KubernetesCluster:                    "" => "tst"
    tags.Name:                                 "" => "tst-kube-worker-03"
    tenancy:                                   "" => "<computed>"
    vpc_security_group_ids.#:                  "" => "1"
    vpc_security_group_ids.827882231:          "" => "sg-34e16353"

~ aws_route.worker_priv.0
    instance_id: "i-08a628d0" => "${element(aws_instance.kube_worker.*.id, count.index)}"

~ aws_route.worker_priv.1
    instance_id: "i-b4a52b6c" => "${element(aws_instance.kube_worker.*.id, count.index)}"

+ aws_route.worker_priv.2
    destination_cidr_block:     "" => "10.1.32.0/24"
    destination_prefix_list_id: "" => "<computed>"
    gateway_id:                 "" => "<computed>"
    instance_id:                "" => "${element(aws_instance.kube_worker.*.id, count.index)}"
    instance_owner_id:          "" => "<computed>"
    nat_gateway_id:             "" => "<computed>"
    network_interface_id:       "" => "<computed>"
    origin:                     "" => "<computed>"
    route_table_id:             "" => "rtb-c14094a5"
    state:                      "" => "<computed>"

~ aws_route.worker_pub.0
    instance_id: "i-08a628d0" => "${element(aws_instance.kube_worker.*.id, count.index)}"

~ aws_route.worker_pub.1
    instance_id: "i-b4a52b6c" => "${element(aws_instance.kube_worker.*.id, count.index)}"

+ aws_route.worker_pub.2
    destination_cidr_block:     "" => "10.1.32.0/24"
    destination_prefix_list_id: "" => "<computed>"
    gateway_id:                 "" => "<computed>"
    instance_id:                "" => "${element(aws_instance.kube_worker.*.id, count.index)}"
    instance_owner_id:          "" => "<computed>"
    nat_gateway_id:             "" => "<computed>"
    network_interface_id:       "" => "<computed>"
    origin:                     "" => "<computed>"
    route_table_id:             "" => "rtb-c04094a4"
    state:                      "" => "<computed>"

~ aws_volume_attachment.docker.0
    instance_id: "i-08a628d0" => "${element(aws_instance.kube_worker.*.id, count.index)}"
    volume_id:   "vol-02c4c0c2" => "${element(aws_ebs_volume.docker.*.id, count.index)}"

~ aws_volume_attachment.docker.1
    instance_id: "i-b4a52b6c" => "${element(aws_instance.kube_worker.*.id, count.index)}"
    volume_id:   "vol-d7c5c117" => "${element(aws_ebs_volume.docker.*.id, count.index)}"

+ aws_volume_attachment.docker.2
    device_name:  "" => "/dev/xvdd"
    force_detach: "" => "<computed>"
    instance_id:  "" => "${element(aws_instance.kube_worker.*.id, count.index)}"
    volume_id:    "" => "${element(aws_ebs_volume.docker.*.id, count.index)}"


Plan: 5 to add, 7 to change, 0 to destroy.
```

**Comment by SpencerBrown** [comment]
And when I apply the plan, I get the following. It seems that the new node and volume are properly created and attached, and the route table is updated, but then Terraform crashes because diffs aren't matching, on both the route tables and and the volume attachments.

So, the fix actually works, but it causes these effects on plan and apply when increasing the node count.

```
aws_ebs_volume.docker.2: Creating...
  availability_zone: "" => "us-west-2a"
  encrypted:         "" => "<computed>"
  iops:              "" => "<computed>"
  kms_key_id:        "" => "<computed>"
  size:              "" => "10"
  snapshot_id:       "" => "<computed>"
  tags.#:            "" => "1"
  tags.Name:         "" => "tst-worker-03-docker"
  type:              "" => "gp2"
aws_instance.kube_worker.2: Creating...
  ami:                                       "" => "ami-03de3c63"
  availability_zone:                         "" => "us-west-2a"
  ebs_block_device.#:                        "" => "<computed>"
  ephemeral_block_device.#:                  "" => "<computed>"
  iam_instance_profile:                      "" => "tst-master-profile"
  instance_state:                            "" => "<computed>"
  instance_type:                             "" => "t2.medium"
  key_name:                                  "" => "kube-key-tst"
  placement_group:                           "" => "<computed>"
  private_dns:                               "" => "<computed>"
  private_ip:                                "" => "172.20.1.32"
  public_dns:                                "" => "<computed>"
  public_ip:                                 "" => "<computed>"
  root_block_device.#:                       "" => "1"
  root_block_device.0.delete_on_termination: "" => "1"
  root_block_device.0.iops:                  "" => "<computed>"
  root_block_device.0.volume_size:           "" => "10"
  root_block_device.0.volume_type:           "" => "gp2"
  security_groups.#:                         "" => "<computed>"
  source_dest_check:                         "" => "0"
  subnet_id:                                 "" => "subnet-c8d8c4bf"
  tags.#:                                    "" => "3"
  tags.DatadogMonitoring:                    "" => "no"
  tags.KubernetesCluster:                    "" => "tst"
  tags.Name:                                 "" => "tst-kube-worker-03"
  tenancy:                                   "" => "<computed>"
  vpc_security_group_ids.#:                  "" => "1"
  vpc_security_group_ids.827882231:          "" => "sg-34e16353"
aws_ebs_volume.docker.2: Still creating... (10s elapsed)
aws_instance.kube_worker.2: Still creating... (10s elapsed)
aws_ebs_volume.docker.2: Creation complete
aws_instance.kube_worker.2: Still creating... (20s elapsed)
aws_instance.kube_worker.2: Still creating... (30s elapsed)
aws_instance.kube_worker.2: Still creating... (40s elapsed)
aws_instance.kube_worker.2: Still creating... (50s elapsed)
aws_instance.kube_worker.2: Creation complete
aws_route.worker_pub.2: Creating...
  destination_cidr_block:     "" => "10.1.32.0/24"
  destination_prefix_list_id: "" => "<computed>"
  gateway_id:                 "" => "<computed>"
  instance_id:                "" => "i-3fc5e9e7"
  instance_owner_id:          "" => "<computed>"
  nat_gateway_id:             "" => "<computed>"
  network_interface_id:       "" => "<computed>"
  origin:                     "" => "<computed>"
  route_table_id:             "" => "rtb-c04094a4"
  state:                      "" => "<computed>"
aws_volume_attachment.docker.2: Creating...
  device_name:  "" => "/dev/xvdd"
  force_detach: "" => "<computed>"
  instance_id:  "" => "i-3fc5e9e7"
  volume_id:    "" => "vol-0c834cbe"
aws_elb.proxy: Modifying...
  instances.#:          "2" => "3"
  instances.1043769016: "" => "i-3fc5e9e7"
  instances.2509988165: "i-b4a52b6c" => "i-b4a52b6c"
  instances.425464228:  "i-08a628d0" => "i-08a628d0"
aws_route.worker_priv.2: Creating...
  destination_cidr_block:     "" => "10.1.32.0/24"
  destination_prefix_list_id: "" => "<computed>"
  gateway_id:                 "" => "<computed>"
  instance_id:                "" => "i-3fc5e9e7"
  instance_owner_id:          "" => "<computed>"
  nat_gateway_id:             "" => "<computed>"
  network_interface_id:       "" => "<computed>"
  origin:                     "" => "<computed>"
  route_table_id:             "" => "rtb-c14094a5"
  state:                      "" => "<computed>"
aws_route.worker_priv.2: Creation complete
aws_route.worker_pub.2: Creation complete
aws_elb.proxy: Modifications complete
aws_volume_attachment.docker.2: Still creating... (10s elapsed)
aws_volume_attachment.docker.2: Creation complete
Error applying plan:

6 error(s) occurred:

* aws_route.worker_priv.0: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.6.15
    Resource ID: aws_route.worker_priv.0
    Mismatch reason: attribute mismatch: instance_id
    Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"instance_id":*terraform.ResourceAttrDiff{Old:"i-08a628d0", New:"${element(aws_instance.kube_worker.*.id, count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

* aws_route.worker_priv.1: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.6.15
    Resource ID: aws_route.worker_priv.1
    Mismatch reason: attribute mismatch: instance_id
    Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"instance_id":*terraform.ResourceAttrDiff{Old:"i-b4a52b6c", New:"${element(aws_instance.kube_worker.*.id, count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

* aws_route.worker_pub.0: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.6.15
    Resource ID: aws_route.worker_pub.0
    Mismatch reason: attribute mismatch: instance_id
    Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"instance_id":*terraform.ResourceAttrDiff{Old:"i-08a628d0", New:"${element(aws_instance.kube_worker.*.id, count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

* aws_route.worker_pub.1: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.6.15
    Resource ID: aws_route.worker_pub.1
    Mismatch reason: attribute mismatch: instance_id
    Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"instance_id":*terraform.ResourceAttrDiff{Old:"i-b4a52b6c", New:"${element(aws_instance.kube_worker.*.id, count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

* aws_volume_attachment.docker.1: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.6.15
    Resource ID: aws_volume_attachment.docker.1
    Mismatch reason: attribute mismatch: instance_id
    Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"volume_id":*terraform.ResourceAttrDiff{Old:"vol-d7c5c117", New:"${element(aws_ebs_volume.docker.*.id, count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instance_id":*terraform.ResourceAttrDiff{Old:"i-b4a52b6c", New:"${element(aws_instance.kube_worker.*.id, count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

* aws_volume_attachment.docker.0: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.6.15
    Resource ID: aws_volume_attachment.docker.0
    Mismatch reason: attribute mismatch: instance_id
    Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"instance_id":*terraform.ResourceAttrDiff{Old:"i-08a628d0", New:"${element(aws_instance.kube_worker.*.id, count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "volume_id":*terraform.ResourceAttrDiff{Old:"vol-02c4c0c2", New:"${element(aws_ebs_volume.docker.*.id, count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.


Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by apparentlymart** [comment]
Hello @dudymas, and thanks for working on this!

As part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it.

In the mean time a core change to Terraform has, I believe, fixed the root cause that motivated this change. Instead of using an expression like `element(aws_volume_attachment.docker.*.id, count.index)` it's now possible to use `aws_volume_attachment.docker.*.id[count.index]`, and this new form gives Terraform the information it needs to understand that the result depends only on the current index. Since `element` is just a normal function like any other, Terraform can't assume this and instead conservatively assumes that the result depends on the _entire_ list.

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Pull request closed without merging**
