### PR TITLE
terraform init: allow -get-plugins=true when -plugin-dir is set

### PR DESCRIPTION
**Pull request by kmoe**
## Background

`terraform init` has a number of mechanisms for locating provider plugins required by the Terraform config.

In normal operation, running `terraform init` triggers the "plugin discovery" mechanism, which will attempt to locate plugin binaries in a local cache before downloading missing plugins. This operation can be disabled with the `-get-plugins` flag, whose default value is `true`.

Users also have the option of supplying local directories containing plugin binaries, specified using one or more occurrences of the `-plugin-dir` flag, e.g. `terraform init -plugin-dir=/usr/local/plugins`. When `-plugin-dir` is set, the value of `-get-plugins` is forced to `false`, whether or not it is also passed in on the command line.

## Change

This PR allows the user to specify that the normal plugin discovery mechanism be used as a fallback when `-plugin-dir` is set. It is motivated by work on the plugin SDK acceptance testing framework (in which a special `-plugin-dir` must be set for the primary provider binary but users may want to load other providers), but it may be useful in other scenarios.

Prior to this PR, the following three commands all do the same thing, namely to initialise Terraform using _only_ those plugins found in `mydir`:
1. `terraform init -plugin-dir=mydir`
2. `terraform init -plugin-dir=mydir -get-plugins=false`
3. `terraform init -plugin-dir=mydir -get-plugins=true`

This is because the value of `-get-plugins` is always overridden to `false` if `-plugin-dir` is set.

This PR introduces the following new behaviour:

`terraform init -plugin-dir=mydir -get-plugins=true` initialises Terraform using those plugins found in `mydir` _and_ plugins found using the usual plugin discovery mechanism (in that order of precedence).

This PR adds a unit test, which fails before this change to how the flags are parsed.

## Assumptions

This only combination of CLI flags this PR changes the meaning of is:

```
terraform init -plugin-dir=mydir -get-plugins=true
```

This PR is not a breaking change, because users are not relying on this command to act, as it does at the moment, as if `-get-plugins` is set to `false`.

## Remarks

I find the behaviour of the `-get-plugins` flag a bit confusing: it has a default value of `true` unless `-plugin-dir` is set, in which case it defaults to `false`.

### CODE REVIEW

**Comment by pselle** [comment]
@mildwonkey Agree that docs update is needed, but I believe this can go in 0.12, as we're talking about an explicit flag setting.

**Comment by jbardin** [comment]
I agree this could be seen as breaking. I've seen many instances of terraform in automation where commands are followed by many or all flags, with combinations that may or may not make sense, but are working nonetheless. The goal of `-plugin-dir` was specifically to disable automatic installation, meaning that it couldn't be overridden, for systems that wanted to ensure specific binaries.

Is it not possible to use the existing mechanism for loading custom provider binaries?  Config-specific plugins were to be loaded from `$PWD/terraform.d/plugins/...` (or `~/.terraform.d/plugins`, but that's of course not convenient for a test harness), and while not specifically documented, we load plugins from `$PWD` itself too.

This is a rather small risk though, so if we have a greater need in testing we can

**Comment by apparentlymart** [comment]
Thinking about the "future plugin installer" angle in the earlier comments (which has, in the meantime, become the _current_ plugin installer in the `master` branch), we have planned a way to explicitly describe all of the locations Terraform should look for providers in [the CLI config](https://www.terraform.io/docs/commands/cli-config.html). This is intended as a generalization of the current mismash of possibilities available on the `terraform init` command line, allowing for some very specific and explicit configurations such as the following one which seems like it would be suitable for the provider testing harness:

```hcl
provider_installation {
  # Get the "dns" provider from a local temporary directory
  filesystem_mirror {
    path = "/tmp/provider-testing12345/plugins"
    include = ["registry.terraform.io/hashicorp/dns"]
  }
  # Get all other providers directly from their canonical sources
  direct {
    exclude = ["registry.terraform.io/hashicorp/dns"]
  }
}
```

We have an environment variable to force looking in a different location for the CLI configuration, so the test harness could potentially generate something like the above and ask Terraform to refer to it, giving more explicit control over the installation behavior.

As things currently stand in `master` this is not implemented yet and we'd been considering it as a stretch goal for the initial 0.13.0 release, because we currently have rules that approximate the old model of automatically looking in some directories unless `-plugin-dir` is set and so the more explicit mechanism could potentially follow in a 0.13.x release.

Does the above seem like it would meet the needs of the test harness, @kmoe? It might require some adjustments to how we've been prioritizing work, but if it seems like this could work I'd rather push ahead with this more explicit model than to introduce further subtlety to our current rather-implicit/confusing set of capabilities that we'd then need to support indefinitely too.

**Comment by pselle** [comment]
Looks like this PR doesn't make sense with the new work coming in 0.13, so closing this PR.

**Pull request closed without merging**
