### PR TITLE
AWS EMR Autotermination and Termination protection

### LINKED ISSUE #10263: Add support for AWS EMR Termination Protection
Please can we have support for the aws command line option --termination-protected supported for EMR clusters.

### Terraform Version
Terraform v0.7.11

### Affected Resource(s)
- aws_emr_cluster

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "aws_emr_cluster" "hbase_ingest" {
  name = "hbase_dev_ingest"
  release_label = "emr-4.8.2"
  master_instance_type = "r3.xlarge"
  core_instance_type = "r3.2xlarge"
  core_instance_count = 3
  termination_protected = true
  service_role = "EMR_DefaultRole"
  applications = ["Sqoop-Sandbox", "Ganglia", "Phoenix", "ZooKeeper-Sandbox", "Hue", "Presto-Sandbox", "HBase", "Tez", "Hadoop", "Hive", "HCatalog", "Spark"]
  log_uri = "s3n://aws-logs-407965986045-ap-southeast-2/elasticmapreduce/"
  tags = {"Environment"="Dev", "Application"="Spark1.6.2"}
  ec2_attributes = {
    "key_name"="linux_key_pair_dev",
    "subnet_id"="subnet-739c4b04",
    "emr_managed_master_security_group"="sg-67eb0603",
    "emr_managed_slave_security_group"="sg-60eb0604",
    "additional_master_security_groups"="sg-816987e5",
    "additional_slave_security_groups"="sg-816987e5",
    "instance_profile"="EMR_EC2_DefaultRole",
    "service_access_security_group"="sg-61eb0605"
  }
  bootstrap_action = {
    name = "NTP Configure for local server"
    path = "s3://wel-science-working-dev/EMR/Bootstrap/NTP/config_ntp.sh"
    args = []
  }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Create an EMR instance with termination protection enabled

### Actual Behavior
Creates a cluster with no termination protection, and rejects any keyword associated with termination_protected

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform show`
Will fail with 
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * aws_emr_cluster.hbase_ingest: : invalid or unknown key: termination_protected

2. 'terraform apply'
Without the termination_protected will create a cluster without any termination protection

### PR DESCRIPTION
**Pull request by xt84**
* Add documentation 
* Autoterminate
* Termination protection

Fixes #10263

### CODE REVIEW

**Comment by stack72** [comment]
Hi @xt84 

Thanks for the work here - just been reviewing it and have noticed that we don't currently account for the new values in the update function. Does this mean they cannot be changed on a cluster?

If this is the case, then they need to be marked as `ForceNew: true` in the schema :)

Thanks

Paul

**Comment by xt84** [comment]
Hi @stack72, sorry for late answer. 
Add "ForceNew: true" for "keep_job_flow_alive_when_no_steps", "termination_protection" can be changed on working cluster

**Comment by stack72** [comment]
got it - i will get this tested today! Thanks for the work here - will get back to you asap

P.

**Comment by stack72** [comment]
ok I just ran the tests and made 1 small update - set ForceNew: true on the termination_protection as well

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSEMRCluster_'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/12/05 13:54:21 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSEMRCluster_ -timeout 120m
=== RUN   TestAccAWSEMRCluster_basic
--- PASS: TestAccAWSEMRCluster_basic (467.50s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	467.521s
```

Thanks for all the work here - this is great!

**Comment by stack72** [comment]
Manually merged in 8586e323dc55b953c48867c71f2ca7869794497a

**Comment by xt84** [comment]
Thanks for merge! And your time!

**Comment by cpower** [comment]
Quick question, why set ForceNew: true on the termination_protection?  In my experience, you can alter this value on a running cluster without needing to recreate the cluster.

"Prevents accidental termination of the cluster: to shut down the cluster, you must turn off termination protection."
https://docs.aws.amazon.com/ElasticMapReduce/latest/ManagementGuide/UsingEMR_TerminationProtection.html

**Comment by stack72** [comment]
Hi @cpower 

This was an oversight - will followup with a PR that takes care of that today

Paul

**Pull request closed without merging**
