### PR TITLE
docs: delete outdated Resource Lifecycle page

### PR DESCRIPTION
**Pull request by kmoe**
This page is outdated, and contains information that is now false. It is superseded by https://github.com/hashicorp/terraform/blob/main/docs/resource-instance-change-lifecycle.md.

### CODE REVIEW

**Review by apparentlymart — APPROVED** [review]
Removing this seems fine to me because it's very stale and factually incorrect in places.

Normally when we delete something that has a successor page we add a redirect for it, but I don't think there's precedent for redirecting to something directly in our repository rather than on the docs site. [It does seem that the website system supports absolute URLs as redirect targets](https://github.com/hashicorp/terraform-website/blob/e920c9f32699aba6912cdaa0556b97d332e95cc5/redirects.next.js#L155-L156) though, so perhaps we should drop one in there just for completeness. (I don't feel super strongly about it, since I can't imagine this was a particularly popular/useful page.)

**Review by apparentlymart — CHANGES_REQUESTED** [review]
Oh, I just noticed that you've updated the old layout file but not the new JSON-based index file, which is why the Vercel build failed.

https://github.com/hashicorp/terraform/blob/main/website/data/internals-nav-data.json

**Comment by kmoe** [comment]
Thanks. Do both need to be updated? Why is the old one still there?

**Review by apparentlymart — APPROVED** [review]
LGTM!

I don't think the `.erb` file is still used and could perhaps be deleted now. I expect it's still there because for a while we were simultaneously publishing with both the old and new stacks, but the old stack is now totally gone so I don't know of anything that should be using the `.erb` files.

**Pull request merged**
