### PR TITLE
aws: Add new region (Mumbai)

### PR DESCRIPTION
**Pull request by radeksimko**
https://aws.amazon.com/about-aws/whats-new/2016/06/announcing-the-aws-asia-pacific-mumbai-region/

New ID verifiable via

```
aws ec2 describe-regions | jq .Regions[].RegionName | sort
```

### CODE REVIEW

**Comment by stack72** [comment]
Nice work! LGTM! Merge when ready

**Comment by stephenchu** [comment]
Mind me asking, why is Terraform keeping a list of hardcoded regions for its purpose?

**Comment by radeksimko** [comment]
> why is Terraform keeping a list of hardcoded regions for its purpose?

I think this is purely for static/offline validation of the aws provider configuration - so that the user gets a human-friendly error for cases like this:

```hcl
provider "aws" {
  region = "not-exists"
}
```

We cannot verify this online, even though it's available from the API, because we'd need to choose a valid region (and hard-coding a single region is not a good idea since that region becomes a single point of failure) + have valid credentials so this is kind of a 🐔  & 🍳  problem when validating `provider` which is responsible for setting up the connection.

Also the way most SDKs work is that they simply take the given region as a string and make a hostname of it, so the error message user would see if Terraform wouldn't perform this offline validation is something like this:

```
Could not connect to the endpoint URL: "https://sts.not-exists.amazonaws.com/"
```

What I think would make sense to do though is to keep such list of valid regions in the SDK and let the SDK perform the validation, but SDK doesn't currently offer such functionality neither a list of regions.

**Comment by boxrick** [comment]
Will this make it into the RC3 at some point shortly?

**Comment by stack72** [comment]
@boxrick not sure what the release plans are - that's a question for @phinze :)

**Comment by boxrick** [comment]
@phinze Will this make it into TF 0.7? Fairly simple change but it is stopping some work and I would appreciate if it could be merged in :)

**Comment by stack72** [comment]
Hi @boxrick 

this has already been merged - so it will definitely be in 0.7

Paul

**Comment by stack72** [comment]
FWIW, it's already part of the RC3

**Comment by radeksimko** [comment]
@stephenchu FYI - I just opened https://github.com/hashicorp/terraform/pull/11358 to add `skip_region_validation`. Feedback welcomed there.

**Pull request merged**
