### PR TITLE
providers/aws: elb subnet change should not force a new resource

### PR DESCRIPTION
**Pull request by pmoust**

### CODE REVIEW

**Comment by mitchellh** [comment]
Can we get an acceptance test written for this?

**Comment by mitchellh** [comment]
It would help us oops-ing it in the future. If you're not comfortable writing it I can do it for you.

**Comment by pmoust** [comment]
@mitchellh sure

**Comment by pmoust** [comment]
@mitchellh please check if 8fe2c0d makes sense

**Comment by spyrospph** [comment]
This is a very imporant fix.

Can we merge this if the acceptance test is ok?

**Comment by pmoust** [comment]
@spyrospph adding it a typo that was missed in tests.

**Comment by mitchellh** [comment]
Test LGTM! Thanks so much @pmoust

**Pull request merged**
