### PR TITLE
Add per user, role and group policy attachment

### PR DESCRIPTION
**Pull request by jeffw-wherethebitsroam**
This provides per user, role and group policy attachments. This is to fix the issue #4165

### CODE REVIEW

**Comment by johnrengelman** [comment]
Awesome. This addresses the concerns that I had with the existing resource and the changes from this: https://github.com/hashicorp/terraform/pull/4016

**Comment by jeffw-wherethebitsroam** [comment]
Thanks John! It certainly solved my issues - we're using the patched version in production now. Reference to the issue you were addressing #2100

**Comment by catsby** [comment]
Hey @jeffw-wherethebitsroam thanks! In order to move this a long we'll need documentation written for these new resources. 

If you look in the `website` folder in the root of the Terraform project, the README will help get you started on running the site locally. From there, it's adding documentation in Markdown format

- https://github.com/hashicorp/terraform/tree/master/website

You should be able to use the other similar IAM resources as a guide/tempalate if you need, and let us know if you have other questions! I'll try and take a dive into the code in the meantime.

**Comment by josephholsten** [comment]
@jeffw-wherethebitsroam think you can throw together some doc for us to review?

**Comment by johnrengelman** [comment]
I rebased this PR, added docs and open a new PR for those changes (https://github.com/hashicorp/terraform/pull/5816)

**Comment by jeffw-wherethebitsroam** [comment]
Thanks John! I haven't had a chance to get back to this. I'll close this PR is favour of yours.

**Pull request closed without merging**
