### PR TITLE
provider/google: Allow attaching/detaching disks from instances

### LINKED ISSUE #6678: 'google_compute_instance' adding 'google_compute_disk' forces new resource
Hey, i've encountered unexpected behaviour while updating a google_compute_instance resource by adding a new disk {}.
### Terraform Version

Terraform v0.6.16
### Affected Resource(s)
- google_compute_instance
- google_compute_disk
### Terraform Configuration Files

Consider starting out with the following configuration:

``` hcl
variable "gce_ssh_user" {}
variable "gce_ssh_pub_key_file" {}
variable "gce_service_account" {}
variable "gce_project_id" {}
variable "gce_image" {}
variable "gce_region" {
  default = "europe-west1"
}

variable "gce_network" {}
variable "gce_subnetwork" {}

provider "google" {
  credentials = "${file(var.gce_service_account)}"
  project     = "${var.gce_project_id}"
  region      = "${var.gce_region}"
}

resource "google_compute_disk" "default" {
  name  = "test-disk"
  type  = "pd-ssd"
  zone = "${var.gce_region}-b"
  size = 10
}

resource "google_compute_instance" "remove-me" {
  name       = "disk-test"
  machine_type         = "n1-standard-1"
  can_ip_forward       = false
  zone = "${var.gce_region}-b"

  disk {
    image = "ubuntu-1604-xenial-v20160429"
  }

  network_interface {
    subnetwork = "${var.gce_subnetwork}"
    access_config {
      // Ephemeral IP
    }
  }

  service_account {
    scopes = ["compute-rw"] 
  }

  metadata {
    sshKeys = "${var.gce_ssh_user}:${file(var.gce_ssh_pub_key_file)}"
  }
}
```

When using the gce interface I would now be able to add the disk 'test-disk' to the instance 'remove-me' without recreating it (or even rebooting). I would expect terraform to behave the same when changing the resource configuration to the following:

``` hcl

variable "gce_ssh_user" {}
variable "gce_ssh_pub_key_file" {}
variable "gce_service_account" {}
variable "gce_project_id" {}
variable "gce_image" {}
variable "gce_region" {
  default = "europe-west1"
}

variable "gce_network" {}
variable "gce_subnetwork" {}

provider "google" {
  credentials = "${file(var.gce_service_account)}"
  project     = "${var.gce_project_id}"
  region      = "${var.gce_region}"
}

resource "google_compute_disk" "default" {
  name  = "test-disk"
  type  = "pd-ssd"
  zone = "${var.gce_region}-b"
  size = 10
}

resource "google_compute_instance" "remove-me" {
  name       = "disk-test"
  machine_type         = "n1-standard-1"
  can_ip_forward       = false
  zone = "${var.gce_region}-b"

  disk {
    image = "ubuntu-1604-xenial-v20160429"
  }

  #DISK ADDED HERE (using .name attribute instead of self_link yields the same result)
  disk {
    disk = "${google_compute_disk.default.self_link}"
  }

  network_interface {
    subnetwork = "${var.gce_subnetwork}"
    access_config {
      // Ephemeral IP
    }
  }

  service_account {
    scopes = ["compute-rw"] //this grands our filesystemd to modify itself
  }

  metadata {
    sshKeys = "${var.gce_ssh_user}:${file(var.gce_ssh_pub_key_file)}"
  }
}
```
### Debug Output

[https://gist.github.com/advanderveer/fc9e8ef73f1f0b0b8578fedf9140307e](https://gist.github.com/advanderveer/fc9e8ef73f1f0b0b8578fedf9140307e)
### Panic Output

No panic is produced
### Expected Behavior

I would expect the the 'google_compute_instance' not to be recreated
### Actual Behavior

It get destroyed, i.e terraform plan shows multiple "forces new resource":

```
-/+ google_compute_instance.remove-me
    can_ip_forward:                                      "false" => "false"
    disk.#:                                              "1" => "2" **(forces new resource)**
    disk.0.auto_delete:                                  "true" => "true"
    disk.0.image:                                        "ubuntu-1604-xenial-v20160429" => "ubuntu-1604-xenial-v20160429"
    disk.1.auto_delete:                                  "" => "true" **(forces new resource)**
    disk.1.disk:                                         "" => "https://www.googleapis.com/compute/v1/projects/microfactory-test/zones/europe-west1-b/disks/test-disk" (forces new resource)
    machine_type:                                        "n1-standard-1" => "n1-standard-1"
    metadata.#:                                          "1" => "1"
    metadata.sshKeys:                                    "<my public ssh key>"
    metadata_fingerprint:                                "Mq9VPCUvh-E=" => "<computed>"
    name:                                                "disk-test" => "disk-test"
    network_interface.#:                                 "1" => "1"
    network_interface.0.access_config.#:                 "1" => "1"
    network_interface.0.access_config.0.assigned_nat_ip: "146.148.15.98" => "<computed>"
    network_interface.0.address:                         "10.0.0.3" => "<computed>"
    network_interface.0.name:                            "nic0" => "<computed>"
    network_interface.0.subnetwork:                      "microfactory-subnetwork" => "microfactory-subnetwork"
    self_link:                                           "https://www.googleapis.com/compute/v1/projects/microfactory-test/zones/europe-west1-b/instances/disk-test" => "<computed>"
    service_account.#:                                   "1" => "1"
    service_account.0.email:                             "1010578936991-compute@developer.gserviceaccount.com" => "<computed>"
    service_account.0.scopes.#:                          "1" => "1"
    service_account.0.scopes.299962681:                  "https://www.googleapis.com/auth/compute" => "https://www.googleapis.com/auth/compute"
    tags_fingerprint:                                    "42WmSpB8rSM=" => "<computed>"
    zone:                                                "europe-west1-b" => "europe-west1-b"
```
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
1. `terraform apply`
### Important Factoids

Not that i'm aware of
### References

I couldn't find any maybe [https://github.com/hashicorp/terraform/pull/5241](https://github.com/hashicorp/terraform/pull/5241) is related

### PR DESCRIPTION
**Pull request by danawillow**
Fixes #6678 (hopefully for real this time!)

This has a similar limitation to the original attempt at this (#12398) that disks can't be deleted and detached at the same time, but I don't think that should block the functionality getting in.

Documentation changes coming later.

### CODE REVIEW

**Comment by danawillow** [comment]
Let me know what you think about adding the `boot` field and whether that needs a migration function (I'm not quite sure what it would look like, if so). Happy to just revert that bit for now too but it was slightly easier to add it (and it was something I wanted to do eventually anyway)

**Comment by paddycarver** [comment]
(Also, `boot` is purely additive, in that it adds a new field, so a state migration shouldn't be necessary.)

**Comment by paddycarver** [comment]
@danawillow shall we close this one out in favour of the approach we chatted about, as well?

**Comment by danawillow** [comment]
Yeah, good call.

**Comment by gdubicki** [comment]
Can you share your new approach idea with the public, @danawillow @paddycarver ?

**Comment by paddycarver** [comment]
#12398 has a good summary. :)

**Comment by danawillow** [comment]
I'm not going to share the full design doc because it's still being worked on (and I don't want to make any promises), but the general idea will be to make two new resources: attached_disk for a single disk, and attached_disks for all attached disks, and then deprecate the current attached_disk property.

**Pull request closed without merging**
