### PR TITLE
website: force JS/CSS mime-types on deploy

### PR DESCRIPTION
**Pull request by phinze**
Should fix occassional issues with application/octet-stream mime type
assets breaking JS/CSS on site.

### CODE REVIEW

**Comment by phinze** [comment]
cc @handlers @sethvargo

**Comment by handlers** [comment]
Seems highly sane to me, but might want :+1: from someone more familiar with `s3cmd`

**Comment by sethvargo** [comment]
:+1: 

This is super annoying too. We need to copy this to all the project sites :frowning:

**Comment by phinze** [comment]
>  We need to copy this to all the project sites 

On it!

**Pull request merged**
