### PR TITLE
Support CloudWatch logging with Kinesis Firehose

### PR DESCRIPTION
**Pull request by bvingerh**
Add support for configuring CloudWatch logging with Kinesis Firehose as per http://docs.aws.amazon.com/firehose/latest/APIReference/API_CreateDeliveryStream.html

### CODE REVIEW

**Comment by bvingerh** [comment]
See also issue https://github.com/hashicorp/terraform/issues/8838

**Comment by cheesefactory** [comment]
Hey @bvingerh, FYI I was also looking into the feature this morning and noticed there is already a PR for this: #8671

**Comment by bvingerh** [comment]
Good to know I'm not the only one in need of the functionality :-)
I don't much care for which pull request gets approved, but I'd like the functionality in an official release sooner rather than later; (and the other guy has even written tests; go for it).

**Comment by stack72** [comment]
Hi @bvingerh 

Thanks for the PR here. If possible, please can you have a look and see if my PR covers your use-case for functionality :) https://github.com/hashicorp/terraform/pull/8671

Paul

**Comment by bvingerh** [comment]
@stack72 your PR seems to cover my use-case, yes.

**Comment by stack72** [comment]
Awesome - closing this in favour of that PR (#8671) so we can get that work taken care of

Paul

**Comment by stack72** [comment]
Thank you so much for all the work put in here!

**Pull request closed without merging**
