### PR TITLE
provider/softlayer: New Resources - DNS Domain/Resource Records, VPX Load Balancer

### PR DESCRIPTION
**Pull request by danielcbright**
### This PR will add 5 new resources to the SoftLayer provider:

**DNS:**
- `softlayer_dns_domain`
- `softlayer_dns_domain_resourcerecord`

**Load Balancing (Citrix VPX):**
- `softlayer_lb_vpx`
- `softlayer_lb_vpx_vip`
- `softlayer_lb_vpx_service`
#### DNS:

```
resource "softlayer_dns_domain" "main" {
    name = "main.example.com"
}

resource "softlayer_dns_domain_record" "www" {
    record_data = "123.123.123.123"
    domain_id = "${softlayer_dns_domain.main.id}"
    host = "www.example.com"
    contact_email = "user@softlayer.com"
    ttl = 900
    record_type = "a"
}
```
##### Load Balancing:

```
resource "softlayer_lb_vpx" "testacc_foobar_vpx" {
    datacenter = "DALLAS06"
    speed = 10
    version = "10.1"
    plan = "Standard"
    ip_count = 2
}

resource "softlayer_lb_vpx_vip" "testacc_vip" {
    name = "test_load_balancer_vip"
    nad_controller_id = "${softlayer_lb_vpx.testacc_foobar_vpx.id}"
    load_balancing_method = "lc"
    source_port = 81
    type = "HTTP"
    virtual_ip_address = "${softlayer_virtual_guest.terraform-acceptance-test-1.ipv4_address}"
}

resource "softlayer_lb_vpx_service" "testacc_service" {
  name = "test_load_balancer_service"
  vip_id = "${softlayer_lb_vpx_vip.testacc_vip.id}"
  destination_ip_address = "${softlayer_virtual_guest.terraform-acceptance-test-2.ipv4_address}"
  destination_port = 89
  weight = 55
  connection_limit = 5000
  health_check = "HTTP"
}
```
- This PR also fixes some type-o's for the `softlayer_ssh_key` and `softlayer_virtual_guest` resources that prevented the examples from working properly and bring some more consistency to the documentation.

### CODE REVIEW

**Comment by danielcbright** [comment]
Hi @jen20, second time around with a PR, hopefully this one will be a lot smoother 😄

**Comment by tmulhern3** [comment]
The names of the VPX Load Balancer resources have been updated as follows: 

`softlayer_network_application_delivery_controller` -> `softlayer_lb_vpx`
`softlayer_loadbalancer_virtual_ip_address` -> `softlayer_lb_vpx_vip`
`softlayer_loadbalancer_service` -> `softlayer_lb_vpx_service`

```
resource "softlayer_lb_vpx" "testacc_foobar_vpx" {
    datacenter = "DALLAS06"
    speed = 10
    version = "10.1"
    plan = "Standard"
    ip_count = 2
}

resource "softlayer_lb_vpx_vip" "testacc_vip" {
    name = "test_load_balancer_vip"
    nad_controller_id = "${softlayer_lb_vpx.testacc_foobar_vpx.id}"
    load_balancing_method = "lc"
    source_port = 81
    type = "HTTP"
    virtual_ip_address = "${softlayer_virtual_guest.terraform-acceptance-test-1.ipv4_address}"
}

resource "softlayer_lb_vpx_service" "testacc_service" {
  name = "test_load_balancer_service"
  vip_id = "${softlayer_lb_vpx_vip.testacc_vip.id}"
  destination_ip_address = "${softlayer_virtual_guest.terraform-acceptance-test-2.ipv4_address}"
  destination_port = 89
  weight = 55
  connection_limit = 5000
  health_check = "HTTP"
}
```

**Comment by danielcbright** [comment]
Hi @stack72, just wanted to check in where we stand on this PR? We have a lot more coming and wanted to see if we could get this pulled in, or if it's ok if we merge the other resources we have in now since this is such a new provider....

**Comment by stack72** [comment]
Hi @danielcbright 

I am trying to work out how we can test this :) I currently have no account for softlayer

P.

**Comment by renier** [comment]
I was contacted by @stack72 that we could get setup to be the reviewers of softlayer pull requests, since we are the creators and have paid softlayer accounts. You can close this PR, while we wait for that to happen.

**Pull request closed without merging**
