### PR TITLE
Fix #34277 by updating AWS SDK to v1.23.0

### LINKED ISSUE #34277: AWS SSO broken in 1.6.4
### Terraform Version

```shell
Terraform v1.6.4
on linux_amd64
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

```AWS_PROFILE=dev aws sts get-caller-identity
{
    "UserId": "AROA54KEOYPRXXXX:YYY@ZZZ.com",
    "Account": "112233",
    "Arn": "arn:aws:sts::112233:assumed-role/AWSReservedSSO_AWSAdministratorAccess_foobar/YYY@ZZZ.com"
}```

Valid SSO session

then 

```
2023-11-20T15:45:32.105-0600 [INFO]  Terraform version: 1.6.4
2023-11-20T15:45:32.106-0600 [DEBUG] using github.com/hashicorp/go-tfe v1.36.0
2023-11-20T15:45:32.106-0600 [DEBUG] using github.com/hashicorp/hcl/v2 v2.19.1
2023-11-20T15:45:32.106-0600 [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.1
2023-11-20T15:45:32.106-0600 [DEBUG] using github.com/zclconf/go-cty v1.14.1
2023-11-20T15:45:32.106-0600 [INFO]  Go runtime version: go1.21.3
2023-11-20T15:45:32.106-0600 [INFO]  CLI args: []string{"terraform", "init"}
... snip ...

Initializing the backend...
2023-11-20T15:45:32.108-0600 [DEBUG] New state was assigned lineage "84f2e7bc-6514-fe37-fa77-131a5fb9b3ea"
2023-11-20T15:45:32.323-0600 [DEBUG] checking for provisioner in "."
2023-11-20T15:45:32.325-0600 [DEBUG] checking for provisioner in "/usr/bin"
2023-11-20T15:45:32.326-0600 [DEBUG] backend-s3.aws-base: Resolving credentials provider: tf_backend.operation=Configure tf_backend.req_id=df83bd5f-ad02-1434-daff-2ff60273c01d tf_backend.s3.bucket=tf-state-dev-us-west-2 tf_backend.s3.path=ZZZ-tf/stack/vpc/terraform.tfstate

...snip...

2023-11-20T15:45:32.326-0600 [DEBUG] backend-s3.aws-base: Retrieving credentials: tf_backend.operation=Configure tf_backend.req_id=df83bd5f-ad02-1434-daff-2ff60273c01d tf_backend.s3.bucket=tf-state-dev-us-west-2 tf_backend.s3.path=ZZZ-tf/stack/vpc/terraform.tfstate
╷
│ Error: No valid credential sources found
│ 
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│ 
│ Error: failed to refresh cached credentials, the SSO session has expired or
│ is invalid: failed to read cached SSO token file, open
│ /home/YYY/.aws/sso/cache/0xdeadbeefhash.json: no
│ such file or directory
│ 
╵

ERRO[0002] terraform invocation failed in /home/YYY/vpc/.terragrunt-cache/5paRZdxXD4QNH-1k6mjhK42O2cI/B3aa0TQF8DQ9QFMKA1HemARc0x0/modules/vpc_v2  prefix=[directory] 
ERRO[0002] 1 error occurred:
	* [/home/YYY/vpc/.terragrunt-cache/5paRZdxXD4QNH-1k6mjhK42O2cI/B3aa0TQF8DQ9QFMKA1HemARc0x0/modules/vpc_v2] exit status 1
```



### Expected Behavior

using terraform 1.6.3

```
2023-11-20T15:49:30.885-0600 [DEBUG] backend-s3.aws-base: HTTP Request Sent: aws.operation=GetRoleCredentials aws.region=us-west-2 aws.sdk=aws-sdk-go-v2 aws.service=SSO tf_backend.operation=Configure tf_backend.req_id=1ddf2c2c-5900-f4f1-5a69-0e8387964599 tf_backend.s3.bucket=tf-state-dev-us-west-2 tf_backend.s3.path=tf/stack/vpc/terraform.tfstate net.peer.name=portal.sso.us-west-2.amazonaws.com http.user_agent="APN/1.0 HashiCorp/1.0 Terraform/1.6.3 (+https://www.terraform.io) aws-sdk-go-v2/1.21.0 os/linux lang/go#1.21.3 md/GOOS#linux md/GOARCH#amd64 api/sso#1.13.6" http.request.header.amz_sdk_request="attempt=1; max=3" http.request.header.x_amz_sso_bearer_token="a_token" http.request.header.amz_sdk_invocation_id=222eb4f9-bfa7-4c96-bb67-4d500425a1d2 http.request.body="" http.method=GET http.url="https://portal.sso.us-west-2.amazonaws.com/federation/credentials?account_id=112233&role_name=AWSAdministratorAccess"
2023-11-20T15:49:32.438-0600 [DEBUG] backend-s3.aws-base: HTTP Response Received: aws.operation=GetRoleCredentials aws.region=us-west-2 aws.sdk=aws-sdk-go-v2 aws.service=SSO tf_backend.operation=Configure tf_backend.req_id=1ddf2c2c-5900-f4f1-5a69-0e8387964599 tf_backend.s3.bucket=tf-state-dev-us-west-2 tf_backend.s3.path=tf/stack/vpc/terraform.tfstate http.response.header.content_type=application/json http.response.header.server="AWS SSO" http.response.header.date="Mon, 20 Nov 2023 21:49:32 GMT"
```
init works as expected using SSO credentials

### Actual Behavior

SSO error message in 1.6.4, init does not complete

### Steps to Reproduce

1. Login with AWS SSO credentials
2. Use terraform 1.6.4 and `init` command

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by rvodden**
Updated AWS SDK (and dependent services) to v1.23.0:

aws-sdk-go-v2 v1.23.0
ec2/imds v1.14.4
s3/manager v1.13.9
dynamodb v1.25.2
s3 v1.42.2
aws-sdk-go-base/v2 v2.0.0-beta.42

This pulls in the fix for an upstream SDK issue documented here:

https://github.com/aws/aws-sdk-go-v2/issues/2370

Fixes #34277 

## Target Release

1.6.5

## Draft CHANGELOG entry

BUG FIXES

 

- `terraform init`: Fixed crash when using AWS SSO with profiles

### CODE REVIEW

**Comment by rvodden** [comment]
I think the tests are failing because the service mocks do not reflect the new API behaviour correctly. I'm digging into this

**Comment by jar-b** [comment]
Hey @rvodden - thanks for opening this! We've got another pending release of `aws-sdk-go-base` which will update a few more dependencies, after which we should be able to move this along. I'll pick this up once that is complete.

**Comment by rvodden** [comment]
Superseded by https://github.com/hashicorp/terraform/pull/34313

**Comment by crw** [comment]
Thanks for your contribution!

**Pull request closed without merging**
