### PR TITLE
Allow import of Route 53 records with underscores in the name

### LINKED ISSUE #12637: aws_route53_record containing underscore cannot be imported
Hi there,

The import command for `aws_route53_record` resources fails if the `name` of the record contains an underscore (as is often the case with DKIM email sender identification records).

### Terraform Version
Terraform v0.8.8

### Affected Resource(s)
- aws_route53_record

### Terraform Configuration Files
```hcl
provider "aws" {}

data "aws_route53_zone" "selected" {
  name = "mydomain.com."
}

resource "aws_route53_record" "domainkey" {
  zone_id = "${data.aws_route53_zone.selected.id}"
  name    = "some._domainkey.mydomain.com."
  type    = "TXT"
  ttl     = "300"
  records = ["somevalue"]
}
```

### Debug Output
https://gist.github.com/nfelger/384e7c4a190cf12ffd8853f124519f51

### Expected Behavior
The resource should be imported successfully.

### Actual Behavior
The import fails as follows:
```
aws_route53_record.domainkey: Importing from ID "Z0000000000000_some._domainkey.mydomain.com_TXT"...
aws_route53_record.domainkey: Import complete!
  Imported aws_route53_record (ID: Z0000000000000_some._domainkey.mydomain.com_TXT)
aws_route53_record.domainkey: Refreshing state... (ID: Z0000000000000_some._domainkey.mydomain.com_TXT)
Error importing: 1 error(s) occurred:

* aws_route53_record.domainkey: InvalidInput: 1 validation error detected: Value 'domainkey.mydomain.com' at 'startRecordType' failed to satisfy constraint: Member must satisfy enum value set: [AAAA, A, NS, SOA, SPF, MX, PTR, CNAME, TXT, SRV, NAPTR]
	status code: 400, request id: fd9bc6e6-07e1-11e7-90e6-b364fcf332cb
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform import aws_route53_record.domainkey Z0000000000000_some._domainkey.mydomain.com_TXT`

I will look into submitting a test case and pull request as well, but I've never opened the terraform source or worked with go, so if anyone could provide a pointer to the files I should be looking at, that'd much appreciated!

### LINKED ISSUE #14465: Import of aws_route53_record with Underscore Fails
### Terraform Version
Terraform v0.9.5

### Affected Resource(s)
aws_route53_record

### Terraform Configuration Files
```hcl
resource "aws_route53_record" "tld_mailgun_key" {
  zone_id = "${aws_route53_zone.tld.id}"
  name    = "krs._domainkey.${var.tld}"
  type    = "TXT"
  ttl     = 300

  records = [
    "\"k=rsa; p=ABCDEFG\"",
  ]
}
```

### Expected Behavior
The Route53 record is imported into Terraform successfully.

### Actual Behavior
This error is printed:
```
aws_route53_record.tld_mailgun_key: Import complete!
  Imported aws_route53_record (ID: SANITIZEDZONEID_krs._domainkey.cntr.io_TXT)
aws_route53_record.tld_mailgun_key: Refreshing state... (ID: SANITIZEDZONEID_krs._domainkey.cntr.io_TXT)
Error importing: 1 error(s) occurred:

* aws_route53_record.tld_mailgun_key (import id: SANITIZEDZONEID_krs._domainkey.cntr.io_TXT): 1 error(s) occurred:

* import aws_route53_record.tld_mailgun_key result: SANITIZEDZONEID_krs._domainkey.cntr.io_TXT: aws_route53_record.tld_mailgun_key: InvalidInput: 1 validation error detected: Value 'domainkey.cntr.io' at 'startRecordType' failed to satisfy constraint: Member must satisfy enum value set: [AAAA, A, NS, SOA, SPF, MX, PTR, CNAME, TXT, SRV, NAPTR]
	status code: 400, request id: SANITIZED
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a Route53 record in AWS with an underscore in the name.
2. Create a Terraform config for that record.
3. Attempt to import the record with `terraform import`.

### Important Factoids
It clearly attempts to split the ID on the underscore in the domain name. I verified this by finding [the specific piece of code responsible for parsing the ID](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_route53_record.go#L461). As I suspected it simply calls `strings.Split(d.Id(), "_")`.

I may cook up a PR if someone doesn't beat me to it.

### PR DESCRIPTION
**Pull request by brycekahle**
Fixes #12637, fixes #14465
Supersedes #14466

### CODE REVIEW

**Comment by akumria** [comment]
Personally I would not have done the extra checking to ensure the R53 supported resource records (as, if it changes, it requires a new terraform build).

But lgtm.

**Comment by brycekahle** [comment]
@akumria That is the only way to know if the last part is a set name, which requires popping off another section to get the record type.

**Comment by stack72** [comment]
Hi @brycekahle / @handlerbot 

I am taking care of this PR right now

Thanks

Paul

**Comment by cazorla19** [comment]
Well, is it closed? Can you provide a link to the issue in [terraform-provider-aws](https://github.com/terraform-providers/terraform-provider-aws)?
I still don't see a PR there although this bugfix is definitely important.

**Pull request closed without merging**
