### PR TITLE
terraform: validate providers' schemas during NewContext

### PR DESCRIPTION
**Pull request by mildwonkey**
Hello! This PR comes with a lead-in question before you look at the code: should we even do this? I think so, but if there's any controversy I can step back and RFC this. [updated with improved error message] ~If agreed, I will have at least one more commit to improve the error message; I didn't want to spend any more time on it before confirming if this is a good idea in the first place.~ 

----

The terraform-plugin-sdk has a lovely series of InternalValidate functions that verify the validity of the providers' schemas during `Configure` (entrypoint [here](https://github.com/hashicorp/terraform-plugin-sdk/blob/dcaac684c7fe179d35d2ff34f9f1de99ea129c6c/helper/schema/provider.go#L109)). Terraform _assumes_ that this is run for every provider. 

This is not a safe assumption, unfortunately: for example a provider not using our sdk might not implement something like `InternalValidate`. Most of the mistakes that the validation would catch will result in errors in terraform (for e.g.: if an attribute is both required and computed, we'll get an invalid result after apply error). There's a _new_ potential issue that will result in a panic: an attribute with both a non-nil `Type` and a `NestedType`. (this is not yet included in `InternalValidate`; the sdk doesn't support the new `NestedType`s yet).

I started down this path because I wanted Terraform to validate the schema too, so we could catch errors at the beginning of a command instead of during plan or apply (apply being the worst case scenario). I tested this change with a config that used all of our top official providers (aws, azure, google, alicloud, oci, k8s), after which I removed one of the original checks that was in `configschema.InternalValidate` (only called by our builtin providers), since that caused an error with the `oci` provider (invalid attribute names - that's a project for another day). 

If you prefer to review this commit-by-commit, this commentary on each might be helpful:

*  c5a903b updates the existing InternalValidate test to verify specific errors instead of the number of errors; the `Attribute.InternalValidate` function in this commit is incomplete (and buggy) so please ignore that.
* 9f669b5 extracts the attribute validation into a function and refactors Block.InternalValidate to use it. One test error message changed. 
* 02c31cd adds the call to InternalValidate into `loadProviderSchemas` (called during `terraform.NewContext`) and fixes a bug with the error message returned by InternalValidate
* 2dc6960 tweaks the error message so it's closer to the sdk's current error (spoiler: it's not as good)

I don't like this error message as much as the one from the provider, but I am not sure how much I can improve it (I'm sure I can get the specific resource name in!), since in this case the error could be one of a series of diagnostics. I shouldn't just throw everything else away in favor of returning exactly/only the same message as the SDK does (I don't think I'm putting this into words very well; hit me up in slack if you want to talk through it). 

Now for the pictures! Here's the current error message from the SDK if a provider has an invalid schema:

Screen Shot 2021-03-16 at 8 30 42 AM

Here's the same error, caught by Terraform during NewContext. UPDATED VERSION ~It's not as nice, and also notice that the failing resource name is missing~:

Screen Shot 2021-03-18 at 9 16 29 AM

### CODE REVIEW

**Comment by mildwonkey** [comment]
👋 Hi enablement! I don't need a code review from y'all (unless you want to!), but wanted you to see my proposal to run a function similar to `InternalValidate` before the SDKs would normally run duing `ConfigureProvider`. (My `InternalValidate` covers less than yours, so yours is still important).

**Review by radeksimko — APPROVED** [review]
This looks like a good idea to me, but the SDK team should definitely have a say on this.

**Review by paddycarver — APPROVED** [review]
I'm a fan of this.

**Comment by radeksimko** [comment]
Maybe one nitpick - is it worth surfacing the provider name too? e.g. change this

```
... Please report this bug:
```
to

```
... Please report this bug to maintainers of hashicorp/random provider:
```

Pulling the bug report URL out of the Registry would be even cooler, but I think this would at least make it more obvious where exactly to report the bug to? That seems especially relevant when the resource name doesn't hold the prefix of the provider name.

**Comment by mildwonkey** [comment]
Oh geez, I hadn't realized the provider name isn't in there anywhere! Thank you! 

Here's the new version. I'll update the top comment, too. I'm not going to include the issues url in this PR since we'd need to do more refactoring than I want to get into right now. We don't have access to the provider installation information at that point, so we wouldn't know if it wasn't a registry provider. It's a great suggestion, though, and we should consider that for future work. 

Screen Shot 2021-03-18 at 9 16 29 AM

**Comment by radeksimko** [comment]
@mildwonkey I think the `ForDisplay` value which omits the hostname for the official registry might suffice in this context, but LGTM either way!

https://github.com/hashicorp/terraform/blob/c6278bbe372781328183d1c8be6a4b100879c8e4/addrs/provider.go#L62-L65

**Comment by mildwonkey** [comment]
We generally use the full source for errors and ForDisplay for informational messages only.

**Comment by mildwonkey** [comment]
Here's the most recent version of this error message. In this example, I ran `terraform plan` without running init (I presume, but do not know, that this is the most likely reason a user would see this error message):


Screen Shot 2021-03-22 at 1 04 59 PM

**Review by pselle — APPROVED** [review]
I really like the new message! I hope it leads to more helpful reporting and helping users figure out where their issues lie sooner

**Pull request merged**
