### PR TITLE
Formalize interpolation language into a real typed interpreted language

### LINKED ISSUE #744: Variable interpolation syntax is confounding in non-trivial cases
Nowhere in a the documentation can I find a formal or comprehensive description of the variable interpolation syntax. There are lots of trivial examples which just expand one variable:

    vpc_id = "${aws_vpc.vpc.id}"

Cool. What if I want to do something nontrivial? How about reading from a file. There's a function for that, and the documentation even gives an example: `${file("path.txt")}`. Neat. But now, I want to include that in my program, where it's already quoted. So, is that:

    user_data = "${file("user_data.txt")}"

or maybe...

    user_data = ${file("user_data.txt")}

or...

    user_data = "${file(\"user_data.txt\")}"

OK whatever, I'll just try them all until I find something that works. But hey, this is a module, and I want that to be relative to the module directory. There's an example:

    script = "${path.module}/script.sh"

Neat...but I also want to use the `file` function. So is that:

    user_data = "${file(${path.module}\"/user_data.txt\")}"

or maybe...

    user_data = "${file(path.module\"/user_data.txt\")}"

Maybe something with that `join` function? No, that only works with the splat syntax.

Oh jeez. I could think of a lot of ways it might be. I'm not sure if it's even possible.

The mental problem I'm having here is that a variable reference is not a string, and a function is not a variable, and `"` isn't a "begin interpretation of half-baked programming language" operator, but the Terraform syntax seems to conflate all of these things. It's very reminiscent of Bash, which has taken me years to understand, and [which people mess up all the time](https://www.google.com/search?q=don%27t%20write%20shell%20scripts). Please don't be like Bash, which has [pages and pages in the manual on expansion](http://www.gnu.org/software/bash/manual/bashref.html#Shell-Expansions) because it's so hard to understand.

### PR DESCRIPTION
**Pull request by mitchellh**
This PR turns the syntax of interpolated configuration values into a real parsed language with real types. Before this, it was just strings all the way down (somehow everything turned into strings). This was really weird because it didn't allow math operations, we actually support some concept of maps in variables, etc. It also led to less than stellar errors.

I'm going to do a bit more work on this PR, but opening it for any feedback and to show to some folks. 

This PR is completely backwards compatible. It also ends up fixing a lot of issues or introducing new functionality:

  * String concatenation just works, so you can do things like `${file("foo_${count.index}.txt")}` now.
  * Escape characters work properly: `${"foo\nbar"}` (newline, example)
  * Numbers are supported: `${function(42)}`, also floating point
  * All function argument counts are semantically verified
  * Types are all verified (although they're still all strings for now since the `terraform` package still gives us all strings. That is the next step to fix after this PR. The language itself is fully typed and type checked).
  * **Super well tested**. The last interpolation regexp stuff was reasonably tested but not as well as it could've been. 

The language itself is a very standard interpreted language with lex -> parse -> semantic check -> execute phases. Lexer goes to a token stream parser goes to an AST tree, semantic check and execution is done using the visitor pattern on the AST tree. 

Fixes #744

### CODE REVIEW

**Comment by mitchellh** [comment]
The tests pass, Travis is just sad for some reason.

**Comment by rubbish** [comment]
:100: Thanks for doing this, it's appreciated!

**Comment by svanharmelen** [comment]
Nice... Really nice... Your clearly back from the holidays :wink:

**Comment by knuckolls** [comment]
:+1: Much needed. Thanks. I happened to find a bug and wrote a fix in the existing code late last week pertaining to doing element(resource.*.parameter, count.index) calls. Going to see if that still remains on this branch and report back.

**Comment by ceh** [comment]
Woah, a treat for the weekend. I will enjoy reading this. Cheers @mitchellh!

**Comment by knuckolls** [comment]
The bug does still exist. I'll get it written up this afternoon.

**Comment by mitchellh** [comment]
@knuckolls I'm guessing its not a parsing bug so much as a logic but in the function at this point. And also probably because we don't have proper types being sent into the configuration yet.

**Comment by knuckolls** [comment]
@mitchellh wrote it up in a new issue #795

**Comment by mitchellh** [comment]
Coming in!

**Pull request merged**
