### PR TITLE
Improve plan output

### PR DESCRIPTION
**Pull request by sylr**
With better padding and colors.

### CODE REVIEW

**Comment by sylr** [comment]
Could someone look at that @apparentlymart @katbyte @tombuildsstuff.

Thanks.

**Comment by apparentlymart** [comment]
Hi @sylr! Thanks for working on this.

We're actually planning to entirely replace the current diff renderer in the near future. You can see a screenshot of our prototype in #15180. We (the Terraform team at HashiCorp) are currently working on the foundational changes that will make that rendering possible -- most notably, changing the internal plan representation so it represents data structures -- and then will change the rendering once that is in place.

So with that said, I'd like to keep the current plan output as-is for the moment while we're working towards this, to avoid making a sequence of changes to the output that may prove disorienting to users and troublesome for those using helpers like [terraform-landscape](https://github.com/coinbase/terraform-landscape) that would probably need to be updated for each change.

Thanks again for working on this, and sorry that the current work in progress wasn't more obvious before you started. :confounded:

**Comment by sylr** [comment]
Hi,

It's been a while now and the plan output still does not seem to have been rewritten. Could we merge this while waiting for the rewrite ?

Regards.

**Comment by apparentlymart** [comment]
Hi @sylr!

The new plan renderer _is_ actually now merged in master, but we didn't yet delete the old (now dead) codepath.

We're still planning some more iteration on it before the final 0.12.0 release, but you can see what's there so far in [the alpha4 builds](https://releases.hashicorp.com/terraform/0.12.0-alpha4/).

**Comment by teamterraform** [comment]
Hi folks! Now that Terraform 0.12 is released, we are undertaking a general GitHub issue/PR cleanup. 

The plan output has changed considerably with terraform 0.12, so we will close this PR. Please do not hesitate to open new PRs or issues. Thanks!

**Pull request closed without merging**
