### PR TITLE
Slight doc correction

### PR DESCRIPTION
**Pull request by robrankin**
Docs referred to availability set name, not NSG name,

### CODE REVIEW

**Comment by stack72** [comment]
Hi @robrankin 

thanks so much for this PR - this points out another small error with copy and paste ;)

When the build goes green, I will merge it

Thanks again

Paul

**Comment by robrankin** [comment]
No problem.

**Comment by robrankin** [comment]
You've labelled it provider/aws, but its AzureRM 😄

**Comment by stack72** [comment]
d'oh! Good spot :)

**Pull request merged**
