### PR TITLE
Search configured project image families

### LINKED ISSUE #9229: google-cloud provider fails to look up family correctly
### Terraform Version

Terraform v0.7.4
### Affected Resource(s)
- google_compute_instance
### Terraform Configuration Files

``` hcl
provider "google" {
  region = "europe-west1"
}

resource "google_compute_instance" "test_vm" {
  name         = "test-vm"
  machine_type = "n1-standard-4"
  zone         = "europe-west1-b"

  disk = {
    image = "ebi-centos-7"
    type  = "pd-ssd"
  }

  # Network interface
  network_interface {
    subnetwork = "default"
  }
}
```
### Debug Output

https://gist.github.com/dvianello/c9fa1f00ec1c342a9197d5eccd9dc49a
### Expected Behavior

Terraform find the latest version of the private image belonging to the (private) ebi-centos-7 family and uses that to launch the VM.
### Actual Behavior

Terraform fails claiming that there's no such family. However, as visible by the logs, it's actually trying to look up for that image name in the centos-cloud project, not the local project. The error goes away pre-pending the project name to the image name like 'image = "project-name/ebi-centos-7'. Images contained in the ebi-centos-7 family are baked starting from the centos-cloud/centos-7 family, of course.
### Steps to Reproduce
1. `terraform apply`
### Important Factoids

Not really.

### PR DESCRIPTION
**Pull request by cblecker**
Fixes #9229.

This adds a check to search image families in the configured project prior to trying to search for an alternative project.

### CODE REVIEW

**Comment by cblecker** [comment]
Hi @stack72 --
I created an acceptance test, but it currently fails. Once I started tugging at the thread of how to write a test to create a private image family, then provision an instance off of it, I ran into an issue where the google_compute_image resource can't be provisioned based off a google_compute_disk resource (#9262). I opened up an issue to track it.

Without that part being fixed, I'm not sure how else to write an acceptance test for this particular case. Feedback is welcome and appreciated!

Christoph

**Comment by cblecker** [comment]
As #9262 was resolved by #9614, this became unblocked.

I rebased this on top of those fixes, and ran the acceptance tests. They now pass.

```
$ make testacc TEST=./builtin/providers/google TESTARGS='-run=TestAccComputeInstance_private_image_family'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/11/01 17:19:24 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/google -v -run=TestAccComputeInstance_private_image_family -timeout 120m
=== RUN   TestAccComputeInstance_private_image_family
--- PASS: TestAccComputeInstance_private_image_family (206.41s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/google	206.413s
```

@stack72 -- I think this is now ready for review and possibly merge 😄

**Comment by stack72** [comment]
Nps - it won't make 0.7.8 as we are in a release prep right now - but i will merge it for the next version if that's ok?

**Comment by cblecker** [comment]
Yeah, that's fine with me. Thanks!

**Comment by stack72** [comment]
LGTM now @cblecker. Ran All Compute Tests just to make sure :)

```
% make testacc TEST=./builtin/providers/google TESTARGS='-run=TestAccComputeInstance'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/11/01 20:16:20 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/google -v -run=TestAccComputeInstance -timeout 120m
=== RUN   TestAccComputeInstanceTemplate_importBasic
--- PASS: TestAccComputeInstanceTemplate_importBasic (26.00s)
=== RUN   TestAccComputeInstanceTemplate_importIp
--- PASS: TestAccComputeInstanceTemplate_importIp (47.41s)
=== RUN   TestAccComputeInstanceTemplate_importDisks
--- PASS: TestAccComputeInstanceTemplate_importDisks (25.54s)
=== RUN   TestAccComputeInstanceTemplate_importSubnetAuto
--- PASS: TestAccComputeInstanceTemplate_importSubnetAuto (89.86s)
=== RUN   TestAccComputeInstanceTemplate_importSubnetCustom
--- PASS: TestAccComputeInstanceTemplate_importSubnetCustom (77.00s)
=== RUN   TestAccComputeInstanceGroup_basic
--- PASS: TestAccComputeInstanceGroup_basic (99.35s)
=== RUN   TestAccComputeInstanceGroup_update
--- PASS: TestAccComputeInstanceGroup_update (162.43s)
=== RUN   TestAccComputeInstanceTemplate_basic
--- PASS: TestAccComputeInstanceTemplate_basic (25.06s)
=== RUN   TestAccComputeInstanceTemplate_IP
--- PASS: TestAccComputeInstanceTemplate_IP (47.14s)
=== RUN   TestAccComputeInstanceTemplate_disks
--- PASS: TestAccComputeInstanceTemplate_disks (25.28s)
=== RUN   TestAccComputeInstanceTemplate_subnet_auto
--- PASS: TestAccComputeInstanceTemplate_subnet_auto (86.92s)
=== RUN   TestAccComputeInstanceTemplate_subnet_custom
--- PASS: TestAccComputeInstanceTemplate_subnet_custom (74.11s)
=== RUN   TestAccComputeInstance_basic_deprecated_network
--- PASS: TestAccComputeInstance_basic_deprecated_network (57.63s)
=== RUN   TestAccComputeInstance_basic1
--- PASS: TestAccComputeInstance_basic1 (57.04s)
=== RUN   TestAccComputeInstance_basic2
--- PASS: TestAccComputeInstance_basic2 (55.43s)
=== RUN   TestAccComputeInstance_basic3
--- PASS: TestAccComputeInstance_basic3 (46.87s)
=== RUN   TestAccComputeInstance_basic4
--- PASS: TestAccComputeInstance_basic4 (75.94s)
=== RUN   TestAccComputeInstance_basic5
--- PASS: TestAccComputeInstance_basic5 (65.17s)
=== RUN   TestAccComputeInstance_IP
--- PASS: TestAccComputeInstance_IP (88.23s)
=== RUN   TestAccComputeInstance_disksWithoutAutodelete
--- PASS: TestAccComputeInstance_disksWithoutAutodelete (88.93s)
=== RUN   TestAccComputeInstance_disksWithAutodelete
--- PASS: TestAccComputeInstance_disksWithAutodelete (78.29s)
=== RUN   TestAccComputeInstance_local_ssd
--- PASS: TestAccComputeInstance_local_ssd (55.76s)
=== RUN   TestAccComputeInstance_update_deprecated_network
--- PASS: TestAccComputeInstance_update_deprecated_network (71.77s)
=== RUN   TestAccComputeInstance_forceNewAndChangeMetadata
--- PASS: TestAccComputeInstance_forceNewAndChangeMetadata (140.11s)
=== RUN   TestAccComputeInstance_update
--- PASS: TestAccComputeInstance_update (114.05s)
=== RUN   TestAccComputeInstance_service_account
--- PASS: TestAccComputeInstance_service_account (55.07s)
=== RUN   TestAccComputeInstance_scheduling
--- PASS: TestAccComputeInstance_scheduling (57.15s)
=== RUN   TestAccComputeInstance_subnet_auto
--- PASS: TestAccComputeInstance_subnet_auto (119.20s)
=== RUN   TestAccComputeInstance_subnet_custom
--- PASS: TestAccComputeInstance_subnet_custom (108.64s)
=== RUN   TestAccComputeInstance_address_auto
--- PASS: TestAccComputeInstance_address_auto (123.41s)
=== RUN   TestAccComputeInstance_address_custom
--- PASS: TestAccComputeInstance_address_custom (104.17s)
=== RUN   TestAccComputeInstance_private_image_family
--- PASS: TestAccComputeInstance_private_image_family (217.44s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/google	2566.435s
```

**Comment by dvianello** [comment]
Thank you guys!

**Pull request merged**
