### PR TITLE
provider/azurerm: Add support for setting the primary network interface

### PR DESCRIPTION
**Pull request by kvisscher**
I'm trying to add support for setting the primary network interface for an Azure VM. This works (we deployed something with this change :-)), but I'm not sure how to write a test to proof it to you guys.

Can you guys point me in the right direction?

### CODE REVIEW

**Comment by pearcec** [comment]
I just validated this patch works. Much better approach then anything I had planned on #6514 .  Keeps the code from breaking and easy fix.  Suggest we need documentation added as well.  I am going to fork off your repo and work of your branch.  I will try to add some tests and documentation and give you a PR.

**Comment by pearcec** [comment]
I just pushed and submitted a PR for this PR https://github.com/kvisscher/terraform/pull/1 Hopefully @kvisscher is still active on this thread.  If not we can just reroll on the latest branch and submit a new PR.

**Comment by skinny** [comment]
I'll poke @kvisscher  when he's back from his holiday next week! Thanks for the work!

**Comment by kvisscher** [comment]
@pearcec I've updated my PR with your changes. Can you verify that this is OK 👍 ?

**Comment by pearcec** [comment]
Looks good.  Did you pull of the latest master?  Initially I tried to merge what you had off master and the PR was a bit stale.

**Comment by kvisscher** [comment]
@pearcec I pulled from master 8 days ago :-). Want me to rebase again?

**Comment by pearcec** [comment]
You are probably good then.  Send out the PR and see what happens.

**Comment by kvisscher** [comment]
@pearcec I made be mistaken, but this PR is already pending against the hashicorp/terrform master.

**Comment by pearcec** [comment]
Right I think you are good.  Hopefully it gets picked up soon.

**Comment by kvisscher** [comment]
@radeksimko Don't want to bother you, but is there any chance you know someone in the community who has the super powers to merge this in?

**Comment by pmcatominey** [comment]
Tests pass!

```
TF_ACC=1 go test ./builtin/providers/azurerm -v -run TestAccAzureRMVirtualMachine_primary -timeout 120m
=== RUN   TestAccAzureRMVirtualMachine_primaryNetworkInterfaceId
--- PASS: TestAccAzureRMVirtualMachine_primaryNetworkInterfaceId (420.95s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/azurerm	420.962s
```

@kvisscher if you're happy with the PR could you remove the WIP tag from the title?

**Comment by kvisscher** [comment]
@pmcatominey Done 😄

**Comment by kblackstone** [comment]
what is the syntax to set an interface as primary?

**Comment by StephenWeatherford** [comment]
@kblackstone https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html#primary_network_interface_id

**Comment by kblackstone** [comment]
thank you!

**Pull request merged**
