### PR TITLE
drop empty line on version check

### PR DESCRIPTION
**Pull request by ajacoutot**
We always add an empty line when asking/checking the version. We should only do
that if there is a new version available. While this is purely cosmetic, it
reads better and is consistent with packer.

### CODE REVIEW

**Comment by wyardley** [comment]
+1 on this for me, I was going to submit a PR, but noticed this one existed.

**Comment by wyardley** [comment]
Now that this has been approved, is there a process to request that it get merged?

```
greta~% tf version
Terraform v0.9.11

greta~% tf --version
Terraform v0.9.11

```

**Comment by apparentlymart** [comment]
Hi @ajacoutot! Thanks for working on this.

We're currently in the feature-freeze period for the 0.10 release, but this looks good and should be easy to merge once we complete the 0.10 release cycle. Sorry for the delay in responding here.

**Comment by ajacoutot** [comment]
Hi @apparentlymart . No worries, it's not what I'd call an urgent fix :-)
Thanks for the heads up.

**Comment by wyardley** [comment]
@apparentlymart: It's now like a year later, and 0.11 is out... could this be (looks like there's a conflict, but that should be pretty easy to deal with, or this could be replaced with a new PR, given how simple the change is).
```
lana~% terraform --version
Terraform v0.11.7

lana~% 
```

**Comment by apparentlymart** [comment]
Hi all,

Sorry this fell off my radar. :confounded:

**Comment by wyardley** [comment]
@apparentlymart Any news?

**Comment by wyardley** [comment]
```
% ./terraform --version
Terraform v0.12.0-alpha1

%
```

**Comment by wyardley** [comment]
Can this get included / re-reviewed, especially now that there's some other recent changes related to this (e.g., #21334)

**Comment by mildwonkey** [comment]
Hi all! 

@ajacoutot , thank you for submitting this request and I'm sorry for the long, long, loooong wait! Cheers 🎉

**Comment by ajacoutot** [comment]
@mildwonkey  ahah no worries, better late than never ;-)
It was trivial anyway. Thank you.

**Comment by wyardley** [comment]
Love this, thanks!

**Pull request merged**
