### PR TITLE
provider/triton: Move to joyent/triton-go

### PR DESCRIPTION
**Pull request by jen20**
This commit moves the Triton provider to the new joyent/triton-go library from gosdc. This has a number of advantages - not least that requests can
be signed using an SSH agent without having to keep unencrypted key material in memory.

Schema has been maintained for all resources, and several tests have been added and acceptance tests repaired - in some cases by fixing bugs in the
underlying resources.

After applying this patch, all acceptance tests pass:

``` go generate $(go list ./... | grep -v /terraform/vendor/) 2017/03/30
13:48:33 Generated command/internal_plugin_list.go TF_ACC=1 go test
./builtin/providers/triton -v  -timeout 120m
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccTritonFabric_basic
--- PASS: TestAccTritonFabric_basic (15.11s)
=== RUN   TestAccTritonFirewallRule_basic
--- PASS: TestAccTritonFirewallRule_basic (1.48s)
=== RUN   TestAccTritonFirewallRule_update
--- PASS: TestAccTritonFirewallRule_update (1.55s)
=== RUN   TestAccTritonFirewallRule_enable
--- PASS: TestAccTritonFirewallRule_enable (1.52s)
=== RUN   TestAccTritonKey_basic
--- PASS: TestAccTritonKey_basic (11.76s)
=== RUN   TestAccTritonKey_noKeyName
--- PASS: TestAccTritonKey_noKeyName (11.20s)
=== RUN   TestAccTritonMachine_basic
--- PASS: TestAccTritonMachine_basic (82.19s)
=== RUN   TestAccTritonMachine_dns
--- PASS: TestAccTritonMachine_dns (173.36s)
=== RUN   TestAccTritonMachine_nic
--- PASS: TestAccTritonMachine_nic (167.82s)
=== RUN   TestAccTritonMachine_addNIC
--- PASS: TestAccTritonMachine_addNIC (192.11s)
=== RUN   TestAccTritonMachine_firewall
--- PASS: TestAccTritonMachine_firewall (188.53s)
=== RUN   TestAccTritonMachine_metadata
--- PASS: TestAccTritonMachine_metadata (614.57s)
=== RUN   TestAccTritonVLAN_basic
--- PASS: TestAccTritonVLAN_basic (0.93s)
=== RUN   TestAccTritonVLAN_update
--- PASS: TestAccTritonVLAN_update (1.50s) PASS ok
github.com/hashicorp/terraform/builtin/providers/triton	1463.621s
```

### CODE REVIEW

**Comment by stack72** [comment]
This is amazing! Thanks so much for all the work here - :1st_place_medal:

**Comment by grubernaut** [comment]
Code-wise looks good to me, only nit is if we can document the switch from `key_material` from a required parameter to optional?

**Comment by jen20** [comment]
@grubernaut This is documented here: https://github.com/hashicorp/terraform/pull/13225/files#diff-fb07e4be32a90ef4af347f843a0f5d2cR33 - do you mean something additional (e.g. changelog)?

**Comment by grubernaut** [comment]
@jen20 ya saw that, mostly meant in the changelog for any current users of the provider on the new behavior.

**Pull request merged**
