### PR TITLE
provider/aws: Add JSON validation to the aws_s3_bucket resource.

### PR DESCRIPTION
**Pull request by kwilczynski**
This commit adds support for new helper function which is used to
normalise and validate JSON string.

Signed-off-by: Krzysztof Wilczynski <krzysztof.wilczynski@linux.com>

### CODE REVIEW

**Comment by kwilczynski** [comment]
Part of work which began in #8028.

**Comment by kwilczynski** [comment]
I have a problem with the acceptance test:

```
--- FAIL: TestAccAWSS3Bucket_Policy (53.54s)
       	testing.go:265: Step 1 error: Check failed: Check 2/2 error: unexpected end of JSON input
```

It does not seem to be related to what I've done, but somehow to: 93f31fce17f15e518da2ffb1093680fd9b3e379d, where `Computed: true` was added to the policy, and it seem to be what is causing this problem. I need to look into this before this commit can be merged, since it fails on master too.

**Comment by kwilczynski** [comment]
Need to wait for https://github.com/hashicorp/terraform/pull/8915 first.

**Comment by kwilczynski** [comment]
I have re-bases against `master` so that the commit includes changes done in #8915.

**Comment by kwilczynski** [comment]
The acceptance test is passing:

```
$ make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSS3Bucket_'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/09/21 11:07:19 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSS3Bucket_ -timeout 120m
=== RUN   TestAccAWSS3Bucket_importBasic
--- PASS: TestAccAWSS3Bucket_importBasic (46.08s)
=== RUN   TestAccAWSS3Bucket_importWithPolicy
--- PASS: TestAccAWSS3Bucket_importWithPolicy (50.07s)
=== RUN   TestAccAWSS3Bucket_Notification
--- PASS: TestAccAWSS3Bucket_Notification (123.61s)
=== RUN   TestAccAWSS3Bucket_NotificationWithoutFilter
--- PASS: TestAccAWSS3Bucket_NotificationWithoutFilter (49.97s)
=== RUN   TestAccAWSS3Bucket_basic
--- PASS: TestAccAWSS3Bucket_basic (36.67s)
=== RUN   TestAccAWSS3Bucket_acceleration
--- PASS: TestAccAWSS3Bucket_acceleration (74.78s)
=== RUN   TestAccAWSS3Bucket_RequestPayer
--- PASS: TestAccAWSS3Bucket_RequestPayer (72.29s)
=== RUN   TestAccAWSS3Bucket_Policy
--- PASS: TestAccAWSS3Bucket_Policy (95.64s)
=== RUN   TestAccAWSS3Bucket_UpdateAcl
--- PASS: TestAccAWSS3Bucket_UpdateAcl (68.06s)
=== RUN   TestAccAWSS3Bucket_Website_Simple
--- PASS: TestAccAWSS3Bucket_Website_Simple (108.99s)
=== RUN   TestAccAWSS3Bucket_WebsiteRedirect
--- PASS: TestAccAWSS3Bucket_WebsiteRedirect (109.45s)
=== RUN   TestAccAWSS3Bucket_WebsiteRoutingRules
--- PASS: TestAccAWSS3Bucket_WebsiteRoutingRules (74.20s)
=== RUN   TestAccAWSS3Bucket_shouldFailNotFound
--- PASS: TestAccAWSS3Bucket_shouldFailNotFound (21.56s)
=== RUN   TestAccAWSS3Bucket_Versioning
--- PASS: TestAccAWSS3Bucket_Versioning (100.26s)
=== RUN   TestAccAWSS3Bucket_Cors
--- PASS: TestAccAWSS3Bucket_Cors (71.29s)
=== RUN   TestAccAWSS3Bucket_Logging
--- PASS: TestAccAWSS3Bucket_Logging (66.31s)
=== RUN   TestAccAWSS3Bucket_Lifecycle
--- PASS: TestAccAWSS3Bucket_Lifecycle (72.91s)
PASS
ok     	github.com/hashicorp/terraform/builtin/providers/aws   	1242.176s
```

**Comment by stack72** [comment]
LGTM! Thanks for the work here :)

**Pull request merged**
