### PR TITLE
Added support for EMR AutoScalingRole

### PR DESCRIPTION
**Pull request by jessecollier**
credit to @tolis-sisiaridis for changes

Addresses https://github.com/hashicorp/terraform/issues/11126

Original PR https://github.com/hashicorp/terraform/pull/11033

### CODE REVIEW

**Comment by stack72** [comment]
LGTM! I will make the documentation change that shows we now accept it

Thanks for the work here

test results incoming - they take about 40 minutes to run

**Comment by stack72** [comment]
```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSEMRCluster_'                                                           ✭
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/03/18 13:17:01 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSEMRCluster_ -timeout 120m
=== RUN   TestAccAWSEMRCluster_basic
--- PASS: TestAccAWSEMRCluster_basic (564.41s)
=== RUN   TestAccAWSEMRCluster_terminationProtected
--- PASS: TestAccAWSEMRCluster_terminationProtected (841.33s)
=== RUN   TestAccAWSEMRCluster_visibleToAllUsers
--- PASS: TestAccAWSEMRCluster_visibleToAllUsers (705.93s)
=== RUN   TestAccAWSEMRCluster_tags
--- PASS: TestAccAWSEMRCluster_tags (799.24s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	2910.943s
```

**Comment by darrenhaken** [comment]
@stack72 is this actually still open?

**Comment by stack72** [comment]
@darrenhaken no idea I am afraid - I am no longer part of this project

**Comment by darrenhaken** [comment]
@stack72 yeah I knew you'd left via Twitter 👍 

Looks like I'm going to have to go deep on Terraform codebase then!

**Comment by darrenhaken** [comment]
There's now a pull request on the AWS provider for this.

**Pull request merged**
