### PR TITLE
rancher: parse Rancher client cli.json config file

### PR DESCRIPTION
**Pull request by raphink**
This doesn't really work yet, because the URL is required in the provider parameters. I see several options, not sure which one is the best:

* make the URL optional, fail in providerConfigure if it's not set
* use our own method instead of `schema.EnvDefaultFunc` to return default values, but then that means we can't provide `config` as a parameter as it needs to be known beforehand.

@stack72 @johnrengelman any idea?

### CODE REVIEW

**Comment by mcanevet** [comment]
I think making the URL optional is a good idea

**Comment by mcanevet** [comment]
The idea is to pass a configuration file created by "rancher config" that we could pass at the instanciation of the provider like that:

```hcl
provider "rancher" {
  config = "${pathexpand(~/.rancher/config.json)}"
}
```

**Comment by raphink** [comment]
@stack72 @mcanevet fixed my code, so it works now, using option 1

**Comment by mcanevet** [comment]
@stack72 could you please review this?

**Comment by stack72** [comment]
LGTM! Thanks for this @raphink :)

**Pull request merged**
