### PR TITLE
helper/schema: Make nested Set(s) in List(s) work (2)

### PR DESCRIPTION
**Pull request by radeksimko**
This is a second (patched) version of #7393 which had to be [reverted](https://github.com/hashicorp/terraform/pull/7436) because some acceptance tests were failing as part of the nightly run.

Related to #7253 & #7254
Supersedes/fixes #7268
Blocking #7395

---

The only difference from the original PR is the last commit (`50fbe79`).

---

I managed to reproduce schema diff edge cases from the failing tests in `aws` provider and fix those. I added 3 new unit tests to cover this new functionality.

I ran the [16 (previously failing)](https://gist.github.com/radeksimko/331ed5a2cb2ce7e84d13a3dcc9fd5331) aws acceptance tests, all are now passing. I also ran first `aws` **141** of total 464 acceptance tests which all (eventually) passed.

I don't have a Fastly account so I would appreciate if someone could double check all acceptance tests are passing there too and generally run the whole shebang once again with this patch (possibly before merging).

### CODE REVIEW

**Comment by apeeters** [comment]
Some tests still seem to be failing, was this expected?

**Comment by radeksimko** [comment]
> Some tests still seem to be failing, was this expected?

Those are unrelated acceptance test failures.

**Comment by apeeters** [comment]
Then what is holding this PR back? I would love #7395 to be implemented soon :)

**Comment by radeksimko** [comment]
I have just rebased this which also restarted tests and should remove the relationship with failing Travis build w/ acceptance tests.

It is possible that we may delay merging this PR (i.e. #7395 too) until 0.7 is out - which should be very soon. 😉

**Comment by apeeters** [comment]
Any updates on this now 0.7 is out? :)

**Comment by mitchellh** [comment]
Hey @radeksimko, I'm interested in getting this into master but it appears to panic on tests when rebased now. Can you rebase this and take a look?

**Comment by catsby** [comment]
Hey @radeksimko is this a thing you plan to complete sometime, or can it be closed? 😄

**Comment by radeksimko** [comment]
Let's close this for now.

**Pull request closed without merging**
