### PR TITLE
[WIP] Add CloudInit Provider

### PR DESCRIPTION
**Pull request by jen20**
This adds an initial version of a cloudinit provider which can be used to construct multipart, gzipped, base64 encoded configurations for use as userdata for various different clouds. It is currently presented as a work-in-progress in order to solicit feedback, but needs improved testing prior to merging.

## Example

```tf
provider "cloudinit" {}

resource "cloudinit_config" "myconfig" {
  gzip = false
  base64_encode = true

  part {
    # Note this is needed since the set does not maintain ordering and the config scripts are not commutative
    order = 2
    content_type = "text/x-shellscript"
    content = "${file("shellscript1.sh")}"
  }

  part {
    order = 1
    content_type = "text/x-shellscript"
    content = "${file("shellscript2.sh")}"
  }

  part {
    order = 3
    content_type = "text/cloud-config"
    merge_type = "list(append)+dict(recurse_array)+str()"
    content = "${file("cloudconfig.yaml")}"
  }
}

output "content" {
  value = "${cloudinit_config.myconfig.rendered}"
}
```

Output:

```
--7e8c268155c51af5992d6f61fa35cc04afb47a4fb3ad3676d0339613fab8
Content-Type: text/x-shellscript

#!/usr/bin/env bash

touch /.testscript2

--7e8c268155c51af5992d6f61fa35cc04afb47a4fb3ad3676d0339613fab8
Content-Type: text/x-shellscript

#!/usr/bin/env bash

touch /.testscript1

--7e8c268155c51af5992d6f61fa35cc04afb47a4fb3ad3676d0339613fab8
Content-Type: text/cloud-config
X-Merge-Type: list(append)+dict(recurse_array)+str()

#cloud-config

runcmd:
 - touch /testfile

--7e8c268155c51af5992d6f61fa35cc04afb47a4fb3ad3676d0339613fab8
Content-Type: text/cloud-config

#cloud-config

runcmd:
 - touch /testfile2

--7e8c268155c51af5992d6f61fa35cc04afb47a4fb3ad3676d0339613fab8--
```

## TODO

- [x] Deal correctly with multi-part content header (not currently implemented)
- [ ] Add resource tests for the config format
- [ ] Fix up error messages to be reasonable and informative
- [ ] Update documentation with resource
- [ ] Document with GoDoc
- [ ] Update ChangeLog

### CODE REVIEW

**Comment by sthulb** [comment]
@radeksimko Is this something you're still working on?

**Comment by radeksimko** [comment]
@sthulb I am not, I was just tagging it properly.
@jen20 Opened the PR, so he's probably better person to answer.

**Comment by sthulb** [comment]
I misread, sorry @radeksimko

**Comment by chrusty** [comment]
I just tried this out myself, and it definitely generates a multi-part userdata. I've not tried it in a launch-config yet, but it seems to be a well-implemented solution to me. Thanks!

**Comment by jen20** [comment]
Closed in favour of the continuing work on #4061.

**Pull request closed without merging**
