### PR TITLE
provider/aws: CloudFormation YAML template support

### PR DESCRIPTION
**Pull request by dylanvaughn**
Hello!

This PR adds support for YAML to the AWS CloudFormation resource and data source.  Fixes:

https://github.com/hashicorp/terraform/issues/9779

Note I don't normalize the YAML templates (as is done for JSON) as that caused the YAML tags which AWS uses (i.e. ```!Ref MyResource```) to be stripped out.

Thanks, Dylan

### CODE REVIEW

**Comment by MarkFischer** [comment]
I'd love to start using this, and would be happy to test out some more complex YAML templates if you need additional testing.

**Comment by MarkFischer** [comment]
I compiled terraform off of the ordinaryexperts:feature/aws-cloudformation-yaml-support branch and was able to successfully deploy the following YAML template with that version:

https://s3-us-west-2.amazonaws.com/ua-uits-ecs-public/service-catalog/admin-deployer.yaml

Will try some more templates with this binary tomorrow.

**Comment by dylanvaughn** [comment]
Thanks @MarkFischer!  I have also been using a binary from this branch with a variety of YAML templates without issues.

**Comment by stack72** [comment]
Hi @dylanvaughn 

Please can you rebase this and we will give it a review?

Thanks

Paul

**Comment by stack72** [comment]
ping @dylanvaughn :)

**Comment by dylanvaughn** [comment]
Hi @stack72 I rebased and squashed - thanks!

**Comment by stack72** [comment]
Hi @dylanvaughn 

I left 1 small comment inline - it was just a musing though rather than something we need to change right now - this LGTM! Thanks for all of the great work here :)

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSCloudFormation'                                                      ✭
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/01/20 13:40:55 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSCloudFormation -timeout 120m
=== RUN   TestAccAWSCloudFormationStack_dataSource_basic
--- PASS: TestAccAWSCloudFormationStack_dataSource_basic (88.07s)
=== RUN   TestAccAWSCloudFormationStack_dataSource_yaml
--- PASS: TestAccAWSCloudFormationStack_dataSource_yaml (90.39s)
=== RUN   TestAccAWSCloudFormation_basic
--- PASS: TestAccAWSCloudFormation_basic (82.65s)
=== RUN   TestAccAWSCloudFormation_yaml
--- PASS: TestAccAWSCloudFormation_yaml (84.22s)
=== RUN   TestAccAWSCloudFormation_defaultParams
--- PASS: TestAccAWSCloudFormation_defaultParams (85.75s)
=== RUN   TestAccAWSCloudFormation_allAttributes
--- PASS: TestAccAWSCloudFormation_allAttributes (126.44s)
=== RUN   TestAccAWSCloudFormation_withParams
--- PASS: TestAccAWSCloudFormation_withParams (155.55s)
=== RUN   TestAccAWSCloudFormation_withUrl_withParams
--- PASS: TestAccAWSCloudFormation_withUrl_withParams (232.03s)
=== RUN   TestAccAWSCloudFormation_withUrl_withParams_withYaml
--- PASS: TestAccAWSCloudFormation_withUrl_withParams_withYaml (135.41s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	1080.524s
```

**Comment by dylanvaughn** [comment]
@stack72 thanks!

**Comment by mrrobby** [comment]
Thanks for this addition all!  Question, seems good for here, would there be much change to support AWS SAM along this same addition?  SAM is a specification for lambdas using CloudFormation templates.  The new SAM Local environment has been working great for us to develop and test lambdas locally (even for simulating events), but we'd like to integrate the deployment/configuration of them with our terraform setup.  Is this possible?  Or if not yet, would anyone be interested in this too?

**Comment by tagirb** [comment]
Thanks for this feature! However, I can't find any references to it in the documentation, e.g. here:
https://www.terraform.io/docs/providers/aws/r/cloudformation_stack.html

Could you please put a few words in there regarding CloudFormation YAML support and maybe an example.

**Pull request merged**
