### PR TITLE
Fix bugs in Librato provider

### PR DESCRIPTION
**Pull request by elblivion**
Adds test cases and fixes for:

* https://github.com/hashicorp/terraform/issues/8966
  * Mandatory `name` and `conditions` attributes weren't being sent on Update unless changed
* https://github.com/hashicorp/terraform/issues/8968
  * Bugs relating to int/uint conversions

### CODE REVIEW

**Comment by stack72** [comment]
Hi @elblivion 

Thanks for the work here :) Will start testing this now

Paul

**Comment by stack72** [comment]
Hi @elblivion 

These changes LGTM! I also used this as a chance to randomize the acceptance test names:

```
% make testacc TEST=./builtin/providers/librato TESTARGS='-run='                                                                                           
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/09/22 12:40:37 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/librato -v -run= -timeout 120m
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccLibratoAlert_Basic
--- PASS: TestAccLibratoAlert_Basic (1.53s)
=== RUN   TestAccLibratoAlert_Full
--- PASS: TestAccLibratoAlert_Full (2.93s)
=== RUN   TestAccLibratoAlert_Updated
--- PASS: TestAccLibratoAlert_Updated (1.85s)
=== RUN   TestAccLibratoAlert_FullUpdate
--- PASS: TestAccLibratoAlert_FullUpdate (3.12s)
=== RUN   TestAccLibratoService_Basic
--- PASS: TestAccLibratoService_Basic (3.25s)
=== RUN   TestAccLibratoService_Updated
--- PASS: TestAccLibratoService_Updated (2.87s)
=== RUN   TestAccLibratoSpaceChart_Basic
--- PASS: TestAccLibratoSpaceChart_Basic (1.87s)
=== RUN   TestAccLibratoSpaceChart_Full
--- PASS: TestAccLibratoSpaceChart_Full (2.32s)
=== RUN   TestAccLibratoSpaceChart_Updated
--- PASS: TestAccLibratoSpaceChart_Updated (2.89s)
=== RUN   TestAccLibratoSpace_Basic
--- PASS: TestAccLibratoSpace_Basic (1.28s)
PASS
ok     	github.com/hashicorp/terraform/builtin/providers/librato       	23.929s
```

Thanks for all the work here :)

Paul

**Comment by elblivion** [comment]
Thanks and sorry for the shoddy work the first time around - still working on getting this rolled out in our environment. 😭

BTW if you have the time: are there any helper functions or useful patterns for calculating hashes of sets in test configs? I had to copy & paste the test config and run Terraform manually to work out the right hash value for the new tests (cf. https://github.com/hashicorp/terraform/blob/master/builtin/providers/librato/resource_librato_alert_test.go#L53)

Thanks!

**Comment by stack72** [comment]
Nothing to apologise for at all sir! :) Providers are an ever evolving thing!

I wish i could say there was a tip for the hash calculation but there isn't. I usually run the test in debug mode and read the logs along the CREATE: log to get the hashes then make the test pass the second time :)

P.

**Pull request closed without merging**
