### PR TITLE
travis: build with go 1.5 now

### PR DESCRIPTION
**Pull request by phinze**
See also: https://github.com/hashicorp/terraform/commit/af04321723200d4cb4158e7e9a6b1f8b9f6aaf1b

### CODE REVIEW

**Comment by stack72** [comment]
@phinze FYI, this is going to really slow down the build. I build terraform locally with 1.5 and it's much slower than 1.4 on travis

**Comment by phinze** [comment]
@stack72 yeah we are aware - we're going to move builtin plugins to be core binary which should help mitigate a bit

We can always go back if we end up really sad. 😄

**Comment by stack72** [comment]
looks good then - as I said, I have been building this with 1.5 for ages so I guess this makes sense to merge :)

**Comment by phinze** [comment]
Alrighty. Hello Go 1.5! :wave:

**Pull request merged**
