### PR TITLE
Added an example of ssl_verify_mode

### PR DESCRIPTION
**Pull request by jjasghar**
- Added some more details about ssl_verify_mode

Signed-off-by: JJ Asghar <jj@chef.io>

### CODE REVIEW

**Comment by apparentlymart** [comment]
Hi @jjasghar! Thanks for this.

I like actually documenting the values for this attribute. I'm a little less sure about including it in the example, since it means that the main example is therefore not a best-practices/secure example.

Do you think it's reasonable to skip adding it to the example here, and just focus on documenting the available options under the argument's own documentation?

**Comment by jjasghar** [comment]
@apparentlymart the irony is that even as not a "secure" practice most non companies who use Chef don't have valid certs on their chef servers. Having it in the example can help highlight how to set that example without having to read through the docs. Granted, by default it is `:verify_peer` which we could put in as the example and then people who need to change it sees the word to change.

**Comment by apparentlymart** [comment]
@jjasghar that seems like a reasonable compromise!

Separately (in another change) it would be ideal to have a way to provide a custom CA certificate to trust, so that it's possible to say "trust my specific CA" rather than "trust _all_ certificates". But I'm not sure what that would entail or how practical it is; happy to merge this docs change in the mean time, as long as the example shows the more secure option.

**Comment by jjasghar** [comment]
Updated :)

**Comment by apparentlymart** [comment]
Thanks, @jjasghar!

**Pull request merged**
