### PR TITLE
provider/vault: vault_policy resource

### PR DESCRIPTION
**Pull request by Mongey**

### CODE REVIEW

**Comment by apparentlymart** [comment]
Hi @Mongey! Thanks for implementing this.

I unfortunately don't have time to properly review an test this today, but I will take a look at it properly soon. I added myself as a reviewer to remind me to take a look next time I'm spending time on Terraform.

**Comment by Mongey** [comment]
@stack72 👍  will update.
I was using the`vault_secret` resource to guide me through implementing this; which is obviously special in the regard that it doesn't implement the`Read` like this should.

**Comment by apparentlymart** [comment]
Yeah, for the secret resource I was being conservative to enable write-only access tokens to be used when populating secrets, but for this one I think we can assume that an admin-ish token will be used and so there isn't a strong reason to support write-only creds here I think.

**Comment by directionless** [comment]
I was just finding myself in need of something like this. Any chance it being merged, or similar features?

**Comment by stack72** [comment]
Hi @Mongey 

Thanks for this - this is now looking good! Tests are passing as well

```
% make testacc TEST=./builtin/providers/vault
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/02/13 18:52:12 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/vault -v  -timeout 120m
=== RUN   TestDataSourceGenericSecret
--- PASS: TestDataSourceGenericSecret (0.56s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestResourceGenericSecret
--- PASS: TestResourceGenericSecret (0.81s)
=== RUN   TestResourcePolicy
--- PASS: TestResourcePolicy (0.78s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/vault	2.170s
```

Paul

**Pull request merged**
