### PR TITLE
Evaluate ignore changes before sending plan to CustomizeDiff

### LINKED ISSUE #22520: Changes to ignored attributes aren't ignored in CustomizeDiff
### Terraform Version

```
Terraform v0.12.6
```

### Terraform Configuration Files
```hcl
provider "vsphere" {
  user           = var.vsphere_user
  password       = var.vsphere_password
  vsphere_server = var.vsphere_server

  # If you have a self-signed cert
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = var.dc
}

data "vsphere_datastore" "datastore" {
  name          = var.datastore
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_compute_cluster" "cluster" {
  name          = var.cluster
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network" {
  name          = var.network
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_virtual_machine" "template" {
  name          = var.template
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_virtual_machine" "vm" {
  name                       = var.vm_name
  resource_pool_id           = data.vsphere_compute_cluster.cluster.resource_pool_id
  datastore_id               = data.vsphere_datastore.datastore.id
  num_cpus                   = 2
  memory                     = 1024
  guest_id                   = data.vsphere_virtual_machine.template.guest_id
  scsi_type                  = data.vsphere_virtual_machine.template.scsi_type
  annotation                 = "test"
  wait_for_guest_net_timeout = -1
  network_interface {
    network_id   = data.vsphere_network.network.id
    adapter_type = data.vsphere_virtual_machine.template.network_interface_types[0]
  }
  disk {
    label          = "disk1"
    datastore_id   = data.vsphere_datastore.datastore.id
    size           = "${var.disk_size}"
    io_share_count = 1000
  }
  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
  }
  lifecycle {
    ignore_changes = [
      clone[0].template_uuid,
      disk[0].datastore_id,
      disk[0].io_share_count,
      disk[0].size,
      disk[0].label,
    ]
  }
}
```

### Debug Output
https://gist.github.com/bill-rich/455d59a7fb9a8d09a5b23674557aadb1

### Expected Behavior
No changes should be made to `disk.0` because all changed attributes are ignored.

### Actual Behavior
`CustomizeDiff` still runs and modifies `disk.0` because the changes are still returned from `GetChange`.  See [line 2738](https://gist.github.com/bill-rich/455d59a7fb9a8d09a5b23674557aadb1#file-tf-log-L2739) for the output of `GetChange`.

### Steps to Reproduce
1. Deploy resource that utilizes `CustomizeDiff` and modifies plan based on changes.
2. Use `lifecycle` to ignore changes to attributes that would trigger `CustomizeDiff` to make modifications.
3. Make change to attribute that would trigger `CustomizeDiff` to make modifications.

### PR DESCRIPTION
**Pull request by pselle**
When we send back the plan to providers, changes were included that should've been caught by `ignore_changes` -- what this causes is that providers who use CustomizeDiff would see extraneous changes they weren't expecting. Thus, this in this change, we process `ignore_changes` before running the plan, so that nodes will be excluded, thus preventing unexpected changes from being included in CustomizeDiff. If anyone was relying on the old behavior, the solution would be to remove the attribute from `ignore_changes` so that it will change (not be ignored) which was the old behavior, for changed values that would be impacted by CustomizeDiff, but set in `ignore_changes`

Also includes some dead code removal, and renaming of the existing `ignore_changes` processing to be clearer.

Fixes #22520

### CODE REVIEW

**Comment by apparentlymart** [comment]
This change looks good to me, and it's encouraging that it didn't cause any regressions for existing tests!

With that said, this _is_ still a change to existing behavior, so I think we need to be cautious with it. I think the risk of misbehavior is relatively small; it would take a rather unusual configuration to see it. Given that, I'm thinking we probably _could_ get away with including this in a minor release with a prominent changelog release note, but I also had a think about ways we might be able to make things more explicit for those whose existing configurations might exhibit new behavior after upgrading.

One idea that came to mind was to add an additional validation rule on `ignore_changes` to produce an error if one of the traversals in there is through a `Computed` attribute that isn't explicitly set in the configuration. That would both make it explicit for new users that `ignore_changes` only applies to values in the configuration, _and_ serve to force anyone who is already ignoring provider-set attributes to review and adjust rather than inadvertently applying a bad plan.

To put that in the same terms as your existing test cases, the following configuration would produce an error:

```hcl
resource "test_resource" "foo" {
  required     = "yep"
  required_map = {
    key = "value"
  }
  lifecycle {
    ignore_changes = [optional]
  }
}
```

...because `optional` is `Optional`+`Computed` and not set in the configuration. Similarly, if `ignore_changes` contained `planned_computed` that would also be an error, because that attribute isn't _and cannot be_ set in the configuration (because it's just `Computed`).

Perhaps we'd have two different error messages here reflecting the subtle difference between those two situations, to avoid leading the user to another error in the case where it can't be set at all:

```
Error: Cannot ignore unconfigured argument

  at example.tf line X, in resource "test_resource" "foo":
    7:    ignore_changes = [optional]

The argument "optional" is not set in the configuration. The ignore_changes
mechanism applies to changes within the configuration only, so you can use
it only for arguments whose values you've explicitly set.
```

```
Error: Cannot ignore unconfigured argument

  at example.tf line X, in resource "test_resource" "foo":
    7:    ignore_changes = [planned_computed]

The value of attribute "planned_computed" is decided by the provider,
rather than set in the configuration. The ignore_changes mechanism
applies to changes within the configuration only, so you can use it
only for configurable arguments.
```

What do you think? I'm not feeling totally sure on this yet... it might still be a bit too "breaky" for a minor release, but I wanted to think that out together so we can try to find a compromise that could help us get this out sooner for the folks who are feeling blocked but minimizing potential for knock-on effects for others. :thinking:

**Comment by teamterraform** [comment]
As much as I want to just fix this now, I think making that an error needs to wait until a major release because it would error on configs that are working. Since there's no validation at all right now, there are many configurations with junk in `ignore_changes` that appear to work, and we could add full validation later on to clear that up. 

While I was leaving validation out entirely for now (sorry, forgot to mention this earlier Pam), it would probably be beneficial to implement it now. We can log the errors which can help in debugging, and possibly present them as warning to the user.

Another idea to help prevent breakage in 0.12 is to re-run `ignore_changes` again after the plan, and remove the extra run in the next major release. This would essentially restore the old behavior, and provide a more solid warning to the user that the provider has overriden the value. While I haven't seen it yet in practice, I would not be surprised if users have plastered over 0.12 behavioral changes in providers by using `ignore_changes`, and are currently relying on suppressing plan output.

**Comment by jbardin** [comment]
As much as I want to just fix this now, I think making that an error needs to wait until a major release because it would error on configs that are working. Since there's no validation at all right now, there are many configurations with junk in ignore_changes that appear to work, and we could add full validation later on to clear that up.

While I was leaving validation out entirely for now (sorry, forgot to mention this earlier Pam), it would probably be beneficial to implement it now. We can log the errors which can help in debugging, and possibly present them as warning to the user.

Another idea to help prevent breakage in 0.12 is to re-run ignore_changes again after the plan, and remove the extra run in the next major release. This would essentially restore the old behavior, and provide a more solid warning to the user that the provider has overriden the value. While I haven't seen it yet in practice, I would not be surprised if users have plastered over 0.12 behavioral changes in providers by using ignore_changes, and are currently relying on suppressing plan output.

**Comment by pselle** [comment]
> ... and it's encouraging that it didn't cause any regressions for existing tests!

Bad news, it did -- I put this up as a PR partially to get the tests to run remotely, but when I ran them locally, I did get some failures to dig into, and the remote tests are running now, and I would be happy to hear they "just work" (that is, a my-machine problem) but at least one Context2Apply test was implicated.

> We can log the errors which can help in debugging, and possibly present them as warning to the user.

I like this mode vs the error.

> Another idea to help prevent breakage in 0.12 is to re-run ignore_changes again after the plan, and remove the extra run in the next major release. 
Hmm! I can look into this.

**Comment by apparentlymart** [comment]
After thinking through various permutations of what running `ignore_changes` twice might affect elsewhere in the system, I feel _mostly_ convinced that the result should only ignore _more_ things, and not _fewer_ things. That's a safe change in behavior in the sense that it won't cause Terraform to plan to replace things it wouldn't have before.

There may be configurations out there which were previously _intentionally_ not ignoring certain things in order to trigger replacement and this change would cause them to now never trigger replacement. That's just an annoying change in behavior rather than a harmful one, and so I think it'd be okay to ship that in a minor release for the greater good (I expect it will fix things for many more people than it will inconvenience) as long as we can come up with a helpful way to describe the change in behavior so that users can decide if the change is likely to affect them.

**Comment by pselle** [comment]
@apparentlymart Yes, I think the changelog/wording will focus on that this impacts users who might now see changes appropriately ignored, such that if they want to _un_ignore them, they'll have to remove the key from `ignore_changes`

**Pull request merged**
