### PR TITLE
New AWS resource `ssm_activation`

### PR DESCRIPTION
**Pull request by liamjbennett**
Adding a new resource to support activation of managed instances for
on-premise virtual-machines.

Last of the resources to close off #4952

### CODE REVIEW

**Comment by liamjbennett** [comment]
This is currently blocked by an issue that needs some deeper investigation. At the moment the tests are receiving the error:
```[ERROR] Error creating SSM activation: ValidationException: Not existing role: arn:aws:iam::483560084512:role/AROAJVG36BCT2PT2QMVOW```

I have been able to re-create this error manually in the console by creating an activation using a custom role with an incorrect assume role policy however it is unclear why this test is failing.

**Comment by liamjbennett** [comment]
Debugging this I have discovered that there is an issue related specifying the region. When running similar commands via the cli the --region flag needs to be specified if not reading from the environment. In addition it appears from debugging the console that region is specified as part of the request.

I am unclear at this stage if this is an issue with my implementation or with the sdk

**Comment by liamjbennett** [comment]
```
➜  terraform git:(ssm_activation) ✗ TF_LOG=TRACE TF_LOG_PATH=test.log make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSSSMActivation_basic'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/10/28 09:59:37 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSSSMActivation_basic -timeout 120m
=== RUN   TestAccAWSSSMActivation_basic
--- PASS: TestAccAWSSSMActivation_basic (23.18s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/aws    23.188s
```

**Comment by stack72** [comment]
LGTM! Thanks @liamjbennett :)

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSSSMActivation_'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/10/28 11:57:05 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSSSMActivation_ -timeout 120m
=== RUN   TestAccAWSSSMActivation_basic
--- PASS: TestAccAWSSSMActivation_basic (39.60s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	39.620s
```

**Pull request merged**
