### PR TITLE
Do not return a root device for instance store backed AMIs.

### LINKED ISSUE #8732: Unable to create an aws_launch_configuration with an instance store AMI
### Terraform Version

```
$ terraform --version
Terraform v0.7.3
```
### Affected Resource(s)
- aws_launch_configuration
### Terraform Configuration Files

``` hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_launch_configuration" "test-launch-config" {
  image_id = "ami-01f69916" // us-east-1 ubuntu 12.04 amd64 hvm instance-store
  instance_type = "c3.large"
}
```
### Debug Output

```
$ terraform apply
aws_launch_configuration.test-launch-config: Creating...
  associate_public_ip_address: "" => "false"
  ebs_block_device.#:          "" => "<computed>"
  ebs_optimized:               "" => "<computed>"
  enable_monitoring:           "" => "true"
  image_id:                    "" => "ami-01f69916"
  instance_type:               "" => "c3.large"
  key_name:                    "" => "<computed>"
  name:                        "" => "<computed>"
  root_block_device.#:         "" => "<computed>"
Error applying plan:

1 error(s) occurred:

* aws_launch_configuration.test-launch-config: [WARN] Error finding Root Device Name for AMI (ami-01f69916)

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```
### Expected Behavior

Launch config should have been created.
When using the same AMI without block devices on a `aws_instance` resource, everything works fine.
### Actual Behavior

Fails with an error:
`Error finding Root Device Name for AMI (ami-01f69916)`
### Steps to Reproduce

`terraform apply`

### PR DESCRIPTION
**Pull request by tomwilkie**
Fixes #8732 

@tpounds opening the PR for you - I just hit this myself.

### CODE REVIEW

**Comment by stack72** [comment]
Hi @tomwilkie 

Any chance we could get a test in place to show this works as expected?

:)

P.

**Comment by tomwilkie** [comment]
@stack72 I didn't write this, its not my branch.  I just found the tested the fix locally, so I thought it would be worth a PR.

**Comment by tpounds** [comment]
@stack72, @tomwilkie Apologies for the delay. I pushed this branch to quickly fix the issue on our end but didn't spend any time to add an acceptance test. I've added it now. Please ping me if there is something else I should address

**Comment by tpounds** [comment]
@stack72 Is this fix ok to merge? Several people are waiting on it.

cc @tomwilkie @omribahumi @jbussdieker @michael-henderson

**Comment by stack72** [comment]
Hey @tomwilkie / @tpounds 

Thanks for the team work here on this :) LGTM!

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSInstance_'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/12/01 15:06:54 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSInstance_ -timeout 120m
=== RUN   TestAccAWSInstance_importBasic
--- PASS: TestAccAWSInstance_importBasic (108.41s)
=== RUN   TestAccAWSInstance_basic
--- PASS: TestAccAWSInstance_basic (158.61s)
=== RUN   TestAccAWSInstance_GP2IopsDevice
--- PASS: TestAccAWSInstance_GP2IopsDevice (85.35s)
=== RUN   TestAccAWSInstance_blockDevices
--- PASS: TestAccAWSInstance_blockDevices (127.45s)
=== RUN   TestAccAWSInstance_rootInstanceStore
--- PASS: TestAccAWSInstance_rootInstanceStore (78.17s)
=== RUN   TestAccAWSInstance_sourceDestCheck
--- PASS: TestAccAWSInstance_sourceDestCheck (214.47s)
=== RUN   TestAccAWSInstance_disableApiTermination
--- PASS: TestAccAWSInstance_disableApiTermination (183.05s)
=== RUN   TestAccAWSInstance_vpc
--- PASS: TestAccAWSInstance_vpc (129.07s)
=== RUN   TestAccAWSInstance_multipleRegions
--- PASS: TestAccAWSInstance_multipleRegions (129.45s)
=== RUN   TestAccAWSInstance_NetworkInstanceSecurityGroups
--- PASS: TestAccAWSInstance_NetworkInstanceSecurityGroups (143.42s)
=== RUN   TestAccAWSInstance_NetworkInstanceVPCSecurityGroupIDs
--- PASS: TestAccAWSInstance_NetworkInstanceVPCSecurityGroupIDs (143.38s)
=== RUN   TestAccAWSInstance_tags
--- PASS: TestAccAWSInstance_tags (124.90s)
=== RUN   TestAccAWSInstance_privateIP
--- PASS: TestAccAWSInstance_privateIP (239.87s)
=== RUN   TestAccAWSInstance_associatePublicIPAndPrivateIP
--- PASS: TestAccAWSInstance_associatePublicIPAndPrivateIP (250.50s)
=== RUN   TestAccAWSInstance_keyPairCheck
--- PASS: TestAccAWSInstance_keyPairCheck (88.48s)
=== RUN   TestAccAWSInstance_rootBlockDeviceMismatch
--- PASS: TestAccAWSInstance_rootBlockDeviceMismatch (120.83s)
=== RUN   TestAccAWSInstance_forceNewAndTagsDrift
--- PASS: TestAccAWSInstance_forceNewAndTagsDrift (362.08s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	2687.512s
```

**Pull request merged**
