### PR TITLE
[WIP] Support AWS Data Pipeline

### PR DESCRIPTION
**Pull request by pawelsawicz**
Add support for AWS [Data Pipeline](http://docs.aws.amazon.com/datapipeline/latest/APIReference/Welcome.html)

It's related to this [feature request](https://github.com/hashicorp/terraform/issues/4077)

### CODE REVIEW

**Comment by coen-hyde** [comment]
How far is this away from being merged? It would be great to see it in Terraform

**Comment by pawelsawicz** [comment]
@coen-hyde hey I am having trouble with tests but I am still working on it.

**Comment by aaronbuchanan** [comment]
Thanks @pawelsawicz We're eagerly looking forward to this one!

**Comment by stack72** [comment]
@pawelsawicz want to pair through some of the tests on this?

**Comment by pawelsawicz** [comment]
@stack72 yes that would be helpful do you have time today after 19:00 UTC ?

**Comment by stack72** [comment]
i'll ping you offline and we can fix something up - I am not free tonight but will be tomorrow

**Comment by tecnobrat** [comment]
Any new news on this one?

**Comment by petterl** [comment]
I am also hoping for this PR, we are moving out datapipelines to code, and have currently had to move it to ruby code, but would love to convert it to terraform.

**Comment by cargom98** [comment]
great feature to have ...

**Comment by stack72** [comment]
Hey @pawelsawicz 

I am going to go ahead and close this PR - please feel free to open a new one if you do get time to work on it

thanks

Paul

**Comment by ifuyivara** [comment]
what's missing from this PR? Is it just the Tests? We need this feature. I'll be glad to help finish whatever is missing here. 

Thanks!

**Comment by FLGale** [comment]
Any word on when this can be merged?

**Comment by ayr-ton** [comment]
Hello darkness my old friend

**Pull request closed without merging**
