### PR TITLE
vendor: Update hashicorp/hcl to latest version

### LINKED ISSUE #5550: 0.6.12 escaping double quotes inside function argument is broken
I believe this is a recurrence of the issue described in #613 but supposedly fixed by #785

this breaks (`parse error: syntax error`):
```
server_list = "${join(",", formatlist("\"%s\"", aws_instance.consul_cluster.*.private_ip))}"
```

this works:
```
server_list = "${join(",", formatlist("%s", aws_instance.consul_cluster.*.private_ip))}"
```

the difference is the `\"` around the `%s`

### PR DESCRIPTION
**Pull request by phinze**
Catches https://github.com/hashicorp/hcl/pull/132

Fixes #5550

### CODE REVIEW

**Comment by catsby** [comment]
Syntax error in `TestLoadFileEscapedQuotes` test ... 

```
--- FAIL: TestLoadFileEscapedQuotes (0.00s)
	loader_test.go:137: err: Error loading test-fixtures/escapedquotes.tf: Error reading config for aws_instance[quotes]: parse error: syntax error
aws_instance.bar (x1)
  ami
aws_instance.baz (x1)
  ami
aws_instance.web (x1)
  amicloudstack_firewall.test (x1)
  ipaddress
  rulecloudstack_firewall.test (x1)
  ipaddress
  ruleFAIL
FAIL	github.com/hashicorp/terraform/config	0.060s
```

**Comment by phinze** [comment]
Ah yes - we covered that case at the TF layer too - will add in a commit to update those and follow up in a bit here

**Comment by jen20** [comment]
@phinze I've sorted out the test for this, so we should be green shortly. Will merge pending that!

**Comment by catsby** [comment]
👍 pending 👍 from Travis

**Pull request merged**
