### PR TITLE
website: decrease the title font size in the docs

### PR DESCRIPTION
**Pull request by berendt**
At the moment long resource names (e.g. OPENSTACK_BLOCKSTORAGE_VOLUME_V1)
break the documentation layout.

### CODE REVIEW

**Comment by apparentlymart** [comment]
Ahh yes, I've been noticing this on more and more resources as we start to build out the AWS resources named things like ``aws_servicename_noun``. Thanks for working on this!

Here's how it looks after your diff is applied:
screenshot from 2015-10-04 15 01 52

The main title now fits a lot better. The visual hierarchy of the page feels a little off now though, since the inline level-1 headings are now larger than the overall page title. Do you think there's room here for a compromise where the page heading is left a little larger than you left it, and then the level-1 headings also shrink to somewhere between the body text and the page heading text?

Using the resource name as the page title is pretty awkward since it's not amenable to wrapping to make it fit better when it's too long. Part of me wonders if we should switch to using a human-oriented resource description as the title, leaving the literal resource name for the body text:

screenshot from 2015-10-04 15 09 50

Moving away from using the literal name allows us to drop the arguably-redundant service name prefix (``aws_`` in this case) and could allow for wrapping long names over multiple lines. However, I'd concede that it does feel a bit artificial.

With all of that said, I'm not really sure what feels best here... but I agree that the current setup isn't working so well. :grinning:

**Comment by berendt** [comment]
@apparentlymart 32pt should be fine. I also cleaned the syntax of the ``_docs.scss`` file.

**Comment by apparentlymart** [comment]
Here's how it looks with 32px:

screenshot from 2015-10-05 09 23 58

@captainill what do you think? Seems like this one is in your department. :grinning:

**Comment by stack72** [comment]
@apparentlymart I agree with the statement above that we should drop the aws_ part of the resource. I think if we really needed it, we could do a breadcrumb like

Docs > Providers > AWS

App Cookie Stickiness Policy

**Comment by berendt** [comment]
Introducing breadcrumbs is a good idea. I could have a look on it. Anyway, I think the ``h1`` titles are too big at the moment, independent of the introduction of breadcrumbs.

**Comment by captainill** [comment]
Breadcrumbs would be good for sure.

This layout is a bit fragile given these resource names. It's making me think a bit about it generally... 

@apparentlymart @berendt So I think 32px is a little small on desktop. It appears 36px for h1's would still accommodate all of these resource names (currently anyway) at `(min-width: 1200px)`. Maybe we just add that as another responsive style on top of these current changes?

```
@media (min-width: 1200px) {
  .bs-docs-section{
    h1{
      font-size: 36px;
      line-height: 36px;
    }
  }
}
```

**Comment by jen20** [comment]
This should be addressed by #4317.

**Pull request closed without merging**
