### PR TITLE
provider/google: Pull a google_compute_backend resource out of the google_compute_backend_service resource.

### PR DESCRIPTION
**Pull request by zachgersh**
This covers the case where you decide to use a `count` on creation of an `instance_group` and then the `google_compute_instance_group.foobar.*.self_link` syntax to grab the list of all instance groups

The `backend` now either excepts `group` or `groups`. When specifying `groups` it will take the values that you set for properties such as `balancing_mode` and share that across all of the instance groups.

Also, original implementation had `flatten_backend` as a function but it does not seem to be required so it was removed.

### CODE REVIEW

**Comment by danawillow** [comment]
Thanks for the PR! I took a look, and I don't love that this ends up changing the resource schema so that it differs from the official API.

Just to make sure I understand what you're trying to accomplish, here's the use case:
- You create multiple instance_groups using the `count` meta-parameter on the instance_group resource
- You want to create a backend service with some number of backends, each of which references one of the instance groups
- Since `backend` isn't on its own a resource, it doesn't have the same special `count` parameter
- So adding a new field that allows the * syntax lets you do what you would accomplish using `count` so you don't have to copy and paste the same thing a whole bunch of times into your configuration.

I'm not sure if there's precedent in introducing a new parameter like this, but I'm also not sure if there's a way around it. @paddyforan, any thoughts?

**Comment by zachgersh** [comment]
Hey @danawillow I think you have it correct with the bullet points and I really appreciate the question! 

I think that making `groups` a brand new parameter now fits better into the terraform paradigm of being able to programmatically pave infrastructure. Working with `backends` previously was clunky as you would need to pre-specify something like this:

```go
backend {
  group = "some-instance-group"
}

backend {
  group = "some-other-instance-group"
}

backend {
  group = "one-more-instance-group"
}
```

The big problem with the template above is that I have no idea how many`instance_groups` I have before they have been terraformed.  Users get to pick that based on the region they are deploying to and the number of zones that region has (one `instance_group` per zone).

I feel like there is a little harm in introducing a new parameter especially since old behavior is unaffected and we have no need to deprecate the old one (unless you feel otherwise). I also don't think it strays too far from the original convention of the API since what it feels like we are doing is a bit of a shorthand syntax for multiple backends.

I would be open to re-working this if there is a better idea - just let me know.

Apologies for the delays in answering.

**Comment by paddyforan** [comment]
Apologies of my own for the delayed response, I was having trouble picking through the intricacies of this issue well enough to come to an informed opinion, so it kept getting pushed to the back of my queue. Thanks @zachgersh for opening the PR!

So my thoughts on this are that generally we have no problems adding a new field to a resource, _as long as_ we're comfortable supporting it over time, meaning we think we've come to the right solution. In this specific case, I'm hesitant just because, as @danawillow pointed out, we're diverging from the API concepts a bit here. And while I can't see how we'd get ourselves in trouble in this specific case, that (in general) just makes me uncomfortable.

That said, I think this is a use case we should support. How do y'all feel about an alternative suggestion: what if we add a `compute_backend` resource that exists to just house the `balancing_mode`, `capacity_scaler`, `description`, `group`, `max_connections`, `max_connections_per_instance`, `max_rate`, `max_rate_per_instance`, and `max_utilization` attributes associated with the current `backend` attribute?

That would, if I understand correctly (please do correct me if I'm not!) allow us to solve the problem in a way that's a more faithful abstraction of the API concepts involved. What do y'all think?

**Comment by zachgersh** [comment]
Hey @paddyforan - I don't mind the suggestion and would be willing to implement it this way but working through the syntax of how this would work I see a bit of a problem, how do we set one `instance_group` onto each `compute_backend`:

```
resource "google_compute_backend_service" "foobar" {
  name        = "blablah"
  description = "Hello World 1234"
  port_name   = "http"
  protocol    = "HTTP"
  timeout_sec = 10
  enable_cdn  = false

  backend = "${google_compute_backend.baz.self_link}"

  health_checks = ["${google_compute_http_health_check.default.self_link}"]
}

resource "google_compute_backend" "baz" {
  description = "something great"
  count = 3
  group =  "${google_compute_instance_group.${count.index}.some-ig}"
  // what we would want is something like this but it is invalid
}

resource "google_compute_instance_group" "some-ig" {
  name = "wow"
  count = 3
  zone = "${element(var.zones, count.index)}"
}
```

I only know of the `*` to grab the full list of `google_compute_instance_group` that I have created. I don't think you can do a double interpolation to use the count from `google_compute_backend` to get each numbered `google_compute_instance_group`.

**Comment by zachgersh** [comment]
bump @danawillow / @paddyforan - I was also wondering whether the set of resources returned, when created by using `count`, are returned as a collection type? That would allow me to tweak this syntax above.

**Comment by paddyforan** [comment]
Hey @zachgersh, really sorry for the delay on this one. I had to investigate the answer a bit, `count` isn't my strongest suit. :(

Here's what I'm imagining the config would look like:

```tf
resource "google_compute_backend_service" "foobar" {
  name        = "blablah"
  description = "Hello World 1234"
  port_name   = "http"
  protocol    = "HTTP"
  timeout_sec = 10
  enable_cdn  = false

  backend = "${google_compute_backend.baz.self_link}"

  health_checks = ["${google_compute_http_health_check.default.self_link}"]
}

resource "google_compute_backend" "baz" {
  description = "something great"
  count = 3
  group =  "${element(google_compute_instance_group.*.some-ig, count.index)}"
}

resource "google_compute_instance_group" "some-ig" {
  name = "wow"
  count = 3
  zone = "${element(var.zones, count.index)}"
}
```

I obviously can't test that as is, but preliminary research (for example: https://blog.gruntwork.io/terraform-tips-tricks-loops-if-statements-and-gotchas-f739bbae55f9, https://charity.wtf/2016/04/14/scrapbag-of-useful-terraform-tips/) says that something like that should work? What do you think?

**Comment by zachgersh** [comment]
@paddyforan sounds good to me - I will try to modify this tonight and push the commit back to this open PR. We'll see how it goes 👍

**Comment by zachgersh** [comment]
@paddyforan - I started to implement this and I hit my first question - what is the `self_link` that relates the `backend` to the `backend_service`? A `backend` from the GCP perspective is never created without a `backend_service` and that is what actually has an id associated with it. I could shoehorn something together but it wouldn't match up with the rest of the provider.

The original implementation attached may actually be the best way forward the more I look at this (since it keeps the resource parts together).

Apologies for no comments for so long - getting back into it.

**Comment by zachgersh** [comment]
hey @paddyforan - would love to bump this for inclusion. Switching to this will allow us to simplify our terraform templates / upgrade.

**Comment by paddyforan** [comment]
Hey @zachgersh! Thanks for contributing this, sorry it has been open so long and went so long without a reply. I've fallen behind. :(

> I started to implement this and I hit my first question - what is the self_link that relates the backend to the backend_service? A backend from the GCP perspective is never created without a backend_service and that is what actually has an id associated with it. I could shoehorn something together but it wouldn't match up with the rest of the provider.

I may have inadvertently sent you down the wrong path on this one, and am terribly sorry if I did. :( You're totally right that the `self_link` doesn't really exist for the backend type... which puts us in a pickle. I'm having some trouble seeing a good direction forward on this one. I think you may be right that the original implementation of `groups` is the closest we're going to get to the API, and the question is now whether it's close enough to justify the feature. If you don't mind, is it OK if I have a conversation about this Thursday afternoon to weigh the options and get back to you? Sorry for the further delays on this. :(

**Comment by zachgersh** [comment]
@paddyforan no problem. I've got another change coming soon (for IAM related to GCP projects). That is a big one (I am going to comment on the bug agian). As it has effectively stopped us from upgrading terraform to beyond 0.84

**Comment by paddyforan** [comment]
Cool. That's a contentious topic, I know, so if you want to chat/have a call/whatever before you sink too much time into a PR just to talk details/design, I'm happy to work something out. :) I always feel terrible saying "thanks for spending so much time on this, but this just isn't something we want to support", so things that lower the chances of that happening are 👍 in my books.

**Comment by zachgersh** [comment]
@paddyforan sounds great - should I just email you to setup a hangout?

**Comment by paddyforan** [comment]
Sure thing; I'm paddy@{githuborg}.com. :)

**Comment by paddyforan** [comment]
Just took another look at this. I'm left with one question, and I think it's merge-ready.

I think this removes `flattenBackends`, and just sets backends in state as they are. If that's the case, and backends have a different format than `flattenBackends` (I think they do?), I believe we need a schema migration for this.

**Comment by zachgersh** [comment]
@paddyforan not a problem at all! Can you point at an example of a schema migration? I don't have a problem doing it and I have no idea when this situation would crop up due to the fact that when I removed this function all the tests continued to work exactly the same.

Could we maybe engineer a test that proves out the need for the migration?

**Comment by paddycarver** [comment]
Hey @zachgersh,

You can see the migration we did for the `google_project` here: https://github.com/hashicorp/terraform/blob/4441c6f53bee67be1c1637cfebee197ef9662c94/builtin/providers/google/resource_google_project_migrate.go

You can see the tests for it here: https://github.com/hashicorp/terraform/blob/4441c6f53bee67be1c1637cfebee197ef9662c94/builtin/providers/google/resource_google_project_migrate_test.go

Unfortunately, we don't have a way (right now) to have test cases prove backwards incompatibility in the state, as far as I know. I can raise it with the team, but I think it would require an entirely new test harness. I could be wrong about that, though.

**Comment by apparentlymart** [comment]
Hello @zachgersh, and thanks for working on this!

As part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it.

If you or someone else has the time and motivation to apply the same changes to [the Google Cloud provider repository](https://github.com/terraform-providers/terraform-provider-google) and open a new PR there to continue this work, the maintainers of that provider should be able to review it.

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Pull request closed without merging**
