### PR TITLE
[WIP] Added Codecommit Trigger

### PR DESCRIPTION
**Pull request by optimisticanshul**
Adds #6973

### CODE REVIEW

**Comment by optimisticanshul** [comment]
It's still in progress

**Comment by optimisticanshul** [comment]
@stack72 Hey need help here. I am not sure how to pass triggers 
```
builtin/providers/aws/resource_aws_codecommit_trigger.go:90: cannot use triggers (type *schema.Set) as type []*codecommit.RepositoryTrigger in field value
```
Newbie to go and terraform :(

**Comment by stack72** [comment]
Hi @optimisticanshul 

No worries - thanks for the work here :)

You need to actually transform that set from Terraform into something that the AWS SDK is compatible with. You can look at something like an expand func [example](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/structure.go#L325) and then when Reading it back from the SDK, you will need to [flatten](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/structure.go#L645) it :)

**Comment by optimisticanshul** [comment]
@stack72 Thanks, i have updated it but still in WIP stage.

```
resource "aws_sns_topic" "sns" {
  name = "user-updates-topic"
}

resource "aws_codecommit_repository" "repo" {
  repository_name = "TestRepository"
  description = "This is the Sample App Repository"
}

resource "aws_codecommit_trigger" "sns" {
  repository_name = "TestRepository"
  trigger {
    name = "test"
    branches = ["All Branches"]
    events = ["all"]
    destination_arn = "${aws_sns_topic.sns.id}"
  }
}
```

```
+ aws_codecommit_trigger.sns
    configuration_id:                       "<computed>"
    repository_name:                        "MyTestRepository"
    trigger.#:                              "1"
    trigger.2550118732.branches.#:          "2"
    trigger.2550118732.branches.2294493954: "All Branches"
    trigger.2550118732.branches.755606486:  "master"
    trigger.2550118732.custom_data:         ""
    trigger.2550118732.destination_arn:     "arn:aws:sns:us-east-1:539114338268:user-updates-topic"
    trigger.2550118732.events.#:            "1"
    trigger.2550118732.events.991457757:    "all"
    trigger.2550118732.name:                "test"
    trigger.3250997206.branches.#:          "2"
    trigger.3250997206.branches.2294493954: "All Branches"
    trigger.3250997206.branches.755606486:  "master"
    trigger.3250997206.custom_data:         ""
    trigger.3250997206.destination_arn:     "arn:aws:sns:us-east-1:539114338268:user-updates-topic"
    trigger.3250997206.events.#:            "1"
    trigger.3250997206.events.991457757:    "all"
    trigger.3250997206.name:                "test"


Plan: 1 to add, 0 to change, 0 to destroy.
```

But on apply

```
Error applying plan:

2 error(s) occurred:

* aws_codecommit_trigger.sns: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.7.0
    Resource ID: aws_codecommit_trigger.sns
    Mismatch reason: attribute mismatch: trigger.1303349384.branches.2294493954
    Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"repository_name":*terraform.ResourceAttrDiff{Old:"", New:"TestRepository", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "trigger.912964690.events.991457757":*terraform.ResourceAttrDiff{Old:"", New:"all", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "trigger.1303349384.events.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "trigger.912964690.destination_arn":*terraform.ResourceAttrDiff{Old:"", New:"arn:aws:sns:us-east-1:539114338268:user-updates-topic", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "trigger.912964690.name":*terraform.ResourceAttrDiff{Old:"", New:"test", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "trigger.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "trigger.912964690.branches.#":*terraform.ResourceAttrDiff{Old:"0", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "trigger.912964690.custom_data":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "trigger.912964690.events.#":*terraform.ResourceAttrDiff{Old:"0", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "trigger.1303349384.destination_arn":*terraform.ResourceAttrDiff{Old:"", New:"arn:aws:sns:us-east-1:539114338268:user-updates-topic", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "trigger.1303349384.branches.2294493954":*terraform.ResourceAttrDiff{Old:"", New:"All Branches", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "trigger.1303349384.branches.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "configuration_id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "trigger.1303349384.name":*terraform.ResourceAttrDiff{Old:"", New:"test", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "trigger.1303349384.custom_data":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "trigger.1303349384.events.991457757":*terraform.ResourceAttrDiff{Old:"", New:"all", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "trigger.912964690.branches.2294493954":*terraform.ResourceAttrDiff{Old:"", New:"All Branches", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"trigger.325730924.custom_data":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "repository_name":*terraform.ResourceAttrDiff{Old:"", New:"TestRepository", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "trigger.4229609250.events.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "trigger.4229609250.destination_arn":*terraform.ResourceAttrDiff{Old:"", New:"arn:aws:sns:us-east-1:539114338268:user-updates-topic", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "trigger.4229609250.branches.2294493954":*terraform.ResourceAttrDiff{Old:"", New:"All Branches", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "trigger.325730924.branches.#":*terraform.ResourceAttrDiff{Old:"0", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "trigger.325730924.events.#":*terraform.ResourceAttrDiff{Old:"0", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "trigger.4229609250.custom_data":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "trigger.325730924.branches.2294493954":*terraform.ResourceAttrDiff{Old:"", New:"All Branches", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "trigger.325730924.name":*terraform.ResourceAttrDiff{Old:"", New:"test", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "trigger.4229609250.name":*terraform.ResourceAttrDiff{Old:"", New:"test", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "trigger.325730924.events.991457757":*terraform.ResourceAttrDiff{Old:"", New:"all", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "configuration_id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "trigger.325730924.destination_arn":*terraform.ResourceAttrDiff{Old:"", New:"arn:aws:sns:us-east-1:539114338268:user-updates-topic", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "trigger.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "trigger.4229609250.events.991457757":*terraform.ResourceAttrDiff{Old:"", New:"all", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "trigger.4229609250.branches.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
```
Any leads where shall i further look at :(

**Comment by jgangemi** [comment]
curious what the status on this is, i'd really like to make use of this.

**Comment by stack72** [comment]
Hi @optimisticanshul 

Did you manage to get any further on this?

Paul

**Comment by optimisticanshul** [comment]
Almost forgot about this, i will get this done by end of this week.

**Comment by stack72** [comment]
Thanks @optimisticanshul 

Paul

**Comment by optimisticanshul** [comment]
@stack72 Hey can i get some help in this i am getting strange error not sure how to debug.
```
panic: interface conversion: interface is nil, not string
```
It don't provide where this issue is :(

**Comment by stack72** [comment]
Hi @optimisticanshul 

The error will be in a line number maybe 3 or 5 lines below this

If you paste the first 7 lines of the panic i can help point it out

Paul

**Comment by optimisticanshul** [comment]
```
aws_codecommit_trigger.trigger: Creating...
  repository_name:                   "" => "TestRepository"
  trigger.#:                         "" => "1"
  trigger.994057110.branches.#:      "" => "1"
  trigger.994057110.branches.0:      "" => "All Branches"
  trigger.994057110.custom_data:     "" => ""
  trigger.994057110.destination_arn: "" => "arn:aws:sns:us-east-1:032007425339:user-updates-topic"
  trigger.994057110.events.#:        "" => "1"
  trigger.994057110.events.0:        "" => "all"
  trigger.994057110.name:            "" => "test"
2016/09/09 01:06:14 [DEBUG] plugin: terraform: Error applying plan:

1 error(s) occurred:

* aws_codecommit_trigger.trigger: unexpected EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
panic: interface conversion: interface is nil, not string
2016/09/09 01:06:14 [DEBUG] plugin: terraform:
2016/09/09 01:06:14 [DEBUG] plugin: terraform: goroutine 248 [running]:
2016/09/09 01:06:14 [DEBUG] plugin: terraform: panic(0x3267300, 0xc820822580)
2016/09/09 01:06:14 [DEBUG] plugin: terraform: 	/usr/local/go/src/runtime/panic.go:481 +0x3e6
2016/09/09 01:06:14 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsCodeCommitRepositoryCreate(0xc8203b3aa0, 0x26de2e0, 0xc8204c9500, 0x0, 0x0)
2016/09/09 01:06:14 [DEBUG] plugin: terraform: 	/Users/anssharma/Code/go/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_codecommit_repository.go:87 +0x223
2016/09/09 01:06:14 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc82075ec60, 0xc8205379a0, 0xc8205aad40, 0x26de2e0, 0xc8204c9500, 0xc8203fa301, 0x0, 0x0)
2016/09/09 01:06:14 [DEBUG] plugin: terraform: 	/Users/anssharma/Code/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:162 +0x29a
2016/09/09 01:06:14 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc8207e70e0, 0xc8206cfdc0, 0xc8205379a0, 0xc8205aad40, 0x5a7c301, 0x0, 0x0)
2016/09/09 01:06:14 [DEBUG] plugin: terraform: 	/Users/anssharma/Code/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:178 +0x1ed
2016/09/09 01:06:14 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc82021e080, 0xc8205aaca0, 0xc82050a5d0, 0x0, 0x0)
2016/09/09 01:06:14 [DEBUG] plugin: terraform: 	/Users/anssharma/Code/go/src/github.com/hashicorp/terraform/plugin/resource_provider.go:460 +0x76
```
@stack72

**Comment by stack72** [comment]
Hi @optimisticanshul 

The issue is on `resource_aws_codecommit_repository.go:87`

can you paste me that line?

**Comment by optimisticanshul** [comment]
```
	input := &codecommit.CreateRepositoryInput{
		RepositoryName:        aws.String(d.Get("repository_name").(string)),
		RepositoryDescription: aws.String(d.Get("description").(string)),
	}
```
RepositoryDescription: aws.String(d.Get("description").(string)),

**Comment by stack72** [comment]
and is this in the schema?

**Comment by optimisticanshul** [comment]
```
resource "aws_sns_topic" "sns" {
  name = "user-updates-topic"
}

resource "aws_codecommit_repository" "repo" {
  repository_name = "TestRepository"
  description = "This is the Sample App Repository"
}

resource "aws_codecommit_trigger" "trigger" {
  depends_on = ["aws_codecommit_repository.repo"]
  repository_name = "TestRepository"
  trigger {
   name = "test"
   branches = ["All Branches"]
   events = ["all"]
   destination_arn = "${aws_sns_topic.sns.id}"
 }
}
```

```

			"description": &schema.Schema{
				Type:     schema.TypeString,
				Optional: true,
				ValidateFunc: func(v interface{}, k string) (ws []string, errors []error) {
					value := v.(string)
					if len(value) > 1000 {
						errors = append(errors, fmt.Errorf(
							"%q cannot be longer than 1000 characters", k))
					}
					return
				},
			},
```

But repo is created but while creating trigger it crashes.

**Pull request closed without merging**
