### PR TITLE
Added join_domain feature to Azure Instance resource

### PR DESCRIPTION
**Pull request by davemcdermid**
Added support for joining Azure Windows instances to a domain

### CODE REVIEW

**Comment by svanharmelen** [comment]
@davemcdermid thanks! One small thing... Would you be able to add some code in the `resourceAzureInstanceRead` function to read this info back and update the state accordingly? That would help to make sure the deployed instance is still in the desired state.

Guess reading back the domain name and maybe (if possible) the OU would be enough for this one...

**Comment by davemcdermid** [comment]
Great idea, will get on that today. Thanks

**Comment by davemcdermid** [comment]
I've done some digging, and can't find a way to achieve this currently via the Azure API. I've raised a feature request here: http://feedback.azure.com/forums/34192--general-feedback/suggestions/9462615-provide-windows-domain-ou-in-get-role-api

**Comment by svanharmelen** [comment]
Ok... Don't think we should wait until the Azure SDK is updated for this. So I'll go ahead and merge this one in right now. If at a later point in time the SDK provides more feedback, we should update the code here as well...

**Comment by davemcdermid** [comment]
I've updated the docs as requested, apologies for missing this before.

Thanks

**Comment by svanharmelen** [comment]
@davemcdermid thanks! LGTM!

**Pull request merged**
