### PR TITLE
update prevent_destroy error message

### LINKED ISSUE #2473: Clarify wording when lifecycle.prevent_destroy is set and `terraform destroy` is run
When running `terraform destroy` and a resource has `lifecycle.prevent_destroy` set to true, we're encouraged to `either disable prevent_destroy, or change your config so the plan does not destroy this resource` which is set in [terraform/eval_check_prevent_destroy.go](https://github.com/hashicorp/terraform/blob/master/terraform/eval_check_prevent_destroy.go#L32).

Would it be possible to clarify the latter portion a bit more? Not really sure what I could change in this context!

### PR DESCRIPTION
**Pull request by phinze**
per recommendations by @nathanielks

closes #2473

### CODE REVIEW

**Comment by apparentlymart** [comment]
I like the new error message... much clearer!

The test for this feature is depending on part of this error message, though: https://github.com/hashicorp/terraform/blob/88dcb24c91c3274ea04758d5240393cc5c85d470/terraform/context_plan_test.go#L607

**Comment by nathanielks** [comment]
Big fan, @phinze! This reads much better. :clap: :clap: :clap: :clap: :clap:

**Comment by nathanielks** [comment]
I also completely forgot I wrote that...

giphy

**Comment by nathanielks** [comment]
¯\_(ツ)_/¯

**Comment by phinze** [comment]
Hm travis does not seem to be picking up the proper diff for the build - verified manually and hopefully the build sorts itself out post-merge

Also lol @nathanielks - good to know that past you and current you agree that it's an improvement. :stuck_out_tongue:

**Pull request merged**
