### PR TITLE
provider/vsphere: fix gateway settings in dhcp tests 

### PR DESCRIPTION
**Pull request by thetuxkeeper**
Fix for DHCP tests after merging #6522.
cc @chrislovecnm , @jen20

### CODE REVIEW

**Comment by stack72** [comment]
LGTM! pending travisci

**Comment by thetuxkeeper** [comment]
@stack72: Wow, that was a fast response :D 
Btw. Is it really the right way to set it only as `Computed`? I mean if you set this setting (not computed) it won't be updated. But `ForceNew` is somehow also wrong since it would redeploy if you change the DHCP gateway not set by terraform.

**Comment by stack72** [comment]
if it can be set by the user and can also be computed then computed and optional is correct

**Comment by thetuxkeeper** [comment]
Ok, thanks. Then we would have to implement the update logic that it works like a user would expect. But that's already on the roadmap.

**Comment by stack72** [comment]
@thetuxkeeper for now, until we get the update logic in place, should these be `Optional`, `Computed` (to fix the bug) and `ForceNew`?

**Comment by thetuxkeeper** [comment]
With `ForceNew`, would it recreate the VM if you use DHCP (`*_gateway` not set and computed) and change the gateway with DHCP?
If it's like that we have two choices while the update logic is not there yet:
1. unnecessary recreation when changing the gateway over DHCP (`ForceNew`)
2. or not applying the setting if you set it in the config

But I think an unnecessary recreation is better than not applying changed. But I'm not sure.

If we change it for the gateway settings to `ForceNew`+`Computed`, should we change it for the other network settings? The IP address settings should have the same behavior since only `Computed` is set

**Comment by stack72** [comment]
Got it - let's (IMO) go with the least dangerous one - the not updating (as you have it) and then revisit the update later

**Comment by thetuxkeeper** [comment]
Ok. Then I know how to set it if something like that appears somewhere else.
Thanks for merging :)

**Pull request merged**
