### PR TITLE
Fix up deps

### PR DESCRIPTION
**Pull request by freeformz**
Done with:

```console
$ godep restore -v
$ rm -rf Godep vendor/
$ godep save ./...
```

Spot checked, but things look legit. I don't (yet) know how to build
terraform though.

See also tools/godep#415 and tools/godep#416

### CODE REVIEW

**Comment by phinze** [comment]
Oh hey thanks @freeformz! Reviewing now.

**Comment by phinze** [comment]
Hm looks like everything builds but google - looking into it.

**Comment by freeformz** [comment]
@phinze `godep update google.golang.org/api/...` committed seems to have fixed the problem. I assume someone was using a more recent local copy of `google.golang.org/api/storage/v1`

**Comment by jen20** [comment]
That may have been me, sorry...

**Comment by jen20** [comment]
This LGTM though now the build is green.

**Comment by freeformz** [comment]
We can (or at least should) be able to remove a bunch of the `go list | grep` stuff in the Makefiles. Should add another commit to clean those up?

**Comment by jen20** [comment]
Does that depend on having a specific version of Godep? If so we might want to test for that in the Makefile also

**Comment by freeformz** [comment]
@jen20 yes >= v54 I'd be happy to add a check as well.

**Comment by phinze** [comment]
Cool - I had reached the same update-google conclusion locally. Will await the Makefile tweaks and merge.

I have a WIP here that adds dependency mgmt docs and moves us to just require Go1.6 so we can drop the env vars everywhere. I'll rebase that and get it pushed up after this lands.

**Comment by phinze** [comment]
Actually just going to merge this as-is and we can circle back w/ Makefile improvements.

Thanks so much for your help on this, @freeformz! :heart_decoration:

**Comment by freeformz** [comment]
@phinze Sorry it was so much of a pita in the first place.

**Pull request merged**
