### PR TITLE
aws_emr_cluster: Fix bootstrap action parameter ordering

### PR DESCRIPTION
**Pull request by ddcprg**
This fixes issue https://github.com/hashicorp/terraform/issues/10691

### CODE REVIEW

**Comment by stack72** [comment]
Hi @ddcprg 

Thanks for the work here - 2 questions:

1. Do you think that people who currently have an emr_cluster will see an adverse change from this change?
2. Please can you add an acceptance test to show that the ordering is preserved?

Thanks

Paul

**Comment by catsby** [comment]
Hey – I'm not sure this is needed, I posted a comment on https://github.com/hashicorp/terraform/issues/10691 please take a look !

**Comment by ddcprg** [comment]
Hi @stack72 I'm waiting to hear back from @catsby on the reported issue. Once I have confirmation that this requires fixing I'll try to write the acceptance test.

Cheers

**Comment by stack72** [comment]
@ddcprg 👍 I will leave this one to you and @catsby :)

**Comment by lattwood** [comment]
@ddcprg this does require fixing.

**Comment by catsby** [comment]
Hey all – I've continued this work in #13580 by adding a thing or two. Thanks!

**Pull request closed without merging**
