### PR TITLE
initial commit for Cobbler provider

### PR DESCRIPTION
**Pull request by thijsschnitger**
This is an initial commit to get the provider we wrote for Cobbler merged as a builtin into Terraform core, as per https://github.com/ContainerSolutions/terraform-provider-cobbler/issues/1. 
I only included the .go files and left out documentation and example config because I thought you might want them elsewhere. Please let us know how to proceed.

### CODE REVIEW

**Comment by jtopjian** [comment]
Very cool! I actually had this on my list of things to look at building. We use Cobbler heavily as our bare metal management utility.

I have a script to build out a simple, disposable Cobbler environment -- I was going to use it as the basis for provider acceptance tests. I'll dig it up, clean it up, and see if I can get this integrated.

(The acceptance tests wouldn't actually verify a provisioned bare metal server, but it can verify that a distro, profile, and system were correctly managed)

**Comment by thijsschnitger** [comment]
We built a Docker image for Cobbler which might be handy in this case. It's currently private but if you're interested we could make it public, it would need some sanatizing but it shouldn't be that much work.

**Comment by jtopjian** [comment]
Just wanted to touch base about this. I'm very sorry for the lack of communication -- I haven't had as much time as I'd like to work on Terraform.

I've been playing with this PR and cleaning up the code. I've started to do a refactor of the `cobblerclient` in order to handle GET/read requests. It's quite messy at the moment. Once I clean it up, I'll push it to github so you can see the changes. :)

**Comment by thijsschnitger** [comment]
Thanks for the heads up. If we can do anything in the mean time to speed up the process, please let us know!

**Comment by phinze** [comment]
Hi @jtopjian - would love to get Cobbler support landed in Terraform core soon. :grinning: 

Were you ever able to push the changes you referenced?

**Comment by jtopjian** [comment]
I've got a patch in queue for the cobblerclient library. I need a couple hours to finish it up, `$work` has been keeping me away from it, but I'll try to get it done soonish.

**Comment by phinze** [comment]
The Cobbler provider has landed via #5969 - thanks for getting things kicked off @thijsschnitger! :+1:

**Pull request closed without merging**
