### PR TITLE
Update CHANGELOG

### PR DESCRIPTION
**Pull request by svanharmelen**
The SSH agent thing applies to all provisioners using the `ssh` connection type, so it would be misleading to write it's only related to the `remote-exec` provisioner.

### CODE REVIEW

**Comment by phinze** [comment]
I actually had `communicator/ssh` written first! :grinning: 

But then I realized that it's not a user-facing concept, which is why I switched it.

What about something like "`provisioner/remote-exec` (ssh connection types only)"?

**Comment by svanharmelen** [comment]
Hmm... No, because this is also true for `provisioner/chef` and `provisioner/file`... At least when they use the `ssh` connection type.

So then maybe `ssh connection type` or `ssh connections`?

**Comment by phinze** [comment]
Oh whoops! Good call. `connection/ssh` works for me :+1:

**Comment by svanharmelen** [comment]
Cool... And of course it's just a small nit, but it will maybe prevent some additional questions/issues later on :wink:

**Pull request merged**
