### PR TITLE
provider/openstack: Multi Ephemeral Disk Support

### LINKED ISSUE #4042: Adding multiple Ephemeral Volumes to Compute Instance on OpenStack
Hi guys,

is there a way to add multiple ephemeral volumes to a given instance?

```
nova boot <vm-name> --image <image-id> --flavor <flaovr-id> \ 
--nic net-id=<net-id> --availability-zone <availability-zone-name> \
--ephemeral size=<size>,format=<format_type> \
--ephemeral size=<size>,format=<format_type> \
... and so on
```

Of course your flavor has to have a big enough ephemeral size configured.

http://docs.openstack.org/cli-reference/content/novaclient_commands.html#novaclient_subcommand_boot

Regards,
Andreas

### LINKED ISSUE #5098: InvalidBDM from nova-api with block device mapping.
When provisioning an instance with a block device in openstack you will recieve a InvalidBDM error if you do not specify volume_size.

Example:    
block_device = {
      uuid = "39807484-2edb-4aae-9fe4-1a878482f16e"
      source_type = "image"
      destination_type = "volume"
}

If you add volume_size it works
Example
block_device = {
      uuid = "39807484-2edb-4aae-9fe4-1a878482f16e"
      source_type = "image"
      volume_size = "50"
      destination_type = "volume"
}

In the code it would be good to query the volume_size from flavor if not se.

### PR DESCRIPTION
**Pull request by jtopjian**
This commit adds the ability to create instances with multiple ephemeral (local) disks.

Fixes #4042
Fixes #5098

### CODE REVIEW

**Comment by afritzler** [comment]
@jtopjian I tested the RP on our OpenStack and it is looking good. I managed to split up a 4TB ephemeral disk into 4 single block devices.

One note though regarding the boot device: 
```
    block_device {
      boot_index = 0
      delete_on_termination = true
      destination_type = "local"
      source_type = "image"
      uuid = "<image uuid>"
    }
```
Did I get it correct, that the block device (index=0) is mandatory? Because I could not create an instance without it. Also, it would be great to use the `image_name` instead of the `uuid`.

**Comment by jtopjian** [comment]
@afritzler Yes, I think `boot_index = 0` is required. Good point about `image_name` instead of `uuid`. I think I'll work in getting this PR merged and then work on `image_name` as an enhancement.

**Comment by afritzler** [comment]
Btw. one more thing regarding `guest_format = "ext4"`: is this flag actually doing something? I ended up with an unformatted vanilla disk.

**Comment by jtopjian** [comment]
@afritzler To be honest, I'm not sure. I'd have to dig into the actual Nova API code to look. However, `guest_format` is being passed to the Nova API when `nova boot` is run on the command line (Check the nodes from #4042), so it might be a good idea to include it from the very start.

**Pull request merged**
