### PR TITLE
add setsubtract function and docs

### PR DESCRIPTION
**Pull request by jamesgoodhouse**
This addresses https://github.com/hashicorp/terraform/issues/20683. Related to https://github.com/hashicorp/terraform/pull/21956

### CODE REVIEW

**Comment by jamesgoodhouse** [comment]
@apparentlymart you've been involved in some other issues related to this, so I thought I'd pull you in here.

**Comment by jamesgoodhouse** [comment]
Tests for go-cty library for `SetSubtractFunc` function have been added in PR https://github.com/zclconf/go-cty/pull/30

**Comment by jamesgoodhouse** [comment]
Opened a PR in the SDK core repo (https://github.com/hashicorp/terraform-plugin-sdk/pull/310)

**Comment by jamesgoodhouse** [comment]
What are the next steps in getting this merged into master? I'm willing to help where I can to make changes or update docs, but it's becoming a blocker unfortunately not having access to all of the basic set functions. CC @cgriggs01 and @jbardin since you two have most recently merged into the project.

**Comment by paultyng** [comment]
For anyone waiting on the PR I believe you can workaround this with something like:

```
toset([for x in var.a : x if ! contains(var.b, x)])
```

**Comment by mildwonkey** [comment]
Thank you for submitting this PR @jamesgoodhouse , and I apologize for the long silence. This looks great and plenty of folks will be happy it's been added.

**Pull request merged**
