### PR TITLE
Bumped the Terraform provider AWS vendoring

### PR DESCRIPTION
**Pull request by Ninir**
Since the merge of https://github.com/terraform-providers/terraform-provider-aws/pull/1608, AWS is now able to assume role from a given profile defined in `~/.aws/credentials`, as in:

```
 [myprofile]
 aws_access_key_id=<redacted>
 aws_secret_access_key=<redacted>
 
 [myextendedprofile]
 role_arn = arn:aws:iam::0123445678901:role/myrole
 source_profile = myprofile
 region = eu-west-1
```

This bumps the `terraform-provider-aws` dependency so that everything relying on AWS (e.g. S3 backend) also reads it properly. 
It also updates the AWS Go SDK to 1.12.27 in order to match the related dependencies from `terraform-provider-aws` 

Used commands:
* `govendor fetch github.com/terraform-providers/terraform-provider-aws/aws`
* `govendor fetch github.com/aws/aws-sdk-go/...@=v1.12.27 `

As a sidenote, should I also send a similar PR to https://github.com/terraform-providers/terraform-provider-terraform waiting for 0.11 to be released?

### CODE REVIEW

**Comment by Ninir** [comment]
Regarding the build error, I think we also need to bump AWS SDK Go dependencies there... what do you think?

**Comment by svenwltr** [comment]
I am not able to build this. This might be a mistake on my side, but the current master works for me.

```
$ go version
go version go1.9.2 linux/amd64
```

I am sorry, if this is unrelated.

---

**this PR**
```
$ git rev-parse HEAD
6d587f8e288122d17a5dbbcf5b5e38a3c1b8f481
```
 
```
$ git status
On branch f-vendoring-terraformaws
Your branch is up-to-date with 'Ninir/f-vendoring-terraformaws'.
nothing to commit, working tree clean
```

```
$ make dev
==> Checking that code complies with gofmt requirements...
go generate ./...
2017/11/16 21:22:44 Generated command/internal_plugin_list.go
stringer: checking package: decoder_spec.go:4:2: could not import github.com/hashicorp/hcl2/hcldec (can't find import: github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcldec)
config/configschema/schema.go:80: running "stringer": exit status 1
stringer: checking package: diagnostics.go:4:2: could not import bytes (reading export data: /home/sven/Data/Applications/golang/pkg/linux_amd64/bytes.a: invalid encoding format in export data: got 'v'; want 'c' or 'd')
tfdiags/diagnostic.go:11: running "stringer": exit status 1
make: *** [Makefile:86: generate] Error 1
```

```
$ git status
On branch f-vendoring-terraformaws
Your branch is up-to-date with 'Ninir/f-vendoring-terraformaws'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   command/internal_plugin_list.go

no changes added to commit (use "git add" and/or "git commit -a")
```

```
$ git diff
diff --git a/command/internal_plugin_list.go b/command/internal_plugin_list.go
index 6834bf5f7..88bd89d42 100644
--- a/command/internal_plugin_list.go
+++ b/command/internal_plugin_list.go
@@ -16,9 +16,10 @@ import (
 var InternalProviders = map[string]plugin.ProviderFunc{}
 
 var InternalProvisioners = map[string]plugin.ProvisionerFunc{
-       "chef":            chefprovisioner.Provisioner,
-       "file":            fileprovisioner.Provisioner,
-       "local-exec":      localexecprovisioner.Provisioner,
-       "remote-exec":     remoteexecprovisioner.Provisioner,
-       "salt-masterless": saltmasterlessprovisioner.Provisioner,
+       "chef":   chefprovisioner.Provisioner,
+       "file":   fileprovisioner.Provisioner,
+       "local-exec":   localexecprovisioner.Provisioner,
+       "remote-exec":   remoteexecprovisioner.Provisioner,
+       "salt-masterless":   saltmasterlessprovisioner.Provisioner,
+
```

---

**master**

```
$ git rev-parse HEAD 
adb6a089ff0e5c0dd487fda6c96ad3f264c35742
```

```
$ git status -v
On branch master
nothing to commit, working tree clean
```

```
$ make dev
==> Checking that code complies with gofmt requirements...
go generate ./...
2017/11/16 21:18:43 Generated command/internal_plugin_list.go
==> Removing old directory...
==> Building...
Number of parallel builds: 3

-->     linux/amd64: github.com/hashicorp/terraform

==> Results:
total 90M
-rwxrwxr-x 1 sven sven 90M Nov 16 21:19 terraform

```

**Comment by mikemoate** [comment]
@Ninir @apparentlymart Terraform 0.11.0 has been released for some time now, in fact I see 0.11.1 has been released more recently, yet this PR still hasn't been merged.

Can we get this released ASAP? I'd really like to not have to keep building a custom fork of Terraform ;-)

(without this change profiles can't be used for accessing S3 based remote state)

**Comment by apparentlymart** [comment]
We waited until the 0.11.1 release before making most changes because we wanted to leave things clear for any urgent bugfixes we might need to release, but we're now back to normal merging. Thanks again for submitting this, @Ninir!

**Pull request merged**
