### PR TITLE
Cloud: Migrate empty default workspace prompt

### PR DESCRIPTION
**Pull request by barrettclark**
Given: You have multiple explicit local workspaces, and the `default`
workspace is empty.

When: You migrate the workspaces to Terraform Cloud.

Then: Terraform should _not_ ask for a workspace to migrate the
`default` workspace to in Terraform Cloud.

### CODE REVIEW

**Review by chrisarcand — COMMENTED** [review]
Haven't given it a test drive, but my assessment of the code matches Alisdair's

**Comment by alisdair** [comment]
Sorry, still not following. Here's the following block I'm referring to: https://github.com/hashicorp/terraform/blob/362a5ffd205373d402356834dfbed5773e741bc4/internal/command/meta_backend_migrate.go#L651-L670

Where does this code prevent us from migrating an empty default workspace? All I can see is that we conditionally _rename_ the default workspace—and this PR is only changing the storing of the rename.

Again, I haven't tested this, so it may well be that I'm misreading. If that's the case I think we should try to either clarify the code or add comments to explain what's happening for future readers.

**Comment by alisdair** [comment]
Somewhat answering my own question: we eventually call into the `s_s` migration path, which has this code preventing migration with empty state: https://github.com/hashicorp/terraform/blob/362a5ffd205373d402356834dfbed5773e741bc4/internal/command/meta_backend_migrate.go#L268-L272

So, this seems like a good fix to me, but I would stand by my prior confused self as being reasonably confused. I think the issue is that this conditional on empty state exists in two places at quite a distance from each other. If there's any way you could make that clearer, I think that would be helpful.

**Review by alisdair — APPROVED** [review]

**Comment by barrettclark** [comment]
Ah - yes. The focus of the fix here was to prevent the user being prompted to rename the `default` workspace when it is empty and would then be thrown away later in the migration process. I will add a comment to make it more clear what this block is doing and why.

**Review by alisdair — APPROVED** [review]
E2E test and comment update are both great! 🎉

**Pull request merged**
