### PR TITLE
2544 terraform s3 policy

### PR DESCRIPTION
**Pull request by m-s-austin**
This code adds a new provider to terraform that allows you to add a Policy to an s3 bucket like this:

```javascript
resource "aws_s3_bucket_policy" "test_policy" {
    name = "Bucket Test Policy"
    bucket = "${aws_s3_bucket.b.id}"
    policy = <<EOF
{
  "Id": "Policy1431447664360",
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Stmt1431447659873",
      "Action": [
        "s3:GetObject"
      ],
      "Effect": "Allow",
      "Resource": "arn:aws:s3:::my_tf_test_bucket/*",
      "Principal": "*"
    }
  ]
}
EOF
}
```

(original issue now closed)
https://github.com/hashicorp/terraform/issues/1150

https://github.com/hashicorp/terraform/issues/28

### CODE REVIEW

**Comment by justincampbell** [comment]
@m-s-austin I have a branch in progress that adds this as an argument to `aws_s3_bucket` instead of a separate resource.

https://github.com/hashicorp/terraform/compare/master...justincampbell:s3-policy

The API would look like (using the `template_file` resource):

```c
variable "bucket" { default = "justincampbell.me" }

resource "aws_s3_bucket" "default" {
  bucket = "${var.bucket}"
  acl = "public-read"
  policy = "${template_file.policy.rendered}"

  website {
    index_document = "index.html"
  }
}

resource "template_file" "policy" {
  filename = "policy.json"

  vars {
    bucket = "${var.bucket}"
  }
}
```

What do you think?

**Comment by mitchellh** [comment]
@justincampbell Can you only have one policy attached? If you can only have one, I think your way is preferred.

**Comment by m-s-austin** [comment]
@justincampbell @mitchellh Either way is fine with me, I was going by what seemed to be an existing pattern with other aws services.

**Comment by justincampbell** [comment]
Yes, only one policy is supported per bucket. Opened #1992

**Comment by radeksimko** [comment]
Thanks @m-s-austin for the work here, but I'm closing this in favour of #1992 -> feel free to chime in with feedback.

**Pull request closed without merging**
