### PR TITLE
provider/aws: Add resource for an ELB SSL negotiation policy

### PR DESCRIPTION
**Pull request by bigkraig**
This is basically a dupe of #5637 but @fpmosley didn't have the bandwidth to rebase.

### CODE REVIEW

**Comment by stack72** [comment]
Fixes #2171 / Fixes #3176

**Comment by stack72** [comment]
Hey @bigkraig 

Thanks so much for the rebase here - the test doesn't work I'm afraid :(

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSLBSSLNegotiationPolicy'
==> Checking that code complies with gofmt requirements...
/Users/stacko/Code/go/bin/stringer
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/08/10 11:58:56 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSLBSSLNegotiationPolicy -timeout 120m
=== RUN   TestAccAWSLBSSLNegotiationPolicy_basic
--- FAIL: TestAccAWSLBSSLNegotiationPolicy_basic (12.81s)
	testing.go:264: Step 0 error: Error applying: 1 error(s) occurred:

		* aws_iam_server_certificate.test_cert: [WARN] Error uploading server certificate, error: MalformedCertificate: Certificate is no longer valid. The 'Not After' date restriction on the certificate has passed.
FAIL
exit status 1
FAIL	github.com/hashicorp/terraform/builtin/providers/aws	12.832s
make: *** [testacc] Error 1
```

Any chance you could have a look?

P.

**Comment by xsmaster** [comment]
Seems it might be just bad test data.

**Comment by fpmosley** [comment]
@bigkraig @stack72 The Acceptance Test fails because it is using an expired certificate that was lifted from:
   builtin/providers/aws/resource_aws_iam_server_certificate_test.go

The certs were fixed in this commit:
https://github.com/hashicorp/terraform/commit/005d9a12e0367c5d22ff1b1bb7776f89e61bf93e

Just take the certs from there and it should work.

**Comment by bigkraig** [comment]
@stack72 I've updated the test data and it looks good

```
Kraigs-MacBook-Pro:terraform kamador$ make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSLBSSLNegotiationPolicy'
==> Checking that code complies with gofmt requirements...
/Users/kamador/gocode/bin/stringer
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/08/10 13:30:32 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSLBSSLNegotiationPolicy -timeout 120m
=== RUN   TestAccAWSLBSSLNegotiationPolicy_basic
--- PASS: TestAccAWSLBSSLNegotiationPolicy_basic (27.99s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	28.009s
```

**Comment by fpmosley** [comment]
@bigkraig Looks like you were already on top of it fixing it. Great!

**Comment by stack72** [comment]
@bigkraig this looks good to me now :) Thanks so much!

**Comment by gokul-p** [comment]
This fix will be included in next release ? whats plan for next release ?

**Comment by stack72** [comment]
Hi @gokul-p 

yes this will be included for 0.7.1 - there is no formal release date yet

Paul

**Comment by gokul-p** [comment]
thanks @stack72 - Please update me,once you have the date.

**Comment by 41jules1967** [comment]
This seems to be in place but I can't tell if it's working.
The console screens make to reference to the new policy and imply the ELB is using the default policy. 
Is it actually working?

**Pull request merged**
