### PR TITLE
Remove use of retracted k8s client-go lib

### PR DESCRIPTION
**Pull request by jaredledvina**
`k8s.io/client-go v10.0.0+incompatible` is a retracted version of client-go library as a result of https://github.com/kubernetes/kubernetes/issues/98267. This PR is an attempt to remove the usage of it from the Terraform project.

### CODE REVIEW

**Comment by jrhouston** [comment]
Just tried to build this branch and it looks like the k8s backend code will need to be updated to support contexts:

```
backend/remote-state/kubernetes/backend_state.go:23:35: not enough arguments in call to secretClient.List
	have ("k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions)
	want (context.Context, "k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions)
backend/remote-state/kubernetes/client.go:49:45: not enough arguments in call to c.kubernetesSecretClient.Get
	have (string, "k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions)
	want (context.Context, string, "k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions, ...string)
backend/remote-state/kubernetes/client.go:108:48: not enough arguments in call to c.kubernetesSecretClient.Create
	have (*unstructured.Unstructured, "k8s.io/apimachinery/pkg/apis/meta/v1".CreateOptions)
	want (context.Context, *unstructured.Unstructured, "k8s.io/apimachinery/pkg/apis/meta/v1".CreateOptions, ...string)
backend/remote-state/kubernetes/client.go:115:42: not enough arguments in call to c.kubernetesSecretClient.Update
	have (*unstructured.Unstructured, "k8s.io/apimachinery/pkg/apis/meta/v1".UpdateOptions)
	want (context.Context, *unstructured.Unstructured, "k8s.io/apimachinery/pkg/apis/meta/v1".UpdateOptions, ...string)
backend/remote-state/kubernetes/client.go:173:42: not enough arguments in call to c.kubernetesLeaseClient.Create
	have (*"k8s.io/api/coordination/v1".Lease)
	want (context.Context, *"k8s.io/api/coordination/v1".Lease, "k8s.io/apimachinery/pkg/apis/meta/v1".CreateOptions)
backend/remote-state/kubernetes/client.go:237:41: not enough arguments in call to c.kubernetesLeaseClient.Update
	have (*"k8s.io/api/coordination/v1".Lease)
	want (context.Context, *"k8s.io/api/coordination/v1".Lease, "k8s.io/apimachinery/pkg/apis/meta/v1".UpdateOptions)
backend/remote-state/kubernetes/client.go:279:37: not enough arguments in call to c.kubernetesSecretClient.Get
	have (string, "k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions)
	want (context.Context, string, "k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions, ...string)
backend/remote-state/kubernetes/client.go:283:36: not enough arguments in call to c.kubernetesLeaseClient.Get
	have (string, "k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions)
	want (context.Context, string, "k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions)
backend/remote-state/kubernetes/client.go:300:40: not enough arguments in call to c.kubernetesSecretClient.Delete
	have (string, *"k8s.io/apimachinery/pkg/apis/meta/v1".DeleteOptions)
	want (context.Context, string, "k8s.io/apimachinery/pkg/apis/meta/v1".DeleteOptions, ...string)
backend/remote-state/kubernetes/client.go:317:39: not enough arguments in call to c.kubernetesLeaseClient.Delete
	have (string, *"k8s.io/apimachinery/pkg/apis/meta/v1".DeleteOptions)
	want (context.Context, string, "k8s.io/apimachinery/pkg/apis/meta/v1".DeleteOptions)
backend/remote-state/kubernetes/client.go:317:39: too many errors
```

**Comment by jbardin** [comment]
Thanks for checking that @jrhouston! I've had a feeling we could get rid of the last two `replace` exceptions, but it looks like that's going to take a bit more work than updating go.mod.

**Comment by jaredledvina** [comment]
Yes, thanks @jrhouston  and @jbardin for checking this out! I pushed my attempt to setup context's. I'm not entirely familiar with the code base though so, it is just an initial attempt.

**Comment by jaredledvina** [comment]
Just wanted to mention that I've fixed up the merge conflicts on this & and signed the CLA. @jrhouston let me know if you need anything else from my side, happy to help!

**Comment by jbardin** [comment]
rebased in #29953

**Comment by jaredledvina** [comment]
Nice, thanks!

**Pull request closed without merging**
