### PR TITLE
provider/aws: aws autoscale schedule 0 values

### PR DESCRIPTION
**Pull request by stack72**
As per #4690 

Added a test to prove that 0 values cannot be specified for the Autoscale Group Schedule resource for min_size, max_size or desirect_capacity even though they are valid values

This shouldn't really be merged until a fix is added for this

### CODE REVIEW

**Comment by catsby** [comment]
I opened https://github.com/stack72/terraform/pull/1 to make these fields optional. It's a simple/naive fix... I don't see what the problem would be if the API allows this. Thoughts? What am I missing?

**Comment by catsby** [comment]
cc @jen20 or @phinze for sanity check, since I contributed here

**Comment by stack72** [comment]
@catsby I think this is fine with me. I am going to up date the documentation to point out that these values will default to 0

**Comment by stack72** [comment]
@catsby I have tested this and it all looks good now since your changes :)

IMO I think putting 0 as the default is ok - we would need to put it in the release notes that it's not a backwards compatible change

```
make testacc TEST=./builtin/providers/aws TESTARGS='-run=AWSAutoscalingSchedule_zero' 2>~/tf.log
==> Checking that code complies with gofmt requirements...
go generate ./...
TF_ACC=1 go test ./builtin/providers/aws -v -run=AWSAutoscalingSchedule_zero -timeout 120m
=== RUN   TestAccAWSAutoscalingSchedule_zeroValues
--- PASS: TestAccAWSAutoscalingSchedule_zeroValues (168.52s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	168.536s
```

I think we can merge this :)

**Comment by jen20** [comment]
LGTM with test coverage.

**Pull request merged**
