### PR TITLE
Allow variables to hold arrays of strings

### PR DESCRIPTION
**Pull request by jamesob**
refs https://github.com/hashicorp/terraform/issues/57

This is a rough first draft. Acceptance tests haven't been run.

Some guidance from more experienced contributors would be appreciated regarding:
- where to add integration tests that show variables with defaults of type string-list being used, e.g. something like
```
variable "default_security_groups" {
  default = ["sg1", "sg2"]
}

resource "aws_instance" "yo" {
  ...
  security_groups = "${var.default_security_groups}"
}
```
- if my proposed return value for `DefaultsMap` is correct, and will be interpreted correctly as a list of strings.

### CODE REVIEW

**Comment by zmt** [comment]
+1 to the need for this or something like it - don't know golang so can't comment on code quality

**Comment by ajvb** [comment]
:+1:

**Comment by joelhandwell** [comment]
@catsby @radeksimko @mitchellh what should be done as the next step for this PR to be merged?

**Comment by Deserved** [comment]
+1

**Comment by little-arhat** [comment]
Any updates on this?

**Comment by sethlindberg** [comment]
Also want to know if there are updates.  Delayed by the holidays? Working on a configuration problem this would fix.

**Comment by josephholsten** [comment]
What this implementation doesn't have is a way to set these arrays of strings from a `terraform.tfvars` file or environment variables. I can at least imagine a way to do it with command line flags, say ` --var 'foo = ["bar", "quux"]'`.

**Comment by stack72** [comment]
I *think* this may be redundant with the latest PR for supporting lists by @jen20 https://github.com/hashicorp/terraform/pull/5936

**Comment by apparentlymart** [comment]
Thanks for the work on this @jamesob, and sorry that it sat here for over a year. :disappointed: 

As noted above, @jen20 has been working on an implementation of this same idea in #5926 and it's coming in Terraform 0.7, so I'm going to close this.

**Pull request closed without merging**
