### PR TITLE
Fix route53 set_identifier logic

### LINKED ISSUE #5776: aws_route53_record does not enforce having set_identifier when weight is set
Just spent a while debugging an issue where we had some aws_route53_record resources in our terraform code where the plan went through OK, but the apply got a 400 error from the AWS API. It took a while to find that the issue was because the 'weight' attribute was set on the resource (to 0, in this case), but no set_identifier. I notice that the docs say that set_identifier is required (https://www.terraform.io/docs/providers/aws/r/route53_record.html#set_identifier) but terraform's own logic doesn't seem to enforce this, causing the confusing 400 error from the AWS API during the apply.

### PR DESCRIPTION
**Pull request by edmundcraske**
Resolves #5776

### CODE REVIEW

**Comment by phinze** [comment]
Hi @edmundcraske - thanks for this! Do you think we should cover `"failover"` here as well so we're matching the docs?

**Comment by edmundcraske** [comment]
Probably, yeah - can't say that I looked at that bit!

**Comment by edmundcraske** [comment]
Updated title as this is no longer just about weight. This means the logic now tallies with the documentation and with the AWS API documentation also.

**Comment by phinze** [comment]
LGTM - thanks @edmundcraske!

**Pull request merged**
