### PR TITLE
provider/azure: Fixes for #3568 and #3428

### PR DESCRIPTION
**Pull request by kbxkb**
Hi Terraform Developers,

These two bugs in Terraform Azure provider severely limits its usage with Azure, because they prevent the deployment of any practical multi-VM environment sitting behind a cloud service, and also using VM-s with additional data disks in such a scenario, both of them pretty basic needs: 
1. https://github.com/hashicorp/terraform/issues/3568
2. https://github.com/hashicorp/terraform/issues/3428

I have fixed these two bugs and thoroughly tested them. They needed a couple of changes in the underlying azure-sdk-for-go. These changes have now been accepted and merged, the latest pull request to get merged to the azure-sdk-for-go repo being this: https://github.com/Azure/azure-sdk-for-go/pull/238

Therefore, the master on azure-sdk-for-go is now ready for these fixes. I request you to take a look at them, review thoroughly, and let me know if they look good. If they do, please accept and merge.

The fixes do not touch a lot of files. They also respect the previous changes put in for "has_dedicated_service". I have tested these scenarios. Thanks!

### CODE REVIEW

**Comment by jen20** [comment]
Hi @kbxkb - thanks for opening this. At the moment I'm reviewing support for the Azure ARM API in preference to the service management API - once I'm done with that I'll go through all other PRs in light of the new bits. I'll make an update on this ticket when that's happened.

**Comment by kbxkb** [comment]
@jen20 thanks! Great that you bring it up, as I was in conversation with some Microsoft groups to help make Terraform ARM-compatible!

These fixes are for service management API ("cloud service" IaaS V1 era), and should be independent of any ARM-upgrade Terraform gets. I expect the ARM-upgrade to take some time. In the meantime, several startups/ ISV-s would want to use Terraform Azure in its service management mode instead of waiting. These fixes would pave the way for Terraform Azure's adoption until the ARM-upgrade comes.

**Comment by jen20** [comment]
Hi @kbxkb! The ARM upgrade is pretty advanced now, though we just decided to change the implementation to bring it in as a new provider instead of attempting to maintain compatibility. I agree the service management API provider shouldn't be affected here though.

**Comment by joaocc** [comment]
Hi. Any news on this merge? Thx

**Comment by andrewduch** [comment]
Hi - also wanted to check on the status of this merge? We're stuck w/ using Service Management for the foreseeable future so would like to see this change make it in. Thanks!

**Comment by bohnjamin** [comment]
+1 on waiting for this merge; thanks for the hard work

**Comment by chan-alex** [comment]
Am waiting for this fix. Just want highlight although Azure ARM is nice and all, ASM is still pretty much in use. There is still a need to support ASM fully for the next few years.

**Comment by apparentlymart** [comment]
Hello @kbxkb, and thanks for working on this!

As part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it. The `azure` provider is not under active development since the development focus has shifted to the `azurerm` provider, so although this change could in theory be re-applied to [the `azure` provider repository](https://github.com/terraform-providers/terraform-provider-azure) it is likely that it would not be merged.

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Pull request closed without merging**
