### PR TITLE
Revert #7464 and allow an empty state

### LINKED ISSUE #7509: Can't initialize a new remote state
x0.7.0-dev eb70dec

PR #7464 broke the initialization of remote state.

### PR DESCRIPTION
**Pull request by jbardin**
Reverted the change that caused 7509, and fix the original panic in the terraform provider itself.

Add another test to cover remote state initialization. 

Fixes #7509

### CODE REVIEW

**Comment by jbardin** [comment]
I'd also like to try and get a unit test in here to verify remote state initialization, since that was completely missed when #7464 was merged.

**Comment by glasser** [comment]
Seeing #7509 here. I'll build with this PR and let you know if this fixes our issue.

**Comment by jbardin** [comment]
@glasser: I'm going to back this out mostly, as I've found other corner cases here. Since I've elbow deep in the remote state code already, what issue are you seeing?

**Comment by glasser** [comment]
Can confirm that with this PR, we aren't seeing #7509 any more.

I don't know what issue #7464 was trying to fix but it definitely stopped us from being able to create new setups with S3 state that doesn't exist yet, with a "no remote state found" error.

**Comment by glasser** [comment]
(ie, if this isn't clear — I like this PR because it makes terraform work again for us, after #7464 broke it)

**Comment by jbardin** [comment]
@glasser Don't worry, this PR is definitely intended to fix that issue. Just pushed a revised patch which should revert to the old behavior entirely, and added another test to keep it stable.

**Comment by glasser** [comment]
Confirm that revised patch works for me too.

**Comment by phinze** [comment]
LGTM

**Pull request merged**
