### PR TITLE
provider/aws: Support suspending auto scaling group processes

### PR DESCRIPTION
**Pull request by tpounds**
Adds support for suspending/resuming auto scaling group processes (e.g. Launch, Terminate, etc.).

see: http://docs.aws.amazon.com/AutoScaling/latest/DeveloperGuide/US_SuspendResume.html

### CODE REVIEW

**Comment by stack72** [comment]
Hi @tpounds,

I think this needs to change slightly, currently (in other resources), when we have an update command after a create command, the create should call the update command (e.g. resource_aws_instance.go)

```
func resourceAwsInstanceCreate(d *schema.ResourceData, meta interface{}) error {
	conn := meta.(*AWSClient).ec2conn

	instanceOpts, err := buildAwsInstanceOpts(d, meta)
	if err != nil {
		return err
	}
        ..........

	// Update if we need to
	return resourceAwsInstanceUpdate(d, meta)
}

func resourceAwsInstanceUpdate(d *schema.ResourceData, meta interface{}) error {
	conn := meta.(*AWSClient).ec2conn

}
```

I think will have to be the pattern in this case as well. 

Thoughts?

Paul

**Comment by tpounds** [comment]
@stack72 I agree creating and then updating is cleaner. I'll ping you once I make the necessary changes to the resource.

**Comment by stack72** [comment]
@tpounds any luck with these updates yet? :)

**Comment by tpounds** [comment]
@stack72 Sorry I haven't provided an update yet. I took a look and updating the create/update code paths like you described requires consolidation of the auto scaling group wait for capacity logic (see: resource_aws_autoscaling_group.go[:225](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_autoscaling_group.go#L225), [:380](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_autoscaling_group.go#L380)). In addition to that change, special care is required to prevent waiting when the Launch or Terminate policies are suspended since you might wait around forever for the capacity to spin up/down. 

My high-level thoughts to fix this are as follow.

1. Consolidate wait for capacity logic (separate pull request)
2. Rebase this pull request on #1 with consideration for Launch/Terminate policies as described above.

Thoughts?

**Comment by tpounds** [comment]
@stack72 I've created #5824 to cleanup the wait for capacity logic. I'll be rebasing this commit on that shortly.

**Comment by tpounds** [comment]
@stack72 Feature should be good to go now. I've rebased this change on #5824 so that should probably be merged first.

**Comment by sj26** [comment]
We've love support for this as well. Any reason this PR stagnated? Can I help get it over the line?

**Comment by stack72** [comment]
Closed via #10096

**Pull request closed without merging**
