### PR TITLE
provider/aws: Supporting New AWS Route53 HealthCheck additions

### PR DESCRIPTION
**Pull request by stack72**
Added:

* [x] measure_latency
* [x] invert_healthcheck
* [x] child_healthchecks
* [x] acceptance tests
* [x] documentation

There were a couple of key changes required here:

1. failure_threshold was changed to optional as it is only required for non Calculated checks
2. request_interval was changed to optional as it is only required for non Calculated checks

### CODE REVIEW

**Comment by radeksimko** [comment]
This is slightly overlapping with https://github.com/hashicorp/terraform/pull/3688

**Comment by stack72** [comment]
@radeksimko what do you need me to do here?

**Comment by radeksimko** [comment]
@stack72 I don't intend to review either of these (at least not in the nearest weeks), so I cannot say, I was merely adding the link so that whoever ends up reviewing & merging this feature is aware of it. :wink:

**Comment by radeksimko** [comment]
Closing this in favour of #4564 as mentioned in that PR.

**Pull request closed without merging**
