### PR TITLE
core: change taint semantics

### PR DESCRIPTION
**Pull request by svanharmelen**
Change tainted resources to act as a normal (first class citizens) resource. This means it’s shown correctly in a plan/diff and takes into account any actions that are dependant on the tainted resource and, vice verse, any actions that the tainted resource depends on.

So this changes the behaviour from saying this resource is tainted so just forget about it and make sure it gets deleted in the background, to saying I want that resource to be recreated (taking into account the
existing resource and it’s place in the graph).

An example of what this fixes is if you taint a resource (say an instance in a network) and then call `terraform destroy`. Before this would not work properly because both the instance and the network would be destroyed in parallel (so no deps taking into account). Now the graph will be correct and so the destroy will succeed properly.

Also it brings a little better UX:

Before:
image

After:
image

This change alters the state file layout, but I don't think a migration is needed. I noticed there is another version of the state being prepared, so I think this change should tag along on that change.

### CODE REVIEW

**Comment by phinze** [comment]
@svanharmelen you are my hero!

Only had time for an initial sweep here, but this is making a lot of sense to me.

I believe this will address #2910 since the regular destroy node handles tainted destroys, and that node is the one that gets shuffled in the CreateBeforeDestroy transformer.

**Comment by svanharmelen** [comment]
@phinze cool 😁 Let me know any comments when you've had a chance to do a full review. Until then, have a good weekend!

**Comment by mitchellh** [comment]
This is interesting. I'll color some history on here too, as well some skepticism and questions. 

**A bit of history...**

The concept of "tainted" has existed since Terraform 0.1. It was originally implemented as you have done here. We ultimately added `Tainted` as a separate slice of instance states to support "create before destroy." This led to all sorts of other pains and bugs, and one of the first things @phinze did as a HC employee years back was introduce the formal concept of "deposed" vs. "tainted" since they are semantically a bit different. 

Which leads us to today: we have both tainted and deposed as slices of instance states. I can no longer think of a reason that there would be more than one tainted but also when @phinze was doing the deposed work we didn't want to do too much madness. 

**And now PR questions...**

My main feedback: I don't see any tests for functionality this fixed/improved, I only see existing tests that are updated to the new API. For this to make sense, I think we need to prove that this fixes prior/other problems without introducing new ones. So, we need at least one new test in `context_apply_test.go`. Without it, the refactor is nice, but uncertain on its utility (and I believe both of you that there is one). 

I'd think very, very hard about whether we can have multiple taints in the current model. I don't think its possible any longer (since even CBD goes to deposed, not tainted).

Further, I question: any graph ordering bugs that exist with tainted probably exist with deposed. Does this cause problems? That shouldn't affect this PR probably but we should think that those bugs probably still exist.

**Comment by apparentlymart** [comment]
The graph ordering issues aside, I've definitely experienced (and seen others on my team experience) the shock and panic of `terraform apply tfplan` saying it's deleting something that was never mentioned in the plan because someone happened to leave something tainted in the state for some reason.

So in terms of user confidence that Terraform is behaving correctly, I personally think it's important that tainting be something that's explicitly included in the plan. I think this applies equally to deposed things that weren't successfully deleted on a previous run, for the same reasons; just last week some operational issues caused us to accumulate a bunch of broken resources in the "deposed" state, and I was only able to explain Terraform's resulting behavior by delving into the state.

I really like the UX change in this PR, where it's explicitly marked as "tainted" in the plan to help the user understand what's going on. How exactly that would be incorporated into the tests I'm not sure. Part of it would be to test that tainted and deposed stuff correctly shows up in the plan, presumably.

**Comment by mitchellh** [comment]
Agreed with @apparentlymart that tainteds need to show up in the plan. :)

**Pull request closed without merging**
