### PR TITLE
provider/ovh: new provider

### PR DESCRIPTION
**Pull request by yanndegat**
new provider targeting the OVH cloud provider.

OVH comes with multiple cloud products: 

- a public cloud based on openstack
- a dedicated private cloud based on vmware.
- bare metal infrastructure

This provider can be "terraformed" through its own API. notably for network resources.

@stack72 : you contacted me a few month ago for this provider.

### CODE REVIEW

**Comment by mcanevet** [comment]
@yanndegat I just played a bit myself with OVH an Terraform and it appears that PublicCloud Network resources are just `openstack_networking_network_v2` but when I try to create a network using this resource I get `{"NeutronError": {"message": "Policy doesn't allow create_network to be performed.", "type": "PolicyNotAuthorized", "detail": ""}}` (I sent an issue to OVH for that) ; but once it's created (using the OVH API) I can import and destroy it using the Openstack provider. For the PublicCloud subnet, I can manage it with `openstack_networking_subnet_v2`.
I think we can workaround the network creation policy limitation by writting a `openstack_networking_network_v2` datasource that would lookup the network created by your PublicCloud network resource by its name so that we can use the network id to create subnet using the regular `openstack_networking_subnet_v2` resource.

**Comment by yanndegat** [comment]
@mcanevet you're completely right and i already submitted the openstack_networking_network_v2 datasource PR. It's been merged last week ;)

**Comment by mcanevet** [comment]
@yanndegat great! I didn't see that PR and was about to code it. So I guess the `ovh_publiccloud_private_network_subnet` is pointless because we can do exactly the same thing with `openstack_networking_subnet_v2`, right?

**Comment by yanndegat** [comment]
@mcanevet well, last time i tried, i encountered the same issue as with the network. but i spoke with people from ovh at their last summit and they should "soon" open the neutron api, one day or another, whenever the interconnection with the vrack is functional.

**Comment by mcanevet** [comment]
@yanndegat `openstack_networking_subnet_v2` works fine now.

**Comment by stack72** [comment]
@yanndegat - AWESOME! Sorry not been in touch about this - will get to reviewing as soon as 0.9 goes out the door :)

Paul

**Comment by yanndegat** [comment]
@stack72 no pb. you tell me

**Comment by mcanevet** [comment]
@yanndegat wouldn't it be better to remove the `ovh_publiccloud_private_network_subnet` as we can do the same thing with `openstack_networking_subnet_v2`. This is misleading I think.

**Comment by yanndegat** [comment]
@mcanevet well... i think the the question is: 
- should the provider provide only the features we can't implement with the other providers (openstack/vmware)
so that when you "terraform" an OVH infrastructure, you always have to use at least 2 providers (ovh+openstack or ovh+vmware)

or

- should the provider "map" the OVH Api as most as possible so that the user can choose whether he uses only the ovh provider or a mix between the ovh provider and openstack/vmware.

and as of today, i really don't know how to answer that question.

**Comment by mcanevet** [comment]
@yanndegat I have an issue when trying to import an `ovh_publiccloud_private_network`:

```shell
$ terraform import ovh_publiccloud_private_network.my_network <vrack_id>_1
ovh_publiccloud_private_network.my_network: Importing from ID "<vrack_id>_1"...
ovh_publiccloud_private_network.my_network: Import complete!
  Imported ovh_publiccloud_private_network (ID: <vrack_id>_1)
ovh_publiccloud_private_network.my_network: Refreshing state... (ID: <vrack_id>_1)
Error importing: 1 error(s) occurred:

* ovh_publiccloud_private_network.my_network (import id: <vrack_id>_1): 1 error(s) occurred:

* import ovh_publiccloud_private_network.my_network result: <vrack_id>_1: ovh_publiccloud_private_network.my_network: Error calling /cloud/project//network/private/<vrack_id>_1:
	 "Error 404: \"Got an invalid (or empty) URL\""
```

The project_id is missing from the URL.
Do you have any idea?

**Comment by yanndegat** [comment]
@mcanevet ok, it's possible that there's an issue with env vars during "import" phase. i'll have to check this. thank you

**Comment by mcanevet** [comment]
@stack72 is there something missing to merge this?

**Comment by stack72** [comment]
Hi @yanndegat 

I am trying to test this right now - I have just set up an OVH account but I can't add a payment method to it - looks like the page doesn't work. Any thoughts on how I can test this?

P.

**Comment by yanndegat** [comment]
well,

i think we'll have to get support from OVH for this.
let me contact them to see what we can do about it.



bitmessage address: BM-2cTD49oR1Xwu28XswZoh4qRMeeQwpUYvhY

**Comment by mcanevet** [comment]
@stack72 FYI I can confirm that at least `ovh_publiccloud_private_network` and `ovh_vrack_publiccloud_attachment` are working very well. We are using it in production for a few weeks now.

**Comment by stack72** [comment]
@mcanevet I need to be able to run this in our acceptance testing environment :)

**Comment by mcanevet** [comment]
Link to another PR implementing an OVH provider but with another resource : https://github.com/hashicorp/terraform/pull/14111

**Comment by yanndegat** [comment]
thanks. i'll try to merge it

bitmessage address: BM-2cTD49oR1Xwu28XswZoh4qRMeeQwpUYvhY

**Comment by stack72** [comment]
Hi @yanndegat 

So, got those secrets - thanks so much - trying to run the tests and get the following:

```
=== RUN   TestAccVRackPublicCloudAttachment_basic
--- FAIL: TestAccVRackPublicCloudAttachment_basic (0.22s)
	provider_test.go:77: couln't load OVH Client: OVH client seems to be misconfigured: "Error 403: \"This credential is not valid\""
FAIL
```

I have set the following env vars

```
export OVH_ENDPOINT=ovh-eu
export OVH_APPLICATION_KEY=<redacted>
export OVH_APPLICATION_SECRET=<redacted>
export OVH_CONSUMER_KEY=<redacted>
export OVH_PUBLIC_CLOUD=9944712e635e41478b28de8534683477
export OVH_VRACK=pn-49183
```

Anything else I need to set?

**Comment by stack72** [comment]
ping @yanndegat :)

**Comment by yanndegat** [comment]
hi @stack72,

yes, i'll have a look right now;)

bitmessage address: BM-2cTD49oR1Xwu28XswZoh4qRMeeQwpUYvhY

**Comment by yanndegat** [comment]
hi @stack72

i've updated the ovhrc in your private keybase folder.
i've forgotten to validate the consumer key.
now it should be working.


bitmessage address: BM-2cTD49oR1Xwu28XswZoh4qRMeeQwpUYvhY

**Comment by stack72** [comment]
Hi @yanndegat 

You are correct - I am able to run the tests now. Unfortunately, they are not passing

```
% make testacc TEST=./builtin/providers/ovh                                                        ✭
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/05/15 12:11:18 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/ovh -v  -timeout 120m
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccPublicCloudPrivateNetworkSubnet_basic
--- FAIL: TestAccPublicCloudPrivateNetworkSubnet_basic (4.49s)
	provider_test.go:117: Read Cloud Project /cloud/project/9944712e635e41478b28de8534683477 -> status: 'ok', desc: 'Hashicorp Acceptance Tests'
	testing.go:280: Step 0 error: Error applying: 1 error(s) occurred:

		* ovh_publiccloud_private_network.network: 1 error(s) occurred:

		* ovh_publiccloud_private_network.network: calling /cloud/project/9944712e635e41478b28de8534683477/network/private with params projectId: 9944712e635e41478b28de8534683477, vlanId:0, name: terraform_testacc_private_net, regions: [BHS1 GRA1]:
			 "Error 400: \"Please attach a vrack on your project before creating private network\""
	testing.go:344: Error destroying resource! WARNING: Dangling resources
		may exist. The full state and error is shown below.

		Error: Error applying: 1 error(s) occurred:

		* ovh_vrack_publiccloud_attachment.attach (destroy): 1 error(s) occurred:

		* ovh_vrack_publiccloud_attachment.attach: Error 500: "Unable to detach this project from private network"

		State: ovh_vrack_publiccloud_attachment.attach:
		  ID = vrack_pn-49183-cloudproject_9944712e635e41478b28de8534683477-attach
		  project_id = 9944712e635e41478b28de8534683477
		  vrack_id = pn-49183
=== RUN   TestAccPublicCloudPrivateNetwork_basic
--- FAIL: TestAccPublicCloudPrivateNetwork_basic (4.35s)
	provider_test.go:117: Read Cloud Project /cloud/project/9944712e635e41478b28de8534683477 -> status: 'ok', desc: 'Hashicorp Acceptance Tests'
	testing.go:280: Step 0 error: Error applying: 1 error(s) occurred:

		* ovh_publiccloud_private_network.network: 1 error(s) occurred:

		* ovh_publiccloud_private_network.network: calling /cloud/project/9944712e635e41478b28de8534683477/network/private with params projectId: 9944712e635e41478b28de8534683477, vlanId:0, name: terraform_testacc_private_net, regions: [BHS1 GRA1]:
			 "Error 400: \"Please attach a vrack on your project before creating private network\""
	testing.go:344: Error destroying resource! WARNING: Dangling resources
		may exist. The full state and error is shown below.

		Error: Error applying: 1 error(s) occurred:

		* ovh_vrack_publiccloud_attachment.attach (destroy): 1 error(s) occurred:

		* ovh_vrack_publiccloud_attachment.attach: Error 500: "Unable to detach this project from private network"

		State: ovh_vrack_publiccloud_attachment.attach:
		  ID = vrack_pn-49183-cloudproject_9944712e635e41478b28de8534683477-attach
		  project_id = 9944712e635e41478b28de8534683477
		  vrack_id = pn-49183
=== RUN   TestAccPublicCloudUser_basic
--- PASS: TestAccPublicCloudUser_basic (24.30s)
	provider_test.go:117: Read Cloud Project /cloud/project/9944712e635e41478b28de8534683477 -> status: 'ok', desc: 'Hashicorp Acceptance Tests'
=== RUN   TestAccVRackPublicCloudAttachment_basic
--- PASS: TestAccVRackPublicCloudAttachment_basic (206.46s)
	provider_test.go:98: Read VRack /vrack/pn-49183 -> name:'', desc:''
	provider_test.go:117: Read Cloud Project /cloud/project/9944712e635e41478b28de8534683477 -> status: 'ok', desc: 'Hashicorp Acceptance Tests'
FAIL
exit status 1
FAIL	github.com/hashicorp/terraform/builtin/providers/ovh	239.625s
make: *** [testacc] Error 1
```

Thoughts?

P.

**Comment by yanndegat** [comment]
@stack72 : having a look at it

bitmessage address: BM-2cTD49oR1Xwu28XswZoh4qRMeeQwpUYvhY

**Comment by yanndegat** [comment]
hi @stack72 

well, i've managed to make the acc. tests pass with your ovhrc.

1/ there was a notion i was missing: there are specific per project regions associations.
E.G.: my project was  associated with GRA1, BHS1, ... and yours with GRA3, BHS3...
So i had to add 2 new datasources to be able to run your tests because i was referencing hard
values in acceptance tests.

2/ i didn't fix anything else to make the other tests pass but i noticed that sometimes we hit an http 500 error. If i replay the same request right after, it passes. In fact, the same requests are run for almost every acceptance tests because each of them attach a vrack to a public cloud project. (and then destroys it) i think there may be some issues within ovh services. i'll try to ping them about this.

what shall we do meanwhile ?



─yann@yann_work [17:26:03] ~/work/go/src/github.com/hashicorp/terraform  ‹master*›
╰─$ make testacc TEST=./builtin/providers/ovh
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/05/15 17:26:10 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/ovh -v  -timeout 120m
=== RUN   TestAccPublicCloudRegionDataSource_basic
--- PASS: TestAccPublicCloudRegionDataSource_basic (6.84s)
=== RUN   TestAccPublicCloudRegionsDataSource_basic
--- PASS: TestAccPublicCloudRegionsDataSource_basic (2.09s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccPublicCloudPrivateNetworkSubnet_basic
--- PASS: TestAccPublicCloudPrivateNetworkSubnet_basic (108.54s)
        provider_test.go:117: Read Cloud Project /cloud/project/9944712e635e41478b28de8534683477 -> status: 'ok', desc: 'Hashicorp Acceptance Tests'
=== RUN   TestAccPublicCloudPrivateNetwork_basic
--- PASS: TestAccPublicCloudPrivateNetwork_basic (103.24s)
        provider_test.go:117: Read Cloud Project /cloud/project/9944712e635e41478b28de8534683477 -> status: 'ok', desc: 'Hashicorp Acceptance Tests'
=== RUN   TestAccPublicCloudUser_basic
--- PASS: TestAccPublicCloudUser_basic (29.14s)
        provider_test.go:117: Read Cloud Project /cloud/project/9944712e635e41478b28de8534683477 -> status: 'ok', desc: 'Hashicorp Acceptance Tests'
=== RUN   TestAccVRackPublicCloudAttachment_basic
--- PASS: TestAccVRackPublicCloudAttachment_basic (64.92s)
        provider_test.go:98: Read VRack /vrack/pn-49183 -> name:'', desc:''
        provider_test.go:117: Read Cloud Project /cloud/project/9944712e635e41478b28de8534683477 -> status: 'ok', desc: 'Hashicorp Acceptance Tests'
PASS
ok      github.com/hashicorp/terraform/builtin/providers/ovh    314.775s

**Comment by stack72** [comment]
@yanndegat ok, let's merge this for now :) We can worry about the API issues later.

I believe that it's only because of hitting limits

Thanks for all the work here - it's been awesome! I will follow up with you on email

**Comment by yanndegat** [comment]
that"s super great!

thanks a lot!

**Pull request merged**
