### PR TITLE
Added support for redshift destination to firehose delivery streams

### PR DESCRIPTION
**Pull request by dminnear**
Previously, firehose delivery streams only supported writing to s3. This PR adds redshift as a destination for firehose delivery streams. There is also some refactoring done to clean up the s3 configuration so existing delivery stream resources will be broken.

The related issue is #5152.

### CODE REVIEW

**Comment by bubenkoff** [comment]
any change to get it merged anytime soon?

**Comment by nathanleiby** [comment]
@catsby if I fixed merge conflicts, would this be likely to get merged? Please let me know if there are other guidelines that need to be followed.

(Thanks @dminnear for the PR!)

**Comment by schimmy** [comment]
Yes @catsby I'd also be very interested in merging this, and would be wiling to help @nathanleiby with the merge conflicts

**Comment by catsby** [comment]
Hi there – 

I see you've made some changes to `helper/resource/testing.go`, are those required for this patch? I'd like to understand why those changes were made.

So that we're clear, this is a backwards incompatible change, correct?

**Comment by dminnear** [comment]
@Bowbaq Do you remember why we made that change to `testing.go`? I think it was to do `resource.TestCheckResourceAttr("aws_kinesis_firehose_delivery_stream.test_stream", "s3_configuration.buffer_size", "5")` and without it that would error since `s3_configuration.buffer_size` is a nested value.

I can probably solve all the merge conflicts this weekend if you guys want this PR, we were using it in production some months ago, just keep in mind that it does break existing tf files since it changes how to use s3 delivery streams.

**Comment by Bowbaq** [comment]
@dminnear @catsby correct, the changes in `testing.go` are a workaround for using a `Set` type for sub-resources. We've added support so that a test checking the value of property `s3_configuration.buffer_size` will fallback to checking `s3_configuration.<hashcode>.buffer_size` in the state. Maybe there's a better way to do that, but I'm not aware of one.

**Comment by catsby** [comment]
An approach we've taken in the past was a method similar to `testAccCheckAWSKinesisFirehoseDeliveryStreamAttributes` and to check the attributes as they come back from the API. 

If the API has the value we expect, and Terraform does not report an non-empty plan, then we assume things to be good

**Comment by Bowbaq** [comment]
I don't see much point in testing the API, presumably whoever created it has their own tests.  I was more interested in checking the correctness of the plan.

I don't really know how the hashcodes are calculated in terraform. It's possible this extension to the testing framework could be made precise instead of heuristic. Unclear how much work that would be though.

**Comment by apparentlymart** [comment]
@Bowbaq what we want to test in acceptance tests is not whether the remote API is behaving correctly but rather whether the Terraform code is *using* the remote API correctly. In order to do that, we make real API calls to the service in question and then inspect what was created to ensure that the expected objects are present.

It is also useful to test that the `Computed` attributes of the resource get populated correctly, but 100% coverage of the entire object is generally not expected... we just extend the acceptance tests in response to bugs that get discovered and fixed, so we learn over time what are the interesting behaviors to test.

**Comment by dminnear** [comment]
@catsby Thanks for the elegant update! Feel free to close this PR. Cool work with the v0 -> v1 migration, I didn't even know that was possible.

**Comment by catsby** [comment]
Hey all – I continued this PR over in #7375 for those interested. I added a handful of minor things that were needed but I didn't want to bug anyone else about. Check it out!

**Comment by schimmy** [comment]
awesome, thanks @catsby !

**Pull request closed without merging**
