### PR TITLE
Update vmware-govcd plugin

### PR DESCRIPTION
**Pull request by robinbowes**
This PR updates the vendored vmware-govcd plugin

It passes all tests and builds for me (on OSX).

### CODE REVIEW

**Comment by stack72** [comment]
Hi @robinbowes 

Do you still need this merged?

Paul

**Comment by robinbowes** [comment]
Well, I'm not currently working on either terraform or vcloud, but that's no reason to not keep the vcloud provider up-to-date :)

**Comment by stack72** [comment]
Got it! I am looking through the back log to see what is / isn't needed anymore

Thanks for the info

**Comment by stack72** [comment]
Closing as there is no activity on this - thanks for all the work here

**Comment by robinbowes** [comment]
I'm not clear why you've not merged this?

You're vendoring the plugin; this MR simply updates the plugin to a more recent version.

**Comment by stack72** [comment]
Hi @robinbowes 

There is a merge conflict and we are not in a position to be able to test the VCD configuration. I can easily fix the conflict, but, as this is not a core provider, if there are issues with it, then it could cause issues for the userbase

We want to mitigate that as much as possible. If you really need this to be merged then we can do that 

Paul

**Pull request closed without merging**
