### PR TITLE
state/remote/swift: Updates

### PR DESCRIPTION
**Pull request by fatmcgav**
Updates to `swift` remote state support:

- Use Gophercloud/gophercloud
- Add support for 'insecure' TLS
- Add Keystone v3 auth values
- Documentation updates

### CODE REVIEW

**Comment by fatmcgav** [comment]
@jtopjian Not sure if you've done anything with Terraform remote state before, but wouldn't mind a quick review of this one from a Gophercloud POV...

**Comment by fatmcgav** [comment]
Hmm, looks like am missing some vendored packages from gophercloud/gophercloud... 

Now lets see if I can work out how to vendor them in :)

**Comment by jtopjian** [comment]
@fatmcgav Nice. I've been meaning to take a look at the Swift remote state support for a while. :)

**Comment by fatmcgav** [comment]
@jtopjian Heh, surprisingly it "Just worked" ;) 

Just making some additions now for extra config settings inline with the changes you made in #9725

**Comment by fatmcgav** [comment]
OK, I think I've got all the possible config permutations covered... 

@jtopjian Fancy giving it a spin?

**Comment by fatmcgav** [comment]
@stack72 I'm guessing I'm going to need to clean this one up a bit... ;)

Any preference on splitting down, or all in one commit?

**Comment by jtopjian** [comment]
@fatmcgav I'll try this out and report back :)

Re cleanup: This PR might make sense as two or more PRs instead of one. It looks like there are distinct topic differences. For example, adding SSL certs doesn't necessarily mean that moving to the new gophercloud repo has to happen at the same time.

Maybe two PRs? One for the Gophercloud move and one for the SSL updates? I can definitely make sure they are merged shortly within each other.

**Comment by fatmcgav** [comment]
@jtopjian Yeh, can look at splitting it down... As this is also the last bit that's using 'rackspace/gophercloud', so can un-vendor that aswell as part of the Gophercloud move PR...

**Comment by jtopjian** [comment]
@fatmcgav that sounds good to me!

**Comment by fatmcgav** [comment]
@jtopjian FYI, I've split the gophercloud migration into https://github.com/fatmcgav/terraform/tree/state_remote_swift_updates_rework. 
I haven't yet updated this branch, as didn't want to break it if you're testing... ;) 

Can then raise a new PR for the other updates...

**Comment by jtopjian** [comment]
@fatmcgav I won't have time to test until this evening (another 7-ish hours my time) so feel free to break this PR up. You can also have the second PR based on the first and unless any changes are made to the first, the second will merge cleanly. I can then test solely on the second PR. :)

**Comment by fatmcgav** [comment]
@jtopjian Cool, ok... I'll get breaking then :)

**Comment by jtopjian** [comment]
@fatmcgav wow - this really needed an update! Keystone v3 wasn't even working. Thanks!

The Swift code looks good to go. A few notes about the vendoring:

1) Can you update the commit messages to have the format:

```
vendor: Updating github.com/gophercloud/gophercloud
vendor: Removing github.com/rackspace/gophercloud
```

Feel free to add a short commit message about each.

2) To fully add/remove a dependency, do:

```
$ govendor fetch github.com/gophercloud/gophercloud/...
$ govendor remove github.com/rackspace/gophercloud/...
```

The trailing `...` is literally a trailing three dots.

I suspect you'll end up with a lot more deleted files after that. Looks like you have the honours of fully wiping out the old repo :)

**Comment by fatmcgav** [comment]
@jtopjian Yeh, was very neglected. 

Commit messages updated, and lots more `github.com/rackspace/gophercloud` file deletions after a `govendor remove` with trailing `...`.

**Comment by jtopjian** [comment]
LGTM!

**Pull request merged**
