### PR TITLE
backend/obs: Add HuaweiCloud OBS backend with locking

### LINKED ISSUE #23888: Feature: Add Huaweicloud OBS backend
Hi there,

We would like to add a new backend type with HuaweiCloud OBS.

### Use-cases

```hcl
terraform {
  backend "obs" {
    bucket = "accbucket"
    key    = "obsbackend/terraform.tfstate"
    region = "cn-north-1"
    access_key_id = "{{ your access key }}"
    secret_key_id = "{{ your secret key  }}"
  }
}
```
Thanks.

### PR DESCRIPTION
**Pull request by ShiChangkuo**
Hello,
This PR provides a new backend that terraform can store state remotely in HuaweiCloud OBS with locking.

the result of testing as follows:
```
=== RUN   TestStateFile
=== PAUSE TestStateFile
=== RUN   TestRemoteClient
=== PAUSE TestRemoteClient
=== RUN   TestRemoteClientWithPrefix
=== PAUSE TestRemoteClientWithPrefix
=== RUN   TestRemoteClientWithEncryption
=== PAUSE TestRemoteClientWithEncryption
=== RUN   TestRemoteLocks
=== PAUSE TestRemoteLocks
=== RUN   TestBackend
=== PAUSE TestBackend
=== RUN   TestBackendWithPrefix
=== PAUSE TestBackendWithPrefix
=== RUN   TestBackendWithEncryption
=== PAUSE TestBackendWithEncryption
=== CONT  TestStateFile
--- PASS: TestStateFile (0.00s)
=== CONT  TestBackendWithEncryption
...
--- PASS: TestBackend (5.23s)
PASS
ok  	github.com/hashicorp/terraform/backend/remote-state/obs	6.473s
```

for more details, please find the attachment:
[test_result_0414.log](https://github.com/hashicorp/terraform/files/4474064/test_result_0414.log)

Fixes #23888

### CODE REVIEW

**Comment by ShiChangkuo** [comment]
@jbardin @pselle , Would you please help processing the review?

**Comment by ShiChangkuo** [comment]
# how to test
## set environment variables
export OS_ACCESS_KEY=...
export OS_SECRET_KEY=...
export OS_REGION_NAME=...

## run test
$ TF_ACC=1 go test -v

**Comment by niuzhenguo** [comment]
Any progress?

**Comment by danieldreier** [comment]
Hello @ShiChangkuo ShiChangkuo -

I really appreciate you making an effort to contribute to Terraform, and to build an integration with an incredibly big cloud provider. The need for HuaweiCloud support is clear, especially to support users in China. Unfortunately, we’re not going to be able to accept this PR, and I want to explain why, and what your options are.

When we adopt new state backends in Terraform core, we take on significant responsibility, because problems with state backends significantly impact users. At the same time, it’s very difficult for us to maintain community-contributed state backends, because we have to maintain code and handle bug reports for integrations we lack domain knowledge in. We’ve tried, and it has been unsatisfactory for our users, open source contributors, and our engineers.

For example, we’ve found that subtle locking bugs are almost inevitable: even very good engineers often miss them, and when we accept community-contributed state backends, we end up responsible for testing and validation of distributed systems that we lack domain knowledge in. This part of the codebase is relatively hard to get right, and bugs in it have an extremely high impact on users. Our experience has been that we cannot guarantee the high quality that users need when we accept third party state backends, and so we have made the difficult decision to stop accepting new community-contributed state backends.

In the future, we are hoping to build a plugin system, similar to the provider system, for allowing external contributors to build state backend plugins that are not built into Terraform core. When that happens, I hope you will build a state backend for HuaweiCloud OBS.

Until we have built a plugin system, we will not be accepting any new state backends that are not maintained by HashiCorp employees, and so I am closing this pull request. If you would like to discuss this further, feel free to reach out to me at ddreier@hashicorp.com or to Petros Kolyvas, our Product Manager, at petros@hashicorp.com.

**Comment by ShiChangkuo** [comment]
@danieldreier 
    Thanks for your response. I understand your explain and very excited to wait for the state backend plugin system.

**Pull request closed without merging**
