### PR TITLE
Yank Azure provider for now

### PR DESCRIPTION
**Pull request by phinze**
This was some first-rate work by @frodenas, to be sure!

However, we'd like to approach the Azure provider a bit more holistically. Rather than releasing this single-resource start and confusing users with a release that "includes Azure support", we'd prefer to wait until we can land a more fully featured and well-supported provider.

We've also had a couple of upstream dependency issues since the Azure go library is under heavy development.

We're getting close to a 0.3.7 release, and pulling the provider will simplify things for now.

Thanks again for all your work on this, @frodenas! I'll make sure to highlight you when we circle back around to Azure.

### CODE REVIEW

**Comment by mitchellh** [comment]
I agree for now. And I second that its first rate work by @frodenas. Let's get it in for 0.4!

**Comment by frodenas** [comment]
Sure, no problem here. My PR just solved a small use case I had to deal with. Be sure to circle back with @keithchambers, he was also looking to expand the Azure support in Terraform.

**Comment by bmorton** [comment]
As some feedback, this was still confusing as it got merged in and I dug through the PR, documentation, and code to figure out how it worked only to find out after experimenting, failing, upgrading, building master from source, and then finally coming across this PR.

As a user, I'd rather see incremental support added rather than a big-bang, fully featured release.

**Comment by hsunami** [comment]
just curious to see if there are any plans to reintegrate the azure provider soon? thanks in advance.

**Comment by svanharmelen** [comment]
@hsunami @frodenas @keithchambers I'm just about done with a very reasonable Azure provider. Currently supporting the creation and updating of both Windows and Linux instances, virtual networks, subnets and network security groups.

Last thing I want to add before making a PR is support for data disks and add some acceptance tests. So expect to make the PR later this week.

**Comment by hsunami** [comment]
@svanharmelen awesome Sander, thanks for your reply!!

**Pull request merged**
