### PR TITLE
Add ansible-local provisioner

### PR DESCRIPTION
**Pull request by wjam**
This adds the capability of provisioning a resource using Ansible that is running locally to the resource being provisioned.

This fixes part of #2661.

### CODE REVIEW

**Comment by wjam** [comment]
A large amount of inspiration for this PR has come from Packer which has similar functionality. Doing the same thing to the `ansible-remote` provisioner will take more time due to the complexity of how it works

**Comment by wjam** [comment]
@radeksimko @apparentlymart Is it possible to get this reviewed?

**Comment by wjam** [comment]
Any chance of this being reviewed? @apparentlymart @radeksimko

**Comment by SurferL** [comment]
@wjam Will this work for Windows hosts as well?

**Comment by anishmashankar** [comment]
Are there any near term plans for merging this? It would be really useful for us to make the switch from our current provisioning system.

**Comment by apparentlymart** [comment]
Hi @wjam! Sorry for the long silence here, and thanks for working on this.

To be transparent, we've found it pretty hard to support the existing service-specific provisioners already present (chef, salt-masterless) because we don't have in-house expertise with these nor infrastructure in place to test them. Thus we find ourselves pretty nervous about adding new ones that may end up in the same situation.

Given that there are far fewer provisioners than providers, we haven't developed a process for dealing with community-driven provisioner development/maintenance and so we found ourselves a bit stalled here, not really knowing how best to proceed.

Do you think that, were this to be merged, you'd be able to help field issues and PRs that might be submitted against this provisioner on an ongoing basis? With the provisioner still living inside the main repository (vs. providers, which were split out) we don't have a proper mechanism in place yet for direct community maintenance of provisioners, but if you'd be willing to monitor for new issues and test/review new PRs (which we could then merge, trusting your review/test) I think that would help assuage the concern here. A new issue/PR label `provisioner/ansible-local` would allow you to more easily find these, hypothetically.

**Comment by cmacrae** [comment]
👏 Great to see some action on this. Can totally appreciate your guys' stance on this @apparentlymart.  
Just dropping by to say: thank you for your work @wjam. Though I'm not particularly well versed in Go, I've used Ansible a lot.  
I'd be happy to keep an eye out for issues and step in where I feel I can help out. There's the small chance I might be able to help here-and-there on actual problems with the implementation, but there's a good chance I can probably assist with issues people might encounter due to misuse/"nuances" of Ansible's operation.

**Comment by wjam** [comment]
@apparentlymart Sure, I'd be willing to monitor issues & PRs for `ansible-local`.

**Comment by cyberious** [comment]
@apparentlymart and @wjam would it be possible to have separate repos for provisioners outside of say remote-exec and local-exec so we can have them centralized similar to the github.com/terraform-providers movement? Would love to have one that the community gets behind b/c as of right now we are using remote-exec for some crazy provisioning and would love to move that logic into an ansible style provisioning.

**Comment by svscorp** [comment]
I wonder, whether this PR is still in review? Will it be onboarded?

**Comment by lfshr** [comment]
Hey @apparentlymart any update on when this will be merged?

**Comment by fdavier** [comment]
Very interested for this new feature. Get a chance to use it for 2018 ?
Thank you

**Comment by JohnRoach** [comment]
Same here really looking forward for this to be merged in.

**Comment by tomaszkrzyzanowski** [comment]
@apparentlymart 

alt text

**Comment by slapula** [comment]
If we are considering the possibility of breaking out the provisioners, I'd like to bring attention to https://github.com/radekg/terraform-provisioner-ansible.  It works pretty well based on the testing Ive done so far and the fact that it's a plugin means we don't need to worry about merging additional code in to terraform core.

**Comment by pkolyvas** [comment]
In [mid-September 2020](https://discuss.hashicorp.com/t/notice-terraform-to-begin-deprecation-of-vendor-tool-specific-provisioners-starting-in-terraform-0-13-4/13997) we announced the deprecation of tool-specific vendor provisioners. Recently, we added a deprecation notice these provisioners in `0.13.4`. 

On a practical level this means we will no longer be reviewing or merging PRs for these built-in plugins. We will also not be adding new tool-specific provisioners to Terraform.

I realise this PR is overdue for a response and as the product manager of Terraform, that onus is on me for having left these untouched while we developed our near-term plan. 

The long term strategy here is less clear than we'd like, but for the time being I'd encourage the community of Terraform provisioner users and developers (who might also be reading this) to follow in the footsteps of the [ansible provisioner](https://github.com/radekg/terraform-provisioner-ansible) as mentioned here. 

Creating provisioner plugins and installing provisioner plugins manually is more involved. Our hope here is that the ability to improve, fix and repair these tools without us blocking their development, much like providers, will help make a strong case for what's next. 

There are also some technical hurdles to cross.  The Terraform plugin SDK does not support provisioners and so moving beyond the deprecation will require more concrete plans. We’d like to base those plans, in part, on the feedback we receive. I think it’s also important to highlight that we have no plans to remove the generic provisioners or the pluggable functionality during Terraform's 1.0 lifecycle.

We didn't make this decision lightly, and removing or no longer supporting features is not ideal for anyone who uses and depends on them. To that end, my door is always open. I'd invite anyone interested or concerned to write me or schedule some time with me to talk about these changes moving forward.

**Pull request closed without merging**
