### PR TITLE
provider/vsphere:  vsphere_virtual_machine resource - option to configure vm notes/annotation property

### PR DESCRIPTION
**Pull request by sripadkollur**
# What is this?
To implement [#9913](https://github.com/hashicorp/terraform/issues/9913) 
This enhancement adds option to specify annotation text to be set on Vsphere VM being created. This enhancement also allows modifying the annotation after VM is created without restarting VM.

# Review points
This is a useful feature as it helps administrator to distinguish the VMs created by terraform. This is a useful feature availbale in Vsphere/Vcenter and same is made available in terraform as part of this patch.

# Note
None

### CODE REVIEW

**Comment by sripadkollur** [comment]
Hello Everyone,
Can you please review this pull request? I am new to terraform ecosystem. Please let me know if I need to follow any process or missing something. Awaiting review?

Regards,
Sripad.

**Comment by darrenswhite** [comment]
Using custom_configuration_parameters should be sufficient. An example would be:

```
resource "vsphere_virtual_machine" "my_vm" {
    name = "my_vm"

    custom_configuration_parameters {
        my-annotation-key = "my-annotation-value"
  }
}
```

**Comment by sripadkollur** [comment]
@darrenswhite 
The custom configuration parameters would not show up as notes in Vcenter UI. It is better to use govmomi provided annotation field so that the annotation added is shown in correct field in Vcenter UI.

**Comment by apparentlymart** [comment]
Hello @sripadkollur, and thanks for working on this!

As part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it.

[The vSphere provider](https://github.com/terraform-providers/terraform-provider-vsphere) -- and, in particular, the virtual machine resource -- are currently in the process of being revamped somewhat, with the goal of supporting more of the available features. Unfortunately this means that to re-target this change to the new repository may require some restructuring :confounded:.

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Pull request closed without merging**
