### PR TITLE
Fixing the broken Test with Master branch

### PR DESCRIPTION
**Pull request by iceycake**
Looks like the master branch is broken due to a bad test implementation.

### CODE REVIEW

**Comment by catsby** [comment]
Hey @iceycake – can you show me what error you're seeing? 
I don't immediately see how this failure to dereference the string here in error _statement_ is causing a failure... can you show me what I'm missing?

**Comment by iceycake** [comment]
This is the error i got when i tried to build master branch:

```
go tool vet -all .
builtin/providers/aws/resource_aws_elastic_beanstalk_environment_test.go:265: arg value for printf verb %s of wrong type: *string

Vet found suspicious constructs. Please check the reported constructs
and fix them if necessary before submitting the code for review.
make: *** [vet] Error 1

```

**Comment by jen20** [comment]
Hi @iceycake! Can you confirm which version of `go` and `go vet` you have? Running locally with `master` I don't see this failure, and Travis appears not to be either.

**Comment by iceycake** [comment]
```
USHOLACH01-ML:terraform andy.chan$ go version
go version go1.6.2 darwin/amd64

```

**Comment by jen20** [comment]
Thanks @iceycake, the fix is correct. Merged to master!

**Pull request merged**
