### PR TITLE
Update taint docs - for_each

### PR DESCRIPTION
**Pull request by scott1138**
Provide an explanation of how to taint a resource created with for_each

### CODE REVIEW

**Comment by pselle** [comment]
Thanks for the PR @scott1138! This should be covered by the docs on that page surrounding addressing, notably https://www.terraform.io/docs/commands/taint.html#aws_instance-baz-quot-key-quot-, but I notice that that's not rendering correctly, so I'll look into that.

I'll also tag in our documentation lead @nfagerlund to see his thoughts on adding more examples to this page (and ordering, etc.) as I do think addressing by string addresses is a bit tricky right now as far as needing the `\"` escape.

**Comment by scott1138** [comment]
Thanks @pselle - it seems like more examples can never be bad, especially with the syntax can be confusing.

**Comment by nfagerlund** [comment]
I think I'm in favor of this — shell escaping is so nasty and squirrelly that a full-line example is worth the extra space. 

But that does bring up another question — do we have someone who can test this on Windows before we merge it? I feel like I remember having to use some kind of tortured quoting construct elsewhere to make sure we weren't lying to Windows users.

**Comment by scott1138** [comment]
I’m actually a windows user. :)

I can confirm that worked for me, but I can test it from Linux as well.

Sent from my Commodore 64
________________________________

**Pull request merged**
