### PR TITLE
Docker provider: send HostConfig on create and start.

### LINKED ISSUE #3526: Docker Swarm, replicas & exposing ports - I get 'port is already allocated' on apply
```
* docker_container.frontend.1: Unable to start container: API error (500): Cannot start container 556d141acc87dcc4797c4a84d82cb35b49197db0009d20f2304f64c0b5146305: Bind for 0.0.0.0:80 failed: port is already allocated
```

I get this error consistently.  I have a 3 host swarm cluster, and want to start 3 replicas of the frontend container, one on each host.  One always fails to start.

My diagnosis is that, as Terraform is passing the HostConfig on start (and not on create), Swarm is making the placement decision before it knows about the port mapping, and is putting two of my frontends on the same machine.

I guess the fix is to pass HostConfig on create, but the comment in the code (https://github.com/hashicorp/terraform/blob/master/builtin/providers/docker/resource_docker_container_funcs.go#L35) seems to indicate you tried this and it didn't work.  I've tried it and it does; perhaps this is an Docker version thing?  Either way, would you be open to a PR which send the host config on create and start?

### PR DESCRIPTION
**Pull request by tomwilkie**
Fixes #3526

### CODE REVIEW

**Comment by tomwilkie** [comment]
@jen20 mind taking a look at this one please?  I'll rebase first thing tomorrow.

**Comment by ColinHebert** [comment]
This is now obsolete, isn't it?

**Comment by stack72** [comment]
Hi @ColinHebert - what makes this obsolete? Has functionality changed to mean we can close this off?

Paul

**Comment by ColinHebert** [comment]
@stack72 It's been deprecated:
https://docs.docker.com/engine/deprecated/#hostconfig-at-api-container-start

**Comment by stack72** [comment]
Hi @tomwilkie 

Thanks for the PR here. I am going to close this as the feature is deprecated as linked above. 

Thanks

Paul

**Pull request closed without merging**
