### PR TITLE
provider/aws: Fix issue when changing map-public-ip in Subnets

### LINKED ISSUE #671: aws subnet VPC forced to change when using "map_public_ip_on_launch" field
Hi,

With the latest edition of the field "map_public_ip_on_launch" in the subnet of the aws VPC we get the below change when terraform planning

~ aws_subnet.some.0
map_public_ip_on_launch: "false" => ""

However when we try to terraform update we get the following error:

Error applying plan:

1 error(s) occurred:

    Resource type 'aws_subnet' doesn't support update

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

The issues is that the state "map_public_ip_on_launch" is false anyway in my VPC so update should not be required.

I am using latest terraform compiled on linux

-S.

### PR DESCRIPTION
**Pull request by catsby**
This should fix #671 (partially?) by actually reading the `map_public_ip_on_launch` config var when making a change.

### CODE REVIEW

**Comment by catsby** [comment]
AWS Defaults this value to `false`. I wonder if adding `Default` to this would be appropriate.

**Comment by phinze** [comment]
> AWS Defaults this value to false. I wonder if adding Default to this would be appropriate. 

Since booleans are so tricky w/ Computed, I think it might be saner to add a `Default: false` and remove `Computed`.

**Comment by catsby** [comment]
> I think it might be saner to add a Default: false and remove Computed.

@phinze done

**Comment by phinze** [comment]
LGTM

**Pull request merged**
