### PR TITLE
Remove incorrect space in doc

### PR DESCRIPTION
**Pull request by willfaught**

### CODE REVIEW

**Comment by willfaught** [comment]
Do I need to keep the "HashiCorp CLA" app on my GH account for the CLA to remain valid? Or can I remove it now?

**Comment by crw** [comment]
@willfaught Looks good, thanks! As to your question, I do not know however once I have merged this fix, feel free to remove it.

**Comment by willfaught** [comment]
It looks like the merge lost the commit authorship :(

**Comment by crw** [comment]
Looks ok to me: https://github.com/hashicorp/terraform/blame/bddd348d740185730803e6a8d15f4afc56c5ee73/website/docs/language/files/index.mdx#L54

**Comment by willfaught** [comment]
Hmm, strange. On https://github.com/hashicorp/terraform/commits/main, it said @crw was the author. Now it shows @willfaught. Perhaps it was a bug that GitHub just fixed. Looks good now at least! :)

**Pull request merged**
