### PR TITLE
Cloudinit Multipart Configuration Resource

### PR DESCRIPTION
**Pull request by jen20**
This pull request is for a new resource in the `template` provider named `template_cloudinit_config` which renders multi-part cloudinit config templates from source files.

It has previously been worked on in #3416 (by me) and #4061 (by @sthulb), but prior to merging it would be good for someone else on the Terraform core team to review it.

## Example

```tf
resource "template_cloudinit_config" "myconfig" {
  gzip = false
  base64_encode = true

  part {
    content_type = "text/x-shellscript"
    content = "${file("shellscript1.sh")}"
  }

  part {
    content_type = "text/x-shellscript"
    content = "${file("shellscript2.sh")}"
  }

  part {
    content_type = "text/cloud-config"
    merge_type = "list(append)+dict(recurse_array)+str()"
    content = "${file("cloudconfig.yaml")}"
  }
}

output "content" {
  value = "${cloudinit_config.myconfig.rendered}"
}
```

Output:

```
--MIMEBOUNDARY
Content-Type: text/x-shellscript

#!/usr/bin/env bash

touch /.testscript2

--MIMEBOUNDARY
Content-Type: text/x-shellscript

#!/usr/bin/env bash

touch /.testscript1

--MIMEBOUNDARY
Content-Type: text/cloud-config
X-Merge-Type: list(append)+dict(recurse_array)+str()

#cloud-config

runcmd:
 - touch /testfile

--MIMEBOUNDARY
Content-Type: text/cloud-config

#cloud-config

runcmd:
 - touch /testfile2

--MIMEBOUNDARY--
```

### CODE REVIEW

**Comment by apparentlymart** [comment]
Hmm interesting... do you think this could just be a general multipart MIME encoder? It sure looks close at first glance... I'd be tempted to name it `template_mime_multipart`. :grinning:

**Comment by jen20** [comment]
@apparentlymart sort of. It does have some additional behaviour that currently stops it being a generic multipart encoder, though I'm not opposed necessarily to the idea of generalising it:
- checks are made as to the `Content-Type` of each part, and whether they are part of the list supported by CloudInit
- headers which are specific to CloudInit (`X-MergeType`) are included as first class options.

**Comment by sthulb** [comment]
@jen20 I've found an issue. I'll submit a PR against this branch

**Comment by jen20** [comment]
Also see #4189 - this requires using a fork of the `mime` package until the change referenced there is merged into the Go standard library.

**Comment by sthulb** [comment]
@jen20 is there any chance of getting this merged for the next release?

**Comment by phinze** [comment]
LGTM

**Comment by sthulb** [comment]
Thanks everyone. :)

**Comment by jen20** [comment]
@sthulb This should be in 0.6.9, which is due imminently!

**Comment by sthulb** [comment]
@jen20 🎉

**Comment by sthulb** [comment]
Thanks for your help @jen20

**Pull request merged**
