### PR TITLE
provider/aws: Fix spurious aws_spot_fleet_request diffs

### PR DESCRIPTION
**Pull request by Bowbaq**
This fixes the following issues:
- [x] The default value for `launch_specification.monitoring` was `""`, which got translated to `false` by AWS, generating a spurious diff
- [x] The default value for `launch_specification.ebs_optimized` was `""`, which got translated to `false` by AWS, generating a spurious diff
- [x] `launch_specification.vpc_security_group_ids` were not read back from AWS, generating a spurious diff
- [x] `launch_specification.vpc_security_group_ids` were not handled properly when setting 'associate_public_ip_address = true'
- [x] `launch_specification.user_data` was not handled consistently (sometimes hashed, sometimes not), generating a spurious diff

I also cleaned up some dead code handling a `security_groups` property since there is no way for the user to define it.

@stack72 it seems you've been reviewing spot fleet related PRs, so tagging you here.

One final note: it may be a good idea to reuse the same hash function for root/ebs/ephemeral volumes across this resource, `aws_instance` and `aws_launch_configuration`?

### CODE REVIEW

**Comment by stack72** [comment]
Hi @Bowbaq 

Thanks for the work here - currently, this change breaks our acceptance tests due to the change of hash

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSSpotFleetRequest_'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/03/06 16:03:57 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSSpotFleetRequest_ -timeout 120m
=== RUN   TestAccAWSSpotFleetRequest_changePriceForcesNewRequest
--- PASS: TestAccAWSSpotFleetRequest_changePriceForcesNewRequest (116.72s)
=== RUN   TestAccAWSSpotFleetRequest_lowestPriceAzOrSubnetInRegion
--- PASS: TestAccAWSSpotFleetRequest_lowestPriceAzOrSubnetInRegion (62.87s)
=== RUN   TestAccAWSSpotFleetRequest_lowestPriceAzInGivenList
--- FAIL: TestAccAWSSpotFleetRequest_lowestPriceAzInGivenList (58.03s)
	testing.go:265: Step 0 error: Check failed: 2 error(s) occurred:

		* Check 4/5 error: aws_spot_fleet_request.foo: Attribute 'launch_specification.1590006269.availability_zone' not found
		* Check 5/5 error: aws_spot_fleet_request.foo: Attribute 'launch_specification.3809475891.availability_zone' not found
=== RUN   TestAccAWSSpotFleetRequest_lowestPriceSubnetInGivenList
--- PASS: TestAccAWSSpotFleetRequest_lowestPriceSubnetInGivenList (85.96s)
=== RUN   TestAccAWSSpotFleetRequest_multipleInstanceTypesInSameAz
--- FAIL: TestAccAWSSpotFleetRequest_multipleInstanceTypesInSameAz (54.30s)
	testing.go:265: Step 0 error: Check failed: 4 error(s) occurred:

		* Check 4/7 error: aws_spot_fleet_request.foo: Attribute 'launch_specification.1590006269.instance_type' not found
		* Check 5/7 error: aws_spot_fleet_request.foo: Attribute 'launch_specification.1590006269.availability_zone' not found
		* Check 6/7 error: aws_spot_fleet_request.foo: Attribute 'launch_specification.3079734941.instance_type' not found
		* Check 7/7 error: aws_spot_fleet_request.foo: Attribute 'launch_specification.3079734941.availability_zone' not found
=== RUN   TestAccAWSSpotFleetRequest_multipleInstanceTypesInSameSubnet
--- PASS: TestAccAWSSpotFleetRequest_multipleInstanceTypesInSameSubnet (93.65s)
=== RUN   TestAccAWSSpotFleetRequest_overriddingSpotPrice
--- FAIL: TestAccAWSSpotFleetRequest_overriddingSpotPrice (58.69s)
	testing.go:265: Step 0 error: Check failed: 4 error(s) occurred:

		* Check 5/8 error: aws_spot_fleet_request.foo: Attribute 'launch_specification.522395050.spot_price' not found
		* Check 6/8 error: aws_spot_fleet_request.foo: Attribute 'launch_specification.522395050.instance_type' not found
		* Check 7/8 error: aws_spot_fleet_request.foo: Attribute 'launch_specification.1590006269.spot_price' not found
		* Check 8/8 error: aws_spot_fleet_request.foo: Attribute 'launch_specification.1590006269.instance_type' not found
```

I am going to try and fix this up before i can merge this

Hope this is all ok - if so, stick with me for a day or 2

Paul

**Comment by stack72** [comment]
Hi @Bowbaq 

I have fixed up the tests now and all looks good - I am going to manually merge this to get the commit for the test results in

Thanks for the work 

Paul

**Comment by Bowbaq** [comment]
@stack72 forgot to check the tests, my bad, thanks for fixing

**Comment by stack72** [comment]
👍

**Pull request merged**
