### PR TITLE
[#4794] Don't Base64-encode EC2 userdata if it is already Base64 encoded

### PR DESCRIPTION
**Pull request by dougneal**
The user data may be Base64 encoded already - for example, if it has been generated by a template_cloudinit_config resource.

Partially resolves https://github.com/hashicorp/terraform/issues/4794

### CODE REVIEW

**Comment by catsby** [comment]
Looks good, thanks! Could I trouble you to throw some already encoded data into the config of the [TestAccAWSInstance_vpc][test]? You can reuse [this user_data encoding][encoding]. That will give us an acceptance test that verifies this works. 

Let me know!

[test]: https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_instance_test.go#L281
[encoding]: https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_instance_test.go#L61-L64

**Comment by dougneal** [comment]
Hey @catsby, something like this? It doesn't decode to anything meaningful, but it passes as a valid Base64 encoding.

**Comment by catsby** [comment]
Yep! I'll to add the `resource.TestCheckResourceAttr` check for that test, thanks!

**Comment by catsby** [comment]
Here's the addition, in case you're curious 

- https://github.com/hashicorp/terraform/commit/2830558bc95a89b8246a8464b338ec0f84edae33

That string is the hex encoding that we do in the [StateFunc][statefunc] for `user_data` 

[statefunc]: https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_instance.go#L91-L103

**Pull request merged**
