### PR TITLE
Adding a computed ARN for the S3 Bucket as per #3666

### PR DESCRIPTION
**Pull request by stack72**
Is a suggested enhancement as per #3666

### CODE REVIEW

**Comment by catsby** [comment]
Is there somewhere I can see the ARN for my bucket? How do I verify this?

**Comment by stack72** [comment]
@catsby The ARN for an S3 bucket is a standard format (as per the docs)

http://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#arn-syntax-s3

It is used when specifying s3 buckets in IAM roles etc:

```
resource "aws_iam_role_policy" "All-Access-S3-Backup" {
    name   = "All-Access-S3-Backup"
    role = "${aws_iam_role.app-server.id}"
    policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:*"
      ],
      "Resource": [
        "arn:aws:s3:::digit-backup",
        "arn:aws:s3:::digit-backup/*"
      ]
    }
  ]
}
POLICY
}
```

Before this change (and the request) I used to hardcode these values.

**Comment by catsby** [comment]
I understand the format, I was just curious if there was a place I could actually see it. Normally the console or `aws <service> --describe-thing` or similar, but the aws CLI for S3 seems lacking :confused: 

I'll go ahead and merge this in, thanks

**Comment by stack72** [comment]
@catsby FWIW, I went straight to the console to see if I could find it and then I went to the CLI reference :)

**Pull request merged**
