### PR TITLE
Closes #1908. Parse AccountId from User ARN for RDS tags

### LINKED ISSUE #1908: Can't apply tags to aws_db_instance
Trying to apply tags to an RDS instance and I'm getting this error:

```
* InvalidParameterValue: Invalid resource name:  arn:aws:rds:us-east-1:AIDAJDGLPYCDOTN7Q7BXG:db:dev-security-user
```

It appears that the `buildRDSARN` method is incorrectly constructing the ARN for the RDS instance. It's using the IAM `UserID` instead of the Account ID.

### PR DESCRIPTION
**Pull request by johnrengelman**
Based on: https://github.com/hashicorp/terraform/pull/1803/files#diff-047ff2782c4a593ae27a5b9bd8ad998fR289

### CODE REVIEW

**Comment by mitchellh** [comment]
LGTM

**Comment by catsby** [comment]
Looks good! As I noted in #1908 , I'm curious why it worked for me in the past. IAM cred issue perhaps? 

This could also be a good time to test the tags in AWS RDS instance, by tacking on a test to `TestAccAWSDBInstance`. Is that something you want to try out? Similar to https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_instance_test.go#L339, though you'd probably need an RDS specific implementation of `testAccCheckTagsSDK`. 

I can do so later if you don't think you'll have time.

Thanks again!

**Comment by catsby** [comment]
I created a DB with this config:

```javascript
provider "aws" {
  region = "us-west-2"
}

resource "aws_db_instance" "bar" {
	identifier = "foobarbaz-test-terraform-test2"

	allocated_storage = 5
	engine = "mysql"
	engine_version = "5.6.21"
	instance_class = "db.t1.micro"
	name = "baz"
	password = "barbarbarbar"
	username = "foo"

	backup_retention_period = 0

  tags {
    One = "Two"
    Three = "Four"
  }

	parameter_group_name = "default.mysql5.6"
}
```

Creation went fine, I then tried to remove the tag `Three` : 

```
~ aws_db_instance.bar
    tags.#:     "2" => "1"
    tags.Three: "Four" => ""
```

Applying that gave me an error: 

    * Error modifying DB Instance foobarbaz-test-terraform-test2: InvalidParameterCombination: No modifications were requested

I'll re-run the scenario on `master` but as you know, RDS takes time... :smile:

**Comment by johnrengelman** [comment]
What you've just encountered is another bug: https://github.com/hashicorp/terraform/issues/1906

**Pull request merged**
