### PR TITLE
Add 'strrev' interpolation function

### PR DESCRIPTION
**Pull request by ewbankkit**
Fixes https://github.com/hashicorp/terraform/issues/21075.

### CODE REVIEW

**Comment by mildwonkey** [comment]
Hi @ewbankkit !
Thank you for working on this PR. 

Unfortunately, the `config` package is used only in terraform 0.11; in 0.12 the functions have moved to [`lang`](https://github.com/hashicorp/terraform/blob/7d58643f272a8d4f792da49320f261f7a8273286/lang/functions.go). We do not expect any more 0.11 releases and 0.12 already includes this function, so I am going to close this PR. 

Thank you again for working on this!

**Comment by ewbankkit** [comment]
@mildwonkey Thanks for the info. I couldn't find a string reversal function in the current 0.12 docs - Do you happen to know its name?

**Comment by mildwonkey** [comment]
Oh! I found the [`strrev`](https://github.com/hashicorp/terraform/blob/7d58643f272a8d4f792da49320f261f7a8273286/lang/functions.go#L102) function, but not the documentation - I will re-open the issue you opened it as a documentation issue and get that fixed. Thank you so much for pointing that out!

**Comment by ewbankkit** [comment]
You've all been doing great work with the Terraform 0.12 betas so all is forgiven 😄.
I'll open another PR.

**Pull request closed without merging**
