### PR TITLE
Rundeck 2.7.1 1

### PR DESCRIPTION
**Pull request by BobVanB**
Ready for rundeck version Rundeck 2.7.1 1 and also rebased and merge the conflict with schedule_cron and schedule.

### CODE REVIEW

**Comment by stack72** [comment]
morning @BobVanB 

Thanks for the work here - please can you rebase this against master - there is a conflict noted in the PR

Thanks

Paul

**Comment by BobVanB** [comment]
Will rebase it tomorrow morning.
It was only a small conflict.

And I am still having trouble with the default interface of a boolean type. It soes not support nil.

And the vendor is out of sync with apearantlysmart/go-rundeck-api. That is after I got my code working.

We use this in production, will probably add the log limit feature in the near future.

**Comment by BobVanB** [comment]
@stack72 Please update the go-rundeck-api then this pull will also build :+1:

**Comment by BobVanB** [comment]
Ping?

**Pull request closed without merging**
