### PR TITLE
Data-driven Terraform Configuration

### PR DESCRIPTION
**Pull request by apparentlymart**
This is where I'm working on the implementation of the proposal from #4169.

* [x] `DataSource` type in the config module
* [x] Loading of `data` blocks from configuration files
* [ ] Validation of `data` blocks
* [ ] Introduction of data sources in the main `terraform` module
* [ ] New `RefreshData` method on the `ResourceProvider` interface
* [ ] `RefreshData` support in `helper/schema`
* Graph node and eval implementations for data sources:
 * [ ] Refresh
 * [ ] Plan
 * [ ] Apply

### CODE REVIEW

**Comment by phinze** [comment]
Hi @apparentlymart, this is looking good so far! I'm working on the Terraform / Vault integration which could really take advantage of Data Sources for several of its main data types.

So I'm checking in on your near-term plans are for this branch. If you don't expect to be picking it up soon, perhaps we can discuss me picking up where you left off?

Let me know! :grinning:

**Comment by apparentlymart** [comment]
@phinze I've become distracted by some other bits at work and so I got stalled on this.

If you'd like to pick it up then that's certainly fine by me. I'll push it to a branch in the main repo so that we can potentially both collaborate on it, if you don't finish it before I get some spare time again.

**Comment by apparentlymart** [comment]
Moving over to #4961, which is in the main hashicorp repo rather than in my fork.

**Comment by apparentlymart** [comment]
@phinze, @jen20: I checked off all the items on my list, so this is now feature-complete according to my original plan.

I have done some ad-hoc manual testing to exercise the various different combinations of computed/non-computed configs, dependent resources, dependent providers, etc.

----

Unfortunately the one situation that still doesn't seem to work is the very case that this feature was intended to solve:

```hcl
data "null_data_source" "test" {
  inputs = {
    aws_region = "us-west-2"
  }
}

provider "aws" {
  region = "${data.null_data_source.test.outputs.aws_region}"
}

resource "aws_instance" "foo" {
  instance_type = "t1.foo"
  ami           = "ami-abc123"
}
```

In the above configuration, the `aws` provider configuration depends on the data resource. The intended behavior is that the data instance gets created before the `aws` provider is configured. However, this fails with the following error on `terraform plan`:

```
$ terraform plan
Error configuring: 1 error(s) occurred:

* no error reported by variable "test" is nil
```

This error seems to be occuring during the "input" walk; running with `-input=false` makes the error go away and the plan complete as expected:

```
$ terraform plan -input=false
Refreshing Terraform state prior to plan...

data.null_data_source.test: Refreshing state...

The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed. Cyan entries are data sources to be read.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

+ aws_instance.foo
    ami:                      "ami-abc123"
    availability_zone:        "<computed>"
    ebs_block_device.#:       "<computed>"
    ephemeral_block_device.#: "<computed>"
    instance_state:           "<computed>"
    instance_type:            "t1.foo"
    key_name:                 "<computed>"
    placement_group:          "<computed>"
    private_dns:              "<computed>"
    private_ip:               "<computed>"
    public_dns:               "<computed>"
    public_ip:                "<computed>"
    root_block_device.#:      "<computed>"
    security_groups.#:        "<computed>"
    source_dest_check:        "1"
    subnet_id:                "<computed>"
    tenancy:                  "<computed>"
    vpc_security_group_ids.#: "<computed>"


Plan: 2 to add, 0 to change, 0 to destroy.
```

I'm not sure this is really resolvable... the only viable path I can see would be to skip asking for inputs on a provider that has any computed configuration, but even that doesn't seem like it'd work since it is the interpolation itself that is failing. If you have any other ideas I'd love to hear them! :grinning:

**Pull request closed without merging**
