### PR TITLE
Feature/func listintersection

### PR DESCRIPTION
**Pull request by pradeepbhadani**
We have a use-case where we need to find the intersection of two lists and there is no easy way to do this using existing interpolation function. 

This PR should be able to also solve https://github.com/hashicorp/terraform/issues/15410.

### CODE REVIEW

**Comment by apparentlymart** [comment]
Hi @pradeepbhadani! Thanks for working on this.

Unfortunately right now this part of Terraform is in a transitional state where we're now using implementations in a different place (in [the `lang` package](https://godoc.org/github.com/hashicorp/terraform/lang)) while the ones in `config` are dead code awaiting cleanup once we eliminate the old configuration parsing code. This means that adding the function implementation where you did will not make it available in future versions of Terraform. :confounded: 

As part of the development for the forthcoming v0.12.0 release we've added a function [`setintersection`](https://github.com/hashicorp/terraform/blob/954d38e8708a710061a87dc82834bc34bd1d9942/website/docs/configuration/functions/setintersection.html.md) which does something quite similar to what you wanted here.

The most significant difference is that it works on sets (a new type in 0.12) rather than lists, and so it will not preserve the relative ordering of the elements in the given lists. However, at first glance I don't think that the ordering can really be treated as significant _anyway_, since the common elements in the first list may be in a different order than those in the second list, and so it would be arbitrary which ordering is chosen. (In your implementation, I think it'd be the ordering in the second list, if I read correctly.)

Does the `setintersection` function achieve what you needed here? Terraform will automatically convert lists to sets when calling this function, so if the ordering _is_ important in some cases I think this could be handled with a more complex expression that is more explicit about which of the lists decides the ordering:

```
[for x in var.list2: x if sethaselement(setintersection(var.list1, var.list2), x)]
```

(That syntax is a [`for` expression](https://github.com/hashicorp/terraform/blob/954d38e8708a710061a87dc82834bc34bd1d9942/website/docs/configuration/expressions.html.md#for-expressions), which is another feature coming in Terraform v0.12.0 to allow constructing lists and maps from other collections.)

**Comment by pradeepbhadani** [comment]
Hi @apparentlymart  - Thanks for the update.
Do I understand correctly that there will be no more Terraform 0.11.x release and next release would be 0.12.x?
I guess terraform 0.12 GA is still has some time so meanwhile, can we include this feature in next terraform 0.11.x release?

Also, this function preserves the order (based on the second list) but this is not required for my use case.

**Comment by apparentlymart** [comment]
Terraform v0.11 is essentially feature-frozen from a core functionality standpoint. There _are_ 0.11 releases coming out, but they are being driven by upstream changes in Terraform Enterprise (for continued compatibility with its API) and not making any changes to the core Terraform functionality. There will not be any new Terraform Core features in the v0.11 line.

In particular, any time we would spend developing features and preparing releases for Terraform v0.11 is time we would not be spending getting v0.12.0 ready, so we are choosing to prioritize v0.12.0.

From what you've said here it sounds like the `setintersection` function already implemented in master would meet your needs, which is good news. We will continue to work on Terraform v0.12.0 and release it once it is ready. In that case, I will close this out and we'll address #15410 using the `setintersection` function. Thanks again for working on this!

**Comment by pradeepbhadani** [comment]
Thanks, @apparentlymart  for taking the time to review my code and answering my queries.
Looking forward to terraform v0.12.0

**Pull request closed without merging**
