### PR TITLE
[WIP] provider/openstack: DNS Zones V2

### PR DESCRIPTION
**Pull request by jrperritt**
for #14603

### CODE REVIEW

**Comment by jrperritt** [comment]
@jtopjian Can you review / take over this PR? I think it's done, but I can't run the acceptance tests. I tracked my issue down to [here](https://github.com/openstack/designate/blob/4fa77c7a6f580a8ab078550ab8c929793cba086d/designate/central/service.py#L884), so either there's a way to create name servers from the API that's not yet in Gophercloud, or my AIO deployment is lacking in functionality. Did you have to do anything special to get your OpenStack setup ready to test the Gophercloud DNS implementation?

**Comment by jtopjian** [comment]
@jrperritt Yep, I will take a look at this tonight.

I'm using [this](https://github.com/jtopjian/terraform-devstack/tree/master/designate-standalone) to build my Designate environment. You can deploy it in any cloud vm -- just dig into the `files/deploy.sh` script for how the environment is built.

**Comment by jrperritt** [comment]
Thank you. I also just remembered that I forgot the documentation for it; sorry about that.

**Comment by jtopjian** [comment]
@jrperritt No problem.

So the good news is that this works in my environment. But it needs a few fixes. Just doing a quick test:

1. I coincidentally had `example.com.` in my environment, so the test initially failed. The testing zone name should probably be randomly generated. Maybe using the `random_pet` resource as a generator.
2. `type` needs to be Computed.
3. There might be a timing issue with waiting for the zone to delete. The basic test fails because the zone still exists, but by the time it completes and I check Designate, it's gone.

I'm happy to take this over, but the soonest I'll be able to get to it is this weekend. Let me know if you'd like to continue at it, just so we're not duplicating work. :)

**Comment by jrperritt** [comment]
Ah, OK, thanks for testing. If I have time today, I'll try to fix my environment so that I can run the tests. If I can test it, I'll gladly finish it. I'll post back here later today on any progress (or lack of it).

**Comment by jrperritt** [comment]
@jtopjian Feel free to take over this PR . I couldn't get my environment's issues resolved.

**Comment by jrperritt** [comment]
@jtopjian I should mention that if you can't get to this today, it's not a problem; I'll pick it back up on Monday. Completing this (`zones`) and DNS `records` are a priority for me, so I'll be working on them until they're complete.

**Comment by jtopjian** [comment]
@jrperritt I'll be finishing this up either today or tomorrow morning. If you want to get a jump on `recordsets`, I can also look at getting that tested or taking over the test validation part. :)

**Comment by jrperritt** [comment]
> If you want to get a jump on recordsets, I can also look at getting that tested or taking over the test validation part.

Yes, I'll be starting them tomorrow. I'll also likely be destroying the current AIO deployment I have and running your terraform deploy script, since we know that works. Hopefully, that will enable me to run the tests.

**Pull request closed without merging**
