### PR TITLE
Adding some needed references and updated a couple of passes

### PR DESCRIPTION
**Pull request by svanharmelen**
It seems I missed a few references causing the new pages to be excluded in the side bar and now have all the proper CSS classes assigned. Both should be fixed now so the pages are displayed correctly.

Next to that there were also some passes that needed to be updated to reflect the correct info/examples.

### CODE REVIEW

**Comment by svanharmelen** [comment]
@armon can you double check if this is complete now? And if so, update the website with this PR?

Thanks!

**Comment by armon** [comment]
@svanharmelen What do you want me to double check? Sorry if I'm being obtuse

**Comment by svanharmelen** [comment]
@armon :smiley: Well, as I missed a few references the first time (one in `_docs.scss` and one in `layouts/docs.erb`) preventing the CloudStack docs to show up properly, I wanted to make sure that now all needed refs are there so the docs can be shown correctly.

**Comment by mitchellh** [comment]
LGTM. Just run it locally to make sure it looks right. :)

**Pull request merged**
