### PR TITLE
config - configs: finish deprecation of the config package by removing the still-used code to configs

### PR DESCRIPTION
**Pull request by mildwonkey**
I didn't put any effort, not one single thought, into considering if there's a better home for these functions. Moving them took almost no effort so if there's someplace that makes more sense than `configs` I'll move 'em!

### CODE REVIEW

**Comment by mildwonkey** [comment]
`addrs.ResourceMode` worried me too! 

I'm not sure how deprecated the remaining functions are, to be honest, seeing how they are used in the `terraform` package. My concern was more if there's a better package for their forever home (the same thing happened when I removed the `state` package: the few remaining functions aren't going anywhere, and they got moved a couple of times before we were happy with where they landed).

**Comment by alisdair** [comment]
I got the impression that some of these are deprecated from their usage sites. For example: https://github.com/hashicorp/terraform/blob/f3566f413823bd8a42ca35282f2d6550aced12b1/terraform/resource.go#L181-L193

Not sure how much of this nice Terraform sweater will unravel if we keep pulling on that thread, though…

Even if that's true, "this is not a complete refactor" doesn't feel like a valid reason not to take this step forward, so my ✅ remains!

**Comment by apparentlymart** [comment]
Seeing this discussion here about the status of some of these still-apparently-used objects, I thought I'd belatedly add some extra context here in case it's interesting for future work:

`RawConfig`, `ResourceVariable` and `interpolationWalker` are both some remaining artifacts of the 0.11-and-earlier model of configuration that stuck around, I believe, only because the SDK was (possibly indirectly) depending on them. `ResourceVariable` and `interpolationWalker` together served as the glue between Terraform Core and HIL, and so as we switched to HCL 2 they were replaced by [the `lang.Eval*` family of functions](https://github.com/hashicorp/terraform/blob/7032e651a803c4fcfd3b8bf3a486ed7da079d86c/lang/eval.go), working with some other parts of the `lang` package.

The SDK now has its own copies of the parts from `hashicorp/terraform` it formally depended on, and so I think it should be okay now to delete these legacy things along with any functions that are referring to them. However, I do agree that it's best to save that for a separate changeset because it involves getting into the dead code of the main `terraform` package, which is much more time-consuming to distinguish from the still-live code than to remove the entirely-deprecated `config` package.

**Comment by apparentlymart** [comment]
Out of some curiosity I went to take a look at what is still using these in `terraform`, and was reminded that during the 0.12 work we preserved some of the existing integration tests by shimming their old-style provider mocks to the new API, and those shims depend _some parts_ of the legacy API. That means we can't just remove these things entirely without updating lots of tests. I have a feeling that it's possible to carve out all but a minimal subset of existing methods of `terraform.ResourceConfig` and thus hopefully remove all of the references to these legacy interpolation codepaths (because the test shimming happens _after_ new-style evaluation already completed anyway), but even so that'll likely require some careful analysis of the legacy codepaths to see what makes sense to remove.

**Pull request merged**
