### PR TITLE
website: List providers vertically instead of horizontally

### PR DESCRIPTION
**Pull request by nfagerlund**
Right now, the master list of all providers uses a table to get a multi-column effect. 

- IMO, alphebetizing things horizontally like that makes it real hard to find what I'm looking for; it's much easier when things are vertical, the way indexes and tables of contents are always laid out in books. 
- Wow, this table looks like a huge pain to maintain every time we add a new provider. @cgriggs01, I'm seeing your name in here a lot; are we really just updating these rows by hand? 

Anyway, how about this instead? It doesn't have the cute stripes, but maybe we could add that somehow. 

image

### CODE REVIEW

**Comment by cgriggs01** [comment]
Yes Yes! Please and thank you Nick!

LGTM!

**Comment by cgriggs01** [comment]
BTW, I'll role these changes into the other provider listing pages.

**Comment by nfagerlund** [comment]
@cgriggs01 oh! I didn't realize there was also a table in the community-index page also. I've got the `s/etc/g`'s already in my history, I can just hit that one while I'm in there. It looks like none of the others need it, right? Or am I missing another one.

**Comment by cgriggs01** [comment]
The other provider "type" pages don't require it. But it would keep things consistent 

I'd be fine with just making the changes to this index page and the community page!

**Comment by nfagerlund** [comment]
Good point — I'll leave them single-column but style them the same way.

**Comment by topfunky** [comment]
I like it! Visually scanning the vertical list is much easier.

**Pull request merged**
