### PR TITLE
Add vsphere virtual machine migration (Fixes #7008)

### LINKED ISSUE #7008: Upgrading to v0.6.16 will delete and rebuild all vSphere hosts
Upgraded to `Terraform v0.6.16` .  Changelog mentions:
provider/vsphere: Add skip_customization option to vsphere_virtual_machine resources (#6355)

All of the resources of this vsphere  are showing:
```
 skip_customization:                     "" => "false" (forces new resource)
```
even explicitly setting `skip_customization = ""` doesn't help.   All of the servers will be delete and rebuild -- data loss.

### PR DESCRIPTION
**Pull request by markpeek**
Fixes vsphere virtual machine migration issues with disk controller_type and skip_customization.

### CODE REVIEW

**Comment by markpeek** [comment]
@chrislovecnm @dkalleg @thetuxkeeper please review this migration change

**Comment by stack72** [comment]
LGTM! Nice fix here :)

**Comment by thetuxkeeper** [comment]
Looks good!
Nice feature you're using. Will keep that in mind if I change something that needs state migration (like the one you fixed :) ).
Just one question. What if we had a new version "2" (or let's say "10" in a year or two :) ), what would you have to change? Is the migration function called for each version or only once?
If only once, is it possible to prepare it for multiple version upgrades/migrations? Something like 
```
while schema_version < target_version 
{
    migrate(current_version, current_version+1)
}
```
I think all at once would be too much at some time in the future, so my idea would be to do it step by step from one version to the next until we reach the latest one.
What do you think?

**Comment by chrislovecnm** [comment]
@markpeek thanks for the work!!  

@thetuxkeeper you have time to run the tests?  Otherwise let me know, and I will run them this eveningish :P

**Comment by markpeek** [comment]
@thetuxkeeper Here's an [example](https://github.com/hashicorp/terraform/blob/master/builtin/providers/google/resource_compute_instance_migrate.go#L13) on how it is done for the Google Compute Instance. Note the fallthrough between the cases in the switch statement.

**Comment by thetuxkeeper** [comment]
@markpeek : ah, I see. Thanks for the example, didn't know that there's such a statement :)
@chrislovecnm : not today, I'll let them run tomorrow, won't hurt if we both let them run. :)

**Pull request merged**
