### PR TITLE
core: Add `terraform state rm` command

### LINKED ISSUE #8060: docs for state CLI link to rm command, which doesn't exist
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. visit https://www.terraform.io/docs/commands/state/index.html
2. observe a link to the subcommand `rm` https://www.terraform.io/docs/commands/state/rm.html
3. select `rm`

### Expected Behavior
The link should work.

### Actual Behavior
404 Not Found

### PR DESCRIPTION
**Pull request by jen20**
This was previously merged in #5953, however was lost at some point during the Terraform 0.7 feature branch merge. This has resulted in a variety of issues and pull requests, so this pull request fixes #8060 and fixes #8088.

### CODE REVIEW

**Comment by jen20** [comment]
cc @phinze, @stack72.

**Comment by jen20** [comment]
Also fixes #8066.

**Comment by phinze** [comment]
@jen20 build failing, maybe a bad merge?

**Comment by jen20** [comment]
This should be better, fixing up the merge conflicts left us without a trailing `,`.

**Comment by stack72** [comment]
```
# github.com/hashicorp/terraform/command
command/state_test.go:11: testStateBackups redeclared in this block
	previous declaration at command/state_rm_test.go:93
```

**Comment by jen20** [comment]
8th time should be the charm...

**Comment by jen20** [comment]
Thanks for fixing this up @stack72, I swear it built here but apparently not...

**Pull request merged**
