### PR TITLE
Chef node import

### PR DESCRIPTION
**Pull request by apetitbois**
This is to resolve issue #13813

### CODE REVIEW

**Comment by stack72** [comment]
Hi @apetitbois 

Please can you add an acceptance test for this and then add the import section to the chef_node documentation page?

thanks

Paul

**Comment by apetitbois** [comment]
Updated the documentation and added acc testing

**Comment by stack72** [comment]
Hi @apetitbois 

Thanks for the work to add the test and documentation. Unfortunately, the test doesn't pass:

```
% make testacc TEST=./builtin/providers/chef                                                                                  ✭
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/04/21 12:39:29 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/chef -v  -timeout 120m
=== RUN   TestAccChefNode_importBasic
--- FAIL: TestAccChefNode_importBasic (3.01s)
	testing.go:280: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

		(map[string]string) {
		}


		(map[string]string) (len=4) {
		 (string) (len=25) "automatic_attributes_json": (string) (len=27) "{\"terraform_acc_test\":true}",
		 (string) (len=23) "default_attributes_json": (string) (len=27) "{\"terraform_acc_test\":true}",
		 (string) (len=22) "normal_attributes_json": (string) (len=27) "{\"terraform_acc_test\":true}",
		 (string) (len=24) "override_attributes_json": (string) (len=27) "{\"terraform_acc_test\":true}"
		}

=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccDataBagItem_basic
--- PASS: TestAccDataBagItem_basic (3.77s)
=== RUN   TestAccDataBag_basic
--- PASS: TestAccDataBag_basic (2.38s)
=== RUN   TestAccEnvironment_basic
--- PASS: TestAccEnvironment_basic (2.92s)
=== RUN   TestAccNode_basic
--- PASS: TestAccNode_basic (2.93s)
=== RUN   TestAccRole_basic
--- PASS: TestAccRole_basic (2.96s)
FAIL
exit status 1
FAIL	github.com/hashicorp/terraform/builtin/providers/chef	17.991s
make: *** [testacc] Error 1
```

Please let me know if you think this is something you need me to look at on your behalf

Thanks

Paul

**Comment by apetitbois** [comment]
I have added some ignored fields since they are not imported. Let me know if this works.

**Comment by apetitbois** [comment]
Hi @stack72 let me know if the scripts are going to be sufficient or if there is something additional I need to do.

Thanks.

**Comment by igorlg** [comment]
+1 to this PR, but shouldn't this be moved to the new Providers repo?

**Comment by apparentlymart** [comment]
Hello @apetitbois, and thanks for working on this!

As @igorlg noted, as part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it.

If you or someone else has the time and motivation to apply the same changes to [the `chef` provider repository](https://github.com/terraform-providers/terraform-provider-chef) and open a new PR there, maintainers of that provider may be able to review it.

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Pull request closed without merging**
