### PR TITLE
block device support for launch configurations

### PR DESCRIPTION
**Pull request by phinze**
With my tweaks

### CODE REVIEW

**Comment by phinze** [comment]
Same as #1271 with a few fixes. Acceptance tests passing. @jwaldrip and @pmoust does this work okay in your envs?

**Comment by jwaldrip** [comment]
Looks good to me as well.

**Comment by jwaldrip** [comment]
@pmoust does it look okay on your end?

**Comment by jwaldrip** [comment]
Uh oh. @phinze looks like your last merge raised a conflict.

**Comment by phinze** [comment]
@jwaldrip yep - already fixing :wink:

**Comment by mitchellh** [comment]
LGTM

**Comment by pmoust** [comment]
Thanks guys, everything smooth

**Pull request merged**
