### PR TITLE
Added Group attribute to cloudstack instance resource

### PR DESCRIPTION
**Pull request by jefflaplante**
In our Cloudstack environment we make use of the group attribute. I noticed it was missing from the Terraform resource yet exists in the go-cloudstack library Terraform is using. This is simply an attribute addition so that the group may be specified in Terraform.

### CODE REVIEW

**Comment by svanharmelen** [comment]
@jefflaplante thanks for the PR!

If we add this attribute, I guess we also need to read back the group a VM belongs so we can make sure TF will keep us in the desired state if anything changes. And also we should be able to update the group if we want it to change right?

Lastly it would be great if you could also add a line to the docs to describe this new attribute. If need help with all this, then just let me know!

**Comment by jefflaplante** [comment]
@svanharmelen Thanks for looking at my PR. I've added to the docs for this attribute and also augmented the read and update functions to support the group attribute.

**Comment by svanharmelen** [comment]
@jefflaplante looks good! One more question... Does that API need the group name, of the group ID?

And could you rebase the PR so it can be merged? Thx!

**Comment by svanharmelen** [comment]
@jefflaplante if you have time to answer that last question and do a rebase, I guess we can land this one so it ends up in the coming 0.6.15 release...

**Comment by svanharmelen** [comment]
@jefflaplante wanted to move forward with this one so checked the expected input which was indeed only accepting a group name and not also the ID. So since that one was OK, I went along and fixed your merge conflicts in order to be able to merge your commits...

So all in done and it will be in the next TF release :wink: Thanks!

**Comment by jefflaplante** [comment]
Thanks @svanharmelen! I got a bit bogged down in some other work. I appreciate you merging my commits. :)

**Pull request merged**
