### PR TITLE
ISSUE-10272 Lets not look at the requestor id.

### PR DESCRIPTION
**Pull request by grayaii**
This is to fix: https://github.com/hashicorp/terraform/issues/10272

Copied from that link:
I can't find (nor can I remember) why RequesterId was even added here (most likely as an extra safety net to make sure we don't delete the wrong ENI), but deleteLingeringLambdaENIs only gets called when resourceAwsSecurityGroupDelete is called, and the filters are "security group-id" and "description", so it should be "good enough". I still don't know who added "awslambda_" to the requestor-id (terraform? or AWS?), but I removed that filter and things seem to be working fine.

### CODE REVIEW

**Comment by grayaii** [comment]
@gposton , @radeksimko , can you guys comment on this?

**Comment by gozer** [comment]
For reference, here is what such an ENI looks like right now:

```json
{
            "Status": "in-use", 
            "MacAddress": "00:XX:00:XX:00:XX", 
            "SourceDestCheck": true, 
            "VpcId": "vpc-xxxx", 
            "Description": "AWS Lambda VPC ENI: 4d30b479-eadf-4293-ad47-034ecbd3c3e5", 
            "NetworkInterfaceId": "eni-XXXXXX", 
            "PrivateIpAddresses": [
                {
                    "PrivateDnsName": "ip-x-x-x-x.us-west-2.compute.internal", 
                    "Primary": true, 
                    "PrivateIpAddress": "10.x.x.x"
                }
            ], 
            "RequesterManaged": false, 
            "Groups": [
                {
                    "GroupName": "xxx-admin-earzgwd5cfcepa6m6qeutegqgm", 
                    "GroupId": "sg-xxxx"
                }, 
            ], 
            "PrivateDnsName": "ip-xx-xx-xx-xx.us-west-2.compute.internal", 
            "AvailabilityZone": "us-west-2a", 
            "Attachment": {
                "Status": "attached", 
                "DeviceIndex": 1, 
                "AttachTime": "2017-02-10T14:36:03.000Z", 
                "DeleteOnTermination": false, 
                "AttachmentId": "eni-attach-xxxx", 
                "InstanceOwnerId": "aws-lambda"
            }, 
            "RequesterId": "AROAITGDG6GCK7DAPOMEW:<lambda-function-name>", 
            "Ipv6Addresses": [], 
            "SubnetId": "subnet-xx", 
            "OwnerId": "11111111", 
            "TagSet": [], 
            "PrivateIpAddress": "10.xx.xx.xx"
}
```

And as far as I can tell, *AROAITGDG6GCK7DAPOMEW* in this case, is the unique_id attribute of the aws_iam_role I have assigned to the lambda function.

Could it be possible that the requester-id is different when the Lambda function doesn't have an attached role ?

And for the UUID in the description, *4d30b479-eadf-4293-ad47-034ecbd3c3e5*, I can't find that anywhere.

**Comment by grayaii** [comment]
@gozer This PR would have caught that ENI for deletion because it matches the security group id AND description :)  I'm not sure if attached roles play a role in this.  Good point though. The only other "safety net" I see is trapping ""InstanceOwnerId": "aws-lambda"", but that may be overkill, just like I think requester-id is overkill.  I built terraform with this PR and I've had no problems so far building/destroying resources :)

**Comment by gposton** [comment]
@radeksimko, I authored the original PR here: https://github.com/hashicorp/terraform/pull/8033  The code being removed in the PR was an 'extra' check that was just a CMA safety measure, but is ultimately unnecessary.  I support this PR and would like to see it merged ASAP :)

**Comment by grayaii** [comment]
@radeksimko Any chance we can merge this in?  We've been having to compile patched versions of terraform with this fix for quite a while now.

**Comment by crossing** [comment]
I think the filter on description should be removed too. It should be enough to filter on the security group itself. Also `Description` is inherit unreliable field. Its content can change anytime.

**Comment by willejs** [comment]
@radeksimko can you review this please?

**Comment by willejs** [comment]
@stack72 could you take a peek please?

**Comment by kristinn** [comment]
Would be nice to get this fix merged.

**Comment by brikis98** [comment]
+1 on getting this merged. Can't really use Lambda in a VPC without it!

**Comment by radeksimko** [comment]
Hi folks,
sorry to keep you waiting here.

I took some time to read the thread and related data, thanks @gozer for data about ENI - that's very useful in this context. As for the reasons why this started failing - it is possible that Amazon has just changed the format of the requestorId - I have observed tiny changes like this in the past as we run all acceptance tests nightly and sometimes tests start to fail without us changing any code and the root cause is change in the API.

@grayaii I added an acceptance test to cover this behaviour so that we have a chance to notice earlier in the future. I hope you don't mind me pushing that into your branch.

This PR looks good to me now. 👍

**Pull request merged**
