### PR TITLE
update to go1.10

### PR DESCRIPTION
**Pull request by jbardin**

### CODE REVIEW

**Comment by jbardin** [comment]
So apparently travis thinks `1.10` == `1.1` 😞

**Comment by jbardin** [comment]
Ah, it's a yaml thing. Version needs to be a string of course.

**Comment by apparentlymart** [comment]
Why is the `go vet` call also removed as part of this change?

(It'd be good to make that change more explicit in the commit message for future history reference...)

**Comment by jbardin** [comment]
The commit message says:

> Remove the vet target too, since vet is now always run with every test.

`vet` is now run as part of `go test`, I can update the commit with more info if you want

**Comment by apparentlymart** [comment]
Ugh I thought I read through all of the commit messages before I posted that but apparently GitHub's UI confused me. Sorry!

**Comment by apparentlymart** [comment]
We should perhaps mention in the changelog that we'll now allow the `HTTP_PROXY` environment variable to specify an `https:` URL, due to [the changes in `net/http`](https://golang.org/doc/go1.10#net/http). I remember someone bringing this up at some point in the past and maybe we even have an issue open for it somewhere.

**Comment by jbardin** [comment]
I have the provisioner script already open :)
Good point about the HTTPS proxy, I'll add it to the changelog.

**Pull request merged**
