### PR TITLE
Add grains_file parameter to salt-masterless provisioner

### PR DESCRIPTION
**Pull request by sevagh**
New parameter added in the Packer edition of this provisioner, copy it to Terraform.

### CODE REVIEW

**Comment by sevagh** [comment]
Been rebasing this for almost 2 months now. Any way I can help get it merged?

**Comment by sevagh** [comment]
Just some random thoughts about provisioners. Seems like there's some friction around enhancing or adding more provisioners to Terraform for the time being.

Now, this is way too ambitious (and I'm probably not the first to have thought about it), but what if one could find out a way to factor out the provisioners from both Packer and Terraform in a way that both projects could use them?

Then you could have a separate project space for Hashi-Provisioners, and have them leveraged by both Packer and Terraform :thinking:

**Comment by sevagh** [comment]
Is this going to be looked at or is part of it the hesitation of continuing to support rich provisioners in Terraform?

**Comment by apparentlymart** [comment]
Hi @sevagh! Sorry this was left so long without a response.

As I think you suspected, the Terraform team has some trouble supporting these provisioners because we lack in-house expertise to review and test them. While we do appreciate the work put in to this provisioner, it's tricky when a component has only one maintainer and so there's no-one else with enough context to review or merge changes by that maintainer.

As a compromise on some other provisioner requests we've suggested that if some other users of the provisioner are able to confirm the functionality and give feedback on it then that can increase our confidence level enough to merge, assuming that the change fits within the intended scope of Terraform's provisioner functionality, fits the usual coding style, etc.

At this time we have no immediate plans to support shared provisioners between Packer and Terraform, mainly because we lack the resources to invest in the design and implementation of such a capability. While provisioners are conceptually similar between Packer and Terraform, they differ in a number of important details that make such a design non-trivial.

If you'd still like to move forward with this and can get one or two users to try it out with their systems then I'm happy to help get this in. However, I know that we missed replying to this for a long time, and so I will totally understand if you no longer have the time or motivation to work on it.

At some point in the future we may support auto-installation of provisioners maintained outside of Terraform, to allow them to have their own release lifecycles just like providers now do. Unfortunately that work has been hard to prioritize due to the relatively small number of provisioners and that they tend to quite quickly reach the point of being "done" and require no further maintenance, assuming we're able to get them to that point. I apologize for the limitations of our current process.

**Comment by dawidmalina** [comment]
@sevagh, @apparentlymart I would also love this feature in terraform. Is it possible to move back on this topic?

If needed I can validate this change on my own and give feedback.

**Pull request closed without merging**
