### PR TITLE
provider/aws: improve redshift cluster validation

### PR DESCRIPTION
**Pull request by netjunki**
Encountered the following two errors while working with redshift earlier today:

     * aws_redshift_cluster.redshift-cluster: InvalidParameterValue: Only lowercase Database names are supported.
    status code: 400, request id: 15b75510-fdd0-11e6-9100-013cfc7b1aeb

And:

    * aws_redshift_cluster.redshift-cluster: InvalidParameterValue: The parameter MasterUserPassword is not a valid password. Only printable ASCII characters except for '/', '@', '"', ' ', '', ''' may be used.

This PR modified the existing validation for the db name and password to catch the above errors during terraform plan instead of terraform apply.

### CODE REVIEW

**Comment by stack72** [comment]
Hi @netjunki 

Thanks for the work here - this build fails i'm afraid - did you update the tests associated with these validation functions?

Thanks

Paul

**Comment by netjunki** [comment]
haha... was working on another tweak to exercise the other new test case for the invalid password characters. will make a new PR for that. :-)

**Comment by stack72** [comment]
sorry! Yes, please do make a separate PR for it :)

**Comment by netjunki** [comment]
@stack72 #12359 has the correctly updated test.

**Pull request merged**
