### PR TITLE
add versioning / snapshot for azure backend state file

### PR DESCRIPTION
**Pull request by rahdjoudj**
Based on @pmarques [PR](https://github.com/hashicorp/terraform/pull/18512)
I've used it and it's a life saver.

Somehow I had an issue where helm_release disappeared ... there is no import yet ...
Snapshot of the remote state file would have been great last night :)

### CODE REVIEW

**Comment by stephennancekivell** [comment]
This relates to https://github.com/hashicorp/terraform/issues/18284

**Comment by DeanPH** [comment]
Any progress on this? Will it be included in the next release?

**Comment by jomeier** [comment]
This one would be crucial for our application. Will it be included in the next release :-) ?

**Comment by pkleimann** [comment]
We would also appreciate this feature. Is it planned for the next release?

**Comment by schlbra** [comment]
@tombuildsstuff Any chance this could be added to an upcoming release?

**Comment by tombuildsstuff** [comment]
👋 hey @rahdjoudj 

Thanks for this PR - apologies for the delayed review here!

This PR (and it's commits) been superseded into #24069 which includes these changes (and is now rebased on top of Giovanni, the new Storage SDK we're using to communicate with Azure) - as such I hope you don't mind but I'm going to close this PR in favour of #24069.

Thanks!

**Pull request closed without merging**
