### PR TITLE
Add support for using a GCP Image Family

### PR DESCRIPTION
**Pull request by cblecker**
Please excuse any mistakes in this as it's my first attempt at a PR for Terraform :)

When I dug into #7562 a bit more, it looked easier than I initially thought to use the image family api instead of the regular image api.

I haven't updated the documentation or anything yet, but I wanted to ensure I'm on the right track. I tested this with my terraform config, and it seemed to work as expected.

### CODE REVIEW

**Comment by cblecker** [comment]
I figured out how to run the acceptance tests, saw they weren't working properly, and then fixed them. I also had to modify the test for these image families, as Google doesn't have/support a Debian 7 image family.

```
$ make testacc TEST=./builtin/providers/google TESTARGS='-run=TestAccComputeInstance_basic[1-5]'
==> Checking that code complies with gofmt requirements...
/opt/gopath/bin/stringer
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/08/09 20:56:01 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/google -v -run=TestAccComputeInstance_basic[1-5] -timeout 120m
=== RUN   TestAccComputeInstance_basic1
--- PASS: TestAccComputeInstance_basic1 (82.49s)
=== RUN   TestAccComputeInstance_basic2
--- PASS: TestAccComputeInstance_basic2 (72.63s)
=== RUN   TestAccComputeInstance_basic3
--- PASS: TestAccComputeInstance_basic3 (90.19s)
=== RUN   TestAccComputeInstance_basic4
--- PASS: TestAccComputeInstance_basic4 (72.50s)
=== RUN   TestAccComputeInstance_basic5
--- PASS: TestAccComputeInstance_basic5 (72.59s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/google	390.406s
```

Side note: Should the other acceptance tests in this project be updated to use Debian 8 too?

**Comment by cblecker** [comment]
And now updated with some documentation. Hopefully this checks all the boxes!

**Comment by cblecker** [comment]
I've squashed the commits and rebased. Removing WIP tag as I think this might be ready for review/merge.

**Comment by stack72** [comment]
@evandbrown would love your thoughts on this PR :)

**Comment by evandbrown** [comment]
This is awesome. Thanks, @cblecker!

Only one nit: mind adding a comment to the `resolveImage` func that lists ImageFamily as one of the possibilities?

After that, LGTM. Thanks for taking the time to contribute solid, useful stuff to the Google provider, Christoph!

**Comment by cblecker** [comment]
@evandbrown -- Updated the comments to be a bit more clear. Mind taking another look?

**Comment by evandbrown** [comment]
LGTM! @stack72, cool if push the merge button on this one? :)

**Comment by stack72** [comment]
done! Thanks @cblecker :)

**Comment by loliee** [comment]
awesome @cblecker !

**Pull request merged**
