### PR TITLE
Fix printf verb %s of wrong type

### PR DESCRIPTION
**Pull request by ojongerius**
Fixes:

```
make test TEST=./builtin/providers/aws
go generate ./...                                                               TF_ACC= go test ./builtin/providers/aws  -timeout=30s -parallel=4               ok      github.com/hashicorp/terraform.dev/builtin/providers/aws    0.014s      go tool vet -asmdecl -atomic -bool -buildtags -copylocks -methods -nilfunc -printf -rangeloops -shift -structtags -unsafeptr .
builtin/providers/aws/resource_aws_launch_configuration.go:436: arg describeOpts for printf verb %s of wrong type: github.com/aws/aws-sdk-go/service/autoscaling.DescribeLaunchConfigurationsInput

Vet found suspicious constructs. Please check the reported constructs
and fix them if necessary before submitting the code for review.
make[1]: *** [vet] Error 1
make: *** [test] Error 2
```

### CODE REVIEW

**Comment by radeksimko** [comment]
Thanks for noticing!
I wonder why it has not been caught by Travis. My local `go tool vet` doesn't report that either.

Either way we recently started using `awsutils.StringValue` which allows us to make these objects full of pointers actually useful in logs.
See https://github.com/hashicorp/terraform/blob/8e23607b670005883fe3da6f0bd563fa1a07dd8f/builtin/providers/aws/resource_aws_flow_log.go#L97

Do you think you could update the PR?

**Comment by cbednarski** [comment]
@radeksimko I think maybe we should use `go vet` instead of `go tool vet`. I just changed this in packer because `go tool vet` wasn't catching anything.

**Comment by ojongerius** [comment]
@radeksimko done! Convenient function :smile:

**Comment by radeksimko** [comment]
@cbednarski The problem with `go vet` is that you cannot pass any special flags. The reason you may be getting more violations is because it's checking everything, not just those flags. I believe you'd get the same result with `go tool vet -all`.

The reason it's not reporting this specific case and won't report any other similar cases is because the _String-ifi-cation_ is already happening inside the AWS library - i.e. these `type`s have each their own `String` functions:

https://github.com/aws/aws-sdk-go/blame/master/service/autoscaling/api.go#L2190-L2193

See https://github.com/aws/aws-sdk-go/pull/299

@ojongerius I apologise for not doing the research before jumping the gun here :no_mouth: , but I think this PR is a bit superfluous now. The reason you may still see these violations being reported is because you have an old version of `aws/aws-sdk-go`. Can you just try to `make updatedeps` and confirm that you're getting none? Also I noticed your fork is old, so you may want to update that too, e.g. if you have upstream repo as git remote named `upstream` and your fork as `origin`:
```
git pull upstream master
git push origin master
make updatedeps
```

**Comment by ojongerius** [comment]
Right. Sorry about that. Updating dependencies made the error go away. Closing this one.

**Pull request closed without merging**
