### PR TITLE
provider/aws Implement username updates properly for aws-sdk-go

### PR DESCRIPTION
**Pull request by GrayCoder**
This should solve #2818

### CODE REVIEW

**Comment by catsby** [comment]
Does this also fix #2761 ?

**Comment by catsby** [comment]
Any thoughts on that, @GrayCoder ?

**Comment by GrayCoder** [comment]
@catsby the 2 PRs ( This one and #3237 ) related to this that I have open solve #2761 for groups and users, but do not solve it for roles unfortunately. The AWS api doesn't seem to provide the same hooks to update roles... so I found a fix that would close #2761

**Comment by catsby** [comment]
@GrayCoder hey sorry for the delay here. Do you by chance have a config that demonstrates for me what this is fixing? I _believe_ that it's good and necessary, but I'm not following when this situation pops up

**Comment by GrayCoder** [comment]
@catsby This situation pops up when you rename a user because the API requires that you specifically call the Update functions on users that are in groups instead of just deleting and recreating the user, which is what the current code does.

Without proper update support, one must manually remove the user from any groups they're in when they want to change the user's name (this often happens unexpectedly during an apply). One must also remove any managed policies attached to the user otherwise the same set of events (api errors) happen.

**Comment by catsby** [comment]
Ah, got it. Thanks @GrayCoder , this looks good to me!

**Pull request merged**
