### PR TITLE
Vendored aws-sdk-go SFN service

### PR DESCRIPTION
**Pull request by Ninir**
This vendors the `Step Functions` (SFN) service.

First step for Step Functions: https://github.com/hashicorp/terraform/issues/10652

### CODE REVIEW

**Comment by stack72** [comment]
Hi @Ninir 

Thanks for this - I am going to wait till after the 0.8.3 release to merge this if that's ok? It will only be a day or 2 max

Thanks

Paul

**Comment by Ninir** [comment]
Hi Paul,

Sure, seems perfect. Thank you 🙂

**Comment by kfloz** [comment]
Brilliant - to be clear does this mean step functions is supported in the next release?

**Comment by Ninir** [comment]
Hi @kfloz,

This means that the codebase is aware of the AWS API.
The second step will be to implement related resources, which will come afterwards!

**Comment by stack72** [comment]
Thanks for waiting @Ninir

**Pull request merged**
