### PR TITLE
aws/provider: Fixes issue for aws_lb_ssl_negotiation_policy of already deleted ELB

### LINKED ISSUE #11260: Error deleting SSL negotiation policy - There is no ACTIVE Load Balancer
### Terraform Version
```
Terraform v0.8.2
```

### Affected Resource(s)
- `aws_lb_ssl_negotiation_policy`
- `aws_elb`

### Terraform Configuration Files
I created module for ELB. It creates `aws_elb` with pretty standard configuration plus `aws_lb_ssl_negotiation_policy`
```hcl
resource "aws_elb" "elb" {
  name = "tf-${var.service_name}-${var.environment_name}"
  ...
}

## restricitive SSL Policy to accept only TLS 1.2 strict security
resource "aws_lb_ssl_negotiation_policy" "default_elb_ssl_policy" {
  name = "tf-${var.service_name}-${var.environment_name}-default-elb-ssl-policy"
  load_balancer = "${aws_elb.elb.id}"
  lb_port = 443

  attribute {
    name = "Protocol-SSLv3"
    value = "false"
  }

  attribute {
    name = "Protocol-TLSv1"
    value = "false"
  }

  attribute {
    name = "Protocol-TLSv1.1"
    value = "false"
  }
  ...
}
```
### Steps to Reproduce
1. Create 2 ELBs (just example of idea)
```hcl
module "site1-elb" {
  source = "modules/elb"
  ...
}

module "site2-elb" {
  source = "modules/elb"
  ...
}
```
and `terraform apply`
2. Two ELBs successfully created
3. Later i need to shutdown one of ELB. I comment the 1st module
```hcl
/*
module "site1-elb" {
  source = "modules/elb"
  ...
}
*/
```
and `terraform apply`

### Expected Behavior
TF removes 1st ELB and complete with success response

### Actual Behavior
```
Error applying plan:

1 error(s) occurred:

* aws_lb_ssl_negotiation_policy.default_elb_ssl_policy: Error deleting SSL negotiation policy tf-wpdev-1-demo-service-stg:443:tf-wpdev-1-demo-service-stg-default-elb-ssl-policy: LoadBalancerNotFound: There is no ACTIVE Load Balancer named 'tf-wpdev-1-demo-service-stg'
        status code: 400, request id: 98256965-dd66-11e6-9597-e9b691191b98
```
I reviewed execution plan 
```
...
module.wpdev-1.elb.aws_lb_ssl_negotiation_policy.default_elb_ssl_policy: Refreshing state... (ID: tf-wpdev-1-demo-service-stg:443:tf-wpdev-1-demo-service-stg-default-elb-ssl-policy)
...
module.wpdev-1.elb.aws_security_group.elb: Refreshing state... (ID: sg-bfda0xxx)
...
module.wpdev-1.elb.aws_cloudwatch_metric_alarm.elb_unhealthy_hosts: Destroying...
module.wpdev-1.elb.aws_security_group.elb: Destroying...
module.wpdev-1.elb.aws_cloudwatch_metric_alarm.elb_zero_healthy_hosts: Destroying...
module.wpdev-1.elb.aws_lb_ssl_negotiation_policy.default_elb_ssl_policy: Destroying...
module.wpdev-1.elb.aws_elb.elb: Destroying...
module.wpdev-1.elb.aws_elb.elb: Destruction complete
module.wpdev-1.elb.aws_cloudwatch_metric_alarm.elb_zero_healthy_hosts: Destruction complete
module.wpdev-1.elb.aws_cloudwatch_metric_alarm.elb_unhealthy_hosts: Destruction complete
...
module.wpdev-1.elb.aws_security_group.elb: Still destroying... (10s elapsed)
module.wpdev-1.elb.aws_security_group.elb: Still destroying... (20s elapsed)
module.wpdev-1.elb.aws_security_group.elb: Still destroying... (30s elapsed)
module.wpdev-1.elb.aws_security_group.elb: Still destroying... (40s elapsed)
module.wpdev-1.elb.aws_security_group.elb: Still destroying... (50s elapsed)
module.wpdev-1.elb.aws_security_group.elb: Destruction complete
```
Looks like ELB is destroyed before `aws_lb_ssl_negotiation_policy` (at least i didn't find `Destruction complete` for it)

### PR DESCRIPTION
**Pull request by bclodius**
Fixes #11260

### CODE REVIEW

**Comment by stack72** [comment]
Hi @bclodius 

Thanks for the work on this - please can you add an acceptance test to show that this works as expected? Please feel free to shout if you need some guidance in this area

Thanks

Paul

**Comment by bclodius** [comment]
@stack72 certainly.  I will take a stab at this and let you know if I need some help.

**Comment by bclodius** [comment]
@stack72 when I comment c5b36c7 I am able to reproduce the issue.  Below is the test case i ran.

```
make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSLBSSLNegotiationPolicy_missingLB'
```

**Comment by stack72** [comment]
nice work @bclodius 

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSLBSSLNegotiationPolicy_'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/03/06 13:39:11 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSLBSSLNegotiationPolicy_ -timeout 120m
=== RUN   TestAccAWSLBSSLNegotiationPolicy_basic
--- PASS: TestAccAWSLBSSLNegotiationPolicy_basic (42.73s)
=== RUN   TestAccAWSLBSSLNegotiationPolicy_missingLB
--- PASS: TestAccAWSLBSSLNegotiationPolicy_missingLB (88.50s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	131.253s
```

LGTM!

**Comment by bclodius** [comment]
Thanks @stack72!!!

**Pull request merged**
