### PR TITLE
provider/aws: Enabled Enhanced Monitoring for RDS

### PR DESCRIPTION
**Pull request by stack72**
As requested in: #4940

Test Results:

```
make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSDBInstance_enhancedMonitoring' 2>~/tf.log
==> Checking that code complies with gofmt requirements...
/Users/stacko/Code/go/bin/stringer
GO15VENDOREXPERIMENT=1 go generate $(GO15VENDOREXPERIMENT=1 go list ./... | grep -v /vendor/)
TF_ACC=1 GO15VENDOREXPERIMENT=1 go test ./builtin/providers/aws -v -run=TestAccAWSDBInstance_enhancedMonitoring -timeout 120m
=== RUN   TestAccAWSDBInstance_enhancedMonitoring
--- PASS: TestAccAWSDBInstance_enhancedMonitoring (1202.80s)
PASS
exit status 1
FAIL	github.com/hashicorp/terraform/builtin/providers/aws	1202.823s
```

### CODE REVIEW

**Comment by stack72** [comment]
I have had to make changes to policy attachment to make sure that a specific IAM is available before I create the db_instance. The tests still work as follows:

```
make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSPolicyAttachment' 2>~/tf.log
==> Checking that code complies with gofmt requirements...
/Users/stacko/Code/go/bin/stringer
GO15VENDOREXPERIMENT=1 go generate $(GO15VENDOREXPERIMENT=1 go list ./... | grep -v /vendor/)
TF_ACC=1 GO15VENDOREXPERIMENT=1 go test ./builtin/providers/aws -v -run=TestAccAWSPolicyAttachment -timeout 120m
=== RUN   TestAccAWSPolicyAttachment_basic
--- PASS: TestAccAWSPolicyAttachment_basic (17.70s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	17.715s
```

**Comment by deanmraz** [comment]
When will this get released?

**Comment by jen20** [comment]
LGTM.

**Comment by stack72** [comment]
@deanmraz - merging now :)

**Comment by deanmraz** [comment]
sweet! @stack72

**Pull request merged**
