### PR TITLE
adding wildcard interpolation

### PR DESCRIPTION
**Pull request by mzupan**
This adds a wildcard search for lookup() function

Usage

```
variable "cidr" {
  default = {
    prod = "10.10.0.0/16"
    "*" = "10.11.0.0/16"
  }
}
```

```
resource "aws_vpc" "main" {
  cidr_block = "${lookup(var.cidr, var.env)}"
  enable_dns_hostnames = true
  enable_dns_support = true
}
```

Example output

```
$ ./terraform plan -var 'env=prod'
Refreshing Terraform state prior to plan...

+ aws_vpc.main
    cidr_block:                "" => "10.10.0.0/16"
    default_network_acl_id:    "" => "<computed>"
    default_security_group_id: "" => "<computed>"
    dhcp_options_id:           "" => "<computed>"
    enable_classiclink:        "" => "<computed>"
    enable_dns_hostnames:      "" => "1"
    enable_dns_support:        "" => "1"
    instance_tenancy:          "" => "<computed>"
    main_route_table_id:       "" => "<computed>"

````

Then a search on the wildcard

```
$ ./terraform plan -var 'env=dev'

+ aws_vpc.main
    cidr_block:                "" => "10.11.0.0/16"
    default_network_acl_id:    "" => "<computed>"
    default_security_group_id: "" => "<computed>"
    dhcp_options_id:           "" => "<computed>"
    enable_classiclink:        "" => "<computed>"
    enable_dns_hostnames:      "" => "1"
    enable_dns_support:        "" => "1"
    instance_tenancy:          "" => "<computed>"
    main_route_table_id:       "" => "<computed>"

```

I think the test I included passes.. But feel free to implement this as you see. This references #6284 for use in 0.7

If this isn't the correct branch let me know.

### CODE REVIEW

**Comment by sl1pm4t** [comment]
This will be a useful addition.

**Comment by gozer** [comment]
@jen20 PR just closed, no merges? Curious as to what is going on with this much desired feature?

**Comment by astlock** [comment]
+1 to the previous comment!

**Comment by astlock** [comment]
Seems I found a solution, and correct me I am wrong but there is no need in any additional PR to use "wildcard interpolation".
Usage:

`variable "amis" {
  default = {
    "barto"  = "ami-lolol"
    "*" = "default-ami"
  }
}`

**Comment by mzupan** [comment]
It just got implemented differently in 0.7

`lookup(var.amis, var.env, 'Default-AMI')`

**Pull request closed without merging**
