### PR TITLE
Literals with escaped interpolations work

### LINKED ISSUE #2909: No way to escape a dollar in template variable.
Terraform 0.6.1

In a template variable section, I need to define a variable like this:

```
resource "template_file" "foo_template" {
    filename = "foo.yaml"
    vars     = {
        TF_FOO = "bar-${baz}"
    }
}
```

That is - literally, where I have ${TF_FOO} in my foo.yaml, I want it replaced, literally with bar-${baz}

Now this obviously doesn't work, because terraform treats ${baz} as a variable and rightly says it doesn't exist.

So then I tried

```
TF_FOO="bar-$${baz}"
```

No luck - this gets written into the template as ... literally bar-$${baz}

So then I tried

```
TF_FOO="bar-\${baz}"
```

No luck - terraform treats this as a variable again.

There is no way to get terraform to write a literal ${baz} as a variable replacement in a terraform file.

### PR DESCRIPTION
**Pull request by mitchellh**
Fixes #2909 

If you had a literal with an escaped interpolation such as `foo-$${bar}` it was not properly turning into `foo-${bar}`. This fixes that. 

The fix is simple: we had an optimization where if after we parsed the string for interpolations we found only a literal we assumed there was nothing and skipped it. We now check to make sure the result is also the same string and if not, we still evaluate the string.

### CODE REVIEW

**Comment by mitchellh** [comment]
Real failing tests :( I'll look

**Comment by mitchellh** [comment]
Fixed tests

**Comment by apparentlymart** [comment]
LGTM!

Thanks for fixing this... it was messing with me just last week when I was trying to use Rundeck interpolations, which happen to use the same syntax as Terraform, and it was really bugging me why the escaping sometimes worked and sometimes didn't. Nice to see that there's a reasonable explanation for that. :smile:

**Comment by phinze** [comment]
LGTM

**Comment by rkul** [comment]
Interpolation escaping also doesn't work for templates. If template contains $${var}, it renders into $${var}.
Simple workaround is to use replace func when rendering:
`${replace(template_file.config.rendered,"$$","$")}`

**Pull request merged**
