### PR TITLE
vSphere: refactor and support for DVS/DVPG

### PR DESCRIPTION
**Pull request by ChloeTigre**
This branch implements several changes.
# General

75% refactor of resource_vsphere_virtual_machine.go
Added typing to the virtual_machine code (type aliases to avoid confusion)
Support for DVS and DVPG.
# VMs

VM: Support for setting guest_id
NIC: Support for setting adapter_type
NIC: Support for NIC creation order (at initial VM creation)
Disk: Support for thick_lazy provisioning type
NIC: Support for updating Network Interfaces instead of recreating the VM
# Documentation

Added docs for the changes.
# How to help

Please help me by contributing tests.

### CODE REVIEW

**Comment by ChloeTigre** [comment]
This should become the new reference for vSphere in Terraform. The code base is simpler. There are shorter functions passing their parameters around and one can easily see how the big things work.

**Comment by chrislovecnm** [comment]
@ChloeTigre can you rebase, and I need to see the output of all of the unit tests on this refactor.  Large code change.  Will review when I have time.

**Comment by ChloeTigre** [comment]
Rebased on recent master and tests are passing.

**Comment by stack72** [comment]
ping @chrislovecnm - is this still something you want to review? I would like to see a close to this if possible

Thanks

Paul

**Comment by ze42** [comment]
ping @stack72 @chrislovecnm 
Any news/comments about that PR?

**Comment by apparentlymart** [comment]
Hello @ChloeTigre, and thanks for working on this!

As part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it.

[The vSphere provider](https://github.com/terraform-providers/terraform-provider-vsphere) -- and, in particular, the virtual machine resource -- are currently in the process of being revamped somewhat, with the goal of supporting more of the available features. Unfortunately this means that to re-target this change to the new repository may require some restructuring :confounded:.

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Pull request closed without merging**
