### PR TITLE
provider/aws: Report the correct number of shards for Kinesis streams

### PR DESCRIPTION
**Pull request by Bowbaq**
This fixes (a small) part of #5352. Reporting the correct number of shards (ie. the number of open shards) at least allows to manually match in terraform whatever was set in AWS, preventing streams from being replaced and data lost.

### CODE REVIEW

**Comment by stack72** [comment]
Hi @Bowbaq,

Does this relate to longer running streams? There is currently a terraform acceptance test that creates a stream with a number of shards and checks that that number os shards is correct

Paul

**Comment by Bowbaq** [comment]
Shards are immutable. When a stream gets re-sharded, existing shards are
split or merged as needed. The resulting shards are "open" while the old
ones become "closed" (ie. the data is still available, but no new data can
be written). The only number of consequence for a stream's capacity is the
number of open shards.

Terraform doesn't support re-sharding so I'm guessing the acceptance test
didnt exercise this behavior.

**Comment by stack72** [comment]
Got it, so the test would be 

1. Create a stream with 1 shard
2. Update the stream to 2 shards

Old code = shards would be 3 and TF would try and fix that

New code (your PR) = open shards are 2 are TF has no action

Right?

**Comment by Bowbaq** [comment]
Correct

**Comment by stack72** [comment]
Thanks @Bowbaq - trying to see if i can get a test in place for this now :)

**Comment by stack72** [comment]
This looks like it works as expected :) Thanks for the work @Bowbaq!

**Pull request merged**
