### PR TITLE
Make use of ComputedWhen in aws_s3_bucket_object

### PR DESCRIPTION
**Pull request by radeksimko**
At the moment if one tries to use `aws_s3_bucket_object` with versioning enabled on that bucket, it won't work quite as expected, because the `version_id` is updated after `apply`.

This limitation makes `aws_s3_bucket_object` not very handy when used in combination with `aws_lambda_function.s3_object_version` (mapped to `aws_s3_bucket_object.version_id`).

The full Lambda Function update cycle when used w/ `aws_s3_bucket_object` therefore requires two `apply` steps.

### CODE REVIEW

**Comment by phinze** [comment]
I think we can cover this behavior in a Lambda function acceptance test? If the update does not propagate across a single apply the "non empty plan after test step" check will fire.

**Comment by radeksimko** [comment]
Basically you mean removing the following 8 lines of code?
https://github.com/hashicorp/terraform/pull/5239/files#diff-bb5084fa21c8a7174fca0cc2119dc5c9R128

:wink: 

Once that PR is merged, I'll be happy to attach such _minus_ change to this PR.

**Comment by phinze** [comment]
Oh HA! Sounds good. :smile:

**Comment by radeksimko** [comment]
@phinze Would you mind rebasing your branch, so I can update this PR?

**Comment by radeksimko** [comment]
Closing until `ComputedWhen` is actually supported - then we can reimplement.

WIP is at https://github.com/hashicorp/terraform/pull/4846 but it might take more effort to finish.

**Comment by thomschlereth** [comment]
Any updates on this?

**Pull request closed without merging**
