### PR TITLE
Triton test updates

### PR DESCRIPTION
**Pull request by catsby**
Should fix failing Triton tests

- https://travis-ci.org/hashicorp/terraform/builds/143814431

There are still a few fixes need but most of the tests should run now and fail with actual error messages

### CODE REVIEW

**Comment by phinze** [comment]
@catsby aws_db_instance change snuck in here too it seems - intentional?

**Comment by catsby** [comment]
fail

**Comment by catsby** [comment]
@phinze fixed, my bad

**Comment by jen20** [comment]
LGTM

**Pull request merged**
