### PR TITLE
[WIP] provider/openstack: Add Region to Provider

### PR DESCRIPTION
**Pull request by jtopjian**
This commit adds the region argument to the OpenStack provider.
This enables a user to specify the region once at the provider-level
and have all resources within that provider be built in that region.

If a resource-level region was specified, it is still recognized
and will override the provider-level region.

For #13625

### CODE REVIEW

**Comment by mcanevet** [comment]
@jtopjian at first glance it looks OK, but whe I try this on an existing project a plan says me that it will force a new resource:

```
-/+ openstack_networking_port_v2.port
    ...
    region:                  "RegionOne" => "" (forces new resource)
    ...
```

This is weird because when running in debug mode I get this:
```shell
2017/05/23 09:45:39 [DEBUG] plugin: terraform-provider-openstack: 2017/05/23 09:45:39 [DEBUG] OpenStack Region is: RegionOne
```

**Comment by jtopjian** [comment]
@mcanevet OK, now the fun begins :)

Did you get that error when you added `region` to the provider and removed it from the resource?

**Comment by jtopjian** [comment]
@mcanevet Give the latest commit a try, but be careful. It's not triggering a "forces new resource" when I think it should be triggered... but it seems to work correctly.

This latest commit is moving the `OS_REGION_NAME` to the provider `region`. As per our previous discussion, I was hesitant about doing that, but after a few different configurations, it does in fact look like the cleanest way of applying this.

I'm to try this out in a multi-region environment myself, but it might take me a few days to get to that.

**Comment by mcanevet** [comment]
@jtopjian looks like it works fine now, even with a multi-region environment.
I this you can merge this.

**Comment by jtopjian** [comment]
Nice! I'm glad it's working for you.

I still want to do more testing on it, plus there's a whole slew of doc changes to make. So hopefully it'll be ready soon. 

But I'm really glad you're able to use it without blowing up your environments -- thank you for taking the time to test this. :)

**Comment by jtopjian** [comment]
I haven't forgotten about this. I still need to do some testing on a few environments I have access to - I've just been pressed for time.

Also, 0.10 is coming up and I think this would be a better fit there. Lots of code being changed in this patch (although it's the same changes in each file). But a new release series is best for something like this.

**Comment by jtopjian** [comment]
This has been implemented in the new provider plugin.

**Pull request closed without merging**
