### PR TITLE
provider/openstack Add Distributed router support

### PR DESCRIPTION
**Pull request by Fodoj**
Please note that this PR depends on this https://github.com/rackspace/gophercloud/pull/525 to be merged.

### CODE REVIEW

**Comment by stack72** [comment]
Hi @Fodoj, please can you squash your commits on this one - this will help keep the git commit log clean

**Comment by jtopjian** [comment]
@Fodoj Thanks for this! Just a heads up that I'm currently traveling for work, so I might not get a chance to review this for a few days.

**Comment by Fodoj** [comment]
@stack72 done, thanks

**Comment by jtopjian** [comment]
Looks like https://github.com/rackspace/gophercloud/pull/525 was merged today! Can you trigger the Travis tests to run? 

Looks good to merge after that. :smile:

**Comment by Fodoj** [comment]
@jtopjian it's about pinning gophercloud version, right?

**Comment by jtopjian** [comment]
Right. You'll have to use [godep](https://github.com/tools/godep) to manage the versions, but I haven't been able to figure out how to do it cleanly. It looks like `GO15VENDOREXPERIMENT=1` (which is explained in the README) is used, but doing:

```shell
$ godep update github.com/rackspace/gophercloud
```

Just clobbers `vendor/github/rackspace/gophercloud` rather than update it.

@phinze @radeksimko I know you guys said you'll be putting docs together shortly. Any quick pointers on the above in the meantime?

**Comment by phinze** [comment]
Hi @jtopjian - sorry about the delay on those docs. In the meantime, I believe the target of `godep update` needs a `...` afterwards to capture all the packages in that dir for analysis. Give this a shot:

```
$ godep update github.com/rackspace/gophercloud/...
```

**Comment by jtopjian** [comment]
@phinze No problem at all! I totally understand this is a large change that was just implemented :)

I tried `...` and it had the same effect, however, I just realized that Godep is simply stripping out `_test.go` files. All other updates are correct. 

Is this intended behavior? The Godep README states that test files are not tracked, but they currently exist in `vendor`, so I just want to make sure.

**Comment by phinze** [comment]
@jtopjian interesting! The original contents of vendor were inadvertently captured with an older version of `godep` so that's entirely possible. Let me clean that discrepancy up in a separate PR so you don't have to deal with that noise.

**Comment by jtopjian** [comment]
@phinze sounds like an awesome plan! Thank you!

**Comment by Fodoj** [comment]
If I run `godep update` I get "Package (github.com/golang/protobuf/proto) not found

**Comment by jtopjian** [comment]
@Fodoj Here's what I ended up doing for #5131:

```shell
rm -rf ~/go/src/github.com/hashicorp/terraform
go get github.com/hashicorp/terraform
cd ~/go/src/github.com/hashicorp/terraform
git remote add jtopjian ...
git fetch jtopjian
git checkout --track jtopjian/...
git rebase -i master
export GO15VENDOREXPERIMENT=1
godep update github.com/rackspace/gophercloud
git status
git add .
git commit -m "provider/openstack: Updating Gophercloud Dependency"
```

I have no idea how correct that is... but I think it worked :)

**Comment by Fodoj** [comment]
@jtopjian ping

**Comment by jtopjian** [comment]
This looks good to me! Did you end up using the steps I listed? 

I'd like @phinze to do a quick review of the Godeps stuff since this will be the first for an OpenStack-related commit.

**Comment by Fodoj** [comment]
@jtopjian yes, your steps were mostly correct, though I also had to run `godep restore -v` to pull deps

**Comment by phinze** [comment]
Godeps diff LGTM!

**Pull request merged**
