### PR TITLE
Fix for GH-13660

### PR DESCRIPTION
**Pull request by brandontosch**
For issue #13660. Fixed logic to allow attaching disks to VMs using `vhd_uri` as the source. Also added a new test for attaching storage blobs to VMs since that was missing.

### CODE REVIEW

**Comment by pearcec** [comment]
So your fix only focuses on the data disk? I am working through a different issue on the os_disk.  Wondering should I combine with yours or keep to mine.  Thinking I should probably keep with mine.

**Comment by brandontosch** [comment]
Hi @pearcec 
This was specifically targeted at a bug that affected data disks. Which issue were you working on for os disks? I know there was also an issue with using storage image references with managed disks (#13932) that I was working here #13960. Is there another issue with os disks as well?

**Comment by pearcec** [comment]
@brandontosch I handled the issue independent of this one.  I ran into the same problem on a fix to attach os_disk.  I read through your code for the fix. Thanks. I believe we are good.

**Comment by nbering** [comment]
@pearcec Does that mean there's a fix applied somewhere? I need update a machine that has os disk set to Attach with a VHD. I don't mind checking out a branch, I already build from source locally.

**Comment by privatwolke** [comment]
Fix for this is to `brew switch terraform 0.9.2` -- may not be possible if your state was created by a later version of terraform. Please rebase and merge this PR! 🙏

**Comment by pearcec** [comment]
@nbering I fixed it for os_disk.  It was merged back in June.

**Comment by apparentlymart** [comment]
Hello @brandontosch, and thanks for working on this!

As part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it.

If you or someone else has the time and motivation to apply same changes to [the `azurerm` provider repository](https://github.com/terraform-providers/terraform-provider-azurerm) and open a new PR there, the maintainers of that provider should be able to review and merge it. The issue corresponding to this PR was already migrated as terraform-providers/terraform-provider-azurerm#62.

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Pull request closed without merging**
