### PR TITLE
Updated implementation of builtin PagerDuty provider.

### PR DESCRIPTION
**Pull request by dthagard**
* Added repeat_enabled for resource_pagerduty_escalation_policy.
* Added start_day_of_week for resource_pagerduty_schedule.
** Added placeholder commit for start_day_of_week in go-pagerduty vendor file while awaiting PR approval from PagerDuty.
* Added summary, incident_urgency_rule, support_hours, and scheduled_actions to resource_pagerduty_service.

### CODE REVIEW

**Comment by heimweh** [comment]
Hi @dthagard, thank you so much for this PR. This is a great addition to the PagerDuty provider!

The changes to `pagerduty_escalation_policy` and `pagerduty_schedule` looks really good, tested them quick with a (plan/apply).

I'm experiencing some issues though when testing out the changes in `pagerduty_service`.
Do you happen to have a config snippet that works for you, so I can test this out quick? :)

Would be awesome if you could add tests and update the documentation to cover these changes, but overall this looks great!

Once again, thanks!

**Comment by dthagard** [comment]
This snippet doesn't exercise all of the options, but it is a start:

```
resource "pagerduty_team" "test" {
  name        = "TEST"
  description = "Test Team - Managed by Terraform"
}

resource "pagerduty_user" "user1" {
  name      = "User1"
  email     = "user1@foorbar.com"
  teams     = ["${pagerduty_team.test.id}"]
  role      = "limited_user"
  job_title = "Test Engineer"
}

resource "pagerduty_user" "user2" {
  name      = "User2"
  email     = "user2@foorbar.com"
  teams     = ["${pagerduty_team.test.id}"]
  role      = "limited_user"
  job_title = "Test Engineer"
}

resource "pagerduty_user" "manager" {
  name      = "Manager"
  email     = "manager@foorbar.com"
  teams     = ["${pagerduty_team.test.id}"]
  role      = "admin"
  job_title = "Test Manager"
}

resource "pagerduty_schedule" "us_east_business_hours" {
  name        = "US East Business Hours"
  description = "Schedule to cover US east business hours, 9AM EST to 6PM EST. Managed by Terraform"
  time_zone   = "America/New_York"

  layer {
    name                         = "US_EAST"
    start                        = "2016-11-07T09:00:00-05:00"       // Monday
    rotation_virtual_start       = "2016-11-07T09:00:00-05:00"       // Monday
    rotation_turn_length_seconds = 604800                            // 7 days
    users                        = ["${pagerduty_user.user1.id}","${pagerduty_user.user2.id}"]

    restriction {
      type              = "weekly_restriction"
      start_time_of_day = "09:00:00"
      duration_seconds  = 32400                // 9 hours
      start_day_of_week = 1                    // Monday
    }

    restriction {
      type              = "weekly_restriction"
      start_time_of_day = "09:00:00"
      duration_seconds  = 32400                // 9 hours
      start_day_of_week = 2                    // Tuesday
    }

    restriction {
      type              = "weekly_restriction"
      start_time_of_day = "09:00:00"
      duration_seconds  = 32400                // 9 hours
      start_day_of_week = 3                    // Wednesday
    }

    restriction {
      type              = "weekly_restriction"
      start_time_of_day = "09:00:00"
      duration_seconds  = 32400                // 9 hours
      start_day_of_week = 4                    // Thursday
    }

    restriction {
      type              = "weekly_restriction"
      start_time_of_day = "09:00:00"
      duration_seconds  = 32400                // 9 hours
      start_day_of_week = 5                    // Friday
    }
  }
}

resource "pagerduty_escalation_policy" "test" {
  name           = "test"
  description    = "Test Escalation Policy - Managed by Terraform"
  num_loops      = "2"
  repeat_enabled = "true"
  teams          = ["${pagerduty_team.test.id}"]

  rule {
    escalation_delay_in_minutes = "60"

    target {
      type = "schedule"
      id   = "${pagerduty_schedule.us_east_business_hours.id}"
    }
  }

  rule {
    escalation_delay_in_minutes = "60"

    target {
      type = "user"
      id   = "${pagerduty_user.manager.id}"
    }
  }
}

resource "pagerduty_service" "test" {
  name              = "test"
  description       = "Test Service - Managed by Terraform"
  escalation_policy = "${pagerduty_escalation_policy.test.id}"

  incident_urgency_rule {
    type    = "constant"
    urgency = "high"
  }
}

resource "pagerduty_service_integration" "test" {
  name              = "Test Service Integration"
  type              = "generic_email_inbound_integration"
  service           = "${pagerduty_service.test.id}"
  integration_email = "${pagerduty_team.test.name}@foobar.pagerduty.com"
}
```

**Comment by dthagard** [comment]
I'll look to add some additional tests and documentation as well.

**Comment by stack72** [comment]
ping @dthagard (//cc @heimweh)

P.

**Comment by heimweh** [comment]
Hi @dthagard, any update on this? I'll be happy to help out wherever I can on this one :)

I also noticed that `repeat_enabled` is being completely ignored by the API (although documented), I just tested it via the API reference page. Could we maybe take that one as a follow up PR?

**Comment by heimweh** [comment]
@stack72 @dthagard: I think most of the additions in this PR has already been added by (https://github.com/hashicorp/terraform/pull/11856, https://github.com/hashicorp/terraform/pull/10069) except for `repeat_enabled` which seems to be ignored by PagerDuty's API (confirmed this with their support), I don't know if that's been fixed yet, but maybe that could be a follow up PR?

**Comment by heimweh** [comment]
**Update**: Just got a response from PagerDuty and they recommend not setting the `repeat_enabled` since it doesn't work but instead use `num_loops` to dictate whether an escalation policy repeats and how many times which already seems to be in the schema.

**Comment by stack72** [comment]
@heimweh what do you suggest with this PR then?

**Comment by heimweh** [comment]
@stack72 I guess we can close this one for now since the PagerDuty API doesn't support the repeat_enabled field. They recommend setting or omitting the num_loops field instead to dictate whether an escalation policy repeats and how many times.

**Comment by stack72** [comment]
okies - <3 to @dthagard for all the work here!

**Comment by gregswift** [comment]
What about the other features like the urgency_rule ?

**Comment by heimweh** [comment]
Hi @gregswift,

it seems like the support for `incident_urgency_rule`, `support_hours` & `scheduled_actions` in `pagerduty_service` was added in this PR: https://github.com/hashicorp/terraform/pull/11856 & the support for `start_day_of_week` in `pagerduty_schedule` was added in this PR: https://github.com/hashicorp/terraform/pull/10069.

**Pull request closed without merging**
