### PR TITLE
Discrepency between local-exec and remote-exec

### PR DESCRIPTION
**Pull request by aclowkey**
#19530

### CODE REVIEW

**Comment by dawidmalina** [comment]
I would love to see this merged (at least multiline support for local-exec). But to be honest renaming field would be probably very tough as it will introduce a lot of incompatibilities.

**Comment by commonbreed** [comment]
It's a shame this PR has sat stale since 2018. I appreciate the issue with deprecation, but this should have at least been considered by now.

**Comment by nckbnv** [comment]
Is this one going to be merged anytime soon?

**Comment by commonbreed** [comment]
@mildwonkey Can we receive feedback from Hashicorp on this? Disappointing that Hashicorp believes it's okay to leave PRs open for going on a year...

**Pull request closed without merging**
