### PR TITLE
Support for dynamic blocks and meta-arguments

### LINKED ISSUE #24188: Support for dynamic blocks and meta-arguments
Afternoon,

FR to allow the dynamic blocks capability to work with resource meta-arguments.

### Current Terraform Version
0.12.20+

```

### Use-cases

The use case Im trying to implement is a simple one.
I would like to add `lifecycle` meta-argument to a resouce when our `var.ENVIRONMENT` == "prod". ie, stop the pipeline destroying prod resources.

### Attempted Solutions

```hcl-terraform
  # Here we set a lifecycle block to include `prevent_destroy=true` when `var.ENVIRONMENT=prod`.
  dynamic "lifecycle" {
    for_each = var.ENVIRONMENT == "prod" ? [{}] : []

    content {
      prevent_destroy = true
    }
  }
```

Result of the above is:

```text
Error: Unsupported block type

  on main.tf line 25, in resource "azurerm_resource_group" "rgnamegoeshere":
  25:   dynamic "lifecycle" {

Blocks of type "lifecycle" are not expected here.
```

### Proposal

Support meta-arguments for use with dynamic blocks. Im sure its really easy to. jk.

### References

Similar request in Terraform Core discussion: https://discuss.hashicorp.com/t/dynamic-lifecycle-ignore-changes/4579/4

### PR DESCRIPTION
**Pull request by raxod502-plaid**
This pull request does not contain any code. It is being filed at the request of @crw in https://github.com/hashicorp/terraform/issues/24188#issuecomment-1409651544 so that it can be discussed whether a pull request implementing the feature would be reviewed and merged by the maintainers.

Please let me know if more information is requested in order to have the requested discussion.

Fixes #24188

## Target Release

1.4.x

### ENHANCEMENTS

-  Resource meta-arguments can now be controlled using dynamic blocks functionality.

### CODE REVIEW

**Comment by crw** [comment]
The next step is to propose an implementation design. This would come from a community member eager to contribute a solution. :) 

I have an additional concern that this functionality might not be possible to implement in Terraform as it is designed today, so may be something that cannot have a solution without breaking the v1 compatibility promise. However, I need to see if that is true - I will take on that action, to have a discussion with the core team.

**Comment by raxod502-plaid** [comment]
Thanks, it sounds like getting sign-off from the core team is a blocker to starting any implementation design proposals, so I will wait until that is done first.

**Comment by jbardin** [comment]
Hi @raxod502-plaid, I think we're skipping step here with a PR before having a plan for what to implement. A lot of the work to be done is in an issue like that is in the product research area, to sort out what the real problem statements are (`dynamic` is a red herring, it wouldn't be used for a single object value like this), and find common themes (for example, a lot of the comments I see are actually provider problems which are addressed by adopting the new SDK), and solutions which can fit within the language (references must be static, so we can't dynamically add them into `ignore_changes` or `replace_triggered_by`)

Since many of the suggestions in the linked issue aren't directly possible to implement, a solution to the underlying problems may require an entirely different approach, and probably different for each lifecycle feature. This isn't to stop you from brainstorming or offering proposals, but longstanding issues aren't there solely out of neglect, there are often complex problems to be solved in concert with many moving parts.

**Comment by raxod502-plaid** [comment]
> I think we're skipping step here with a PR before having a plan for what to implement

I was specifically asked by @crw in https://github.com/hashicorp/terraform/issues/24188#issuecomment-1409651544 to file a PR. Would you like me to do something else instead? What I'm trying to do is determine whether the Terraform core team is willing to accept a fix for this issue, before any implementation work starts. This is because past PRs fixing issues have frequently been rejected.

**Comment by jbardin** [comment]
@raxod502-plaid ah sorry, I see. If the PR was intended to be a location for more focused discussion, that works too. There may be acceptable solutions, but it's going to take some work to do to figure out what the real problems are and what any solution is going to look like.

**Comment by raxod502-plaid** [comment]
Okay. Is there anything that can realistically be done by the community to move this forward or are we blocked on internal discussions at Hashicorp?

**Comment by raxod502-plaid** [comment]
Okay, so, to summarize, there is nothing that can be done externally, and there is no option for the issue to be resolved until the core team works on it?

**Comment by crw** [comment]
@raxod502-plaid That is a summary of the situation. I think the core problem is, per James:

> [...] we can't expect external contributors to invest the significant time involved in developing that expertise. So realistically it's hard for the community to move forward with something like this [...]

It is not *impossible* for a community member to contribute a proposal that takes into account the many concerns of an issue such as this, just *very difficult*. The reason I suggested that an interested party could open a PR to discuss a proposal was to allow the opportunity for a motivated community member to propose such a solution and have it discussed. As no such proposal seems forthcoming and this discussion has wandered away from a specific proposal to a general discussion of why it is difficult to create meaningful proposals, I am going to go ahead a close it. Please feel free to open a new issue or PR if you have a proposal to share for this issue. Thanks for your continued interest in finding solutions to our hardest problems!

**Pull request closed without merging**
