### PR TITLE
provider/vsphere: rename vcenter_server config parameter to something clearer

### PR DESCRIPTION
**Pull request by tkak**
This fixes https://github.com/hashicorp/terraform/issues/3522.

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@tkak isn't vcenter more accurate?  It is actually the api url on the vcenter server ...

**Comment by tkak** [comment]
@chrislovecnm hmm..., I think the parameter has a use case in ESXi, not just vcenter server.

**Comment by chrislovecnm** [comment]
@tkak indeed

LGTM

@phinze might we get some mergeness?

**Comment by tkak** [comment]
@chrislovecnm I updated the docs. Thanks!

**Comment by phinze** [comment]
This LGTM. I'm going to follow up with a tweak to include the old field as supported but deprecated so we don't break any existing users with this, we can leave that for at least one release and clean it up in a future one.

**Pull request merged**
