### PR TITLE
Switching the healthcheck shouldn't cause a refresh of the resource

### PR DESCRIPTION
**Pull request by mzupan**
Switching the healthcheck from elb->ec2 or ec2->elb shouldn't cause the ASG to re-create itself

You can do this operation in the AWS console

### CODE REVIEW

**Comment by phinze** [comment]
Unfortunately we can't just flip `ForceNew` to false here - we need to also handle the attribute change in the `Update` method. Want to follow the pattern for other attributes in Update and give it a shot?

**Comment by mzupan** [comment]
@phinze yep my fault.. I'll update the PR shortly

**Comment by mzupan** [comment]
@phinze updated the PR

```
aws_autoscaling_group.mc: Modifying...
  health_check_type: "ELB" => "EC2"
aws_autoscaling_group.mc: Modifications complete
```

You need to pass in the grace period if you change the type. So that's why that gets included.

**Comment by phinze** [comment]
Nice - thanks! LGTM

**Pull request merged**
