### PR TITLE
AWS WAF Regional

### PR DESCRIPTION
**Pull request by yusukegoto**
Resolving conflicts of #11263 coz original author is silent for weeks in spite of his great work.
Add implementations of change token consideration from #13656 .

### CODE REVIEW

**Comment by radeksimko** [comment]
Hi @yusukegoto 
and thanks @neildothunter for the initial work.

Would either of you mind submitting vendor updates (any changes in `/vendor/*`) in a separate PR, so we can reduce the LOC in the real PR and make it a bit easier to review?

I'm happy to merge that one pretty much straight away and let you rebase.

If you could then submit 1 resource at a time (with relevant docs) that would be awesome as well.
Less LOC will be easier/faster to review. Most of us, maintainers prefer to review smaller PRs rather than bigger ones. 😃

**Comment by yusukegoto** [comment]
rebasing... 🏃

**Comment by yusukegoto** [comment]
sorry, this is my best.

**Comment by yusukegoto** [comment]
@radeksimko hi, should I create PRs by each resources???

**Comment by yusukegoto** [comment]
I think this PR will be closed after finising splits.

**Comment by radeksimko** [comment]
Thanks @yusukegoto ,
I really appreciate the effort you put into splitting this out 👍 👍 
I will have a look at those PRs this week.

**Comment by neildothunter** [comment]
@yusukegoto thanks for moving this forward (and sorry commitments stopped my further contribution when the PR got some focus). @radeksimko, would it be worth noting that resources should be submitted in individual PRs in the contribution guide?

**Comment by radeksimko** [comment]
@neildothunter No worries. Good idea about the update of contribution guide, see https://github.com/hashicorp/terraform/pull/13737

@yusukegoto do you mind if we close this PR in favour of the other ones?

**Comment by yusukegoto** [comment]
@reedloden yes, please close this PR👍 .
@neildothunter hi, it's nice to see you!

**Pull request closed without merging**
