### PR TITLE
Adding data sources to dns provider.

### PR DESCRIPTION
**Pull request by BSick7**
This is a continuation of #7270 that includes only dns data sources.
- `dns_a_record_set`
- `dns_cname_record_set`
- `dns_txt_record_set`.

### CODE REVIEW

**Comment by BSick7** [comment]
@catsby This PR should be ready to go. Let me know if I'm missing anything.

**Comment by catsby** [comment]
Thanks! I had to `go fmt` a file, and merged in https://github.com/hashicorp/terraform/commit/628dd2a1a48b1006e3f9d5020cfc753fef08c6b7

**Comment by catsby** [comment]
Hey @BSick7 a big thanks for taking the time to manually rework this to fit into the other PR. I really appreciate the time and generosity there.

Also thanks to @drebes in #8299 for modifying that PR to accommodate the merging with this one. We here sincerely appreciate the contributions and the teamwork from all involved 😄

**Comment by BSick7** [comment]
Glad to see it finally land. Thanks @catsby!

**Pull request merged**
