### PR TITLE
stacks: split the terraform1 RPC package into per-service packages

### PR DESCRIPTION
**Pull request by liamcervante**
This PR modifies the layout of packages underneath the `terraform1` RPC API go-plugin.

Each of the services we support (`Stacks`, `Dependencies`, `Setup`, and `Packages`) has been broken into a dedicated package. Any messages shared by the 2 or more of the services (such as the diagnostics) are kept in the existing `terraform1` package.

We can freely move messages between packages without breaking compatibility if one of the services change and we require more sharing of content. By placing the services into dedicated packages we get a better separation of concerns and can more clearly define the boundaries between them.

At the moment there is some overlap between the `Dependencies` and the `Packages` services and we could think about combining them. But, the `Packages` service is only in use by the `terraform-stacks-cli` repository which will eventually be merged back into the main repository anyway, and we can delete the service at that point. Therefore, I think it is a good idea to keep the services separate as we can enforce anything that is actually needed by stacks should be in the dependencies package, but anything we are just using to make development of the CLI easier can stay in the packages service.

Internal ticket: https://hashicorp.atlassian.net/browse/TF-10081

### CODE REVIEW

**Comment by alisdair** [comment]
This broadly makes sense to me as a split! I can't reliably review a diff of this size to look for typos but since it's largely a mechanical refactor I don't think I need to.

Did you consider pulling some of the theoretically reusable generic types into the shared `terraform1` protocol? Things like `DynamicValue` and `AttributePath`. I don't think it's particularly necessary, as implementing an API for non-stacks workloads isn't something we're doing right now, seems but I'm curious about the pros and cons.

**Comment by liamcervante** [comment]
> Did you consider pulling some of the theoretically reusable generic types into the shared terraform1 protocol?

We could do that, but I think we can also move the nested messages between packages later without it being a breaking change. My understanding is that the underlying protocol only cares that the messages have the same structure since it's all serialised in the same way.

With that in mind, I'd lean towards just lazily moving them as and when we see a need for them to be shared.

**Comment by alisdair** [comment]
Ah, of course. Yep, that makes sense to me then.

If this rebase is manageable perhaps we should get this split done now, before the branch gets too stale?

**Comment by liamcervante** [comment]
> If this rebase is manageable perhaps we should get this split done now, before the branch gets too stale?

Ready for review!

**Review by alisdair — APPROVED** [review]

**Pull request merged**
