### PR TITLE
Support recursive targeting on modules

### PR DESCRIPTION
**Pull request by josephholsten**
Rebase of #9236

### CODE REVIEW

**Comment by apparentlymart** [comment]
Note to self, for later review in more detail: this patch changes the `ResourceAddress` population so that when no resource type is present `Type` is set to the magic string "module". Subsequent changes since this PR was originally submitted have added a `HasResourceSpec` method to `ResourceAddress` that would be broken by merging this, since it expects a resource-only address to have an empty `Type`.

**Comment by josephholsten** [comment]
also note: the original PR contained modification to [`terraform/transform_resource.go`](https://github.com/hashicorp/terraform/pull/9236/files#diff-f1e1215b1d2659dfedac1d179e494d2a) but the modern `terraform/transform_resource_count.go` uses a completely different implementation. I have no idea if that could break anything.

**Comment by dcosson** [comment]
Any chance of getting this reviewed/merged? From #9236 it sounded like this was blocked on being able to merge breaking changes for 0.10, and since there are now 2 betas out for 0.10 I'm guessing we've reached that point?

**Comment by apparentlymart** [comment]
Ahh, I had independently rebased and tweaked this in #15314, which went out in 0.10.0-beta1. Sorry I didn't catch this one while I was working on that.

**Comment by dcosson** [comment]
Oh awesome! Thanks for getting this through

**Pull request closed without merging**
