### PR TITLE
Optimized build processes and image sizes by using build containers.

### PR DESCRIPTION
**Pull request by ScriptMyJob**
What all this really comes down to is smaller terraform containers.  Here are some containers that I built that are smaller than the official containers:

https://cloud.docker.com/u/aztek/repository/docker/aztek/terraform/tags

### CODE REVIEW

**Comment by ScriptMyJob** [comment]
I should also point out that I was not sure why `git` and `openssh` were being added to the container.  I think that `git` is an artifact of an old Dockerfile, but I am unsure as to why `openssh` was there.  I can add it into the `final` image though if it is deemed that it is needed.

**Comment by ScriptMyJob** [comment]
I realized after thinking about it a bit more that `git` and `openssh` are needed in the final image (for use in terraform modules).  I have updated the PR with an additional commit to account for this.

**Comment by apparentlymart** [comment]
Hi @ScriptMyJob! Thanks for working on this.

Avoiding having `gpg`, the source archive, etc in the "release" images is a great addition which I'd like to merge. As you've seen, aside from some tools Terraform relies on for installation of modules, Terraform is generally self-contained on Linux and so this sort of minimal container is ideal.

I have some concerns about changing the top-level `Dockerfile` in this way, though. As currently defined, that image intentionally contains the Terraform source code, because it's current purpose is to be used for Terraform _development_, not releasing. While that purpose could potentially change, I don't want to do it yet without a better understanding of what use-cases it might affect, since I expect some processes are relying on that image for its containing source code -- otherwise, they'd presumably use the release images.

Would you be okay with moving forward with just the changes to `Dockerfile-release` for now, which seem uncontroversial better, but leaving `Dockerfile` as-is? I think that's the best way to get the benefit of smaller images for the release ones (which are more commonly used, due to them being versioned) in the short term now, while avoiding the uncertainty of what the root `Dockerfile` changes might affect.

**Comment by apparentlymart** [comment]
Thanks, @ScriptMyJob!

**Comment by ScriptMyJob** [comment]
@apparentlymart,

Thanks for taking the time to review my PR.  You brought up great points that I hadn't considered.  I have made the requested changes reverting `./Dockerfile` to `HEAD~3`.

Respectfully,
Robert J.

**Pull request merged**
