### PR TITLE
terraform-provider-maas

### PR DESCRIPTION
**Pull request by negronjl**
Adds support for MAAS

### CODE REVIEW

**Comment by apparentlymart** [comment]
r.e. #2979

**Comment by negronjl** [comment]
Wow ... I really need to learn to to type.  bzr .. not bar.

**Comment by negronjl** [comment]
Is there anything I need to do here?

**Comment by apparentlymart** [comment]
@negronjl this one is tough because I don't have a MAAS setup to test this with, and I don't think I can just spin one up since it requires physical infrastructure, right?

Do you have any ideas about how I might try this out? Alternatively, are there other MAAS users in the Terraform community that could give this a try and vouch that it's working well for them?

**Comment by negronjl** [comment]
If you have a big enough machine, you can create KVM instances and treat them as bare metal.  You can have 11 KVM instances, for example, where the first one is the maas server and the rest are maas managed nodes.
I had a project that created this type of environment … let me dig it out and dust it off.  I’ll push it somewhere where you can get it and test.


Thanks,

Juan

**Comment by phinze** [comment]
Hi @negronjl! Were you ever able to find that testing environment you used? We'd want to implement something similar in Terraform's nightly acceptance test CI env when we merge this.

**Comment by samjwlee** [comment]
We got maas running today, with the intent to operate it via terraform.  Is there any progress regarding accepting maas as a new provider?

**Comment by apparentlymart** [comment]
Hi again @negronjl! Sorry for the long silence here.

We try to maintain an internal environment for automatically running all of the acceptance tests daily so that we can detect drift and regressions in the providers bundled with Terraform. It sounds like there's a path to get that set up here but we don't internally have the expertise to do so, so in order to include this in the main Terraform distribution we'd need to find someone who has the time and willingness to help us maintain the provider itself and its test environment.

I remember that you had originally implemented this as an externally-maintained provider and I'd encouraged you to submit this PR. I'm sorry that at that time the policy for maintainership builtin providers wasn't quite as fleshed out and so it wasn't clear to me at that time the complexity of what I was suggesting.

For the moment it seems like you were able to get what you needed from your externally-maintained provider, so I'm going to close this out. We have plans in future to better improve the user-experience around non-builtin plugins, which will roll out gradually over coming versions of Terraform though there's no committed schedule for that. Once we reach that point though, your external MaaS plugin will hopefully be a good use-case for that.

Thanks again, and sorry for recommending that we try to merge this before thinking through all of the implications.

**Pull request closed without merging**
