### PR TITLE
Fix for GH-13932

### PR DESCRIPTION
**Pull request by brandontosch**
This is to address issue #13932. When using managed disks, the Azure API does not support provisioning a VM using the `image_uri` field under `storage_os_disk`. The solution I found is to expose the `id` field of `storage_image_reference` and use that to specify the custom image URI which the Azure API accepts and results in a successful VM provisioning.

todo:
- [x] Update docs
- [x] ~~Add test if possible (need a reliable reference to an image or dynamically create one)~~

### CODE REVIEW

**Comment by Trip09** [comment]
Is there a expected date to merge?

**Comment by brandontosch** [comment]
@Trip09 I'll try to wrap up the docs/tests tonight so that it's ready to merge whenever someone gets time to review.

**Comment by CloudSurgeon** [comment]
Any updates to this? I was so hoping this would have made it into 0.9.6

**Comment by brandontosch** [comment]
Sorry for the delay. Fixed some merged issues and updated the docs so think this should be good now.

**Comment by Trip09** [comment]
@tombuildsstuff , can you take a look in the PR? lgtm

**Comment by rbramwell** [comment]
Been hunting down this issue all day. Saw the azure docs that showed the 'id' field and came across this. Really looking forward to this making it into a release soon.

**Comment by rbramwell** [comment]
@brandontosch Unfortunately, you have conflicts once again. Could take another look at it? Thanks for the work you put in! Really looking forward to this update.

**Comment by apparentlymart** [comment]
Hello @brandontosch, and thanks for working on this!

As part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it.

If you or someone else has the time and motivation to apply the same changes to [the `azurerm` provider repository](https://github.com/terraform-providers/terraform-provider-azurerm) and open a new PR there, the maintainers of that provider should be able to review it.

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Pull request closed without merging**
