### PR TITLE
insert missing infinitive particle

### PR DESCRIPTION
**Pull request by bobsut**

### CODE REVIEW

**Comment by crw** [comment]
Thanks for the submission!

**Review by mgarrell777 — APPROVED** [review]
Hi @bobsut I'm Matthew, technical writer for Terraform. Thanks for fixing the missing infinitive particle.

I have a couple other small wording change suggestions. Otherwise, your fix is good.

**Comment by bobsut** [comment]
I fear I may have prematurely closed this PR by deleting my fork

**Comment by crw** [comment]
Thanks @bobsut! We did miss merging this so even though it was an accident, it led to the right thing happening. :)

**Comment by bobsut** [comment]
I am not very often overtaken by spasms of housekeeping.
When such a fit strikes, it's unfamiliar, so I need to be extra cautious to avoid unintended consequences.
Sometimes the side-effects are trivial, like if these grammatical nits had persisted.
Sometimes it's more serious, and I have found myself rushing to the curb and pulling a treasure from the barrel as the trash truck rolls up to my house.
I have learned the safest strategy is to avoid tidiness, though my lovely bride has tried to convince me otherwise.
This almost-lost PR will provide yet another data point to support my position.

**Pull request merged**
