### PR TITLE
Add FreeIPA provider

### PR DESCRIPTION
**Pull request by raphink**

### CODE REVIEW

**Comment by raphink** [comment]
Do you mean I need to rebase?

**Comment by pkolyvas** [comment]
@raphink I cherry-picked it into our `stable-website` branch for you. :)

**Comment by raphink** [comment]
Thanks!

**Comment by raphink** [comment]
How often is the website rebuilt?

**Comment by pkolyvas** [comment]
Pretty frequently. It should appear later today.

**Pull request merged**
