### PR TITLE
aws: Add support for Alias records into AWS Route 53

### PR DESCRIPTION
**Pull request by radeksimko**
This closes https://github.com/hashicorp/terraform/issues/747
Documentation attached.

Alias records (as documented) can be currently used in conjunction with
 - ELBs - one extra commit here is allowing it to happen by exposing `zone_id`
 - existing R53 records (works out of the box)
 - CloudFront distributions - see https://github.com/hashicorp/terraform/pull/1780#issuecomment-98403101
 - S3 buckets - see https://github.com/hashicorp/terraform/issues/1769

### Test plan

```
$ make testacc TEST=./builtin/providers/aws TESTARGS='-run=Route53Record' 2>/dev/null
```
```
go generate ./...
TF_ACC=1 go test ./builtin/providers/aws -v -run=Route53Record -timeout 45m
=== RUN TestAccRoute53Record
--- PASS: TestAccRoute53Record (260.16s)
=== RUN TestAccRoute53Record_txtSupport
--- PASS: TestAccRoute53Record_txtSupport (279.02s)
=== RUN TestAccRoute53Record_generatesSuffix
--- PASS: TestAccRoute53Record_generatesSuffix (269.83s)
=== RUN TestAccRoute53Record_wildcard
--- PASS: TestAccRoute53Record_wildcard (402.11s)
=== RUN TestAccRoute53Record_weighted
--- PASS: TestAccRoute53Record_weighted (266.97s)
=== RUN TestAccRoute53Record_alias
--- PASS: TestAccRoute53Record_alias (529.72s)
=== RUN TestAccRoute53Record_weighted_alias
--- PASS: TestAccRoute53Record_weighted_alias (521.43s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	2529.257s
```

### Example
```ruby
resource "aws_route53_zone" "main" {
  name = "notexample.com"
}

resource "aws_route53_record" "alias" {
  zone_id = "${aws_route53_zone.main.zone_id}"
  name = "www"
  type = "A"

  alias {
  	zone_id = "${aws_elb.main.zone_id}"
  	name = "${aws_elb.main.dns_name}"
  	evaluate_target_health = true
  }
}

resource "aws_elb" "main" {
  name = "foobar-terraform-elb"
  availability_zones = ["us-west-2a"]

  listener {
    instance_port = 80
    instance_protocol = "http"
    lb_port = 80
    lb_protocol = "http"
  }
}
```

Related PR: https://github.com/hashicorp/terraform/pull/1366. I hope I covered all the edge cases and conflicts (e.g. TTL).

### CODE REVIEW

**Comment by mitchellh** [comment]
Looks perfect!

**Comment by radeksimko** [comment]
@c4milo I see your point, sorry for the troubles caused. I was actually thinking about this problem, but it's not just related to this resource, it's a global issue affecting many other resources as well.

There is simply nothing like `RequiredWhen` yet where we could say _"this is only required if property X == Y"_ or _"one of these fields is required"_. I agree that the `Schema` desperately needs such functionality. I may have a look into it this weekend.

> also, this change is currently misaligned with what the documentation says.

could you be a bit more specific, please?

**Comment by c4milo** [comment]
@radeksimko I didn't mean it in a negative way, I should've used a different word instead of "waste". It just took me longer than normal to realized what was going on. So, there is nothing to be sorry about :)

Regarding the documentation, I think it only needs to make more explicit that `ttl` and `records` are required only if there is not an ALIAS block.

**Comment by radeksimko** [comment]
@c4milo Regarding docs -> see https://github.com/hashicorp/terraform/pull/2092

I was already adding `ConflictsWith` for similar purpose, so I'd expect it should tell you that these parameters conflict with each other. If it doesn't, then there must be a bug in that implementation.

**Comment by c4milo** [comment]
@radeksimko, yes, I tested that case and it complains about conflicting configuration options correctly.

**Pull request merged**
