### PR TITLE
New resource - aws_availability_zones

### PR DESCRIPTION
**Pull request by vancluever**
This adds a new resource - `aws_availability_zones` - to get a list of availability zones that the account/region combination can use.

Precedent: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getavailabilityzones.html

I've exposed the API parameters (docs in the PR).

One thing - the test is general, as depending on where you are set up, doing something like limiting your region to `us-east-1`, etc, will give no results. I've tested locally here though with the options and had success.

Also - `buildEc2Filters` is similar to the function I have in #4396, which I will move to use this if/when things are merged.

### CODE REVIEW

**Comment by vancluever** [comment]
Note the the usefulness of this PR is kind of diminished by the fact that you currently can't splat nested resource attributes. I'd love to see this happen though, and if someone can tell me where to start, I might give it a go.

**Comment by radeksimko** [comment]
This resource would hugely benefit from using https://github.com/hashicorp/terraform/pull/4705

**Comment by jen20** [comment]
I would be tempted to wait on this until #4705 is implemented. I see that @apparentlymart has started work on it, I have some type system work to do in core before turning my attention to it but hopefully it's something we can address soon!

**Comment by vancluever** [comment]
@radeksimko:

> it would be nice if we could limit the amount of zones returned (e.g. not everyone may want to use all 4 AZs in us-east-1, where 2 or 3 AZs would just do the job for cheap redundancy). Maybe introduce limit (TypeInt) would help here?

I think that this might be something we could leave up to the template/module author, no? If you know how many zones you need, then you could just limit your say, `count` to iterate over that number and leave the rest.

> it would be nice if we could guarantee the ordering of zones, so that in case I deployed everything into us-east-1a + us-east-1b and API suddenly returns us-east1-a + us-east1-c, I would not suddenly redeploy everything to a different zone. Maybe we can just alphabetically sort the returned list?

I think this is a good idea for sure. Not too much work, and that way you can expect the same results back all the time. It could be how CloudFormation even behaves, The docs mention a sorted list in the sample results but I'm not too sure if that's just due to the example. I'll add this to the code.

And yeah, I've run into some limitations with these kinds of utility resources for sure in the way they are currently configured. The AMI search resource is kind of resistant to change in that if you change the search parameters it doesn't necessarily update any dependent resources in the next run (although it doesn't affect if the search returns a different AMI, ie: a new AMI is pushed with the same tag, etc). Since this resource is relatively static though, it should be pretty resilient to the shortcomings of the current architecture.

What would benefit this resource much more is if #2833 is addressed, as right now you can't use `element` on the returned AZs.

**Comment by radeksimko** [comment]
> I think that this might be something we could leave up to the template/module author, no? If you know how many zones you need, then you could just limit your say, count to iterate over that number and leave the rest.

True, that's also an elegant solution. :+1: 

Either way I think we should wait for https://github.com/hashicorp/terraform/pull/4705

**Comment by vancluever** [comment]
Roger that. Also, just updated the code - I've simplified the results returned, so now it can be looked up on without having to splat, and also added sorting. Will wait for the LGTM, and/or feedback on if we should just stick with this structure (the value to TF on the other returned values (ie: status and status messages) are kind of debatable), and then will squash.

**Comment by josh-padnick** [comment]
Is there an update on this PR? This would be a useful feature since I'm still hardcoding availability zone lists into my templates since they vary by AWS account.

**Comment by vancluever** [comment]
Guys - it's been a while since this PR is in, and I'm still using it, so I figured I'd give it a rebase to make it easier to merge. 

Would love to see this in upstream - even it it gets removed in 0.7 (and again, I would be totally fine with porting it over to a data source when that happens).

**Comment by vancluever** [comment]
Going to be closing this one shortly, as we have #6671 - going to take the tests from this one and port them over so that we have those.

**Pull request closed without merging**
