### PR TITLE
null eval from output

### PR DESCRIPTION
**Pull request by jbardin**
Failing minimal test for #19223

The issue is that the evaluation of the config (from `EvaluateBlock`) returns a `Null` value for the `required` field when referencing an attribute in a module output, rather than `Unknown`.

### CODE REVIEW

**Comment by apparentlymart** [comment]
I found the cause of the issue here: the output change object in the plan was being written without an address, and so the evaluator couldn't find it.

I found another problem along the way, which is that whole-resource references (`module.foo` rather than `module.foo.bar`) were not consulting the plan at all, and would thus have hit the same problem. I added a new test that covers that by forcing the evaluation of the whole module as a value before making the same assertions as the other one.

One of these changes seems to have regressed a few of the apply tests. I expect that these tests are not actually _broken_ and were instead just relying on the implicit nullification of outputs, but I will investigate that more tomorrow.

**Comment by jbardin** [comment]
Nice! The new commits LGTM!

**Comment by jbardin** [comment]
One of the apply tests simply was missing the output, but this seems to have inverted the issue for the others, and apply ends up with unknown values after the fact.

**Comment by apparentlymart** [comment]
@jbardin in retrospect this is a bit weird because this was your PR but now I've pushed a bunch to it, but if this looks good to you then let me know and we can just go ahead and merge it even though technically GitHub won't let you approve your own PR. :grinning: 

I pushed one more commit today to fix the last part of this problem, which was about updating the values in the changeset during apply. In retrospect the choice to use a slice for the output value changes (mimicking what we did for resources) doesn't seem like such a great choice right now but I chose to leave it alone both to minimize risk at this late stage and also thinking that our future changes to deal with outputs in a more first-class way during planning will cause us to revisit this soon enough.

**Pull request merged**
