### PR TITLE
[WIP] Add `terraform state edit` - edits properties of state objects.

### PR DESCRIPTION
**Pull request by korfuri**
While onboarding a sizeable brownfield infrastructure into Terraform, I ran into the need to perform some state surgery that isn't supported by `tf state` so far.  Namely, I had a need to import resources with a config that used "name_prefix". Our MOP for this involves editing the state file to copy the "name" property into a "name_prefix" property, but doing this by hand is complicated and error-prone.

I put together a quick way to do this via a new command in `tf state`. Before I proceed, I'd like to get a sense of whether there's interest in this approach.

### CODE REVIEW

**Comment by apparentlymart** [comment]
Hi @korfuri! Thanks for working on this.

I'm honestly a little nervous about adding a command like this, since it seems like it could cause people to get into some sticky situations that are hard to recover from. While I could see the argument that `terraform state rm` is already dangerous, directly editing the properties of an existing resource has some extra risk in that it may cause the resource state to no longer comply with the expected schema or invariants of the resource implementation, which could then cause Terraform to fail in strange ways.

My feeling at the moment is that the need to directly edit the state file serves to make this sort of change just difficult enough that a user will approach it with some caution and know that it's a risky operation. By making it a first-class command we could encourage using it as a routine part of workflow, which would be unfortunate.

I could see us potentially doing something like this in future where we're able to hook in to the provider's validation functionality to help ensure that the proposed change is valid, but that would be a longer-term "polish" sort of thing and not something we'd prioritize in the short term.

Your implementation here looks good and I'm grateful for the time you spent working on it, but I want to hold on adding this functionality for now until we're able to make it more "first-class". I hope that rationale makes sense!

**Comment by korfuri** [comment]
I completely understand, I agree that this may be too blunt or too powerful. I'll try to think of alternative approaches that would be less risky or at least that people wouldn't use lightly as they would with this. Ideas very welcome :)

For now I'll split this off into a separate binary, since we need it for our workflow to address the `name_prefix` vs `name` mismatch during import. Hopefully, having it as a separate tool will make it clear that this is not a terraform-supported operation and that it is inherently risky. The tradeoff in our case is that we have a need in our workflow to edit the state file anyway, and that editing it by hand is riskier than using a command-line tool that does it for us.

I had another idea that maybe could work: we could have a command, say `tf state edit` that pulls the latest state, opens `$EDITOR`, lets you edit the state file, and pushes it back to remote (or just saved terraform.tfstate locally if no remote state is used). This would use state locking when available. It has the benefit of strongly encouraging a human approach, so it wouldn't become routinely embedded in scripts. What do you think, is this something that would fit better in the Terraform landscape?

**Comment by apparentlymart** [comment]
Hi @korfuri!

Thanks for the additional ideas here! The helper for manual edits is an interesting idea.

In principle it is possible to implement something like this in an external program by using `terraform state pull` and `terraform state push`. It would be interesting to prototype some different ideas in that way to see what works well, and then possibly later a promising idea could be incorporated into the `terraform state` subcommand which is, after all, essentially the some process of pulling, editing, and pushing.

The main thing lost with an external tool is that Terraform can't hold a state lock during the change, but the lineage/serial checks should still prevent collisions that would work the state.

**Comment by teamterraform** [comment]
Hello! I am going to close this older WIP PR. If this is a feature you are still interested in, please open a Github issue using the Feature Request template so we can discuss the design.

**Pull request closed without merging**
