### PR TITLE
Website update

### PR DESCRIPTION
**Pull request by jasoncostello**
Hi all :wave:

I've been working with HashiCorp on an update to the Terraform homepage. This update expands the content out a bit, offering a more succinct explanation of Terraform's benefits. As far as I understand, there may be some design tweaks coming shortly after this, but for now this PR is up for content review. 

@KFishner, may we have your 👀 on this for content approval? 

cc/ @captainill 

✌️

### CODE REVIEW

**Comment by mitchellh** [comment]
LGTM once @KFishner approves the content.

**Comment by jasoncostello** [comment]
The latest round of commits does the following:

- Optimizes an svg that was loading slowly
- Makes the "feature cards" links to the related section ( as requested by @phinze )
- Fixes webkit rendering issues due to the transformed divs
- Final spacing for x-large displays so skews always overlap ( @media query >1440px )

cc/ @captainill @KFishner

**Comment by KFishner** [comment]
LGTM!

**Comment by mitchellh** [comment]
Merging it for tmrw

**Pull request merged**
