### PR TITLE
Small change to terraform import docs

### PR DESCRIPTION
**Pull request by georgespatton**

### CODE REVIEW

**Comment by jamtur01** [comment]
This feels like it might work better in a dedicated "third party" tools page perhaps?

**Comment by georgespatton** [comment]
Can you point me to a more appropriate place for this perhaps?  I didn't write the terraforming tool, but it was useful for initial use of terraform, so users may find value in knowing about the tool.

**Comment by jamtur01** [comment]
@georgespatton Something like https://github.com/hashicorp/terraform/pull/9384.

**Comment by georgespatton** [comment]
Looks good in that new location.

**Pull request closed without merging**
