### PR TITLE
provider/aws: Improved Auto Scaling Groups updates

### PR DESCRIPTION
**Pull request by catsby**
- availability zones are optional if you specify a VPC Zone Identifier (subnet)
- availability zones can be updated in place

Fixes https://github.com/hashicorp/terraform/issues/2338

Remaining:

- [x] doc update

### CODE REVIEW

**Comment by phinze** [comment]
So we're giving up the plan-time validation in the Classic deploy case, but I think that's AOK. I'm always willing to take from Classic UX if it means improving VPC UX.

**Comment by phinze** [comment]
(LGTM so far, will give it one more review after docs land.)

**Comment by catsby** [comment]
> So we're giving up the plan-time validation in the Classic deploy case, 

Unfortunately yes, until we have a `RequiredUnless` concept in the Schema

**Comment by catsby** [comment]
@phinze doc update in 55a1a31 just mentions that AZ is optional if VPC Zone is not specified

**Pull request merged**
