### PR TITLE
#9241 Show actual SoftLayer error instead of generic message

### PR DESCRIPTION
**Pull request by bondyk**
Fix of issue https://github.com/hashicorp/terraform/issues/9241

### CODE REVIEW

**Comment by TheKevJames** [comment]
I don't think we want to be manually modifying vendor'd code; rather we should update [the vendor file](https://github.com/hashicorp/terraform/blob/master/vendor/vendor.json#L1295) to pull from the correct commit.

I'm not sure See [the terraform readme](https://github.com/hashicorp/terraform#updating-a-dependency) for more info and the process by which we do this.

**Comment by bondyk** [comment]
Actually it was fixed there as well. See https://github.com/maximilien/softlayer-go/pull/136

**Comment by TheKevJames** [comment]
Yup, I saw that! What I mean is that we shouldn't change this repo by applying the same patch as we do to a vendor library, rather we should update the pinned version of that library with `govendor` to a version that includes that patch already. Please see [the readme](https://github.com/hashicorp/terraform#updating-a-dependency) for more info.

**Comment by TheKevJames** [comment]
As of today, maximilien/softlayer-go has been updated to [v0.7.0](https://github.com/maximilien/softlayer-go/releases/tag/v0.7.0) which includes the fix relevant to this PR. Let's pin [v0.7.0's SHA: 1d4217550](https://github.com/maximilien/softlayer-go/commit/1d4217550aef2c9207aeae5a93c7ce5c3c91ef21) with `govendor`.

**Comment by teamterraform** [comment]
Hi folks! We are undertaking a general GH issue/PR cleanup. The [softlayer provider](https://github.com/terraform-providers/terraform-provider-softlayer) now has its own repository, and any PRs and issues should be opened there.

**Pull request closed without merging**
