### PR TITLE
Add support for SNS delivery status

### PR DESCRIPTION
**Pull request by gazoakley**
Addresses #11739

### CODE REVIEW

**Comment by gazoakley** [comment]
Acceptance tests passing:

```
gaz$ make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSSNSTopic_deliveryStatus'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/04/30 16:55:49 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSSNSTopic_deliveryStatus -timeout 120m
=== RUN   TestAccAWSSNSTopic_deliveryStatus
--- PASS: TestAccAWSSNSTopic_deliveryStatus (46.43s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	46.453s
```

**Comment by gazoakley** [comment]
Fixed the merge conflict with #14064. Acceptance tests passing:

```
gaz$ make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSSNSTopic_deliveryStatus'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/05/02 17:16:21 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSSNSTopic_deliveryStatus -timeout 120m
=== RUN   TestAccAWSSNSTopic_deliveryStatus
--- PASS: TestAccAWSSNSTopic_deliveryStatus (60.62s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	60.644s
```

**Comment by gazoakley** [comment]
Any news on a review?

**Comment by catsby** [comment]
Hello – I sincerely apologize for not getting to this in a timely manner. As you probably know we've since split out the AWS Provider into it's own repository, https://github.com/terraform-providers/terraform-provider-aws . If you are still interested in this feature and willing to port it over, we can proceed with the review there. 

Sorry again

**Pull request closed without merging**
