### PR TITLE
provider/openstack: minor fixes to compute and router resources

### LINKED ISSUE #1741: Openstack provider boolean values create a change
I'm going to use subnet in the example, but this happens with other boolean values in the Openstack provider, such as "admin_state_up" in the router resource.

Any time I set a boolean value to true in the config, the terraform plan reports that it will change from "true" => "1"

Here's the resource definition (fixed to note that we actually use true, not 1)

    resource "openstack_networking_subnet_v2" "subnet-internal" {
	    network_id = "${openstack_networking_network_v2.network-internal.id}"
	    tenant_id = "${var.tenant_id}"
	    region = "${var.openstack_region}"
	    cidr = "${var.internal_cidr}"
	    gateway_ip = "${var.internal_gateway}"
	    enable_dhcp = true
	    dns_nameservers = ["${split(" ", var.dns_nameservers)}"]
	    ip_version = 4
	    allocation_pools = {
		    "start" = "${var.internal_dhcp_start}"
		    "end" = "${var.internal_dhcp_end}"
	   }
    }

Here's the current state:

    "openstack_networking_subnet_v2.subnet-internal": {
        "type": "openstack_networking_subnet_v2",
        "depends_on": [
            "openstack_networking_network_v2.network-internal"
        ],
        "primary": {
            "id": "d2cc8a10-2e74-400a-8720-9951e6dafc39",
            "attributes": {
                "allocation_pools.#": "1",
                "allocation_pools.0.end": "192.168.222.254",
                "allocation_pools.0.start": "192.168.222.100",
                "cidr": "192.168.222.0/24",
                "dns_nameservers.#": "2",
                "dns_nameservers.3811298194": "8.8.4.4",
                "dns_nameservers.3817307869": "8.8.8.8",
                "enable_dhcp": "true",
                "gateway_ip": "192.168.222.1",
                "host_routes.#": "0",
                "id": "d2cc8a10-2e74-400a-8720-9951e6dafc39",
                "ip_version": "4",
                "name": "",
                "network_id": "0ba33147-2340-467d-b691-255921cf7a89",
                "region": "foo",
                "tenant_id": "f79b28dcf6b34b0a8c847a5e35ffcd05"
            }
        }
    }
    
This is the output of terraform plan

    ~ openstack_networking_subnet_v2.subnet-internal
           enable_dhcp: "true" => "1"

### PR DESCRIPTION
**Pull request by cvvs**
Change the OpenStack providers compute resource security_groups schema from a list to a set.

When the security groups are a list, terraform will often indicate change due to a simple reordering of the security group. By changing this to a set, it not only matches the aws providers compute resource, it avoids ordering problems.

Change the OpenStack provider's router resource admin_state_up attribute from a string to a bool

In the openstack provider's router resource, the admin_state_up value's schema type is string. This changes it to a boolean, similar Mitchell's changes to fix #1741

### CODE REVIEW

**Comment by jtopjian** [comment]
@cvvs I apologize for being obtuse or too lazy to look this up, but the Security Group modification does not change the actual syntax in the resource, right?

**Comment by cvvs** [comment]
It does not. In my local testing, the results of an apply were the same before and after.

**Comment by jtopjian** [comment]
It sounds like a good idea to me, then! :+1: 

I don't work with the network resources, but that change also make sense.

**Comment by trumant** [comment]
:+1: This was an annoyance.

**Comment by jtopjian** [comment]
@cvvs I just ran this through the acceptance test suite and had to make a minor change:

https://github.com/cvvs/terraform/blob/master/builtin/providers/openstack/resource_openstack_compute_instance_v2.go#L761

needs to be:

```
rawSecGroups := d.Get("security_groups").(*schema.Set).List()
```

All tests passed after that.

If you make that change, maybe ping one of the Terraform guys and let them know that all tests are passing -- that should expedite this into master.

**Comment by dupuy** [comment]
This PR works like a charm for my existing deployments, but when creating a new terraform.tfstate file, I am getting a Terraform crash with `terraform-provider-openstack: panic: interface conversion: interface is *schema.Set, not []interface {}`

**Comment by jtopjian** [comment]
@dupuy Right - that's the same error I get when running the acceptance tests. Changing line 761 will resolve it. It's interesting that existing states work.

**Comment by cvvs** [comment]
Thanks for the fix. I ran into that this past week, but hadn't had a chance to track it down. I don't know why I didn't see it earlier because I did a lot of creates and destroys, including starting with no state.

**Comment by dupuy** [comment]
I actually still ran into another crash after apply the line 761 fix - I had to make a similar change (twice) on line 554 as well - I have submitted this as a PR against cvvs/terraform: https://github.com/cvvs/terraform/pull/1.

I think that there are still other remaining issues (although less critical than a terraform crash). For example, after fixing the second crash, I see the following as output from terraform
```
    security_groups.2662085388: "https-external" => "https-external"
    security_groups.3271157693: "web-internal" => "web-internal"
    security_groups.3275750968: "" => "ssh-external"
    security_groups.3814588639: "default" => "default"
```
where the former security group that was changing ("ssh-internal") is rendered as an empty string, and the other (unchanged?) entries are also printed (which could be appropriate if those security groups had been destroyed/recreated because of other changes, but that is not the case here).

**Comment by jtopjian** [comment]
@dupuy Nice catch. 

Do you think the behavior you're seeing is fixed in #2008?

**Comment by dupuy** [comment]
I got the crash on a working branch which was effectively 0.5.2+#2008+#1848+your fix, I suppose the "missing name" thing could be due to the remove before add ordering in #2008.

**Comment by cvvs** [comment]
I haven't had an opportunity to run the acceptance tests since my test tenant is use by my team for the rest of this week. Hopefully this weekend or early next next week.

I'm still getting the hang of git (Hg user), so feel free to smack... er direct me, regarding proper merging etiquette.

**Comment by dupuy** [comment]
With your acceptance of my PR, and your merge from hashicorp master (I think), the commits on this PR are getting a bit messy.

Probably the best thing to do is to `git rebase hashicorp/master` (you will need to setup hashicorp as a remote if you haven't done this already).  That will make your master a straight branch from the head, and remove the extraneous merges (including my PR) leaving just your and my commits (so instead of seeing 10 commits in the PR, you will only see the first four - your two and my two).  At that point it could probably be merged at the hashicorp side.

**Comment by cvvs** [comment]
OK, this has gotten so ugly, that I think I'm just going to abandon it, and try again. Any disagreement?

**Comment by dupuy** [comment]
A fresh PR would be fine.  Create a new branch (not master) off of hashicorp/master (`git checkout -b openstack-resource-sets hashicorp/master`) and then you can cherry-pick the four commits from before, and submit that branch as a new PR referencing this one.

**Comment by cvvs** [comment]
Going to try again, this time with panache.

**Comment by justinclayton** [comment]
Has there been any movement on this? If anyone needs help I may be willing to dig into it, depending on the level of complexity.

**Comment by jtopjian** [comment]
@justinclayton it looks like this made its way to #2284.

**Pull request closed without merging**
