### PR TITLE
provider/cloudstack: performance improvements

### PR DESCRIPTION
**Pull request by svanharmelen**
Again a few tweaks to improve performance and also introduced a cidr_list attribute for all firewall related resources.

### CODE REVIEW

**Comment by svanharmelen** [comment]
@phinze while your at it... :wink: Could you also do a quick review on this one? I run all CloudStack acceptance tests on this branch successfully.

**Comment by svanharmelen** [comment]
@catsby noticed your online :stuck_out_tongue_closed_eyes: Any change you can have a look this PR and PR #3992?

**Comment by phinze** [comment]
Gave the code a once over, looks reasonable to me! Thanks for running the acceptance tests as well, that's a big help.

**Comment by svanharmelen** [comment]
:+1: Thanks!

**Pull request merged**
