### PR TITLE
provider/aws: Added Usage Plan Key resource

### PR DESCRIPTION
**Pull request by Ninir**
## Description
This adds the API Gateway usage plan key, based on the following API: https://docs.aws.amazon.com/apigateway/api-reference/link-relation/usageplankey-create/

## Related issues
Follow up of https://github.com/hashicorp/terraform/pull/12542
Might resolve other issues too.

## Tests
```bash
$ make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSAPIGatewayUsagePlanKey_'     
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/03/18 19:30:46 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSAPIGatewayUsagePlanKey_ -timeout 120m
=== RUN   TestAccAWSAPIGatewayUsagePlanKey_importBasic
--- PASS: TestAccAWSAPIGatewayUsagePlanKey_importBasic (25.35s)
=== RUN   TestAccAWSAPIGatewayUsagePlanKey_basic
--- PASS: TestAccAWSAPIGatewayUsagePlanKey_basic (123.42s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	148.800s
```

## TODOs
- [x] Add the API Gateway Usage Plan Key resource
- [x] Add validation
- [x] Add the documentation
- [x] Add test cases
- [x] Add import tests
- [x] Compile & test

### CODE REVIEW

**Comment by Ninir** [comment]
All ok on from my point of view :)

```bash
$ make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSAPIGatewayUsagePlanKey_'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/03/20 11:13:52 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSAPIGatewayUsagePlanKey_ -timeout 120m
=== RUN   TestAccAWSAPIGatewayUsagePlanKey_importBasic
--- PASS: TestAccAWSAPIGatewayUsagePlanKey_importBasic (34.73s)
=== RUN   TestAccAWSAPIGatewayUsagePlanKey_basic
--- PASS: TestAccAWSAPIGatewayUsagePlanKey_basic (180.61s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	215.377s
```

**Comment by Ninir** [comment]
@stack72 Hi Paul,

You're 100% right. Due a typo on my side, the import was working for... usage plan, not usage plan keys.
As the `import` command only takes two parameters as far as I know, i.e. the resource type & resource name, there are no possibilities to handle such import I guess. 

Removing that part.

**Comment by stack72** [comment]
In that case, we look good here! thanks for the work

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSAPIGatewayUsagePlanKey_'       ✭
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/03/20 13:50:03 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSAPIGatewayUsagePlanKey_ -timeout 120m
=== RUN   TestAccAWSAPIGatewayUsagePlanKey_basic
--- PASS: TestAccAWSAPIGatewayUsagePlanKey_basic (155.47s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	155.496s
```

Paul

**Comment by Ninir** [comment]
Thanks for the quick review Paul, as always. 👍

**Comment by stack72** [comment]
you make these thing easy to review @Ninir :) you always use clear PR descriptions and it's usually the questions we need to ask

**Pull request merged**
