### PR TITLE
TLS: Adding public key to resource output

### PR DESCRIPTION
**Pull request by simar7**
This pull request targets: https://github.com/hashicorp/terraform/issues/4134

Signed-off-by: Simarpreet Singh <simar@linux.com>

### CODE REVIEW

**Comment by simar7** [comment]
Okay, the CI build failed. Going to look into fixing this shortly.

**Comment by simar7** [comment]
yay all green! @apparentlymart, @radeksimko mind giving this a look when you have time to see if this is okay?

**Comment by apparentlymart** [comment]
Hi @simar7... sorry I took so long to respond to you on this one.

Thanks for working on this! I took your work here and added an additional feature of generating OpenSSH-formatted public keys so that this resource can also be used for SSH credentials. My updated patch is in #4606. Once another Terraform collaborator has reviewed it we should hopefully be able to get this merged.

**Comment by stack72** [comment]
@apparentlymart can you have a look at this one and see if you feel it is ready to merge now that #4606 was merged?

@simar7 please can you rebase this PR so that it can be merged cleanly?

Thanks

**Comment by apparentlymart** [comment]
#4606 superseded this patch, incorporating this feature plus the SSH public key format. I forgot to close this one out back when I merged that one, but I'll do that now. Thanks for the reminder, @stack72!

**Pull request closed without merging**
