### PR TITLE
providers/vsphere: recreate virtual machine if template changes

### PR DESCRIPTION
**Pull request by akshaykarle**
Quite new to terraform and vsphere, but I've been having issues with updating templates not actually recreating the vm, so thought of looking into this.

This may be a possible solution but happy to hear any feedback anyone may have.

### CODE REVIEW

**Comment by akshaykarle** [comment]
Hello,

Is there anything I could do to help get this PR merged? It is stopping us from adopting terraform at my current stint. Would appreciate an update/feedback.

**Comment by jkraj** [comment]
What if one expects to reconfigure a VM instead of recreating using the same template?

**Comment by akshaykarle** [comment]
@jkraj my understanding of having ForceNew is that, if the template has changed, it should recreate the entire vm. if the template stays the same but other properties of the vm are changed it may not require recreating the template.

The problem right now is that we are updating our template with a later version, but since it doesn't recreate the vm, it fails to run terraform apply. Having a ForceNew should recreate the vm only if it has changed. If the template is the same as before it shouldn't recreate the vm.

**Comment by stealthybox** [comment]
Maybe there should be an option that parametizes ForceNew, so that this isn't a breaking change.

something like `update_template = true`

does terraform detect whether a template changed right now?
have you verified that this PR fixes your problem?

**Comment by apparentlymart** [comment]
Hello @akshaykarle, and thanks for working on this!

As part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it.

[The vSphere provider](https://github.com/terraform-providers/terraform-provider-vsphere) -- and, in particular, the virtual machine resource -- are currently in the process of being revamped somewhat, with the goal of supporting more of the available features. Unfortunately this means that to re-target this change to the new repository may require some restructuring :confounded:.

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Pull request closed without merging**
