### PR TITLE
Update Travis to use Go 1.6

### PR DESCRIPTION
**Pull request by jen20**

### CODE REVIEW

**Comment by apparentlymart** [comment]
:+1: from the GoSF 1.6 launch party :grinning:

**Comment by apparentlymart** [comment]
(go fmt failures notwithstanding :grinning:)

**Comment by jen20** [comment]
Hey @apparentlymart you're in SF at the moment? And I will fix the fmt...

**Comment by stack72** [comment]
/me chants merge merge merge merge merge

**Pull request merged**
