### PR TITLE
Security: Upgrade version of golang.org/x/crypto to latest

### PR DESCRIPTION
**Pull request by rafalpotempa**
**Description**

`golang.org/x/crypto v0.0.0-20191202143827-86a70503ff7e` is found to be vulnerable due to possibility of DOS attack, while allowing to panic under verification of specifically crafted ssh-ed25519 or sk-ssh-ed25519@openssh.com public key (CVSS 3 Score: 7.5).

**References**

- https://github.com/golang/crypto/commit/bac4c82f69751a6dd76e702d54b3ceb88adab236
- https://groups.google.com/forum/#!topic/golang-announce/3L45YRc91SY
- https://packetstormsecurity.com/files/156480/Go-SSH-0.0.2-Denial-Of-Service.html

**Changes proposed in this pull request**

- Upgrade of `golang.org/x/crypto` to latest version.

### CODE REVIEW

**Comment by rafalpotempa** [comment]
I hope that any of you will look at those changes.

**Comment by danieldreier** [comment]
@rafalpotempa thanks for reporting this! We're looking into it.

**Comment by alisdair** [comment]
@rafalpotempa Thanks for bringing this to our attention! I've upgraded the `crypto` dependency on the 0.12 branch in #24928, and it will go out in an upcoming 0.12 release.

Since you opened this PR, a new version of `crypto` has been released (20200510223506-06a226fb4e37). I'd like to make sure that the master branch has at least the same version. If you wouldn't mind updating to that version, I'd be happy to merge this PR onto master for a future 0.13 release.

**Comment by rafalpotempa** [comment]
Great, thank you!
@alisdair I'v just updated it to latest :)

**Pull request merged**
