### PR TITLE
Initial SQS support

### PR DESCRIPTION
**Pull request by johnewart**
Initial support for making / updating / removing SQS queues; feedback welcome.

### CODE REVIEW

**Comment by radeksimko** [comment]
@johnewart Thanks for the contribution,
have you looked at https://github.com/hashicorp/terraform/pull/1888 ? It has already tests + docs, maybe it's worth investing time into testing & reviewing that one instead?

**Comment by catsby** [comment]
@radeksimko I poked @johnewart to submit this, he had mentioned he had it started. 
#1888 has `unknown repository` as a source, which if I recall means the author pulled the branch down(?). The commits are still available, it seems...

I imagine we can likely combine the two, or just use #1888. I'd like to hear back from @mzupan on his branch.

**Comment by radeksimko** [comment]
@catsby you're right... @mzupan apparently created the PR from master of his fork and then force-pushed over it... :cry:

**Comment by pmoust** [comment]
@radeksimko @catsby sorry just read you were discussing this, here is how to get a branch over a PRs head on GH @ https://github.com/hashicorp/terraform/pull/1888#issuecomment-101556313

**Comment by johnewart** [comment]
I see it now -- they're quite similar and that one already has tests so I'm fine with whichever makes more sense (or a combination of the two). I'll see if there's anything drastically different, but it didn't look like there was at fist glance.

**Comment by catsby** [comment]
LGTM, thanks!

**Pull request merged**
