### PR TITLE
SNS Platform Application Support

### PR DESCRIPTION
**Pull request by megaqube**
Based on @dalehamel's original pull request implementation for SNS Application Support.

Added Import support.

Tested for GCM and APNS platform types. Unit tests added with API Credentials extracted out to Environment variables.

Website Documentation updated.

### CODE REVIEW

**Comment by Xirel** [comment]
Currently tests pull GCM and APNS_SANDBOX credentials from the Environment so that I can run these tests locally without accidentally committing them, but Travis CI test are failing due to this.

**Comment by radeksimko** [comment]
@Xirel To answer your question in
https://github.com/hashicorp/terraform/pull/3335#issuecomment-239994896

Environment variable is a good approach, we can set those as part of the build in Travis for nightly runs. That said `os.Exit` is almost never a good thing when used in tests. Have a look at how we deal with the same issue in [`aws_vpc_peering_connection`](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_vpc_peering_connection_test.go#L19-L24) 😉

**Comment by Xirel** [comment]
@radeksimko Thanks for pointing out the example. I've made the updates to the SNS_APPLICATION tests.

**Comment by Xirel** [comment]
@radeksimko - any other suggestions on what I need in order to get this feature merge in?

**Comment by iceycake** [comment]
Any update on this?  I need this feature.

**Comment by bigkraig** [comment]
@radeksimko @stack72 dudes! @Xirel fixed up the os.Exit, is it good to merge?

**Comment by mikecook** [comment]
@radeksimko @stack72 Fixes made, anything else needed for merge?

**Comment by bigkraig** [comment]
@radeksimko @stack72 any help?

**Comment by mikecook** [comment]
@clstokes This is the PR that needs some love. Thanks!

**Comment by jedi4ever** [comment]
👍 for merging this in

**Comment by Xirel** [comment]
Pretty please... 🙏

**Comment by bigkraig** [comment]
@radeksimko @stack72 👀

**Comment by iceycake** [comment]
Waiting for a long time.  Can this PR have some love?

**Comment by jdori** [comment]
I'm also waiting on this PR.

**Comment by danscan** [comment]
Very excited to see this PR merged!  @stack72, can you please review this?  😁

**Comment by rokka-n** [comment]
Lets do it!

**Comment by danscan** [comment]
This seems to have slipped through the cracks!  Hey, @mitchellh could you please merge or give some quick feedback?  :D

**Comment by stack72** [comment]
Hi all

this hasn't slipped through the cracks by any means - I promise we will get to this soon. We need to get the test accounts in place to set this up as part of our nightly tests before we merge it. This is on my to-do list to pick up :)

Paul

**Comment by Xirel** [comment]
👍

**Comment by mikecook** [comment]
Rebased on new master to resolve conflict.

**Comment by rokka-n** [comment]
Can somebody give it a green light, please

**Comment by mikecook** [comment]
@stack72 @mitchellh @radeksimko @clstokes This PR just had its 6 month birthday on the 18th. It would love to be merged. Pretty please?

**Comment by mikecook** [comment]
@stack72 Is this still held up by test accounts?

**Comment by tazjin** [comment]
tumbleweed

**Comment by etartakovsky** [comment]
That's the only thing stopping us from completely relying on terraform for our AWS infrastructure deployment at the moment. 

@stack72 guys, there are real production users and huge systems waiting for that for half a year already. Can you let us know what's preventing this from being merged? Can we do something to speed up the process?

**Comment by bigkraig** [comment]
⚰️

**Comment by kwent** [comment]
Let's do it. How can i help ?

**Comment by grubernaut** [comment]
Hello all, 

First of all, I'm extremely sorry that this PR has sat here for so long without response, review, or resolve. This is absolutely our fault, and definitely not something that I'm proud of. We absolutely need to be better at reviewing and managing pull requests from outside contributors. Ignoring the obvious issue we have in this area will only serve to injure the amazing and tremendous open source community we already have. 

Part of the provider-level split out will also help us out in this area. With only 6 full-time employees working on Terraform Providers, a lot of issues and PR's had the habit of "slipping through the cracks". With the split-out, we're able to give a finer granularity of permissions to outside contributors, enabling outside maintainers with full commit-rights on provider repositories that they manage. This incredible help from our talented community is going to be essential moving forwards, and we couldn't do it without all your help. 

That being said, it looks like some tremendous work has already been done to migrate this PR to the new `aws` provider. Thus, I'm going to close this PR and I'm currently reviewing the new PR here: https://github.com/terraform-providers/terraform-provider-aws/pull/1101. 

I sincerely thank you all for your patience, continued support, and understanding for the past year that this has been open.

**Pull request closed without merging**
