### PR TITLE
Create a scrollable and fixed navigation bar

### PR DESCRIPTION
**Pull request by jweir**
The last few days I was pretty heavily in the Terraform docs.  Lots of going back and forth between links, trying to find the right link, or just browsing the Provider resources.

It was frustrating.

Since the navigation and document are static, context would be lost.  Say I clicked on aws_db_instance.  I would no longer see the related RDS Resources.  If I would scroll down to those I would no longer see the documentation.

So I created this patch.

docs-scroll-sample

It would be awesome if there were a pure CSS rule set to do this.  And perhaps there is?

Caveats:  How will this look in browsers which always show scroll bars?  It will need some styling. And, it works on an iPad, but has some artifacts.

### CODE REVIEW

**Comment by apparentlymart** [comment]
Thanks for working on this! I agree that the AWS provider docs (in particular) have got pretty unwieldy now that there are so many resources in it.

However, I wonder if rather than introducing multiple scrolling regions into the page, which may not be clear to all users, we should instead try to fix the navigation structure so that it's more usable. For example, what if we make the navbar show only the resources in the selected service, and only show the service headings for the others? This will probably require us to have an introductory page for each service so that there's somewhere for the headings to link to, but that could be pretty useful anyway to help new users understand the relationships between all of the resources for a particular service.

As far as I know none of the other providers yet have enough resources that this is so problematic.

Were you able to test the double-pane scroll on a mobile phone browser? IIRC on phones the navbar renders above the content, so having each of the areas scroll separately will presumably not work well there.

**Comment by jweir** [comment]
You are welcome and my pleasure.

On the point of confusion with a multiple scroll region – there are plenty of documentation interfaces which follow the layout: Amazon's AWS's documentation, Read The Docs, Rails API and so on.

There are many ways to skin a cat – taking the approach of not expanding the AWS Provider categories could also work well, but it will require some labor.

The patch I created will not affect the mobile/small screen layout at all – although the AWS Provider docs are nearly unusable on a mobile phone right now.

I'd say try it out and see how it feels. I'm using it locally and much happier with the docs.

**Comment by apparentlymart** [comment]
@jwelr fair enough on your assertion that lots of other things follow this multi-pane approach. In particular it seems very common in the AWS docs.

I did give it a try and it's definitely growing on me. I think the only thing that feels odd about it is that the header and footer scroll along with the main page content, which feels strange somehow. I think it'd feel more comfortable if the header and footer were fixed in place with the scroll regions between them, but of course that'd be a much more radical change than you were aiming at here.

@captainill do you have any opinions here?

**Comment by jweir** [comment]
The header with logo is workable without much effort.  The footer would require a change in layout – the footer's height is very large.

Will adding a persistent header and/or footer improve the usability of the navigation?

**Comment by jweir** [comment]
Ping on this. I stepped in the AWS docs again today after a hiatus, and it is rather difficult to use.

**Comment by captainill** [comment]
@jweir We actually just talked about this internally and know the experience is lacking in the docs. We are planning a general refresh on terraform.io and the docs are a part of that. Definitely want to level up the context/navigation. Not sure when it will land but I will take a look at this patch for inclusion in that launch.

**Comment by stack72** [comment]
Hi @jweir 

We are planning some changes to the website over the coming months. I am going to close this PR out - I am sorry it wasn't given the time needed, but these style of changes will be included going forward :)

Thanks for all the effort here

Paul

**Pull request closed without merging**
