### PR TITLE
Add support for PG_CONN_STR ENV var

### LINKED ISSUE #32525: Support env vars for pg backend connection string / username, password and dbname as input
### Terraform Version

```shell
➜  ~ terraform version
Terraform v1.3.7
on linux_amd64
```

### Use Cases

As of now, the `pg` backend type only support a hard coded `conn_str` in the `backend` configuration according to:  https://developer.hashicorp.com/terraform/language/settings/backends/pg#configuration-variables and also the code does not read any environment variables: https://github.com/hashicorp/terraform/blob/main/internal/backend/remote-state/pg/backend.go#L22-L26.

In contrast, eg the `azure` remote-state supports multiple env vars to be able to not check-in sensible data into your terraform code. -> https://github.com/hashicorp/terraform/blob/main/internal/backend/remote-state/azure/backend.go#L78

This would be a great feature for the `pg` backend. 

### Attempted Solutions

-

### Proposal

Add support for environment variables, either one singe `conn_str` but having flexibility using `DB_NAME`, `DB_USER`, `DB_PASSWORD`, `DB_HOSTNAME` would be awesome.

### References

_No response_

### PR DESCRIPTION
**Pull request by janaurka**
Describe in detail the changes you are proposing, and the rationale.

Somwhat Fixes #32525 , but only the easy way, by supporting the whole `conn_str` as environment variable. Theoretically being able to build this using `DB_NAME`, `DB_USER`, `DB_PASSWORD` and `DB_HOSTANAME` (or so) would be even more interesting.

## Target Release

(not important, just convenient)

1.4.x

## ENHANCEMENTS 

A user can now (eg by the pipeline, which is running `terraform`) set the `conn_str` as environment variable, instead of having the requirement to set it inside the `backend` block. This mainly prevents the `backend` block from containing a secret (mostly the database password). 

In the [`backend_test.go`](https://github.com/hashicorp/terraform/blob/main/internal/backend/remote-state/pg/backend_test.go#L29-L31) this is basically done by setting `DATABASE_URL` (which imho is a somehow not nice variable name, that’s why I have called it `PG_CONN_STR`, `PG` for the Backend type and `CONN_STR` which is the name of the variable). I have not replaced `DATABASE_URL` in the tests with `PG_CONN_STR`, since I am not aware of where I would need to replace this and I avoid to break the tests (for no very good reason).

### CODE REVIEW

**Comment by crw** [comment]
Thanks for this submission. @remilapeyre FYI for your review. I'll also check with the core team if this is something we can review. Thanks!

**Comment by janaurka** [comment]
@crw || @remilapeyre : do you have an update on this?

**Comment by crw** [comment]
I do not; for backends, the [CODEOWNER](https://github.com/hashicorp/terraform/blob/main/CODEOWNERS) needs to review and then generally the core team does a basic review and merges.

**Comment by remilapeyre** [comment]
Hi @janaurka, thanks for your PR. I will test the change and post a review shortly

**Comment by remilapeyre** [comment]
Hi @janaurka, to detect properly when the environment variable is not set the second argument of `EnvDefaultFunc()` will need to be `nil`. I think we should also use the `PGDATABASE` environment variable for this as it is the one used by the PostgreSQL utilities.

I wrote a patch that does this, updates the documentation and add tests.

[0001-Add-test-documentation-and-use-PGDATABASE-for-the-en.patch](https://github.com/hashicorp/terraform/files/10896836/0001-Add-test-documentation-and-use-PGDATABASE-for-the-en.patch)

@crw it seems that I lost the write permissions on this repo so I don't receive review requests and can't push on Pull Requests, can you please check if I can get them back?

**Comment by crw** [comment]
@remilapeyre I'll look into it. Thanks for reviewing this request.

**Comment by crw** [comment]
Apologies for the late follow-up. @remilapeyre I am not sure if this changed, but the belief is that outside contributors have never had write access to the repo. Unfortunately we are not able to grant it at this time. 

@janaurka it sounds like this would be approved if you applied the patch provided by @remilapeyre. If you make that happen, I'll put this in front of the core team for sign-off.

**Comment by janaurka** [comment]
Hey @crw 
 
Alright, thank you for the update. I’ve applied the patch from @remilapeyre and pushed it. (Sorry for the force push, I’ve first applied and pushed the patch as a commit from me, but credit where credit is due, it’s now the correct commit from @remilapeyre ).

The digital content errors seems to be from files which were not touched by us.

cheers
Jan

**Review by remilapeyre — APPROVED** [review]

**Comment by crw** [comment]
OK I'll get this in the queue. Thanks!

**Comment by apparentlymart** [comment]
Thanks for working on this, @janaurka, and thanks @remilapeyre for reviewing it! I'm going to merge this now.

FWIW, outside contributors definitely _did_ have write access to this repository in the past, and I was one of them before I became an employee! But I think it _is_ true that repositories in the "hashicorp" organization no longer have outside contributors as a general rule -- as part of general security-related standardization -- so seems like we'll need to find a new approach to dealing with the parts of this codebase that are maintained by community members. I don't have a ready answer and this PR isn't the right place to get into the weeds about that anyway, but @crw just wanted to note it in case you want to follow up about this in a different place.

For now though, I'll merge this on @remilapeyre's behalf. Thanks again!

**Comment by crw** [comment]
> FWIW, outside contributors definitely did have write access to this repository in the past, and I was one of them before I became an employee!

Thanks for this clarification! The person who told me this should have known better. :D

**Pull request merged**
