### PR TITLE
Provider/aws/fix acceptance test log bucket

### PR DESCRIPTION
**Pull request by PayscaleNateW**
* Factored out the s3 buckets used in the various test configs
* Made sure to define the logs bucket as part of the config.  Since it wasn't defined, it was giving me errors for not being found
* Also fixed up the bucket naming.  I don't think the bucket should be named <name>.s3.amazonaws.com. I think that adding the domain there is a convention for accessing the bucket, but the name should just be <name>. So for example, the name might be mylogs.73178316, and then in the logging config bucket you list mylogs.73178316.s3.amazonaws.com

### CODE REVIEW

**Comment by stack72** [comment]
Hi @PayscaleNateW 

Thanks so much for the work here. I just ran the tests and all worked except the first:

```
=== RUN   TestAccAWSCloudFrontDistribution_importBasic
--- PASS: TestAccAWSCloudFrontDistribution_importBasic (1146.30s)
=== RUN   TestAccAWSCloudFrontDistribution_S3Origin
--- FAIL: TestAccAWSCloudFrontDistribution_S3Origin (29.99s)
	testing.go:265: Step 0 error: Error applying: 1 error(s) occurred:

		* aws_s3_bucket.s3_bucket_origin: NoSuchBucket: The specified bucket does not exist
			status code: 404, request id: C263F98949EC55D2
=== RUN   TestAccAWSCloudFrontDistribution_S3OriginWithTags
--- PASS: TestAccAWSCloudFrontDistribution_S3OriginWithTags (1182.16s)
=== RUN   TestAccAWSCloudFrontDistribution_customOrigin
--- PASS: TestAccAWSCloudFrontDistribution_customOrigin (1192.55s)
=== RUN   TestAccAWSCloudFrontDistribution_multiOrigin
--- PASS: TestAccAWSCloudFrontDistribution_multiOrigin (1161.27s)
=== RUN   TestAccAWSCloudFrontDistribution_noOptionalItemsConfig
--- PASS: TestAccAWSCloudFrontDistribution_noOptionalItemsConfig (1071.63s)
```

I believe the issue here is that you changed the config that the first test depends on but didn't pass in both buckets to that test config

Please can you update the test and then we can merge this? :)

Thanks for all the work here

Paul

**Comment by PayscaleNateW** [comment]
Ah I noticed that as well... Wasn't sure if it was a separate issue to be fixed next, because the error there only happens in the sequence of tests, not when you run TestAccAWSCloudFrontDistribution_S3Origin by itself. I think I figured out the issue:

Both TestAccAWSCloudFrontDistribution_importBasic and TestAccAWSCloudFrontDistribution_S3Origin use the *same* config, with the same random int for their aws buckets. The random int doesn't get regenerated. Probably want to regenerate it so each test is independent.

**Comment by stack72** [comment]
YEs, now that the test has been updated to take the strings, the config must also be done to do that in the test :)

**Comment by PayscaleNateW** [comment]
I just pushed another commit that fixes that issue, by supplying the import test and the s3config test with different random ints, so they don't collide.

Acceptance tests seem to be passing for me!

**Comment by stack72** [comment]
Nice work @PayscaleNateW 

Thanks for the work here! Will get this tested now and then merged asap

P.

**Comment by stack72** [comment]
New test looks good :)

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSCloudFrontDistribution_S3Origin'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/10/03 23:15:38 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSCloudFrontDistribution_S3Origin -timeout 120m
=== RUN   TestAccAWSCloudFrontDistribution_S3Origin
--- PASS: TestAccAWSCloudFrontDistribution_S3Origin (1007.72s)
=== RUN   TestAccAWSCloudFrontDistribution_S3OriginWithTags
--- PASS: TestAccAWSCloudFrontDistribution_S3OriginWithTags (1176.16s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	2183.897s
```

**Comment by PayscaleNateW** [comment]
Awesome, thanks so much @stack72!

**Pull request merged**
