### PR TITLE
Upgrade to Go 1.17

### PR DESCRIPTION
**Pull request by apparentlymart**
**NOTE:** This is currently a draft because we need to first verify that all of our test and release infrastructure has suitable Go 1.17 machine images available before making this switch, but I'm sharing it now in order to give time to reflect on the information below and to have something to test against.

I'd like to merge this as soon as our test/release infrastructure is ready to accept it so that we can include the changes in at least a few alpha releases before we reach the v1.1.0 prerelease period, so I'd appreciate early review of anything that seems concerning here.

---

This includes the addition of the new `//go:build` directive form in addition to the legacy `// +build` notation, as produced by gofmt to ensure consistent behavior between Go versions. The new directives are all equivalent to what was present before, so there's no change in behavior.

Go 1.17 continues to use the Unicode 13 tables as in Go 1.16, so this upgrade does not require also upgrading our Unicode-related dependencies.

This upgrade includes the following breaking changes which will also appear as breaking changes for Terraform users, but that are consistent with the Terraform v1.0 compatibility promises.

- On MacOS, Terraform now requires macOS 10.13 High Sierra or later. Our compatibility promises allow for us to drop support for older versions of supported operating systems.

This upgrade also includes the following breaking changes which will appear as breaking changes for Terraform users that are inconsistent with our compatibility promises, but have justified exceptions as follows:

- The `cidrsubnet`, `cidrhost`, and `cidrnetmask` functions will now reject IPv4 CIDR addresses whose decimal components have leading zeros, where previously they would just silently ignore those leading zeros.

  This is a security-motivated exception to our compatibility promises, because some external systems interpret zero-prefixed octets as octal numbers rather than decimal, and thus the previous lenient parsing could lead to a different interpretation of the address between systems, and thus potentially allow bypassing policy when configuring firewall rules etc.

This upgrade also includes the following breaking changes which could _potentially_ appear as breaking changes for Terraform users, but that do not in practice for the reasons given:

- The Go `net/url` package no longer allows query strings with pairs separated by semicolons instead of ampersands, which was an addition suggested by a W3C HTML spec contrary to the corresponding IETF HTTP RFCs.

    This primarily affects HTTP servers written in Go, and Terraform includes a special temporary HTTP server as part of its implementation of OAuth for "terraform login", but that server only needs to accept URLs created by Terraform itself and Terraform does not generate any URLs that would be rejected.

### CODE REVIEW

**Comment by apparentlymart** [comment]
I was hesitating to change our `go` declaration in `go.mod` because we currently have it set to Go 1.14 and I don't know if there were any opt-in behavior changes implied by `go 1.15` or `go 1.16`, but I suppose I can just give that a try and see if there's any observable behavior change in the toolchain or in our tests. I'll do that now.

**Comment by apparentlymart** [comment]
The release process uses Docker images from the same source as the CircleCI checks in this repository, so the fact that our tests are succeeding here (in a PR where I updated the CircleCI config) suggests that the same will be true for the release process, and so I think we're unblocked from merging this once approved and thus I'm going to un-draft it now.

**Comment by apparentlymart** [comment]
I added the `go.mod` changes as a separate commit here so we can more easily see the effect of this opt-in change independently of the mandatory changes for Go 1.17.

The tests all seem to still pass and the build still seems to work so it seems good to go.

**Comment by jbardin** [comment]
Hmm, I though `go mod tidy -go=1.17` was supposed to always put all the indirects in a separate block, but it doesn't seem to complain about this format either. No big deal since they would end up being merged eventually.

**Review by jbardin — APPROVED** [review]

**Comment by apparentlymart** [comment]
After some further reflection with fresh eyes today, we concluded that we can't actually justify the breaking changes to the various `cidr...` functions on the same grounds that the Go team did, because the impact of the old behavior is considerably lower for our focused use-case only of constructing new addresses vs. actually validating or acting on the addresses given as input.

For that reason, I've pushed an additional commit here which forks the relevant subset of the Go `net` package and disables the new checks, thus restoring the previous behavior. This forked version is actually derived directly from [the Kubernetes project's similar solution](https://github.com/kubernetes/utils/commit/ca7b03c9e86696e8237e39ddc63083ea7ccf455e), modified only to replace the Kubernetes-related comments with corresponding Terraform-related comments.

This extra commit therefore mitigates the related item from the list of breaking changes I wrote up in the PR summary above, and so if we move ahead with this I'll exclude that one from my corresponding updates to the Terraform changelog.

**Review by jbardin — APPROVED** [review]

**Comment by apparentlymart** [comment]
I'm going to merge this now, but before I do I just want to create some breadcrumb links to the upstream Go discussions about each of the breaking changes I discussed in the initial writeup, in case in future we find ourselves wanting to revisit those decision processes and understand what motivated them:

* Go 1.17 requiring macOS 10.13 or later: golang/go#23011 (a general, ongoing discussion about Go's macOS version support policy, not yet resolved at the time I'm writing this)
* The IP address parsing change: golang/go#30999
* The `net/url` query string parsing change: golang/go#25192

**Pull request merged**
