### PR TITLE
website/intro: remove outdated examples section

### PR DESCRIPTION
**Pull request by mildwonkey**
I had removed the outdated examples from our repository, not realizing they were referenced by this (also outdated) examples section. `examples` has been superseded by our learn content and is not necessary or worth keeping up-to-date.

### CODE REVIEW

**Review by alisdair — APPROVED** [review]
👋 

Can we add useful redirects for these pages? The URLs are quite prominent on Google. Maybe from `/intro/examples/*` to `https://learn.hashicorp.com/terraform` would be good enough.

**Comment by mildwonkey** [comment]
Good suggestion, do you know where or how those get managed @alisdair ?

**Comment by alisdair** [comment]
I think it's by [editing this redirects file on the `terraform-website` repo](https://github.com/hashicorp/terraform-website/blob/master/content/redirects.txt).

**Comment by mildwonkey** [comment]
Thanks! I opened https://github.com/hashicorp/terraform-website/pull/1506 for the redirects (alas, it does not support `*`)

**Pull request merged**
