### PR TITLE
fix up some other badly saved deps.

### PR DESCRIPTION
**Pull request by freeformz**
Looks like 237e257f3793faa3258c0e1e1b6731cd8b1087a4 may have been using an older version of godep.

### CODE REVIEW

**Comment by freeformz** [comment]
because I saved with `godep save github.com/onsi/ginkgo/ginkgo ./...` ginkgo can be installed with either `go install ./...` (which will compile / install everything including ginkgo or `go install github.com/hashicorp/terraform/vendor/github.com/onsi/ginkgo/ginkgo`

**Comment by phinze** [comment]
Hi @freeformz - sorry I missed this. I'm confused where the `ginkgo` dependency is coming in though? I just built a release from a blank `$GOPATH` w/ no troubles here.

**Comment by freeformz** [comment]
@phinze Lol so. I brain farted on ginkgo. I thought I saw that being used in a Makefile somewhere. So I re-pushed w/o that.

**Comment by phinze** [comment]
:+1: cool this looks reasonable - thanks again!

**Pull request merged**
