### PR TITLE
internal/getproviders: switch to ProtonMail/go-crypto/openpgp

### PR DESCRIPTION
**Pull request by rolandshoemaker**
Switches away from the deprecated, unmaintained golang.org/x/crypto/openpgp module, and replaces it with the (mostly) drop-in, maintained, github.com/ProtonMail/go-crypto/openpgp.

The only logic change here is that CheckDetachedSignature now requires a openpgp/packet.Config, and enforces key/signature expirations. This means we now need a way to supply a config during testing, so that we can continue to use keys/signatures which are actually expired.

This is part of a wider effort by the Go Security team to remove uses of golang.org/x/crypto/openpgp from the Go ecosystem.

### CODE REVIEW

**Comment by radeksimko** [comment]
Related: https://github.com/hashicorp/terraform/pull/32056

**Comment by rolandshoemaker** [comment]
I understand this may not be a simple decision, so I'll try to provide some further context that may be valuable in terms of guiding the conversation. At Google we are working internally to replace all usages of golang.org/x/crypto/openpgp with github.com/ProtonMail/go-crypto/openpgp, the maintainers of which we have worked with to make the module as much of a drop-in replacement as possible.

golang.org/x/crypto/openpgp was deprecated for a handful of reasons (see https://github.com/golang/go/issues/44226), namely that there were no active maintainers, and no appetite from the core Go team to take over ownership. While the Security team is willing to fix critical security issues that are reported to us, there are a number of known issues in the package that we have no intention of prioritizing (see [this search](https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen+openpgp++in%3Atitle)), and a number of inherent API design flaws that cannot be solved in a backwards compatible way (hence why github.com/ProtonMail/go-crypto/openpgp cannot be a truly drop-in replacement).

While github.com/ProtonMail/go-crypto/openpgp does increase the scope of supported functionality, I believe it is on balance a security win to switch to, as it removes a number of openpgp foot-guns (namely it actually enforces key and signature validity periods, which golang.org/x/crypto/openpgp just ignores), and is actively maintained.

**Comment by MasonM** [comment]
This appears to be a duplicate of https://github.com/hashicorp/terraform/pull/32056

**Comment by crw** [comment]
Thanks @MasonM, we were aware although it helps to have the details posted in both tickets. I've left both open so as to not shut down the ongoing conversation, including the further arguments made by @rolandshoemaker in https://github.com/hashicorp/terraform/pull/33131#issuecomment-1531749336.

**Comment by rolandshoemaker** [comment]
Sorry @MasonM, I hadn't seen your PR when working on this, and am happy to defer to your change. @crw I will leave it up to you what to do with this change (i.e. if you want to leave it open for contextual purposes), but I'll move over to #32056 for further comments.

**Comment by crw** [comment]
Thanks for that comment @rolandshoemaker - I am tracking both of these, and will keep both in the conversation when we are deciding which to review.

**Pull request closed without merging**
