### PR TITLE
[WIP] [provider/cloudflare] Implement Cloudflare Page Rules

### PR DESCRIPTION
**Pull request by OJFord**
This PR is a work in progress, towards #9040, where page rules are a popular would-be-feature.

- [x] Basic structure; creating page rules
- [x] Action validator - complex beast, depends on action type
- [x] Action default func - " "
- [x] Complete Read, Update, Delete implementations
- [ ] Tests

### CODE REVIEW

**Comment by OJFord** [comment]
@elithrar - I'm seeing the error:

> error unmarshalling the JSON response: json: cannot unmarshal string into Go value of type int      
 
coming out of `cloudflare.API.CreatePageRule` - but if I check myself (i.e. web UI or curl) it's created successfully.

```go
	res, err := api.makeRequest("POST", uri, rule)
	if err != nil {
		return errors.Wrap(err, errMakeRequestError)
	}
	var r PageRuleDetailResponse
	err = json.Unmarshal(res, &r)
	if err != nil {
		return errors.Wrap(err, errUnmarshalError)
	}
```
([cloudflare-go/pagerules.go](https://github.com/cloudflare/cloudflare-go/blob/f51439e7713acb59ca73bb2db90f4421bfe83f51/pagerules.go#L115-L123))

I don't see that this can be an issue with what I'm passing in?

**Comment by cemo** [comment]
hey @OJFord what is the state of this issue. It seems it is almost finished.

**Comment by OJFord** [comment]
@cemo It's functional, from manual testing, but I haven't had a chance to add any proper tests which I assumed would be required for it to be accepted? (Thanks for reminding me!)

However it's also blocked on cloudflare/cloudflare-go#108 (which was accepted a couple of days ago, and is now being tracking internally at Cloudflare) - since the CF library throws an error when it receives the API response whether or not it was a success. This means that `terraform apply` errors, despite having correctly created a page rule.

**Comment by cemo** [comment]
Thanks for clarification.

**Comment by OJFord** [comment]
That Cloudflare API bug was fixed today (cloudflare/cloudflare-go#108) - so I'll be able to finish this up soon, likely not before the next weekend though.

**Comment by stack72** [comment]
ping @OJFord 

is this still an active PR?

**Comment by OJFord** [comment]
@stack72 Thanks - yep, it's still something I'd very much like to finish and use myself (there's interest in #9040 too).

I'm just swamped with coursework & an exam at the moment; didn't get to it when I said I might a week or so ago. I've set a reminder for the weekend 25/26.

The status is that it's implemented and fully functional per manual testing, but pretty bare on test cases. If you're happy with it, that's great, but I suppose I just assumed you'd want better coverage and have kept it marked WIP on that basis. :slightly_smiling_face:

**Comment by thasmo** [comment]
@OJFord Thanks for your work on this!

**Comment by OJFord** [comment]
@thasmo :slightly_smiling_face: - thanks for the notification, I hadn't forgotten about this, and I've a much clearer plate now so I should be able to finish it off this week.

I believe I need to move it over to terraform-providers/terraform-provider-cloudflare though. The closed issue on this repo (#9040) that spawned this PR has moved here: terraform-providers/terraform-provider-cloudflare#3.

**Comment by OJFord** [comment]
Closing in favour of terraform-providers/terraform-provider-cloudflare#12.

**Pull request closed without merging**
