### PR TITLE
Upgrade hcl and go-cty

### LINKED ISSUE #22404: Argument expansion error in output expression during validation walk
### Terraform Version

```
$ terraform version
Terraform v0.12.7-dev
```

### Terraform Configuration Files

```hcl
variable "mapping" {
  default = {
    "a" = ["b", "c"]
  }
}

locals {
  mapping = [
    for x, y in var.mapping : [
      for z in y : {
        "${z}" = x
      }
    ]
  ]
}

output "x" {
  value = merge(flatten(local.mapping)...)
}
```

### Crash Output

https://gist.github.com/apparentlymart/e1e86b3299c679df1b66d64e2ee86fb5

### Expected Behavior

The value for output `x` after applying should be:

```
{
  "b" = "a"
  "c" = "a"
}
```

### Actual Behavior

Terraform produces an error during the validation walk:

```
Error: Invalid expanding argument value

  on expand-arguments-error.tf line 18, in output "x":
  18:   value = merge(flatten(local.mapping)...)

The expanding argument (indicated by ...) must be of a tuple, list, or set
type.
```

### Steps to Reproduce
Using the above configuration, run `terraform apply`

### Additional Context

Interestingly, evaluating the same expression in `terraform console` works as expected:

```
$ terraform console
> merge(flatten(local.mapping)...)
{
  "b" = "a"
  "c" = "a"
}
```

The console is evaluating expressions in a different mode than in the validate walk, so perhaps there's something unusual about the validate walk that is making this fail.

This bug is likely to be upstream in the HCL repository, e.g. [in the `FunctionCallExpr` evaluation logic](https://github.com/hashicorp/hcl2/blob/65731f3310963019707cb1ee851b7c12779a4f62/hcl/hclsyntax/expression.go#L262). It looks like this isn't correctly handling the case where the expression to expand is `cty.DynamicVal`, so perhaps that's the root cause; if so, adding `cty.DynamicPseudoType` to the set of allowed types is probably enough to fix it, because there's already a test in there for if the value is unknown. If this theory does turn out to be true then this'll be a PR in the HCL repository first, and then a vendor update PR in here.

This value would be unknown here during the validation walk because it's derived from a variable, and variables don't get concrete values until the plan walk.

### References

This was originally reported in [a community forum topic](https://discuss.hashicorp.com/t/when-are-expanding-arguments-actually-allowed/2288).

### LINKED ISSUE #24377: Terraform console crashes when passing incorrect arguments to setsubtract() function
### Terraform Version

```
Terraform v0.12.23
```

### Terraform Configuration Files

No file, just a commands
```hcl
terraform console
setsubtract([["a"], "b", null], ["a"])
```

### Debug Output

https://gist.github.com/allexandr112/6020d1b5da7f2aef98b880ef89511045

### Crash Output

https://gist.github.com/allexandr112/b35d5f362bf7649f276d63ec680a9d24
### Expected Behavior

I suppose it should be some error message, but no crash
### Actual Behavior

Terraform console crashes and panic
### Steps to Reproduce

1. `terraform console`
2. `setsubtract([["a"], "b", null], ["a"])`
### Additional Context

```
Linux 4.15.0-88-generic x86_64 x86_64 GNU/Linux amd64
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
```

### LINKED ISSUE #24805: “panic: runtime error: index out of range” using a combination of null and splat
### Terraform Version

```
v0.12.24
```

### Terraform Configuration Files

```hcl
locals {
  x = concat([1, null]...)
}
```

### Debug Output

https://gist.github.com/izeau/8be4f9671c27a2404eee74ca82a9a29c#file-trace-out

### Crash Output

https://gist.github.com/izeau/8be4f9671c27a2404eee74ca82a9a29c#file-crash-log

### Expected Behavior

I expected it to fail with an error, but not a panic. The generic one would have been nice:

```
Invalid value for "seqs" parameter: argument must not be null.
```

### Actual Behavior

💥 

### Steps to Reproduce

```shell
$ terraform console <<< 'concat([1, null]...)'
```

### LINKED ISSUE #25150: Crash when using terraform_remote_state data source
### Terraform Version
```
Terraform v0.13.0-dev
```

Built from 0b38ab30782462153ea8b82613b9e2eb39bc3dc7

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.12"
}

data "terraform_remote_state" "random" {
  backend = "remote"
  config = {
    organization = "alisdair-v2"
    workspaces = {
      name = "terraform-random"
    }
  }
}

output ids {
  value = data.terraform_remote_state.random.outputs.random
}
```

### Debug Output
https://gist.github.com/alisdair/7c02fc9340d4686e8797d9a2b8fec777#file-output-log

### Crash Output
https://gist.github.com/alisdair/7c02fc9340d4686e8797d9a2b8fec777#file-crash-log

### Expected Behavior
Apply succeeds and displays outputs from Terraform Cloud workspace.

### Actual Behavior
Crash.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### References
I found this while trying to reproduce #25148.

### PR DESCRIPTION
**Pull request by alisdair**
Upgrades:
- hcl v2.6.0: https://github.com/hashicorp/hcl/releases/tag/v2.6.0
- cty v1.5.0: https://github.com/zclconf/go-cty/releases/tag/v1.5.0

Issues:
- Fixes #22404
- Fixes #24377
- Fixes #24805 
- Fixes #25150

### CODE REVIEW

**Comment by alisdair** [comment]
@mildwonkey I tried to spelunk for all the related issues I could find, but I could have missed some! Feel free to add others to the PR description or otherwise link them.

**Comment by grobie** [comment]
@alisdair @jbardin Thanks for this! Will this be part of the next Terraform version? I ran into a Terraform crash when using the hashicorp/terraform-provider-kubernetes-alpha provider, and it seems it's also the result of https://github.com/zclconf/go-cty/pull/55

```
panic: interface conversion: interface {} is *cty.unknownType, not bool
```

**Comment by alisdair** [comment]
@grobie Yes, this dependency upgrade will be released in Terraform 0.13.0-beta2.

**Comment by grobie** [comment]
@alisdair Thanks. It appears Terraform 0.13.0 is still not advised to be used in production and some time out. Any chance to release a new 0.12.x version with the fixes for these terraform panics? It's really hard to use the current kubernetes-alpha provider as Terraform always crashes when attempting to render a diff for a K8s deployment.

**Comment by alisdair** [comment]
We do not currently have plans to release another 0.12.x version. All our efforts are on releasing 0.13.0, hopefully in just a few weeks time.

**Pull request merged**
