### PR TITLE
implements base64{enc,dec} interpolation funcs

### LINKED ISSUE #3320: feature request: new built-in function base64(string)
I would like to include in a cloud-config (which is formatted using YAML) section my custom certification authority certificate, which contains newlines. If I use directly with ${file} cloud-config will fail parsing.

What do you think if we can make a function like base64("mystring") which interpolates to the encoded base64 format?

Use-case:

```
#cloud-config

[...]

write_files:
  - path: "/etc/ssl/etcd/ca-chain.cert.pem"
    permissions: "0600"
    owner: "etcd"
    encoding: "base64"
    content: |
      ${base64(file("etcd-ca-chain.cert.pem"))}
```

WDYT?

### PR DESCRIPTION
**Pull request by glerchundi**
fixes #3320

Signed-off-by: Gorka Lerchundi Osa <glertxundi@gmail.com>

### CODE REVIEW

**Comment by stack72** [comment]
@glerchundi this looks very cool. I would love to see 1 of the acceptance tests updated to include an encrypted string just to see it in action :)

**Comment by apparentlymart** [comment]
Thanks for working on this! :+1:

**Comment by apparentlymart** [comment]
I've merged this along with a follow-up commit c3d15a2336d783e4f73c4c81c20bf076cb5bd848 to add these functions to the interpolation docs. Thanks again!

**Comment by radeksimko** [comment]
@apparentlymart Maybe a nitpick, but I still think it's worth asking before this reaches release - How about renaming these functions to `base64encode` and `base64decode`?

I have not seen `enc` or `dec` as a conventional abbreviations used anywhere, in fact `dec` could even evoke _decimal_.

**Comment by stack72** [comment]
I'd love to see some examples of usage added to the examples repo

**Comment by apparentlymart** [comment]
@radeksimko a fair point... also none of the other function names include abbreviated words. I think I agree with you. Shall I make a followup commit to fix this now, or do you think it's worth seeking other input first?

**Comment by radeksimko** [comment]
@apparentlymart I think two maintainers in agreement should be enough :wink: 
Make a followup PR, I'll merge it.

**Comment by glerchundi** [comment]
Cool, thanks! :)

**Pull request merged**
