### PR TITLE
OpenStack: add functionality to attach FloatingIP to Port

### PR DESCRIPTION
**Pull request by JeanMertz**
A couple of notes:

* I didn't write any tests, because I apparently can't even *break* any tests. Whenever I change random test values in `_test.go` files, and run `go test ./...`, all tests still pass. As soon as I manage to get a test-workflow going, I will try my hand at the tests.

* I tested this on my own OpenStack environment, and things work as expected.

* The possibility to actually manage ports is introduced here: #1789

### CODE REVIEW

**Comment by mitchellh** [comment]
LGTM, same with tests here

**Comment by josephholsten** [comment]
@mitchellh is this waiting on anything to merge?

**Comment by josephholsten** [comment]
@phinze this seems ready to merge

**Comment by DanyC97** [comment]
+1

**Comment by phinze** [comment]
LGTM - thank you!

**Pull request merged**
