### PR TITLE
Document that ValidateFunc works on maps.

### PR DESCRIPTION
**Pull request by alexsomesan**
This change documents that `ValidateFunc` is also available for use on TypeMap attributes.
Support for map validation has been added through https://github.com/hashicorp/terraform/pull/3505

### CODE REVIEW

**Comment by alexsomesan** [comment]
@bflad Thanks for pointing that out! I wasn't aware about the TypeSet. I've rephrased. PTAL.

**Comment by bflad** [comment]
Sorry if my mention made the situation more unclear. 😅

I wonder if it might make sense to phrase it in the positive as a specific list:

ValidateFunc currently only works for:
* TypeString, TypeInt, and TypeFloat attributes
* TypeMap attribute keys when declared outside the Elem
* TypeMap, TypeList, and TypeSet attribute values when declared inside an Elem of TypeString, TypeInt, and TypeFloat

Or maybe in the negative as:

ValidateFunc currently has no effect when declared with TypeList / TypeSet attributes except when declared inside the Elem schema to validate TypeString, TypeInt, and TypeFloat attribute values.

I'm fine any which way though!

**Comment by alexsomesan** [comment]
@bflad I think the bullet-list formatting is actually way cleaner.

I'm a bit confused though about the inclusion of `TypeList` as I can't seem to find a call to `schema.ValidateFunc` within `func (m schemaMap) validateList(..)` like there is in `func (m schemaMap) validateMap(..)`. Does that mean `TypeList` actually doesn't do validation? Or am I missing something?

**Comment by apparentlymart** [comment]
I'm not sure we need to specifically mention the behavior when inside a nested `schema.Resource`, since the behavior there is identical to when it's in a top-level `schema.Resource`. Validation happens the same way for nested attributes as it does for top-level ones.

If we want to be specific here maybe we should describe the constraints in terms of actual attribute values:

> `ValidateFunc` is honored only when the schema's `Type` is set to `TypeInt`, `TypeFloat`, `TypeString`, `TypeBool`, or `TypeMap`. It is ignored for all other types.

**Pull request merged**
