### PR TITLE
Add github_team data source

### PR DESCRIPTION
**Pull request by raphink**
This PR adds a data source for Github teams.

### CODE REVIEW

**Comment by stack72** [comment]
Hi @raphink 

This is looking good - unfortunately, before merging, would you be able to write some documentation for it?

Thanks

Paul

**Comment by raphink** [comment]
@stack72 sorry, I thought I had. I will certainly do that.

**Comment by raphink** [comment]
@stack72 added doc

**Comment by stack72** [comment]
Hi @raphink 

Thanks for adding the docs - these look great. On last check, the test is failing:

```
% make testacc TEST=./builtin/providers/github TESTARGS='-run=TestAccGithubTeamDataSource_noMatchReturnsError'                               ✭
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/05/21 00:45:36 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/github -v -run=TestAccGithubTeamDataSource_noMatchReturnsError -timeout 120m
=== RUN   TestAccGithubTeamDataSource_noMatchReturnsError
--- FAIL: TestAccGithubTeamDataSource_noMatchReturnsError (1.25s)
	testing.go:274: Step 0, expected error:

		Error refreshing: 1 error(s) occurred:

		* data.github_team.test: 1 error(s) occurred:

		* data.github_team.test: data.github_team.test: Could not find team with slug: non-existing

		To match:

		Not Found


FAIL
exit status 1
FAIL	github.com/hashicorp/terraform/builtin/providers/github	1.260s
make: *** [testacc] Error 1
```

**Comment by raphink** [comment]
Ah, my bad. It should be fine now.

**Comment by stack72** [comment]
LGTM now sir :)

```
% make testacc TEST=./builtin/providers/github TESTARGS='-run=TestAccGithubTeamDataSource'                                           
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/05/22 15:27:19 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/github -v -run=TestAccGithubTeamDataSource -timeout 120m
=== RUN   TestAccGithubTeamDataSource_noMatchReturnsError
--- PASS: TestAccGithubTeamDataSource_noMatchReturnsError (0.73s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/github	0.746s
```

**Comment by raphink** [comment]
Great thanks!

**Pull request merged**
