### PR TITLE
Remove usage of http.DefaultClient

### PR DESCRIPTION
**Pull request by jefferai**

### CODE REVIEW

**Comment by apparentlymart** [comment]
Thanks for this... Though I am not sure I understand the motivation. Was this discussed somewhere else?

**Comment by jefferai** [comment]
@apparentlymart Yes, it spun off of an internal discussion. I'm on a crusade to remove usage of http.DefaultClient as it very easily causes strange and hard-to-diagnose problems like hashicorp/vault#700. As http.DefaultClient is literally just a `&http.Client{}`, except it shares state implicitly instead of explicitly, I'm removing it across our projects.

The next step in Terraform will be going through dependencies and ensuring that, where possible, code paths in dependencies that use DefaultClient are instead given their own clients. I'll submit a PR for that later today.

Tests should certainly be run to ensure that nothing was relying on this behavior, but in that case the right fix isn't to use DefaultClient, it's to pass in the properly-configured client to the library for usage.

**Comment by jefferai** [comment]
Hold off on merging this for the moment; there is an upstream fix going into packngo, and once it does I'll update this.

**Comment by brockoffdev** [comment]
:+1: This worked well as a fix for https://github.com/hashicorp/vault/issues/700

**Comment by jefferai** [comment]
Done -- ready to merge!

**Pull request merged**
