### PR TITLE
Update github.com/Azure/azure-sdk-for-go@v31.0.0

### PR DESCRIPTION
**Pull request by tamalsaha**
Fix https://github.com/hashicorp/terraform/issues/22085

Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by tamalsaha** [comment]
Travis tests have passed successfully. I'm not sure why the status is not updating in GitHub.

**Comment by jbardin** [comment]
Hi @tamalsaha,

Thanks for the contribution.

I think this is something we're going to have to look at more closely. The `+295,140` lines is a bit disconcerting here (though not necessarily a problem if it's due to some largely unused packages). Also a blanket upgrade of all dependencies between major releases is something we have to carefully review as well, especially since it effects the internal plugin protocol with grpc and probuf updates.

**Comment by tamalsaha** [comment]
Hi @jbardin , FWIW, the changes to unrelated packages are rather changes in `patch` versions as evident from the diff on the `vendor/modules.txt` file.

https://github.com/hashicorp/terraform/pull/22087/files?file-filters%5B%5D=.txt&hide-deleted-files=true#diff-31be3fbc3cb3d1a36172f2111034b4ce

When I run `go mod tidy`, these changes are automatically picked up by `go` compiler. If you folks prefer, I can use `replace` rules to keep then same as before.

I understand why dependency changes can be scary. But the longer you wait, the scarier it gets.

**Comment by pselle** [comment]
> I understand why dependency changes can be scary. But the longer you wait, the scarier it gets.

The counterpoint here is that it makes it difficult for us to pin-point the source of an issue when a regression happens and its related to a dependency, if those are updated in one go.

Might I suggest reducing the scope of this changeset, to help us help you, so that we can get this merged, rather than having a large PR that goes stale?

**Comment by tamalsaha** [comment]
@pselle , All the code change I really want is this 2 lines:
https://github.com/hashicorp/terraform/pull/22087/files#diff-9bedbd138a1872ee7c10f252c8710229R84

tf-update

All the dependency changes are coming from `go mod`. I have tried to trim those but I was not successful. I am totally cool if you can create a fresh pr with just two-line change. :pray:

**Comment by vancluever** [comment]
Incidentally, I've just added #22247 as we need it the ACME provider (the outdated deps here are creating conflicts with lego's Azure DNS provider).

Not too sure what else is being done here, but upgrading the deps without changing the API version in the remote state backend seems to work fine (pending results of integration tests). Both the binary and `github.com/hashicorp/terraform/backend/remote-state/azure` build without issue.

PS: @tamalsaha I'm not too sure why https://github.com/hashicorp/terraform/pull/22087/files#diff-9bedbd138a1872ee7c10f252c8710229R20 was necessary but it kind of creates a circular dependency. Core should not be depending on any providers. Can you tell us why this was needed?

**Comment by tamalsaha** [comment]
From #22805, we are working on a project that depends on both terraform and terraform-provider for Azure. We are using Go modules and the latest version of these repos as dependency.

```
	github.com/hashicorp/terraform v0.12.4
	github.com/terraform-providers/terraform-provider-azurerm v1.31.0
```

So, I also need to use a common version of `github.com/hashicorp/go-azure-helpers`. So, I tried to update that to `github.com/hashicorp/go-azure-helpers@v0.5.0`, @vancluever .

I agree that this repo should not depend on `github.com/terraform-providers/terraform-provider-azurerm` . Do you think I should create the sender using the following snippet?

```
import (
"github.com/hashicorp/go-azure-helpers/sender"
)

sender.BuildSender("AzureRM")
```

If you can also update `github.com/hashicorp/go-azure-helpers@v0.5.0` in your pr that will be great.

**Comment by vancluever** [comment]
@tamalsaha I've added #22248 along with what looks like the necessary corrections to `arm_client.go`. Should be good to go now.

Note that it's been added off of a separate PR, but it also includes #22247, so if you want to try that with a `go get` you should be able to.

**Comment by tamalsaha** [comment]
Thanks a lot, @vancluever ! Once your prs are merged, this pr can be closed.

**Pull request closed without merging**
