### PR TITLE
Ansible provisioner

### PR DESCRIPTION
**Pull request by radekg**
Source: https://github.com/radekg/terraform-provisioner-ansible/commit/47d943565097e3d5b3612c056f220df807343bb6.

Local and remote Ansible Terraform provisioner, bastion host support. No Windows support.

There is a lot of information in the [readme](https://github.com/radekg/terraform/blob/provisioner-ansible/builtin/provisioners/ansible/README.md) and [examples](https://github.com/radekg/terraform/blob/provisioner-ansible/builtin/provisioners/ansible/examples/README.md).

### CODE REVIEW

**Comment by alexkreidler** [comment]
any updates on this?

**Comment by kbcz1989** [comment]
still nothing?

**Comment by wangzw** [comment]
Is there any reason that this pull request does not get reviewed or merged?

**Comment by danieldreier** [comment]
Hi @radekg -

I'm closing this PR because we announced tool-specific (vendor or 3rd-party) provisioner deprecation in [mid-September 2020](https://discuss.hashicorp.com/t/notice-terraform-to-begin-deprecation-of-vendor-tool-specific-provisioners-starting-in-terraform-0-13-4/13997). Additionally, we added a deprecation notice for tool-specific provisioners in 0.13.4. On a practical level this means we will no longer be reviewing or merging PRs for these built-in plugins.

For the time being, the best option is to continue distributing this as a plugin. I'm acutely aware of the limitations of this approach, but it's the less-bad option compared to coupling provisioner development to the Terraform Core release lifecycle. We believe the benefit to users of having provisioner development decoupled from core, exceeds the convenience of having these provisioners built in to core. We want to provide a better user experience in the future, and our hope here is that the ability to improve, fix and repair provisioners without us blocking their development, much like providers, will help make a strong case for what's next.

I think it’s also important to highlight that we have no plans to remove the generic provisioners or the pluggable functionality during Terraform's 1.0 lifecycle. 

Please feel free to reach out to me or Petros Kolyvas if you would like to talk more about this change.

**Comment by radekg** [comment]
Hey @danieldreier, thanks for a thorough update.

Just to confirm. The plugin functionality will be available regardless of the deprecation of the provisioners through Terraform 1.0.

**Pull request closed without merging**
