### PR TITLE
provider/fastly: Add support syslog logging to Fastly provider

### PR DESCRIPTION
**Pull request by aadidenko**

### CODE REVIEW

**Comment by stack72** [comment]
Hi @aadidenko 

Sorry to have to ask you, but can you please rebase this against master and we can have a look at it

Thanks

Paul

**Comment by stack72** [comment]
ping @aadidenko :)

**Comment by mtougeron** [comment]
@aadidenko Hi, any chance you can finish this PR? I'd love to be able to use it. Thanks.

**Comment by mtougeron** [comment]
Also, would it be possible to support `response_condition` for the `syslog`?

**Comment by aadidenko** [comment]
Hi, Sorry, I was very busy.
I will finish in the coming days

**Comment by mtougeron** [comment]
@aadidenko No worries. Thanks for the update :)

**Comment by aadidenko** [comment]
I pushed the changes to https://github.com/terraform-providers/terraform-provider-fastly/pull/16

**Pull request closed without merging**
