### PR TITLE
Rundeck 2.7.3 1

### PR DESCRIPTION
**Pull request by BobVanB**
Rebased on Terraform v0.9.2-dev (6e827d794035294344f81cab1ac6bd3e649f469f+CHANGES)

### CODE REVIEW

**Comment by BobVanB** [comment]
rebase https://github.com/hashicorp/terraform/pull/11382

**Comment by tombuildsstuff** [comment]
Hi @BobVanB 

Thanks for your contributions here :)

From what I can see this PR supersedes #11382 - should that PR be closed in favour of this one?

Thanks!

**Comment by BobVanB** [comment]
Yup. Closed it.

**Comment by apparentlymart** [comment]
Hi @BobVanB! Thanks for working on these enhancements.

When I ran the acceptance tests for this I got some errors. Most of them I was able to quickly fix by just renaming some things (the log level is "ADVANCED" rather than "INFO" or "DEBUG" and one of the test configs says `schedule_cron` instead of just `schedule`) but there was one I couldn't quite make sense of:

```
--- FAIL: TestAccJob_basic (0.24s)
	testing.go:273: Step 0 error: Error applying: 1 error(s) occurred:
		
		* rundeck_job.test: 1 error(s) occurred:
		
		* rundeck_job.test: rundeck schedule_cron format is incorrect, missing ?
		Rundeck schedule must be formated like a cron expression, as defined here: http://www.quartz-scheduler.org/documentation/quartz-2.2.x/tutorials/tutorial-lesson-06.html
	testing.go:337: Error destroying resource! WARNING: Dangling resources
		may exist. The full state and error is shown below.
		
		Error: Check failed: got something other than NotFoundError (HTTP Error %!i(int=403)) when getting key
		
		State: <no state>
```

Do you know what's going on here? It seems like Rundeck has a more constrained interpretation of cron format than I'm accustomed to, where it requires a `?` somewhere.

**Comment by BobVanB** [comment]
@apparentlymart Hi, thnx for the review. I will look in to it tomorrow when i am at work.
Rundeck uses the folloing cron notation:
http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger.html

**Comment by rumenvasilev** [comment]
Guys, are there any plans to get this request merged as it contains two very important functionalities to make this provider fully functional:
- [nodes_selected_by_default](https://github.com/hashicorp/terraform/pull/13156/files#diff-97df485d9a36dbf526c105a77b93cdafR116)
- [notifications](https://github.com/hashicorp/terraform/pull/13156/files#diff-97df485d9a36dbf526c105a77b93cdafR245)

Without these two, this plugin is not that useful if you have to deal with lots of jobs, because it doesn't allow setting notification prefs, neither chooses the nodes that the filter has selected. And to make the jobs work you have to manually go to each and every job and edit it, to activate these features (especially nodes_selected_by_default).

**Comment by apparentlymart** [comment]
This is on my list to look at but since it requires some merge conflict work I've not been able to get to it yet. I will take a look as soon as I can.

**Comment by apparentlymart** [comment]
This was migrated to terraform-providers/terraform-provider-rundeck#3, as part of separating the providers out into separate repositories.

**Pull request closed without merging**
