### PR TITLE
Improving Rundeck provider: scheduler

### PR DESCRIPTION
**Pull request by samber**
Hi guys,

Rundeck provider cannot create scheduled jobs (understand cronjobs).
This PR make it possible ;-)

Also upgraded go-rundeck library.

### CODE REVIEW

**Comment by samber** [comment]
ping @apparentlymart ;-)

**Comment by Freyskeyd** [comment]
LGTM 👌

**Comment by nanoz** [comment]
Oh, nice ! I really need this :)

**Comment by stack72** [comment]
Hi @samber 

Sorry taken for the time taken to getting this up and tested! Thanks so much for this work :)

```
% make testacc TEST=./builtin/providers/rundeck
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/12/13 12:00:04 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/rundeck -v  -timeout 120m
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccJob_basic
--- PASS: TestAccJob_basic (1.73s)
=== RUN   TestAccPrivateKey_basic
--- PASS: TestAccPrivateKey_basic (0.32s)
=== RUN   TestAccProject_basic
--- PASS: TestAccProject_basic (0.45s)
=== RUN   TestAccPublicKey_basic
--- PASS: TestAccPublicKey_basic (1.48s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/rundeck	3.997s
```

This LGTM!

Paul

**Pull request merged**
