### PR TITLE
core: fixing annoying git diffs

### PR DESCRIPTION
**Pull request by svanharmelen**
As these files are recreated/updated every time when calling `make dev` of `make bin`, git show these diffs every time which is a little annoying. So I thought to just update them and get it over with :wink:

### CODE REVIEW

**Comment by mitchellh** [comment]
Oh, these shouldn't be ignored, why aren't they just getting updated when they change?

**Comment by svanharmelen** [comment]
How do you mean? They are updated locally, but that results in different files than in master. So I thought to just commit the updated versions so they wouldn't be changing all the time. Or am I missing some insights?

**Comment by phinze** [comment]
@svanharmelen I believe you need to `make updatedeps` to get the latest `golang.org/x/tools/cmd/stringer` package, which recently changed the way it generates these files.

**Comment by svanharmelen** [comment]
Whoeps! Should have checked that already of course... Thx!

**Pull request closed without merging**
