### PR TITLE
Google Cloud: Dataflow Resource

### PR DESCRIPTION
**Pull request by coffeepac**
Adds the Dataflow resource as an available google resource.  

There is no go API for the dataflow service so I have wrapped the gcloud cli in a helper library and am calling that.  The helper library is 22acacia/terraform-gcloud.  Because of this, I have made running the tests for this an additional environment variable as both java and the gcloud cli are required to run them.

### CODE REVIEW

**Comment by coffeepac** [comment]
rebase was uglier then expected, but the additional change was to add docs.

**Comment by coffeepac** [comment]
@sparkprime is this PR likely to be accepted at all?  It is based on a lib I've written which is a wrapper around the gcloud command line tool.  I have to do something similar for creating pods in clusters by wrapping the kubectl cli.  I imagine the answer will be the same for both PRs. 

I'm asking because if its not going to be accepted I'll create a google_exp provider and shove these guys over there.  Then whoever wants that piece of the binary can go grab it.

**Comment by sparkprime** [comment]
Yes and no -- I don't think calling gcloud is a good idea but I like your style :)

I presume there will be an API soon (I need to ask some people) in which case your PR can be a starting point, as the attributes etc should be the same (hopefully).

Re: Kubernetes, Are you aware of the work going on in https://github.com/hashicorp/terraform/tree/f-kubernetes-provider

**Comment by coffeepac** [comment]
I have asked about a go api and its not on the horizon.  There is too much interaction between job creation and what goes on inside the job.  But yeah, the hope was that I've made the entry point of my lib clean enough that it can be easily swapped out with a real API if that ever happens.

I am not aware of that provider.  I will go check it out.  thanks!

**Comment by sparkprime** [comment]
I just looked at gcloud alpha dataflow and it didn't look like it was possible to create a job.  Can you tell me what exactly your code does here, or link me to the library code that wraps gcloud.

**Comment by coffeepac** [comment]
you are correct, gcloud does not have the ability to create or modify dataflow jobs.  you can only do that by using the java sdk.  the lib that does this is over here:  https://github.com/22Acacia/terraform-gcloud  That lib checks that both java and gcloud are installed.  So the create section calls 'java -cp <jarfile> <class name> <other..  stuff...>' and executing that creates the job.  

its also possible to update a running job but that's not supported by my wrapper lib yet.  its more complicated and I'm not sure I understand the mechanics of updating a running dataflow job well enough to code it up.

**Comment by sparkprime** [comment]
Since Terraform is fundamentally for creating persistent resources, how do you map this batch-oriented dynamic model on top of that?

What new capabilities does integrating Terraform get you, that you wouldn't get simply by having a couple of bash scripts to do this stuff?

**Comment by coffeepac** [comment]
dataflow jobs can be batch or streaming and for my use case we are mostly focused on spinning up long-running streaming jobs.  there will also be batch jobs but those are not the target.

we are using terraform for creating the rest of our infrastructure for this project so I'd rather only have one tool for all portions of the infrastructure instead of terraform for creating parts then when that's done, go run a bunch of bash scripts.

**Comment by sparkprime** [comment]
Ah I didn't know about the streaming case.  That puts this in the same category as pubsub so seems pretty reasonable.

It looks like there is an API available for doing at least some of what you want, so I don't think you'd need to run gcloud anymore:

https://developers.google.com/apis-explorer/#search/dataflow/dataflow/v1b3/

I'm not sure if you still have to run java to use the Java SDK, there is a create call there.

**Comment by coffeepac** [comment]
interesting, I've never used this browser before but how do I go from this link you've shared to an endpoint to hit?

**Comment by sparkprime** [comment]
It's like all the other Google APIs, there is a generated go wrapper here:

go-workspace/src/google.golang.org/api/dataflow/v1b3/dataflow-gen.go

**Comment by francesperry** [comment]
We intend for Dataflow to be used currently via the Java SDK or the alpha CLI. We don't encourage (nor document sufficiently ;-) going directly via the v1b3 API. We may change that in the future, but there is no timeline currently.

I don't have full context on your use case. Are you just looking to create basic job control functionality for an existing .jar containing a Dataflow java program?

**Comment by coffeepac** [comment]
@francesperry so I've heard!  A bunch :D  

I'm looking for job control functionality, yes.  CRUD, although the U is rather difficult in this case from an error handling point of view.  So much can go wrong and I'm not sure its wise to try and model all of the error states that could occur during a job update.

Is the v1b3 API okay for what I'm up to?  At the moment I've got a lib elsewhere that wraps the gcloud alph cli and presents CRD operations to terraform.

**Comment by coffeepac** [comment]
@sparkprime I'm going to close this PR.  I've decided to create a new more volatile resource called 'googlecli'.  Its over here:  https://github.com/22Acacia/terraform-provider-googlecli  It supports dataflow and replica controllers (if the kubenetes PR ever gets merged I'll switch to using that).  

mostly leaving this comment in case someone else wants a ready-made resource for creating dataflow jobs.

**Pull request closed without merging**
