### PR TITLE
provider/aws: Add `aws_ecs_task_definition` datasource to allow services to track the latest revision

### PR DESCRIPTION
**Pull request by builtinnya**
Implements #8449 

This PR contains the following:
- New datasource `aws_ecs_task_definition`
- ~~New interpolation function `max`~~ (added in #9692)
- The corresponding unit tests and acceptance tests
- The corresponding documentation updates

See #8449 for the detailed explanation of the why.

### CODE REVIEW

**Comment by gregwebs** [comment]
I am finding it impossible to use terraform with ecs without this functionality.

**Comment by gregwebs** [comment]
I am using this now, it works great, thank you!

@apparentlymart please get his merged in

**Comment by jsonmaur** [comment]
This really needs to be merged/addressed. Every other solution out there is super hacky, and requires maintaining two different docker images so terraform can safely rollback to the tag specified in the task definition when updating. This is a necessary feature for anyone using continuous deployment with ECS.

Any updates from the terraform guys?

**Comment by curena** [comment]
Status?

**Comment by curena** [comment]
So as a question, isn't it currently possible to provide the current resource *aws_ecs_task_definition*'s exported _revision_ attribute to the aws_ecs_service?

**Comment by hSATAC** [comment]
💯  
+1 to this.

**Comment by ColinHebert** [comment]
@jen20 Would it be possible to get eyes on this Pull Request?

**Comment by builtinnya** [comment]
I'm working on resolving the conflicts.
#9692 seems to add a better `max` interpolation function.

**Comment by builtinnya** [comment]
Done.

**Comment by curena** [comment]
Will this make it into the next release?

**Comment by ColinHebert** [comment]
@stack72 would you be able to review/approve this?

**Comment by curena** [comment]
Bump?

**Comment by stack72** [comment]
Hi all

This LGTM! Is this just a case of wanting to find details out of a latest version of a task definition? Or what other usecase does this actually solve? Right now, it just seems to set up a task def, pass that into the data_source and get itself back

Thoughts?

Paul

**Comment by curena** [comment]
The main use case is to be able to update a task definition as part of a CI build (outside of TF), and have Terraform correctly pull in the latest revision of the task and update its corresponding service accordingly.

**Comment by stack72** [comment]
@curena do you would then feed the result of the data source lookup into the ECS service?

**Comment by curena** [comment]
Correct.

**Comment by stack72** [comment]
Got it - will get this merged then :) It makes sense

I would like to get an example for the documentation to show how this would work

**Comment by curena** [comment]
Thanks. There's a pretty good example in the parent issue https://github.com/hashicorp/terraform/issues/8449.

**Comment by stack72** [comment]
ok, LGTM! The tests pass and I now understand the use-case

I will follow up with a more complete example in the documentation about what this will enable

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSEcsDataSource'                                                       ✭
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/01/31 17:23:28 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSEcsDataSource -timeout 120m
=== RUN   TestAccAWSEcsDataSource_ecsContainerDefinition
--- PASS: TestAccAWSEcsDataSource_ecsContainerDefinition (112.95s)
=== RUN   TestAccAWSEcsDataSource_ecsTaskDefinition
--- PASS: TestAccAWSEcsDataSource_ecsTaskDefinition (24.45s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	137.421s
```

**Pull request merged**
