### PR TITLE
provider/digitalocean: fix issue #3628 by accepting SSH fingerprints

### PR DESCRIPTION
**Pull request by aybabtme**
fix issue #3628 by accepting SSH fingerprints

### CODE REVIEW

**Comment by phinze** [comment]
LGTM - thanks @aybabtme!

**Comment by yebyen** [comment]
Is there a release coming soon?  I want to publish something on my blog for DigitalOcean users and this is still stuck in HEAD

**Comment by phinze** [comment]
@yebyen yep! going to cut a release next week. :+1:

**Comment by yebyen** [comment]
Awesome!  Thank you much

**Pull request merged**
