### PR TITLE
core: formalize internals to do graph transformation steps and walking over an AST tree for execution

### PR DESCRIPTION
**Pull request by mitchellh**
This is a huge huge huge refactor. It doesn't change any practical behavior and acceptance tests are still passing. No core unit tests were changed in this refactor, though many were added.

Brief background: Terraform internals have always been about building a graph from the configuration and walking it for execution. But Terraform core hasn't properly formalized the layers and as such they've historically been really nasty and intertwined (see: https://github.com/hashicorp/terraform/blob/8463c921027acde225bf549f674501212da99565/terraform/graph.go). As a result, it has exponentially gotten more difficult to add core features since adding the features generally introduced other seemingly unrelated regressions. 

To improve these, we decided to undertake a large refactor. The goal was to refactor graph creation and execution without changing any `Context` unit tests (the main API to Terraform core). Informally, the goal was to be "less YOLO" and more academic in our approach to Terraform core. 

To that end, we made the following changes:

* Terraform core now builds the graph through a series of simple _graph transformations_. These are transformations in the academic sense: a graph goes in, vertex replacement/rotation/etc. is done to transform the graph. 

* The existing graph.go soup has now been broken down into about 15 separate, simple graph transformations that are tested in isolation. 

* The graph now represents a _logical graph_ of the configuration, and only minimally represents what will actually be executed. In the prior graph, a graph node was only present if there were changes to execute. Now, the graph node is present, despite the execution perhaps being a no-op. 

* Various optimization passes are done across the graph to remove unnecessary nodes. This is related to the above point, we just aren't as aggressive as before.

* Evaluation is done by walking the graph, finding `GraphNodeEvalable` implementations, and evaluating them. 

* Evaluation is broken down into a series of `EvalNode`s, rather than a huge single 500 line function of yore. This both simplifies and complicates things. More on this in the "future improvements" section below. I would say its overall an improvement, however.

The result:

* Future TF core features can be cleanly added by adding new isolated graph transformations, new `EvalNode` implementations, and unit tests across all. 

* Many edge cases were found that affected TF core that we fixed. TF 0.4.0 should as a result be more stable in that regard.

Future improvements:

* `EvalNodes` are still rather clunky. I'd like to turn those into a pure graph as well, using the same graph transformation core, and just walking and executing the nodes. 

* Transitive reduction should be done across the DAG in order to get a minimal graph to simplify it visually. This is primarily aesthetic.

### CODE REVIEW

**Comment by amadeus** [comment]
wow

**Comment by knuckolls** [comment]
Really pleased to see this. Will review. :100: :star2: :+1:

**Comment by armon** [comment]
So amazing. This will be fantastic.
magic

**Comment by mitchellh** [comment]
So here is how we're going to do this. I'm just going to merge this. With @phinze I'm going to do a Google Hangout or Screenhero-based review of how it works, and we'll iron out any issues in master. 

As I said, a good amount of acceptance tests pass, and _all_ unit tests pass (unchanged from pre-refactor). So, while there might very likely be edge cases, I don't think we'll find them through an eyeball here. And this way we can start fixing some core issues that are on the issue tracker too.

**Comment by knuckolls** [comment]
If possible could you do a hangouts on air and record the hangout when you
do the walkthrough?

**Comment by mitchellh** [comment]
@knuckolls I don't see why not. I'll think about it to verify but at this time yes, I think that would be sane. Note this will likely be next week as @phinze is on vacation for a few days. :)

**Comment by mitchellh** [comment]
I'll be sure to update this issue with the link to it once we do. Again, in a few days.

**Comment by knuckolls** [comment]
Awesome. I've found recorded code walkabouts to be quite helpful for a new
codebase or a big PR like this one. Thanks!

**Comment by mitchellh** [comment]
@knuckolls Review Hangout: https://www.youtube.com/watch?v=suiuaKgaQ74

**Pull request merged**
