### PR TITLE
Fix `terraform force-unlock <lock_id>` for Consul backend

### PR DESCRIPTION
**Pull request by remilapeyre**
When locking was enabled with the Consul backend and the lock not properly
released, the `terraform force-unlock <lock_id>` command would do nothing as
its implementation would exit early in that case.

It now destroys the session that created the lock and clean both the lock and
the lock-info keys.

A regression test is added to TestConsul_destroyLock() to catch the issue if it
happends again.

Closes https://github.com/hashicorp/terraform/issues/22174

### CODE REVIEW

**Review by alisdair — APPROVED** [review]
Thanks!

**Comment by alisdair** [comment]
@remilapeyre Thank you for this fix! Unfortunately there's a conflict after merging #25842. Would you mind rebasing?

**Comment by remilapeyre** [comment]
Hi @alisdair, sorry I had missed your message, it should all be good now :)

**Review by alisdair — APPROVED** [review]
Thank you! 🙌

**Pull request merged**
