### PR TITLE
Add support for building packages for ppc64le platform

### PR DESCRIPTION
**Pull request by mkumatag**
This PR will add support compiling and packaging terraform for ppc64le platform

### CODE REVIEW

**Comment by apparentlymart** [comment]
Hi @mkumatag! Thanks for working on this.

I don't think we'll be able to move forward with this in the very short term because Terraform Core alone isn't very useful without also having builds of all of the providers for the new architecture, and that'd require some effort in our internal provider build/release tooling that we unfortunately don't have the cycles to do immediately.

I assume the goal here is to be able to run Terraform on PPC64 hosts in IBM Cloud? If this is intended as a first step on a longer arc of some other project, please let me know.

---

For our team's future reference, here's a non-exhaustive list of other things we might need to do before merging this:

- As noted above, we'll need to include this new architecture in the set of targets used when building providers, and have done enough subsequent provider releases for at least the most "strategic" providers to be installable on a `ppc64le` host.

- We may wish to adjust the "pretty architecture" rendering logic in our `hashicorp-middleman` library so that the download page can show a better name for this architecture rather than the fallback behavior of "Ppc64le". (@mkumatag, is there a preferred way to display the name of this architecture to end-users in documentation, as opposed to the compiler-oriented architecture string `ppc64le`? On some IBM Cloud pages I see references to "POWER8", but I believe that is a processor product family rather than an architecture.)

- We'll need to get some access to ppc64le hardware (or virtual hardware) so that we're able to do testing/etc in case we get any bug reports that are specific to this architecture.

- Consider whether to also add releases for aarch64 at the same time, so we can amortize some of this "new target architecture" cost across both changes.

There are probably some additional things here I'm not thinking of; it's been a long time since we last introduced a new architecture.

**Comment by james-crowley** [comment]
@apparentlymart I wanted to touch base on the revamping of your build process. I know Terraform just released `0.12`  in May and was hoping this was the revamping/reorganizing of your build process that you were referring too, thus opening the opportunity of adding support for more architectures. 

To answer your question on a "pretty" name for PowerPC, it would be `ppc64le`. Additionally for Z, Mainframe, it would be `s390x`. 

I can't speak for @mkumatag, but I know I would like to see `ppc64le` and `s390x`, as teams do have use cases where running Terraform remotely from a currently supported architecture is not going to work. They need to be able to run natively on their respective architectures.


> We'll need to get some access to ppc64le hardware (or virtual hardware) so that we're able to do testing/etc in case we get any bug reports that are specific to this architecture.

I would be happy to help get you(the Terraform team) access to both `ppc64le` and `s390x` resources. We have a couple ways to accomplish this, but it depends on how you want it set up.

One of the ways is to utilize Oregon State University's pipeline resources. Here are some links to check out, https://osuosl.org/services/powerdev/ and http://osuosl.org/services/ibm-z/. I have more experience with the  Z, `s390x` pipeline but I imagine the Power pipeline is similar. You can  hear more about a dev's experiences from the Dumb-init team, https://github.com/Yelp/dumb-init/issues/188#issuecomment-517456003. 

If that does not fit your current build workflow/pipeline, we could set up some servers running on `s390x` and `ppc64le`, that you would have full access to, thus allow you to pull them into your build process. This method is a little more flexible but requires a little more setup. 

Speaking of your build process, are you able to share more about your process? What tools you are using, etc? I was interested in knowing so I could assist more in getting `ppc64le` and `s390x` support. 

Additionally, if you are unable to add `ppc64le` and `s390x` into the build process, could you share more about your process to I can build all the official support providers. Currently, when we are interested in utilizing one I need to pull down the repo and build it myself. GO is support fully on  `ppc64le` and `s390x`  and I have not it a build issues yet. I did not know if you had a build script that builds all the official providers that you could share/point me too.

**Comment by james-crowley** [comment]
@apparentlymart Did you get chance to see my previous post? 

Additionally, I been talking internal with some co-workers and more teams are embracing Terraform. Would you be open to setting up a meeting to discuss what I mentioned in my previous post? I think there is potential business value for both of us.

**Comment by mildwonkey** [comment]
Hi! I am going to close this issue - our list of supported platforms is managed internally in conjunction with other teams and so we will not accept external PRs. Please do open a Github issue if there isn't one already so we can discuss our supported platform list through our internal channels. Thanks, and sorry for the unsatisfying response!

**Pull request closed without merging**
