### PR TITLE
Change delete_on_termination's default

### PR DESCRIPTION
**Pull request by gfoligna**
For aws_instance it is FALSE, not true.

### CODE REVIEW

**Comment by stack72** [comment]
Hi @gfoligna 

Is this PR for default `delete_on_termination` for EBS volumes?

Paul

**Comment by gfoligna** [comment]
Hi @stack72.

I'm referring to the volumes at a `aws_instance definition`. 
We found this behaviour running v0.6.14.

**Comment by stack72** [comment]
@gfoligna 

ok that makes sense. Unfortunately, according to the code:

```
"ebs_block_device": &schema.Schema{
				Type:     schema.TypeSet,
				Optional: true,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"delete_on_termination": &schema.Schema{
							Type:     schema.TypeBool,
							Optional: true,
							Default:  true,
							ForceNew: true,
						},
```

```
"root_block_device": &schema.Schema{
				// TODO: This is a set because we don't support singleton
				//       sub-resources today. We'll enforce that the set only ever has
				//       length zero or one below. When TF gains support for
				//       sub-resources this can be converted.
				Type:     schema.TypeSet,
				Optional: true,
				Computed: true,
				Elem: &schema.Resource{
					// "You can only modify the volume size, volume type, and Delete on
					// Termination flag on the block device mapping entry for the root
					// device volume." - bit.ly/ec2bdmap
					Schema: map[string]*schema.Schema{
						"delete_on_termination": &schema.Schema{
							Type:     schema.TypeBool,
							Optional: true,
							Default:  true,
							ForceNew: true,
						},
```

So this is much more of a change that just the documentation I'm afraid

Paul

**Comment by gfoligna** [comment]
@stack72 I only observed the documentation difference bewteen the  `apply` run. Please don't take this as a request for code modification.

**Comment by stack72** [comment]
Hi @gfoligna 

I am not sure what we can do with this PR - currently, the documentation reflects the code. As the issue was reported with version 0.6.14, maybe there have been changes in the newer versions of Terraform

Thoughts?

Paul

**Comment by gfoligna** [comment]
I think this one should be closed now.

**Pull request closed without merging**
