### PR TITLE
update to match new default branch name

### PR DESCRIPTION
**Pull request by mildwonkey**
Mostly a docs/links update, but there are some build-related renames in here too. 

The good news is if I missed anything, GitHub will provide a redirect anyway 🎉

### CODE REVIEW

**Review by jbardin — APPROVED** [review]

**Review by apparentlymart — APPROVED** [review]
I had no idea we had so many references to the specific branch name! Thanks for updating all of these.

**Comment by mildwonkey** [comment]
sorry, clearly one of these changes is incorrect and causing build failures, i'll fix it!

**Comment by mildwonkey** [comment]
The broken links are false errors / a-ok:

```
=== Found broken links! ===
Fix before merging... or if they're not really broken, explain why.

website/docs/language/state/workspaces.html.md
  - Broken link: https://consul.io/
    [307 Temporary Redirect] https://consul.io/

website/upgrade-guides/0-10.html.markdown
  - Broken link: http://semver.org/
    [301 Moved Permanently] http://semver.org/

website/upgrade-guides/0-13.html.markdown
  - Broken link: https://discuss.hashicorp.com/c/terraform-core
    [301 Moved Permanently] https://discuss.hashicorp.com/c/terraform-core
```

**Comment by pselle** [comment]
Thank you for making these updates, Kristin!

**Pull request merged**
