### PR TITLE
Move DNSMadeEasy provider to community providers

### PR DESCRIPTION
**Pull request by tdmalone**
This is quite a bold pull request, made in response to some major issues with the DNS Made Easy provider which I think should render it as no longer supported by Hashicorp. The provider has a [major bug](https://github.com/terraform-providers/terraform-provider-dme/issues/1) where changes to existing resources are said to be applied, but are not, which means the only way to really use the provider is to taint every resource that you want to modify. In production, this is of course rarely a suitable thing to do to a DNS record.

Given that the provider doesn't support making changes to existing records, I think including it on a list of official Terraform providers is disingenuous. It leaves a potential user to start using it to discover that it isn't really usable.

The provider also doesn't appear to gracefully [handle DNS Made Easy's API rate limits](https://github.com/terraform-providers/terraform-provider-dme/issues/2), which makes it close to unusable when dealing with a large portfolio of resources.

Issues and pull requests to fix major issues have been open in the repository since at least June and October last year, respectively, without any attention from maintainers.

Examples:
* https://github.com/terraform-providers/terraform-provider-dme/issues/1 (reported again at [#11](https://github.com/terraform-providers/terraform-provider-dme/issues/11))
* https://github.com/terraform-providers/terraform-provider-dme/issues/2
* https://github.com/terraform-providers/terraform-provider-dme/pull/7

Given this, I think the provider should be considered in the docs as a community provider and not a core Terraform one, to avoid misleading potential users as to its suitability.

_Note: Although the only effective change in the commit is removing DME from the main index and network index, and adding it to the community index, the table columns have also been adjusted to ensure that three providers remain in each row._

### CODE REVIEW

**Comment by apparentlymart** [comment]
Hi @tdmalone! Thanks for starting this discussion.

This provider is indeed one of the ones that is currently in a state of having no maintainers. There is a small handful of these and we are currently keeping them in a "sustaining" state (making sure they remain compatible with Terraform and Terraform's installer, but otherwise not changing them) in the hope of finding someone who has the knowledge and motivation to take on maintainership.

Later in the year we plan to begin a process of "archiving" the providers that remain without maintainers. It's not clear yet exactly what form that will take, but we want to provide a reasonably-graceful EOL path for anyone already using them.

Until we reach that point, we'd rather leave things as they are right now because making the change you proposed here would effectively create a new state of provider that our internal tracking method can't model: a provider that is listed as community but yet distributed via `releases.hashicorp.com` and maintained within the `terraform-providers` organization. The process I described above will include changing some details of how we track these providers internally, but we're not yet ready to begin doing that because all of the teams involved are currently engaged elsewhere.

**Comment by tdmalone** [comment]
Thank you for the fast response @apparentlymart, and for the context around the situation.

I understand the caution to take a step like this before the right processes are ready internally.

I’m concerned, though, that others like me will find themselves in a similar position. I’m an almost daily user of Terraform - primarily the AWS provider, but some others as well - and I selected the DME provider to help with the transition of a large DNS management portfolio to Route 53. While I obviously didn’t expect it to be as full featured as the AWS provider (it has only one resource, after all), I have come to appreciate the high quality of Terraform (in fact, Hashicorp products in general) and expected that the resource that was available would have been tested and maintained, given it was on the Hashicorp-supported providers list. While I reviewed the documentation first, I didn’t review the open issues and pull requests - there’s always gonna be bugs, I just didn’t expect them to be as much of a show stopper as they were. If I _had_ realised earlier, I would have planned an entirely different approach (and I do realise I should review the issues first!)

While the context you’ve provided is helpful, it’s currently not very accessible. Rather than moving the provider, then, can I suggest instead adding some form of deprecation or unmaintained notice at the top of the documentation index page for the providers in this situation? It needn’t give a 100% guarantee of the way forward, but simply an alert and accessible acknowledgment that the provider is currently in an unmaintained state, and that extra care should be taken.

(I’d be happy to adjust the pull request accordingly if that would be acceptable - if you could also let me know the other providers that are currently in the unmaintained handful).

**Comment by apparentlymart** [comment]
I totally understand the frustration that some of the providers are more fully developed and maintained than others.

Our team that looks after the ecosystem of providers has been discussing this internally recently, and I believe there will be some action in this regard soon, in the general direction you're suggesting of marking the maintainership status of each provider. We generally prefer to make this sort of change in a "bulk" sort of way, across all of the providers, to avoid them drifting apart from one another too much, so I expect the team will make a plan for what to do and then do it systematically (probably with a script) across all of the affected repositories.

**Comment by tdmalone** [comment]
Hi @apparentlymart,

Just following up to see if there is any further movement on acknowledging the unmaintained providers in the documentation.

Thanks!

**Comment by tdmalone** [comment]
Hi @apparentlymart,

Just following up to see if there is any further movement on acknowledging the unmaintained providers in the documentation.

I note that https://github.com/terraform-providers/terraform-provider-dme/ was archived in late September 2018, and a [note on archived providers](https://www.terraform.io/docs/internals/archiving.html) was added to the website, but the DNS Made Easy provider is still listed as an official Terraform provider with no notice on its archival status on the website.

The archive note says:
> When this happens, HashiCorp may use GitHub's "archiving" feature on the provider's repository, to clearly signal the provider's status to users.

However, given one to specifically seek out the GitHub repository to find out it has been archived, I don't believe this clearly signals anything to users.

Are there any plans to acknowledge provider status in the documentation?

**Comment by pkolyvas** [comment]
Hi @tdmalone It looks like we've added a note on the DME provider page that it is deprecated and no longer interacts with a working service. Do you feel that's adequate to close this PR?

**Comment by tdmalone** [comment]
Absolutely. Thanks for the update!

**Pull request closed without merging**
