### PR TITLE
provider/aws: Import OpsWorks stacks

### PR DESCRIPTION
**Pull request by DJRH**
Add ability to import AWS OpsWorks stacks.

Acceptance test passes:

```
vagrant@terraform:/opt/gopath/src/github.com/hashicorp/terraform$ make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSOpsWorksStack_importBasic'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/09/29 11:55:52 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSOpsWorksStack_importBasic -timeout 120m
=== RUN   TestAccAWSOpsWorksStack_importBasic
--- PASS: TestAccAWSOpsWorksStack_importBasic (56.48s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	56.496s
```

### CODE REVIEW

**Comment by stack72** [comment]
Hi @DJRH 

Thanks for the work here - am interested in why we changed the AZs to us-east-1? That meant changing the individual tests as well

Paul

**Comment by DJRH** [comment]
Hi @stack72 

Thanks for checking this out. I've now reverted the AZ changes and set the default region within the import acceptance test to match us-west-2, and the acceptance test still passes.

Cheers,
Dan

**Comment by stack72** [comment]
Thanks @DJRH :) Will get this tested today!

P.

**Comment by stack72** [comment]
Hi @DJRH 

Thanks for the work here - I have manually merged this as I made a slight change in fa3051a42b3c8a4b5b4b804555b16ae4d0f191dd

:)

P.

**Pull request merged**
