### PR TITLE
Add a new `terraform fmt` command for linting

### PR DESCRIPTION
**Pull request by dcarley**
Add a new `terraform fmt` command for rewriting Terraform config files to a canonical format and style. This builds upon the `hcl/fmtcmd` package that was added in hashicorp/hcl#80 and wouldn't have been possible without @fatih's excellent work. There's more detail in the individual commits.

### CODE REVIEW

**Comment by dcarley** [comment]
Looks like the dependencies need to be updated to pull in a later version of `hashicorp/hcl`.

How does this work, post #4909?

**Comment by dcarley** [comment]
Fixed the dependency problems :yum:

**Comment by josephholsten** [comment]
@dcarley looks great, and I was just looking at adding a `-l` to `hclfmt` this week.

I have a feeling this will bring https://github.com/fatih/hclfmt/issues/3 to people's attention, since it's actually coming from `hashicorp/hcl`.

@phinze care to lay your :eyes: on this one? Has tests, needs doc.

**Comment by dcarley** [comment]
I've rebased the existing commits to add website documentation. Sorry, forgot about that originally.

**Comment by dcarley** [comment]
Rebased against master. I've omitted the update to the HCL dependency because #5400 pulled in a sufficient version.

@radeksimko @phinze: Can you review?

**Comment by dcarley** [comment]
Oops, fixed build failure.

**Comment by ronnylt** [comment]
It would be great to have this in terraform, looking forward to adding it to our CI process.

**Comment by josephholsten** [comment]
@radeksimko @phinze: what do we need to get this in for 0.6.15? I'd actually love to have this command for every hashi-app using hcl, but this is where I'm needing it most right now.

**Comment by apparentlymart** [comment]
Thanks for this, @dcarley!

I tried it out on some config files I have here and it worked out great. I've merged this set of changes for inclusion in 0.6.15.

**Comment by dcarley** [comment]
Thanks! :whale:

**Pull request merged**
