### PR TITLE
provider/vault: Remove user input for optional vault provider fields

### PR DESCRIPTION
**Pull request by Mongey**
Hello again @apparentlymart 👋 

When `ca_cert_dir` and `ca_cert_file` are not set in the `vault` provider, Terraform will prompt the user for input. 

Looking at [`helper/schema/schema.go`](https://github.com/hashicorp/terraform/blob/master/helper/schema/schema.go#L501) it seems that a nil `DefaultValue` for a `TypeString` will ask the user for input. Defaulting to `""` will allow us to continue without user input.

It also seems like Terraform isn't handling `TypeList`, causing the crash described in #10505.

### CODE REVIEW

**Comment by Mongey** [comment]
Adding a `WIP` tag, `ConflictsWith` always gets triggered with either `ca_cert_file` or `ca_cert_dir` set

**Comment by Mongey** [comment]
It seems that the Vault Client allows `ca_cert_file` and `ca_cert_dir` to be set, so I've removed the `ConflictsWith` on these fields.

**Comment by gerr1t** [comment]
+1 , thanks @Mongey

**Comment by stack72** [comment]
LGTM! thanks for the work here :)

**Pull request merged**
