### PR TITLE
GCS remote state

### PR DESCRIPTION
**Pull request by sl1pm4t**
This is PR #3719 rebased on top of master (0.7 code).
CC @stack72

### CODE REVIEW

**Comment by stack72** [comment]
YAY! <3 thanks!

**Comment by jen20** [comment]
Hi @sl1pm4t! I've just been testing this, but it appears it does't respect the environment variables for the location of credentials. Normally in Terraform we use a combination of `GOOGLE_REGION`, `GOOGLE_PROJECT` and `GOOGLE_CREDENTIALS`, but we are not honouring these in this case. I think we do need to account for the fact that the GCP account may be different from one under management, so consequently we should make explicitly passed `-backend-var` type parameters override the environment variables. Does this seem reasonable?

**Comment by sl1pm4t** [comment]
Hi @jen20 - yep more than reasonable. I'll take another pass.

**Comment by sl1pm4t** [comment]
@jen20 I added support for the `GOOGLE_CREDENTIALS` env var.

**Comment by jen20** [comment]
Thanks @sl1pm4t! I'll give this another shot now

**Comment by jen20** [comment]
```
=== RUN   TestGCSClient_impl
--- PASS: TestGCSClient_impl (0.00s)
=== RUN   TestGCSClient
2016/05/31 13:41:26 [INFO] Requesting Google token...
2016/05/31 13:41:26 [INFO]   -- Email: travis-acctests@hashicorp-terraform-testing.iam.gserviceaccount.com
2016/05/31 13:41:26 [INFO]   -- Scopes: [https://www.googleapis.com/auth/devstorage.full_control]
2016/05/31 13:41:26 [INFO]   -- Private Key Length: 1704
2016/05/31 13:41:26 [INFO] Instantiating Google Storage Client...
Created bucket terraform-remote-gcs-test-574ddad6 at location https://www.googleapis.com/storage/v1/b/terraform-remote-gcs-test-574ddad6

2016/05/31 13:41:29 [INFO] Writing terraform-remote-gcs-test-574ddad6/testState
2016/05/31 13:41:29 [INFO] Writing terraform-remote-gcs-test-574ddad6/testState
2016/05/31 13:41:30 [INFO] Reading terraform-remote-gcs-test-574ddad6/testState
2016/05/31 13:41:30 [INFO] Downloaded 393 bytes
2016/05/31 13:41:30 [INFO] Deleting terraform-remote-gcs-test-574ddad6/testState
2016/05/31 13:41:30 [INFO] Reading terraform-remote-gcs-test-574ddad6/testState
2016/05/31 13:41:30 [INFO] terraform-remote-gcs-test-574ddad6/testState not found
--- PASS: TestGCSClient (5.95s)
```

I've rebased this and will merge locally. Thanks @sl1pm4t!

**Comment by sl1pm4t** [comment]
No problem. Thanks @jen20

**Comment by jen20** [comment]
Merged as 48e85d6 - thanks @sl1pm4t!

**Pull request closed without merging**
