### PR TITLE
provider alicloud:add new rds resource and some bugs fix

### PR DESCRIPTION
**Pull request by demonwy**
IMPROVEMENTS:

alicloud/config: add businessinfo to sdk client [#96](https://github.com/alibaba/terraform-provider/pull/96)

BUG FIXES:

resource/alicloud_db_instance: fix rds update failed bug [#102](https://github.com/alibaba/terraform-provider/pull/102)
resource/alicloud_instance: fix ecs instance system disk size not work bug [#100](https://github.com/alibaba/terraform-provider/pull/100)

### CODE REVIEW

**Comment by demonwy** [comment]
@stack72 
I've submit the new PR, but the CI always failed.
I've run the command `make vet vendor-status test` on my MacBook and is passed.

I've search the error `The following packages are missing or modified locally` around the world, it seems related to **govendor bug** ? I'am not sure.

What can i do for this?

Refer to [#225](https://github.com/kardianos/govendor/issues/255) and [#233](https://github.com/kardianos/govendor/issues/233#issuecomment-269963836)


Thanks,
Yue Wang

**Comment by stack72** [comment]
Hi @demonwy 

So (thanks to @jbardin) we worked out what the issue is - govendor has picked up a file called `slb.test` which sits in the path:

```
github.com/denverdino/aliyungo/slb
```

but in the Terraform .gitignore file, we exclude all *.test files. Therefore, the file that govendor expects is not there. Is this a required file or is this a file left over from a manual test run?

If this is not required, please can you remove it and re-run govendor on this PR and we can solve it for you?

The same issue happened on your other PR as well - I have reopened that PR under a different number - if you solve the govendor issue above, please can you send a PR against this https://github.com/hashicorp/terraform/pull/12879 with the new govendor?

Thanks 

Paul

**Comment by demonwy** [comment]
Thanks @stack72  and @jbardin 
I've check the dependency, that there is a file named slb.test located in the path `github.com/denverdino/aliyungo/slb`.

But the repo `aliyungo` is maintained by other team, it may be not so easy to delete a .test file.

BTW,Will you add the check logic in the script, avoid including .test file.


Regards,
Yue Wang

**Comment by stack72** [comment]
Closed via #12913

**Pull request closed without merging**
