### PR TITLE
Connect network after docker container has been started.

### LINKED ISSUE #5033: Docker provider tries to connect networks before it is running.
Getting this error:

> 1 error(s) occurred:
> - docker_container.nzbget: Unable to connect to network 'ba576708b1403c86625e83cfce77face1bbbefa061f0d3bb09a6869defa1d238': API error (500): Container e056e2e37486821352b1d010c92c85760dc42deb0a528c38c08df1d3121d585a is not running

Presumably because the `StartContainer()` call is after the block that connects the networks: https://github.com/hashicorp/terraform/blob/e490b44daa9297ac78828a44f0b1148af72ce4d0/builtin/providers/docker/resource_docker_container_funcs.go#L174

### PR DESCRIPTION
**Pull request by rayward**
Fixes #5033

As mentioned in that issue, this is no longer an issue in the recently released Docker 1.10, but the fix might be useful still for those on older versions (as there is no enforcement of versions in Terraform).

Test before and after on Docker 1.9.1:
```
root@terraform:/opt/gopath/src/github.com/hashicorp/terraform# make testacc TEST=./builtin/providers/docker TESTARGS="-run network"
TF_ACC=1 GO15VENDOREXPERIMENT=1 go test ./builtin/providers/docker -v -run network -timeout 120m
=== RUN   TestAccDockerContainer_network
--- FAIL: TestAccDockerContainer_network (0.30s)
	testing.go:148: Step 0 error: Error applying: 1 error(s) occurred:

		* docker_container.foo: Unable to connect to network 'b4205fd0054921585655a8924d43eaefd751bdf952495ff747f3266981fc9f2a': API error (500): Container 3184345d4aede934df0de5e07767e635ee0d212d12e4d435dc0c0931fd10833e is not running

FAIL
exit status 1
FAIL	github.com/hashicorp/terraform/builtin/providers/docker	0.312s
make: *** [testacc] Error 1
root@terraform:/opt/gopath/src/github.com/hashicorp/terraform# make testacc TEST=./builtin/providers/docker TESTARGS="-run network"
TF_ACC=1 GO15VENDOREXPERIMENT=1 go test ./builtin/providers/docker -v -run network -timeout 120m
=== RUN   TestAccDockerContainer_network
--- PASS: TestAccDockerContainer_network (0.92s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/docker	0.932s
```

### CODE REVIEW

**Comment by ColinHebert** [comment]
I'm surprised, I've been using this feature with docker 1.9.1 and it hasn't failed so far.

The network connection is expected to be before the start as the service might require that network to even start properly.

Could you show the terraform configuration that failed in the first place?

**Comment by rayward** [comment]
@ColinHebert Here's my entire configuration - https://github.com/rayward/terraform-plex

It could probably be distilled down to something much simpler though.

**Comment by rayward** [comment]
> The network connection is expected to be before the start as the service might require that network to even start properly.

That is a good point and would be preferable behaviour, perhaps we can ignore this change then, but enforce docker >= 1.10.

**Comment by rayward** [comment]
> it's not unlikely that the service will expect the network to be available when starting

Yeh, but I'm wondering how `docker run --net=my-user-defined-network` works (or worked in 1.9.1) in that case.

The docker codebase is a bit confusing to navigate, but I *think* that the `NetworkMode` option on container create can be used to specify the network as user defined which may allow docker to connect the network at `create` time rather than `start` time. 

Whereas explicitly executing `docker network connect` required the container to be running.

A bit speculative though...

Perhaps you would just like to keep the acceptance test for a bit more coverage?

**Comment by stack72** [comment]
Hi @rayward

I want to thank you for the work you have put in here. On looking through the PR, I see it targets early versions of docker - I am going to close this out. I think on retrospect, there are so many changes to docker recently that a fair few of the later resource changes will not be backwards compatible either

I do hope you understand. Thanks again for the work

Paul

**Comment by rayward** [comment]
@stack72 not a problem! I'd actually forgotten about this issue now and I'm sure most people are running a modern docker version now.

Cheers

**Pull request closed without merging**
