### PR TITLE
Revert "providers/template: template_file supports floating point math"

### PR DESCRIPTION
**Pull request by phinze**
Reverts hashicorp/terraform#8590

See comments on that thread.

### CODE REVIEW

**Comment by phinze** [comment]
cc @sethvargo @mitchellh

**Comment by sethvargo** [comment]
👍  - do we need to reopen the original issue #7887?

**Comment by mitchellh** [comment]
Great catch before a release!

**Comment by mitchellh** [comment]
LGTM, I think we do, I think helper/schema needs a new type to support typed maps.

**Comment by sethvargo** [comment]
I don't always run master, but when I do it's to catch pre-release bugs 😄

**Pull request merged**
