### PR TITLE
provider/aws Add S3 bucket object tag support

### PR DESCRIPTION
**Pull request by ewbankkit**
Add support for AWS S3 [object tagging](http://docs.aws.amazon.com/AmazonS3/latest/dev/object-tagging.html).

### CODE REVIEW

**Comment by ewbankkit** [comment]
Rebased and fixed some acceptance tests.

**Comment by stack72** [comment]
Hi @ewbankkit 

How is this progressing? Ready for a review?

Thanks

Paul

**Comment by ewbankkit** [comment]
Right now the acceptance tests are passing and the functionality works but _Update_ is always recreating - via [PUT](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUT.html) - the whole bucket object even if just the tags change. This is also true for the bucket object ACL also.
I'd like to correct that.

**Comment by ewbankkit** [comment]
I'd certainly welcome any preliminary comments.

**Comment by ewbankkit** [comment]
Because of the way the `source` attribute on the resource works - the value of `source` may not change but the contents of the file referred to may - we will have to always rewrite the bucket object whenever and change is detected.

**Comment by ewbankkit** [comment]
Rebased.
Removing _WIP_.
Ready for review.

**Comment by stack72** [comment]
LGTM Thanks for this work :)

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=S3BucketObject'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/02/13 16:45:28 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=S3BucketObject -timeout 120m
=== RUN   TestAccDataSourceAWSS3BucketObject_basic
--- PASS: TestAccDataSourceAWSS3BucketObject_basic (98.21s)
=== RUN   TestAccDataSourceAWSS3BucketObject_readableBody
--- PASS: TestAccDataSourceAWSS3BucketObject_readableBody (95.32s)
=== RUN   TestAccDataSourceAWSS3BucketObject_kmsEncrypted
--- PASS: TestAccDataSourceAWSS3BucketObject_kmsEncrypted (126.91s)
=== RUN   TestAccDataSourceAWSS3BucketObject_allParams
--- PASS: TestAccDataSourceAWSS3BucketObject_allParams (102.44s)
=== RUN   TestAccAWSS3BucketObject_source
--- PASS: TestAccAWSS3BucketObject_source (61.92s)
=== RUN   TestAccAWSS3BucketObject_content
--- PASS: TestAccAWSS3BucketObject_content (61.63s)
=== RUN   TestAccAWSS3BucketObject_withContentCharacteristics
--- PASS: TestAccAWSS3BucketObject_withContentCharacteristics (59.16s)
=== RUN   TestAccAWSS3BucketObject_updates
--- PASS: TestAccAWSS3BucketObject_updates (104.26s)
=== RUN   TestAccAWSS3BucketObject_updatesWithVersioning
--- PASS: TestAccAWSS3BucketObject_updatesWithVersioning (105.96s)
=== RUN   TestAccAWSS3BucketObject_kms
--- PASS: TestAccAWSS3BucketObject_kms (91.82s)
=== RUN   TestAccAWSS3BucketObject_sse
--- PASS: TestAccAWSS3BucketObject_sse (67.96s)
=== RUN   TestAccAWSS3BucketObject_acl
--- PASS: TestAccAWSS3BucketObject_acl (108.00s)
=== RUN   TestResourceAWSS3BucketObjectAcl_validation
--- PASS: TestResourceAWSS3BucketObjectAcl_validation (0.00s)
=== RUN   TestAccAWSS3BucketObject_storageClass
--- PASS: TestAccAWSS3BucketObject_storageClass (108.61s)
=== RUN   TestResourceAWSS3BucketObjectStorageClass_validation
--- PASS: TestResourceAWSS3BucketObjectStorageClass_validation (0.00s)
=== RUN   TestAccAWSS3BucketObject_tags
--- PASS: TestAccAWSS3BucketObject_tags (62.80s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	1255.034s
```

**Pull request merged**
