### PR TITLE
provider/google: add support for GKE node pool autoscaling

### LINKED ISSUE #8605: [GKE] Support autoscaling
hey all,

Google cloud supports autoscaling for nodes which is very useful in high traffic kubernetes deployments. Could you add this feature to terraform? Currently i use local exec like this:

``` bash
  # enable autoscaling
  provisioner "local-exec" {
      command = "gcloud container clusters update ${var.google_container_cluster.name} --enable-autoscaling --min-nodes=${var.min_nodes} --max-nodes=${var.max_nodes} --project='${var.project_name}'"
  }
```

Documentation is here
https://cloud.google.com/container-engine/docs/clusters/operations

### PR DESCRIPTION
**Pull request by danawillow**
Fixes #8605.

Note that I decided not to include the "enabled" boolean in the terraform state, and instead just assert that if the autoscaling field exists in a terraform config then autoscaling is enabled. Let me know if you notice any gotchas with that approach, or if you think it makes more sense just to go with what the API has.

### CODE REVIEW

**Comment by danawillow** [comment]
Ah, looks like you can update autoscaling but I didn't notice because it's part of the clusters API call instead of the nodepools one. I just sent an email to the GKE team to check that I'm understanding things correctly overall; I'll update again once I've gotten a clear answer.

**Comment by Liberski** [comment]
@danawillow @paddycarver Any update on this?

**Comment by danawillow** [comment]
No updates right now, but it's still on our radar. A few higher-priority things came up but I'll try to finish this up soonish.

**Comment by munnerz** [comment]
This is pretty important for a project I'm working on at the moment.

Would it be possible to get it merged in as-is at the moment? (with ForceNew still enabled). I may be able to spend some time working on this if there's anything extra needed doing.

**Comment by danawillow** [comment]
Hey @munnerz, we're actually in a code freeze at the moment so this won't be able to get merged until next week at the earliest (I'm not sure how long the freeze will last for).

**Comment by munnerz** [comment]
Hey again - I'm not sure where to check on the status of code freeze so sorry to keep bothering you. Again, is there anything I can do to move this along? 😄

**Comment by danawillow** [comment]
Ah whoops! So the code freeze was a part of the provider split that happened (we're now in https://github.com/terraform-providers/terraform-provider-google). Let me port this over there and finish it up right now.

**Comment by danawillow** [comment]
New PR at https://github.com/terraform-providers/terraform-provider-google/pull/157

**Pull request closed without merging**
