### PR TITLE
[WIP] provider/aws: Elasticache Replication Group

### PR DESCRIPTION
**Pull request by stack72**
Initial scaffolding for Elasticache Replication Groups

* [x] Schema
* [ ] CRUD functionality
- [ ] Acceptance Tests
- [ ] Documentation

As per requested #4361

### CODE REVIEW

**Comment by catsby** [comment]
There was an existing PR for this, if I recall correctly... It may have been closed though, did you see it by chance?

**Comment by stack72** [comment]
@catsby they are closed by the looks of it (from doing a quick search)

**Comment by catsby** [comment]
Cool, will review as soon as I can

**Comment by cordoval** [comment]
bump @catsby did you review it? we need this @stack72

**Comment by catsby** [comment]
Unfortunately we'll need the acceptance tests and documentation before we can merge this.

**Comment by stack72** [comment]
@catsby @cordoval I will get this finished this weekend - I have been struggling on how to achieve the Read func as the API returns basically none of the information needed to set the terraform state

**Comment by stack72** [comment]
This PR is on hold - basically the SDK method that reads back the Replication Group has some weird structure in how it holds the data. I need to try and work out how to set the data back to the terraform state

**Comment by nicolai86** [comment]
@stack72 what's the status of this & will you have time to work on it? Otherwise I'd love to help out.

**Comment by hatt** [comment]
@stack72 I'm keen to help out on this too - what part of the returned data are you have trouble with? From briefly looking over your branch, it looks like getting the number of nodes in the replicated cache clusters is broken?

The API is kinda ugly in how it exposes that data but from how I've done it in Ruby before, the easiest way is to count `len(rg.NodeGroups[0].NodeGroupMembers)`. This is a list of all nodes in each cluster of the replication group but as there is only ever one NodeGroup in a Redis cluster, the total number of nodes in the replication group will then be `c.NumCacheNodes` multiplied by the number of group members (groups include the original primary cluster).

I hope this helps, maybe I misunderstood where you were stuck or how the API works but I think this is correct.

**Comment by samber** [comment]
Hey !
@stack72 : What's the status on this PR ? How can I help ?
@hatt : I will explore this way ;-)

**Comment by dankrieger** [comment]
Hoping to push this forward a bit, I've taken what @stack72 began and (tried) to fill in functionality for the read function and adding further: 
https://github.com/dankrieger/terraform/tree/aws-elasticache-replication_groups.  

I'm was able to create a replication group, add clusters, remove clusters, change node types, and switch to/from automatic failover.  It probably isn't feature complete, but it feels like it meets the requirements for the initial functionality people are probably hoping for.

Big caveat: I'm not a Go developer and this was my first experience with the language so I shamelessly cloned and tweaked functionality from resource_aws_elasticache_cluster.go where necessary.  If anybody is interested in trying out and/or completing what I've started I'd love to see this functionality added officially to terraform however I'm likely not the guy qualified to make it so

**Comment by ricoli** [comment]
any progress on this?

**Comment by stack72** [comment]
Closing this - not had time to fix it up. Please feel free to help out @dankrieger with his effort pushing this forward

@dankrieger please can you convert your's into a PR and then we can get some feedback on it?

**Pull request closed without merging**
