### PR TITLE
Add lower / upper interpolation functions

### PR DESCRIPTION
**Pull request by sl1pm4t**

### CODE REVIEW

**Comment by sl1pm4t** [comment]
For #3542

**Comment by sl1pm4t** [comment]
the build failure is coming from packngo which seems to be in the packet provider and not related to this change. If I'm wrong please let me know and I'll clean it up.

**Comment by apparentlymart** [comment]
Great, thanks!

So far the interpolation functions have been maintained in the docs in alphabetical order. Could you make your new additions consistent with this? I suspect as this list of functions grows we'll want to split it out into a few different categories of functions, but for now while they are all in one big list I think it's better to have them in a predictable order so it's easier for people to look them up.

**Comment by sl1pm4t** [comment]
@apparentlymart - I committed a fix for docs func ordering. Is that what you needed?

**Comment by apparentlymart** [comment]
Thanks a lot for working on this! I squashed it into a single commit and merged it as e2232b1b7b46e9aad45999ef0d088bf07360eb6d.

**Comment by makered** [comment]
Thanks for a quick fix, much appreciated!

**Pull request closed without merging**
