### PR TITLE
Allow vpc_peering_connection

### PR DESCRIPTION
**Pull request by julienba**
It's my first time writing go, so be careful.

At the moment, you need to create the peering connection with ami-cli or aws-console.
For a better integration it is required to improve https://github.com/mitchellh/goamz for creating the peering connection and link it into terraform

### CODE REVIEW

**Comment by julienba** [comment]
Link to https://github.com/mitchellh/goamz/pull/220

**Comment by mitchellh** [comment]
This looks good! I noticed it doesn't support update. Is this true of the AWS resource? If so, you should set the `RequiresNew: true` parameter on all elements of the schema (except tags). You'll need an update to update the tags as well. Look at other resources for guidance!

**Comment by julienba** [comment]
You're right that I missed the update part and yes it's possible to update the tags.
I just add it

**Comment by mitchellh** [comment]
This looks really good!

**Comment by piavlo** [comment]
Btw why  not to automatically accept the peering connection in case the peer and peering vpcs are managed by same aws account?

**Comment by julienba** [comment]
That should be possible. I will try to look at it it next week

**Comment by julienba** [comment]
@piavlo I've made a new PR with https://github.com/hashicorp/terraform/pull/1161

**Pull request merged**
