### PR TITLE
Fix bad message from TimeoutError

### PR DESCRIPTION
**Pull request by dtolnay**
Before:

> Error creating IAM Role my-role: timeout while waiting for state to become 'success'. last error: %!s(\<nil\>)

### CODE REVIEW

**Comment by catsby** [comment]
Thanks @dtolnay – do you have any clues as to why that last error is `nil`?

**Comment by dtolnay** [comment]
Yes, it should be fixed in #7733. It means the first try never finished.

**Comment by dtolnay** [comment]
@catsby is there anything I can do to move this along?

**Comment by jen20** [comment]
Hi @dtolnay, I rebased and merged this - thanks for your contribution to Terraform!

**Pull request closed without merging**
