### PR TITLE
hash rds and aurora password

### PR DESCRIPTION
**Pull request by arcadiatea**
1. Store RDS and Aurora master user password as hashed value in states file.
2. Change RDS operation timeout from 40 minutes to 120 minutes.
For SQL server EE version, the RDS creation takes about 60 minutes for 200GB (minimum size for SQL Server EE). Create Oracle RDS from a snpashot also may take longer than 40 minutes to completed

### CODE REVIEW

**Comment by arcadiatea** [comment]
Can have this pull request merge in? It is critical for ticketmaster.  Please let me know if you have any concern on the approach. And I will submit another PR for hash password on DMS endpoint .

**Comment by Xirel** [comment]
bump...

**Comment by iceycake** [comment]
Any update on this pull request?  I

**Comment by arcadiatea** [comment]
the hard code of timeout is taken out. This PR only have hash password function.

**Comment by iceycake** [comment]
Removed the 120 mins hard coded timeout respect the latest changes on timeout configuration.

**Comment by joshuaspence** [comment]
This is awesome. Exactly what I was looking for.

**Comment by Ninir** [comment]
@catsby this one has been migrated to the AWS repository. Can you close it please?

**Comment by grubernaut** [comment]
Closing in favor of: https://github.com/terraform-providers/terraform-provider-aws/pull/1084, thanks!

**Pull request closed without merging**
