### PR TITLE
remove security groups (by name) before adding security groups (by id)

### PR DESCRIPTION
**Pull request by dupuy**

### CODE REVIEW

**Comment by dupuy** [comment]
This is a partial fix (of the worst problems) that I reported in #2009.  A good fix ought to do the security groups comparison by name or id, but that's a bit beyond my Terraform / Go hacking skills at the moment.

**Comment by jtopjian** [comment]
I agree with everything you've done here and explained in #2009. This patch looks good to me and makes sense. I'll leave more comments in #2009.

**Comment by josephholsten** [comment]
@phinze do you anything to merge this?

**Comment by phinze** [comment]
Sounds good to me - merging!

**Pull request merged**
