### PR TITLE
set cross_zone_load_balancing default to true

### PR DESCRIPTION
**Pull request by optimisticanshul**
#6891 

/cc @apparentlymart

### CODE REVIEW

**Comment by stack72** [comment]
Hi @optimisticanshul 

Thanks for the PR here - in order to make sure that we let the users know of the new behaviour, please can you update the documentation and make sure the tests work as expected / make the appropriate changes before we merge this?

thanks

Paul

**Comment by optimisticanshul** [comment]
Sure i will add them today.

**Comment by optimisticanshul** [comment]
@stack72 all tests are passing and i don't see anywhere, this option is explicitly documented. So i think we are good, but let me know if i missed anything.

**Comment by stack72** [comment]
Hi @optimisticanshul 

Just ran the tests for this and it indeed does look good :)

```
make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSELB'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /vendor/)
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSELB -timeout 120m
=== RUN   TestAccAWSELB_importBasic
--- PASS: TestAccAWSELB_importBasic (38.23s)
=== RUN   TestAccAWSELB_basic
--- PASS: TestAccAWSELB_basic (33.97s)
=== RUN   TestAccAWSELB_fullCharacterRange
--- PASS: TestAccAWSELB_fullCharacterRange (32.37s)
=== RUN   TestAccAWSELB_AccessLogs
--- PASS: TestAccAWSELB_AccessLogs (98.13s)
=== RUN   TestAccAWSELB_generatedName
--- PASS: TestAccAWSELB_generatedName (32.22s)
=== RUN   TestAccAWSELB_availabilityZones
--- PASS: TestAccAWSELB_availabilityZones (54.11s)
=== RUN   TestAccAWSELB_tags
--- PASS: TestAccAWSELB_tags (58.55s)
=== RUN   TestAccAWSELB_iam_server_cert
--- PASS: TestAccAWSELB_iam_server_cert (41.07s)
=== RUN   TestAccAWSELB_InstanceAttaching
--- PASS: TestAccAWSELB_InstanceAttaching (158.45s)
=== RUN   TestAccAWSELBUpdate_Listener
--- PASS: TestAccAWSELBUpdate_Listener (56.19s)
=== RUN   TestAccAWSELB_HealthCheck
--- PASS: TestAccAWSELB_HealthCheck (32.53s)
=== RUN   TestAccAWSELBUpdate_HealthCheck
--- PASS: TestAccAWSELBUpdate_HealthCheck (54.22s)
=== RUN   TestAccAWSELB_Timeout
--- PASS: TestAccAWSELB_Timeout (32.67s)
=== RUN   TestAccAWSELBUpdate_Timeout
--- PASS: TestAccAWSELBUpdate_Timeout (60.83s)
=== RUN   TestAccAWSELB_ConnectionDraining
--- PASS: TestAccAWSELB_ConnectionDraining (34.34s)
=== RUN   TestAccAWSELBUpdate_ConnectionDraining
--- PASS: TestAccAWSELBUpdate_ConnectionDraining (70.20s)
=== RUN   TestAccAWSELB_SecurityGroups
--- PASS: TestAccAWSELB_SecurityGroups (69.06s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	957.155s
```

Thanks for the work here 

Paul

**Pull request merged**
