### PR TITLE
Implement aws_ebs_volume

### PR DESCRIPTION
**Pull request by bitglue**
This resource allows the management of EBS volumes not associated with
any EC2 instance.

### CODE REVIEW

**Comment by mitchellh** [comment]
Looks great. Missing docs and some more assertions in the tests, but I'll add those right after this. Thanks!

**Comment by alekseymykhailov** [comment]
is it possible to associate EBS volume created by this resource with instance ?
or we should use some "local-exec" + aws-cli hacks ?

**Comment by bitglue** [comment]
@alekseymykhailov no, but if you just want an EBS volume attached to an instance, the [aws_instance](https://terraform.io/docs/providers/aws/r/instance.html) resource has parameters to do that. For my needs, I'm using systemd mount units scheduled by fleet in a CoreOS cluster to dynamically mount the volume.

**Comment by alekseymykhailov** [comment]
>the aws_instance resource has parameters to do that
yes, but there is one issue - when terraform recreates instance it also create new EBS volume (even if I keep old one)

**Comment by bitglue** [comment]
I agree, that would be useful.

**Comment by prepor** [comment]
+1

**Pull request merged**
