### PR TITLE
Make persist interval configurable via environment variable

### LINKED ISSUE #35115: Make persistence interval configurable for the remote state backend
### Terraform Version

```shell
1.8.1
```

### Use Cases

When state size increases, the persistence of the state becomes a bottleneck as it happens synchronously. Currently, the persist interval is [hardcoded in local apply backend](https://github.com/hashicorp/terraform/blob/main/internal/backend/local/backend_apply.go#L85) to 20 seconds, and as state size increases, it becomes a significant amount of time spent on the persisting. 

For remote apply backend it's possible to disable intermediate persistence completely, but it's not possible to do for the local apply backend.

### Attempted Solutions

I have code changes that allow to specify a new persist interval via an environment variable.

### Proposal

Make the persist interval configurable (or allow you to disable it completely) instead of using a hardcoded value. Open question: How to specify it: Is it enough to provide support via an environment variable, or will we need to add support for the command-line option?

Also, maybe it makes sense to make actual cloud write async? 

### References

_No response_

### PR DESCRIPTION
**Pull request by alexott**
By default, the remote state backend persists state to the remote storage every 20 seconds—this value is hardcoded. But when the state is big (> 100Mb), this operation takes a long time and consumes a significant portion of these 20 seconds. This PR allows to make the persist interval configurable via the `TF_BACKEND_PERSIST_INTERVAL_SECONDS` environment variable, which allows to specify how often persistence should happen.

Please guide what part of the documentation needs to be updated to document it...

P.S. I thought about adding the ability to completely disable this persist interval like it's done when the remote execution backend is used - but this could be a topic for discussion.

Fixes #35115

## Target Release

1.8.x

### NEW FEATURES | UPGRADE NOTES | ENHANCEMENTS | BUG FIXES | EXPERIMENTS

 

-  Added `TF_BACKEND_PERSIST_INTERVAL_SECONDS` environment variable to control persist interval in the remote state backend.

### CODE REVIEW

**Comment by brandonc** [comment]
@alexott Hey, Alex, thanks for this improvement. We'd like to enable this capability, but we need to account for allowing HCP Terraform to set a minimum interval in order to protect itself from state snapshot load. What I've found with your version is that I can override any interval the server sets due to the way that backends are structured and used.

What I'm thinking is that this env variable that you've recommended can define the maximum interval to allow you to store state less frequently than what is set by HCP Terraform, which will now define the minimum interval. I'll incorporate your code in an upcoming PR of my own.

**Comment by alexott** [comment]
@brandonc hmmm, as I saw in the code, this change doesn't affect the behavior of HCP Terraform, etc. It just allows to specify persist interval via environment variable instead of using the hardcoded one... No other places are affected. Of course, if the new behavior exists, then it's just a way a previous version was implemented...

But anyway, I'm happy if you implement something else that will allow to reach the desired behavior - do you have any ETA on that?

**Comment by brandonc** [comment]
@alexott It's a little roundabout, but the gist is that HCP Terraform ends up running terraform using a local backend, and users may set environment variables in that context. ETA probably next week or two, as it's prioritized in with some other stuff.

**Comment by alexott** [comment]
@brandonc do you need any help from me to speedup this implementation?

**Comment by brandonc** [comment]
@alexott not at this time. The work is prioritized and narrowly scoped so it shouldn't be too much of a wait

**Comment by sebasslash** [comment]
Hey Alex! Thanks again for your contribution here. Going to close this PR in favor of #35176 which includes some minor refactoring. All credit goes to you! 👍

**Comment by brandonc** [comment]
@alexott We discovered that the [maximum interval was already implemented](https://github.com/hashicorp/terraform/blob/9448845e911fc51390dbd3d3d8f540b2abe13beb/internal/cloud/state.go#L261-L269) but opened a new PR to move ENV evaluation. Thanks again

**Pull request closed without merging**
