### PR TITLE
helper/schema: Expose ResourceDiff IsSet method

### PR DESCRIPTION
**Pull request by julienduchesne**
* Adds an IsSet method that tells if the attribute has a value or not in the config. (It can be computed or not).
* The reason for this feature is that for this PR: https://github.com/terraform-providers/terraform-provider-aws/pull/5002, I need to tell in the CustomizeDiff function if an attribute has been set. Right now, there is no way to know from inside that function if an attribute is set when that attribute's value comes from interpolation (All ResourceDiff methods filter out computed values).

Let me know what you think!
Thanks

### CODE REVIEW

**Comment by apparentlymart** [comment]
Hi @julienduchesne! Thanks for working on this.

The provider SDK doesn't currently expose the distinction between zero-value and unset more directly because in the current model there are situations where this answer is not decidable because of how the data is represented internally. This arises in particular when a value _was_ set and has now become _unset_: the diff will show this as a change from the prior value to the default value, because the current diff model has no other way to represent "deleted".

As part of our current work to improve the configuration language we've added a first-class representation of a value being unset (called `null` in the language), which will then allow us to fully distinguish these two cases. This will initially only happen at the Terraform Core level, since we do not wish to change the provider-facing behavior for this initial release, but once we have the groundwork in place we are likely to update the provider SDK to make better use of this new capability, which could include a version of the function you added here that would not suffer from the same ambiguity it would have if we were to add this today.

For the moment, the `GetOkExists` function is intended to already expose this (not-quite-accurate) idea of exists, for situations where the above ambiguity is acceptable. You may be able to get what you need with that for now, as long as you don't need to deal with the situation where an attribute moves from being set to being unset.

**Comment by julienduchesne** [comment]
The issue is that `GetOkExists` also tells that computed resources don't exist with `!r.Computed`. Also, in my code, I can tell if a variable that is set has been unset using this: `return new.Exists && !(new.hasZeroValue() && !old.hasZeroValue())`. You can also see this use case being represented in the tests.

**Comment by julienduchesne** [comment]
So? What do you think? Is there anything I can modify to make this pass?
As it is, I do not have the information necessary using ResourceDiff to make my code work. I need this to differentiate at plan-time between two distinct sets of attributes that can be used to create a resource.

**Comment by teamterraform** [comment]
Hello, and sorry for the long silence!
The Terraform SDK has been extracted to its own repository (https://github.com/hashicorp/terraform-plugin-sdk). In support of this we are freezing the related codepaths in Terraform and closing PRs. Thank you!

**Pull request closed without merging**
