### PR TITLE
core: fix for #813 - added a gaurd for interface conversion

### PR DESCRIPTION
**Pull request by gosuri**

### CODE REVIEW

**Comment by svanharmelen** [comment]
@gosuri I see the problem and what you are trying to do, but this solution also prevents the set count (.#) to be written to the state... So it would be better to have something like this:

```
254: k := strings.Join(addr, ".")
255:
256: if value == nil {
257:    w.result[k+".#"] = "0"
258:    return nil
259: }
```

If your up to refactor this it's all yours, otherwise I'll prep something like this in a few...

Thx!

**Comment by gosuri** [comment]
Ah! Makes sense!

**Comment by svanharmelen** [comment]
LGTM! Thanks!

**Comment by mitchellh** [comment]
It'd be good to have a test for this added so it doesn't happen again (to TestFieldWriterMap)

**Comment by mitchellh** [comment]
I pushed a test up

**Comment by svanharmelen** [comment]
Nice one!

Should have thought about a test before merging, sorry about that...

**Pull request merged**
