### PR TITLE
Openstack / Add endpoint type provider configuration

### PR DESCRIPTION
**Pull request by ggiamarchi**
Add the possibility to specify the endpoint type (public, admin, internal). The default remains the same (public).

### CODE REVIEW

**Comment by mitchellh** [comment]
LGTM!

**Comment by hartzell** [comment]
[I'm not sure if I should bring this up here, or file a bug report or if there's a mailing list, or ....    I'd appreciate feedback on how the community does this]

After updating this morning, terraform pesters me for two pieces of information that it didn't ask for before:

```
PUB-0MJ250:nebula-pgperl-builder georgewh$ terraform plan
provider.openstack.api_key
  Enter a value:

provider.openstack.endpoint_type
  Enter a value:

Refreshing Terraform state prior to plan...
```

It's happy for me to just hit carriage return for both.

I think that the request for the endpoint type is an effect of this change.  I haven't tracked down what changed (which commit) to cause it to prompt for the api key.

It's a problem for me to have to hit return to these two questions every time, this should not require manual intervention.

It seems like the logic in openstack/provider's Provider() func seems too simplistic;

- W.R.T. the endpoint type setting, if I didn't provide it and it's optional, why prompt for it?
- W.R.T. the api key, there isn't a simple constraint on a single value;  one must provide either an api key (via OS_AUTH_TOKEN) or a password (via OS_PASSWORD).  I suspect specifying both is an error and specifying neither is an error, which one you would prompt for if neither is specified is a mystery.

**Comment by ggiamarchi** [comment]
@hartzell I don't know why in your situation you get prompted. But waiting for a complete answer you can add `-input=false` to prevent terraform to ask you anything.

**Comment by mitchellh** [comment]
Hm, if we set a default value we shouldn't be prompted.

**Pull request merged**
