### PR TITLE
add support GTD enabled domains to DME provider

### PR DESCRIPTION
**Pull request by ashmere**
specifically this adds support got gtdlocation to the dnsmadeeasy provider

### CODE REVIEW

**Comment by ashmere** [comment]
@radeksimko do you need me to do anything else to get this accepted?

**Comment by ashmere** [comment]
@soniah anything you can do to get this accepted?

**Comment by soniah** [comment]
Hi @ashmere I'm not on the team, so can't do anything :-( But thanks for asking me, reminds me there's things I need to backport to https://github.com/soniah/terraform-provider-dme and vice versa.

Adding Jack Pearkes @pearkes from Terraform, see if he can help.

**Comment by ashmere** [comment]
Hi @pearkes is there anything that needs doing to get this accepted we have been using this in production for a month with no issues

**Comment by jen20** [comment]
Hi @ashmere! Thanks for opening this PR - sorry about the amount of time it took to review it. I've rebased it and squashed the commits, and the changes are now on master in `45b3b9d`.

While I was working on this one thing I noted was that this provider does not follow the conventions of most others of using `_` separators in words - to keep it consistent with itself I merged this one using `gtdlocation` rather than the usually `gtd_location` format, but something we may want to consider is deprecating these fields in favour of the usual Terraform schema naming conventions.

Thanks for your work!

**Pull request closed without merging**
