### PR TITLE
fix whitespace in json derived from iam_policy_document

### PR DESCRIPTION
**Pull request by djosephsen**
Please see my comments at the bottom of https://github.com/hashicorp/terraform/issues/4273

Thanks!

### CODE REVIEW

**Comment by catsby** [comment]
This looks fine from here, but TravisCI says it need to have `go fmt` ran

**Comment by djosephsen** [comment]
I don't _think_ that ssh failure is mine?

**Comment by djosephsen** [comment]
Does the current travis failure on this pr have anything to do with my change? I didn't go anywhere near `hashicorp/terraform/communicator/shared` do I need to provide an ssh key of some kind to get clean builds?

**Comment by radeksimko** [comment]
Hi @djosephsen 
is it possible that @catsby and you know more than myself? 😄 

While I believe there's a bug somewhere in policy parsing, I don't think this PR would make any specific difference in changing any behaviour.

1) Data sources are read-only, so there's always a single version of the data source - single state, nothing to compare in `DiffSuppressFunc`. Data sources never generate diffs. Resources do.
2) `DiffSuppressFunc` doesn't affect how the given field is stored in the state and what is then shared with other resources when referencing such field. `StateFunc` does.
2) The `json` field is Computed-only which means user cannot specify it in the config and therefore `ValidateFunc` will never be triggered.

---

Would either of you mind sharing either repro case or at least `plan` output? It's more likely that a resource which has a `policy` field needs to be fixed.

**Comment by djosephsen** [comment]
Hi @radeksimko.  Unfortunately I'm no longer with the org I was at when I opened this PR, so I don't have access to the repos any longer.  Sorry about that. If no one else can verify this is still an issue I'd say go ahead and close it.

**Comment by apparentlymart** [comment]
Thanks for your work here, @djosephsen. Sorry it sat here unattended for so long.

All of what @radeksimko said above matches my understanding of data sources, so indeed I think this change doesn't get to the root problem here, though I can see that it might help in certain cases if the result is being used with a resource whose underlying API happens to agree with how the JSON gets normalized here.

Your change here was the right idea but I think not the right place. The changes you made here would make sense to apply to any attribute that accepts an IAM policy as _input_; doing it there ensures that we do it at the point where the config and state are being compared as part of producing the diff.

Thanks again for the work here, and sorry we weren't able to get back to you in time to dig into this properly. :disappointed:

**Pull request closed without merging**
