### PR TITLE
Terraform vSphere Snapshot management resources by GSLab

### PR DESCRIPTION
**Pull request by idmsubs**
Please review code changes implemented for vSphere snapshot management resources.

Resources implemented are :
a. Snapshot management (Create and delete snapshot)
b. Revert snapshot

Referred https://github.com/hashicorp/terraform/blob/master/.github/CONTRIBUTING.md for following standards for Terraform provider.

Please suggest changes if required any.

### CODE REVIEW

**Comment by idmsubs** [comment]
Travis CI build failing due to issue - https://github.com/hashicorp/terraform/issues/14232

**Comment by Freyert** [comment]
@idmsubs the built in providers have been moved out of master. You will need to remake these changes over on https://github.com/terraform-providers/terraform-provider-vsphere

**Comment by idmsubs** [comment]
With recent Terraform release and new provider changes, require to create new PR with individual provider repo. Closing this PR.

**Comment by grubernaut** [comment]
Thanks @idmsubs, and apologies for the extra work required here!

**Comment by idmsubs** [comment]
Opened https://github.com/terraform-providers/terraform-provider-vsphere/pull/107 with new changes for provider.

@grubernaut no problem

**Pull request closed without merging**
