### PR TITLE
website: document state environments

### PR DESCRIPTION
**Pull request by mitchellh**
Title is self-explanatory!

### CODE REVIEW

**Comment by shanielh** [comment]
If I understand correct, there will be no interpolation variable `environment` or something that I may use to configure specific differences between the environments?

**Comment by mitchellh** [comment]
@shanielh Actually we planned for that but not sure it'll make it in prior to 0.9. It'll come shortly after though.

**Comment by mitchellh** [comment]
@shanielh Its going to make it in: https://github.com/hashicorp/terraform/pull/12660

**Comment by shanielh** [comment]
@mitchellh Awesome, what about support of the [terraform remote state provider](https://www.terraform.io/docs/providers/terraform/d/remote_state.html)?

**Pull request merged**
