### PR TITLE
Adding ignore_changes lifecycle flag

### PR DESCRIPTION
**Pull request by robzienert**
First stab at adding an "ignore_updates" lifecycle flag; addresses https://github.com/hashicorp/terraform/issues/2437.

### CODE REVIEW

**Comment by joekhoobyar** [comment]
+1

**Comment by maxenglander** [comment]
+1!

**Comment by JeanMertz** [comment]
Yes! Just came looking for this after:

```
~ aws_eip.core
    instance: "i-92eeed5c" => ""
```

as I can't let Terraform manage this EIP.

**Comment by dalehamel** [comment]
:+1:

**Comment by dalehamel** [comment]
Unfortunately, doesn't seem to work:

```
* aws_route_table.subnet_routing_table.0: diffs didn't match during apply. This is a bug with Terraform and should be reported.

```

Maybe this is just an issue with resources with count?

**Comment by pmoust** [comment]
Hi @robzienert , please have a look at https://github.com/hashicorp/terraform/issues/2018#issuecomment-105624364 where a meta-paremeter is proposed to ignore changes in targeted attributes of a resource.

**Comment by robzienert** [comment]
@pmoust I like this a lot more. Not sure why I didn't see that issue when I was originally working on this PR. I'll work on getting this updated this coming weekend to use a list of properties, rather than being resource-level.

**Comment by berset** [comment]
Would love to see this feature! :+1:

**Comment by robzienert** [comment]
Finally got around to updating the PR. Right now it ignores attributes by their name, not state ID, but I would like to support both however I'm running into an issue with my implementation. For example:

I have a dynamic route on an `aws_route_table` resource. When defining a state ID, like `route.1157028409` in `aws_route_table`, the `route.#` value stays the same, saying that a route is still being removed. Makes me think I'm evaling the diff in the wrong place.

**Comment by phinze** [comment]
@robzienert This is looking good! If you could add a covering unit test or two in our higher level [context tests](https://github.com/hashicorp/terraform/blob/master/terraform/context_plan_test.go), I think this should be merge-able. Let me know if the tests are any trouble and one of us can help pick them up.

**Comment by robzienert** [comment]
Welcome back @phinze. Will look into this - until then, do you have any feedback re my previous comment?

**Comment by phinze** [comment]
Oh right! Sorry about missing that, @robzienert 

> Right now it ignores attributes by their name, not state ID, but I would like to support both however I'm running into an issue with my implementation. 

I'm not sure we should expose the internals of state storage as an interface here. Why would you need to do this instead of just the attribute names?

Based on your example, it looks like you're trying to partially manage the routes on a route table? For that use case I think we should go for a separate `aws_route` resource.

**Comment by robzienert** [comment]
Not exposing the state ID is fine, I was just thinking if people wanted to ignore an individual list item - but that would certainly be better suited with a join resource like `aws_route`. Good call.

**Comment by pmoust** [comment]
Would love to see that landing in 0.6.4, thanks for your efforts

**Comment by robzienert** [comment]
PR updated with a context test.

**Comment by phinze** [comment]
Looks good! Thanks for all your work on this, @robzienert :bow:

**Comment by berset** [comment]
Finally :)

**Pull request merged**
