### PR TITLE
provider/heroku: Heroku addon config_vars retrieved as string array

### PR DESCRIPTION
**Pull request by kubek2k**
* schema change
* acceptance test that checks if config_vars from memcachier addon are going to resource state config_vars field

### CODE REVIEW

**Comment by kubek2k** [comment]
@mitchellh as promised

**Comment by catsby** [comment]
How does this change the configuration file? E.g. what were users expected to enter, and what do they enter now?

**Comment by kubek2k** [comment]
It doesn't change anything because it's output variable.

**Comment by mitchellh** [comment]
Sorry I forgot what is the purpose of this? This excludes the values of the config vars.

**Comment by kubek2k** [comment]
@mitchellh its done this way because heroku doesn't return config_vars as a map - as a matter of fact these are not actual config_vars of an addon, but the list of env variable set by this addon (twisted - I know).

**Comment by mitchellh** [comment]
Got it. I think in that case this should be a `TypeSet`.

**Comment by phinze** [comment]
I had forgotten about this PR - I ended up fixing this quickly in https://github.com/hashicorp/terraform/commit/28875f49cdd50ab976b4432dd278a678c1e9c14f to get acceptance tests to pass.

Heroku had it as an array, so I left it as a TypeLIst. We can revisit converting it to a TypeSet if we like.

Thanks for pushing us in the right direction @kubek2k!

**Pull request closed without merging**
