### PR TITLE
provider/aws: Consolidate duplicate list/set type conversions

### PR DESCRIPTION
**Pull request by tpounds**
Removes some duplicate list/set type conversion methods.

### CODE REVIEW

**Comment by stack72** [comment]
thanks for the PR @tpounds, I think that @apparentlymart should be the person to bless this PR - there may have been some method to why these unwrap funcs were used

Paul

**Comment by apparentlymart** [comment]
If this works then it looks good to me. There's no good reason for the difference here... I think I just didn't spot these functions when I was working on this the first time, and also the Opsworks patch was actually a combination of work from three different people so some inconsistencies inevitably crept in.

I don't have spare cycles right now to test this comprehensively, but I did read the patch and it seemed fine. @tpounds, were you able to run the acceptance tests on this and verify that it's all still working?

**Comment by tpounds** [comment]
@apparentlymart I can't get the acceptance tests to pass. AFAICT, it's unrelated to this change since I latest master fails with the same issue.

```
=== RUN   TestAccAWSOpsworksCustomLayer
--- FAIL: TestAccAWSOpsworksCustomLayer (13.38s)
	testing.go:148: Step 0 error: After applying this step, the plan was not empty:
		
		DIFF:
		
		UPDATE: aws_opsworks_stack.tf-acc
		  default_subnet_id: "subnet-0d62cb26" => ""
		  vpc_id:            "vpc-67fea902" => ""
```

**Comment by stack72** [comment]
I concur, I am getting the same behaviour on master:

```
make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSOpsworksCustomLayer' 2>~/tf.log
==> Checking that code complies with gofmt requirements...
/Users/stacko/Code/go/bin/stringer
GO15VENDOREXPERIMENT=1 go generate $(GO15VENDOREXPERIMENT=1 go list ./... | grep -v /vendor/)
TF_ACC=1 GO15VENDOREXPERIMENT=1 go test ./builtin/providers/aws -v -run=TestAccAWSOpsworksCustomLayer -timeout 120m
=== RUN   TestAccAWSOpsworksCustomLayer
--- FAIL: TestAccAWSOpsworksCustomLayer (58.07s)
	testing.go:148: Step 0 error: After applying this step, the plan was not empty:

		DIFF:

		UPDATE: aws_opsworks_stack.tf-acc
		  default_subnet_id: "subnet-c0f30fb6" => ""
		  vpc_id:            "vpc-b645c2d2" => ""

		STATE:

		aws_iam_instance_profile.opsworks_instance:
		  ID = tf-5658139449227573093_opsworks_instance
		  arn = arn:aws:iam::881237884953:instance-profile/tf-5658139449227573093_opsworks_instance
		  name = tf-5658139449227573093_opsworks_instance
		  path = /
		  roles.# = 1
		  roles.2922581043 = tf-5658139449227573093_opsworks_instance

		  Dependencies:
		    aws_iam_role.opsworks_instance
		aws_iam_role.opsworks_instance:
		  ID = tf-5658139449227573093_opsworks_instance
		  arn = arn:aws:iam::881237884953:role/tf-5658139449227573093_opsworks_instance
		  assume_role_policy = {
		  "Version": "2008-10-17",
		  "Statement": [
		    {
		      "Sid": "",
		      "Effect": "Allow",
		      "Principal": {
		        "Service": "ec2.amazonaws.com"
		      },
		      "Action": "sts:AssumeRole"
		    }
		  ]
		}

		  name = tf-5658139449227573093_opsworks_instance
		  path = /
		  unique_id = AROAIWOYM2J4NPAY3Q4D2
		aws_iam_role.opsworks_service:
		  ID = tf-5658139449227573093_opsworks_service
		  arn = arn:aws:iam::881237884953:role/tf-5658139449227573093_opsworks_service
		  assume_role_policy = {
		  "Version": "2008-10-17",
		  "Statement": [
		    {
		      "Sid": "",
		      "Effect": "Allow",
		      "Principal": {
		        "Service": "opsworks.amazonaws.com"
		      },
		      "Action": "sts:AssumeRole"
		    }
		  ]
		}

		  name = tf-5658139449227573093_opsworks_service
		  path = /
		  unique_id = AROAI7N7T4RMU4MO6ZOH2
		aws_iam_role_policy.opsworks_service:
		  ID = tf-5658139449227573093_opsworks_service:tf-5658139449227573093_opsworks_service
		  name = tf-5658139449227573093_opsworks_service
		  policy = {
		  "Statement": [
		    {
		      "Action": [
		        "ec2:*",
		        "iam:PassRole",
		        "cloudwatch:GetMetricStatistics",
		        "elasticloadbalancing:*",
		        "rds:*"
		      ],
		      "Effect": "Allow",
		      "Resource": ["*"]
		    }
		  ]
		}

		  role = tf-5658139449227573093_opsworks_service

		  Dependencies:
		    aws_iam_role.opsworks_service
		aws_opsworks_custom_layer.tf-acc:
		  ID = e26c7a8a-29d9-4a87-b687-986dae1305d7
		  auto_assign_elastic_ips = false
		  auto_assign_public_ips = true
		  auto_healing = true
		  custom_configure_recipes.# = 0
		  custom_deploy_recipes.# = 0
		  custom_instance_profile_arn =
		  custom_security_group_ids.# = 2
		  custom_security_group_ids.1845968770 = sg-6956b611
		  custom_security_group_ids.3878996456 = sg-6a56b612
		  custom_setup_recipes.# = 0
		  custom_shutdown_recipes.# = 0
		  custom_undeploy_recipes.# = 0
		  drain_elb_on_shutdown = true
		  ebs_volume.# = 1
		  ebs_volume.3575749636.iops = 0
		  ebs_volume.3575749636.mount_point = /home
		  ebs_volume.3575749636.number_of_disks = 2
		  ebs_volume.3575749636.raid_level = 0
		  ebs_volume.3575749636.size = 100
		  ebs_volume.3575749636.type = gp2
		  install_updates_on_boot = true
		  instance_shutdown_timeout = 300
		  name = tf-5658139449227573093
		  short_name = tf-ops-acc-custom-layer
		  stack_id = 28a3e333-6655-413a-ad35-ecf120ef1a83
		  system_packages.# = 2
		  system_packages.1368285564 = git
		  system_packages.2937857443 = golang
		  use_ebs_optimized_instances = false

		  Dependencies:
		    aws_security_group.tf-ops-acc-layer1
		    aws_security_group.tf-ops-acc-layer2
		    aws_opsworks_stack.tf-acc
		aws_opsworks_stack.tf-acc:
		  ID = 28a3e333-6655-413a-ad35-ecf120ef1a83
		  berkshelf_version = 3.2.0
		  color =
		  configuration_manager_name = Chef
		  configuration_manager_version = 11.10
		  custom_cookbooks_source.# = 1
		  custom_json = {"key": "value"}
		  default_availability_zone = us-east-1c
		  default_instance_profile_arn = arn:aws:iam::881237884953:instance-profile/tf-5658139449227573093_opsworks_instance
		  default_os = Amazon Linux 2014.09
		  default_root_device_type = ebs
		  default_ssh_key_name =
		  default_subnet_id = subnet-c0f30fb6
		  hostname_theme = Layer_Dependent
		  manage_berkshelf = false
		  name = tf-5658139449227573093
		  region = us-east-1
		  service_role_arn = arn:aws:iam::881237884953:role/tf-5658139449227573093_opsworks_service
		  use_custom_cookbooks = false
		  use_opsworks_security_groups = false
		  vpc_id = vpc-b645c2d2

		  Dependencies:
		    aws_iam_role.opsworks_service
		    aws_iam_instance_profile.opsworks_instance
		aws_security_group.tf-ops-acc-layer1:
		  ID = sg-6956b611
		  description = Managed by Terraform
		  egress.# = 0
		  ingress.# = 1
		  ingress.490428346.cidr_blocks.# = 1
		  ingress.490428346.cidr_blocks.0 = 0.0.0.0/0
		  ingress.490428346.from_port = 8
		  ingress.490428346.protocol = icmp
		  ingress.490428346.security_groups.# = 0
		  ingress.490428346.self = false
		  ingress.490428346.to_port = -1
		  name = tf-5658139449227573093-layer1
		  owner_id = 881237884953
		  tags.# = 0
		  vpc_id = vpc-b645c2d2
		aws_security_group.tf-ops-acc-layer2:
		  ID = sg-6a56b612
		  description = Managed by Terraform
		  egress.# = 0
		  ingress.# = 1
		  ingress.490428346.cidr_blocks.# = 1
		  ingress.490428346.cidr_blocks.0 = 0.0.0.0/0
		  ingress.490428346.from_port = 8
		  ingress.490428346.protocol = icmp
		  ingress.490428346.security_groups.# = 0
		  ingress.490428346.self = false
		  ingress.490428346.to_port = -1
		  name = tf-5658139449227573093-layer2
		  owner_id = 881237884953
		  tags.# = 0
		  vpc_id = vpc-b645c2d2
FAIL
exit status 1
FAIL	github.com/hashicorp/terraform/builtin/providers/aws	58.094s
```

**Comment by stack72** [comment]
@tpounds this error has nothing to do with your PR so merging :) thanks for the help here

**Pull request merged**
