### PR TITLE
provider/openstack: increase instance timeout from 10 to 30 minutes

### PR DESCRIPTION
**Pull request by nicgrayson**
This is a temporary fix for #4129

### CODE REVIEW

**Comment by jtopjian** [comment]
I'm OK with this change. I'll get this merged later on tonight. 

I'm also going to review the other provider code to see if this is being handled in a different way (/cc @phinze ?)

**Comment by phinze** [comment]
@jtopjian yeah we have some early proposals floating around for generalized timeout definition / customization for resource CRUD operations. I'd expect to see movement towards some sort of core feature to help manage timeouts in the medium term.

**Comment by jtopjian** [comment]
@nicgrayson Thanks! Please feel free to submit any other PRs where you're hitting a timeout.

**Comment by reubenavery** [comment]
I'm also hitting this timeout with AWS creating EKS clusters.  Would be great if one could pass an arg or environment var to terraform apply increasing it.

**Pull request merged**
