### PR TITLE
Fix races in GetVariableValue and login

### LINKED ISSUE #24589: concurrent map read and map write in GetVariableValue
### Terraform Version
```
0.12.23
```

### Terraform Configuration Files
* Private configuration :/; 
* 2 providers (AWS and one custom), 8 modules, data sources, s3 backend...

I could provide more details privately.

### Debug Output & Crash Output
The trace is absurdly long but its during the DAG walk:
Here are some of the traces an stacktrace
```
[...]
2020/04/07 14:00:55 [TRACE] [walkValidate] Exiting eval tree: module.some-module.var.some-var
2020/04/07 14:00:55 [TRACE] <root>: eval: *terraform.EvalSetModuleCallArguments
2020/04/07 14:00:55 [TRACE] <root>: eval: *terraform.evalVariableValidations
fatal error: concurrent map read and map write
2020/04/07 14:00:55 [TRACE] <root>: eval: *terraform.EvalSequence
2020/04/07 14:00:55 [TRACE] <root>: eval: *terraform.EvalOpFilter
2020/04/07 14:00:55 [TRACE] <root>: eval: *terraform.EvalModuleCallArgument
2020/04/07 14:00:55 [TRACE] <root>: eval: *terraform.EvalSetModuleCallArguments
2020/04/07 14:00:55 [TRACE] <root>: eval: *terraform.evalVariableValidations
2020/04/07 14:00:55 [TRACE] evalVariableValidations: not active for module.some-db-1.var.datadog_monitor_cpuutilization_config, so skipping
2020/04/07 14:00:55 [TRACE] [walkValidate] Exiting eval tree: module.some-db-1.var.datadog_monitor_cpuutilization_config

goroutine 1611 [running]:
runtime.throw(0x2aadf42, 0x21)
	/opt/goenv/versions/1.12.13/src/runtime/panic.go:617 +0x72 fp=0xc00154f508 sp=0xc00154f4d8 pc=0x102bcc2
runtime.mapaccess2_faststr(0x2744440, 0xc000e414a0, 0xc0012684b0, 0x26, 0xc00139ef28, 0x0)
	/opt/goenv/versions/1.12.13/src/runtime/map_faststr.go:116 +0x4a9 fp=0xc00154f578 sp=0xc00154f508 pc=0x1012709
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).GetVariableValue(0xc001e54270, 0xc00086d680, 0x1, 0x1, 0xc0012684b0, 0x26, 0x0, 0x2f6f5e0, 0x100b709, 0x48)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval_context_builtin.go:318 +0xa6 fp=0xc00154f5b8 sp=0xc00154f578 pc=0x1adeb36
github.com/hashicorp/terraform/terraform.(*evalVariableValidations).Eval(0xc001344f50, 0x2fa47a0, 0xc001e54270, 0x2, 0x2, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval_variable.go:138 +0xc0 fp=0xc00154fac8 sp=0xc00154f5b8 pc=0x1aff2c0
github.com/hashicorp/terraform/terraform.EvalRaw(0x2f2bec0, 0xc001344f50, 0x2fa47a0, 0xc001e54270, 0x0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131 fp=0xc00154fb90 sp=0xc00154fac8 pc=0x1ad5ac1
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc001d98220, 0x2fa47a0, 0xc001e54270, 0x2, 0x2, 0x1af3f25, 0x2f2bec0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:20 +0xfd fp=0xc00154fc40 sp=0xc00154fb90 pc=0x1af3d4d
github.com/hashicorp/terraform/terraform.EvalRaw(0x2f2b980, 0xc001d98220, 0x2fa47a0, 0xc001e54270, 0x27356e0, 0x3fdb8e5, 0x269d020, 0xc001af0630)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131 fp=0xc00154fd08 sp=0xc00154fc40 pc=0x1ad5ac1
github.com/hashicorp/terraform/terraform.Eval(0x2f2b980, 0xc001d98220, 0x2fa47a0, 0xc001e54270, 0xc001d98220, 0x2f2b980, 0xc001d98220, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval.go:35 +0x4d fp=0xc00154fd58 sp=0xc00154fd08 pc=0x1ad591d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x28f6ae0, 0xc00140d8c0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/graph.go:90 +0xf40 fp=0xc00154fe80 sp=0xc00154fd58 pc=0x1b71050
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc001429780, 0x28f6ae0, 0xc00140d8c0, 0xc001ad00c0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:392 +0x353 fp=0xc00154ffc0 sp=0xc00154fe80 pc=0x1a85183
runtime.goexit()
	/opt/goenv/versions/1.12.13/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00154ffc8 sp=0xc00154ffc0 pc=0x1058ec1
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:314 +0xa9b

goroutine 1 [select]:
github.com/hashicorp/terraform/command.(*Meta).RunOperation(0xc0003f4820, 0x2f87180, 0xc0007281a0, 0xc0005bda40, 0x2f6f6e0, 0xc000598188, 0xc00056e2c0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/meta.go:291 +0x216
github.com/hashicorp/terraform/command.(*PlanCommand).Run(0xc0003f4820, 0xc00003a0a0, 0x2, 0x2, 0xc0001419f0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/plan.go:175 +0x1285
github.com/mitchellh/cli.(*CLI).Run(0xc000108a00, 0xc000108a00, 0xc00052fd90, 0x1)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1f1
main.wrappedMain(0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:239 +0xc33
main.realMain(0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:103 +0xb4
main.main()
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:39 +0x3b

goroutine 34 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0002645a0)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/go.opencensus.io@v0.22.0/stats/view/worker.go:154 +0x100
created by go.opencensus.io/stats/view.init.0
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/go.opencensus.io@v0.22.0/stats/view/worker.go:32 +0x57

goroutine 35 [syscall]:
os/signal.signal_recv(0x0)
	/opt/goenv/versions/1.12.13/src/runtime/sigqueue.go:139 +0x9f
os/signal.loop()
	/opt/goenv/versions/1.12.13/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/opt/goenv/versions/1.12.13/src/os/signal/signal_unix.go:29 +0x41

goroutine 18 [chan receive]:
main.makeShutdownCh.func1(0xc00004e840, 0xc0000422a0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/commands.go:387 +0x34
created by main.makeShutdownCh
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/commands.go:385 +0xf2

goroutine 229 [select]:
github.com/hashicorp/terraform/dag.(*Walker).waitDeps(0xc001429780, 0x29abd40, 0xc000a9e500, 0xc00195ffb0, 0xc00178e700, 0xc0014b8240)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:428 +0x25a
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:307 +0xde2

goroutine 236 [select]:
github.com/hashicorp/terraform/dag.(*Walker).waitDeps(0xc001429780, 0x2911680, 0xc000c147b0, 0xc0018b2270, 0xc001958700, 0xc00195aae0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:428 +0x25a
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:307 +0xde2
[...]
```
A lot of goroutines, but there are 3 recurring ones:
```
goroutine 2351 [select]:
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc001429780, 0x28f6ae0, 0xc00140da80, 0xc000d16240)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:345 +0x1ac
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:314 +0xa9b

goroutine 2352 [chan send]:
github.com/hashicorp/terraform/terraform.Semaphore.Acquire(...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/util.go:25
github.com/hashicorp/terraform/terraform.(*ContextGraphWalker).EnterEvalTree(0xc0012b60c0, 0x28f6ae0, 0xc00140a880, 0x2f2b980, 0xc0019145a0, 0xc000cea800, 0x33)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/graph_walk_context.go:104 +0xfa
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x28f6ae0, 0xc00140a880, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/graph.go:89 +0xf11
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc001429780, 0x28f6ae0, 0xc00140a880, 0xc000d163c0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:392 +0x353
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:314 +0xa9b

goroutine 229 [select]:
github.com/hashicorp/terraform/dag.(*Walker).waitDeps(0xc001429780, 0x29abd40, 0xc000a9e500, 0xc00195ffb0, 0xc00178e700, 0xc0014b8240)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:428 +0x25a
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:307 +0xde2
```

There is one routine thats a singleton and has walk.go in it:
```
goroutine 63 [semacquire]:
sync.runtime_Semacquire(0xc0014297d8)
	/opt/goenv/versions/1.12.13/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc0014297d0)
	/opt/goenv/versions/1.12.13/src/sync/waitgroup.go:130 +0x65
github.com/hashicorp/terraform/dag.(*Walker).Wait(0xc001429780, 0xc001001540, 0x2b2d8a8, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:114 +0x49
github.com/hashicorp/terraform/dag.(*AcyclicGraph).Walk(0xc001001540, 0xc0014aefc0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/dag.go:173 +0xe0
github.com/hashicorp/terraform/terraform.(*Graph).walk(0xc001001540, 0x2f832e0, 0xc0012b60c0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/graph.go:140 +0x1fd
github.com/hashicorp/terraform/terraform.(*Graph).Walk(...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/graph.go:38
github.com/hashicorp/terraform/terraform.(*Context).walk(0xc00057c1e0, 0xc001001540, 0x5, 0xc000f01a00, 0x1, 0x1, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/context.go:767 +0x20b
github.com/hashicorp/terraform/terraform.(*Context).Validate(0xc00057c1e0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/context.go:682 +0x1d6
github.com/hashicorp/terraform/backend/local.(*Local).context(0xc0007281a0, 0xc0005bda40, 0x1, 0x1, 0x2, 0xc000518100, 0x1, 0x2, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/backend/local/backend_local.go:120 +0x974
github.com/hashicorp/terraform/backend/local.(*Local).opPlan(0xc0007281a0, 0x2f6db60, 0xc0001f2c80, 0x2f6db60, 0xc0001f2cc0, 0xc0005bda40, 0xc0001f2c40)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/backend/local/backend_plan.go:70 +0x2a3
github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc00064f080, 0xc00064f090, 0xc00064f0a0, 0xc0005bda40, 0xc0007281a0, 0xc0001f2c40, 0xc00064f070, 0x2f6db60, 0xc0001f2c80, 0x2f6db60, ...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/backend/local/backend.go:350 +0x135
created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/backend/local/backend.go:334 +0x36b
```

### Expected Behavior
No crash :) Keep going with the plan...

### Actual Behavior
Golang crash, no release of the lock

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### Additional Context
running plain tf on osx and linux.
Linux is containerized.

### Early thoughts
It seems the following comment is wrong:
https://github.com/hashicorp/terraform/blob/v0.12.23/dag/walk.go#L44
```
	// changeLock must be held to modify any of the fields below. Only Update
	// should modify these fields. Modifying them outside of Update can cause
	// serious problems.
```
even reads should be protected as shown by the error thrown.

I couldn't find the read thats causing it just yet.

### PR DESCRIPTION
**Pull request by jbardin**
Fix a few races that had crept into the codebase. Now that we've moved to a new CI system, we can probably start testing for these automatically, but there will still be some test fixtures that need updating.

- `GetVariableValue` was missing the variable mutex calls.
- The `login` command had a race around a closed-over `err` value.
- The `testHook` mock wasn't synchronized in the tests.
- Missing call to `wg.Wait()` caused a race in the deferred cleanup function.

Fixes #24589

### CODE REVIEW

**Comment by corentone** [comment]
Thank you @jbardin !

For my education, --if you have time-- could you describe roughly how you were able to reproduce/identify the issue? I'm not too familiar with the TF code so it was tricky for me ( I swear I tried!)
I was looking at the DAG so I was pretty off from where you found the missing lock. The stacktrace, being in GetVariableValue, is not found again in the stacktrace but I only found in two other goroutines in the stacktrace that are in the `Eval` areas (but not explicitely GetVariableValue), so that would likely be them?

**Comment by jbardin** [comment]
No problem @corentone,

The most relevant portion of a stack trace is always the fist stack. Since this is a fatal error and not a normal panic, it's coming out of the runtime and we don't have the corresponding read/write locations like we would from the race-detector, but it will show a map access somewhere. If you step back through the frames of that first stack, the first instance of terraform code you encounter is the `GetVariableValue` call. From here it was a quick diagnosis, since the mutex for the variables map was missing from that method. (If that method was not supposed to be safe for concurrent access in the first place, that would be a larger issue to diagnose)

I actually don't have a test fixture to trigger this at the moment, as any test configuration I have doesn't end up triggering the race. I have an idea to create a larger config that will, but since this bug is simple to visually inspect we can leave that for later, and try to fish out more of these in the long term with some fuzzing.

Thanks for reporting it!

**Comment by Ninir** [comment]
@jbardin Do you know if this will be backported to TF 0.12.X somehow? 🙏

**Comment by Ninir** [comment]
@jbardin Do you think We can backport that to a patch version for the TF 0.12 branch somehow?

I've heard reports of this impacting some people, and this is biting us also.

**Pull request merged**
