### PR TITLE
provider/aws: Support additional changes to security groups of instance without forcing new

### PR DESCRIPTION
**Pull request by innossh**
With this pull request, `security_groups` can now be updated without forcing a new instance.

API reference for Modify Instance Attribute:
http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyInstanceAttribute.html

[description]
First apply the following sample config:

```
resource "aws_instance" "web" {
    ami = "ami-383c1956"
    instance_type = "t2.micro"
    security_groups = [
        "${aws_security_group.tf_test_foo.name}"
    ]
}

resource "aws_security_group" "tf_test_foo" {
  name = "tf_test_foo"
  description = "foo"

  ingress {
    protocol = "icmp"
    from_port = -1
    to_port = -1
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_security_group" "tf_test_bar" {
  name = "tf_test_bar"
  description = "bar"

  ingress {
    protocol = "icmp"
    from_port = -1
    to_port = -1
    cidr_blocks = ["0.0.0.0/0"]
  }
}
```

Next change the `security_groups` in `aws_instance` :

```
resource "aws_instance" "web" {
...
    security_groups = [
        "${aws_security_group.tf_test_bar.name}" # changed
    ]
}
...
```

In this case, `terraform plan` results into:

```
-/+ aws_instance.web
    ami:                        "ami-383c1956" => "ami-383c1956"
...
    security_groups.#:          "1" => "1"
    security_groups.1111111111: "" => "tf_test_bar" (forces new resource)
    security_groups.2222222222: "tf_test_foo" => ""
...

Plan: 1 to add, 0 to change, 1 to destroy.
```

The instance will be destroyed when the re-creating is not necessary. :disappointed: 
But with this pull request, like this:

```
~ aws_instance.web
    security_groups.1111111111: "" => "tf_test_bar"
    security_groups.2222222222: "tf_test_foo" => ""


Plan: 0 to add, 1 to change, 0 to destroy.
```

### CODE REVIEW

**Comment by innossh** [comment]
I want to change `security_groups` of instance without forcing new. :smiley: 
Could anyone check this one? Thanks.

**Comment by jamielennox1** [comment]
This would be incredibly helpful. Never really understood why It destroys the instance just to change the security group.

**Comment by stack72** [comment]
@innossh thanks so much for the PR. Currently running all the Instance tests to make sure all is well. Pending those going green, will merge :)

**Comment by stack72** [comment]
```
make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSInstance_' 2>~/tf.log
==> Checking that code complies with gofmt requirements...
/Users/stacko/Code/go/bin/stringer
go generate $(go list ./... | grep -v /vendor/)
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSInstance_ -timeout 120m
=== RUN   TestAccAWSInstance_basic
--- PASS: TestAccAWSInstance_basic (207.34s)
=== RUN   TestAccAWSInstance_blockDevices
--- PASS: TestAccAWSInstance_blockDevices (148.30s)
=== RUN   TestAccAWSInstance_sourceDestCheck
--- PASS: TestAccAWSInstance_sourceDestCheck (273.32s)
=== RUN   TestAccAWSInstance_disableApiTermination
--- PASS: TestAccAWSInstance_disableApiTermination (194.67s)
=== RUN   TestAccAWSInstance_vpc
--- PASS: TestAccAWSInstance_vpc (157.30s)
=== RUN   TestAccAWSInstance_multipleRegions
--- PASS: TestAccAWSInstance_multipleRegions (167.49s)
=== RUN   TestAccAWSInstance_NetworkInstanceSecurityGroups
=== RUN   TestAccAWSInstance_NetworkInstanceVPCSecurityGroupIDs
--- PASS: TestAccAWSInstance_NetworkInstanceVPCSecurityGroupIDs (218.34s)
=== RUN   TestAccAWSInstance_tags
--- PASS: TestAccAWSInstance_tags (151.04s)
=== RUN   TestAccAWSInstance_privateIP
--- PASS: TestAccAWSInstance_privateIP (287.71s)
=== RUN   TestAccAWSInstance_associatePublicIPAndPrivateIP
--- PASS: TestAccAWSInstance_associatePublicIPAndPrivateIP (257.65s)
=== RUN   TestAccAWSInstance_rootBlockDeviceMismatch
--- PASS: TestAccAWSInstance_rootBlockDeviceMismatch (171.78s)
=== RUN   TestAccAWSInstance_forceNewAndTagsDrift
--- PASS: TestAccAWSInstance_forceNewAndTagsDrift (316.09s)
```

**Comment by innossh** [comment]
@phinze I haven't noticed about classic environments. :cry:
Thank you for the information and your time.

**Comment by vitroth** [comment]
FYI, I noticed that while this PR got reverted, the changelog entry for this still exists in the changelog for 0.6.13: `provider/aws: aws_instance now allows changes to security groups without force new resource (#5193)`

**Comment by stack72** [comment]
Hi @vitroth 

you are indeed correct - i will take care of that - thanks for pointing it out

Paul

**Comment by catsby** [comment]
Hey @cbarbour – I followed up in #11276 but wanted to post here as well that this change not appearing in the changelog is likely because it was reverted in #5571

**Pull request merged**
