### PR TITLE
Update 404 page

### PR DESCRIPTION
**Pull request by ajlanghorn**
The existing 404 page didn't quite fit in with the style of the rest of the site.
Fixes this by adding a layout value for use during rendering, and adds some nicer markup.

Feel free to suggest modifications and make comments. I didn't include links to the intro,
the docs or the community page since they're already visible in the "inner" layout, and
because I find them sometimes a touch annoying.

### CODE REVIEW

**Comment by ajlanghorn** [comment]
Here's the page as it currently stands:

screen shot 2015-09-19 at 17 06 16

**Comment by radeksimko** [comment]
Thanks for noticing!

Would you mind adding `page_title: "404"` as well, so we can fix the header too?
Here's how it looks like after applying this PR:

screen shot 2015-09-19 at 17 37 38

**Comment by ajlanghorn** [comment]
@radeksimko Yep, just noticed that when running locally. Commit coming right up.

**Comment by ajlanghorn** [comment]
@radeksimko I've added a `page_title` key, and rebased. It's now inside 0e16480. Here's how it now looks when running locally:

screen shot 2015-09-19 at 17 42 01

**Comment by radeksimko** [comment]
Great, thanks Andrew

**Comment by ajlanghorn** [comment]
:sunglasses:

**Pull request merged**
