### PR TITLE
[WIP] provider/github: Adding in github release + tag capabilities

### PR DESCRIPTION
**Pull request by mnzt**
Adds in ability to create GitHub tags and releases. Example module:
```
provider "github" {
  token        = "J. R. R. Token"
  organization = "hashicorp"
}

resource "github_repository_tag" "tag" {
  repo   = "terraform"
  tag    = "v1.0.0"
  commit = "1234567891011121314151617181920212223242"

  author = "Terraform Release"
  email = "support@somewhere.io"
}

resource "github_repository_release" "testing" {
  repo       = "terraform"
  tag        = "v1.0.0"
  committish = "master" // This may be able to be removed in favour of tag refs

  name  = "Release 1.0.0"
  draft = true
}

```

# NOTE:
I had to update github.com/google/go-github for this to be possible. The github plugin still builds.

# TODO:
- [ ] Tests!
- [ ] Ensure releases and tags can be updated, without forcing new

### CODE REVIEW

**Comment by jason-riddle** [comment]
Any update on this?

**Comment by mnzt** [comment]
@jason-riddle This is functional, just needs testing and pulling in master.

I'm unsure whether the second point in the TODO is possible

**Comment by stack72** [comment]
ping @mnzt 

Is this still an active PR?

**Comment by apparentlymart** [comment]
Hello @mnzt, and thanks for working on this!

As part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it.

If you or someone else has the time and motivation to apply the same changes to [the `github` provider repository](https://github.com/terraform-providers/terraform-provider-github) and open a new PR there, maintainers of that provider may be able to review it.

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Pull request closed without merging**
