### PR TITLE
Update of obsolete links in 0-13.html.markdown

### PR DESCRIPTION
**Pull request by Noann35**
Addition of the "terraform.io" domain name in the links of the type "/docs/*"

### CODE REVIEW

**Comment by mildwonkey** [comment]
Hi @Noann35, thanks for submitting this.

These are relative links to documents within this repository, not full hyperlinks, so the format that you see is correct.

Is there a problem on the website that lead you to open this PR? I checked this page on our website and didn't find any broken links, though I could have easily missed one: https://www.terraform.io/docs/commands/0.13upgrade.html

 I am going to close this PR, but if there is a broken link that I've missed, please open a GitHub issue. Thanks!

**Comment by Noann35** [comment]
> Hi @Noann35, thanks for submitting this.
> 
> These are relative links to documents within this repository, not full hyperlinks, so the format that you see is correct.
> 
> Is there a problem on the website that lead you to open this PR? I checked this page on our website and didn't find any broken links, though I could have easily missed one: https://www.terraform.io/docs/commands/0.13upgrade.html
> 
> I am going to close this PR, but if there is a broken link that I've missed, please open a GitHub issue. Thanks!

HI @mildwonkey ,

There is no problem on the website.

On the other hand, when I consult this page https://github.com/hashicorp/terraform/blob/master/website/upgrade-guides/0-13.html.markdown
and that I click on a link of the type "/ docs", I arrive on a 404.

For example the link "terraform 0.13upgrade" (docs / commands / 0.13upgrade.html)

Is it wanted?

Solution in this case :
Actual : 
https://github.com/hashicorp/terraform/blob/master/docs/commands/0.13upgrade.html
Expected : 
https://github.com/hashicorp/terraform/blob/master/website/docs/commands/0.13upgrade.html.markdown

**Comment by mildwonkey** [comment]
Yes, that's expected @Noann35. the links work when the page is published to the website, not in github. Sorry for the confusion!

**Comment by Noann35** [comment]
@mildwonkey 

Ok, I understand better why these are relative links.

Sorry for the inconvenience !

**Pull request closed without merging**
