### PR TITLE
`enable` habitat supervisor service before `start`

### PR DESCRIPTION
**Pull request by smartb-pair**
Signed-off-by: Arash Zandi <arash.zandi@smartb.eu> #17224 

Enable Habitat Supervisor before starting the service. We think this should be the default behavior.

### CODE REVIEW

**Comment by nsdavidson** [comment]
👍  This makes total sense to me, and it was an oversight on my part that this was not in the initial implementation.

**Comment by rwc** [comment]
Fixes https://github.com/hashicorp/terraform/issues/17224

**Comment by smartb-pair** [comment]
As this is the first time we've looked at Terraform code, we'd appreciate some guidance here on properly handling tests. @nsdavidson, perhaps you can help?

**Comment by jbardin** [comment]
Hi @smartb-pair,

I'm not sure what happened to this PR, but I moved the commit over to #17781.
Can you verify if that is  all that is required?
Thanks!

**Pull request closed without merging**
