### PR TITLE
provider/pagerduty pagerduty_schedule - support for start_day_of_week (schedule restriction)

### LINKED ISSUE #10033: provider/pagerduty: missing key for weekly layer restriction
### Terraform Version

Terraform v0.7.10

### Affected Resource(s)

- pagerduty_schedule

### Terraform Configuration Files
```hcl
resource "pagerduty_schedule" "PlatformTest" {
    name = "Platform Test"
    time_zone = "America/New_York"
    description = "testing some terraformy stuff"
    
    ## Monday 9am to Wednesday 5pm
    layer {
        name = "M9a-W5p"
        start = "2016-11-13T23:00:00Z"
        rotation_virtual_start = "2016-11-09T23:00:00Z"

        rotation_turn_length_seconds = "${ 7 * 24 * 3600 }" ## 7 days

        restriction {
            type = "weekly_restriction"
            start_time_of_day = "09:00:00"
            start_day_of_week = 1
            duration_seconds = "${ 56 * 3600 }" ## 56 hours
        }
        
        users = [ "PDYDMY2" ]
    }
}
```

### Debug Output

- [terraform-without-start_day_of_week.txt](https://github.com/hashicorp/terraform/files/584753/terraform-without-start_day_of_week.txt)
- [terraform-with-start_day_of_week.txt](https://github.com/hashicorp/terraform/files/584754/terraform-with-start_day_of_week.txt)

### Expected Behavior

Should have been able to create schedule layer with a `weekly_restriction` restriction that specifies the starting day of the week.

### Actual Behavior

When not including the `start_day_of_week` attribute, `terraform apply` gets an error from the PagerDuty API because that attribute is required.  When specifying the attribute in the Terraform config, `terraform apply` fails because the attribute is unknown to the provider.

### PR DESCRIPTION
**Pull request by heimweh**
This should resolve #10033 (waiting for client library fix https://github.com/PagerDuty/go-pagerduty/pull/52 to be merged)

### CODE REVIEW

**Comment by stack72** [comment]
Hi @heimweh 

Any chance you could email me on stack72 at hashicorp.com? Would love to discuss this provider more with you :)

P.

**Comment by paultyng** [comment]
The PR on pagerduty has been merged, so probably just need a vendor update in this and its good to go.

**Comment by heimweh** [comment]
@paultyng thanks for checking up on this one. That's awesome :)

Updated `go-pagerduty` and added tests and they seem to pass now.

```bash
$ make testacc TEST=./builtin/providers/pagerduty TESTARGS='-run=TestAccPagerDutySchedule_Multi'                                                                                                    23:16:30
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/12/16 23:16:56 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/pagerduty -v -run=TestAccPagerDutySchedule_Multi -timeout 120m
=== RUN   TestAccPagerDutySchedule_Multi
--- PASS: TestAccPagerDutySchedule_Multi (10.30s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/pagerduty	10.313s
```

**Comment by stack72** [comment]
Hi @heimweh 

Thanks so much for this - it LGTM! :) 

```
% make testacc TEST=./builtin/providers/pagerduty
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/12/17 12:49:55 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/pagerduty -v  -timeout 120m
=== RUN   TestAccDataSourcePagerDutyUser_Basic
--- PASS: TestAccDataSourcePagerDutyUser_Basic (5.75s)
=== RUN   TestAccPagerDutyVendor_Basic
--- PASS: TestAccPagerDutyVendor_Basic (9.15s)
=== RUN   TestAccPagerDutyEscalationPolicy_import
--- PASS: TestAccPagerDutyEscalationPolicy_import (7.78s)
=== RUN   TestAccPagerDutySchedule_import
--- PASS: TestAccPagerDutySchedule_import (8.31s)
=== RUN   TestAccPagerDutyService_import
--- PASS: TestAccPagerDutyService_import (10.53s)
=== RUN   TestAccPagerDutyTeam_import
--- PASS: TestAccPagerDutyTeam_import (2.90s)
=== RUN   TestAccPagerDutyUser_import
--- PASS: TestAccPagerDutyUser_import (5.12s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProviderImpl
--- PASS: TestProviderImpl (0.00s)
=== RUN   TestAccPagerDutyEscalationPolicy_Basic
--- PASS: TestAccPagerDutyEscalationPolicy_Basic (12.87s)
=== RUN   TestAccPagerDutyEscalationPolicyWithTeams_Basic
--- PASS: TestAccPagerDutyEscalationPolicyWithTeams_Basic (14.64s)
=== RUN   TestAccPagerDutySchedule_Basic
--- PASS: TestAccPagerDutySchedule_Basic (11.65s)
=== RUN   TestAccPagerDutySchedule_BasicWeek
--- PASS: TestAccPagerDutySchedule_BasicWeek (10.37s)
=== RUN   TestAccPagerDutySchedule_Multi
--- PASS: TestAccPagerDutySchedule_Multi (8.59s)
=== RUN   TestAccPagerDutyServiceIntegration_Basic
--- PASS: TestAccPagerDutyServiceIntegration_Basic (27.97s)
=== RUN   TestAccPagerDutyService_Basic
--- PASS: TestAccPagerDutyService_Basic (11.93s)
=== RUN   TestAccPagerDutyTeam_Basic
--- PASS: TestAccPagerDutyTeam_Basic (4.58s)
=== RUN   TestAccPagerDutyUser_Basic
--- PASS: TestAccPagerDutyUser_Basic (5.67s)
=== RUN   TestAccPagerDutyUserWithTeams_Basic
--- PASS: TestAccPagerDutyUserWithTeams_Basic (13.98s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/pagerduty	171.821s
```

**Pull request merged**
