### PR TITLE
build: remove unused scripts 

### PR DESCRIPTION
**Pull request by mildwonkey**
This PR removes some unused release-related code. 

Notes:
* scripts/changelog-links.sh is used directly by our release process; it's probably a good idea to remove it from this repository and drop it in the internal repo eventually: https://github.com/hashicorp/terraform-releases/blob/67d2a39a526aac4b8fbd730cc18eebc4a5faed3b/.circleci/config.yml#L99
* Once this is merged I have a follow-up PR removing references to the legacy release process and tfbuilder in our internal engineering docs; I believe the steps and code are outdated enough that a manual release guide would need to be written from scratch anyway (and if I am mistaken we can discuss it there).

### CODE REVIEW

**Comment by alvin-huang** [comment]
I didn't copy the build scripts over to the `terraform-releases` repo so it's checking out this `terraform` repo and running the scripts from this PWD. We can certainly copy it over to `terraform-releases` and not run it from this repo's context though.

**Comment by mildwonkey** [comment]
Thank you @alvin-huang ! I appreciate confirmation that it's just that one script for releasing. We don't _need_ to move it, I'm mainly trying to clean up unused code so we don't keep getting PRs opened against scripts that aren't used.

**Comment by alvin-huang** [comment]
Makes sense! All of these are good to go except for the Make target you removed. We still run it in CI here: https://github.com/hashicorp/terraform/blob/master/.circleci/config.yml#L25. Feel free to remove it or change it in the CircleCI config if the `gofmtcheck` target should not be run anymore.

**Comment by mildwonkey** [comment]
oh, whoops, I'd meant to restore that - thanks again! It's back!

**Review by alvin-huang — APPROVED** [review]

**Comment by jrottenberg** [comment]
Hello !


https://github.com/hashicorp/terraform-releases/pull/20 that repo seems private, is it expected to become public ?

In case not, can you have a look at https://github.com/hashicorp/terraform/issues/20669 ?

@mildwonkey @alvin-huang 


Thank you !

**Pull request merged**
