### PR TITLE
provider/google: SQL Certs + tests

### PR DESCRIPTION
**Pull request by lwander**
I'm creating this PR because I think something strange is going on with setting nested `computed` fields. I'll elaborate in an associated issue.

### CODE REVIEW

**Comment by radeksimko** [comment]
@lwander Sorry to keep you waiting here.

Would you mind resolving the conflicts?
You may also need to vendor `google.golang.org/api/sqladmin/v1beta4` via `godep`.

**Comment by lwander** [comment]
@radeksimko, I was hoping you could look at the associated issue I opened with this PR #3782

**Comment by radeksimko** [comment]
Ah, right, I see, I guess I misread your original comment, sorry!

Nested & computed fields are troublesome atm, agreed. I remember I had to mark all nested fields as `Computed` when I wanted to make the parent `Computed`. That isn't nice, but I'm not sure I will have time to look into it soon.

**Comment by apparentlymart** [comment]
Hello @lwander, and thanks for working on this!

As part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it.

If this is still needed and you or someone else has the time and motivation to apply the same changes to [the Google Cloud provider repository](https://github.com/terraform-providers/terraform-provider-google) and open a new PR there, the maintainers of that provider should be able to review and merge it.

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Pull request closed without merging**
