### PR TITLE
provider/docker: Add support for registry auth

### PR DESCRIPTION
**Pull request by kyhavlov**
This PR adds support for registry auth when using the `docker_image` resource and `docker_registry_image` data source. The auth config is set in the provider and a docker `config.json`  file can be used or user/pass set directly:

``` hcl
provider "docker" {
  host = "tcp://localhost:2376"

  registry_auth {
    address = "registry.hub.docker.com"
    config_file = "~/.docker/config.json"
  }

  registry_auth {
    address = "quay.io"
    username = "someuser"
    password = "somepass"
  }
}

data "docker_registry_image" "quay" {
  name = "quay.io/org/testimage"
}
```

This PR is basically done, the only thing I'm wondering is if I should configure the provider directly in provider_test instead of passing auth stuff through the test config. This also needs someone from Hashicorp to set up the new env vars for the private image used by the tests on Travis (DOCKER_PRIVATE_IMAGE/DOCKER_REGISTRY_USER/etc).

This is a followup PR to #7000 to do the auth bit, as discussed there and in #6507.

@radeksimko

### CODE REVIEW

**Comment by magnayn** [comment]
This would be very useful!

**Comment by kyhavlov** [comment]
@phinze @radeksimko Any thoughts on this PR?

**Comment by athirn** [comment]
I would also like to see this merged in

**Comment by adveres** [comment]
Very interested in this as a feature.

**Comment by hmcgonig** [comment]
What is left on this PR? Does it just need conflicts resolved and review?

**Comment by ubergesundheit** [comment]
Any update in here? What is blocking the merge? Is there something left to do?

**Comment by LinusU** [comment]
@kyhavlov do you think that you have time to update this? Would really appreciate it 💟

**Comment by mavogel** [comment]
@LinusU @ubergesundheit @hmcgonig @adveres @athirn I just created a [PR](https://github.com/terraform-providers/terraform-provider-docker/pull/21) on the `terraform-provider-docker` where I just used almost all of his code. This feature belongs now there after the split out of the providers.

**Comment by apparentlymart** [comment]
Thanks for migrating this to the new repository, @kyhavlov! I'm going to close this PR, just because it's no longer mergeable in this repository.

**Pull request closed without merging**
