### PR TITLE
Structured plan renderer: connect it with the rest of terraform

### PR DESCRIPTION
**Pull request by liamcervante**
This PR connects the new structured plan renderer with the rest of terraform. It enables it as the default renderer and can be disabled with the flag `-structured-renderer=false`.

**Do not merge this before the one remaining functionality PR: https://github.com/hashicorp/terraform/pull/32496**

## Proposed changelog entry

1.4.0 (unreleased)

UPGRADE NOTES:

- The Terraform plan renderer has been completely rewritten to aid with future Terraform Cloud integration. Users should not see any material change in the plan output between 1.3 and 1.4. Users are encouraged to file reports if they notice material differences, or encounter any bugs or panics during their normal execution of Terraform. Using the `structured-renderer=false` flag will disable the new renderer for any users that do encounter bugs or crashes.

### CODE REVIEW

**Comment by liamcervante** [comment]
Note, the tests are failing with panics as they're waiting for the implementation in the other PR.

**Comment by alisdair** [comment]
Quick pre-review thought: do we definitely need the new CLI flag? There's nothing backwards incompatible in this release, so if there is somehow a significant bug in the diff renderer, users can always roll back. One of the main reasons for this project is to make the diff renderer more maintainable, and keeping the old version around as a crutch will slow the transition.

I'd also suggest adjusting the changelog entry to note the other benefits of the renderer, as it's not a purely Terraform Cloud motivated change.

**Comment by alisdair** [comment]
That aside, this also all looks good to me!

**Comment by liamcervante** [comment]
Closed in favour of https://github.com/hashicorp/terraform/pull/32520

**Pull request closed without merging**
