### PR TITLE
provider/scaleway: update sdk for ams1 region

### PR DESCRIPTION
**Pull request by nicolai86**
this PR updates the Scaleway SDK for the new announced [Amsterdam 1](https://blog.online.net/2016/10/27/scaleway-global-expansion-starts-in-amsterdam/) region.

Previously the Scaleway provider would error when using `ams1` as region, because the SDK did not recognize the region yet.

### CODE REVIEW

**Comment by nicolai86** [comment]
fixes https://github.com/scaleway/scaleway-cli/issues/426

**Comment by nicolai86** [comment]
\cc @tboerger

**Comment by tboerger** [comment]
Cool, thanks!

**Comment by stack72** [comment]
LGTM! Thanks for the work here @nicolai86 :) It will be part of the 0.7.8 release

P.

**Comment by stack72** [comment]
Actually, @nicolai86, this is a breaking change! We need to check the code here

Paul

**Comment by nicolai86** [comment]
Interesting. I'll take a look asap to fix this

**Comment by stack72** [comment]
nps :)

**Comment by nicolai86** [comment]
yay, fixed. tiny SDK incompatability

**Pull request merged**
