### PR TITLE
vendor: Update github.com/gophercloud/gophercloud

### LINKED ISSUE #9965: provider/openstack: openstack_compute_instance_v2 'user_data' gets double encoded
`openstack_compute_instance_v2` `user_data` gets double encoded due to a bug in Gophercloud - See https://github.com/gophercloud/gophercloud/pull/170 for further details.

Pull request incoming to update vendored gophercloud library.

### PR DESCRIPTION
**Pull request by fatmcgav**
Fix issue with double base64 encoding userdata value.
Fixes #9965

### CODE REVIEW

**Comment by fatmcgav** [comment]
@jtopjian Nice easy one... ;)

**Comment by fatmcgav** [comment]
@jtopjian Are you able to cherry pick this one onto maint-0.7 branch? 
As otherwise looks like it won't land until 0.8.0 release...

**Comment by jtopjian** [comment]
@fatmcgav I've marked the change under the 0.7.10 header. Whoever does the maint release should be handling that.

**Comment by jtopjian** [comment]
@fatmcgav Ah, actually I just read the instructions on this. I'll cherry pick this as soon as I can.

**Comment by jtopjian** [comment]
@fatmcgav There was a 0.7.10 release cut today. I didn't get to cherry pick the commit in time. Sorry about that! I'll get it done ASAP and it'll be in the next release.

**Comment by fatmcgav** [comment]
@jtopjian They're not hanging around with 0.7 releases are they... ;) Much appreciated...

**Comment by jtopjian** [comment]
@fatmcgav OK, this is all sorted out. I'm really sorry about that. This change will be in the next 0.7 release as well as 0.8.

**Comment by fatmcgav** [comment]
No worries, cheers for the assist.

Gav

**Pull request merged**
