### PR TITLE
New Provider: SoftLayer

### PR DESCRIPTION
**Pull request by danielcbright**
### This PR will add a new cloud provider to the Terraform mix - [IBM's SoftLayer](http://www.softlayer.com/)

I'm starting this PR with support for `virtual_guest` and `ssh_key` resources, these resources are complete enough for most basic needs when spinning up a virtual_guest on SoftLayer. After this PR is accepted we will be creating PR's for even more significant updates not only to `virtual_guest` and `ssh_key` but support for `dns_domain`, `dns_domain_resource` and `network_application_delivery_controller` *(Netscaler VPX)* resources.

- [x] ~~Depends on https://github.com/maximilien/softlayer-go/pull/81 being accepted and merged.~~
- [x] ~~Depends on https://github.com/maximilien/softlayer-go/pull/85 being accepted and merged.~~
- [x] ~~Complete Resource Documentation for Website~~
- [ ] Gather input from Hashicorp and the community
- [ ] Fix any issues/bugs that are brought up

## Using the provider

Here is an example that will setup the following:
+ An SSH key resource.
+ A virtual server resource that uses an existing SSH key.
+ A virtual server resource using an existing SSH key and a Terraform managed SSH key (created as "test_key_1" in the example below).

(create this as sl.tf and run terraform commands from this directory):
```hcl
provider "softlayer" {
    username = ""
    api_key = ""
}

# This will create a new SSH key that will show up under the \
# Devices>Manage>SSH Keys in the SoftLayer console.
resource "softlayer_ssh_key" "test_key_1" {
    name = "test_key_1"
    public_key = "${file(\"~/.ssh/id_rsa_test_key_1.pub\")}"
    # Windows Example:
    # public_key = "${file(\"C:\ssh\keys\path\id_rsa_test_key_1.pub\")}"
}

# Virtual Server created with existing SSH Key already in SoftLayer \
# inventory and not created using this Terraform template.
resource "softlayer_virtual_guest" "my_server_1" {
    name = "my_server_1"
    domain = "example.com"
    ssh_keys = ["123456"]
    image = "DEBIAN_7_64"
    region = "ams01"
    public_network_speed = 10
    cpu = 1
    ram = 1024
}

# Virtual Server created with a mix of previously existing and \
# Terraform created/managed resources.
resource "softlayer_virtual_guest" "my_server_2" {
    name = "my_server_2"
    domain = "example.com"
    ssh_keys = ["123456", "${softlayer_ssh_key.test_key_1.id}"]
    image = "CENTOS_6_64"
    region = "ams01"
    public_network_speed = 10
    cpu = 1
    ram = 1024
}
```

You'll need to provide your SoftLayer username and API key,
so that Terraform can connect. If you don't want to put
credentials in your configuration file, you can leave them
out:

```
provider "softlayer" {}
```

...and instead set these environment variables:

- **SOFTLAYER_USERNAME**: Your SoftLayer username
- **SOFTLAYER_API_KEY**: Your API key

### CODE REVIEW

**Comment by jen20** [comment]
Hi @danielcbright! Thanks for submitting this PR - it would be great to have Softlayer support! At the moment it looks like Travis isn't particularly happy though - could you take a look? Thanks

**Comment by danielcbright** [comment]
Thanks @jen20! Travis should be happy after https://github.com/maximilien/softlayer-go/pull/81 is accepted and merged, we have a few other things we will be working on as well before this is ready to be pulled in (see checklist). I'm just happy to get this PR started so discussions can be had.

**Comment by edude03** [comment]
Just wanted to say I've been using this PR since it was created and the Softlayer support has been working great! Let me know if there is anything I can do to help this PR get merged faster so I can stop using 3 versions of terraform (custom w/ this PR, custom w/ the NAT gateway PR, and 0.6.9)

**Comment by danielcbright** [comment]
Hi @edude03, currently this is stalled as bugs are being worked out on softlayer-go (PR: herehttps://github.com/maximilien/softlayer-go/pull/85). As soon as that's pulled into master, the tests for this PR should start passing and I can start addressing bugs etc.. and move towards getting it pulled in. Glad to see it's working for you!

**Comment by jkbbwr** [comment]
Just as a question, having seen that maximilien/softlayer-go#85 has been merged where is the progress on this pull request? My company is deciding if its worth waiting for this to complete or if we should try and roll a simple solution ourselves.

**Comment by edude03** [comment]
Another option is compiling your own version, it's fairly straightforward
once you have a working go dev environment.

**Comment by jkbbwr** [comment]
That is an option but an official release date might also be nice.

**Comment by danielcbright** [comment]
@jkbbwr 

>Just as a question, having seen that maximilien/softlayer-go#85 has been merged where is the progress on this pull request? My company is deciding if it's worth waiting for this to complete or if we should try and roll a simple solution ourselves.

PR 85 hasn't been merged, but the previous PR 84 has been, it is live in the develop branch of softlayer-go (https://github.com/maximilien/softlayer-go/tree/develop). Perhaps commenting in the PR for softlayer-go of your success in using the provider will help get it merged into master faster.

:beers:

**Comment by eirslett** [comment]
@jkbbwr You could try using [this plugin](https://github.com/finn-no/terraform-provider-softlayer), which is basically an early version of this softlayer provider.

**Comment by danielcbright** [comment]
Hi @jen20 looks like we're passing Travis' checks now, would definitely like some feedback, especially wanted to make sure I imported the softlayer-go into the ```/vendors``` tree properly or if I missed something. Thanks!

**Comment by ckelner** [comment]
Would love a status update from the HC side :+1: thanks!

**Comment by jen20** [comment]
Hi @danielcbright and @ckelner! Looking over this it definitely seems to be in better shape now! Does anyone involved have any objections to me rebasing and squashing the commits here? We need to get a softlayer account set up for running acceptance tests as part of our nightly build - I'll start the process of that now.

**Comment by ckelner** [comment]
Hey @jen20 -- I have no objections!  Thank you for looking! :fireworks:

**Comment by danielcbright** [comment]
Thanks @jen20 sounds great to me!

**Comment by danielcbright** [comment]
@jen20 I'm going to go ahead and rebase/squash the commits, how are things coming on your side?

**Comment by danielcbright** [comment]
Hi @jen20 just wanted to check-in and see if there is anything I can do to get this moving on my side.

🍻

**Comment by eirslett** [comment]
@danielcbright Do you currently run a Terraform in-house fork? (In FINN.no we still use the independent terraform plugin that this PR is based on, which can be released whenever we need to)

Releasing it as a separate project might be a possible solution if the PR isn't merged :wink:

**Comment by jen20** [comment]
Hi @danielcbright! I've just given the code for this a quick initial review, and it looks good to merge to me. I haven't managed to yet run the tests as we have no internal SoftLayer account. I'll aim to get that sorted out this week and have this merged for v0.6.16 of Terraform! Thanks for your work on this!

**Comment by danielcbright** [comment]
Thanks @jen20 that's great to hear!, please let me know if you need any help getting a Softlayer account sorted for testing purposes.

**Comment by jen20** [comment]
This is merged - it was rebased so the commit IDs changed however. Thanks for the work @danielcbright!

**Pull request closed without merging**
