### PR TITLE
Add `aws_ami_ids` and `aws_ebs_snapshot_ids` resources

### LINKED ISSUE #12081: [Feature Request] data "aws_ami" - add "allow_empty" flag
Currently I must match at least one result if I use the "aws_ami" data source. 

I would like to implement an A/B lookup of AMI values using the aws_ami data source.
For example, AMI set "A" includes testing AMIs that match a particular environment,
and AMI set "B" includes production AMIs that match all environments.

I would like to be able to select from `coalesce(A, B)`, but to do this today means I must structure my image tags for both AMI lookups to return one result each, and dynamically decide

`A != "known-default" ? A : B`  

### Actual Behavior
Null set results in a terraform error and `plan` phase halts.

### Desired Behavior
Null set results in a terraform error only if requested flag `allow_empty` is false.

### PR DESCRIPTION
**Pull request by joshuaspence**
Fixes #12081. Adds new `aws_ami_ids` and `aws_ebs_snapshot_ids` resources.

### CODE REVIEW

**Comment by joshuaspence** [comment]
One thing that I wasn't sure of is whether the `ids` output should be sorted in any particular way. For example, it wasn't completely clear to me how you would uses the resources to obtain the most-recent EBS snapshot, whilst also allowing for the snapshot to not exist. I was thinking that if we sort the output `ids` by age then you could do something like this (I'm not sure how Terraform handles accessing an index of an array that doesn't exist, I'm assuming that it returns some sort of null value here):

```hcl
data "aws_ebs_snapshot_ids" "test" {
  # filter { ... }
}

resource "aws_ebs_volume" "test" {
  availability_zone = "us-west-2a"
  size              = 40
  snapshot_id       = "${data.aws_ebs_snapshot_ids.test.ids[0]}"
}
```

**Comment by joshuaspence** [comment]
```
> make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccDataSourceAws\(Ami\|EbsSnapshot\)Ids' 
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/04/21 21:48:34 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccDataSourceAws\(Ami\|EbsSnapshot\)Ids -timeout 120m
=== RUN   TestAccDataSourceAwsAmiIds_basic
--- PASS: TestAccDataSourceAwsAmiIds_basic (89.93s)
=== RUN   TestAccDataSourceAwsAmiIds_empty
--- PASS: TestAccDataSourceAwsAmiIds_empty (68.24s)
=== RUN   TestAccDataSourceAwsEbsSnapshotIds_basic
--- PASS: TestAccDataSourceAwsEbsSnapshotIds_basic (95.20s)
=== RUN   TestAccDataSourceAwsEbsSnapshotIds_empty
--- PASS: TestAccDataSourceAwsEbsSnapshotIds_empty (43.34s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	296.724s
```

**Comment by joshuaspence** [comment]
One other issue is that there is a fair bit of code duplication between the existing `aws_ami` and `aws_ebs_snapshot` resources and the `aws_ami_ids` and `aws_ebs_snapshot` resources and I'm not sure how best to consolidate the shared code.

**Comment by stack72** [comment]
This LGTM! Thanks for this @joshuaspence :) I am presuming those now closes #12081 ?

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccDataSourceAws\(Ami\|EbsSnapshot\)Ids'              ✭
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/04/21 16:33:43 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccDataSourceAws\(Ami\|EbsSnapshot\)Ids -timeout 120m
=== RUN   TestAccDataSourceAwsAmiIds_basic
--- PASS: TestAccDataSourceAwsAmiIds_basic (36.55s)
=== RUN   TestAccDataSourceAwsAmiIds_empty
--- PASS: TestAccDataSourceAwsAmiIds_empty (26.25s)
=== RUN   TestAccDataSourceAwsEbsSnapshotIds_basic
--- PASS: TestAccDataSourceAwsEbsSnapshotIds_basic (61.11s)
=== RUN   TestAccDataSourceAwsEbsSnapshotIds_empty
--- PASS: TestAccDataSourceAwsEbsSnapshotIds_empty (22.90s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	146.842s
```

**Comment by tamsky** [comment]
Thanks very much for this @joshuaspence indeed!

**Pull request merged**
