### PR TITLE
[WIP] Terraformfile prototype

### PR DESCRIPTION
**Pull request by fatz**
This PR is a WIP feature for terraform. It adds a feature for overwriting sources in complex module setups.
Please review this request and let me know what you think

It enables developers to overwrite registry sources without touching the source entries in multiple modules. 

Example
```
Infrastructure -> Masters -> Instances
               -> Agents  -> Instances
```

If we want to test a change in instances we have to touch every module to point it to a branch or a local module. 

Instead the `Terraformfile` drops in where we could easily overwrite the Instance source
```json
{
  "dcos-terraform/instance/aws": {
    "source": "git::https://github.com/dcos-terraform/terraform-aws-instance.git?ref=remote-name-prefix"
  }
}
```

Still missing
- version matcher do have conditional matching on versions
- ~overwriting registry versions~

`Terraformfile` is not a must I'm open for other suggestions like env-vars or similar. But whatever will be the solution should be something we could easily generate in Integration tests with multiple overwrites

Version override are also possible. Even version matchers on a different registry module should work

```json
{
  "dcos-terraform/instance/aws": {
    "source": "fatz/instance/aws"
    "version" "0.0.1"
  }
}
```

### CODE REVIEW

**Comment by lorengordon** [comment]
Love this idea!

**Comment by apparentlymart** [comment]
Hi @fatz! Sorry for the delay in responding to you here.

Our focus is currently elsewhere (preparing for the v0.12.0 release) so I can't get into the details of this right now, but I just wanted to let you know that we're planning to switch focus over to dependency management (including both modules and providers) in the near future, which makes this proposal pretty timely.

We have some design sketches of a file _like_ this, though not exactly the same, and so to be completely transparent with you I expect we will not move forward with the exact format you've presented here (there are some other requirements motivating the design which I can share more about once we finish v0.12) but this PR does present an important _use-case_ we want to be sure to support: being able to temporarily override the location of a module in order to develop it concurrently with the root module or to test a branch as you said.

I'd you'd like to keep iterating on this as a prototype in the mean time then please do! I just wanted to let you know that there's a parallel work stream here in case that changes the way you'd prefer to engage with this. I'll share some more details one we have an opportunity to write out a full proposal, to see if what we have with meets the needs you had in mind.

Thanks for working on this, and sorry I can't share full details of the planned future work right now; we usually prepare this sort of documentation as part of early release planning, which will happen only once the current release is complete.

**Comment by fatz** [comment]
Hi @apparentlymart thanks a lot for letting us know. We really look forward to the new official feature as we own a lot of nested modules where we need this feature for development and testing

In the meanwhile we will maintain this branch/PR for our use case.

If you'd like to hear any input on your new design once its finish let us know.

**Comment by mildwonkey** [comment]
Hello! I'm doing some PR cleanup and am going to close this WIP PR. If you'd like to continue working on this prototype of course feel free, though we suggest opening a Github issue (using the feature request template) so we can discuss the design and use cases together. Thanks!

**Pull request closed without merging**
