### PR TITLE
Fix azurerm_virtual_machine_scale_sets

### PR DESCRIPTION
**Pull request by rrudduck**
This PR attempts to fix a number of issues with the current azurerm_virtual_machine_scale_sets resource.

1) Fix issues related to using a custom image.
2) Fix issues related to the ip_configurations not being properly passed to the Azure api.
3) Support setting load_balancer_backend_address_pool_ids. There seems to be some issues with changes to this property after create not getting picked up for some reason, but on create this works correctly now.
4) Add support for the overprovision property.

I've run though various tests using my Azure account and things seem to work correctly. Any feedback is appreciated!

Thanks.

### CODE REVIEW

**Comment by stack72** [comment]
Hi @rrudduck 

Thanks for the work here - I would love to see a couple of acceptance tests added to show that this all works as expected :)

We will also need to update the relevant documentation for this

Thanks

Paul

**Comment by rrudduck** [comment]
Sure, I can take care of that.

**Comment by stack72** [comment]
You Rock!

**Comment by moritzheiber** [comment]
#11400 is related to this

**Comment by moritzheiber** [comment]
@rrudduck You probably want to update the documentation as well, mentioning that you have to specify either `vhd_containers` or `image` (and how they relate to each other)

**Comment by rrudduck** [comment]
Docs updated and tests for the lb and overprovision changes are done. I didn't create a test for the image related changes as it requires a custom image to be available in the storage account before creating the scale set. I didn't see a good way to do that given how the tests run.

**Comment by retheshnair** [comment]
@rrudduck . I was using packer to create the custom image post the storage account creation

**Comment by stack72** [comment]
Hi @rrudduck 

Thanks for the work here - this LGTM! I have just been able to run the tests on our CI server :)

Paul

**Pull request merged**
