### PR TITLE
Feature/allow multiple imports at the same time

### PR DESCRIPTION
**Pull request by ankon**
Allow to provide multiple 'ADDR ID' pairs to be passed to `terraform import`

This seems to be needed, as at least in my work today I was unable to run `terraform import`
in succession and get it to actually import resources into a Terraform Cloud state: It would
always start out from the last refreshed/applied state.

In any case though: This looks like a trivial enough extension.

## Target Release

1.5.x

### ENHANCEMENTS

 

-  `terraform import` now allows to specify multiple pairs of "address" and "identifier" to import multiple resources at the same time

### CODE REVIEW

**Comment by crw** [comment]
Thanks for this submission! I put it on the queue to be triaged.

**Comment by crw** [comment]
Apologies for the very late reply on this, @ankon. Have you seen the [import block](https://developer.hashicorp.com/terraform/language/import) feature? Does it meet your needs? If so, can we close this PR? Thanks!

**Comment by ankon** [comment]
We're indeed quite happy with the import blocks, and haven't done CLI-based imports since then. Not sure whether these are completely equivalent, but from my side would be ok to close this PR and point to them instead as the better practice.

**Comment by crw** [comment]
Thanks!

**Pull request closed without merging**
