### PR TITLE
Remove sthulb/mime/multipart

### PR DESCRIPTION
**Pull request by sthulb**
This dep was meant as a stopgap for a patch in the stdlib of Go which I
wrote.

The patch was released in Go 1.7. We can now remove my fork and go back
to the stdlib

### CODE REVIEW

**Comment by sthulb** [comment]
I consider this done :)

**Comment by jen20** [comment]
Hi @sthulb! Thanks for circling back around to this. I'll run the acceptance testing now with this patch and merge pending the results of that.

**Comment by jen20** [comment]
LGTM! Thanks @sthulb!

```
› make testacc TEST=./builtin/providers/template
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/11/06 10:24:09 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/template -v  -timeout 120m
=== RUN   TestRender
--- PASS: TestRender (0.09s)
=== RUN   TestTemplateRendering
--- PASS: TestTemplateRendering (0.13s)
=== RUN   TestValidateTemplateAttribute
--- PASS: TestValidateTemplateAttribute (0.00s)
=== RUN   TestValidateVarsAttribute
--- PASS: TestValidateVarsAttribute (0.00s)
=== RUN   TestTemplateSharedMemoryRace
--- PASS: TestTemplateSharedMemoryRace (0.00s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/template	0.240s
```

**Comment by sthulb** [comment]
Awesome. Thanks @jen20!

**Comment by sthulb** [comment]
@jen20 Anything to stop people being inflicted to my code :)

**Pull request merged**
