### PR TITLE
Add DigitalOcean SSH Key resource

### PR DESCRIPTION
**Pull request by plalloni**
Adds complete support for managing ssh keys in DO.

This PR depends on DO client's [PR#6](https://github.com/pearkes/digitalocean/pull/6) to be accepted.

### CODE REVIEW

**Comment by ebergonzi** [comment]
+1

**Comment by pearkes** [comment]
Made some comments over on https://github.com/pearkes/digitalocean/pull/6, but overall looks perfect!

**Comment by pearkes** [comment]
Re-running the job on Travis and will get this merged if it passes now that pearkes/digitalocean#6 is in!

**Comment by pearkes** [comment]
I'll write out some docs for this on master and cc you. Thanks again!

**Pull request merged**
