### PR TITLE
Fix precedence

### PR DESCRIPTION
**Pull request by PayscaleNateW**
@stack72 Here is a more complete fix for cache behavior precedence, based heavily on what @radeksimko did. Tests pass (I think, though running one more time just to be sure).

Addresses: #7253 
Relates to: #7395 #9167

Precedence is vitally important for most real world uses of cloudfront. For example, if you want to run wordpress through cloudfront, you typically need certain rules for `/<blog-name>/wp-admin*` that come before `/blog-name*`. Otherwise, the wordpress admin tool will not work.

For us, Terraform is pretty much unusable for cloudfront without precedence.

Therefore, would really like to get this merged in! Thanks!

### CODE REVIEW

**Comment by radeksimko** [comment]
Just FYI: Keep in mind that none of the CloudFront-specific bugfixes will _actually_ fix the currently broken behaviour until a core/schema bug is addressed: https://github.com/hashicorp/terraform/pull/7485

So _at the moment_ merging any of https://github.com/hashicorp/terraform/pull/7395 https://github.com/hashicorp/terraform/pull/9167 or this PR would actually break it even more - since nested sets don't seem to suffer from the schema bug as much as nested lists.

**Comment by PayscaleNateW** [comment]
Ah I was hoping that that bug had somehow been fixed... because I now see that it's working for me

**Comment by PayscaleNateW** [comment]
I just checked again - forwarded values, the main culprit of "set nested inside a list", seems to work fine. However, the checks failed due to the stochastic nature of iterating through maps. Going to use your fix of iterating through in the same order every time.

**Comment by PayscaleNateW** [comment]
All acceptance tests pass. My individual testing hasn't shown anything wrong either, so I don't think that nested sets thing is an issue any more. Forwarded values, for whatever reason, are working completely fine.

Also parallelized the acceptance tests, as they were taking forever to run and timing out after 2 hours. I updated the documentation to describe this precedence.

I really think we should merge this in.

**Comment by PayscaleNateW** [comment]
@radeksimko could you provide a test case where you think the nested sets issue will cause problems?

@stack72 Any word on what it would take to get this merged in? We'd really like to stop using a forked version of terraform on our team.

**Comment by apparentlymart** [comment]
Hello @PayscaleNateW, and thanks for working on this!

As part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it.

If you or someone else has the time and motivation to apply same changes to [the `aws` provider repository](https://github.com/terraform-providers/terraform-provider-aws) and open a new PR there, the maintainers of that provider should be able to review and merge it.

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Comment by PayscaleNateW** [comment]
Hey @apparentlymart - thanks for the response! No problem - I had noticed this PR was getting a bit cobwebby. Luckily, it appears that this PR in the new project picks up the slack: https://github.com/terraform-providers/terraform-provider-aws/pull/1269

Hopefully that PR gets merged in soon. That will enable us to update our org to use the latest version of terraform. We have been using my forked version since last year :)

**Pull request closed without merging**
