### PR TITLE
Bump aws-sdk-go from 1.44.122 to 1.44.298

### LINKED ISSUE #32448: error configuring S3 Backend: no valid credential sources for S3 Backend found.
### Terraform Version

```shell
1.3.6
```

### AWS CLI Version

```shell
aws-cli/2.9.12 Python/3.11.1 Darwin/22.2.0 source/arm64 prompt/off
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.30.0"
    }
  }
  backend "s3" {
    bucket         = "terraform-state-int"
    key            = "key/"
    region         = aws-region
    profile = "int"
  }
  required_version = ">= 1.1.0"
}
```

### Debug Output

No relevant debug output except the few lines below (Actual Behaviour)

### Expected Behavior

Should have applied initial config and download plugins

### Actual Behavior

Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
│ 
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│ 
│ Error: SSOProviderInvalidToken: the SSO session has expired or is invalid
│ caused by: open /Users/rsharma/.aws/sso/cache/9ceab8b92e009ecc15fdc2be3fe58963c97c5870.json: no such file or directory
│ 

### Steps to Reproduce

1. terraform init

### Additional Context

I have set up and created aws sso profile. I can access aws s3 buckets using that profile ` aws s3 ls --profile PROFILE_NAME`. I can also see json files in .aws/sso/cache and .aws/cli/cache. However, with terraform init, it couldn't file the the particular session

### References

_No response_

### LINKED ISSUE #32465: AWS S3 state backend fails with AWS SSO new profile format
### Terraform Version

```shell
Terraform v1.3.7
on darwin_arm64
+ provider registry.terraform.io/datadog/datadog v3.19.1
+ provider registry.terraform.io/hashicorp/aws v3.75.2
+ provider registry.terraform.io/hashicorp/null v3.2.1
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = "~>1.0"

  required_providers {
    aws = {
      version = "~>3.0"
      source  = "hashicorp/aws"
    }
    null = {
      version = "~>3.0"
      source  = "hashicorp/null"
    }
    datadog = {
      source  = "DataDog/datadog"
      version = "~> 3.18"
    }
  }

  backend "s3" {
    region         = "eu-central-1"
    bucket         = "xxxx-bucket-xxxx"
    key            = "state-key"
    dynamodb_table = "lock-table"
    encrypt        = "true"
  }
}
```

### Debug Output

```
...
2023-01-05T17:27:57.944+0100 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2023-01-05T17:27:57.945+0100 [INFO]  CLI command args: []string{"apply"}
2023-01-05T17:27:57.954+0100 [TRACE] Meta.Backend: built configuration for "s3" backend with hash value 3591387704
2023-01-05T17:27:57.955+0100 [TRACE] Preserving existing state lineage "8e30792b-97ac-5674-d17a-955b1985e845"
2023-01-05T17:27:57.955+0100 [TRACE] Preserving existing state lineage "8e30792b-97ac-5674-d17a-955b1985e845"
2023-01-05T17:27:57.956+0100 [TRACE] Meta.Backend: working directory was previously initialized for "s3" backend
2023-01-05T17:27:57.956+0100 [TRACE] Meta.Backend: using already-initialized, unchanged "s3" backend configuration
2023-01-05T17:27:57.959+0100 [INFO]  Attempting to use session-derived credentials
╷
│ Error: error configuring S3 Backend: Error creating AWS session: profile "xxx" is configured to use SSO but is missing required configuration: sso_region, sso_start_url
│ 
│ 
╵
```

### Expected Behavior

Terraform should work with the new AWS config format

### Actual Behavior

Terraform throws error with the new AWS config format

### Steps to Reproduce

1. Configure S3 remote state backend (including creating the bucket, making sure your AWS permissions are sufficient, etc.)
2. Configure your AWS client to use AWS IAM Identity Center (SSO) new format. Example ~/.aws/config entry:
```
[profile xxx]
sso_session = my-sso
sso_account_id = 111122223333
sso_role_name = SampleRole

[sso-session my-sso]
sso_region = us-east-1
sso_start_url = https://my-sso-portal.awsapps.com/start
sso_registration_scopes = sso:account:access
```
> reference: see [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html)
3. Login with `AWS_PROFILE=xxx aws sso login`
4. confirm that your bucket is accessible (e.g. `AWS_PROFILE=xxx AWS_REGION=yyy aws s3 ls <your-bucket-name>`)
5. Run e.g. `terraform init`, and receive the error message above.

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by johnnywalker**
Upgrade aws-sdk-go to v1.44.298, which enables support for Identity Center/SSO.

Ref: https://github.com/aws/aws-sdk-go/releases/tag/v1.44.298

Fixes #32448
Fixes #32465

## Target Release

1.5.x

## Draft CHANGELOG entry

Bump aws-sdk-go from 1.44.122 to 1.44.298 (support SSO in AWS backend)

### BUG FIXES

When using the `aws` backend, Terraform no longer throws:

```
╷
│ Error: error configuring S3 Backend: Error creating AWS session: profile "xxx" is configured to use SSO but is missing required configuration: sso_region, sso_start_url
│ 
│ 
╵
```

### CODE REVIEW

**Comment by crw** [comment]
Thanks for this submission! I'll raise it in triage.

**Comment by johnnywalker** [comment]
Very welcome! Thanks for taking a look.

**Comment by crw** [comment]
As this library is only used by this backend, it has been referred to the AWS Provider team for review. Thanks!

**Comment by johnnywalker** [comment]
@crw Sorry for the confusion, but my PR should have targeted `v1.5` instead of `main`. I've updated the base and fork accordingly.

**Comment by crw** [comment]
@johnnywalker have you seen this PR / thread as well? I think we can probably close this PR as the work will be done in stages by the provider team - what do you think?

https://github.com/hashicorp/terraform/pull/33469#issuecomment-1626158408

**Comment by johnnywalker** [comment]
@crw Yes sir I took a look at that but wasn't sure about the timeline. In particular, that comment mentions rolling out the change with several releases, so I assume it's a bit more protracted.

This PR effectively backports SSO support for the S3 backend to `v1.5` and can be used immediately. I'm running it locally and thoroughly enjoying the SSO support! If others agree, I think it would be very helpful to merge this to `v1.5` in the interim.

**Comment by crw** [comment]
Interesting. It may be problematic merging only to 1.5 - if the other change isn't baked by the time 1.6 rolls out, then this feature would regress. In any case, I will leave this PR open for the AWS provider team to review as they have time.

**Comment by michailw** [comment]
Just leaving the note - the AWS provider team merged the same bump on the AWS provider side and released it with the 5.8.0 version of the AWS provider.

https://github.com/hashicorp/terraform-provider-aws/issues/28263
https://github.com/hashicorp/terraform-provider-aws/pull/32426/files

**Review by michailw — APPROVED** [review]

**Comment by crw** [comment]
@johnnywalker Just a heads-up, this would need to be merged to main (and then we would backport it to 1.5). I need to check with @tombuildsstuff to see if we can merge this without getting in the way of what he has planned - I'll follow up on that and get back to you.

**Comment by crw** [comment]
@johnnywalker Confirmed that this can be merged without impacting the upgrade to 2.x, so when you get a chance please re-target to `main` and I can get this reviewed and merged. Thanks!

**Comment by crw** [comment]
Thanks! We can move the further discussion there.

**Comment by johnnywalker** [comment]
@crw @jBouyoud Sorry for the late response. I'll continue discussion on #33607 , but I initially applied these changes to `main` and ran into problems using the updated version locally. Perhaps this has been resolved already, but I assumed `main` included work-in-progress for migrating to `aws-sdk-go-v2`. In particular, there are quite a few `aws-sdk-go-v2` dependencies listed in `go.sum` now, and these originated in https://github.com/hashicorp/terraform/commit/9f6a3ba70151106634fb8305a19166f74aed06db#diff-3295df7234525439d778f1b282d146a4f1ff6b415248aaac074e8042d9f42d63.

**Pull request closed without merging**
