### PR TITLE
New provider arukas

### PR DESCRIPTION
**Pull request by yamamoto-febc**
This PR adds a provider for the [Arukas](https://arukas.io/en/).

Arukas is a Docker hosting service and is explained on the official website as follows.

> Arukas is the simplest-to-use Container-as-a-service that makes it easy to deploy and manage apps at scale.

One can manage the container on arukas like this:
```hcl
provider "arukas" {
    token = "[put_your_api_token]"
    secret = "[put_your_api_secret]"
}

resource "arukas_container" "foobar" {
    name = "terraform_for_arukas_test_foobar"
    image = "nginx:latest"
    instances = 1
    memory = 256
    ports = {
        protocol = "tcp"
        number = "80"
    }
    environments {
        key = "key1"
        value = "value1"
    }
}
```

The PR includes tests & documentation.

Test output :
```sh
TF_ACC=1 go test ./builtin/providers/arukas -v  -timeout 120m
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccArukasContainer_Basic
--- PASS: TestAccArukasContainer_Basic (80.82s)
=== RUN   TestAccArukasContainer_Update
--- PASS: TestAccArukasContainer_Update (164.25s)
=== RUN   TestAccArukasContainer_Minimum
--- PASS: TestAccArukasContainer_Minimum (79.97s)
=== RUN   TestAccArukasContainer_Import
--- PASS: TestAccArukasContainer_Import (69.71s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/arukas	394.961s
```

Looking forward to your feedback!

### CODE REVIEW

**Comment by stack72** [comment]
Hi @yamamoto-febc 

Thanks for the work here - this provider LGTM! There is a merge conflict on the vendor.json file (since we merged another provider) - please can you resolve that and then the code is mergeable.

I have requested an account on arukas.io - hopefully that will come through soon and I can run all the tests to make sure that they work as expected

Thanks for the work here

Paul

**Comment by yamamoto-febc** [comment]
@stack72 Thanks for the review, and welcome to arukas.io!  
I resolved conflicts so please review again.  

Thanks!

**Comment by stack72** [comment]
thanks for the changes @yamamoto-febc :) This LGTM! Just waiting to get my account on the provider for Terraform so we can run the acceptance tests

thanks

Paul

**Comment by yamamoto-febc** [comment]
There was a merge conflict on the vendor.json file , so I resolved that.

**Comment by stack72** [comment]
Hi @yamamoto-febc 

Thanks for waiting here - this LGTM!

```
% make testacc TEST=./builtin/providers/arukas                                                                                               ✭
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/01/09 17:08:13 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/arukas -v  -timeout 120m
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccArukasContainer_Basic
--- PASS: TestAccArukasContainer_Basic (88.30s)
=== RUN   TestAccArukasContainer_Update
--- PASS: TestAccArukasContainer_Update (98.31s)
=== RUN   TestAccArukasContainer_Minimum
--- PASS: TestAccArukasContainer_Minimum (74.70s)
=== RUN   TestAccArukasContainer_Import
--- PASS: TestAccArukasContainer_Import (28.64s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/arukas	289.960s
```

Paul

**Comment by jbardin** [comment]
@stack72,

This broke the windows build.
Looks like the dependency `gopkg.in/alecthomas/kingpin.v2` isn't compatible with windows.

**Comment by yamamoto-febc** [comment]
@stack72,
I found the cause of the broken build on Windows and I fixed it and created a pull request(#11140).
Please review and merge that:pray:

Yamamoto

**Pull request merged**
