### PR TITLE
Allow multiple instances in AWS ALB target group attachment

### PR DESCRIPTION
**Pull request by fredsted**
In #9986 @optimisticanshul made a PR that allows you to do this:

```
resource "aws_instance" "test" {
  count = 1
  // ...
}

resource "aws_instance" "demo" {
  count = 1
  // ...
}

resource "aws_alb_target_group_attachment" "test" {
  target_group_arn = "${aws_alb_target_group.test.arn}"
  targets {
   target_id = "${aws_instance.test.id}"
   port = 80
  }
  targets {
   target_id = "${aws_instance.demo.id}"
   port = 8080
  }
}
```

However, if you're using instances with the `count` property, this is not ideal. I made a few small changes so instances with the `count` property can be added to an ALB attachment. I also renamed `targets` to `instances`, to keep in line with the similar `aws_elb` resource.

This PR allows you to do this:

```
resource "aws_instance" "backend" {
  count = 2
  // ...
}

resource "aws_alb_target_group_attachment" "test" {
  target_group_arn = "${aws_alb_target_group.test.arn}"
  instances        = ["${aws_instance.backend.*.id}"]
  port             = 80
}
```

### CODE REVIEW

**Comment by dohoangkhiem** [comment]
I tried with Terraform binary built with this PR, it works well when applying terraform configuration, allowing creating target group with multiple instances.

However after creating the resource, checking with `terraform plan` will always show that the `aws_alb_target_group_attachment` resource should be created (while it's actually already created).  Something might be wrong for its state?

**Comment by fredsted** [comment]
@dohoangkhiem Thanks for the comment. I've been trying to fix that bug, but no luck so far. 😕

**Comment by dohoangkhiem** [comment]
@fredsted adding `ForceNew: true` to `instances` helped me fix that bug
```
"instances": &schema.Schema{
	Type:     schema.TypeSet,
	Elem:     &schema.Schema{Type: schema.TypeString},
	ForceNew: true,
	Optional: true,
	Computed: true,
	Set:      schema.HashString,
},
```

**Comment by fredsted** [comment]
@dohoangkhiem Thanks! I tried adding the line and recompiling Terraform, but Terraform still wants to create new attachments when I generate a plan. Do I have to do anything else?

**Comment by dohoangkhiem** [comment]
@fredsted it works for me on my own branch - without anything changes when I check with the plan it does not create new attachment anymore, I just added that `ForceNew: true`.

One note: I rebased your branch with the v0.9.8 before compiling. Maybe you can try.

**Comment by korotovsky** [comment]
Any updates here?

**Comment by fredsted** [comment]
@korotovsky Not really – it would be awesome to hear from someone from the terraform project so I can decide whether I should keep working on this.

**Comment by korotovsky** [comment]
@fredsted I faced an issue with that and would be nice to get it merged :)

**Comment by apparentlymart** [comment]
Hello @fredsted, and thanks for working on this!

As part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it.

If you or someone else has the time and motivation to apply same changes to [the `aws` provider repository](https://github.com/terraform-providers/terraform-provider-aws) and open a new PR there, the maintainers of that provider should be able to give feedback and review.

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Pull request closed without merging**
