### PR TITLE
Swift remote backend support for workspaces & locking

### PR DESCRIPTION
**Pull request by yanndegat**
superseeds #18431,#18378

### CODE REVIEW

**Comment by jbardin** [comment]
Hi @yanndegat,

We're nearing completion of the core 0.12 work, and I'd like to evaluate this for inclusion in the dev builds before the 0.12 release.

Can you run acceptance tests on this, and add the test statuses n a comment here?

Thanks!

**Comment by yanndegat** [comment]
hi @jbardin 

of course, something like a pastebin of the standard output?

**Comment by yanndegat** [comment]
@jbardin 
``
$ env GO111MODULE=on make testacc TEST=./backend/remote-state/swift/ > testacc.out 2> testacc.err
$ echo $?
0
$ === RUN   TestBackend_impl
--- PASS: TestBackend_impl (0.00s)
=== RUN   TestBackendConfig
--- PASS: TestBackendConfig (0.44s)
=== RUN   TestBackend
--- PASS: TestBackend (106.18s)
=== RUN   TestBackendArchive
--- PASS: TestBackendArchive (51.52s)
=== RUN   TestRemoteClient_impl
--- PASS: TestRemoteClient_impl (0.00s)
=== RUN   TestRemoteClient
--- PASS: TestRemoteClient (8.60s)
$ tail testacc.out
2019/02/25 10:17:25 [DEBUG] Deleting object terraform-state-swift-testclient-5c73b29d/tfstate.tf
2019/02/25 10:17:25 [DEBUG] Getting object terraform-state-swift-testclient-5c73b29d/tfstate.tf
2019/02/25 10:17:25 [DEBUG] Object doesn't exist to download.
2019/02/25 10:17:25 [DEBUG] Deleting container terraform-state-swift-testclient-5c73b29d
2019/02/25 10:17:25 [DEBUG] Deleting container terraform-state-swift-testclient-5c73b29d
--- PASS: TestRemoteClient (8.60s)
    backend_test.go:19: swift backend acceptance tests enabled
    client_test.go:21: TestBackendConfig on *swift.Backend with configs.synthBody{Filename:"<TestWrapConfig>", Values:map[string]cty.Value{"container":cty.StringVal("terraform-state-swift-testclient-5c73b29d")}}
PASS
ok      github.com/hashicorp/terraform/backend/remote-state/swift       166.763s
``

see [txt files](https://paste.fedoraproject.org/paste/T5bDSXI7DFu5WjBaFxfw7Q/)

**Comment by jbardin** [comment]
Thanks @yanndegat!

**Comment by sebastien-prudhomme** [comment]
@jbardin I start evaluating TF 0.12 beta1 by migrating an existing infrastructure and got this bug that seems related workspace implementation in this PR:

```
2019/03/08 13:26:54 [DEBUG] OpenStack Request URL: GET https://objet.oshimae.rie.agri:8080/swift/v1/infrastructures-auth-common/ctrl?delimiter=%2F&prefix=env-
2019/03/08 13:26:54 [DEBUG] OpenStack Request Headers:
Accept: text/plain
Content-Type: text/plain
User-Agent: Terraform/0.12.0 gophercloud/2.0.0
X-Auth-Token: ***
2019/03/08 13:26:57 [DEBUG] OpenStack Response Code: 200
2019/03/08 13:26:57 [DEBUG] OpenStack Response Headers:
Accept-Ranges: bytes
Content-Length: 0
Content-Type: binary/octet-stream
Date: Fri, 08 Mar 2019 12:26:57 GMT
Etag: d41d8cd98f00b204e9800998ecf8427e
Last-Modified: Fri, 08 Mar 2019 12:26:54 GMT
X-Timestamp: 1552048014.96344
X-Trans-Id: tx000000000000000185b58-005c825f8e-219fbce1-default
2019/03/08 13:26:57 [DEBUG] Not logging because OpenStack response body isn't JSON
Cannot extract names from response with content-type: [binary/octet-stream]
```

Can you confirm?

**Comment by yanndegat** [comment]
hi @sebastien-prudhomme 

thanks for reporting this.
acceptance tests are passing & i have a working env based on terraform 0.12_beta1

so it's going to be hard to reproduce without more information on your setup.
could you provide us with versions, logs from the swift service, etc ?

thanks a lot

**Comment by sebastien-prudhomme** [comment]
@yanndegat found the problem: i'm using "infrastructures-auth-common/ctrl" as container name, that is the openstack container name plus a path. That name is not compatible with the way the workspace search is done.

The prefix used should be prefixed by the path I use in my name and the path stripped from the container name:

https://objet.oshimae.rie.agri:8080/swift/v1/infrastructures-auth-common/ctrl?delimiter=%2F&prefix=env-

should be

https://objet.oshimae.rie.agri:8080/swift/v1/infrastructures-auth-common?delimiter=%2F&prefix=ctrl/env-

BTW, it's work fine with TF 0.11 but perhaps it should not. I also remember that i was using the obsolete "path" parameter in the swift backend in previous TF versions without any problems.

**Comment by kayrus** [comment]
@sebastien-prudhomme could you please try to compile my branch: https://github.com/kayrus/terraform/tree/swift-workspaces? The purpose of #20122 was to keep the backward compatibility.

**Comment by sebastien-prudhomme** [comment]
@kayrus sorry but i've switched all my infrastructures to "workspace" mode...

**Pull request merged**
