### PR TITLE
[WIP] provider/openstack - Add support for identity v3

### PR DESCRIPTION
**Pull request by sbourlon**
I just sent a PR to the gophercloud repository in order to improve the identity v3 support: https://github.com/rackspace/gophercloud/pull/593. While waiting for them to merge it, here is the code on the Terraform side. I am actually already using it for my Stackato Cloud Foundry cluster deployment automation tool (https://github.com/hpcloud/stackato-cluster-tool).

This PR adds the following keys:
- user_domain_name and user_domain_id identifying the domain where the user lives
- project_domain_name and project_domain_id for project scoping
- default_domain for shared domain when the domain scope and user scope are the same
- project_name and project_id which is the new naming for tenant since OpenStack cli 1.7.0

Before merging this PR, we would need to bump the Godeps gophercloud dependency after they merge https://github.com/rackspace/gophercloud/pull/593.

Please, let me know if I am missing something or if this PR needs to be improved.

### CODE REVIEW

**Comment by jtopjian** [comment]
@sbourlon Cool! Thank you for this. I've subscribed to https://github.com/rackspace/gophercloud/pull/593 and will also keep an eye on it.

As an aside, I'm awaiting https://github.com/rackspace/gophercloud/pull/528 which will help with #6458.

**Comment by sbourlon** [comment]
Thanks @jtopjian! The repo https://github.com/rackspace/gophercloud is moving to a new one https://github.com/gophercloud/gophercloud. I will have to test and move the gophercloud PR to this new repo.

**Comment by jtopjian** [comment]
:+1: 

I followed along the conversation today. The move go gophercloud/gophercloud was news to me, too. The Terraform OpenStack provider in general will have to move over to it... one step at a time, I guess :smile:

**Comment by sbourlon** [comment]
If needed, I joined the build of this PR to the latest release of my cluster tool: https://github.com/hpcloud/stackato-cluster-tool/releases/tag/v0.9.0

**Comment by dpmex4527** [comment]
Looking forward to seeing this PR go through :)

**Comment by sbourlon** [comment]
@dpmex4527 Meet too! However, we would need to have Terraform using the new gophercloud (https://github.com/rackspace/gophercloud/issues/592), then I will migrate https://github.com/rackspace/gophercloud/pull/593 to it.

**Comment by dpmex4527** [comment]
@sbourlon would you happen to have a gist or some instructions on how to build this PR for me to test? Would like to validate as we currently use Openstack V3 at work and would love to help test it out.

**Comment by dpmex4527** [comment]
@sbourlon looks like the new gophercloud repo is up and receiving PR's now (I see a few PR's and issues out there now). Hoping we can see V3 support in terraform soon :)

Also, someone already submitted a V3 related PR. Similar to yours? gophercloud/gophercloud/pull/13

**Comment by jtopjian** [comment]
Just a heads up: The Terraform OpenStack provider won't immediately be switching to the new `gophercloud/gophercloud` library. The new library has a good amount of changes from the original library.

I'm in the process of reviewing the code now, basically going through each acceptance test as a way of identifying breaking changes. I'm pretty sure any public-facing changes will just be a few call rewrites, but will take some time to confirm.

I do intend to switch over as soon as possible, though. :)

**Comment by fatmcgav** [comment]
@jtopjian What's the latest on this change and the switch to gophercloud/gophercloud? 

As I've just hit the same issue I believe where I can't scope Terraform auth to a specific project name :(

**Comment by jtopjian** [comment]
@fatmcgav Check out #7926 for the status of moving to `gophercloud/gophercloud`. :)

**Comment by fatmcgav** [comment]
@jtopjian Cool, cheers... I'll have a look...

**Pull request closed without merging**
