### PR TITLE
Google Container Cluster: support tags and metadata

### PR DESCRIPTION
**Pull request by ruzarowski**
We implemented support for tagging and adding metadata to kubernetes cluster nodes in google container engine. Tested and docs included.

### CODE REVIEW

**Comment by danawillow** [comment]
Thanks @ruzarowski! Can you add a test in resource_container_cluster_test that exercises this path? Feel free to copy and paste what I did in #12743 (I was already working on it by the time you sent out yours).

**Comment by k-kawa** [comment]
Super great hack @ruzarowski !
What is this PR status? I'm also very interested in this feature and would like to fix it if you're busy.

**Comment by danawillow** [comment]
FYI support for these have been added:
https://github.com/terraform-providers/terraform-provider-google/commit/834ecc493415bcb384434805f12786d1cce208df
https://github.com/terraform-providers/terraform-provider-google/pull/7

**Comment by apparentlymart** [comment]
Hello @ruzarowski, and thanks for working on this!

As part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it. It looks like in the meantime equivalent functionality was added in terraform-providers/terraform-provider-google#7.

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Pull request closed without merging**
