### PR TITLE
e2e test for `init -from-module`

### PR DESCRIPTION
**Pull request by jbardin**
Pull down the hashicorp/vault/aws module into the current directory with
init.

### CODE REVIEW

**Comment by jbardin** [comment]
Good idea! I thought we would just skip these on travis altogether.

**Comment by jbardin** [comment]
hmm, that doesn't work with a local git config. Maybe I can set the global config for the user in travis 🤔

**Comment by apparentlymart** [comment]
Until now we've only been depending on our own services for these tests, so I made it run these tests alone in Travis as a special case to help us catch certain errors sooner. Having an external service in the mix changes things a bit here but since it's github it seems reasonable to keep doing it if we can make it work -- our build _already_ depends on github, after all.

When I made that suggestion earlier I was thinking of it as an extra step to run in `.travis.yml` rather than as something in the code, though I'm not sure if we need to be careful where we do that so we don't break other git-related work that is done by both Travis itself and by our Makefile during the run.

**Comment by jbardin** [comment]
yeah, I don't really want it to chance effecting any other travis steps. Giving it another shot with GIT_CONFIG, since I forgot the dir where go-getter pulls won't be where the .git dir lives.

**Comment by jbardin** [comment]
nope, trying to force the global git config this time

**Comment by jbardin** [comment]
haha, found a combination that worked.
Had to set the global config, and specifically check for the `ssh://git@github.com/`

**Pull request merged**
