### PR TITLE
config/module: fix test failures on Windows

### PR DESCRIPTION
**Pull request by ceh**

### CODE REVIEW

**Comment by mitchellh** [comment]
This is _awesome_. My only nitpick is can you rename `util.go` to `url_helper.go` or something. I generally try to shy away from the blanket "util" which ends up being a repository of sadness.

**Comment by ceh** [comment]
@mitchellh Done. Thanks for the early review.

**Comment by mitchellh** [comment]
Coming in.

**Comment by mitchellh** [comment]
@ceh You got a tweet too: https://twitter.com/mitchellh/status/560201423808241666

**Comment by ceh** [comment]
@mitchellh That was fast. Cheers.

**Pull request merged**
