### PR TITLE
address conflict btw list-type attributes and ignore_changes

### LINKED ISSUE #9043: All `vpc_security_group_ids` being removed when updating instance Security Groups
When trying to modify AWS Security Groups on an already Terraformed EC2 instance, it seems to forget about all existing SGs (even though they appear in the statefile), and the `plan` output initially looks legit.

We originally found this issue, when trying to add a brand-new SG. Terraform removed all existing SGs (and caused some chaos!), but successfully added the new one. We've since reduced the problem down to just removing an existing SG, or somewhere parsing the existing SGs from the `vpc_security_group_ids` field.

In the following example:
- One EC2 instance called `ganglia-a`
- 4 existing Security Groups `AAAAAA`, `BBBBBB`, `CCCCCC`, & `DDDDDD`
- Trying to remove `BBBBBB`.
- Statefile shows the existing 4 SGs, (and all have their definitions too).
- Terraform plan shows the reduction in count from `4=>3`
- Terraform plan shows the SG being removed
- Terraform apply attempts to clear out all SGs. Only limited in this case by the AWS API complaining about lack of parameter payload.
### Terraform Version

`Terraform v0.7.4`
### Affected Resource(s)
- aws_instance
- vpc_security_group_ids
### Terraform Configuration Files

Existing Statefile showing existing 4 SGs:

``` json
                "aws_instance.ganglia-a": {
                    "type": "aws_instance",
                    "depends_on": [
                        "aws_security_group.CCCCCC",
                        "aws_security_group.DDDDDD",
                        "aws_security_group.AAAAAA",
                        "aws_subnet.blah-public",
                        "data.template_file.ganglia-cloudinit"
                    ],
                    "primary": {
                        "id": "i-INSTANCE-ID-HERE",
                        "attributes": {
                            "ami": "ami-AMI-ID",
                            "associate_public_ip_address": "false",
                            "availability_zone": "us-west-2a",
                            "disable_api_termination": "false",
                            "ebs_block_device.#": "0",
                            "ebs_optimized": "false",
                            "ephemeral_block_device.#": "0",
                            "iam_instance_profile": "",
                            "id": "i-INSTANCE-ID-HERE",
                            "instance_state": "running",
                            "instance_type": "m4.large",
                            "key_name": "dom",
                            "monitoring": "false",
                            "network_interface_id": "eni-xxxxxx",
                            "private_dns": "blah.compute.internal",
                            "private_ip": "SOME_IP",
                            "public_dns": "blah.compute.amazonaws.com",
                            "public_ip": "SOME_IP",
                            "root_block_device.#": "1",
                            "root_block_device.0.delete_on_termination": "true",
                            "root_block_device.0.iops": "192",
                            "root_block_device.0.volume_size": "64",
                            "root_block_device.0.volume_type": "gp2",
                            "security_groups.#": "0",
                            "source_dest_check": "true",
                            "subnet_id": "subnet-ID",
                            "tags.%": "2",
                            "tags.Cost Center": "Platform",
                            "tags.Name": "ganglia",
                            "tenancy": "default",
                            "user_data": "SOME_HASH_HERE",
                            "vpc_security_group_ids.#": "4",
                            "vpc_security_group_ids.1389827218": "sg-AAAAAA",
                            "vpc_security_group_ids.258711328": "sg-DDDDDD",
                            "vpc_security_group_ids.4034046821": "sg-CCCCCCC",
                            "vpc_security_group_ids.4249215419": "sg-BBBBBB"
                        },
                        "meta": {
                            "schema_version": "1"
                        },
                        "tainted": false
                    },
                    "deposed": [],
                    "provider": ""
                }
```

Existing Terraform file:

``` hcl
# ganglia
resource "aws_instance" "ganglia-a" {
  ami = "${var.ubuntu_ami_id}"
  availability_zone = "${var.vpc_region}a"
  instance_type = "m4.large"
  key_name = "dom"
  vpc_security_group_ids = ["${aws_security_group.AAAAAA.id}", "${aws_security_group.BBBBBB.id}", "${aws_security_group.CCCCCC.id}", "${aws_security_group.DDDDDD.id}" ]
  subnet_id = "${aws_subnet.blah-public.0.id}"
  user_data = "${data.template_file.SOMEDATA.rendered}"

  lifecycle {
    ignore_changes = ["user_data"]
  }

  root_block_device {
    volume_type = "gp2"
    volume_size = "${var.default_volume_size}"
  }

  provisioner "local-exec" {
    command = "../../../scripts/autosign ${var.foreman_proxy_url} ganglia-${replace(aws_instance.ganglia-a.id, "i-", "")}.${var.vpc_domain}"
  }

  tags {
    Name = "ganglia"
    "Cost Center" = "Platform"
  }
}
```

Actual change we're trying to apply (removal of `BBBBBB`)

``` diff
-  vpc_security_group_ids = ["${aws_security_group.AAAAAA.id}", "${aws_security_group.BBBBBB.id}", "${aws_security_group.CCCCCC.id}", "${aws_security_group.DDDDDD.id}"]
+  vpc_security_group_ids = ["${aws_security_group.AAAAAA.id}", "${aws_security_group.CCCCCC.id}", "${aws_security_group.DDDDDD.id}"]
```

Terraform Plan

```
~ aws_instance.ganglia-a
    vpc_security_group_ids.#:          "4" => "3"
    vpc_security_group_ids.4249215419: "sg-BBBBBB" => ""
```
### Debug Output
- Debug output shows the API call to Amazon, having an empty payload. It should have the remaining 3 SGs?
  https://gist.github.com/scottgeary/67a7584bffdeeb672425cf6d1092c5c9
### Expected Behavior
- A single SG `aws_security_group.BBBBBB` being removed
- Terraform plan usually shows elements to be kept.
### Actual Behavior
- Attempts to removes all SGs
- Causes AWS API error, about lack of parameters.
### Steps to Reproduce
1. `terraform plan`
2. `terraform apply`
### Important Factoids
- I've removed a lot of IDs from the various output.
- If we try adding a brand new SG, it removes all existing SGs, and leaves the new one as the _only_ one. (This is how we discovered the bug)
### References
- None that I could find that clear the existing SGs.

### PR DESCRIPTION
**Pull request by br0ch0n**
fixes #9043

### CODE REVIEW

**Comment by Jonnymcc** [comment]
This fixes the issue in #9043 but introduces another artifact. Not only does it fix my security groups but it also lists the ebs_block_device as changing even though it is not.

```
 ebs_block_device.#:                                "1" => "1"
    ebs_block_device.3133358816.delete_on_termination: "true" => "true"
    ebs_block_device.3133358816.device_name:           "xvdb" => "xvdb"
    ebs_block_device.3133358816.encrypted:             "true" => "true"
    ebs_block_device.3133358816.volume_size:           "50" => "50"
    ebs_block_device.3133358816.volume_type:           "gp2" => "gp2"
    vpc_security_group_ids.#:                          "2" => "3"
    vpc_security_group_ids.2422803500:                 "sg-7656d80b" => "sg-7656d80b"
    vpc_security_group_ids.408308980:                  "sg-f175848e" => "sg-f175848e"
    vpc_security_group_ids.988224174:                  "" => "sg-75a779d"
```

I noticed this while debugging...
`[INFO] atrrs Checking ebs_block_device.3133358816.iops, &{150  %!s(bool=true) %!s(bool=false) <nil> %!s(bool=false) %!s(bool=false) %!s(terraform.DiffAttrType=0)}, 150,`

Here is the debug code,
```
changingSiblings := make(map[string]bool)
	for k, v := range diff.CopyAttributes() {
		log.Printf("[INFO] atrrs Checking %s, %s, %s, %s", k, v, v.Old, v.New)
		if listTypeAttrKeys[strings.Split(k, ".")[0]] && v.Old != v.New {
			changingSiblings[strings.Split(k, ".")[0]] = true
		}
	}
```

My guess is that since I am not specifying a number of iops it is detecting it as a change from "150" => "". Setting the iops in my TF template to 150 actually makes the reported change disappear. Should find a solution that doesn't require settings iops though.

Also, I experienced this issue by spinning up instances referencing user_data resources and later removing those resources and setting lifecyle
`ignore_changes = ["user_data"]`

In the meantime while waiting for this fix my workaround is to revert the changed that removed the user_data resources, that way I can remove the lifecyle changes and, as expected, I do not have the issue adding security groups anymore.

**Comment by br0ch0n** [comment]
by chance did you see if it was going to (or did) actually change your block device?  Or was it purely screen spam?

**Comment by Jonnymcc** [comment]
With Terraform plan it shows as if it would modify the attribute. I did not test if it actually did.

**Comment by Jonnymcc** [comment]
It actually shows as the only change to other instances. Which leads me to believe that Terraform would always think there is a change to apply even when there is none.

**Comment by br0ch0n** [comment]
OK cool, thanks for testing!  I'll try and reproduce and see what I can do.

**Comment by josephholsten** [comment]
I wonder if this is necessary after #12897

**Comment by br0ch0n** [comment]
Yaa, I should close this since it's supposedly fixed. I haven't tested personally tho.

**Pull request closed without merging**
