### PR TITLE
provider/google: Limit hardcoded test resource names

### PR DESCRIPTION
**Pull request by lwander**
Fix tests that failed as a result of #4516 

@phinze, I got all tests to work locally after making changes that failed in the last Travis run, with the exception of [this one](https://travis-ci.org/hashicorp/terraform/jobs/100462877#L498), which I was never able to make fail in the first place. Maybe it was a transient error?

### CODE REVIEW

**Comment by phinze** [comment]
Nice, thanks for this.

The error you mentioned:

```
Error 503: Backend Error, backendError
```

Does indeed look like an upstream transient issue. If it's something we see regularly we can try to retry through them, but for now I think it's safe to ignore. :+1:

**Comment by phinze** [comment]
Fresh travis run:

https://travis-ci.org/hashicorp/terraform/builds/100511688

**Comment by lwander** [comment]
Looks like both failures were server side this time.

**Comment by phinze** [comment]
Nice - much better! :grinning: 

Capturing the failures here:

```
--- FAIL: TestAccGoogleStorageBucketAcl_upgrade
Error reading bucket tf-test-acl-bucket-5418736544792479648: Get https://www.googleapis.com/storage/v1/b/tf-test-acl-bucket-5418736544792479648?alt=json: oauth2: cannot fetch token: 504 Gateway Timeout
Response: {
  "error" : "internal_failure"
}--- FAIL: TestAccGoogleStorageBucketAcl_upgrade (64.91s)
	testing.go:148: Step 2 error: Error on follow-up refresh: 1 error(s) occurred:
		
		* google_storage_bucket.bucket: Get https://www.googleapis.com/storage/v1/b/tf-test-acl-bucket-5418736544792479648?alt=json: oauth2: cannot fetch token: 504 Gateway Timeout
		Response: {
		  "error" : "internal_failure"
		}
```

```
--- FAIL: TestAccAutoscaler_basic (136.78s)
	testing.go:148: Step 0 error: Error applying: 1 error(s) occurred:
		
		* google_compute_autoscaler.foobar: Error loading zone 'us-central1-a': googleapi: Error 503: Backend Error, backendError
```

And rekicking those two jobs.

**Comment by phinze** [comment]
@lwander it is a bit disconcerting how common these 500-class errors from upstream seem to be. Is there a good place for us to report these for further investigation?

**Comment by lwander** [comment]
@phinze, it is very concerning. Just ping me with them and I'll submit a bug internally.

**Comment by phinze** [comment]
Sounds good - emailed!

**Pull request merged**
