### PR TITLE
add functions to encode/decode base64 strings with specific encoding

### PR DESCRIPTION
**Pull request by r0bnet**
Hey,

my first PR here. Hope I didn't miss anything.

Background of this PR is:
https://github.com/hashicorp/terraform/issues/25387

### CODE REVIEW

**Comment by pkolyvas** [comment]
Thanks for the pr @r0bnet :) 

Just a quick note that we're not going to be merging external PRs for new functionality (or much else, short of bugs) until 0.13 is released. 

We'll revisit this following Terraform's 0.13.0 release.

**Comment by r0bnet** [comment]
Hey @pkolyvas,

that's what I expected but not what I hoped ;)

I'll try to keep it updated once in a while with a rebase so that merging later will be faster hopefully.

Thanks.

**Comment by r0bnet** [comment]
@apparentlymart is it possible that you or someone else could check this PR? Just rebased it and back then it was blocked due to pre-0.13

**Comment by apparentlymart** [comment]
Hi @r0bnet! Sorry for the delay in looking at this... my work for Terraform 0.14.0 ran on a little longer than I'd hoped, so I'm only just getting to PR reviewing now.

What you wrote here is great, and I'm grateful that you took the time to contribute it. I made some small tweaks to the error messages, with the main functional change being that it will now use `function.NewArgErrorf` instead of just `fmt.Errorf`, which the language runtime understands as a special way to signal that a specific argument was errored, and thus highlight only that argument in the final error message.

After seeing this all in context I realized also that the function names I'd suggested to you in #25387 were inconsistent with our existing naming scheme of putting the "encoding type" at the start of the name, so that the encode/decode pairs of functions can sort together in an alphabetical list of functions. With that in mind, I also added a follow-up commit here to rename them to `textencodebase64` and `textdecodebase64`, with "text" here serving as a short way of saying "character encoding". I'm sorry for my oversight in suggesting inconsistent names before.

With all of that said, I'm going to merge this now. I had also intended to merge this during the v0.14.0 development window, and so as a special exception I'm going to backport it into the v0.14 branch even though typically at this stage we'd normally be primarily merging only bug fix changes based on the beta feedback. That means these functions will be available for the first time in v0.14.0-beta2, and should in turn therefore be included in the final v0.14.0 release in a few weeks.

Thanks again, and sorry for the delay!

**Pull request merged**
