### PR TITLE
core: non-CBD depending on CBD won't depend on destroy

### LINKED ISSUE #11349: "ResourceInUse: Cannot delete launch configuration "  occured. When changing launch configuration
When changing launch configuration.
"ResourceInUse: Cannot delete launch configuration " occured

```
* aws_launch_configuration.jqmb_lc.1 (deposed #0): ResourceInUse: Cannot delete launch configuration jqmb_smp_stg_lc_BLUE003df7c24951572ed9b5aed3a0 because it is attached to AutoScalin
gGroup jqmb_smp_stg_asg_BLUE
```

### version
Terraform v0.8.4 .
but Terraform v0.7.7 is ok

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_launch_configuration

### Terraform Configuration Files
```hcl
  resource "aws_launch_configuration" "jqmb_lc" {
    name_prefix          = "jqmb_smp_stg_lc_${var.environment_names[ count.index ]}"
    count                = "${var.environment_count}"
    image_id             = "${var.web_linux_ami}"
    instance_type        = "${var.web_instance_size}"
    security_groups      = [ "${aws_security_group.jqmb_sg_web_instance.id}" ]
    associate_public_ip_address = true
    lifecycle {
      ignore_changes = ["image_id"] 
      create_before_destroy = true
    }
  }

  /**
   * Autoscaling group.
   */
  resource "aws_autoscaling_group" "jqmb_asg" {
    name                 = "jqmb_smp_stg_asg_${var.environment_names[ count.index ]}"
    count                = "${var.environment_count}"
    availability_zones   = ["${var.main_availability_zone}"]
    launch_configuration ="${element(aws_launch_configuration.jqmb_lc.*.id, count.index)}"
    min_size             = "0"
    max_size             = "${var.web_instance_count}"
    desired_capacity     = "${var.web_instance_count}"
    lifecycle {
      ignore_changes = ["desired_capacity"]
    }
    vpc_zone_identifier =  ["${element(aws_subnet.jqmb_web_subnet.*.id, count.index)}"]
    target_group_arns = ["${element(aws_alb_target_group.jqmb_alb_target_group_http.*.id, count.index)}"]
    tag {
      key = "Name"
      value = "JQMB-STG-WEB-${var.environment_names[ count.index ]}"
      propagate_at_launch = true
    }
  }

```

### Expected Behavior
1.Terraform create a new launch configuration with prefix name and change 
2.and  bind new launch configuration to autoscaling group.
3.and remote old launch configuration

### Actual Behavior
1.Removing current launch configuration.
2.Error occured
ResourceInUse: Cannot delete launch configuration

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. changed to some launch configuration variable(instance type , security group...)
3. `terraform apply`

### PR DESCRIPTION
**Pull request by mitchellh**
Fixes #11349 

There are actually two bugs fixed here. Both aren't obvious so I'll explain both in detail. Both bugs manifested themselves in #11349 although it was also possible to hit them in isolation as well.

## 1. CBD with Counts

When CBD is used with `count > 1`, the edge transform wasn't working correctly and would not create the proper dependencies. The `CBDEdgeTransformer` creates a non-CBD graph to determine what the normal dependencies would be, then uses that to _invert_ the edges for CBD.

This non-CBD graph doesn't expand counts, so if you had `type.A[0]` in your normal graph, it'd be `type.A` in the graph used to determine the edges. For now, the solution is simply to ignore indexes when comparing the graphs. 

In the future, this won't be sufficient as we want to make our edges exact (`type.A[0]` should only depend directly on `type.B[0]`, not `type.B[1]`). For now, we don't do this for a number of reasons much larger than CBD.

## 2. Non-CBD Depending on CBD Creates a Cycle

When a non-CBD resource depended on a CBD resource and the non-CBD resource wasn't being destroyed, a cycle would be created. This was caused by non-CBD resources advertising their dependence on any "destroy" portion of their dependencies as well. 

Let's use a concrete example of an ASG depending on an LC to explain this bug.

#### Case 1: No CBD on the ASG and LC

The change should be: `ASG(D) => LC(D) => LC => ASG`. 

This works correctly already.

#### Case 2: CBD on BOTH ASG and LC

The change should be: `LC => ASG => ASG(D) => LC(D)`

This also works correctly already since CBDEdgeTransformer modifies the edges of any CBD resource.

#### Case 3: CBD on ONLY ASG

This is identical to case 2, since we force all dependencies to also inherit CBD status.

#### Case 4: CBD on ONLY LC

The change should be: `LC => ASG (update) => LC(D)`

This is the case where we did the wrong thing. The ASG still advertised it depended on `LC(D)` because it looked like case 1 above. Instead, due to LC being CBD, we already handled the edge manipulations.

To fix this, we now have destroy nodes that are due to CBD advertise themselves as different from non-CBD destroy nodes. Regular nodes still depend on non-CBD destroy nodes for their dependencies. This makes everything connect together properly.

### CODE REVIEW

**Comment by 2rs2ts** [comment]
Is this going to go out in 0.9.0 or can a 0.8.7 be released so our team does not have to jump two major versions? :)

**Comment by mitchellh** [comment]
This will be in 0.8.7 I'm pretty sure.

**Comment by setevoy2** [comment]
@mitchellh Could you please say - when 0.8.7 release planned?
We use _hashicorp/terraform:light_ image atm with 0.8.6 and faced with a "_Cannot delete launch configuration because it is attached to AutoScalingGroup_" error from [here](https://github.com/hashicorp/terraform/issues/532).
And we can't roll back to 0.8.5 (because of state-files). And we really in trouble now, as our CI is not functional now...

**Comment by mitchellh** [comment]
Barring unforeseen issues it will be tomorrow

**Comment by biellou** [comment]
@mitchellh Great news. Is the plan still to release 0.8.7 today?
Thanks,

**Comment by setevoy2** [comment]
Hi, @mitchellh.
Thanks for the 0.8.7 release.
Unfortunately - we still have a "Cannot delete launch configuration" error:

> * aws_launch_configuration.lc (deposed #0): ResourceInUse: Cannot delete launch configuration terraform-00b8b118b0d5aba362e2090a63 because it is attached to AutoScalingGroup staging-api-green-asg

Both LC and ASG have `create_before_destroy = true`:

```
$ grep -r "before_destroy" .
./launch_configuration/launch_configuration.tf:  lifecycle { create_before_destroy = true }
./autoscaling_group_blue/autoscaling_group_blue.tf:  lifecycle { create_before_destroy = true }
./autoscaling_group_green/autoscaling_group_green.tf:  lifecycle { create_before_destroy = true }
```

I also removed `name from the LC tf-file:

```
resource "aws_launch_configuration" "lc" {
  lifecycle { create_before_destroy = true }
  name_prefix     = "${var.name}-"
  image_id        = "${var.image_id}"
  instance_type   = "${var.instance_type}"
  security_groups = ["${split(",", var.security_groups)}"]
  key_name        = "${var.key_name}"
  user_data       = "${var.user_data}"
}
```

Bu this doesn't help.
Our release currently blocked. Maybe there are any other fixes?

Thanks.

**Comment by 2rs2ts** [comment]
I am not having the same problem as @setevoy2. Not sure what the difference is for us.

**Comment by jecnua** [comment]
Having same problem as @setevoy2 and @2rs2ts. Still present for us in v0.8.7.

**Pull request merged**
