### PR TITLE
Fix for #20669

### PR DESCRIPTION
**Pull request by jrottenberg**
Example run :

```
$ ./tag.sh v0.12.25
-- Updating tags to point to version v0.12.25 --

hashicorp/terraform:0.12                                           2020-05-13 10:09:39 -0700 PDT   80.2MB
hashicorp/terraform:0.12-full                                      2020-05-13 10:09:39 -0700 PDT   80.2MB
hashicorp/terraform:0.12-light                                     2020-05-13 10:09:39 -0700 PDT   80.2MB
hashicorp/terraform:0.12.25                                        2020-05-13 10:09:39 -0700 PDT   80.2MB
hashicorp/terraform:0.12.25-full                                   2020-05-13 10:09:39 -0700 PDT   80.2MB
hashicorp/terraform:full                                           2020-05-13 10:09:39 -0700 PDT   80.2MB
hashicorp/terraform:latest                                         2020-05-13 10:09:39 -0700 PDT   80.2MB
hashicorp/terraform:light                                          2020-05-13 10:09:39 -0700 PDT   80.2MB
```

Left the build process alone, but tag and push scripts were adjusted to be able to use a major.minor tagged image rolling forward.

See #20669

### CODE REVIEW

**Comment by danieldreier** [comment]
@jrottenberg I'm not quite sure I understand the objective here. After we release 0.13.0, we will probably not release another 0.12.x release. Can you help me understand what the goal is? I also read the linked issue and didn't understand from there either.

**Comment by jrottenberg** [comment]
Hello !

It's to be able to pin a major.minor release of terraform, today if I want to use 0.12 I need to pin to the patch version in my ci jobs for example. The alternative is to use latest or light, but as you said it will jump to 0.13 quite soon, there's no guarantee 0.13.* will be compatible with 0.12.*.

Say I want to stick to the latest of the 0.13.* builds , without that PR I won't be able to do so safely (using latest is not future proof, as 0.14.x or 1.x most likely will break my builds) or without too much effort (needs to keep track of 'patch versions' and update my terraform reference appropriately)

See https://medium.com/@mccode/using-semantic-versioning-for-docker-image-tags-dfde8be06699 for a longer explanation

Hope that helps !

**Comment by onlydole** [comment]
Howdy, team! 

Regarding @jrottenberg's input, it looks like [this description](https://github.com/hashicorp/docker-hub-images/issues/84) adds a bit more detail in how this this proposed change would work. TL;DR - this would allow for less specific tags to be used for minor versions like `:0.12` as an example.

> ...the goal is to have images on dockerhub with tags matching MAJOR.MINOR , today we only have MAJOR.MINOR.PATCH versions : https://hub.docker.com/r/hashicorp/terraform/tags , 0.12.25 being the latest, but there is no rolling 0.12 tag that we can use in CI for example.

> ```
> $ docker pull hashicorp/terraform:0.12
> Error response from daemon: manifest for hashicorp/terraform:0.12 not found: manifest unknown: manifest unknown
> ```

**Comment by aldegoeij** [comment]
We would also be greatly helped with this!

In our CICD we have projects on 11, 12 and pretty soon 13, not having to lock to patch versions like `0.11.7` would save us a lot of maintenance of CICD scripts, bumping a docker tag when a patch gets released.

We can have our 0.11 projects on `terraform:0.11`, the 12 ones on `terraform:0.12` etc, even if you're stopping development on them, I'm pretty sure there will be a security patch at some time, which we always want to pull in, and not keep track of CVEs etc and update tags manually on our side.

+1 ;)

**Comment by jrottenberg** [comment]
@danieldreier so terraform 0.13.0 is out, now if I need to get the latest of 0.12 version for my cI, there's no clear way beside pinning it to 0.12.29 (but there might be a 0.12.30 to fix a critical security issue, I will not get automatically).

CC @onlydole

**Comment by jrottenberg** [comment]
Ah https://github.com/hashicorp/terraform/pull/26484 will followup on https://github.com/hashicorp/terraform-releases/ if necessary, once it is public

**Pull request closed without merging**
