### PR TITLE
vSphere provider developer docs

### PR DESCRIPTION
**Pull request by chrislovecnm**
Start on a README for developers.

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@phinze @jen20 @catsby please merge ... alas it is only documentation :)  BTW let me know if this is the correct place to put this.  I noticed that the other providers do not have developer specific docs ... I don't think we need this on the website ...

**Comment by phinze** [comment]
Great start, thanks @chrislovecnm!

**Comment by rossedman** [comment]
👍  Great start.

**Comment by chrislovecnm** [comment]
@phinze thanks for the merge!

**Pull request merged**
