### PR TITLE
Fix broken logo link

### PR DESCRIPTION
**Pull request by trung**
Bring back the logo

### CODE REVIEW

**Comment by apparentlymart** [comment]
Thanks for this, @trung!

I'm looking at a way to decouple this from the details of how the website repo is laid out, so I'm going to hold on this for a moment to see what we can do there, but if that doesn't work out then I'll merge this for now so the logo comes back until we figure out the longer-term solution.

Thanks again!

**Comment by apparentlymart** [comment]
Hi again, @trung!

In hashicorp/terraform-website#9 I've tweaked the website source so that these logos should will be available on www.terraform.io. Assuming this works out, the plan would be to link to https://www.terraform.io/assets/images/logo-hashicorp.svg here instead. (This URL is not working at the time of writing, because that image is not currently referenced anywhere on the website.)

**Comment by trung** [comment]
@apparentlymart thanks for the update. I had inspected the resources in www.terraform.io to see if there was any svg image for the logo but i only found https://www.terraform.io/assets/images/mega-nav/logo-terraform-ff69eaae.svg which contains only the logo not the full banner. Further it is prefixed with some random value so I wouldn't take it. 

It's great to know that you already have a fix.

**Comment by apparentlymart** [comment]
Hi @trung,

I changed the README to refer to https://www.terraform.io/assets/images/logo-hashicorp.svg, and the website repository has been adjusted to include that image. The image won't actually be available there until we update the website as part of the 0.10.0 release, but since that's going to happen reasonably soon I figured that we can live with it being broken for now and it should just start working again as a side-effect of the release.

Thanks again for pointing this out! I'm going to close this now since there's no more direct work required here, though I acknowledge that the logo is still broken as of this moment.

**Pull request closed without merging**
