### PR TITLE
Use built-in schema.HashString instead of custom hash functions.

### PR DESCRIPTION
**Pull request by tpounds**
Cleanup a bunch of custom hash functions that implement the same logic as the built-in schema.HashString function.

### CODE REVIEW

**Comment by phinze** [comment]
This is looking great, @tpounds!

But I believe we can take this even one step further - I'm pretty sure that when `Elem` is a string, the `schema.HashString` func is the implicit value for `Set` - so these entries can be simply omitted without a change to behavior.

Then this PR becomes basically all minuses! :grinning:

**Comment by tpounds** [comment]
@phinze It looks like the default hash implementation your refer to was added in cc8e8a55. Before I make the change I just wanted to confirm that the default hash is equivalent to the existing behavior for primitive types. There are a lot of places across all providers that can be simplified to use the default hashing behavior. If this is the route we want to go I can update the pull request to change this across the board.

**Comment by apparentlymart** [comment]
The default implementation for hashing single schema string fields will place a semicolon on the end of the string, as a consequence of how it inserts field separators for more complex constructs. I expect that switching from `schema.HashString` will therefore cause all of the hashes to change, causing inappropriate diffs.

I think continuing to use `schema.HashString` for these is the safe, easy option. Otherwise I expect some gnarly upgrade code will be required, and it's not clear to me that it would give enough value to be worth the time and complexity.

**Comment by phinze** [comment]
Ah thanks for the catch on that @apparentlymart. Let's go with this as-is. :+1:

**Comment by tpounds** [comment]
@apparentlymart, @phinze Does it make sense to fix the default hash behavior to make it equivalent to `schema.HashString`? It seems like there should be explicit `schema.Hash*` functions that have the same behavior as the default hashes. Thoughts?

**Comment by phinze** [comment]
@tpounds the tricky part of that would be the potential churn that would introduce in existing states in the wild... I think we might need some additional core machinery for preventing unexpected diffs on upgrades so we can confidently make changes like this... I'll think about this a bit more and get back to you

**Pull request merged**
