### PR TITLE
examples: add OpenStack configuration with networking

### PR DESCRIPTION
**Pull request by berendt**

### CODE REVIEW

**Comment by jtopjian** [comment]
Very nice!

What are your thoughts about adding a note to say that the auth variables can be omitted when the user has sourced an openrc file?

**Comment by berendt** [comment]
@jtopjian Please have a look. I think it is more convenient to use the `openrc` file.

**Comment by jtopjian** [comment]
@berendt I like it. Very nice work. :smile: 

The CI test failure looks to be something unrelated.

**Comment by berendt** [comment]
In the latest update of this PR I removed unused variables from `variables.tf`.

**Comment by berendt** [comment]
Anything else to do here?

**Comment by apparentlymart** [comment]
Agreed that those test failures don't seem to have anything to do with your change. Thanks!

**Pull request merged**
