### PR TITLE
Improve Documentation regarding `templatefile`

### PR DESCRIPTION
**Pull request by FireDrunk**
As talked about in https://github.com/hashicorp/terraform/issues/35441

Just a documentation improvement.

### CODE REVIEW

**Comment by crw** [comment]
Thanks for the submission! I believe the text as written as been outdated by the further explanation in the ticket. The feedback from this comment would need to be integrated: https://github.com/hashicorp/terraform/issues/35441#issuecomment-2220969976. Thanks again!

**Comment by FireDrunk** [comment]
I think my addition to the documentation sufficiently explains the caveats on using the `file` function inside the `templatefile` function?

To state it differently, what documentation changes would you suggest to increase the chances of users finding it, and not go through the same ordeal as I did?

**Comment by crw** [comment]
From the `file` function page:

> file reads the contents of a file at the given path and returns them as a string.

Which is what it does in this context. I do not think it is accurate to say it has caveats or will not load a "template file," it will load any string file as a string, as I understand it. Perhaps it would be more accurate to say:

> Using the `file` function to load a template file will result in that file being introduced as the literal string contents of that file, and will not result in the template file being processed as a template.

I might be missing a nuance here, I'll also run this past the devs in triage. Thanks!

**Comment by crw** [comment]
Thanks again for this submission! I reviewed this in triage and there was consensus that this warning does not reflect the actual behavior of Terraform. Thanks again!

**Pull request closed without merging**
