### PR TITLE
command/workspace_select: create workspace if it doesn't exist.

### PR DESCRIPTION
**Pull request by iamnande**
Halo!

This is a pass at a flag for `workspace select` that creates a given workspace if it doesn't already exist.

All of the terraform repositories we run go through a CI system for actual processing. The concept of workspaces helps separate state from a single repository if multiple humans are iterating over work. Even using the best practice structure of an environment, or workspace, directory per environment we still run into the issue of manually having to create a workspace when adding environments or adding logic to the CI build to catch the error that the workspace doesn't exist.

This change adds a `-create` flag to the `workspace select` command to optionally create the workspace if it does not exist, and if it does exist - just continue as normal.

Cheers,
@iamnande

_p.s. - this was a fun little aside for my brain, feel free to close/rework/etc._

### CODE REVIEW

**Comment by apparentlymart** [comment]
Hi @iamnande! Thanks for working on this.

The team is largely heads-down on finish up the Terraform 0.12 development work right now so we'll come back and look at this once that work is merged down into `master`.

Thanks again!

**Comment by mildwonkey** [comment]
Well hello @iamnande, I know you! I'd be happy to take a look at this - are you still interested in working on it (to resolve the conflict), or would you like me to take it over? In either case, thank you!

**Comment by iamnande** [comment]
hey there @mildwonkey! I'm down to pick it back up. I'm just coming back from a month off so i'm still figuring out how to computer again. 

i can probably have a good idea of whether or not i'd like to pass it off by the weekend.

cheerio!

**Comment by mildwonkey** [comment]
I'm going to close this since it's been quite awhile, and we've been making various changes to the `workspace` code so there are conflicts. Please feel free to open a new PR (or a feature request) if you're still interested. Cheers!

**Pull request closed without merging**
