### PR TITLE
[Docs] Clarify remote state storage w/ TFE

### PR DESCRIPTION
**Pull request by chrisarcand**
Adds a bit of clarification about state storage with the remote backend and TFE.

### CODE REVIEW

**Comment by blalor** [comment]
I don't think this addresses the case of a user whose organization is not enabled for remote compute.  They'll still be using the `remote` backend, but plans and applies are executed on the local machine, right?

**Comment by chrisarcand** [comment]
Ahh good call! Amended!

**Comment by nfagerlund** [comment]
This is great, thanks! Also, Sander updated something else in that page before I got around to merging this, and there's a merge conflict. 😅 So I'm closing this and just cherry-picking the commit onto Sander's branch (https://github.com/hashicorp/terraform/pull/20739), then re-arranging things a little bit.

**Comment by chrisarcand** [comment]
@nfagerlund Awesome, thanks!

**Pull request closed without merging**
