### PR TITLE
provider/openstack: Redesign openstack_blockstorage_volume_attach_v2

### PR DESCRIPTION
**Pull request by jtopjian**
The current design of openstack_blockstorage_volume_attach_v2 does
not correctly implement the Block Storage API attachment call. It
was only partially implemented, only marking volumes as being
attached, while never actually attaching them.

This redesign is a closer alignment to how creating attachments
to a standalone Block Storage service works.

For creating attachments specifically in the case of OpenStack
Compute instances, the openstack_compute_volume_attach_v2 resource
is required.

For #12000

### CODE REVIEW

**Comment by jtopjian** [comment]
So this is embarrassing. I originally made this resource in parallel to `openstack_compute_volume_attach_v2` and I must have gotten my testing mixed up. None of the acceptance tests actually _log in_ to the created virtual machines to confirm a volume was attached (it would be quite difficult to do, but something to perhaps look into in the future), so I must have fumbled when I did a manual verification. Since then, always thinking this was verified at some point. Ouch.

As reported in #12000, no volume is actually being attached to the instance. Therefore, if anyone is using this resource, it's not actually doing anything, and thus, IMO, open to either two things:

1. total removal
2. attempt to fix it for what it should actually be used for.

I'm going with 2. I have actually tested this one across two OpenStack clouds (and did some iSCSI work, as noted in the updated docs), so I'm _positive_ this resource actually _does something_ this time. However, it's worth noting that this functionality is a bit cutting-edge (and mostly undocumented, as can humorously be seen [here](http://lists.openstack.org/pipermail/openstack-dev/2016-January/083684.html)). I'm OK with that. I'd rather try adding something where a user could do some possibly cool stuff and report any fixes required than entirely yanking this resource. 

But if it's safer to just remove this resource, I'm OK with that, too, and I apologize for the blunder on this one.

**Comment by michalmedvecky** [comment]
For my purposes, `openstack_compute_volume_attach_v2` works fine so as someone who reported the issue, I am fine with the removal of `openstack_blockstorage_volume_attach_v2`.

**Comment by jtopjian** [comment]
@michalmedvecky Yeah, removing this won't actually hurt anyone, so I'm not opposed to it. Since it's already been added, though, I'm interested to see if users find this useful when applied in the way it was supposed to be used.

I've updated the docs to mention that this resource is experimental and might be removed in the future, which will help in the case when it's best to just throw in the towel. 

@stack72 Thoughts?

**Comment by stack72** [comment]
Now that we have handled backwards incompatibility - this LGTM! Thanks for tall the work on fixing this resource up @jtopjian

**Pull request merged**
