### PR TITLE
core: processIgnoreChanges drops NewComputed+ForcesNew only diffs

### PR DESCRIPTION
**Pull request by dpiddockcmp**
Fix for #17855

Sometimes a resource is set for destroy/create when it only has computed attributes creating that change. I haven't been able to get the null_resource to do this as it doesn't set NewComputed on the triggers.

If you have an ignore_changes lifecycle set on any valid attribute those computed values get ignored. The resource is then not recreated.

Please see issue for full details.

### CODE REVIEW

**Comment by apparentlymart** [comment]
Hi @dpiddockcmp! Thanks for working on this, and sorry for the slow response.

We're currently working in a development branch for the next major release which includes some significant changes to how plans are represented internally, as part of introducing the new type system for [the planned configuration language improvements](https://www.hashicorp.com/blog/terraform-0-1-2-preview).

The changeset here is unfortunately already in conflict with the development branch :confounded: so what I'd like to do here is keep this PR open for the moment and then refer to it once the work in progress is complete to understand how to apply the same fix to the new code structure. We're still a ways away from completing the restructuring work, but I expect once that's finished we should be able to find an equivalent way to get the result you intended here against the new data types.

**Comment by ravenac95** [comment]
@apparentlymart Is this going to be available in 0.12.x? This is a very disruptive issue because of terraform-providers/terraform-provider-aws#5170

**Comment by barryib** [comment]
Any chance to see this merged ? This fix a real problem detailed within terraform-providers/terraform-provider-aws#5170

**Comment by teamterraform** [comment]
Closing as this will need to be reworked post-0.12, as per @apparentlymart's comment.

Please add a :+1:  #17855 if you would like this to be prioritised by the Terraform Core team.

**Pull request closed without merging**
