### PR TITLE
[WIP] Add support for CloudTrail Event Selectors

### PR DESCRIPTION
**Pull request by bryan-stripe**
Hi, folks!

I've made a first draft of an attempt to add support for [CloudTrail Event Selectors](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/logging-management-and-data-events-with-cloudtrail.html) to Terraform. This is obviously my first PR against Terraform, so I'm very happy to accept any feedback from y'all that you'd be willing to give. (Specifically around organization of the code, naming of the resources, suggestions for more tests, etc.! Even nitpicks very welcome. :))

From what I can tell, this code mostly does the right thing, but there's one case I haven't yet figured out. Trails have a "simple" mode—where you don't specify any event selectors, and you get all of the read/write management events—which is what TF can currently create; this patch lets you optionally add selectors, but despite the fact that the _console_ seems to be able to revert a trail back to "simple" mode, I can't figure out how to do so from the API. (I've even gone so far as to make the change in the console and watch the generated CloudTrail logs, and... near as I can tell it's just magic.)

Thanks for your consideration!

(I'll ping issue #13949, since I think this patch'll address their request as well.)

### CODE REVIEW

**Comment by bryan-stripe** [comment]
(And before this gets merged I'll obviously fix the `TODO`...)

**Comment by nwalke** [comment]
Looks like this will solve my feature request 👍

**Comment by stack72** [comment]
Ping @bryan-stripe 

thanks for taking the time to work on this PR - please could you update us on the status of it? Incase you didn't realise, Terraform has just split it's repository apart. It would be great if you could open this PR against the [correct repo](https://github.com/terraform-providers/terraform-provider-aws) when you believe it is ready for a review

Thanks

Paul

**Comment by bryan-stripe** [comment]
@stack72 Hey Paul! I was actually hoping for some directional feedback (just a few minutes of review by an experienced committer). Sorry if that wasn't clear! I'm happy to move this over to the new repo and re-raise for feedback; once I do, what's the best way to get some quick review to make sure I'm not barking up the wrong tree?

**Comment by stack72** [comment]
Hi @bryan-stripe 

I *definitely* think this is looking sharp - I am certainly not looking at the code and thinking that it looks as though the approach is incorrect. The only think i would suggest is some naming updates and some changes to validation :)

But that's all easily achievable

Thanks

Paul

**Comment by apparentlymart** [comment]
Hello @bryan-stripe, and thanks for working on this!

As part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it.

If you or someone else has the time and motivation to apply same changes to [the `aws` provider repository](https://github.com/terraform-providers/terraform-provider-aws) and open a new PR there, the maintainers of that provider should be able to review and merge it.

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Pull request closed without merging**
