### PR TITLE
[WIP] Add Kubernetes provider

### PR DESCRIPTION
**Pull request by radeksimko**
Resubmitting #3132 from `hashicorp` branch since there will be a lot more work involved in this and @lwander volunteered to help out. :wink: 

Feel free to submit PRs against this new branch.

### CODE REVIEW

**Comment by xied75** [comment]
Guys, when are we going to have this into the master?

**Comment by lwander** [comment]
@xied75, once we have the full implementation finished; you can see partial progress here: #3584. Since the resources are so verbose (about 1KLOC for just the pod description) I ran a proposal by the Hashicorp guys on a way to speed up this implementation, but haven't heard back yet - it might be time for me to speed up implementation again.

**Comment by Fodoj** [comment]
@radeksimko what are your plans on this PR?

**Comment by hingstarne** [comment]
+1 Would love to see it implemented

**Comment by radeksimko** [comment]
Thanks for the interest, the current state (@lwander correct me if I'm wrong) is that we'd love to have it in upstream, but we aren't sure about the approach and weight of all pros/cons of either translating the K8S API fields of all resources completely into the Terraform's HCL or letting the user define everything via YAML/JSON.

Each approach has different caveats which were mostly discussed in https://github.com/hashicorp/terraform/pull/3132

What is your POV on this @Fodoj @hingstarne ?

**Comment by lwander** [comment]
Yes, that's correct. The pod resource is fully implemented using Terraform's config language, and the PR is huge: https://github.com/hashicorp/terraform/pull/3584. I'd prefer to switch to code generation to generate provider resources to avoid this kind of thing before writing another several thousand lines of code.

**Comment by mtougeron** [comment]
Hi, wanted to throw in my 2c on this. Having a provider where we have to use yaml/json for `spec` is better than having nothing at all. Then having another release/update with the full HCL implementation for `spec` once the code generator part is figured out.

At the moment we are "hacking" things together by using the `template` resource and `local-exec` provider for interacting with Kubernetes. Having the basic kubernetes resources would save us a ton of headaches.

Thanks for your great work!
-Mike

**Comment by pmoust** [comment]
What are the cons in letting users defining K8s stuff in json/yaml @radeksimko from your PoV?

**Comment by radeksimko** [comment]
@pmoust From user's perspective there may be a few - non-idiomatic Terraform configs is one I can think of. e.g. it would be tricky/impossible to make "subresources" off resources that you'd configure via JSON/YAML.

Imagine there was something worth managing separately (to make use of `count` and/or interpolation functions) - e.g. `kubernetes_pod_container` which would be a subset of `kubernetes_pod` YAML/JSON definition.

From Terraform's developer perspective it is very tricky to get around the way K8S API works where you send an array `[a, b, c]` to the `Create` API and then you `Get` back `[a, b, c, d]`. This happens for example with pods that get some secret volumes attached automatically, but happens with most other resources I had the chance to play with. The whitelisting/blacklisting is tricky part.

**Comment by lwander** [comment]
Also - not all Kubernetes resource attributes can be updated, but the Terraform provider cannot be made aware of this unless it parses and reads all the JSON/YAML input.

**Comment by errordeveloper** [comment]
Would love to try this out and help where I can, but it'd much easier if it was in a separate repo, i.e. a plugin.

**Comment by devth** [comment]
:+1: I'd also like to see K8S ConfigMap support in provider/kubernetes.

**Comment by Seraf** [comment]
:+1:, I'd be happy to help on this topic, we will need it soon for our internal usage.

**Comment by radeksimko** [comment]
Hi folks,
I'd be happy for more people to get involved in this + do some work myself.

The K8S provider is somewhat special in terms of size & complexity of the API hence there are some core-enhancements that most likely need to be done to make creation and ongoing maintenance of such provider less painful:

1. Nestable resources - https://github.com/hashicorp/terraform/issues/2275
2. Have a way to **generate (or at least partially generate) resource schemas**. I don't think it's a good idea to _reimplement_ the whole K8S API by hand in `schema` and keep maintaining it by hand. See https://github.com/hashicorp/terraform/pull/3132 & https://github.com/hashicorp/terraform/pull/3026#issuecomment-132691896 to understand why handling raw JSON is probably not the right approach either.
3. Have a way to **generate (or at least partially generate) docs** - see WIP at https://github.com/jen20/larceny

Suggestions and (WIP) PRs regarding each point are welcomed. 😉

**Comment by radeksimko** [comment]
As discussed privately with @lwander I'm closing this stale PR for now along with https://github.com/hashicorp/terraform/pull/3584 .

The Kubernetes provider implementation is open for anyone else to revisit, but I'd highly recommend doing so after the [mentioned things](https://github.com/hashicorp/terraform/pull/3453#issuecomment-224261369) are at least partially solved.

Implementing even a very basic (and actually useful) K8S provider _manually_ (like I did here) doesn't seem to be a good approach which is a **lesson learnt** from this closed PR - so in that sense the effort & time here was not wasted.

**Pull request closed without merging**
