### PR TITLE
AWS Spot fleet resource

### LINKED ISSUE #4070: Feature Request: Spot-Fleet Requests from AWS
It would be nice to add this to terraform:

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet-requests.html

AWS sucks at keep track of such spot-fleet requests, with terraform you can easily tag them internally.

### PR DESCRIPTION
**Pull request by keshavdv**
This adds a Spot fleet resource to AWS, docs and some acceptance tests. We've been using this for a bit in our own environment without any issues.

Fixes #4070

### CODE REVIEW

**Comment by jen20** [comment]
Hi @keshavdv! Thanks for opening a pull request. I've taken a quick look over it and it looks good to me - one request however: could you rebase this onto master and squash it into a single commit? Thanks!

**Comment by keshavdv** [comment]
Done!

**Comment by solarkennedy** [comment]
^ keep in mind that "fixes" thing has to be in the "body" of the PR to work (otherwise it is just a reference, not an auto-close thing):
https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by keshavdv** [comment]
Huh, didn't know that. Updated the PR.

**Comment by stack72** [comment]
Thanks for rebasing this PR @keshavdv 

On running the tests, I could see they were targetted towards us-east-1, but no region was added to the region:

```
make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSSpotFleetRequest_'
==> Checking that code complies with gofmt requirements...
/Users/stacko/Code/go/bin/stringer
go generate $(go list ./... | grep -v /vendor/)
2016/06/23 07:55:34 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSSpotFleetRequest_ -timeout 120m
=== RUN   TestAccAWSSpotFleetRequest_basic
--- FAIL: TestAccAWSSpotFleetRequest_basic (73.70s)
	testing.go:255: Step 0 error: Error applying: 1 error(s) occurred:

		* aws_spot_fleet_request.foo: Error requesting spot fleet: [WARN] Error creating Spot fleet request, retrying: InvalidSpotFleetRequestConfig: Invalid Amazon Machine Image(s) specified: The image id '[ami-f652979b]' does not exist (Service: AmazonEC2; Status Code: 400; Error Code: InvalidAMIID.NotFound; Request ID: bfd448e2-0979-4ed1-bd30-fba3f47c3b1a).
			status code: 400, request id: f7d44743-6108-4de8-aef7-a5432b604a8c
=== RUN   TestAccAWSSpotFleetRequest_launchConfiguration
--- FAIL: TestAccAWSSpotFleetRequest_launchConfiguration (14.84s)
	testing.go:255: Step 0 error: Error applying: 1 error(s) occurred:

		* aws_spot_fleet_request.foo: InvalidAMIID.NotFound: The image id '[ami-f652979b]' does not exist
			status code: 400, request id: ed45e060-06b5-4250-8caf-ceebddf23b16
=== RUN   TestAccAWSSpotFleetRequest_CannotUseEmptyKeyName
--- PASS: TestAccAWSSpotFleetRequest_CannotUseEmptyKeyName (0.00s)
FAIL
exit status 1
FAIL	github.com/hashicorp/terraform/builtin/providers/aws	88.553s
```

I then changed the tests to use `us-west-2a` and `ami-d06a90b0` (and m1.small to keep the testing costs down) for us-west and got the following results:

```
make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSSpotFleetRequest_'
==> Checking that code complies with gofmt requirements...
/Users/stacko/Code/go/bin/stringer
go generate $(go list ./... | grep -v /vendor/)
2016/06/23 08:11:21 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSSpotFleetRequest_ -timeout 120m
=== RUN   TestAccAWSSpotFleetRequest_basic
--- PASS: TestAccAWSSpotFleetRequest_basic (29.91s)
=== RUN   TestAccAWSSpotFleetRequest_launchConfiguration
--- PASS: TestAccAWSSpotFleetRequest_launchConfiguration (31.60s)
=== RUN   TestAccAWSSpotFleetRequest_CannotUseEmptyKeyName
--- PASS: TestAccAWSSpotFleetRequest_CannotUseEmptyKeyName (0.00s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	61.523s
```

I have manually merged this with these changes :)

Thanks for the work here

Paul

**Pull request merged**
