### PR TITLE
backend/local: preserve serial and lineage on failure

### PR DESCRIPTION
**Pull request by svanharmelen**
When failing to write the state, the local backend writes the state to a local file called `errrored.tfstate`. Previously it would do so by creating a new state file which would use a new serial and lineage. By exorting the existing state file and directly assigning the new state, the serial and lineage are preserved.

### CODE REVIEW

**Comment by svanharmelen** [comment]
While this fixes the bug, I also noticed that the error that is returned mentions:

```
Running "terraform apply" again at this point will create a forked state, making it harder to recover.
```

I assumed a `forked state` meant a state with a different lineage. But I tested that and that doesn't seem to be the case. At least not when using the remote backend for remote state storage. So does a `forked state` only means a state file whose content has diverged from the actual last state (the one captured in `errored.tfstate` in this case)?

**Comment by apparentlymart** [comment]
The idea of "forked state" here means that there will be two different snapshots that have the same serial and lineage, which is not supposed to be possible and breaks the ordering assumptions we normally make about state snapshots.

It's unfortunate to be introducing that new concept right here in the middle of a pretty bad error condition; when I originally wrote it I hoped that the "making it harder to recover" part would be the most significant part for the reader: even if they don't fully understand _why_ it is harder to recover then, it's important for them to know that running `terraform state push errored.tfstate` _as the very next step_ is important. Whether the message achieves that goal is of course debatable; this message appears so infrequently we've not really got a good signal on the usability of it.

**Comment by svanharmelen** [comment]
> The idea of "forked state" here means that there will be two different snapshots that have the same serial and lineage, which is not supposed to be possible and breaks the ordering assumptions we normally make about state snapshots.

Check!

> I hoped that the "making it harder to recover" part would be the most significant part for the reader

I think it is. And also the "what to do next" is very clear, so I don't think we should change the error right now. Just making sure I didn't misunderstand or missed anything.

**Comment by svanharmelen** [comment]
Sure thing! I'll update those docs before merging the PR 👍

**Pull request merged**
