### PR TITLE
provider/aws: Add aws_instance data source

### PR DESCRIPTION
**Pull request by grubernaut**
Adds the `aws_instance` data source, tests, and documentation.

```
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/01/18 11:49:09 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSInstanceDataSource -timeout 120m
=== RUN   TestAccAWSInstanceDataSource_basic
--- PASS: TestAccAWSInstanceDataSource_basic (106.24s)
=== RUN   TestAccAWSInstanceDataSource_AzUserData
--- PASS: TestAccAWSInstanceDataSource_AzUserData (108.52s)
=== RUN   TestAccAWSInstanceDataSource_gp2IopsDevice
--- PASS: TestAccAWSInstanceDataSource_gp2IopsDevice (80.71s)
=== RUN   TestAccAWSInstanceDataSource_blockDevices
--- PASS: TestAccAWSInstanceDataSource_blockDevices (94.07s)
=== RUN   TestAccAWSInstanceDataSource_rootInstanceStore
--- PASS: TestAccAWSInstanceDataSource_rootInstanceStore (95.17s)
=== RUN   TestAccAWSInstanceDataSource_privateIP
--- PASS: TestAccAWSInstanceDataSource_privateIP (241.75s)
=== RUN   TestAccAWSInstanceDataSource_keyPair
--- PASS: TestAccAWSInstanceDataSource_keyPair (208.77s)
=== RUN   TestAccAWSInstanceDataSource_VPC
--- PASS: TestAccAWSInstanceDataSource_VPC (109.89s)
=== RUN   TestAccAWSInstanceDataSource_SecurityGroups
--- PASS: TestAccAWSInstanceDataSource_SecurityGroups (118.66s)
=== RUN   TestAccAWSInstanceDataSource_VPCSecurityGroups
--- PASS: TestAccAWSInstanceDataSource_VPCSecurityGroups (136.79s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/aws    1300.625s
```

Fixes: #11172

### CODE REVIEW

**Comment by stack72** [comment]
This is awesome :) LGTM!

**Comment by cemo** [comment]
I was almost filed an issue for this. Thank you so much for your work.

**Comment by cemo** [comment]
@grubernaut before opening an issue I wanted to be sure. It seems that `aws_instance` can not support multiple instances. My use case including a scenario to get instances from `aws_autoscaling_groups`. I would like to reach instances and include in load balancer in a dynamic way.

**Comment by cemo** [comment]
BTW `https://www.terraform.io/docs/providers/aws/d/instance.html` is not listed at side menu as well. :) I will add tonight.

**Comment by cemo** [comment]
I have just seen your comment.

```// Possibly with a different data source that returns a list of individual instance data sources```

**Comment by kreisys** [comment]
Just a heads up, this is still not listed in the documentation side menu under data sources. I've written a lot of ugliness in order to work around the lack of an aws_instance datasource 😅

Also, it seems like this data source doesn't map the tags properly and leaves them in the form they were received from amazon. For comparison, see the state from the resource vs the data source:

```
tags.#                                    = 3
tags.2220489295.key                       = Name
tags.2220489295.value                     = core-001
tags.3171833312.key                       = Terraform
tags.3171833312.value                     = 1
tags.982453103.key                        = Consul
tags.982453103.value                      = Server
```
```
tags.%                                            = 3
tags.Consul                                       = Server
tags.Name                                         = core-001
tags.Terraform                                    = 1
```
I tried to work around this with interpolations but haven't been successful.

**Pull request merged**
