### PR TITLE
Bumped AWS SDK to 1.5.8

### LINKED ISSUE #10234: request: Update aws/aws-sdk-go to 1.5.8
Hi guys,

It would be awesome to bum the aws/aws-sdk-go version to 1.5.8. This way, we could benefit from apigateway binary format, lambda env vars, etc.

I tried to install govendor, but every govendor command on my Mac is hanging without doing anything... (excepted for sync, but that's another subject I guess)

(By the way, If someone can help on that, would be awesome!)

### PR DESCRIPTION
**Pull request by Ninir**
This updates the aws/aws-sdk-go to 1.5.8

The main reasonning is to get:
* apigateway binary format
* lambda env vars
* auto-scaling EMR instance groups.
* ...

As this is a big change, is there something I should provide? Hope it can fit!

### CODE REVIEW

**Comment by stack72** [comment]
Hi @Ninir 

Thanks for the work here - can I ask what the govendor command you ran here? :)

Paul

**Comment by Ninir** [comment]
Hi @stack72 

Sure, here it is:

    govendor fetch github.com/aws/aws-sdk-go/...@=v1.5.8

Do you want me to run any acceptance tests?

**Comment by catsby** [comment]
I ran a few acceptance tests as a smoke test, as expected nothing red. I'm going to go ahead and pull this in

**Comment by Ninir** [comment]
Thank you @catsby !

**Pull request merged**
