### PR TITLE
Deps: Update Depedency for license

### PR DESCRIPTION
**Pull request by grubernaut**
Previously dependency didn't have a license file attached, causing
audit to fail. Update dependency to use newly attached license.

### CODE REVIEW

**Comment by grubernaut** [comment]
Depends on: https://github.com/terraform-providers/terraform-provider-aws/pull/1558

**Comment by catsby** [comment]
terraform-providers/terraform-provider-aws#1558 has been 👍

**Comment by radeksimko** [comment]
Do you mind looking into this?
```
$ make vendor-status
The following packages are missing or modified locally:
	github.com/aws/aws-sdk-go/aws/arn
Error: status failed for 1 package(s)
```

**Comment by grubernaut** [comment]
@radeksimko, yea diving into that now. It's a circular dependency between importing the `aws-sdk-go` and `terraform-provider-aws` packages. :scream_cat:

**Pull request merged**
