### PR TITLE
lock timeouts

### PR DESCRIPTION
**Pull request by jbardin**
Adds a `-lock-timeout` parameter, which will retry a state lock for at least the duration of the timeout. 

The actual blocking retry loop is provided by the `state.LockWithContext` function. State implementations themselves still don't need to be able to handle blocking on locks or timeouts.

Having a way to retry a lock, up until a timeout, would allow terraform automation processes to run concurrently without immediately failing. 

Some additional cleanup:
- Add the Locker interface to the standard State interface. Since all implementations are now Lockers, we can avoid a bunch of type assertions.
- rename "message" package to "clistate", since that is how it's imported everywhere.
- move the `force-unlock` command to "plumbing"
- Add missing `-lock` option to `import` and `init`
- Catch a couple locations where locks could be attempted even with `-lock=false`.

### CODE REVIEW

**Comment by jbardin** [comment]
yeah, I usually prefer to create hooks to cause time-related tests to step through the possible states without Sleep (and I've been known to habitually refactor Sleeps out of exiting tests 😉 ). 

I could pretty easily drop the sleep from the in-package test (which I think I'll do now), but agree adding the hooks for external testing doesn't seem worth it, especially since that is using an external process to lock the file as well.

**Comment by jbardin** [comment]
Just tacked on the doc changes here too

**Comment by apparentlymart** [comment]
The docs look good to me too! :grinning:

**Comment by brikis98** [comment]
@jbardin If you run the `init` command with `-lock-timeout=60m`, does that timeout apply only to the `init` command itself, or all future commands you call after as well (e.g. `apply`)? Is there any way to define the timeout in your Terraform configurations (`.tf`) themselves or only via the CLI? It seems very error prone to have to remember to specify the timeout for every single command...

**Comment by jbardin** [comment]
@brikis98, the `-lock-timeout` flag only applies to the command being executed. 

The locks by design are intended to fail fast, protecting the state files from concurrent mutations, and the lock implementations themselves don't provide any blocking behavior. This flag was primarily added for the case where automated systems may want to retry the operation automatically if a lock was already taken, and we often rely on flags over configuration for automated systems. This is not meant to solve the problem for highly concurrent systems, since the locks themselves can't block, and therefor can't provide a deterministic serialization of waiting clients. 

Not providing the flag can't cause any additional errors, it just reports the lock status to the user. on the first attempt.

**Comment by brikis98** [comment]
Got it, thanks.

**Pull request merged**
