### PR TITLE
Add a boolean flag to http remote that disables cert validity checking (for e.g. self-signed certs)

### LINKED ISSUE #2214: `terraform remote config` with REST backend errors on self-signed certs
Hello!

We are integrating Terraform with an internal inventory tool, and would like to store the state using a REST endpoint.

Currently our REST endpoint works wonderfully if accessed over HTTP, but when we switch to our (self-signed) HTTPS, Terraform complains:

```
Error while performing the initial pull. The error message is shown
below. Note that remote state was properly configured, so you don't
need to reconfigure. You can now use `push` and `pull` directly.

Error reloading remote state: Get https://<server>/api/terraform/state: x509: certificate signed by unknown authority
```

Would it be possible to add an override to accept self-signed certs?

Cheers,
Colin

### PR DESCRIPTION
**Pull request by LeftyBC**
Should fix #2214.

Extend the HTTP remote storage to support skipping SSL/TLS certificate validation.  This is useful for testing, or if using self-signed certs in an internal network.

Skip validation of certs:
```terraform remote config -backend=http -backend-config="address=https://server_with_invalid_cert/path" -backend-config="skip_cert_verification=true"```

Restore validation of certs:
```terraform remote config -backend=http -backend-config="address=https://server_with_invalid_cert/path" -backend-config="skip_cert_verification=false"```

Default for this flag is to verify certs, which matches the behaviour in Terraform 0.5.3.

### CODE REVIEW

**Comment by mitchellh** [comment]
Thanks! There is some Go weirdness here, but I'll fix that up and CC you on it if that helps. :) Otherwise LGTM!

**Comment by mitchellh** [comment]
Cleaned up here: 76d920f5042c78eb5553fdb0a02f74ba95cdf1ae

**Comment by LeftyBC** [comment]
My first foray into Go, so I'm not surprised that it's not quite idiomatic... thanks for the cleanup!  

We're very excited to be implementing Terraform, especially after your talk at Hootsuite a little while ago.  Very cool stuff.  Keep up the good work!

**Comment by JackChance** [comment]
terraform on  windows 7 was giving me "←[31mFailed to read state: Error reloading remote state: HTTP remote state endpoint requires auth←[0m←[0m" every time I tried a push or pull to the tutorial atlas server. Setting cert verification to false fixed it. Thanks!

**Comment by jkodroff** [comment]
In case anyone stumbles upon this now-obsolete PR, this is how to get around the self-signed cert issue these days:

```
provider "vsphere" {
    allow_unverified_ssl = true
}
```

**Comment by danparsons** [comment]
The above "allow_unverified_ssl" flag does not exist in all providers. For example, it doesn't exist in the powerdns provider.

**Comment by vedat227** [comment]
when I use below configuration it works for almost all AWS services but S3 

caused by: Get https://XXX.s3-eu-west-1.amazonaws.com/?prefix=env%3A%2F: x509: certificate signed by unknown authority

provider "aws" {
  region = "eu-west-1"
  profile = "saml"
  insecure = true
}

data "terraform_remote_state" "network" {
  backend = "s3"
  config {
    bucket = "XXX"
    key    = "XXX"
    profile = "saml"
    region= "eu-west-1"
  }
}

**Comment by warroyo** [comment]
is there a way to ignore ssl verification errors using the new backend configuration style release in 0.9.x?

**Pull request merged**
