### PR TITLE
Fix quoting in README.md

### PR DESCRIPTION
**Pull request by spy-tech**
Fix one correctness issue, the rest is stylistic.

### CODE REVIEW

**Comment by mitchellh** [comment]
Hey there! Thanks. I tried our current quoting (or lack thereof) in sh, bash, and zsh and it worked fine in all three. Given those are three of the most major shells out there, I think our quoting is likely fine unless there is something I'm missing!

**Comment by spy-tech** [comment]
@mitchellh Try adding a space to the GOPATH. 

```
GOPATH='/home/foo bar' cd $GOPATH
bash: cd: /home/foo: No such file or directory
```

**Comment by mitchellh** [comment]
Ah, in that case we should probably just double quote the entire value. Will edit live.

**Comment by spy-tech** [comment]
No

**Comment by mitchellh** [comment]
Can you please explain further? "No" is not particularly helpful and I am interested in getting in any changes I am misunderstanding. Thank you!

**Comment by spy-tech** [comment]
Quoting just the variable tells the human that a small part is interpreted using variable substitution rules. The way I wrote it is how it is supposed to be done.

**Comment by mitchellh** [comment]
I see. Unless there are practical dangers of quoting the entire string here, I think that is more aesthetically appealing to me, correctness aside. Please correct me if I'm misunderstanding something, though. Even our "incorrect" path has worked without a single issue being raised for 3 years so I imagine we're having a mostly theoretical discussion here in any case.

**Comment by spy-tech** [comment]
I think it's sloppy. Other people will also think that, but might not say it. To me it communicates that any shell script being written by the Terraform people is suspect. It undermines confidence on what is supposed to be a marketing page.

Feel free to disagree, but I won't change my opinion.

**Comment by mitchellh** [comment]
Fair enough. Thanks for your input! I have no intention of changing your opinion, just wanted to hear it. 😄  In any case, the quoting now covers cases where there may be a space in your GOPATH. If there are edge cases still that aren't handled, I'd be happy to make any changes.

**Pull request closed without merging**
