### PR TITLE
provider/aws: Retire goamz

### PR DESCRIPTION
**Pull request by catsby**
This PR retires `goamz` in favor of [hashicorp/aws-sdk-go][1]

```console
[~/../hashicorp/terraform][f-retire-goamz]$ ack 'goamz' -i .
[~/../hashicorp/terraform][f-retire-goamz]$
```

- consolidates `tags.go` and `tags_sdk.go` (and tests)
- consolidates various `*SDK` versions of functions 
- removes `AWSAuth()` and `AWSRegion()` functions from `aws/config.go`; I don't believe we need them anymore
- renames of `awsEC2conn` to `ec2conn`
- removes `awsGo` import name

[1]: https://github.com/hashicorp/aws-sdk-go

### CODE REVIEW

**Comment by phinze** [comment]
LGTM!

**Comment by pmoust** [comment]
screenshot 2015-03-13 16 54 05

**Comment by willejs** [comment]
:+1:

**Comment by duggan** [comment]
<3 <3 <3

**Pull request merged**
