### PR TITLE
salt-masterless: use sudo to remove dirs

### PR DESCRIPTION
**Pull request by azban**
addresses https://github.com/hashicorp/terraform/issues/20323

### CODE REVIEW

**Comment by azban** [comment]
i could use a hand, if someone could point me to an example of where multiple provisioner runs are run in one test and the state between runs is relevant? looks to me that each of [these](https://github.com/hashicorp/terraform/blob/master/builtin/provisioners/salt-masterless/resource_provisioner_test.go#L107) runs are independent.

**Comment by azban** [comment]
@jcockhren @pointlessone @dawidmalina ^^ ?

**Comment by ycote88** [comment]
When this will be release ? I'm facing same issue here

**Comment by tomwerneruk** [comment]
> i could use a hand, if someone could point me to an example of where multiple provisioner runs are run in one test and the state between runs is relevant? looks to me that each of [these](https://github.com/hashicorp/terraform/blob/master/builtin/provisioners/salt-masterless/resource_provisioner_test.go#L107) runs are independent.

I have hit this scenario due to using Packer to build a base image then using a Terraform provisioner step to provide extra configuration to the ami that can only be known at terraform run time. At present will see if this can be workaround by removing this directory as part of Packer build.

**Comment by mmanea-tc** [comment]
Why is this PR waiting for a full year to be merged? I don't get it.
This is a real issue which people are dealing with, and you force us using workarounds..

**Comment by mmanea-tc** [comment]
And it should not have been classified as 'enhancement'.. it is an bug!

**Comment by danieldreier** [comment]
Hi @azban -

I'm closing this PR because we announced tool-specific (vendor or 3rd-party) provisioner deprecation in [mid-September 2020](https://discuss.hashicorp.com/t/notice-terraform-to-begin-deprecation-of-vendor-tool-specific-provisioners-starting-in-terraform-0-13-4/13997). Additionally, we added a deprecation notice for tool-specific provisioners in 0.13.4. On a practical level this means we will no longer be reviewing or merging PRs for these built-in plugins.

For the time being, the best option if you want to incorporate this change, is to extract the salt-masterless provisioner from the core codebase and distribute it as a plugin binary, similar to how the [ansible provisioner](https://github.com/radekg/terraform-provisioner-ansible) is distributed. I'm aware of the limitations of this approach, but it's the less-bad option compared to coupling provisioner development to the Terraform Core release lifecycle. We believe the benefit to users of having provisioner development decoupled from core, exceeds the convenience of having these provisioners built in to core. We want to provide a better user experience in the future, and our hope here is that the ability to improve, fix and repair provisioners without us blocking their development, much like providers, will help make a strong case for what's next.

I think it’s also important to highlight that we have no plans to remove the generic provisioners or the pluggable functionality during Terraform's 1.0 lifecycle. 

I appreciate your work here to improve Terraform, and am always happy to talk. Please feel free to reach out to me or Petros Kolyvas if you would like to talk more about this change.

**Pull request closed without merging**
