### PR TITLE
Add retention policy support to InfluxDB provider

### PR DESCRIPTION
**Pull request by aspring**
This PR adds retention policy support to the InfluxDB provider.

### CODE REVIEW

**Comment by bflad** [comment]
@stack72 sorry to ping you directly but since you added the tags back in the day, any chance we could get this looked at/merged in please?

**Comment by aspring** [comment]
Any chance to get this evaluated and merged in?

**Comment by apparentlymart** [comment]
Hi @aspring, @bflad. Sorry for the delay here.

I am ostensibly the maintainer of this provider but since I joined Hashicorp full time my attention has been diverted elsewhere, so I apologize for letting this sit here ignored. I can't take a look at this immediately right now but I have it on my todo list and will look at it as soon as I can.

**Comment by bflad** [comment]
@aspring looks like we'll need to move this to https://github.com/terraform-providers/terraform-provider-influxdb per https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/

Please reach out if you need any help!

**Comment by apparentlymart** [comment]
Hello @aspring, and thanks for working on this!

As @bflad noted, in the Terraform 0.10 release earlier this year all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately for the reasons I noted above (changing job responsibilities) I was not able to look at this before the split, and there is unfortunately no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it.

Unfortunately at this time the InfluxDB provider has no dedicated maintainer, and so its review queue can be slow. :confounded: However, if you or someone else has the time and motivation to apply the same changes to [the `influxdb` provider repository](https://github.com/terraform-providers/terraform-provider-influxdb) and open a new PR there, I will try to take a look at it when I am able.

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Pull request closed without merging**
