### PR TITLE
[WIP] Data-driven Terraform Configuration

### PR DESCRIPTION
**Pull request by apparentlymart**
This is where I'm working on the implementation of the proposal from #4169.

* [x] `DataSource` type in the config module
* [x] Loading of `data` blocks from configuration files
* [ ] Validation of `data` blocks
* Interpolation variables of the form `data.TYPE.NAME.ATTR`, with the same multi-capabilities as resources
  * [x] Parsing (in `config` package)
  * [ ] Resolving (in `terraform` package)
* [x] Introduction of data sources in the main `terraform` module
* [x] New `RefreshData` method on the `ResourceProvider` interface
* [x] `RefreshData` support in `helper/schema`
* Graph node and eval implementations for data sources:
 * [ ] Refresh
 * [ ] Plan
 * [ ] Apply
* [ ] Change resource `count` implementation to allow any non-computed variable, which will then include attributes of any data instances that do not depend on resource creation
* [x] Backward-compatibility shim in `helper/schema`, allowing specific data source implementations to be aliased as resource implementations
  * [x] `terraform_remote_state` data source based on the existing resource, as an initial example
  * [ ] Deprecation warning when using shimmed data sources as resources
* [x] User-oriented documentation

### CODE REVIEW

**Comment by apparentlymart** [comment]
@phinze here's the same changeset but in the main repo. Feel free to pick up the reins!

I'll check in here again when things calm down for me and see if there's anything I can do to help finish this up.

**Comment by phinze** [comment]
Thanks @apparentlymart! Will dig in soon.

**Comment by stack72** [comment]
after @jen20 explained what this means, I am very excited to see it - this will mean that I can ditch so many custom modules that do lookups :)

**Comment by nickithewatt** [comment]
This functionality is much required and looking forward to it! Do we have any rough release that we think this will make it into?

**Comment by phinze** [comment]
@nickithewatt We're currently targeting 0.7 - Terraform's next major release.

Not sure on the timeline quite yet, but suffice it to say this one is high on our list of core improvements!

**Comment by apparentlymart** [comment]
I rebased this onto the `dev-0.7` branch and started a new PR #6430. Follow me over there, if you'd like! :grinning:

**Pull request closed without merging**
