### PR TITLE
[WIP] update go-ntlmssp to support domain authentication over WinRM

### PR DESCRIPTION
**Pull request by justdan96**
This just updates the dependency so that domain authentication can work over WinRM

Please let me know if you want me to update documentation as well

### CODE REVIEW

**Comment by grig-tar** [comment]
Guys, when you plan to merge this?

**Comment by lapfrank12** [comment]
Same question here, any ETA on when this could get merged? We really need this functionality after joining a domain.

**Comment by lavahot** [comment]
Any update on this? It's getting close to a year on being submitted. We really need this functionality. Local users are just not acceptable in our environment.

**Comment by ekodian** [comment]
Funny thing is that there is not confortable workaround on all theese issues with winrm + https + ntlm.
You can use constructions like this. It is basicly workarounds 'provisioner file', but you can remote-exec any script, tested from windows thou, but i think with pwsh it'll do.
%%
resource "null_resource" "myResource" {
    provisioner "local-exec" {
        command = "Copy-Item \"C:\\file.txt\" -Destination \"c:\\prov\" -ToSession $(New-PSSession -Authentication \"Negotiate\" -SessionOption (New-PSSessionOption -SkipCACheck -SkipCNCheck -SkipRevocationCheck) -ComputerName ${yandex_compute_instance.jump.network_interface.0.nat_ip_address} -UseSSL -Credential $(New-Object System.Management.Automation.PSCredential (\"${local.user}\",$(ConvertTo-SecureString \"${local.pass}\" -AsPlainText -Force))))"
        interpreter = ["Powershell", "-Command"]
    }
}
%%

**Comment by bodgit** [comment]
It looks like this dependency has already been bumped and is in version 0.12.0 onwards. There should possibly still be some sort of documentation tweak to help people avoid scratching their heads when it doesn't appear to work, i.e. domain accounts will need to use WinRM over HTTPS.

**Comment by teamterraform** [comment]
Hi folks! Now that Terraform 0.12 is released, we are undertaking a general GitHub issue/PR cleanup. 
Among other changes, we have switched to go modules so any changes need to be made in go.mod. It appears that we have since upgraded `go-ntlmssp` to a new version, so we will close this PR. Please do not hesitate to open a new PR or issue in the future, and thank you!

**Pull request closed without merging**
