### PR TITLE
Better comparison of compose files

### PR DESCRIPTION
**Pull request by raphink**
Comparing YAML files by string is not reliable. This commit interprets the compose files (using Docker's libcompose) and performs a DeepEqual comparison of the resulting structures.

### CODE REVIEW

**Comment by mcanevet** [comment]
Tested and approved!

**Comment by raphink** [comment]
@stack72 good for you?

**Comment by stack72** [comment]
Hi @raphink 

This fails the build - if you can look atthat, then we can merge

Paul

**Comment by raphink** [comment]
@stack72 Ah yes, the vendoring. I'll try and add libcompose to the PR.

**Comment by raphink** [comment]
Fixed the deps and build is now :green_heart:

**Comment by stack72** [comment]
amazing! Thanks so much :)

**Pull request merged**
