### PR TITLE
provider/google: Fix service scope update bug

### LINKED ISSUE #3586: google provider crashes when removing a service_account scope from an instance
Steps to reproduce:

1. Create an instance with the scopes `["storage-ro", "compute-rw"]`.
2. Remove the `compute-rw` scope.
3. Run `terraform plan` and it crashes

The specific problem is a nil string at `google/resource_compute_instance.go:225`. I'm seeing this both with the latest release of Terraform and building from the `master` branch.

Crash.log and terraform.tfstate are here: https://gist.github.com/dimfeld/9acc2d18f367a975dcc9

### PR DESCRIPTION
**Pull request by lwander**
Fixes #3586

### CODE REVIEW

**Comment by dimfeld** [comment]
I just tried with the patch, and it doesn't crash, but I do get the following error when removing a scope now:
```
Error applying plan:

1 error(s) occurred:

* google_compute_instance.test-instance: diffs didn't match during apply. This is a bug with Terraform and should be reported.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by dimfeld** [comment]
Just guessing, but this might be because the scope becomes blank instead of disappearing completely:
```
-/+ google_compute_instance.test-instance
   <SNIP>
    service_account.0.scopes.#:                 "2" => "1" (forces new resource)
    service_account.0.scopes.1632638332:        "https://www.googleapis.com/auth/devstorage.read_only" => "https://www.googleapis.com/auth/devstorage.read_only" (forces new resource)
    service_account.0.scopes.299962681:         "https://www.googleapis.com/auth/compute" => "" (forces new resource)
```

**Comment by lwander** [comment]
Yes, you're right - I'm closing this because this seems to be a deeper issue with `StateFunc`.

**Comment by dimfeld** [comment]
Ok, thanks for looking into it. This isn't urgent for me so no hurry :)

**Pull request closed without merging**
