### PR TITLE
Vendored WAF

### PR DESCRIPTION
**Pull request by optimisticanshul**
@radeksimko As discussed in #8705 This PR vendor WAF of aws sdk.
I will close the #8705 once we complete all the checkpoints.

### CODE REVIEW

**Comment by stack72** [comment]
Hi @optimisticanshul 

Can you add the vendored WAF as of the 1.4.7 release of the SDK? This means we are going to be following the same release as the other pieces of the SDK

Thanks

Paul

**Comment by optimisticanshul** [comment]
Hi Paul sorry for stupid question but can you please elaborate what needs
to be done here.

**Comment by apparentlymart** [comment]
Hi @optimisticanshul,

I believe @stack72 was suggesting to upgrade the existing vendoring of the whole of the AWS SDK to 1.4.7, rather than just adding the WAF service package within the version we were already running.

I'm not sure if there are some specific steps to deal with this for the AWS provider, but usually when upgrading packages we'd do something like this:

```
govendor fetch github.com/aws/aws-sdk-go
```

We like to upgrade upstream libraries in whole so that we don't get any unexpected friction between the parts and so we can more easily reason about what version we're currently running compared to the upstream.

**Comment by stack72** [comment]
Hi @optimisticanshul (and @apparentlymart)

The command I run for a specific tag is as follows:

```
 govendor fetch github.com/aws/aws-sdk-go/...@v1.4.7
```

If you can, please ensure the WAF vendor updates are of the same tag 

Paul

**Comment by optimisticanshul** [comment]
@stack72 Updated ready for another review 👍

**Comment by radeksimko** [comment]
👍

**Pull request merged**
