### PR TITLE
provider/fastly add origin shielding

### LINKED ISSUE #8279: provider/fastly: Support for origin shielding
Fastly supports [Origin Shielding](https://docs.fastly.com/guides/performance-tuning/shielding) to gain performance benefits by utilizing Fastly's POP as a shield node. 

According to Fastly's API Documentation, it seems [possible](https://docs.fastly.com/api/config#backend) to configure shield variable via an existing API endpoint.
#### More info
- Fastly Documentation: [About Fastly's Origin Shielding features](https://docs.fastly.com/guides/about-fastly-services/about-fastlys-origin-shielding-features)
- Fastly Documentation: [Shielding](https://docs.fastly.com/guides/performance-tuning/shielding)

### PR DESCRIPTION
**Pull request by travertischio**
Adds option to set origin shielding in fastly backend

Closes #8279

### CODE REVIEW

**Comment by stack72** [comment]
Hi @travertischio 

thanks for all the work here - this LGTM! All the tests pass as expected

```
% make testacc TEST=./builtin/providers/fastly
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/12/12 22:11:16 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/fastly -v  -timeout 120m
=== RUN   TestAccFastlyIPRanges
--- PASS: TestAccFastlyIPRanges (1.48s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccFastlyServiceV1CacheSetting_basic
--- PASS: TestAccFastlyServiceV1CacheSetting_basic (39.61s)
=== RUN   TestAccFastlyServiceV1_conditional_basic
--- PASS: TestAccFastlyServiceV1_conditional_basic (17.70s)
=== RUN   TestFastlyServiceV1_FlattenGzips
--- PASS: TestFastlyServiceV1_FlattenGzips (0.00s)
=== RUN   TestAccFastlyServiceV1_gzips_basic
--- PASS: TestAccFastlyServiceV1_gzips_basic (43.75s)
=== RUN   TestFastlyServiceV1_BuildHeaders
--- PASS: TestFastlyServiceV1_BuildHeaders (0.00s)
=== RUN   TestAccFastlyServiceV1_headers_basic
--- PASS: TestAccFastlyServiceV1_headers_basic (38.69s)
=== RUN   TestAccFastlyServiceV1RequestSetting_basic
--- PASS: TestAccFastlyServiceV1RequestSetting_basic (18.12s)
=== RUN   TestAccFastlyServiceV1_s3logging_basic
--- PASS: TestAccFastlyServiceV1_s3logging_basic (36.96s)
=== RUN   TestAccFastlyServiceV1_s3logging_s3_env
--- PASS: TestAccFastlyServiceV1_s3logging_s3_env (16.12s)
=== RUN   TestResourceFastlyFlattenDomains
--- PASS: TestResourceFastlyFlattenDomains (0.00s)
=== RUN   TestResourceFastlyFlattenBackend
--- PASS: TestResourceFastlyFlattenBackend (0.00s)
=== RUN   TestAccFastlyServiceV1_updateDomain
--- PASS: TestAccFastlyServiceV1_updateDomain (40.29s)
=== RUN   TestAccFastlyServiceV1_updateBackend
--- PASS: TestAccFastlyServiceV1_updateBackend (37.71s)
=== RUN   TestAccFastlyServiceV1_basic
--- PASS: TestAccFastlyServiceV1_basic (14.84s)
=== RUN   TestAccFastlyServiceV1_disappears
--- PASS: TestAccFastlyServiceV1_disappears (8.85s)
=== RUN   TestAccFastlyServiceV1_VCL_basic
--- PASS: TestAccFastlyServiceV1_VCL_basic (37.94s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/fastly	352.070s
```

Thanks

Paul

**Comment by rlunardelli** [comment]
I keep getting errors on this feature say the shield POP does not exist. Could someone shed some light on the proper usage...

`
backend {
    name = "some name"
    address = "some address"
    port = 80
    shield = "Denver" <= I've tried many things ("DEN", "denver", denver, "Denver", "DENVER")
}
`

**Comment by hobara** [comment]
It seems we'll have to pass in this format to enable shielding: Ex) "den-co-us" for Denver, "hnd-tokyo-jp" for Tokyo Haneda.

**Comment by hobara** [comment]
In case, anybody is looking for the other POP names to enable shielding. 
Here is the list - as of Sep 19, 2018. 

```{
  "Europe": {
    "Amsterdam":             "amsterdam-nl",
    "Frankfurt":             "frankfurt-de",
    "Frankfurt - Interxion": "hhn-frankfurt-de",
    "Helsinki":              "hel-helsinki-fi",
    "London - LCY":          "london_city-uk",
    "London - Slough":       "london-uk",
    "Madrid":                "mad-madrid-es",
    "Paris":                 "cdg-par-fr",
    "Stockholm":             "stockholm-bma"
  },

  "North America": {
    "Ashburn":       "iad-va-us",
    "Ashburn - DCA": "dca-dc-us",
    "Atlanta":       "atl-ga-us",
    "Atlanta - PDK": "pdk-ga-us",
    "Boston":        "bos-ma-us",
    "Chicago":       "mdw-il-us",
    "Dallas":        "dallas-tx-us",
    "Denver":        "den-co-us",
    "Los Angeles":   "lax-ca-us",
    "Miami":         "miami-fl-us",
    "Montreal":      "yul-montreal-ca",
    "New York City": "jfk-ny-us",
    "Palo Alto":     "pao-ca-us",
    "San Jose":      "sjc-ca-us",
    "Seattle":       "sea-wa-us",
    "Toronto":       "yyz-on-ca",
  },

  "Asia Pacific": {
    "Auckland":          "auckland-akl",
    "Brisbane":          "brisbane-au",
    "Fujairah Al Mahta": "fjr-ae",
    "Hong Kong":         "hongkong-hk",
    "Melbourne":         "melbourne-au",
    "Osaka":             "osaka-jp",
    "Perth":             "perth-au",
    "Singapore":         "singapore-sg",
    "Tokyo":             "tyo-tokyo-jp",
    "Tokyo - HND":       "hnd-tokyo-jp",
    "Tokyo - NRT":       "tokyo-jp2",
    "Wellington":        "wellington-wlg"
  },

  "South Africa": {
    "Cape Town":    "cpt-capetown-za",
    "Johannesburg": "jnb-johannesburg-za"
  },

  "South America": {
    "Sao Paulo": "gru-br-sa"
  }
}

**Pull request merged**
