### PR TITLE
provisioner/chef: fixes issue #2872

### LINKED ISSUE #2872: Cannot use vars for chef provisioner bool arguments
```sh
variable "skip_chef_install" {
  default = true
}

resource "aws_instance" "foo" {
  ...
  provisioner "chef" {
    ...
    skip_install = "${var.skip_chef_install}"
    ...
  }
  ...
}
```

```console
$ terraform plan --module-depth=-1
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * aws_instance.foo: 1 error(s) decoding:

* cannot parse 'skip_install' as bool: strconv.ParseBool: parsing "${var.skip_chef_install}": invalid syntax
```

### PR DESCRIPTION
**Pull request by svanharmelen**
Still not a 100% fix, but that would require some more hacking in core TF. If time permits I’ll have a look at that later on… But for now this is a good fix to be able to close #2872

### CODE REVIEW

**Comment by svanharmelen** [comment]
@catsby if you have a sec to glance over this one to that would be create... Thx!

**Comment by svanharmelen** [comment]
Merging this one as it doesn't touch any code outside the Chef provisioner and it fixes an open bug...

**Comment by catsby** [comment]
Sorry I didn't get to reviewing these before :frowning:

**Comment by svanharmelen** [comment]
@catsby no problem! This was a very small fix so a review was hardly worth the effort anyway... Otherwise I've wouldn't have merged it of course :wink:

**Pull request merged**
