### PR TITLE
provider/aws: Add resource_aws_organization.

### PR DESCRIPTION
**Pull request by asedge**
First attempt at writing my own resource for #12337.

Still needs tests.
I should probably also update the docs/website.

I won't deny I have very little idea about what I'm doing besides looking at other resources as examples and trying to do what they do.  Open to suggestions.

### CODE REVIEW

**Comment by asedge** [comment]
I think this is ready for review.  Please let me know if it looks OK, thanks!

**Comment by asedge** [comment]
I am writing a resource to manage `aws_organization_account`.  When TF tried to create the account after creating the Organization I got this error `FinalizingOrganizationException`.
> AWS Organizations could not finalize the creation of your organization. Try again later. If this persists, contact AWS customer support. 

Unfortunately, the `CreateOrganization` request returns immediately so there's no status to poll when using `WaitForState()`.  Do you have any recommendations on how best to handle this?

**Comment by asedge** [comment]
@radeksimko Any opinion on how best to handle the `FinalizingOrganizationException`?  I was thinking that I could use `waitForState()` during the `CreateAccount()` for the `aws_organization_account` resource I'm making but other resources that depend on the organization existing will need to implement the same behavior.  Just looking for a suggestion and hoping I can get this resource closed so I can finish  `aws_organization_account`.  Thanks!

**Comment by asedge** [comment]
@radeksimko Do you have any feedback on this?  I have another resource I would like to submit soon but wanted to get this one merged in first.  Thanks!

**Comment by asedge** [comment]
Thanks @MrGossett!

**Comment by lstolyarov** [comment]
@radeksimko do you have any updates on this?

**Comment by asedge** [comment]
I reopened this PR under the new provider repository for AWS: https://github.com/terraform-providers/terraform-provider-aws/pull/903. Hopefully it can get merged over there.

**Pull request closed without merging**
