### PR TITLE
[WIP] Add `name_prefix` to more resources

### LINKED ISSUE #6099: Support name prefix everywhere
I generally try to use `name_prefix` instead of `name` where possible, but not all resources support `name_prefix`. For example, `aws_security_group` does but `aws_iam_role` does not. It would be great to have support for `name_prefix` everywhere that `name` is supported.

### PR DESCRIPTION
**Pull request by joshuaspence**
Closes #6099. I need to extend this change to other AWS resources, but I wanted to request some additional feedback as I am a new contributor to Terraform.

### CODE REVIEW

**Comment by jen20** [comment]
Hi @joshuaspence! It looks like there is quite a lot of whitespace diff in this commit - is there a reason for that? Apart from that and the build errors currently reported by Travis (which look potentially like a missing import) this looks like positive progress!

**Comment by joshuaspence** [comment]
I ran `make fmt` and it touched a lot of files in the `vendor/` directory... is this expected?

**Comment by jen20** [comment]
@joshuaspence yes sadly, `make fmt` has not been correctly updated for vendoring yet. Is this work now considered complete (modulo build errors)?

**Comment by joshuaspence** [comment]
I'm going to split this up into smaller PRs.

**Pull request closed without merging**
