### PR TITLE
Initial Joyent SDC implementation

### PR DESCRIPTION
**Pull request by kiasaki**
_This is a WIP_

I am trying out and benchmarking few cloud providers at the moment and I already use Terraform for what we currently have in AWS and really enjoy it.

This is a first try at implementing a new provider, I based myself from the DigitalOcean implementation, if some core member or somebody could comment and point out my wrongs I'd be happy to address them!

At the moment all fields are in `ForceNew: true` because I also need to build the [Go client](https://github.com/kiasaki/go-sdc) at the same time.

Todo list:

- [x] Machine Read
- [x] Machine Create supporting [all](https://github.com/kiasaki/go-sdc/blob/master/machines.go#L48) parameters
- [x] Machine Destroy
- [ ] Machine Update: Rename
- [ ] Machine Update: Resize
- [ ] Machine Update: Enable/Disable firewall
- [ ] Machine Update: Update Metadata
- [ ] Machine Update: Update Tags

In a separate PR I will tackle more _resources_ (mainly Firewalls)

### CODE REVIEW

**Comment by kiasaki** [comment]
Acceptance tests pass given a valid SDC_URL, SDC_ACCOUNT, SDC_KEY_ID and SDC_KEY

```
--- PASS: TestAccSDCMachine_Basic (147.94s)
PASS
ok      github.com/kiasaki/terraform/builtin/providers/sdc      147.953s
```

**Comment by mitchellh** [comment]
This is looking really awesome. Ping us when its ready for more review!

**Comment by MerlinDMC** [comment]
@kiasaki I have a usable SDC provider in my fork as well - not feature complete but was used to create/update/destroy production environments.

https://github.com/MerlinDMC/terraform/tree/feature/add_sdc_provider

**Comment by jgrowl** [comment]
I'm really excited for this feature. :thumbsup:

**Comment by josephholsten** [comment]
@kiasaki are you still working on this? is there anything we can wrap up to make this usable?

**Comment by MerlinDMC** [comment]
@josephholsten if you want to try one out https://github.com/MerlinDMC/terraform/tree/feature/add_sdc_provider/builtin/providers/sdc just rebased has Instance create, update, destroy including support for metadata and tags

Acceptance tests assume running in the ams-1 datacenter (hardcoded network UUIDs) but other than that the tests pass.

It is using the official Joyent cloudapi golang client so in theory should be easier to extend as the cloudapi client is already there :)

**Comment by phinze** [comment]
Hey folks. Going to close this for inactivity. @MerlinDMC if you're willing to PR your newer implementation we can definitely get it reviewed and in. :+1:

**Comment by kiasaki** [comment]
Good call @phinze . @josephholsten yeah, sadly I the project that required me to test out SDC doesn't need it anymore and I have already many other projects, won't be able to the the final push on that one soon.

If someone want to give a try at finishing it it's just missing the update call, like stated in the checklist in the description.

**Pull request closed without merging**
