### PR TITLE
Add `executionEnabled` schema attribute to rundeck job

### PR DESCRIPTION
**Pull request by patcadelina**
I'm trying to port existing Rundeck jobs to Terraform DSL. There are a couple of things needed, so I'm starting with what seems to be basic. Feedback will be highly appreciated.

### CODE REVIEW

**Comment by jen20** [comment]
Hi @patcadelina. Thanks for submitting this, it does appear we have some missing API coverage based on the latest version. Were you able to build this locally? The upstream rundeck API package appears to be missing the `ExecutionEnabled` struct member on `JobDetail`. It's possible @apparentlymart might be able to shed some light on that!

**Comment by patcadelina** [comment]
Absolutely need some help there, I can't pinpoint what's missing.

**Comment by BobVanB** [comment]
@patcadelina Dont know if you still need this one.
But take a look at my pull request: https://github.com/hashicorp/terraform/pull/8161/files
The go-rundeck-api is mirrored in the vendor directory in terraform.

Add your option to the jobDetail in:
vendor/github.com/apparentlymart/go-rundeck-api/rundeck/job.go

But as you know, before there can be a pull request on terraform,
make shure its in go-rundeck-api first.

Currently working on terraform-rundeck,
maybe i just take the whole job xml and just put it in there at once.
This way, more ppl from terraform can work on it.

**Comment by apparentlymart** [comment]
Hello @patcadelina, and thanks for working on this!

As part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it.

There have been several improvements to the Rundeck provider since you opened this PR, so this feature may now be supported. If it's not, and if you or someone else has the time and motivation to apply same changes to [the `rundeck` provider repository](https://github.com/terraform-providers/terraform-provider-rundeck) and open a new PR there, this could potentially be merged. Unfortunately the time of writing the Rundeck provider has no dedicated maintainers, so a review may take some time. :confounded:

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Pull request closed without merging**
