### PR TITLE
provider/azurerm: Adding `azurerm_virtual_machine` resource

### PR DESCRIPTION
**Pull request by stack72**
Adds the `azurerm_virtual_machine` resource. We currently have tests for basic linux and windows machines. More tests will be added later. This is the initial work that will allow us to create machines :)

### CODE REVIEW

**Comment by avdhoot** [comment]
Any progress? any ETA. Please guys. :(

**Comment by jen20** [comment]
Acceptance test run:

```
make testacc TEST=./builtin/providers/azurerm TESTARGS="-run TestAccAzureRMVirtualMachine"
==> Checking that code complies with gofmt requirements...
/Users/James/Code/go/bin/stringer
go generate $(go list ./... | grep -v /vendor/)
TF_ACC=1 go test ./builtin/providers/azurerm -v -run TestAccAzureRMVirtualMachine -timeout 120m
=== RUN   TestAccAzureRMVirtualMachine_basicLinuxMachine
--- PASS: TestAccAzureRMVirtualMachine_basicLinuxMachine (592.77s)
=== RUN   TestAccAzureRMVirtualMachine_basicWindowsMachine
--- PASS: TestAccAzureRMVirtualMachine_basicWindowsMachine (851.18s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/azurerm	1443.968s
```

**Comment by jen20** [comment]
This LGTM @stack72! I've rebased it and merged to master and will push shortly.

**Comment by jen20** [comment]
Landed in and: 808ce45, 4db3242, cb10904.

Thanks @stack72 - this is _great_ work on this API!

**Comment by lmeyemezu** [comment]
Hi,
is Azure RM virtual machine yet available?
Regards

**Comment by stack72** [comment]
Hi @lmeyemezu,

This has already been merged and will be made available in Terraform 0.6.14

Paul

**Comment by lmeyemezu** [comment]
Hi  @stack72 ,
Thanks.

**Pull request merged**
