### PR TITLE
provider/aws: send Terraform version in User-Agent

### PR DESCRIPTION
**Pull request by phinze**

### CODE REVIEW

**Comment by radeksimko** [comment]
Closes https://github.com/hashicorp/terraform/issues/5020

Do you think it would make sense to make this optionally/partially modifiable via ENV variable, so that other tools using Terraform, like Atlas can also add their version there or you think it's not worth it or there isn't much value in knowing what Atlas version was used per request?

**Comment by phinze** [comment]
> Do you think it would make sense to make this optionally/partially modifiable via ENV variable

Sure, wouldn't hurt!

**Comment by radeksimko** [comment]
Also as this is now overriding the original value (AWS Go SDK version), do you think there is value in putting it back into the full string?

So that the full User-Agent string would contain:

1. (optional) Atlas/3rd party tool version that is using Terraform
2. Terraform version
3. AWS Go SDK version

I'm not sure if the version is nicely exposed from the SDK though...

**Comment by phinze** [comment]
@radeksimko it's not overriding, current user agent string looks like:

```
User-Agent: aws-sdk-go/1.1.2 (go1.6; darwin; amd64) terraform/0.6.13 (dev)
```

**Comment by radeksimko** [comment]
> it's not overriding

right, because of `PushBackNamed`... that's good then, so the optional part can be handled the same way I assume?

**Comment by jen20** [comment]
Potential bikeshedding, do we want to put `terraform/version` before `aws-sdk-go/version`? Otherwise LGTM!

**Comment by phinze** [comment]
Ok:

 * Moved to `PushFront` so TF version shows up before aws-sdk-go version
 * Going to hold off on external customizability since it's slightly trickier than a one-liner and I'd like to land this now.

**Pull request merged**
