### PR TITLE
Add a `kubernetes_service` resource

### PR DESCRIPTION
**Pull request by dasch**
This is an attempt at implementing part of https://github.com/hashicorp/terraform/issues/13420. Note that this is the very first time I write Go code, so the quality may not live up to your standards. Help is much appreciated.

Adds a `kubernetes_service` resource with the most basic schema. If this is the right direction to go in, I can add more stuff to the schema.

### CODE REVIEW

**Comment by radeksimko** [comment]
Hi @dasch 
thanks for the contribution. `kubernetes_service` was certainly on my K8S todo list, great you picked that one up 😃 

I will have a look at the code and leave some feedback for you today. I think it will take a few more steps and effort to get it to the finish line, but I'm happy to help you get there.

**Comment by dasch** [comment]
@radeksimko oh man, I had hoped it would have been a matter of copy/pasting the existing K8s stuff and replacing a few things 😂 

Would you have time to take over the code and get it across the finish line? I won't have time for a project this size in the coming weeks (and I'd have to learn more Go...)

**Comment by radeksimko** [comment]
No probs, I can pick it up - it will just take me some time as I plan to focus first on some other resources, e.g. pod.

**Comment by radeksimko** [comment]
In the spirit of avoiding stale PRs which aren't waiting for any feedback anymore, do you mind me closing this? I'll ping you once in the finished PR once I have it ready.

Thanks

**Comment by dasch** [comment]
@radeksimko that's fine – thanks for the help!

**Pull request closed without merging**
