### PR TITLE
Fix issue with with Opsworks and empty Custom Cook Book sources

### LINKED ISSUE #6077: provider/aws : Opsworks fails on update
Opsworks fails during updates:

```shell
Error applying plan:

1 error(s) occurred:

* aws_opsworks_stack.main: ValidationException: Custom Cookbooks Source's Type: Unsupported scm type
        status code: 400, request id: *snip*
```

This is due to the provider "computing" empty fields and adding it to the JSON request:

```shell
2016/04/07 19:17:06 [DEBUG] terraform-provider-aws:   CustomCookbooksSource: {
2016/04/07 19:17:06 [DEBUG] terraform-provider-aws:     Password: "",
2016/04/07 19:17:06 [DEBUG] terraform-provider-aws:     Revision: "",
2016/04/07 19:17:06 [DEBUG] terraform-provider-aws:     SshKey: "",
2016/04/07 19:17:06 [DEBUG] terraform-provider-aws:     Type: "",
2016/04/07 19:17:06 [DEBUG] terraform-provider-aws:     Url: "",
2016/04/07 19:17:06 [DEBUG] terraform-provider-aws:     Username: ""
2016/04/07 19:17:06 [DEBUG] terraform-provider-aws:   },
```

### PR DESCRIPTION
**Pull request by u2mejc**
This resolves #6077

### CODE REVIEW

**Comment by u2mejc** [comment]
I've confirmed this persists with HEAD: `Terraform v0.6.15-dev (aef5bcf98227b0ac964657a29ef2a1ebeed19a51)`

I've created a simple gist to demonstrate the fix against: https://gist.github.com/u2mejc/c1613ed663daa9bd3eb8749e8a658cfd

**Comment by catsby** [comment]
Replied to https://github.com/hashicorp/terraform/issues/6077, I'd like for us to considering not making this `computed`, but instead only saving the information when there is actual a custom cookbook returned

**Comment by u2mejc** [comment]
@catsby said:
>Hey @u2mejc – do you have a simple config that demonstrates this problem? The computed flag tells Terraform that the API may return data and to not worry about it; the resource itself is not populating empty data on it's own. Or, it shouldn't :smile:

> I did some debugging, and found that the CustomCookbooksSource source that's returned from DescribeStacks call here is coming back empty, instead of the typical nil. As a result we're storing empty values when we should omit it if nothing there is found. Do you think you could adjust #6078 to account for that?

Moving development discussion here so we don't get too split brained. I'm guessing you saw the example to reproduce the issue above. :point_up: 


> Replied to #6077, I'd like for us to considering not making this computed, but instead only saving the information when there is actual a custom cookbook returned

I'm not sure I understand, by `not making this computed` did you mean something different then what is already dropped in this PR? I thought Terraform was populating the empty strings intentioanlly when computed based on inline comments like [this](https://github.com/hashicorp/terraform/blob/d1ac7d3b2e1be2f32092275340f33a2d73f7b31a/helper/schema/resource_data.go#L51):
```
// If the key does exist in the schema but doesn't exist in the configuration,
// then the default value for that type will be returned. For strings, this is
// "", for numbers it is 0, etc.
```
Is that not what's expected?

**Comment by u2mejc** [comment]
@catsby I'm happy to be able to help, getting Terraform to fully support OpsWorks is aligned with my current sprint. But I'm not super familiar with the code base. Can you please give a little more context around your ask, I'll be happy to work on the code for you then. :+1:

**Comment by u2mejc** [comment]
@apparentlymart I was wondering if you could look at this PR? I know you're probably most intimate with it.

Use case is for creating OpsWorks stacks without custom repos, namely for recipes that are all available in the supermarket. I think this change is pretty straightforward, can you think of a use case this wouldn't work?

**Comment by apparentlymart** [comment]
@u2mejc I'm not sure exactly what @catsby was getting at here, but I think what he's suggesting is that instead of changing the schema we would check for and ignore an empty cookbooks source.

So maybe [in `resourceAwsOpsworksSetStackCustomCookbooksSource`](https://github.com/hashicorp/terraform/blob/0a0ccb84f2d48b33d12e10502b7e38bdb9b315c9/builtin/providers/aws/resource_aws_opsworks_stack.go#L217) the condition would become:

```go
    if v != nil && *.v.Type != "" {
        // ...
```

This would mean that if the Opsworks API returns a the cookbooks source as a bunch of empty strings then we just keep the values we already had.

Hopefully @catsby can confirm whether that was what he was driving at.

I'm super rusty on this code so I don't have any better theories than his, but I would agree that setting it as `Computed` is probably just masking the issue by ignoring the diff, and so other related problems may still arise as a result.

**Comment by u2mejc** [comment]
Thank you Martin!

I don't believe that AWS should ever respond with computed values for custom cookbooks? But if @catsby believes it would be better to ignore Terraform creating empty strings, I'm happy to adjust the PR. 

Clint, let me know if you have time to look at this and comment or if you'd like Paul / Martin to approve it.

**Comment by catsby** [comment]
Hi friends! I'm terribly sorry to have left you hanging here. I popped in, said a thing, and then left, leaving you not unable to understand my glaring typo 😄 

> I'd like for us to considering not making this computed, but instead only saving the information when there is actual a custom cookbook returned

What I _meant_ was not changing the `computed` nature, but instead only saving data if it's non-empty. I alluded to that in my comment https://github.com/hashicorp/terraform/issues/6077#issuecomment-207613512 but I failed to speak clearly, sorry!

What I'm seeing here is that if you do not specify a custom cookbook, that the `stack.CustomCookbooksSource` still has an "empty" cookbook, which is getting saved to state. 

So, what @apparentlymart said, in that we should verify it's not nil and also contains something meaningful. I would want to triple check that this is true though (the empty value)

I hope that clears things up! I apologize again for the science

**Comment by u2mejc** [comment]
Thank you Clint!!! I'll rework the PR and shoot it back up.

**Comment by u2mejc** [comment]
@catsby Per your request, I've adjusted this PR to simply check for nil and empty string, instead of disabling the computed value.  Please let me know if there is anything else you'd like me to add. 👍

**Comment by catsby** [comment]
Excellent, thank you!

**Pull request merged**
