### PR TITLE
command: Clarify 'cloud' configuration block change message

### PR DESCRIPTION
**Pull request by uturunku1**
When you change a tag after the workspace has been initialized, executing a command like `terraform plan` or `terraform apply` will throw this error:

```
Error: Terraform Cloud initialization required, please run "terraform init"
│ 
│ Reason: Backend configuration changed from "cloud" to Terraform Cloud
│ 
│ Changes to the Terraform Cloud configuration block require reinitialization.
│ This allows Terraform to set up the new configuration, copy existing state, etc.
│ Please run "terraform init" with either the "-reconfigure" or "-migrate-state"
│ flags to use the current configuration.
│ 
│ If the change reason above is incorrect, please verify your configuration
│ hasn't changed and try again. At this point, no changes to your existing
│ configuration or state have been made.
```

In general the error is correct, one must re run `terraform init` with either the flag `-reconfigure` or `-migrate-state` after changing the cloud configuration block (because it's possible that with the change now you are pointing to a different set of a workspaces). However, what is incorrect is the second line of the error msg, the "Reason" part. The wording does not make sense because you cannot change from "cloud" to "cloud". This line is probably meant for reflecting a change from "backend" to "cloud" or "something that is not cloud" to "cloud".

I have adjusted the logic around this switch case statement that was assigning the incorrect value to "Reason" (`initReason` variable).

After the change now the error displays the correct "reason":

```
 Error: Terraform Cloud initialization required, please run "terraform init"
│ 
│ Reason: Backend configuration changed for "cloud"
│ 
│ Changes to the Terraform Cloud configuration block require reinitialization.
│ This allows Terraform to set up the new configuration, copy existing state, etc.
│ Please run "terraform init" with either the "-reconfigure" or "-migrate-state"
│ flags to use the current configuration.
│ 
│ If the change reason above is incorrect, please verify your configuration
│ hasn't changed and try again. At this point, no changes to your existing
│ configuration or state have been made.
```

After feedback from Chris, now the reason reads "Reason: Terraform Cloud configuration block changed"

### CODE REVIEW

**Review by chrisarcand — CHANGES_REQUESTED** [review]
This needs just a bit more - it's not backend configuration that's changed, and the literal `cloud` backend is nothing but an implementation detail. I would expect the reason to read something along the lines of `Terraform Cloud configuration block changed`.

**Review by nfagerlund — COMMENTED** [review]
The updated messages read well to me, and the logic makes sense. 

There's a missing case for changing _from_ TFC to a backend; do you think we should catch that in this PR as well?

**Comment by uturunku1** [comment]
@nfagerlund The missing case for changing from TFC to backend that you are referring to, would it applicable to switching from  using `cloud {}` block to `backend "s3" {}` block? If so, when I make that change in my backend config, I get this error msg which I thought it displays the correct `Reason` :

```
Error: Backend initialization required, please run "terraform init"
│ 
│ Reason: Backend configuration changed from "cloud" to "s3"
│ 
│ The "backend" is the interface that Terraform uses to store state,
│ perform operations, etc. If this message is showing up, it means that the
│ Terraform configuration you're using is using a custom configuration for
│ the Terraform backend.
│ 
│ Changes to backend configurations require reinitialization. This allows
│ Terraform to set up the new configuration, copy existing state, etc. Please run
│ "terraform init" with either the "-reconfigure" or "-migrate-state" flags to
│ use the current configuration.
│ 
│ If the change reason above is incorrect, please verify your configuration
│ hasn't changed and try again. At this point, no changes to your existing
│ configuration or state have been made.
```
Or were you referring to a different TFC to backend change?

**Comment by uturunku1** [comment]
Also, I just merged main branch into this branch and the merge brought a bunch of changes with it. That's why my "Files changed" section is now all cluttered with a lot of changes that are not mine :( Let me know if you want me to filter out that view for you. 
Do you happen to know if this backport workflow is suppose to help with updating a PR to have the latest changes from main once it gets merged? https://github.com/hashicorp/terraform/blob/main/.github/workflows/main.yml#L17 Feel free to point me to the image its referring to if you know where that lives! @nfagerlund

**Comment by uturunku1** [comment]
I made a bit of a mess here when git merging main into this branch (to get my branch up to date) and then git squashing all commits coming from main. I am closing this PR and start a new, pretty one here: https://github.com/hashicorp/terraform/pull/29967

**Pull request closed without merging**
