### PR TITLE
Upgrade go-tfe from 1.51.0 to 1.58.0

### PR DESCRIPTION
**Pull request by jbonhag**
This PR bumps the go-tfe dependency in Terraform to v1.58.0, which allows the Terraform `cloud` block to interact with workspaces that have HCP IDs.

This requires changing the mock dependency from golang/mock to go.uber.org/mock to maintain compatibility with go-tfe v1.53.0: https://github.com/hashicorp/go-tfe/pull/897 

### Why?

For Unified HCP Terraform, we create organizations, projects, and workspaces using HCP-generated external IDs (e.g. `terraform.workspace:qjRw3Pbjttz9D73mR7Rz` for a workspace) rather than a prefixed ID format (`ws-DEB5Hz2oJM2fXnBs`). This allows for greater interoperability between HCP and TFC, and also required relaxing client-side ID validation in the go-tfe library.

The go-tfe changes were made here: https://github.com/hashicorp/go-tfe/pull/924 and included in the go-tfe 1.58.0 release.

Because the Terraform `cloud` block uses go-tfe 1.51.0, Terraform is currently unable to read the current state of those workspaces. In the following example, `jbonhag-demo-1` is a unified organization, and `default-project` is a unified project synced from HCP.

main.tf:

```
terraform {
  cloud {
    organization = "jbonhag-demo-1"

    workspaces {
      project = "default-project"
      name    = "unified"
    }
  }
}
```

With Terraform 1.9.2:

```
❯ terraform init 
Initializing HCP Terraform...
╷
│ Error: Error refreshing state: error retrieving state: invalid value for workspace ID
│ 
│ 
╵
```

With proposed change:

```
❯ go build
❯ ./terraform init
Initializing HCP Terraform...
Initializing provider plugins...

HCP Terraform has been successfully initialized!

You may now begin working with HCP Terraform. Try running "terraform plan" to
see any changes that are required for your infrastructure.

If you ever set or change modules or Terraform Settings, run "terraform init"
again to reinitialize your working directory.
```

Here is where Terraform fetches the state:

https://github.com/hashicorp/terraform/blob/a72b48a7bedc427216796fec48e345e1cb1b3fad/internal/cloud/state.go#L411

And here is where go-tfe performs the subsequent workspace ID validation:

https://github.com/hashicorp/go-tfe/blob/dee5a9cfda19483a7cdf7f6728b70d0e2340168b/state_version.go#L346-L348

## Target Release

1.9.3

### ENHANCEMENTS

- The `cloud` block can now interact with workspaces that have HCP resource IDs.
- Mocks are now generated using the go.uber.org/mock package.

### CODE REVIEW

**Comment by jbonhag** [comment]
go-tfe 1.53.0 includes a change to the mocking framework, so these unit test failures will need to be resolved before merging.

**Review by jbardin — APPROVED** [review]
This changes the mocks for packages unrelated to go-tfe too, but since `github.com/golang/mock` is now deprecated in favor of `go.uber.org/mock` I don't see any reason to not change them all at once anyway.

**Review by SarahFrench — APPROVED** [review]
Approving on behalf of the `gcs` backend - the acceptance tests pass when I use this branch

**Review by jar-b — APPROVED** [review]
LGTM 🎉 

```console
% TF_ACC=1 go test -count=1 ./...
ok      github.com/hashicorp/terraform/internal/backend/remote-state/s3 207.382s
```

**Review by jackofallops — APPROVED** [review]
LGTM 👍

**Pull request merged**
