### PR TITLE
provider/alicloud: Add a new alicloud resource oss_bucket

### PR DESCRIPTION
**Pull request by xiaozhu36**
This PR add a new alicloud resource oss bucket, and this PR contains oss bucket resource provider, testcase, examples and introduction documents.

The running results of oss bucket's testcase as follows:

TF_ACC=1 go test ./alicloud -v -run=TestAccAlicloudOssBucket -timeout 120m
=== RUN   TestAccAlicloudOssBucketBasic
--- PASS: TestAccAlicloudOssBucketBasic (32.35s)
=== RUN   TestAccAlicloudOssBucketCors
--- PASS: TestAccAlicloudOssBucketCors (33.40s)
=== RUN   TestAccAlicloudOssBucketWebsite
--- PASS: TestAccAlicloudOssBucketWebsite (33.07s)
=== RUN   TestAccAlicloudOssBucketLogging
--- PASS: TestAccAlicloudOssBucketLogging (36.72s)
=== RUN   TestAccAlicloudOssBucketReferer
--- PASS: TestAccAlicloudOssBucketReferer (39.26s)
=== RUN   TestAccAlicloudOssBucketLifecycle
--- PASS: TestAccAlicloudOssBucketLifecycle (32.20s)
PASS
ok      github.com/alibaba/terraform-provider/alicloud  207.031s

### CODE REVIEW

**Comment by stack72** [comment]
@xiaozhu36 please can you rebase this against master? It seems merging your other PRs has caused a conflict

**Comment by xiaozhu36** [comment]
Hi @stack72 

Thank you for your feedback. I have solve the conflict of the PR, and please check it, thanks.

Regards,
Guimin He

**Comment by stack72** [comment]
Hi @xiaozhu36 

Please could you reopen this PR against the new terraform-provider-alicloud repo? https://github.com/terraform-providers/terraform-provider-alicloud

Thanks

Paul

**Comment by xiaozhu36** [comment]
Hi @stack72 

I have reopened this PR against the new terraform-provider-alicloud repo, and please check it, thanks.

Regards,
Guimin

**Pull request closed without merging**
