### PR TITLE
provider/aws: Add cloudformation_stack data source

### PR DESCRIPTION
**Pull request by radeksimko**
### Test plan

```
make testacc TEST=./builtin/providers/aws TESTARGS='-run=AWSCloudFormationStack_dataSource'
```
```
TF_ACC=1 go test ./builtin/providers/aws -v -run=AWSCloudFormationStack_dataSource -timeout 120m
=== RUN   TestAccAWSCloudFormationStack_dataSource_basic
--- PASS: TestAccAWSCloudFormationStack_dataSource_basic (87.58s)
PASS
ok     	github.com/hashicorp/terraform/builtin/providers/aws   	87.597s
```

### CODE REVIEW

**Comment by apparentlymart** [comment]
This is a neat idea! Seems like it makes cloudformation stacks act a bit like `terrafrom_remote_state`s in that you can derive resources from them, so could use cloudformation to build some foundational stuff and then use it within Terraform.

I don't really know cloudformation enough (at all!) to be of much use in reviewing this in detail, but the general mechanism/flow looks reasonable to me.

**Comment by jen20** [comment]
:+1: This is a great idea! Going to look at pulling it in now.

**Comment by jen20** [comment]
```
$ make testacc TEST=./builtin/providers/aws TESTARGS="-run TestAccAWSCloudFormationStack_dataSource_basic"
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/09/03 14:13:10 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run TestAccAWSCloudFormationStack_dataSource_basic -timeout 120m
=== RUN   TestAccAWSCloudFormationStack_dataSource_basic
--- PASS: TestAccAWSCloudFormationStack_dataSource_basic (66.45s)
PASS
ok     	github.com/hashicorp/terraform/builtin/providers/aws   	66.471s
```

Thanks @radeksimko!

**Comment by mwarkentin** [comment]
@radeksimko This is awesome - I was just wondering if there's a reason the "Resources" part of the stack isn't available? Seems like it'd be useful:



I suppose that's potentially more dynamic than the rest of the stack?

**Comment by radeksimko** [comment]
@mwarkentin I can't think of a particular reason, as long as it's available via the API/SDK it makes sense to expose it. PRs welcomed. 😉

**Comment by mwarkentin** [comment]
@radeksimko Thanks - looks like they are: http://docs.aws.amazon.com/sdk-for-go/api/service/cloudformation/#example_CloudFormation_ListStackResources

Will open a separate issue - not sure if this is something I'd be able to tackle at this point (very golang noob), but could be a good learning experience. :)

**Pull request merged**
