### PR TITLE
Deletions in the config package

### PR DESCRIPTION
**Pull request by pselle**
Continuing to pull out smaller parts of #23682, this implements some deletions in the `config` package.

### CODE REVIEW

**Comment by pselle** [comment]
@mildwonkey Great point! All that function was doing now was a type conversion, so I've lifted it out and deleted the func (moved the comment along with)

**Comment by jbardin** [comment]
The `config` package is not used any longer, except in one particular spot in core. I think the idea there was to leave it alone and delete the entire package at once (which IIRC we can do once we remove `helper/schema` and `builtin/providers/test`)

**Comment by pselle** [comment]
@jbardin Thanks! I was wondering about the state. I'll merge this though, but noted on any further `config` package spelunking (not to be prioritized over other packages)

**Comment by jbardin** [comment]
Looks like it's going to be a fairly large cleanup too, all associated around the removal of `terraform.ResourceConfig`, which is the last type that needs that package.

**Pull request merged**
