### PR TITLE
Openstack docs fixes

### PR DESCRIPTION
**Pull request by supaspoida**
Was having a hard time reading & finding the new OpenStack docs, this should fix it up.

### CODE REVIEW

**Comment by phinze** [comment]
Nice - thanks for this! Think you could give this a quick rebase for me?

**Comment by phinze** [comment]
@supaspoida were you going to resubmit as a new PR? If you're strapped for time - happy to pick up the rebase over on this side. Just let me know! :ok_hand:

**Comment by supaspoida** [comment]
When I rebased onto master it looks like my commits were dropped, and I'm seeing the correct changes in master now. Looks like someone beat me to it!

**Comment by phinze** [comment]
Ah cool. Sounds good. Thanks again!

**Pull request closed without merging**
