### PR TITLE
Terraform Microsoft AD Provider by GSLab

### PR DESCRIPTION
**Pull request by idmsubs**
Please review code changes implemented for Microsoft’s Active Directory Provider and resources.

Resources implemented are : 
a.	AD Entry Management (Add entry and delete entry)

Referred https://github.com/hashicorp/terraform/blob/master/.github/CONTRIBUTING.md for following standards for Terraform provider.

Please suggest changes if required any.

### CODE REVIEW

**Comment by idmsubs** [comment]
Please review code changes implemented for Microsoft’s Active Directory Provider and resources.

Resources implemented are : 
a.	AD Entry Management (Add entry and delete entry)

Referred https://github.com/hashicorp/terraform/blob/master/.github/CONTRIBUTING.md for following standards for Terraform provider.

Please suggest changes if required any.

**Comment by fkgre** [comment]
+1

**Comment by idmsubs** [comment]
With recent Terraform release and new provider changes, require to create new PR with individual provider repo. Closing this PR.

**Comment by catsby** [comment]
Hey @idmsubs was this migrated to another repo? If so, please share a link. Thanks!

**Comment by idmsubs** [comment]
@catsby yes required due to latest terraform changes with v0.10 release. We will be opening new PR soon which will work with new release. Thank you for interest in provider :) 

Will share new PR link over here.

**Comment by bhushan-rane** [comment]
@catsby @fkgre Please visit https://github.com/GSLabDev/terraform-provider-ad for updated implementation of Terraform AD Provider.

**Pull request closed without merging**
