### PR TITLE
Adding new function interpolationFuncZipMapSet

### PR DESCRIPTION
**Pull request by luizfeliperj**
With this new builtin function it would be possible to create an on demand list of maps, like the one below:

      authorized_networks = [ "${zipmapset(list("name","value"), var.ip, formatlist("%v/32", var.ip))}" ]

authorized_networks requires a list of maps like in below:

     authorized_networks = [ { name: xx, value: yy} , { name: foo, value: bar } ]

This patch makes it simpler to create such a list from an array.

### CODE REVIEW

**Comment by apparentlymart** [comment]
Hi @luizfeliperj! Thank you for working on this.

In the next major version of Terraform we are planning to introduce a generalized syntax for doing this sort of transformation, like this:

```hcl
# (not yet implemented and details may change before final release)
  dynamic "authorized_networks" {
    for_each = var.networks
    content {
      name  = authorized_networks.key
      value = authorized_networks.value
    }
  }
```

This would expand out to one `authorized_networks` block for each item in that `var.networks` map.

We're also adding an expression-level construct that allows for some similar behavior with lists and maps, rather than for nested blocks:

```hcl
# (not yet implemented and details may change before final release)
  example = [
    for k, v in var.any_map: {
      name  = k
      value = v
    }
  ]
```

This construct is not appropriate for `authorized_networks`, because it is a nested configuration block rather than an attribute, but could be used in contexts where a list or map needs to be constructed by transforming another list or map. These two constructs can even be used together by assigning a transform expression like the latter to the `for_each` attribute of the `dynamic "authorized_networks"` block.

Do you think these features will meet your use-case, or does `zipmapset` provide some additional functionality that this construct would not?

Thanks again for working on this! It looks like good work, but we're hoping that these new features described above will avoid the need to have so many different functions for specific transformations from lists into maps and vice-versa.

**Comment by luizfeliperj** [comment]
If I understood the syntax right, in both cases a list of maps are expected as input.
The question is how one is supposed to create this list of map values from a couple of array, let's suppose:

names = [ "foo", "bar" ]
values = [ "value1", "value2" ]

How could I get a result like this:

result = [ { "name":"foo" , "value":"value1" }, { "name:bar", "value":"value2"} ]

Using the examples given?

**Comment by apparentlymart** [comment]
If the names and values are provided as two separate lists of the same length then I'd first turn them into a map using `zipmap` and then proceed as before:

```hcl
# (not yet implemented)
result = [
  for k, v in zipmap(var.names, var.values): {
    name  = k
    value = v
  }
]
```

The above does not preserve the order of the lists given because maps are not ordered. In the rarer case where the order is significant, the following (admittedly less readable) approach should work:

```hcl
# (not yet implemented)
result = [
  for i, n in var.names: {
    name  = n
    value = var.values[i]
  }
]
```

The collection provided to both the `for` expression (as shown here) and to the `for_each` argument for the `dynamic` block can be either a list or a map. If a list is passed, the iteration is over the list element indexes and the corresponding values. If a map is passed, the iteration is over the map keys and their corresponding values.

**Comment by luizfeliperj** [comment]
The first example would not work if a name needs to be mapped to multiple values or a third parameter, like an user expiration date, would need to be given.

The second example would work for all the use cases I can imagine right now.

**Comment by luisdavim** [comment]
I see a lot of these comments on PRs saying that this will be implemented in a future version of hcl but there's little information about this new version and when it will be available...

**Comment by apparentlymart** [comment]
The new configuration language implementation will be included in the next major release.

**Comment by luizfeliperj** [comment]
IMHO, my PR won't hurt if accepted, it would be just another way to archive the same thing, the good thing is we would not need to wait for the next major release to have this feature running.

**Comment by luisdavim** [comment]
when is the next major release happening? @apparentlymart ?

**Comment by mildwonkey** [comment]
Hi folks, sorry for the long silence here! Now that terraform 0.12 has been released, the functions have been rewritten. The `config` package is deprecated and all functions live in `lang/funcs`. Also, as martin mentioned, this feature is supported directly, plus there is a new [`zipmap()`](https://www.terraform.io/docs/configuration/functions/zipmap.html) function. 

I am going to close this PR now - thank you for submitting it!

**Pull request closed without merging**
