### PR TITLE
implements gzip interpolation func

### LINKED ISSUE #3407: feature request: new built-in function gzip(string)
Maybe this is a little bit opinionated but here it is.

Recently I run into an issue with cloud-config (yes, again (: ), and I solved it with a gzip function. I use GCE for deploying my machines and the maximum size for metadata is 32KB. I was deploying a whole Kubernetes cluster using CoreOS and cloud-config but when I tried to create the kube-master (which requires a bunch of files -certs,keys,cfgs-) it suddenly failed: `fileSizeTooLarge`.

Probably the best way to create this kind of clusters is to refer to a google cloud storage which contains everything I need and load them when booting but:
- It's not as portable as a unique cloud-config file
- and, it has dependencies I would like to avoid

Having a gzip built-in interpolation function solved my problem, I'm using it like this:

```
resource "template_file" "kube-master-userdata" {
    filename = "${format("%s/%s", path.module, "files/kube-master.yml")}"
    vars {

        #
        # parameters
        #

        dns-service-ip   = "10.3.0.10"
        etcd-endpoints   = "${var.etcd-endpoints}"
        service-ip-range = "10.3.0.0/24"
        pod-network      = "10.2.0.0/16"
        fleet-metadata   = "${var.kube-master-tags}"

        #
        # files
        #

        ca-cert               = "${base64encode(gzip(file(var.file-ca-cert)))}"
        api-server-cert       = "${base64encode(gzip(file(var.file-kube-api-server-cert)))}"
        api-server-key        = "${base64encode(gzip(file(var.file-kube-api-server-key)))}"
        etcd-ca-cert-file     = "/etc/ssl/etcd/ca.pem"
        etcd-ca-cert          = "${base64encode(gzip(file(var.file-kube-master-etcd-ca-cert)))}"
        etcd-client-cert-file = "/etc/ssl/etcd/client.pem"
        etcd-client-cert      = "${base64encode(gzip(file(var.file-kube-master-etcd-client-cert)))}"
        etcd-client-key-file  = "/etc/ssl/etcd/client.key.pem"
        etcd-client-key       = "${base64encode(gzip(file(var.file-kube-master-etcd-client-key)))}"
    }
}
```

And then in the cloud-config template like this:

```
[...]

  - path: "${etcd-client-key-file}"
    permissions: "0644"
    encoding: "gzip+base64"
    content: |
      ${etcd-client-key}

[...]
```

WDYT, is it worth it?

### PR DESCRIPTION
**Pull request by glerchundi**
fixes #3407 

Signed-off-by: Gorka Lerchundi Osa glertxundi@gmail.com

### CODE REVIEW

**Comment by glerchundi** [comment]
In case you feel it can be merged, here it is the PR. You can take a look to these use cases:

For **etcd2**:
https://github.com/glerchundi/infrastructure-etcd2/blob/master/etcd.tf#L69-L78
For **kubernetes**:
https://github.com/glerchundi/infrastructure-kubernetes/blob/master/kubernetes.tf#L182-L190

Ignore the old-fashioned `base64enc` (in favor or `base64encode`) because we're using a hand-made terraform binary yet.

**Comment by apparentlymart** [comment]
Interesting...

I think this would be the first time we explicitly encouraged having raw binary data interpolated in Terraform. Technically it has always been possible to read binary data using `file(...)` but in practice I think most use-cases for it were to load text-based files.

If it is always used inside `base64` to create something text-friendly again then I guess it could be fine, but in cases where `base64` isn't used I wonder how well/badly this would interact with the JSON serialization of Terraform states, since JSON doesn't explicitly support non-text strings. Did you try some cases without `base64`?

**Comment by glerchundi** [comment]
> If it is always used inside base64 to create something text-friendly again then I guess it could be fine, but in cases where base64 isn't used I wonder how well/badly this would interact with the JSON serialization of Terraform states, since JSON doesn't explicitly support non-text strings. Did you try some cases without base64?

I cannot figure out any use-case in which this can be used without base64ing or encoding in whatever form. At least I have not found in the position.

Thanks for the quick response.

**Comment by glerchundi** [comment]
@apparentlymart, I found that sooner or later #3846 & #3909 are going to be merged. If this is the direction Terraform is going to take regarding to local resource management, I can imagine another use case in which this would be useful. Imagine you want to save files in a storage service (s3, gcs or whatever) and you want to make them gzipped. Something like:

**current**:
```
resource "aws_s3_bucket_object" "object" {
    bucket = "your_bucket_name"
    key = "new_object_key"
    source = "path/to/file"
}
```

**gzipped**:
```
resource "aws_s3_bucket_object" "object" {
    bucket = "your_bucket_name"
    key = "new_object_key"
    source = "${gzip(file("path/to/file))}"
}
```

WDYT?

**Comment by apparentlymart** [comment]
@glerchundi I definitely agree that this is useful... I'd love to be able to upload gzipped stuff to S3 as you suggested!

My concern is specifically with how well Terraform's internals will deal with having raw binary data in property values: Go strings are UTF-8 by convention but in practice can be any bytes, but JSON can't serialize raw bytes and so the `encoding/json` library will replace non-UTF-8-valid data with the unicode replacement character. This is just one case I know of where we implicitly assume UTF-8 string data in Terraform; they may be other cases I'm not considering.

This will probably work fine for attributes that have a `StateFunc` that returns a hash of the data (which I believe `aws_s3_bucket_object.source` does), but it may cause strange consequences for any attribute whose value is stored literally in the state.

I think it would be good to test some edge cases here to make sure that Terraform won't silently corrupt binary data. We could test some of this by just adding a couple extra unit tests that return raw binary data without base64-encoding it, but I'm not sure how best to test what happens when binary data gets written out into the JSON state file... that probably requires something like an acceptance test using the `null_resource`, e.g. putting gzip data in the `triggers` map to see whether Terraform corrupts it at some point during the workflow.

**Comment by glerchundi** [comment]
@apparentlymart thanks for this detailed explanation, I really appreciate it. 

> This will probably work fine for attributes that have a StateFunc that returns a hash of the data (which I believe aws_s3_bucket_object.source does), but it may cause strange consequences for any attribute whose value is stored literally in the state.

This seems reasonable. I think it would be possible to diverge paths depending on how do you what to save this in the state based on the value type. But anyway this is your concern and your internal&core headaches ;P.

> I think it would be good to test some edge cases here to make sure that Terraform won't silently corrupt binary data. We could test some of this by just adding a couple extra unit tests that return raw binary data without base64-encoding it, but I'm not sure how best to test what happens when binary data gets written out into the JSON state file... that probably requires something like an acceptance test using the null_resource, e.g. putting gzip data in the triggers map to see whether Terraform corrupts it at some point during the workflow.

Yep, absolutly needed! If I find a free slot I can work on this.

And again, thanks for pointing me out with every detail it was really interesting.

**Comment by oli-g** [comment]
+1. I really need something like this.

**Comment by sean-brandt** [comment]
+1 This would be extremely helpful.

**Comment by glerchundi** [comment]
@apparentlymart I rebased, any chance to make this merged into the master branch? It seems like it's not just me ;)

If not, please tell us something so that we can start thinking in other approaches.

Thanks.

**Comment by cihangir** [comment]
+1 I really need this right now :)

**Comment by moosilauke18** [comment]
+1

**Comment by paultyng** [comment]
Running in to the same issues with large cloud inits.  Coreos doesn't support multipart, but it does support base64+gzip content of files.  This would be a big win.

**Comment by Seraf** [comment]
Hello,

I also need it for coreos !

**Comment by opsline-ryan** [comment]
I also really need this to use terraform with coreos and CloudFormation. This PR looks good to be merged. If you need help with anything related to adding this feature, please let me know.

**Comment by sachincab** [comment]
thanks for looking into this, much needed feature!
I hope it would be available sooner for use.

**Comment by rochacon** [comment]
Any updates on this? This would be really helpful when using some rather large user data scripts (I just hit this problem). 

@glerchundi would you mind rebasing the branch with latest master so the conflict is resolved?

**Comment by Seraf** [comment]
Hello, any progress on this feature please ?

Thanks

**Comment by akranga** [comment]
Hello, any update on this? Is this just a rebase issue + merge conflict issue?

**Comment by francisbeaudoin** [comment]
+1

**Comment by cemo** [comment]
@apparentlymart please merge this. This will be gonna a big win since it is replacing a layer in coreos by removing extra storages.

**Comment by cemo** [comment]
@grubernaut don't you think that this is a good addition?

**Comment by grubernaut** [comment]
Hello all, and @glerchundi. 

Thank you so much for the contribution, and I sincerely apologize that this has sat here for so long without a response or action. This is entirely our fault, and we're working on making the review process better in the future. 

That being said, I can see the benefit of this PR and will happily merge this once the conflicts are resolved. We'll also need some clear documentation on the interpolation function and any use cases that it will solve. 

Thanks again for the contribution!

**Comment by glerchundi** [comment]
> Thank you so much for the contribution, and I sincerely apologize that this has sat here for so long without a response or action. This is entirely our fault, and we're working on making the review process better in the future.

Don't worry. Good to know there is an intention to improve this process.

> That being said, I can see the benefit of this PR and will happily merge this once the conflicts are resolved. We'll also need some clear documentation on the interpolation function and any use cases that it will solve.

Will rebase as soon as possible. Once its rebased on master, start requesting changes and hopefully we can push this forward.

**Comment by cemo** [comment]
Thank you @grubernaut and @glerchundi. Hope that it will included in the next release which will be pretty soon. Maybe tomorrow?

**Comment by apparentlymart** [comment]
Hi everyone! Sorry for the long silence here.

Back in 2015 I shared my suspicion that this was going to cause some issues with Terraform's architecture, due to its implicit assumption that all strings are UTF-8.

Recently #14314 was filed, which seems to confirm that fear: raw gzip data is getting corrupted somewhere in Terraform core.

So for the moment we're going to have to leave this on hold until we can get to the bottom of what's going on here and devise a solution. I know this is frustrating, but we don't want to ship a feature (another one!) that seems to work at first but then quietly corrupts data behind the scenes, so we need to do some foundational work here to make this possible.

In the mean time, we're definitely open to the idea of adding some less-general features to achieve certain specific use-cases if people have them. In the past we've tended to deal with binary data (like the archives uploaded to AWS Lambda, for example) by referencing files on disk rather than data in memory, and while that does have some drawbacks it is something we can consider for other use-cases too as a stopgap until we're able to do the more general work here.

**Comment by cemo** [comment]
@apparentlymart, Is this because gzip is used without base64?

**Comment by apparentlymart** [comment]
Yes, if this function was both gzip _and_ base64 at once the problem would go away, though I'm not sure if such a thing would still be useful unless we were to make certain resources accept base64-encoded data as input. (Which we could do... Just need to know which ones would benefit from it.)

**Comment by cemo** [comment]
I think that this might be documented for precaution. At worst case a function `gzipBase64` like `base64sha256`can be introduced.
We hit the limit of user data now. There is not any easy way to fix it without using `gzip` interpolation function. Also see #3858, #8994. Really glad if we can move this issue since other solutions are really too ugly.

**Comment by apparentlymart** [comment]
If someone had the time and motivation to make a revision of this PR for a function `gzipbase64` we could safely merge that, and then work on adding base64 support to resource arguments where providing gzip data makes sense. (I believe, though don't remember for certain, that the `user_data` argument already accepts base64-encoded data.)

**Comment by cemo** [comment]
@glerchundi does it make sense for you too?

**Comment by rochacon** [comment]
I've been using this patch in a custom built Terraform binary and haven't seen this corrupt gzip data issue, this is worrying, thanks for bringing this up.

My use case does not allow the base64 wrapping though, since CoreOS cloud init implementation does not support it (not sure if this changed recently).

For reference, this is the way I've been using it in my resources:

```
resource "aws_launch_configuration" "controller" {
  # ...
  user_data = "${gzip(data.template_file.controller_user_data.rendered)}"
  # ...
}
```

**Comment by apparentlymart** [comment]
If passing base64 directly to `user_data` is not workable, I expect we could offer an alternative property `user_data_base64` that does the decoding internally to the provider before sending data to the EC2 API. This is admittedly annoying for anyone already using it since it will require some manual fixup to prevent Terraform from replacing the instance to set it, but after the initial transition I think it would work as expected, despite being not the most ideal solution.

**Comment by cemo** [comment]
Coreos support gzip+base64 encoded files. Our simplified use case is like this:
 
```
data "template_file" "cloud-config" {
  vars {
    ca_pem = "${base64encode(var.tls-ca-self-signed-cert-pem)}"
  }
}
```
But we have so much certificates so we had to pass them as gzip since we exceeded 16K limit. If `gzip` PR will be merged, we will use like `base64encode(gzip(content))`.

**Comment by cemo** [comment]
@apparentlymart, @glerchundi I have rebased and added necessary implementations at [here]. But expected result at my test is different than @glerchundi. He has used base64 as well but I am not sure why the result is different. Would you review this please guys?

[here]: https://github.com/cemo/terraform/commit/8b1ae071e6b82a1240640cfd4bb0514ef58e9ff6

**Comment by cemo** [comment]
I think it is related to go version the time first PR is submitted. Since there are changes at [1.8 related gzip] the output might change.

[1.8 related gzip]: https://golang.org/doc/go1.8#compress_flate

**Comment by glerchundi** [comment]
@cemo definitely, it's related to gzip implementation changes. We already faced this issue in other projects, same input different results depending on the runtime you were using:

https://golang.org/doc/go1.8#compress_flate

@apparentlymart Ok, seems reasonable. That being said, and knowing there were precedents in place (`base64sha{256,512}`) I updated the PR to do gzip+base64 both at the same time. This would unblock the issues with CoreOS and gzip'ed+base64'ed data. In case gzip (or whatever func which requires raw data as output) was needed it can be tackled in another PR, lets resolve this first.

**Comment by glerchundi** [comment]
Just to put some info on this thread, [`coreos-cloudinit`](https://github.com/coreos/coreos-cloudinit) already supports `encoding: "gzip+base64"` but the whole config file is being deprecated and replaced by a lighter, simplified and json based alternative called [`ignition`](https://github.com/coreos/ignition) which follows the standard [data URI scheme](https://tools.ietf.org/html/rfc2397) when it comes to embedding data. I didn't tried yet but I think the same behaviour can be achieved by doing something like this: `data:application/x-gzip;base64:<gzipped-and-then-base64ed-data>`.

So it seems this PR applies.

**Comment by cemo** [comment]
@apparentlymart I think that you can merge this issue since all your concerns are addressed. This PR also closes #3407.

**Comment by shantanugadgil** [comment]
Hi,

This seems to be only one way, right? No way to get back the original using any other function?
Do you think we would need a "gunzipbase64decode" as well ?

I happened to stumble upon this while searching for _my_ requirement:
"base64encodebzip2"/"bunzipbase64decode"
I need to interpolate and use bzip2+base64encoded data (small strings)
_* could work the same for template files as well I guess._

Thanks and Regards,
Shantanu

**Comment by josephholsten** [comment]
@cemo where's the PR with your implementation? seems like we could close this PR if yours gets merged.

**Comment by cemo** [comment]
@josephholsten I had implemented but did not create a PR since @glerchundi was the original author. He also updated to address @apparentlymart's concerns. Now it is safe to merge this PR.

**Comment by apparentlymart** [comment]
Hi everyone! Sorry for the silence here. This is on my list to review soon, just getting delayed by some legwork going on for the 0.10 release. I will look at this as soon as I can.

**Comment by gargath** [comment]
This would be incredibly useful.
Our use case is templating cloud-config `write-file` blocks with base64 encoded certificate data read from Vault.
Since these go onto S3, we encrypt them using kms (for which there is a terraform resource), but need to gzip the payload first (due to kms plaintext size limit).

It would be great if we could simply do
```
data "aws_kms_ciphertext" "somesecret" {
  key_id = "${aws_kms_key.my_key.key_id}"
  plaintext = "${gzip(${vault_generic_secret.cert.data["cert"]})}"
}
```

**Comment by apparentlymart** [comment]
I rebased this, added some docs, and merged it as a303817e03bc048c5656f4648e91fa3384c981f3.

Thanks for working on this, @glerchundi, and for your patience as we worked through the design constraints. Sorry this one took so long!

At present this function will likely be of limited use due to the need for other resources to be updated to expect base64 data as an option, but this is a good first step.

We'd be happy to review PRs for adding base64 variants of attributes that are often used with the `file` interpolation function where there's a strong use-case for using binary data, such as `content` on `aws_s3_bucket_object` having a companion `content_base64` attribute. I expect we'd be more cautious about situations where the use of binary data seems marginal; if someone wants to propose such a change, I'd ask that they do their best to describe the use-case for binary data and why plain text isn't a suitable alternative, since plain text is generally better where possible for having readable diffs, etc.

**Comment by glerchundi** [comment]
Don't worry @apparentlymart and thanks this is going to be a huge win for us.

**Pull request closed without merging**
