### PR TITLE
provider/aws: fix potential panic when finding network ACL

### LINKED ISSUE #1549: Crash while adding network acls
So as not to be spammy, I've attached as a gist:

https://gist.github.com/sethlindberg/68311cfe488636995bb3

the issue happened when applying a self-created module that applies a set of network acls to subnets. If you need more information I'm happy to give it.

### PR DESCRIPTION
**Pull request by mitchellh**
Fixes #1549 

I wasn't able to reproduce this but I can see how its technically possible. I just guard this with some sanity.

### CODE REVIEW

**Comment by phinze** [comment]
Yup yup, might as well be cautious. LGTM

**Comment by johnrengelman** [comment]
This might be posing a new error however - I'm trying to create a brand new VPC, w/ subnet and ACL and I"m getting this error on apply:
`Failed to update acl acl-8df4d1e8 with subnet subnet-a0e3c09a: InvalidNetworkAclID.NotFound: The networkAcl ID '' does not exist`

**Comment by phinze** [comment]
@johnrengelman whoops! do you have a config snippet you can share?

**Comment by johnrengelman** [comment]
Haven't tried it watered down to this, but I think this it will do it:
```
variable "cidrs" {
  default = {
    "0" = "172.29.0.0/26"
    "1" = "172.29.0.64/26"
    "2" = "172.29.0.128/26"
  }
}

variable "azs" {
  default = {
    "0" = "us-east-1c"
    "1" = "us-east-1d"
    "2" = "us-east-1e"
  }
}

resource "aws_vpc" "main" {
  cidr_block = "172.29.0.0/24"
  instance_tenancy = "default"
  enable_dns_support = true
  enable_dns_hostnames = true
  tags {
    Name = "${var.environment}"
    Environment = "${var.environment}"
  }
}

resource "aws_internet_gateway" "gw" {
  vpc_id = "${aws_vpc.main.id}"
  tags {
    Name = "${var.environment}"
    Environment = "${var.environment}"
  }
}

resource "aws_subnet" "main" {
  count = 3
  vpc_id = "${aws_vpc.main.id}"
  availability_zone = "${lookup(var.azs, count.index)}"
  cidr_block = "${lookup(var.cidrs, count.index)}"
  map_public_ip_on_launch = false
  tags {
    Name = "${var.environment}"
    Environment = "${var.environment}"
  }
}

resource "aws_network_acl" "main" {
  count = 3
  vpc_id = "${aws_vpc.main.id}"
  subnet_id = "${element(aws_subnet.main.*.id, count.index)}"
  egress = {
    protocol = "all"
    rule_no  = 1
    from_port = 0
    to_port = 65535
    action = "allow"
    cidr_block = "0.0.0.0/0"
  }
  ingress = {
    protocol = "all"
    rule_no = 1
    from_port = 0
    to_port = 0
    action = "allow"
    cidr_block = "0.0.0.0/0"
  }
}
```

The problem is this line: https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_network_acl.go#L345
That's adding the `networkAclId` filter, but with no values. 
I removed that locally and it works.

**Comment by phinze** [comment]
Thanks for the report - filed as #1634 and will get it fixed up.

**Pull request merged**
