### PR TITLE
[WIP] provider/aws: AWS WAF Regional Web ACL support

### PR DESCRIPTION
**Pull request by yusukegoto**
This PR is from #13676.

test
```
resource "aws_wafregional_byte_match_set" "byte_set" {
  name = "tf_waf_byte_match_set"
  byte_match_tuples {
    text_transformation = "NONE"
    target_string = "badrefer1"
    positional_constraint = "CONTAINS"
    field_to_match {
      type = "HEADER"
      data = "referer"
    }
  }
}

resource "aws_wafregional_rule" "wafrule" {
  depends_on = ["aws_wafregional_byte_match_set.byte_set"]
  name = "tfWAFRule"
  metric_name = "tfWAFRule"
  predicates {
    data_id = "${aws_wafregional_byte_match_set.byte_set.id}"
    negated = false
    type = "ByteMatch"
  }
}

resource "aws_wafregional_web_acl" "wafacl" {
  depends_on = ["aws_wafregional_byte_match_set.byte_set", "aws_wafregional_rule.wafrule"]
  name = "tfWebACL"
  metric_name = "tfWebACL"
  default_action {
    type = "ALLOW"
  }
  rules {
    action {
       type = "BLOCK"
    }
    priority = 1
    rule_id = "${aws_wafregional_rule.wafrule.id}"
  }
}
```

exec
```
```

### CODE REVIEW

**Comment by DennyLoko** [comment]
Hello @yusukegoto. Since #13705 has already been merged, would you mind to rebase this?

**Comment by yusukegoto** [comment]
@DennyLoko 
Sorry for my lazy reply.
Thanks for taking over these. I can't have much time to fix these. Thanks.

**Comment by DennyLoko** [comment]
Hello @yusukegoto, no worries.
I've already migrated most of them to the new repository.

**Comment by apparentlymart** [comment]
Hello , and thanks for working on this!

As part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it. It looks like @DennyLoko already migrated this as terraform-providers/terraform-provider-aws#1046, so thanks!

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Comment by jornjambers** [comment]
wauw...

**Pull request closed without merging**
