### PR TITLE
helper/schema: map counts in state

### PR DESCRIPTION
**Pull request by mitchellh**
@svanharmelen This fixes the computed map issue. I honestly don't think this ever worked... or if it did it just happened to work. None of our tests covered it. Take a look.

### CODE REVIEW

**Comment by svanharmelen** [comment]
Looks good... Just double checking with some acc tests...

**Comment by svanharmelen** [comment]
LGTM! All tests passed (as expected :wink:)

**Comment by mitchellh** [comment]
Wonderful... merging

**Comment by kubek2k** [comment]
:raised_hands: !

**Pull request merged**
