### PR TITLE
provider/vsphere: virtual_machine -- Allow timeout when no IP will be allocated

### PR DESCRIPTION
**Pull request by ChloeTigre**
### Abstract

I work in a context where the VMs will have no IP address until we give them one.
### Problem addressed

In that case the vSphere provider will wait forever for an IP address to show up.
### Solution

I give the API 10 seconds to give me IP addresses and I ignore it if none can be found. This allows for a more universal support.
### Points to be improved

Allow to configure the wait timeout in the provider config
Allow to be blocking until an IP address is allocated (current behaviour)
Test and find the best default timeout value.
### Unit tests

No changes needed in the current unit tests.

### CODE REVIEW

**Comment by ChloeTigre** [comment]
Bump. The fix did not do well on VM updates. So I added it on updates.

**Comment by chrislovecnm** [comment]
any way we can test this?  Thanks for the contribution

**Comment by ChloeTigre** [comment]
It runs using the same unit tests as vSphere.

I could add a unit test where I don't explicitly attribute an IP address to a vsphere_virtual_machine to confirm it works but it would need to be supported by the underlying test cluster

**Comment by apparentlymart** [comment]
Hello @ChloeTigre, and thanks for working on this!

As part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it.

[The vSphere provider](https://github.com/terraform-providers/terraform-provider-vsphere) -- and, in particular, the virtual machine resource -- are currently in the process of being revamped somewhat, with the goal of supporting more of the available features. Unfortunately this means that to re-target this change to the new repository may require some restructuring :confounded:.

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Pull request closed without merging**
