### PR TITLE
Gracefully stops on SIGTERM

### PR DESCRIPTION
**Pull request by mildred**
Add SIGTERM handling on UNIX platforms.

closes issue #10459

### CODE REVIEW

**Comment by mildred** [comment]
I had another patch, but I tested it and it seems it works without. How do signals interact with plugins ?

Here it is:

```
diff --git a/vendor/github.com/hashicorp/go-plugin/server.go b/vendor/github.com/hashicorp/go-plugin/server.go
index 4e3a552..02519a2 100644
--- a/vendor/github.com/hashicorp/go-plugin/server.go
+++ b/vendor/github.com/hashicorp/go-plugin/server.go
@@ -11,6 +11,7 @@ import (
        "runtime"
        "strconv"
        "sync/atomic"
+       "syscall"
 )
 
 // CoreProtocolVersion is the ProtocolVersion of the plugin system itself.
@@ -117,7 +118,7 @@ func Serve(opts *ServeConfig) {
 
        // Eat the interrupts
        ch := make(chan os.Signal, 1)
-       signal.Notify(ch, os.Interrupt)
+       signal.Notify(ch, os.Interrupt, syscall.SIGTERM)
        go func() {
                var count int32 = 0
                for {
```

**Comment by mildred** [comment]
This PR doesn't work yet, unless `TF_FORK=0`. I will provide a fix soon.

**Comment by mildred** [comment]
Modifying panicwrap was necessary to allow signal forwarding. See PR mitchellh/panicwrap#15. This PR also contains a commit to update the panicwrap dependency.

**Comment by mitchellh** [comment]
Merged to master. I made the updates necessary for the panicwrap passthrough config to be setup. Thanks!

**Comment by mildred** [comment]
Hello,

I'm afraid this won't work. Panicwrap is blocking SIGTERM and does not forward the signal to the main terraform process. See mitchellh/panicwrap#15:

> SIGINT is generally sent to all processes connected to the virtual terminal when typing Ctrl-C. SIGTERM is generally sent to a single process. In that case, it is wise not to ignore that signal but to forward it to the child process instead to give it the opportunity to handle it.
>
> This is required for correct handling of SIGTERM inside terraform. When SIGTERM is sent to the parent process, ignoring the signal won't help, it must be forwarded.

**Comment by mitchellh** [comment]
Ah I see, chatting over at panicwrap I didn't realize that SIGTERM wasn't sent to all processes like SIGINT. I'll check that out.

**Pull request closed without merging**
