### PR TITLE
[WIP] Icanhazip data source

### PR DESCRIPTION
**Pull request by deanwilson**
I often need to have my AWS security groups update their "from" lines to suit the IP my ISP has assigned me. While this can be done out of bounds, or via a local exec, I'd rather have Terraform manage this via a data source.

Any feedback would be greatly welcomed.

### CODE REVIEW

**Comment by cemo** [comment]
There are some other ip providers such as:
- http://ifconfig.co/ip
- http://whatismyip.akamai.com

It might be better to support all of them with a sensible default. User can change its ip provider?

**Comment by apparentlymart** [comment]
Hi @deanwilson! Thanks for working on this.

I do share a little @cemo's concern that there are lots of "what is my ip?" services, and it feels weird to play favorites with one in particular, but equally weird to have a separate provider for each one given how simple they all are.

But when I thought about how this would generalize, I realized that ultimately most of these are just an HTTP request that returns a plaintext response. So maybe this would reduce to just being the `http` data source?

```hcl
data "http" "example" {
  url = "https://ifconfig.co/ip"
}
```

Would it work to combine this with the `chomp` function to get the same information without a specialized provider?

**Comment by cemo** [comment]
@apparentlymart this is nicer. 👍

**Comment by deanwilson** [comment]
I think you're right, and this should be approached in a different way. Thank you both for taking the time to look it over. I'll close this one and come back with something hopefully better.

**Pull request closed without merging**
