### PR TITLE
provider/aws: KMS WIP

### PR DESCRIPTION
**Pull request by psytale**
Currently only supporting Keys + Aliases, could add more but looking for a bit of feedback to ensure I'm on the right path.

Tests need writing but a bit unsure, main concern is that KMS keys can not be deleted only deactivated in addition there is a limit to total number of keys per account, so the idea of adding them in acceptance tests is a bit scary.

### CODE REVIEW

**Comment by radeksimko** [comment]
FYI:
https://aws.amazon.com/about-aws/whats-new/2015/10/aws-key-management-service-now-supports-deletion-of-keys/

@psytale Sorry for the silence here, would you mind incorporating the deletion into the PR and solving conflicts that have accumulated over the time? :wink:

**Comment by Felivel** [comment]
I want to know what is missing for this feature to reach release?

**Comment by catsby** [comment]
Sorry for the silence @psytale and @Felivel –

In order to merge this we'll need to add acceptance tests, to ensure things work and continue to work going forward. Any chance you'd be willing to add those? If you have questions on how to proceed, you can ask here, otherwise I would simply copy over an existing `_test.go` file from another AWS resource and modify it to fit your needs.

Let me know if you have any questions!

**Comment by catsby** [comment]
I just noticed #3928 which seems to be a continuation of this PR in spirit, can we close this PR then?

**Comment by psytale** [comment]
Closed in favor of #3928

**Comment by catsby** [comment]
Thanks @psytale !

**Pull request closed without merging**
