### PR TITLE
providers/aws: Validate IOPs for EBS Volumes

### PR DESCRIPTION
**Pull request by catsby**
IOPs must be an integer. 
The range varies by instance size (docs [here][1])pl, so we simply validate that it's an integer. 
IOPs is also not valid for any type that is not `io1`. Unfortunately I don't believe we can check for that in the `plan` phase, but we validate that in the `apply` phase here

Also, a minor fix to the docs: `us-west-1a` does not exist 

helping

[1]: http://docs.aws.amazon.com/fr_fr/AWSEC2/latest/APIReference/API_CreateVolume.html

### CODE REVIEW

**Comment by catsby** [comment]
Fixes #4146

**Comment by billputer** [comment]
Just to clarify, does this still allow passing in a false value to iops? 

Currently we have a module that accepts two arguments: storage_type and iops. We use this with both gp2 and io1. For example:

    storage_type = "gp2"
    iops = false

    storage_type = "io1"
    iops = 200

Basically we need our module to accept both gp2 and io1 storage types. My intuition is that d.GetOk("iops") will return the "false" value and fail validation.

**Comment by catsby** [comment]
> Just to clarify, does this still allow passing in a false value to oops?

Sorry, no :( 

`iops` is an integer value. Passing `false` doesn't fit here. As the PR stands, supplying `iops` with type of `gp2` will result in an error. But maybe it should just ignore the `iops` and log a warning? cc @phinze / @jen20 for thoughts on that

**Comment by billputer** [comment]
The underlying problem that I'm dealing with is that there's I haven't found away in Terraform to conditionally set an argument in a module. That is, only set the "iops" if it's passed in to the module. You can't allow both (storage_type = gp2) and (storage_type = io1, iops = 200).

That's more an issue with Terraform than it is with this PR, which does the sensible thing. Unfortunately it probably means I'll have to have two modules, one for gp2 and one for io1, unless I can find a better workaround.

**Comment by phinze** [comment]
@catsby I think the zero value here can just skip the validation so that this would work:

```
storage_type = "gp2"
iops = 0

storage_type = "io1"
iops = 200
```

I'd actually expect us to have some sort of gp2 exercising acctest that would be failing now w/ an `iops` validation error. We should probably add one if not.

**Comment by catsby** [comment]
Agreed. I'll remove the strict validation. @billputer would `iops = 0` be sufficient for "false" for your use case?

**Comment by billputer** [comment]
@catsby Yup, that should do the trick.

**Comment by catsby** [comment]
@billputer had to tweak it some, but I think this should work for you. Any chance you can try it out? Otherwise I'll just nag @phinze :smile:

**Comment by jen20** [comment]
This LGTM (assuming we don't want to wait to fix this with whatever @phinze is cooking up for resource-level validation!)

**Comment by catsby** [comment]
don't know, @phinze: should I delay?

**Comment by phinze** [comment]
Let's merge this as-is and we can follow up once ResourceValidateFunc finally lands. The conditional read stuff is still going to be valid no matter what we do for validation.

**Pull request merged**
