### PR TITLE
DigitalOcean: Export droplet prices

### PR DESCRIPTION
**Pull request by roidelapluie**
Note: In DO, Droplets are about the only thing you pay. DNS/Float IP are
free.

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
```
make testacc TEST=./builtin/providers/digitalocean TESTARGS='-run=TestAccDigitalOceanDroplet_Basic'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/04/17 22:55:02 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/digitalocean -v -run=TestAccDigitalOceanDroplet_Basic -timeout 120m
=== RUN   TestAccDigitalOceanDroplet_Basic
--- PASS: TestAccDigitalOceanDroplet_Basic (47.36s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/digitalocean   47.368s
```

**Comment by stack72** [comment]
Hi @roidelapluie 

Thanks for the PR - unfortunately, this doesn't pass the tests for me

```
% make testacc TEST=./builtin/providers/digitalocean TESTARGS='-run=TestAccDigitalOceanDroplet_Basic'                           ✭
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/04/18 14:02:52 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/digitalocean -v -run=TestAccDigitalOceanDroplet_Basic -timeout 120m
=== RUN   TestAccDigitalOceanDroplet_Basic
--- FAIL: TestAccDigitalOceanDroplet_Basic (60.82s)
	testing.go:280: Step 0 error: Check failed: Check 2/7 error: Bad price_monthly: %!s(float64=5)
FAIL
exit status 1
FAIL	github.com/hashicorp/terraform/builtin/providers/digitalocean	60.839s
make: *** [testacc] Error 1
```

Please can you take a look?

Paul

**Comment by roidelapluie** [comment]
```
make testacc TEST=./builtin/providers/digitalocean TESTARGS='-run=TestAccDigitalOceanDroplet_Basic'  
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/04/18 13:07:40 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/digitalocean -v -run=TestAccDigitalOceanDroplet_Basic -timeout 120m
=== RUN   TestAccDigitalOceanDroplet_Basic
--- PASS: TestAccDigitalOceanDroplet_Basic (60.84s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/digitalocean   60.844s
```

**Comment by roidelapluie** [comment]
Oh I committed the wrong thing :)

**Comment by roidelapluie** [comment]
@stack72 Fixed now.

**Comment by stack72** [comment]
Awesome! LGTM :)

```
% make testacc TEST=./builtin/providers/digitalocean TESTARGS='-run=TestAccDigitalOceanDroplet_Basic'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/04/18 14:43:25 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/digitalocean -v -run=TestAccDigitalOceanDroplet_Basic -timeout 120m
=== RUN   TestAccDigitalOceanDroplet_Basic
--- PASS: TestAccDigitalOceanDroplet_Basic (60.67s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/digitalocean	60.690s
```

Thanks for doing this

**Pull request merged**
