### PR TITLE
vendor: Downgrade Azure dependencies

### PR DESCRIPTION
**Pull request by radeksimko**
This is effectively reverting https://github.com/hashicorp/terraform/pull/22247 and https://github.com/hashicorp/terraform/pull/22248

----

I haven't had chance to debug and fully understand _why_, but here's what the end-user experience of provider developer looks like (this is for a provider which doesn't depend on the Azure SDK at all - AWS):

```
go: finding github.com/hashicorp/terraform master
go: downloading github.com/hashicorp/terraform v0.12.7-0.20190816123248-b5508b914224
go: extracting github.com/hashicorp/terraform v0.12.7-0.20190816123248-b5508b914224
build github.com/hashicorp/terraform: cannot load github.com/Azure/go-autorest/autorest: ambiguous import: found github.com/Azure/go-autorest/autorest in multiple modules:
	github.com/Azure/go-autorest v10.15.4+incompatible (/Users/radeksimko/gopath/pkg/mod/github.com/!azure/go-autorest@v10.15.4+incompatible/autorest)
	github.com/Azure/go-autorest/autorest v0.5.0 (/Users/radeksimko/gopath/pkg/mod/github.com/!azure/go-autorest/autorest@v0.5.0)
```

So the end-user/developer of a provider receives quite a cryptic error message, which is _probably_ solvable by adding `replace` into their `go.mod`, but:

- the solution is not immediately obvious
- we force _majority_ of our users/developers to do some extra work to comfort _the few_, which is a pretty high cost to pay for this change
- we end up with these `replace` "hacks" sprinkled over all provider codebases, which is far from ideal

----

I do not know what the right solution is, but I'm proposing to revert these changes until we find a solution which ideally doesn't break most providers' `go get` UX.

### CODE REVIEW

**Comment by appilon** [comment]
More information on why this is happening can be found here: https://gist.github.com/appilon/1ba757b22845b400aa9841ff54d0f330

To summarize, it seems when upgrading Terraform go modules tries to satisfy both the old version of TF and the new one. This will lead to an ambiguous import of the problematic dependencies, despite this being incorrect, we only need the transitive dependencies of the new Terraform. You can clear up the temporary problem with `go mod tidy`. This is explained a bit more clearly in the gist.

**Comment by tombuildsstuff** [comment]
@jhendrixMSFT any chance we we get your input on the best path forward here?

To give a little context: Terraform's vendored as a library into it's providers (which can vendor each other, for historical reasons) - so whilst `replace` might work at the top level, that's going to need to be added to every provider (or ask folks to run `go mod tidy` to remove the unused dependency) - which isn't ideal

**Comment by radeksimko** [comment]
cc @tamalsaha

**Comment by tamalsaha** [comment]
It might be worth waiting to hear from @jhendrixMSFT . He has actively working on getting the go.mod issues under control.

**Comment by jhendrixMSFT** [comment]
Regarding the ambiguous imports problem, this is being discussed in https://github.com/Azure/go-autorest/issues/414, I will get this deployed in `go-autorest` today.

**Pull request closed without merging**
