### PR TITLE
Updated google instance docs with custom instance type

### PR DESCRIPTION
**Pull request by pradeepchhetri**

### CODE REVIEW

**Comment by radeksimko** [comment]
:+1: Thanks.

**Comment by pradeepchhetri** [comment]
@radeksimko Looks like a lot of the documentation which is in master is not actually deployed. Is there any particular reason for it ? Would like to see terraform website also up to date :)

**Comment by radeksimko** [comment]
It will be deployed along with the next release as it also contains docs for new resources/providers/functions which have not been released yet.

**Comment by pradeepchhetri** [comment]
Ah, got it. Thank you for the clarification.

**Pull request merged**
