### PR TITLE
Spotlight-like search facility in the Terraform documentation

### PR DESCRIPTION
**Pull request by jammycakes**
This is a quick lookup feature that I proposed as a possible solution for #9589. It will allow users to navigate quickly and easily to other pages on the site. This is especially important for very large providers such as AWS that have a large number of data sources and resources and that are difficult to navigate.

When the user presses the appropriate keystroke (Ctrl-/ or Cmd-/ on the Mac), it will bring up a Spotlight-style search box, similar to the Ctrl-P functionality in text editors such as Sublime Text, Visual Studio Code, and Vim's CtrlP extension. The user can then type in a part of the title and will be shown a list of pages that changes as they type.

Once they've got a list of candidates, they can then either click on one of them directly, or else use the Tab key to navigate to the one they wish to choose.

Tested on IE10, IE11, Edge, Firefox 52, Chrome 56, Safari 10.

# A couple of questions here for feedback:

1. Is the styling OK? Any particular changes necessary?
2. Is Ctrl-/ or Cmd-/ the best key combination to invoke the search box? Would a different combination be better? I originally went for Ctrl-P but changed this to avoid conflicting with browsers' print dialogs.
3. Do you want a visible clickable link for this or will the key combination suffice?

# Technical notes:

I'm keeping some fairly comprehensive lab notes on this pull request as I'm working on it; these explain my thinking behind the design in greater detail. You can find these at https://github.com/jammycakes/terraform/wiki/issue_9589.

### CODE REVIEW

**Comment by radeksimko** [comment]
cc @captainill I think you are working on something very similar to this? 😃

**Comment by jammycakes** [comment]
I'm thinking about using a different key combination for this, since Ctrl-P conflicts with the print dialog box on Windows/Linux. My current thoughts are Ctrl-/ (or Cmd-/ on the Mac.) Any thoughts anyone?

**Comment by stack72** [comment]
Hi @jammycakes 

Thanks for the PR here - is there any chance you could email me on stack72 at hashicorp.com so we can discuss this :) This is an interesting PR that I'd love to talk more about

Paul

**Comment by Defozo** [comment]
What's the progress on that?

**Comment by teamterraform** [comment]
Hello, and sorry for the long silence on this PR. 

There have been many changes to the website layout and functionality since this PR was opened, and the website is continuing to be worked on by a different team, so we are going to close this PR. 

Thank you for your submission.

**Pull request closed without merging**
