### PR TITLE
main: Special error message for invalid top-level command

### PR DESCRIPTION
**Pull request by apparentlymart**
Previously Terraform would react to an invalid top-level command the same way as for typing no command at all: just printing out the long top-level help directory.

If someone's tried to type a command, it's more helpful to respond to that request by explaining directly that the command is invalid, rather than leaving the user to puzzle that out themselves by referring to the help text.

As a bonus, this also allows us to use our `didyoumean` helper package to suggest a possible alternative if it seems like the user made a typo.

```shellsession
$ terraform blorp
Terraform has no command named "blorp".

To see all of Terraform's top-level commands, run:
  terraform -help

$ terraform destory
Terraform has no command named "destory". Did you mean "destroy"?

To see all of Terraform's top-level commands, run:
  terraform -help

$ terraform consul
Terraform has no command named "consul". Did you mean "console"?

To see all of Terraform's top-level commands, run:
  terraform -help

$ terraform okan
Terraform has no command named "okan". Did you mean "plan"?

To see all of Terraform's top-level commands, run:
  terraform -help
```

Due to the design of the CLI library we use, this special error message only works for top-level commands right now. Typing `terraform state posh`, for example, will just print out the help directory for `terraform state` like before. On the plus side, the subcommand help directories are generally not as long as the main one and so hopefully easier to quickly scan and understand what happened. Maybe we'll improve on this more someday, but this is just intended as a quick fix for a common "papercut".

### CODE REVIEW

**Comment by alisdair** [comment]
This seems to break `terraform help`:

```shellsession
 $ terraform help
Terraform has no command named "help".

To see all of Terraform's top-level commands, run:
  terraform -help
```

Maybe we can special-case that?

**Review by alisdair — APPROVED** [review]
Oh, oops, I just realized that `terraform help` is not an intentionally supported command, it just happened to print the same usage that `terraform -help` does. Never mind!

**Comment by apparentlymart** [comment]
Heh... that does suggest that maybe we _should_ have a `terraform help` command (similar to how `terraform -version` and `terraform version` are the same), but I think I'll save that for another day because the new error message here _does_ directly show how to get the help information.

**Comment by pselle** [comment]
:heavy_plus_sign: to Alisdair's comment! I did use `help` this way myself, so I suspect we'll "break" this for some users.

**Pull request merged**
