### PR TITLE
Add new auth for tencentcloud cos backend

### PR DESCRIPTION
**Pull request by SevenEarth**
Add more authentication method for COS backend.

## Target Release

1.19.x

### ENHANCEMENTS

 

-  Support `shared_credentials_dir`, `profile` authentication method
-  Support `cam_role_name` authentication method
-  Updated documentation for TencentCloud cos backend

### CODE REVIEW

**Comment by SevenEarth** [comment]
@crw Hello,  I've signed the CLA,  Please review this pr. thanks

**Comment by SevenEarth** [comment]
@crw Hi, I've signed the CLA, Please review this pr. thanks

**Comment by SevenEarth** [comment]
Hi @likexian, pls help to review my PR. 3q.

**Comment by likexian** [comment]
LGTM

**Comment by SevenEarth** [comment]
@jbardin Hi, could you please take a look at this pr, thanks?

**Comment by SevenEarth** [comment]
@crw @jbardin @likexian This PR has been submitted for some time now, Please take a look at this pr? thanks

**Review by radeksimko — APPROVED** [review]

**Comment by SevenEarth** [comment]
Thanks ^_^

**Pull request merged**
