### PR TITLE
Fix regex pattern for more alternatives

### PR DESCRIPTION
**Pull request by petoju**
During refactoring, there was a backslash added to `|` character in terraform regex. That doesn't actually work.

Fix that and return just `x|y` - that's the correct usage, that works.

Fixes #

## Target Release

1.1-backport
1.2-backport
1.3-backport
1.4.x

### BUG FIXES

- Terraform regex documentation of `x|y` included an extra backslash. Removed.

### CODE REVIEW

**Comment by crw** [comment]
Thanks for the submission! I've notified the docs team. I'm not sure why CLA bot is having issues with this PR. I'll ask around to see if someone knows why that is happening. Thanks!

**Comment by petoju** [comment]
@crw That was my bad - I used an incorrect user in my commit before.

**Review by mgarrell777 — APPROVED** [review]
@petoju Thanks very much for this PR. Looks good to me.

**Review by rkoron007 — APPROVED** [review]
Hello! 👋  Sorry for the late response here, but this one looks good to me! I'm going to go ahead and merge, thank you so much for contributing! ✨

**Pull request merged**
