### PR TITLE
Add support for SSH Agent

### PR DESCRIPTION
**Pull request by tarrant**

### CODE REVIEW

**Comment by mitchellh** [comment]
This is a great start! Noted on your need to close the socket but I see there isn't a good place yet. But so far so good. :+1:

**Comment by mitchellh** [comment]
Let me know when you want me to take another look.

**Comment by tarrant** [comment]
I added a cleanup function and added calls to it everywhere that seemed appropriate. Feel free to let me know of any additional changes you require or would like.

On a side note thanks for this project! I love it and my coworkers are quickly coming to love it also.

**Comment by mitchellh** [comment]
LGTM. This looks great. Thanks so much for the great PR as well as docs. You also touched probably the only feature that isn't unit tested. :) So, no tests needed. Coming in.

**Pull request merged**
