### PR TITLE
Allow count in data sources

### LINKED ISSUE #8527: count is not implemented in data sources
Hi,

### Terraform Version
Terraform v0.7.2

### Affected Resource(s)
Related to data sources implementation 
error noticed with  
- data.template_file
- data.null_data_source

### Terraform Configuration Files
```hcl
data "template_file" "check_connection_to_jboss" {
    count = "2"
    template = "${file("${path.root}/files/consul/check_connection_to_jboss.json.tpl")}"
    vars {
        aps = "${element(azurerm_virtual_machine.aps.*.name, count.index)}"
    }
}
```

### Expected Behavior
I need to generate specific consul check scripts for each created node. 
To do that, I have looped on the VMs count and pass them as vars to rendered templates. 
It was working fine with terraform 0.6.16. To migrate in 7.2, I have transformed 
```hcl
resource "template_file" "check_connection_to_jboss" {
```
into 
```hcl
data "template_file" "check_connection_to_jboss" {
```

### Actual Behavior
I got the message
  * data.template_file.check_connection_to_jboss #1: : invalid or unknown key: count
  * data.template_file.check_connection_to_jboss #0: : invalid or unknown key: count

I cannot see in the documentation reference to supported meta-parameters for data sources. 
I have found the same limitation with null_data_source. 
So, I would assume that this affects any data source. 

### Steps to Reproduce
terraform plan

### PR DESCRIPTION
**Pull request by jbardin**
Count worked in data sources, but the resource validation would fail due to the extra "count" key in the raw config. Make sure the HCL loader removes count.

Fixes #8527

### CODE REVIEW

**Comment by mitchellh** [comment]
A couple things:

  * Could we add a `context_apply_test` as well for this to make sure that the multiple query works properly? 

  * Can we add a test to verify `count.index` works properly within a data source? (e.x. `foo = "${count.index}"`)

**Comment by jbardin** [comment]
@mitchellh Can you give me an example of what you mean by that first part? I couldn't come up with a good test for apply that didn't just repeat the plan. It's probably the same issue I had with assigning "${count.index}" -- I couldn't figure out how to expose them correctly in the tests (the data sources show up differently in the state than regular resources).

**Comment by jen20** [comment]
@mitchellh I'm not so sure there is a distinct apply test here because of the refresh at plan to make the values known?

**Comment by mitchellh** [comment]
You're probably right with refresh and I can add a count.index test later.

**Comment by jen20** [comment]
Also fixes #7919 (and probably some others).

**Comment by jen20** [comment]
I've added a test of count.index, but to avoid circular dependencies or large modifications to the null providers used in context tests it is implemented as a unit test in the `builtin/providers/test` package. It's possible that there is a better way to test this in future however!

**Pull request merged**
