### PR TITLE
Flatten `assume_role` block for OSS backend 

### PR DESCRIPTION
**Pull request by hayorov**
# Motivation
Current OSS backend implementation has a nested block in the config section called `assume_role` that doesn't allow to use it in data source #29305.

This is a suggestion to make the design of the OSS backend (https://www.terraform.io/docs/language/settings/backends/oss.html) more aligned with other existing backends and resolve issues #29305 #23755

# Implementation

- Flatter the `assume_role` as it implemented in other backends (example s3) as `assume_role_X`, X nested paremeter
- Support and deprecate `assume_role` since 1.1.0 (next release)
- Add constraints `assume_role` <> `assume_role_X` 

Params digest with the next flow:
- populate from  deprecated `assume_role` block
- (if block empty) populate from flat `assuime_role_X`

# Considerations

This PR introduces backward-compatible changes for the OSS backend and introduces flatter assume_role_* options together with the deprecation of the existing assume_role block with nested parameters.

### CODE REVIEW

**Comment by hayorov** [comment]
UPD: if the design is acceptable I'm happy to add OSS backend tests and cover assume_role logic, currently there are no tests.

**Comment by hayorov** [comment]
@jacobm3  up!

**Comment by hayorov** [comment]
<copy here>

@jbardin it seems that the component maintainer is not available. I've tried all available channels, including Alibaba corporate email and internal Alibaba representatives. What can be next? Any ideas on how to contribute? I'm extremely open to any options.

ping @xiaozhu36
syn @xiaozhu36

**Comment by hayorov** [comment]
Many thanks @xiaozhu36 , let me check and I'll sort them out ...

**Comment by jbardin** [comment]
Thanks @hayorov and @xiaozhu36!

**Pull request merged**
