### PR TITLE
providers/MySQL: Table Level Privilege Grant

### PR DESCRIPTION
**Pull request by renou**
Hi! This is an enhancement around mysql provider's privilege grant functionality.
Currently, privileges are given to all tables on the database. This change is to add a table attribute to the resource so that users can grant privilege on the table level.

Previous resource definition, privileges are granted to the entire database:
```
resource "mysql_grant" "jdoe" {
    user = "${mysql_user.jdoe.user}"
    host = "${mysql_user.jdoe.host}"
    database = "app"
    privileges = ["SELECT", "UPDATE"]
}
```

Enhanced resource definition, privileges can be granted to a specific table:
```
resource "mysql_grant" "jdoe" {
    user = "${mysql_user.jdoe.user}"
    host = "${mysql_user.jdoe.host}"
    database = "app"
    table = "users" // new attribute added in this PR
    privileges = ["SELECT", "UPDATE"]
}
```

Enhanced resource definition, privileges can still be grant to the entire database by not specifying a table attribute:
```
resource "mysql_grant" "jdoe" {
    user = "${mysql_user.jdoe.user}"
    host = "${mysql_user.jdoe.host}"
    database = "app"
    privileges = ["SELECT", "UPDATE"]
}
```

0. updated code
1. updated tests
2. updated website document

### CODE REVIEW

**Comment by renou** [comment]
@protomouse @jtopjian adding the original authors of mysql grant :)

**Comment by jtopjian** [comment]
@renou Thanks for the ping! Here are some thoughts, but keep in mind that I don't manage intricate database permissions on a daily basis:

I think the problems you describe are valid for any tool like Terraform, Puppet, Chef, etc. So the first thing I would do is see how a Puppet or Chef module handles per-table permissions.

If you're concerned about existing permissions or permissions being modified outside of Terraform, that's a valid problem with _any_ Terraform resource. IMO, the user has some responsibility to ensure this happens in a manageable way.

When I first created the `mysql_grant` resource, I made it with just enough functionality to get started with the hope that others would enhance it. That's what @protomouse did and that's what you're doing here, too. And since it looks like this feature isn't opening up any glaring security holes or can easily destroy a user's data, I'm in favor of this feature. :smile: 

With regard to the code itself, I have a few comments:

1. Note how the unique ID of the resource is being formed [here](https://github.com/renou/terraform/blob/bbd212f55ea2eb802ac4b212cfabf65d2887fa6f/builtin/providers/mysql/resource_grant.go#L92-L93). Since you're adding support for individual tables, you will need to add the table to this ID. This is so someone can use multiple `mysql_grant` resources for the same user, same database, but different tables.

2. I would add some acceptance tests to this to validate the functionality works.

Nice work, and I think it's awesome that you raised your concern :)

**Comment by renou** [comment]
Hi @jtopjian Thank you for your feedbacks! I'm going to work through the contributing checklist and complete this feature. Since the MYSQL GRANT statement works on both db and tables, no reason not to have this feature 😄

**Comment by renou** [comment]
Hi @jtopjian I think I've completed this PR and I've updated the PR description. Please review, thank you! 😄  The AppVeyor failed I don't konw why...

**Comment by renou** [comment]
Hi @jtopjian ! Do you know how can I proceed from here to have someone code review the pull request? Thank you!

**Comment by smferguson** [comment]
any traction here? it'd be great to not have custom pieces to manage privs.

**Comment by jtopjian** [comment]
Sorry for the late reply. In general, the code looks good to me, but I think this might require some type of migration for existing resources. @stack72 thoughts?

**Comment by apparentlymart** [comment]
Hello @renou, and thanks for working on this!

As part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it.

If you or someone else has the time and motivation to apply the same changes to [the `mysql` provider repository](https://github.com/terraform-providers/terraform-provider-mysql) and open a new PR there, the maintainers of that provider may be able to review it.

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Pull request closed without merging**
