### PR TITLE
provider/aws: Elastic Beanstalk Application Version

### PR DESCRIPTION
**Pull request by djlestephane**

### CODE REVIEW

**Comment by djlestephane** [comment]
I have rebased and run the acceptance tests successfully:

        lestephane@le-studio: [  ] :~/GoGitRepos/src/github.com/hashicorp/terraform $ aws-vault exec --debug --assume-role-ttl=1h terraform-acceptance-test@sandbox -- make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSBeanstalk'
        ...
        ==> Checking that code complies with gofmt requirements...
        /home/lestephane/GoGitRepos/bin/stringer
        go generate $(go list ./... | grep -v /vendor/)
        2016/07/08 15:30:58 Generated command/internal_plugin_list.go
        TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSBeanstalk -timeout 120m
        === RUN   TestAccAWSBeanstalkApp_basic
        --- PASS: TestAccAWSBeanstalkApp_basic (24.48s)
        === RUN   TestAccAWSBeanstalkAppVersion_basic
        --- PASS: TestAccAWSBeanstalkAppVersion_basic (58.88s)
        === RUN   TestAccAWSBeanstalkConfigurationTemplate_basic
        --- PASS: TestAccAWSBeanstalkConfigurationTemplate_basic (33.92s)
        === RUN   TestAccAWSBeanstalkConfigurationTemplate_VPC
        --- PASS: TestAccAWSBeanstalkConfigurationTemplate_VPC (56.67s)
        === RUN   TestAccAWSBeanstalkConfigurationTemplate_Setting
        --- PASS: TestAccAWSBeanstalkConfigurationTemplate_Setting (33.86s)
        === RUN   TestAccAWSBeanstalkEnv_basic
        --- PASS: TestAccAWSBeanstalkEnv_basic (419.71s)
        === RUN   TestAccAWSBeanstalkEnv_tier
        --- PASS: TestAccAWSBeanstalkEnv_tier (632.75s)
        === RUN   TestAccAWSBeanstalkEnv_outputs
        --- PASS: TestAccAWSBeanstalkEnv_outputs (402.95s)
        === RUN   TestAccAWSBeanstalkEnv_cname_prefix
        --- PASS: TestAccAWSBeanstalkEnv_cname_prefix (416.76s)
        === RUN   TestAccAWSBeanstalkEnv_config
        --- PASS: TestAccAWSBeanstalkEnv_config (611.49s)
        === RUN   TestAccAWSBeanstalkEnv_resource
        --- PASS: TestAccAWSBeanstalkEnv_resource (403.15s)
        === RUN   TestAccAWSBeanstalkEnv_version_label
        --- PASS: TestAccAWSBeanstalkEnv_version_label (441.97s)
        PASS
        ok  	github.com/hashicorp/terraform/builtin/providers/aws	3536.610s

**Comment by stack72** [comment]
@dharrisio / @djlestephane 

Can you folks please let me know about this one? Do we use this and close off #5770? If so, please can this be rebased

Thanks

Paul

**Comment by dharrisio** [comment]
@stack72 I don't think this is quite ready to be merged. There are still a few pieces outlined in #5770 that make me uncomfortable with the changes. For now, I'm going to update #5770 as a WIP, because I think that is probably more representative of the work that as been done so far on that PR.

I do have some plans for using the application version without a new resource. This should at least help some use cases with Elastic Beanstalk. I'm planning on getting that done soon, as well as working on some of the issues in #5770. I should have more on that this week. Hope this clears up the current status of this for you!

**Comment by djlestephane** [comment]
@stack72 I've rebased #7407 in the meantime. I'm new at this so if that is
not the right thing to do, you can close my pull request.

**Comment by marchub** [comment]
+1

**Comment by dharrisio** [comment]
@stack72 This pr can probably be closed now that #5770 has been merged.

**Comment by stack72** [comment]
Closed via #5770

**Pull request closed without merging**
