### PR TITLE
[WIP] Add Triton CNS tag support.

### PR DESCRIPTION
**Pull request by sodre**
The code does an invertible transformation of the Triton CNS tags
effectively mapping `_ -> __` followed by `. -> _`.

Suggested modification to address hashicorp/terraform#5836.

### CODE REVIEW

**Comment by sodre** [comment]
One of the reasons why the AccTest is failing is because of GH-6148. 
I am working to get that fixed as well.

**Comment by sodre** [comment]
@stack72,  I want to expose a field called "DomainNames" which is an array of strings derived from the machine name and the tag values of triton_cns_services. 

What is the best way to include a resource feature that is "read-only" ? Should I include it in the schema and set Computed to true? Is there a way to return it as an output variable, if so can you point me to an example in code that does that?

Thank you.

**Comment by stack72** [comment]
Hi @sodre 

Not sure what you mean by readonly? Do you mean that get's returned from the API only and cannot be set by the user?

P.

**Comment by sodre** [comment]
Hi Paul,

Exactly what you said. It can’t be set directly by the user.

Patrick

**Comment by stack72** [comment]
https://github.com/hashicorp/terraform/blob/master/builtin/providers/azurerm/resource_arm_sql_server.go#L54 This should work for you :)

**Comment by sodre** [comment]
Thanks!
 
I’ll make the mods and check it in with tests this weekend.

Patrick

**Comment by stack72** [comment]
👍

**Comment by sodre** [comment]
I am investigating if PR #6322  fixes the issue for us as well. If it does then there is no need to use my transformation.

**Comment by stack72** [comment]
Hi @sodre 

Any thoughts on whether we still need this PR?

P.

**Comment by sodre** [comment]
Hi Paul,

I tested one of the fixes that supports '.' and it did not work for me. 

I am without a computer until Sunday night, I'll retest it. 

Patrick

**Comment by stack72** [comment]
No worries :)

**Comment by stack72** [comment]
Hi @sodre 

ping :) Anything you need here? 

P.

**Comment by sodre** [comment]
Hi @stack72,
The code as is works fine for me. My only hesitation on taking the WIP tag out because @jen20 suggested in #2143 that the code in #6322 would fix this issue for everyone. 

Unfortunately, it was not clear to me how the fix translated to what gets written in the terraform config files, or whether it required modifications to the provider code. I never heard back from @jen20 on how he was able to get it to work for his case.

I will leave it up to you.  The worst case is having to undo the change in a future release and deprecate the transformation my code currently implements.

Patrick

**Comment by sodre** [comment]
let me make sure I am not missing any other things from my local branch....

**Comment by sodre** [comment]
@stack72 and @jen20,
I am withdrawing this pull request in favor of #7149 and #7130.

**Pull request closed without merging**
