### PR TITLE
[WIP] AWS ConfigService Resource

### PR DESCRIPTION
**Pull request by stack72**
WIP for the ConfigService

- [x] schema
- [ ] resource
- [ ] acceptance tests
- [ ] documentation

This is based on the http://docs.aws.amazon.com/cli/latest/reference/configservice/index.html#cli-aws-configservice

### CODE REVIEW

**Comment by stack72** [comment]
@radeksimko can you add the WIP label to this please?

**Comment by stack72** [comment]
Closing this for now - will reopen when it's done

**Comment by gawbul** [comment]
Any further progress on this? Or has any development been started on this provider at Hashicorp?

**Comment by hamstah** [comment]
Hi,
Any update on this?
Thanks

**Comment by magnusthorne** [comment]
I need this.

**Comment by gawbul** [comment]
See https://github.com/hashicorp/terraform/pull/5850 now included in Terraform 0.8.7+

**Pull request closed without merging**
