### PR TITLE
Add timeouts for google_container_cluster

### PR DESCRIPTION
**Pull request by sovanesyan**
I haven't run or added an acceptance test yet, can you help me figure out how to setup them?

### CODE REVIEW

**Comment by danawillow** [comment]
Code looks good!

As for acceptance tests, you'll want to add something in https://github.com/hashicorp/terraform/blob/master/builtin/providers/google/resource_container_cluster_test.go. I think adding a new test based on the _basic test, but with a timeout, is the best option.

Here's the command I use to run tests (from the base directory):
```
$ export GOOGLE_CREDENTIALS=$(cat [path-to-keyfile-json])
$ make testacc TEST=./builtin/providers/google GOOGLE_PROJECT=$PROJECT GOOGLE_REGION=$REGION GOOGLE_XPN_HOST_PROJECT=ignore TESTARGS='-run=TestAccContainerCluster_basic'
```
The keyfile json is explained at https://www.terraform.io/docs/providers/google/index.html#authentication-json-file.

If you don't have a project you can use for testing let me know (once you've added the test) and I can run it for you as well.

Hope that helps!

**Comment by stack72** [comment]
Hi @sovanesyan 

I am in the process of migrating this code from this PR to the new google repo. As you can see (below), I have kept your commit in place. I just added a test on top as per @danawillow's request

```
commit 8798346e7011cafc562f9b7deb0cd6d8fdb018c8
Author: stack72 <public@paulstack.co.uk>
Date:   Wed Jun 28 11:34:20 2017 +0300

    Add an acceptance test to show timeouts in container_cluster

commit b2f789ca0a25aefc70397cd68ba4397b6e5de50c
Author: sovanesyan <sovanesyan@gmail.com>
Date:   Wed Jun 28 11:22:31 2017 +0300

    provider/google: Add Timeout support to google_container_cluster

    Migrated from https://github.com/hashicorp/terraform/pull/13203
```

Thanks for the work here

Paul

**Comment by sovanesyan** [comment]
I completely forgot about this issue, sorry for not coming up with a test myself. Thanks!

**Comment by Stono** [comment]
Hey, any idea what version of TF this will be in?

**Comment by danawillow** [comment]
It'll be in version 0.1.2 of the google provider, which should be released very soon.

**Pull request closed without merging**
