### PR TITLE
core: fix provider/close provider race when targeting

### LINKED ISSUE #2495: Templates not working with latest master branch
Hey, I just updated TF to pull in some changes and noticed that all of our templates stopped working.  If I move back to a previous release all is well.  It's been quite a while (a week?) since I updated TF so I don't have any info about which commit this stops working at but for now have reverted back.

      * Error configuring template: connection is shut down
      * Error configuring template: connection is shut down
      * Error configuring aws: connection is shut down

Occasionally I'll get multiple lines the same as above.  Is this an issue with TF or have the templates changed?  I don't see any differences in the documentation.

version: Terraform v0.6.0-dev (c1bb9116ad1899209bc87eae6122b478aee4d839)

### PR DESCRIPTION
**Pull request by phinze**
When targeting prunes out all the resource nodes between a provider and
its close node, there was no dependency to ensure the close happened
after the configure. Needed to add an explicit dependency from the close
to the provider.

fixes #2495

### CODE REVIEW

**Comment by phinze** [comment]
I'll follow up with a similar fix for provisioners

**Comment by mitchellh** [comment]
It'd be interesting to see how this interact with provider aliases. It might work fine, but its still probably worth adding a test case for them.

**Comment by phinze** [comment]
In addition to test outputs needing updates - this breaks the DisableProviderTransformer as well since that's looking for providers without descendents... looking into it...

**Comment by mitchellh** [comment]
LGTM. You're right that that test probably isn't testing anything. I have an idea, going to hijack your branch for a second and see something.

**Comment by phinze** [comment]
Hijack away! :rocket:

**Comment by phinze** [comment]
Okay @mitchellh one more review - I think this is G2G.

**Comment by mitchellh** [comment]
Yep yep LGTM

**Comment by svanharmelen** [comment]
:+1:

**Pull request merged**
