### PR TITLE
provider/template: convert resources to data sources

### PR DESCRIPTION
**Pull request by apparentlymart**
The template resources don't actually need to retain any state, so they are good candidates to be data sources.

### CODE REVIEW

**Comment by apparentlymart** [comment]
@phinze / @jen20: now that the bugs around testing data sources have been resolved this seems to work as expected, so I think it's now ready for review.

**Comment by ColinHebert** [comment]
Fixes #6899

**Comment by jen20** [comment]
LGTM! I'll merge this locally following the rebase and push it up.

**Comment by jen20** [comment]
Merged as 861ac53.

**Pull request closed without merging**
