### PR TITLE
Ignore vpc endpoint routes

### LINKED ISSUE #2063: Terraform panics on calculating diffs for route tables containing S3 VPC endpoint routes.
Running Terraform in planning mode for route tables with S3 VPC endpoint routes result in a panic.

We started seeing consistent panics after configuring S3 VPC endpoints. Investigation showed that routes tables will contain lack a routes that lack DestinationCidrBlock. -They typically include Origin, Stage, GatewayId and DestinationCidrBlock.

Snippet of logging output during panic:

```
build	20-May-2015 06:45:26	Error refreshing state: 21 error(s) occurred:
build	20-May-2015 06:45:26	
build	20-May-2015 06:45:26	* 1 error(s) occurred:
build	20-May-2015 06:45:26	
build	20-May-2015 06:45:26	* unexpected EOF
build	20-May-2015 06:45:26	* connection is shut down
build	20-May-2015 06:45:26	* 1 error(s) occurred:
<SNIP>
build	20-May-2015 06:45:26	
build	20-May-2015 06:45:26	panic: interface conversion: interface is nil, not string
build	20-May-2015 06:45:26	2015/05/20 06:45:25 terraform-provider-aws: 
build	20-May-2015 06:45:26	2015/05/20 06:45:25 terraform-provider-aws: goroutine 275 [running]:
build	20-May-2015 06:45:26	2015/05/20 06:45:25 terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsRouteTableHash(0x86ca80, 0xc20808a5d0, 0x4c0000000040cb89)
build	20-May-2015 06:45:26	2015/05/20 06:45:25 terraform-provider-aws: 	/Users/mitchellh/code/go/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_route_table.go:278 +0xf0
build	20-May-2015 06:45:26	2015/05/20 06:45:25 terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Set).add(0xc20810b780, 0x86ca80, 0xc20808a5d0, 0xc208381760)
build	20-May-2015 06:45:26	2015/05/20 06:45:25 terraform-provider-aws: 	/Users/mitchellh/code/go/src/github.com/hashicorp/terraform/helper/schema/set.go:125 +0x9a
build	20-May-2015 06:45:26	2015/05/20 06:45:25 terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Set).Add(0xc20810b780, 0x86ca80, 0xc20808a5d0)
build	20-May-2015 06:45:26	2015/05/20 06:45:25 terraform-provider-aws: 	/Users/mitchellh/code/go/src/github.com/hashicorp/terraform/helper/schema/set.go:32 +0x3c
build	20-May-2015 06:45:26	2015/05/20 06:45:25 terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsRouteTableRead(0xc2082cf5c0, 0x846900, 0xc208044dc0, 0x0, 0x0)
build	20-May-2015 06:45:26	2015/05/20 06:45:25 terraform-provider-aws: 	/Users/mitchellh/code/go/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_route_table.go:145 +0x7c6
build	20-May-2015 06:45:26	2015/05/20 06:45:25 terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc2080c1680, 0xc2082c30b0, 0x846900, 0xc208044dc0, 0xc2080c74b0, 0x0, 0x0)
```

An S3 VPC endpoint route (from awscli) shows:

```
           "Routes": [
            <SNIP>                    
            {
                    "GatewayId": "vpce-b3cd28da",
                    "Origin": "CreateRoute",
                    "State": "active"
                },
            <SNIP> 
```

### PR DESCRIPTION
**Pull request by ojongerius**
Fixes #2063

### CODE REVIEW

**Comment by radeksimko** [comment]
Thanks for noticing.

I feel we should add a proper support for VPC endpoints, but there's no support in the upstream AWS Go SDK yet.

I will keep asking the AWS support.

**Comment by ojongerius** [comment]
@radeksimko cheers!

Terraform support for S3 VPC endpoints would be amazing, it makes a HUGE difference the amount of traffic flowing through our routers. Entertainingly enough we noticed Cloudformation currently also chokes on route tables containing S3 VPC endpoint routes object.

This patch at least fixes the current situation.

**Comment by gjohnson** [comment]
Looks like it was added upstream this week. Be awesome to have this support.

**Comment by radeksimko** [comment]
@gjohnson Yes, "we ask for it, we get it". :smiley: 

I already started working on EFS which was added in the same commit and unless someone will be quicker, I may start working on VPC endpoints as well after finishing EFS, so far it's open for everyone (it always is though :) ).

**Comment by gjohnson** [comment]
@radeksimko I may have time to add endpoints while your on EFS, ping you on the PR if I get to it.

**Comment by radeksimko** [comment]
@ojongerius Thanks, but @gjohnson came up with slightly cleaner solution to this issue.
We also now support VPC endpoints, so these don't have to be managed outside Terraform.

See #2695 which has been just merged.

**Pull request closed without merging**
