### PR TITLE
provider/aws: Add support for Elastic Search

### PR DESCRIPTION
**Pull request by radeksimko**
Closes https://github.com/hashicorp/terraform/issues/3381

FYI @nickschuch

### Test plan
```
$ make testacc TEST=./builtin/providers/aws TESTARGS='-run=ElasticSearch' 2>~/tf.log
```
```
go generate ./...
TF_ACC=1 go test ./builtin/providers/aws -v -run=ElasticSearch -timeout 90m
=== RUN   TestAccAWSElasticSearchDomain_basic
--- PASS: TestAccAWSElasticSearchDomain_basic (1448.71s)
=== RUN   TestAccAWSElasticSearchDomain_complex
--- PASS: TestAccAWSElasticSearchDomain_complex (1454.23s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	2902.972s
```

### CODE REVIEW

**Comment by pmoust** [comment]
LGTM! Just tested ;) Thanks for this

**Comment by catsby** [comment]
Tests pass and the code looks good :+1:

**Comment by nickschuch** [comment]
Thanks @radeksimko! You rock!

(Worked for me!)

**Comment by gjohnson** [comment]
:+1:

**Pull request merged**
