### PR TITLE
provider/azure: added load balancer support.

### PR DESCRIPTION
**Pull request by aznashwan**

### CODE REVIEW

**Comment by aznashwan** [comment]
@jen20 @phinze this one, I feel, requires quite some attention :smile:

**Comment by jen20** [comment]
:+1: Looks like a reasonably complex resource! Thanks for your work! Similarly to local network gateway, could you consider adding an acceptance test to verify basic functionality, and the resource documentation?

**Comment by phinze** [comment]
Wow yes this is definitely one of the more complicated back-end APIs we've had to convert into a resource! Looks solid at first glance - will wait for the acctests before I review more thoroughly.

In the meantime, I wanted to discuss a resource modeling question. I wonder if we should consider proactively splitting out multiple resources here, to allow, for example, an ELB to be defined in a module and load balancing rules to be attached elsewhere in config.

The config would become much more verbose in the short term, and down the road we could reintroduce nestable config via #2275 once that's done.

If we went down that road, `azurerm_load_balancer` would be reduced to just handling the presence of the top-level resource, and we'd gain:

 * `azurerm_load_balancer_frontend_ip`
 * `azurerm_load_balancer_backend_address_pool`
 * `azurerm_load_balancer_rule`
 * `azurerm_load_balancer_probe`
 * `azurerm_load_balancer_nat_rule` - could select `inbound` / `outbound` with an attribute

Each of these resources would have a `load_balancer_id` reference and interact with their respective subset of the deeply nested parameters. We'd need to add a per-LB mutex to guard against race conditions - there's an implementation of this in `aws_security_group_rule` we could use for that.

So there are obviously downsides to this way:

 * the config is immensely noisier than the nested route
 * the implementation is more complicated and difficult
 * it does not naturally have the ability to manage the full set of "sub-resources", so e.g. Terraform would not detect an extra manually added `probe` as drift

But on the flipside, this is the only way I know of to support configurations where the full set of the load balancer's details are not known in one spot in the config.

/cc @mitchellh - I'm basically using this as an example of a larger more abstract modelling question.

Thoughts are welcome! :grinning:

**Comment by iaingblack** [comment]
This looks great! Sorry for the usual "when will this be implemented" query though... But, i was very happy to see azurerm virtual machines are being supported now (https://github.com/hashicorp/terraform/pull/5514) but just realised I also need load balancer support in AzureRM to send traffic to various VMs in the resource group. Without that ability things get quite tricky with multiple VMs as each windows system created really potentially needs RDP, HTTP/HTTPS and WinRM/Powershell ports opened. Not sure how to handle that elegantly in terraform currently. Unless i'm missing something obvious? Trying hard to fit terraform into my azure workflow but it's not quite there. Terraform much easier to use than native ARM templates from Microsoft in my opinion, so trying to avoid them if I can!

Cheers!
Iain

**Comment by igable** [comment]
@aznashwan do you happen to have a HCL example that works with this PR?

**Comment by buzztroll** [comment]
After many hours of trying to massage the ARM API I agree that @phinze described approach is in the right direction.  At the same time I think that drift is inevitably possible and that it will be difficult (if at all possible) to present the full combination of features possible with multiple ARM LB updates and maintain a good user experience.  Would it make sense for a simple LB resource to be created that could either live along side of a more feature rich one or be enhanced over time to become a feature rich one?

**Comment by jen20** [comment]
@stack72 and I have started working on this, basing it on some later work that was done. We'll open a new pull request later in the week when there is something to report. Thanks for all the work done here!

**Comment by jen20** [comment]
The new pull request for this is #9199.

**Pull request closed without merging**
