### PR TITLE
Add Azure provider

### PR DESCRIPTION
**Pull request by frodenas**
This PR adds a new Terraform provider: [Microsoft Azure](http://azure.microsoft.com/). It provides a single resource: **azure_virtual_machine**. Besides the new provider code, it has acceptance tests for the resource and the corresponding documentation.

It has several **constrains**:
* It only supports creating Linux virtual machines
* It doesn't support updates on the resource
* Doesn't include support for networks/reserved IP address/disks/...
* The hosted/cloud service name must the same as the virtual machine

This PR depends on https://github.com/MSOpenTech/azure-sdk-for-go/pull/8, so it is **NOT** yet merge-able, but I want to gather some feedback in the meantime.

This fixes https://github.com/hashicorp/terraform/issues/238.

### CODE REVIEW

**Comment by keithchambers** [comment]
This PR no longer blocked on https://github.com/MSOpenTech/azure-sdk-for-go/pull/8 (see https://github.com/MSOpenTech/azure-sdk-for-go/pull/18).

Thanks @fordenas !

**Comment by phinze** [comment]
Pulling this down now. Rebases cleanly. Signing up for some Azure right now to verify the acceptance tests. :dancer:

**Comment by phinze** [comment]
Merged in #899 :ok_woman:

**Comment by frodenas** [comment]
Thanks @phinze!

**Comment by keithchambers** [comment]
+1

**Pull request closed without merging**
