### PR TITLE
Update resource_provisioner.go

### LINKED ISSUE #18399: Looks like the habitat provisioner is missing a space
https://github.com/hashicorp/terraform/blob/a50a3839460af999ffe4a4be92f4eaf6b621919b/builtin/provisioners/habitat/resource_provisioner.go#L612

This causes an error when trying to do anything with an on prem depot.

The solution `options += fmt.Sprintf(" --url %s", service.URL)` will fix this.

### PR DESCRIPTION
**Pull request by skylerto**
fix spacing for service url.

resolves #18399

### CODE REVIEW

**Comment by mildwonkey** [comment]
@skylerto Thank you for submitting this pr, and rest assured we know the failure isn't your doing :) 

There's a known issue that @apparentlymart is working on (I believe) - #18380. You might want to watch that issue and we'll try again when it's fixed.

**Comment by skylerto** [comment]
@mildwonkey thanks! I suspect all failing PRs will be blocked until the issue is resolved?

**Comment by mildwonkey** [comment]
@skylerto since this is a very small and reasonable change, I ran the tests locally. This PR is mildwonkey-ci approved. I will merge this now and it will be released with the next terraform release (sorry to say I do not have an idea of when that might be). 

Thank you again for submitting this bugfix!

**Comment by skylerto** [comment]
Just to update: made it into release [0.11.8](https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#0118-august-15-2018).

**Pull request merged**
