### PR TITLE
Gh 2087 consul service resource

### PR DESCRIPTION
**Pull request by maxenglander**
I accidentally deleted PR #3687 - this is (very nearly) the same PR, re-opened.

### CODE REVIEW

**Comment by nanoz** [comment]
Thanks for your work on this ! This is gonna be very useful to register RDS and Elasticache instances :)

**Comment by jrnt30** [comment]
Fixes #2087

**Comment by stack72** [comment]
This LGTM! 

```
% make testacc TEST=./builtin/providers/consul TESTARGS='-run=TestAccConsul'                                 
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
TF_ACC=1 go test ./builtin/providers/consul -v -run=TestAccConsul -timeout 120m
=== RUN   TestAccConsulAgentService_basic
--- PASS: TestAccConsulAgentService_basic (0.04s)
=== RUN   TestAccConsulCatalogEntry_basic
--- PASS: TestAccConsulCatalogEntry_basic (0.03s)
=== RUN   TestAccConsulKeyPrefix_basic
--- PASS: TestAccConsulKeyPrefix_basic (0.09s)
=== RUN   TestAccConsulKeys_basic
--- PASS: TestAccConsulKeys_basic (0.06s)
=== RUN   TestAccConsulNode_basic
--- PASS: TestAccConsulNode_basic (0.02s)
=== RUN   TestAccConsulService_basic
--- PASS: TestAccConsulService_basic (0.02s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/consul	0.272s
```

**Comment by stack72** [comment]
Manually merged as a small change was made to the tests in (47c274f)

**Comment by maxenglander** [comment]
Thanks @stack72!

**Pull request merged**
