### PR TITLE
Backend: add swift workspaces

### LINKED ISSUE #19993: remote/swift: add workspace support
### Current Terraform Version

```
Terraform v0.11.11
```

### Use-cases

Multiple workspaces should be supported by the swift backend.

### Attempted Solutions

I'm using the `terraform init --backend-config container=terraform/workspace1/`, but it is not convenient.

### Proposal

https://github.com/hashicorp/terraform/blob/21d65cfa9a5f081018c4569a8be522ea3744f9a7/backend/remote-state/swift/backend_state.go file should be modified to provide this support.

### PR DESCRIPTION
**Pull request by kayrus**
Resolves #19993 

/cc @jtopjian

### CODE REVIEW

**Comment by jtopjian** [comment]
Just a heads up that there's an older implementation of this here: https://github.com/hashicorp/terraform/pull/20122. I haven't looked too closely at this version to see if there are any significant differences. The other implementation looks like it needs to be rebased. 

If this one has a better implementation, it would be a good idea to add an acceptance test.

**Comment by kayrus** [comment]
Tests are in place. They were skipped, because workspaces were not supported. I had to adjust them to work properly though.

**Comment by jtopjian** [comment]
> Tests are in place.

Indeed they are! My mistake.

**Comment by kayrus** [comment]
When I looked for a swift workspaces issue, I haven't found that PR. It looks like this one also could be forgotten.

**Comment by majewsky** [comment]
I was asked by @kayrus to review this as a Swift expert, and left some remarks on #20127 that probably also apply here.

**Pull request closed without merging**
