### PR TITLE
provider/azurerm: Event Hubs Consumer Groups

### PR DESCRIPTION
**Pull request by tombuildsstuff**
- [x] Create / Update
- [x] Delete
- [x] Acceptance Tests
- [x] Documentation
- [x] Rebase on top of #9889 once it's merged
- [x] Run the Tests

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
Going to upgrade this to v7.0.1 of the SDK to see if the idempotency issue is gone

**Comment by tombuildsstuff** [comment]
Upgraded - will test later on.

**Comment by tombuildsstuff** [comment]
Tests pass - the builds failing for an unrelated reason (ssh timeout):

```
$ TF_ACC=1 go test ./builtin/providers/azurerm -v -run TestAccAzureRMEventHubConsumerGroup -timeout 120m
=== RUN   TestAccAzureRMEventHubConsumerGroup_importBasic
--- PASS: TestAccAzureRMEventHubConsumerGroup_importBasic (360.09s)
=== RUN   TestAccAzureRMEventHubConsumerGroup_importComplete
--- PASS: TestAccAzureRMEventHubConsumerGroup_importComplete (356.24s)
=== RUN   TestAccAzureRMEventHubConsumerGroup_basic
--- PASS: TestAccAzureRMEventHubConsumerGroup_basic (357.92s)
=== RUN   TestAccAzureRMEventHubConsumerGroup_complete
--- PASS: TestAccAzureRMEventHubConsumerGroup_complete (358.76s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/azurerm	1433.027s
```

I could have sworn I'd opened an issue about `eventHubPath` previously - but I can't find it. It's settable in the SDK but not actually returned from the API - so for now I've ignored the field altogether.

Is it worth blocking this PR on that - or shall that become a secondary PR?

cc @stack72

**Comment by stack72** [comment]
This LGTM! Thanks @tombuildsstuff :)

**Comment by tombuildsstuff** [comment]
Opened an issue for the `eventHubPath` field - https://github.com/Azure/azure-rest-api-specs/issues/838

**Pull request merged**
