### PR TITLE
change types and handling for OU

### LINKED ISSUE #13578: tls csr support multiple OU
### Terraform Version
v0.9.2

### Affected Resource(s)
Please list the resources as a list, for example:
- tls_cert_request

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "tls_private_key" "client" {
  algorithm = "RSA"
}
resource "tls_cert_request" "client" {
  key_algorithm   = "RSA"
  private_key_pem = "${tls_private_key.client.private_key_pem}"

  subject = {
    common_name         = "aCN"
    organizational_unit = ["OU1", "OU2", "OU3"]
  }
}
```

### Expected Behavior
generate a csr with a subject with multiple OUs (consistent with an AD directory entry i want a cert for)

### Actual Behavior
`* tls_cert_request.client: subject.0.organizational_unit must be a single value, not a list`

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
idk, unless there's something non-standard about AD (haha what isn't, but i digress)

### PR DESCRIPTION
**Pull request by automaticgiant**
fixes #13578

### CODE REVIEW

**Comment by automaticgiant** [comment]
not good yet. the new OUs don't actually come out in the cert.

**Comment by apparentlymart** [comment]
Thanks for this, @automaticgiant! This seems like a fine idea.

I think in order to do this without a breaking change we'd need to add a new attribute `organizational_units` alongside the existing and continue to support both for a while. The `ConflictsWith` schema attribute can be used to ensure that they are mutually exclusive, so the code doesn't need to deal with weird combinations.

If you don't have time to make that revision, I'm happy to do it on your behalf though I won't be able to jump on it immediately.

**Comment by automaticgiant** [comment]
that's true.
i don't know much about it. this is the most complete tf source contrib i've made so far.
but i can learn.
i'll look at it this afternoon/tonight and see if i can't make that work. an example would be helpful.

**Comment by automaticgiant** [comment]
i think i just found the sauce. https://github.com/hashicorp/terraform/pull/1594/commits/e0df74c863bc8559cfdadfa135d07917a66518fb
let me see what i can do.

**Comment by automaticgiant** [comment]
yeah not sure what's wrong.
gives me:
```
[WARN] /Users/krm158/.go/bin/terraform-provider-tls overrides an internal plugin for tls-provider.
  If you did not expect to see this message you will need to remove the old plugin.
  See https://www.terraform.io/docs/internals/internal-plugins.html
1 error(s) occurred:

* provider.tls: Internal validation of the provider failed! This is always a bug
with the provider itself, and not a user issue. Please report
this bug:

2 error(s) occurred:

* resource tls_self_signed_cert: organizational_unit: ConflictsWith references unknown attribute (organizational_units)
* resource tls_cert_request: organizational_units: ConflictsWith references unknown attribute (organizational_unit)
```

**Comment by apparentlymart** [comment]
@automaticgiant thanks for working on these revisions!

Indeed it looks like #11101 is a blocker for doing what I suggested here. In that case, perhaps we can just treat the singular `organizational_unit` attribute, if present, as an implied extra item in the `organizational_units` list, effectively merging the two into a single list before we use it. (Normally that would be problematic since it would be hard to re-separate those in the `Read` function, but that's not a problem for these resources since they exist entirely within the Terraform state and so there's nothing for them to read.)

**Comment by automaticgiant** [comment]
@apparentlymart idk man. i just moved on to vault pki backend. so we can throw this away, or wait until next version.

**Comment by apparentlymart** [comment]
Thanks for working on this, @automaticgiant.

Unfortunately since we weren't able to get this merged before all of the providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), this can no longer be applied here and so I'm going to close it.

It sounds like you no longer need this functionality due to switching to using Vault's PKI backend. I'm nonetheless sorry that we weren't able to move on this faster to get it in before the providers were split.

**Pull request closed without merging**
