### PR TITLE
Add puppetdb provider

### PR DESCRIPTION
**Pull request by raphink**
This adds a PuppetDB provider with a `puppetdb_node` type. Used as:

```hcl
provider puppetdb {
  url        = "https://puppetdb:8081"
  key        = "certs/my.key"
  cert       = "certs/my.crt"
  ca         = "certs/ca.crt"
}

resource puppetdb_node "foo" {
  certname = "foo.example.com"
}
```

This type will detect if the node is present in the PuppetDB. It exposes various attributes (read-only):

```
id                              = foo.example.com
cached_catalog_status           = 
catalog_environment             = 
catalog_timestamp               = 
certname                        = foo.example.com
deactivated                     = 
expired                         = 
facts_environment               = production
facts_timestamp                 = 2017-03-15T06:10:08.957Z
latest_report_corrective_change = 
latest_report_hash              = c6509b124d494060f667153673eeaddef6abf159
latest_report_status            = failed
report_environment              = production
report_timestamp                = 2017-03-15T06:09:55.894Z
```

and deactivates the node in the PuppetDB when the resource is destroyed.

### CODE REVIEW

**Comment by raphink** [comment]
@stack72 I added SSL support for authentication, which is working fine.

**Comment by raphink** [comment]
@stack72 could you have a look into this PR please?

**Comment by mcanevet** [comment]
@stack72 is there something preventing this PR to be merged? We are using this in production for 2 weeks now and it works well. Thanks

**Comment by raphink** [comment]
@stack72 @radeksimko any news on this?

**Comment by raphink** [comment]
@grubernaut maybe?

**Comment by raphink** [comment]
Fair enough, thank you for the review. I'll rebase it on https://github.com/akira/go-puppetdb, which is the only maintained go lib for PuppetDB, although that will require some contributions to it first.

**Comment by teamterraform** [comment]
Hello, we apologize that this pull request review fell by the wayside. We are actively cleaning up Terraform issues and pull requests, and given Terraform's [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10), we will no longer be accepting pull requests for providers into the core repository. We encourage any potential provider to reach out through the [provider development program](https://www.terraform.io/guides/terraform-provider-development-program.html) to become an official provider. Thank you for your ongoing contributions to our community.

**Pull request closed without merging**
