### PR TITLE
IPv6 Support To Cloudfront

### LINKED ISSUE #9276: AWS CloudFront IPv6 support
AWS [announced support](https://aws.amazon.com/de/blogs/aws/ipv6-support-update-cloudfront-waf-and-s3-transfer-acceleration/) for IPv6 protocol in Amazon CloudFront.

### LINKED ISSUE #10327: Add IPv6 support for AWS Cloufront distribution
Looks like the latest stable version of Terraform doesn't support IPv6 for Cloudfront distribution creation.

It's actually supported by the Go SDK:
https://github.com/aws/aws-sdk-go/blob/master/service/cloudfront/api.go#L4859

### PR DESCRIPTION
**Pull request by optimisticanshul**
/cc @paddyforan @stack72 

Fixes #9276 
Fixes #10327

### CODE REVIEW

**Comment by stack72** [comment]
Hi @optimisticanshul 

Thanks for the addition here - I will get this tested asap. Please can you update the documentation as well?

Thanks

Paul

**Comment by optimisticanshul** [comment]
Sure.

**Comment by optimisticanshul** [comment]
@stack72 Updated docs 👍

**Comment by stack72** [comment]
Hi @optimisticanshul 

The code looks good but the tests don't pass I'm afraid - CloudFront is *REALLY* slow, therefore this happens in the test:

```
=== RUN   TestAccAWSCloudFrontDistribution_IsIPV6EnabledConfig
--- FAIL: TestAccAWSCloudFrontDistribution_IsIPV6EnabledConfig (2418.25s)
	testing.go:329: Error destroying resource! WARNING: Dangling resources
		may exist. The full state and error is shown below.

		Error: Error applying: 1 error(s) occurred:

		* aws_cloudfront_distribution.is_ipv6_enabled: timeout while waiting for state to become 'Deployed' (last state: 'InProgress', timeout: 40m0s)
```

**Comment by optimisticanshul** [comment]
It passed for me not sure what's wrong i will check.

**Comment by optimisticanshul** [comment]
@stack72 
```
anssharma@Ban-1Anssharma-M:~/Code/go/src/github.com/hashicorp/terraform|ipv6-cloudfront
⇒  make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSCloudFrontDistribution_IsIPV6EnabledConfig'
==> Checking that code complies with gofmt requirements...

go generate $(go list ./... | grep -v /terraform/vendor/)
2016/11/25 09:53:52 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSCloudFrontDistribution_IsIPV6EnabledConfig -timeout 120m
=== RUN   TestAccAWSCloudFrontDistribution_IsIPV6EnabledConfig
--- PASS: TestAccAWSCloudFrontDistribution_IsIPV6EnabledConfig (1582.14s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	1589.363s
```

**Comment by stack72** [comment]
Weird, it passes now - maybe my internet connection was *really* bad that day ;)

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSCloudFrontDistribution_IsIPV6EnabledConfig'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/11/30 13:50:41 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSCloudFrontDistribution_IsIPV6EnabledConfig -timeout 120m
=== RUN   TestAccAWSCloudFrontDistribution_IsIPV6EnabledConfig
--- PASS: TestAccAWSCloudFrontDistribution_IsIPV6EnabledConfig (1230.23s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	1230.260s
```

**Pull request merged**
