### PR TITLE
docs: AWS launch configuration

### PR DESCRIPTION
**Pull request by mtchavez**
* Spot instance documentation

Searching for how to implement spot pricing on AWS launch configurations led me to #1339 as there were no docs on how to achieve that. This pull request adds some basic docs on how to do so.

### CODE REVIEW

**Comment by stack72** [comment]
@mtchavez after a PR that was merged already ( #3270 ) - this needs to be rebased

**Comment by mtchavez** [comment]
Rebased. Looks like there was white space in what was previously merged so that is fixed in this pull request now too.

**Comment by stack72** [comment]
:) thanks!

**Comment by catsby** [comment]
Thanks!

**Pull request merged**
