### PR TITLE
website/docs: move type func docs to a useful location

### PR DESCRIPTION
**Pull request by mildwonkey**
It'd be nice if this documentation actually showed up in the website. (thanks to @alisdair for figuring out what i'd done wrong)

### CODE REVIEW

**Comment by alisdair** [comment]
Do we need to add it to [the sidebar file](https://github.com/hashicorp/terraform/blob/main/website/layouts/language.erb) as well? I don't know how to test the website locally at this point.

**Comment by mildwonkey** [comment]
oh yeah that'd help too

**Comment by mildwonkey** [comment]
I swear I've worked on terraform documentation before

**Comment by mildwonkey** [comment]
I lumped `type` in with the `Type Conversion Function` heading, which isn't really right, but nowhere felt more right / less wrong. I'll happily move it if there's a better suggestion.

(I can test the sidebar, from the terraform-website repository, but you can't actually load the function documentation itself from there, just show that the sidebar looks right)

**Review by alisdair — APPROVED** [review]

**Pull request merged**
