### PR TITLE
provider/docker: Add support of custom networks

### LINKED ISSUE #4478: [Docker] Add support for docker network
Docker support the creation of custom networks, terraform should allow the management of those docker networks
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#2-5-networks
https://docs.docker.com/engine/reference/commandline/network_create/
https://docs.docker.com/engine/userguide/networking/dockernetworks/
https://github.com/fsouza/go-dockerclient/blob/master/network.go

### PR DESCRIPTION
**Pull request by ColinHebert**
Fixes #4478

### CODE REVIEW

**Comment by ColinHebert** [comment]
The networks can't be used from terraform quite yet as the connect and disconnect API haven't been implemented in fsouza/go-dockerclient ( seefsouza/go-dockerclient#442 )

**Comment by ColinHebert** [comment]
Upstream issue fixed, I added a commit to the pull request.

**Comment by jen20** [comment]
Thanks @ColinHebert - I'll rerun the build on Travis now the upstream has merged.

**Comment by jen20** [comment]
@ColinHebert - looks like there are legit build failures: https://travis-ci.org/hashicorp/terraform/builds/100197037#L517

**Comment by ColinHebert** [comment]
@jen20 yep they're fixed now.

**Comment by jen20** [comment]
Hi @ColinHebert! I fixed up a merge conflict here and merged this manually. As part of it I fixed up the image tests so that they don't depend on a hash which changes. Thanks for your contribution, and sorry this took us so long to get to.

**Comment by ColinHebert** [comment]
Hey no worries @jen20, thanks for merging that :)

**Pull request merged**
