### PR TITLE
parameterize Omnitruck install script URL

### PR DESCRIPTION
**Pull request by tnguyen14**
This is an attempt to address #6455.

This is my first Go project contribution, so my apologies in advance for the things that I've missed.

There are a few things that still need to be worked on here, including doc changes and test updates. But I wanted to put this forward first to receive any feedback about whether this is the right direction to take to implement this feature.

Any suggestion would be greatly appreciated.

### CODE REVIEW

**Comment by tnguyen14** [comment]
@cgriggs01 could you help me take a look at this?

**Comment by sethvargo** [comment]
This LGTM and seems reasonable. Ping @catsby @paultyng

**Comment by tnguyen14** [comment]
@catsby I updated the docs. As for Windows, instead of `https://omnitruck.chef.io/install.sh`, it constructs the URL as `"http://omnitruck.chef.io/%s/chef/download?p=windows&pv=$machine_os&m=$machine_arch&v=%s"`. 

Because of the substitution, it's a bit trickier.

Do you know if all of the parameters for the provisioner listed here https://www.terraform.io/docs/provisioners/chef.html apply to both windows and linux use cases?

**Comment by abmoham** [comment]
This is great! There's actually a Windows version of the Omnitruck script at http://omnitruck.chef.io/install.ps1

@catsby, no need for the substitution (we've used the Omnitruck (ps1) script successfully across our fleet.

**Comment by tnguyen14** [comment]
@catsby have you had any chance to take a look at this?

**Comment by tnguyen14** [comment]
Could some reviewers help me take a look at this when they get a chance?

**Comment by tnguyen14** [comment]
@catsby do you have any update on this PR?

**Comment by tnguyen14** [comment]
Could someone help me take a look at this?

**Comment by tnguyen14** [comment]
@apparentlymart do you have any thoughts on this?

**Comment by apparentlymart** [comment]
Hi @tnguyen14! Thanks for working on this, and sorry for the long silence here.

For these provisioners that depend on outside services, the Terraform team unfortunately currently does not have a good solution for reviewing them and testing them in-house. For most of them, there is an community contributor who has access to a suitable test environment and reviews proposed changes, but that is unfortunately not currently true for the `chef` provisioner.

However, to allow us to move forward here I'd like to propose a workaround: I assume you've seen this work against chef server in _your_ environment, and indeed the _code_ looks fine to me, so if we can get confirmation from another person with access to a Chef server (perhaps @abmoham?) to also try it and confirm that it works I'd be comfortable moving forward with merging it. We just need to be sure that this will not change behavior for existing users, which _looks_ to be true because of the `Default` value but I'd like to confirm it.

Sorry for this strange situation. We are intending to refine the development process for the provisioners in the future to make this less awkward -- similar to providers -- but with the relatively-small number of them unfortunately priorities have kept us working elsewhere for the moment.

**Comment by tnguyen14** [comment]
@apparentlymart do you have any guidance on how to test this version of terraform?

Also, I could create a PR against this feature branch with the change for the Windows URL, as suggested by @abmoham, if that is desired.

**Comment by tnguyen14** [comment]
Is there any update to this?

**Comment by paultyng** [comment]
@tnguyen14 we are in the final alpha/beta passes on 0.12, so you probably won't get any follow-up until that is out the door. This repo is mostly locked down except fixes to issues found in the 0.12 alpha.

**Comment by odiosdado** [comment]
Is there any update on this? We would also like to leverage this new feature.

**Comment by pkolyvas** [comment]
@tnguyen14 @odiosdado In [mid-September 2020](https://discuss.hashicorp.com/t/notice-terraform-to-begin-deprecation-of-vendor-tool-specific-provisioners-starting-in-terraform-0-13-4/13997) we announced we'd be deprecating tool-specific provisioners. We added a deprecation notice for tool-specific (vendor or 3rd-party) provisioners in `0.13.4`. 

On a practical level this means we will no longer be reviewing or merging PRs for these built-in plugins. 

I understand that ignoring PRs and then deprecating the same features is a terrible community experience. We’re working hard to clean up our community interaction, and get better about being open and frank around our intentions. To that end, I’m tackling each one individually.

The long term strategy here is less clear than we'd like, but for the time being I'd encourage the community of Terraform provisioner users and developers (who might also be reading this) to follow in the footsteps of the [ansible provisioner](https://github.com/radekg/terraform-provisioner-ansible).

Creating provisioner plugins and installing provisioner plugins manually is more involved. Our hope here is that the ability to improve, fix and repair these tools without us blocking their development, much like providers, will help make a strong case for what's next. 

In the long term, there are also some technical hurdles to cross. The Terraform plugin SDK does not support provisioners and so moving beyond the deprecation will require something more concrete plans. We’d like to base those plans, in part, on the feedback we receive. I think it’s also important to highlight that we have no plans to remove the generic provisioners or the pluggable functionality during Terraform's 1.0 lifecycle.

We didn't make this decision lightly, and removing or no longer supporting features is not ideal for anyone who uses and depends on them. To that end, my door is always open. I'd invite you, or anyone interested, to write me or schedule some time with me to talk about these changes moving forward.

**Pull request closed without merging**
