### PR TITLE
ultradns_tcpool: add

### PR DESCRIPTION
**Pull request by josephholsten**
This patchset is best reviewed a patch at a time, especially because it includes a large update to `github.com/Ensighten/udnssdk`. Inside, you'll find
- a few straightforward cleanup patches,
- the vendor update,
- a squashed implementation+test patch and
- a doc patch.

### CODE REVIEW

**Comment by stack72** [comment]
Hi @josephholsten 

any chance you can rebase this? I think this was created before we switched to govendor :)

P.

**Comment by stack72** [comment]
@josephholsten 

I am going to close this out. There hasn't been any activity on this since May 10th - this was well before we moved to govendor - the PR doesn't merge cleanly now. If you still feel this is requried functionality, please can you reopen another PR? :)

Thanks

Paul

**Comment by josephholsten** [comment]
@stack72 that's great. entertainingly, this'll be actually ready next week. I'll put it in a new PR.

**Comment by stack72** [comment]
@josephholsten - let's reopen this one then :) If you feel it's getting closer to being ready then you will be able to rebase in this PR

**Comment by mitchellh** [comment]
I'll close this until you resubmit @josephholsten :) Thanks!

**Comment by josephholsten** [comment]
@mitchelh thanks, forgot to reference this from #9788

**Pull request closed without merging**
