### PR TITLE
Add an `aws_regions` data source

### PR DESCRIPTION
**Pull request by joshuaspence**
Adds a data source source for querying all AWS regions.

### CODE REVIEW

**Comment by apparentlymart** [comment]
Hi @joshuaspence! Thanks for working on this.

I have some general contextual questions about this:
* Did you have a concrete use-case in mind for this, or was this just in the interest of API completeness? These plural data sources tend to be pretty awkward to use and so we've been trying to only implement the ones that are genuinely useful in the short term, expecting that we might change our approach in future in order to make multi-object data sources a little more "ergonomic" and would rather keep the amount of deprecation that would cause to a minimum.
* Outside of regions AWS has the idea of "partitions", where GovCloud and AWS China are examples of separate partitions compared to the main partition where us-east-1 lives. Does the result of this data source change depending on the partition of the region the API request is made in?

**Comment by radeksimko** [comment]
+1 for @apparentlymart 's question about use-case.

I always try to discourage people from spanning across multiple regions, because they often don't see the big picture. IMO vast majority of users should keep 1 `terraform apply` scoped to a single region.

Why?

1. Latency
2. Availability - If a single `terraform apply` manages 2+ regions and one of those goes down what is the expected outcome? Is your whole infrastructure going to be broken because of 1 region? Then it kind of defeats the purpose of multiple regions. In which region do you store the tfstate?

To be clear there are people who do manage cross-region infrastructure and do it well, but it's a tough discipline and I'm not sure that even such users would ever want to iterate over a list of regions, but I might be wrong.

**Comment by joshuaspence** [comment]
Sorry about the delayed response. The use case here is for sharing instance-store AMIs across all available AWS regions. Basically, we do something like this at the moment:

```
variable "ami_regions" {
  type        = "list"
  default     = ["ap-southeast-1", "ap-southeast-2", "us-east-1", "us-west-1", "us-west-2"]
  description = "AWS regions in which instance-store-backed AMIs are created."
}

resource "aws_s3_bucket" "ami" {
  bucket = "${var.s3_bucket_prefix}-ami"

  versioning {
    enabled = true
  }
}

data "aws_iam_policy_document" "packer" {
  statement {
    actions = [
      "ec2:AttachVolume",
      "ec2:CopyImage",
      "ec2:CreateImage",
      "ec2:CreateSnapshot",
      "ec2:CreateTags",
      "ec2:CreateVolume",
      "ec2:DeleteSnapshot",
      "ec2:DeleteVolume",
      "ec2:DescribeImages",
      "ec2:DescribeInstances",
      "ec2:DescribeSecurityGroups",
      "ec2:DescribeSnapshots",
      "ec2:DescribeSubnets",
      "ec2:DescribeVolumes",
      "ec2:DetachVolume",
      "ec2:ModifyImageAttribute",
      "ec2:RegisterImage",
      "ec2:RunInstances",
      "ec2:StopInstances",
      "ec2:TerminateInstances",
      "iam:PassRole",
      "s3:ListAllMyBuckets",
    ]

    resources = ["*"]
  }

  statement {
    actions = [
      "s3:CreateBucket",
      "s3:GetBucketAcl",
    ]

    resources = ["${formatlist("arn:aws:s3:::amis-for-%s-in-%s-*", var.aws_account_id, var.ami_regions)}"]
  }

  statement {
    actions   = ["s3:GetBucketLocation"]
    resources = ["${aws_s3_bucket.ami.arn}"]
  }

  statement {
    actions = [
      "s3:GetObject",
      "s3:PutObject",
      "s3:PutObjectAcl",
      "s3:PutObjectVersionAcl",
    ]

    resources = ["${aws_s3_bucket.ami.arn}/*"]
  }

  statement {
    actions = [
      "s3:PutObject",
      "s3:PutObjectAcl",
    ]

    resources = ["${formatlist("arn:aws:s3:::amis-for-%s-in-%s-*/*", var.aws_account_id, var.ami_regions)}"]
  }
}
```

My intention is to replace the `ami_regions` variable with the `aws_regions` data source.

**Comment by apparentlymart** [comment]
Hello @joshuaspence, and thanks for working on this!

As part of the the Terraform 0.10 release earlier this year, all of the Terraform providers were moved to their own repositories in [the terraform-providers GitHub organization](https://github.com/terraform-providers), and removed from the Terraform Core repository.

Unfortunately due to the fact that new issues and pull requests are being opened constantly, it was not possible for the various provider maintainers to merge all outstanding pull requests before this split, and there is no automatic way to migrate a pull request to a new repository.

As a result, this pull request can sadly no longer be applied as-is, and so I'm going to close it.

If you or someone else has the time and motivation to apply the same changes to [the `aws` provider repository](https://github.com/terraform-providers/terraform-provider-aws) and open a new PR there, the maintainers of that provider should be able to review and merge it.

Thanks again for working on this, and sorry it was not able to be merged before the provider repository changes.

**Pull request closed without merging**
