### PR TITLE
Add MemoryReservation To ECS Container Definition

### PR DESCRIPTION
**Pull request by optimisticanshul**
Adds #8389

### CODE REVIEW

**Comment by stack72** [comment]
Hi @optimisticanshul 

Thanks for the PR here - this isn't correct I'm afraid. This is a value that can be set by the user http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#standard_container_definition_params

Paul

**Comment by optimisticanshul** [comment]
Sorry but i didn't get you, that's what it does if in definition
memoryReservation is set, this set value to that value.

**Comment by stack72** [comment]
Hi @optimisticanshul 

you haven't given the user any option to set the value via Terraform. You have made it computed: true which means that it is only set when a value comes back from the EC2 API

Paul

**Comment by optimisticanshul** [comment]
@stack72 sorry got it now. Thanks.

**Comment by stack72** [comment]
@optimisticanshul do you want me to take this PR over or are you in a situation of being able to work on it?

**Comment by optimisticanshul** [comment]
Hi Paul, sorry i am out till Saturday can't work on this atm.

**Comment by stack72** [comment]
Hi @optimisticanshul 

I take that back - the work you have done here is correct :) I have renamed the variable to stick with our start naming convention. Other than that - I will be merging this shortly!

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSEcsDataSource_'                                            ✹
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/08/25 17:57:34 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSEcsDataSource_ -timeout 120m
=== RUN   TestAccAWSEcsDataSource_ecsContainerDefinition
--- PASS: TestAccAWSEcsDataSource_ecsContainerDefinition (121.18s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	121.201s
```

Changes made in 0087068a0e7f2956010634649e767c9ddab31862

**Pull request merged**
