### PR TITLE
Fail silently when account validation fails while from instance profile 

### PR DESCRIPTION
**Pull request by sarguru**
As far as I know, cross account IAM instance profiles are not possible, so when iam.GetUser() fails for non-User credentials , its better that it fails silently and prints the warning instead of halting the entire run.
This is similar to #2959. If there are better ways of handling (or if its better to explicitly specify) this that would be great aws well. Thanks !

### CODE REVIEW

**Comment by bobtfish** [comment]
:+1: we definitely want this to make instance profiles work correctly

**Comment by apparentlymart** [comment]
The logic seems reasonable. :+1:

It'd be awesome if you could run your code through ``go fmt`` to make it conform to the code style used elsewhere in Terraform.

**Comment by sarguru** [comment]
thanks @apparentlymart . Done :+1:

**Comment by phinze** [comment]
LGTM

**Pull request merged**
