### PR TITLE
provider:fastly - gcs_logging - Optionally use env variable for credentials

### PR DESCRIPTION
**Pull request by kbvincent**

### CODE REVIEW

**Comment by kbvincent** [comment]
@grubernaut If this is good as is, any idea when this would be able to be merged?  Its affecting our ability to obscure credentials in our terraform pipeline.  Would love to get it rolled out.

**Comment by grubernaut** [comment]
@kbvincent I didn't review the PR, simply labeled it. I can review it later this week, or ping another maintainer to review it here shortly.

**Comment by kbvincent** [comment]
@grubernaut Thank you sir!

**Comment by catsby** [comment]
Hey there – I've manually moved this to https://github.com/terraform-providers/terraform-provider-fastly/pull/15

**Pull request closed without merging**
