### PR TITLE
Moving octet-stream to json for remote http backend

### PR DESCRIPTION
**Pull request by anubhavmishra**
Saw the discussion on https://groups.google.com/forum/#!searchin/terraform-tool/http$20remote/terraform-tool/Uy1EDGQTiGg/ckGy0wUMCwAJ.

### CODE REVIEW

**Comment by phinze** [comment]
LGTM, thanks @anubhavmishra!

**Comment by phinze** [comment]
(Just trying to work out the backwards compatibility story here and will merge once that's sorted.)

**Comment by phinze** [comment]
(Decided to just mention it in the changelog notes in case it trips anybody up.)

**Comment by anubhavmishra** [comment]
Thanks @phinze!

**Pull request merged**
