### PR TITLE
ignition: internal cache moved to global, instead per provider instance

### PR DESCRIPTION
**Pull request by mcuadros**
This is fixing a related issue to  https://github.com/hashicorp/terraform/issues/11518, was tested again several complex configurations as described in the issue.

/cc @alexsomesan

### CODE REVIEW

**Comment by alexsomesan** [comment]
I can confirm that this change solves the problem I reported under #11518 

I've tested with a terraform binary that I built from this branch.
It was able to successfully build the ignition templates we've been having issues with (module code [here](https://github.com/alexsomesan/tectonic-installer/tree/tf09-ignition-datasource/modules/aws/ignition) and module invocation [here](https://github.com/alexsomesan/tectonic-installer/blob/tf09-ignition-datasource/platforms/aws/main.tf#L75-L89)).

**Comment by mcuadros** [comment]
@tombuildsstuff sorry but this is a fix not an enhancement.

**Comment by mcuadros** [comment]
@stack72

**Comment by grubernaut** [comment]
```
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/04/25 17:16:48 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/ignition -v  -timeout 120m
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestValidateUnit
--- PASS: TestValidateUnit (0.00s)
=== RUN   TestIngnitionFileReplace
--- PASS: TestIngnitionFileReplace (0.02s)
=== RUN   TestIngnitionFileAppend
--- PASS: TestIngnitionFileAppend (0.02s)
=== RUN   TestIngnitionDisk
--- PASS: TestIngnitionDisk (0.03s)
=== RUN   TestIngnitionDiskResource
--- PASS: TestIngnitionDiskResource (0.02s)
=== RUN   TestIngnitionFile
--- PASS: TestIngnitionFile (0.03s)
=== RUN   TestIngnitionFilesystem
--- PASS: TestIngnitionFilesystem (0.05s)
=== RUN   TestIngnitionFilesystemMissingCreate
--- PASS: TestIngnitionFilesystemMissingCreate (0.00s)
=== RUN   TestIngnitionGroup
--- PASS: TestIngnitionGroup (0.03s)
=== RUN   TestIngnitionNetworkdUnit
--- PASS: TestIngnitionNetworkdUnit (0.02s)
=== RUN   TestIngnitionRaid
--- PASS: TestIngnitionRaid (0.03s)
=== RUN   TestIngnitionSystemdUnit
--- PASS: TestIngnitionSystemdUnit (0.03s)
=== RUN   TestIngnitionSystemdUnitEmptyContentWithDropIn
--- PASS: TestIngnitionSystemdUnitEmptyContentWithDropIn (0.03s)
=== RUN   TestIgnitionSystemdUnit_emptyContent
--- PASS: TestIgnitionSystemdUnit_emptyContent (0.02s)
=== RUN   TestIngnitionUser
--- PASS: TestIngnitionUser (0.04s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/ignition       0.395s
```

**Pull request merged**
