### PR TITLE
Add the symmetric difference function, so given a number of sets, I c…

### PR DESCRIPTION
**Pull request by jjshoe**
…an get back only unqiue items

Solves for #16044

### CODE REVIEW

**Comment by apparentlymart** [comment]
Hi @jjshoe! Thanks for working on this and sorry for the slow response.

I've pushed a new version of your change after resolving the conflicts that appeared with `master` in the meantime. I also tweaked the documentation slightly to connect with the other set functions as Related Functions and some minor tweaks to the wording.

In the process of testing this I noticed that the upstream `cty` library, from which we're taking this function, has a bug: its `SetSymmetricDifferenceFunc` is actually implementing `SetSubtractFunc`, and thus producing the wrong answer. I've opened zclconf/go-cty#27 for that, but I've run out of time for now so I won't be able to make an upstream fix for that, and sadly that upstream fix will block us from merging this PR. If you or somebody else is interested in taking on the `go-cty` fix then I'd love to review a PR over in that repository.

We also sadly won't be able to merge this until you go through the CLA signing step described by @hashicorp-cla above. If that process is giving you some trouble please let me know and I will investigate.

Thanks again!

**Comment by jjshoe** [comment]
@apparentlymart If I don't complete the CLA then if effectively blocks this feature from ever being added, as I can claim copyright, correct? What's wrong with the license that terraform uses that requires a cla?

Side note: I don't sign cla's. Unless you're willing to pay for my lawyer.

**Comment by apparentlymart** [comment]
Thanks for letting us know, @jjshoe. In that case, I will close this out.

You can find information in the link that @hashicorp-cla posted above about why HashiCorp requires CLA agreement for contributions.

Thanks again for working on this!

**Comment by jjshoe** [comment]
@apparentlymart in this case I maintain my copyright, and any use, full or in partial, of the above code, is not permitted.

**Pull request closed without merging**
